### ISSUE TITLE
176-7，176-8，177-1更新订阅会失败，导致服务暂停，用175-5版本更新同样的订阅就正常

### ISSUE THREAD

**Issue by jackberry** [fw876/helloworld#10]
176-7，176-8，177-1更新订阅会失败，导致服务暂停，用175-5版本更新同样的订阅就正常

**Comment by iamggs** [comment]
截止现在，最新版本不就是176-7么？你的176-8和177-1哪儿来的？我这儿176-7订阅更新正常。
```
PKG_NAME:=luci-app-ssr-plus
PKG_VERSION:=176
PKG_RELEASE:=7
```

**Comment by coolsnowwolf** [comment]
你可能用的是其他人的预览版本了

**Comment by norikohxb** [comment]
哈哈，lean大跑到这边来回复了，我还担心你被友好的请过去喝茶所以把ssr切割出来呢。还好

**Comment by norikohxb** [comment]
lean大你的youtube是交会员的吗，这个youtube的屏蔽广告没有办法把youtube的中间的广告一并去掉吗？我现在用的是youtube vanced。如果能在路由器集成就太好了

**Comment by norikohxb** [comment]
> 176-7，176-8，177-1更新订阅会失败，导致服务暂停，用175-5版本更新同样的订阅就正常

jackberry，请教你一下，这个176-7， 177-1 ，175-5是去哪里看到的版本号？

**Comment by int2e** [comment]
我也遇到了，编译的4月12号的仓库源码。

**Comment by jackberry** [comment]
> jackberry，请教你一下，这个176-7， 177-1 ，175-5是去哪里看到的版本号？

软件包-已安装软件


> 你可能用的是其他人的预览版本了

176-8，177-1是预览版，176-7不是

**Comment by tty228** [comment]
ssh
`/usr/bin/lua /usr/share/shadowsocksr/subscribe.lua`
查看报错

**Comment by int2e** [comment]
恢复出厂设置以后，重新配好现在不会掉进程了，原先是旧版本升级保留配置的。

**Comment by fw876** [comment]
预览版不做技术支持
