### ISSUE TITLE
游戏模式UDP看来又又又不行了，类型SSR，已经破案请关闭ISSUES！！

### ISSUE THREAD

**Issue by chobitsos** [fw876/helloworld#1000]
找了一晚上 ，都没找出问题!
系统日志里面也没看出问题
[系统日志](https://github.com/fw876/helloworld/files/9797533/syslog.log)
[固件版本](https://github.com/coolsnowwolf/lede/commit/b1b6cd41bb9d4f63ab2870177cbaf5031d41aea5)
[hello版本](https://github.com/fw876/helloworld/commit/80bc9ebd7a72c32d00d8c0f5998c074a046f5498)
编译插件
1. helloworld
2. KMS
3. miniupnp
4. turboacc

client配置
![client配置](https://user-images.githubusercontent.com/18194327/196106271-25f78f29-cc26-4335-9b05-3e91668671c6.jpg)

status检查
![status检查](https://user-images.githubusercontent.com/18194327/196106315-b8cda1b4-fc72-426e-ac9c-49f7fd9e76c1.jpg)

已破案是[固件版本](https://github.com/coolsnowwolf/lede/commit/b1b6cd41bb9d4f63ab2870177cbaf5031d41aea5)的问题
已经更换MTK驱动之前的R21即可解决

**Comment by chobitsos** [comment]
服务端也没看见有UDP包过来

**Comment by chobitsos** [comment]
检查iptables的mangle表里面也没有数据通过，貌似只有TCP OVE UDP的通过了
![屏幕截图 2022-10-17 174652](https://user-images.githubusercontent.com/18194327/196146816-bd77eca4-5796-46fd-bb29-c88987671f67.jpg)

**Comment by chobitsos** [comment]
破案了，是隔壁系统问题，换了R21没问题

**Comment by Cathgao** [comment]
自己关

**Comment by wuzhuang123** [comment]
> 破案了，是隔壁系统问题，换了R21没问题

啊， 我折腾好几天以为深信服搞鬼，尝试刷回备份就好了。
