### ISSUE TITLE
ss协议，ssrp+程序重启之后，原先运行的sip003插件没有被kill，而是重新启动了一份

### ISSUE THREAD

**Issue by qwerttvv** [fw876/helloworld#1004]
ss协议用自定义插件，主程序关了，插件没kill。或者主程序重启，旧的放着，然后新启一个插件进程，这样下去，内存早晚扛不住的，尤其小内存硬路由openwrt，点几次“保存&应用”，机器一会儿就完蛋了

**Comment by 1715173329** [comment]
Check if it works for you: https://github.com/fw876/helloworld/commit/d9ed8f18fcd122ce3039f35c189e8fe3be215f20

**Comment by qwerttvv** [comment]
> Check if it works for you: [d9ed8f1](https://github.com/fw876/helloworld/commit/d9ed8f18fcd122ce3039f35c189e8fe3be215f20)

多谢大佬，我感觉应该行

不过我晚上等回去我实际试一下，试完了会回来反馈的，多谢

**Comment by qwerttvv** [comment]
> Check if it works for you: [d9ed8f1](https://github.com/fw876/helloworld/commit/d9ed8f18fcd122ce3039f35c189e8fe3be215f20)

https://raw.githubusercontent.com/fw876/helloworld/d9ed8f18fcd122ce3039f35c189e8fe3be215f20/luci-app-ssr-plus/root/etc/init.d/shadowsocksr

改这个之后，点“保存&应用”，程序起不来了……
Wed Oct 26 21:54:37 2022 user.notice shadowsocksr: ssrplus redir tcp error.restart!
然后就是插件的进程还在，还是之前执行时候的

**Comment by qwerttvv** [comment]
自定义的第三方插件，旧的没结束，新的又起来了，刚刚路由死机了…

我先照猫画虎的改了原来的891行
killall -q -9 v2ray-plugin obfs-local xray-plugin
在这里硬写了我用的第三方插件的名字，临时解决了问题了

更好的方式，还是靠大佬搞。。我可以积极配合测试

@1715173329

**Comment by 1715173329** [comment]
我之前已经说过，只有你自己知道你究竟使用了什么插件，程序难以判断。
把第 896 行的 & 去掉再试试。

**Comment by qwerttvv** [comment]
> 我之前已经说过，只有你自己知道你究竟使用了什么插件，程序难以判断。 把第 896 行的 & 去掉再试试。

这回行了，感谢大佬！
