### ISSUE TITLE
能否在luci-ui选择xtls时加入uTLS指纹伪造和alpn选择嘛？

### ISSUE THREAD

**Issue by GreatMichaelLee** [fw876/helloworld#1006]
如题，最新的xray内核支持了h2的uTLS指纹伪造，但好像luci ui在选择xtls是不能界面配置，只有选tls才有，这个是指纹伪造只支持tls不支持xtls吗？如果xtls也支持能否UI适配一下配置呢

**Comment by GreatMichaelLee** [comment]
最近xray core更新了1.6.2 增加了一个流控xtls-rprx-vision，好像只能在tls/tls setting下用，ssr luci界面配置还没有适配，麻烦大佬到时候一起改了吧。

**Comment by GreatMichaelLee** [comment]
1.6.3 xray-core已出，麻烦大佬失陪一下luci界面和配置哈，多谢，1.6.3应该是比较NB的了。除了握手包用TinT, 其他都裸奔，减少了端的解密负担和提高了带宽利用率，也减少了特征。希望尽快更新啊。谢谢 @fw876 @coolsnowwolf

**Comment by 1715173329** [comment]
19ae664cd9c615a5117a78ab1c2a6ad2a289541a
