### ISSUE TITLE
启用ChinaDNS-ng后，节点无法连接

### ISSUE THREAD

**Issue by leochien0102** [fw876/helloworld#1007]
节点为域名形式，据测试，在开启ChinaDNS-ng时，国外域名DNS只有选择114的OverSea Mode DNS才能正常解析节点，其它诸如Google/Cloudflare/OpenDNS这些，都不行。

见附图，第一次nslookup为开启ChinaDNS-NG，第二次为禁用。两次的国外域名DNS皆为默认的8.8.4.4。PS：国外域名DNS使用114的OverSea Mode DNS结果同第二次。
![ChinaDNS-ng](https://user-images.githubusercontent.com/3915276/198187599-86e6eae2-9c73-4f1f-af7b-2bc21fc24367.png)

**Comment by lgh200** [comment]
同样问题，不开启ChinaDNS-ng，是正常的

**Comment by 1715173329** [comment]
需要让转发规则在核心启动之后执行，最近看看。
此外 v2ray 系节点不必开启 chinadns-ng，确保你的 DNS 不会返回保留结果即可。

**Comment by chobitsos** [comment]
> 需要让转发规则在核心启动之后执行，最近看看。 此外 v2ray 系节点不必开启 chinadns-ng，确保你的 DNS 不会返回保留结果即可。

ChinaDNS-ng这个插件是ChinaDNS魔改的，我看了代码魔改的还行
其实ChinaDNS这个插件是很不错的，就是不够稳定，代码写的没问题，就是不知道为何跑的时间长了，DNS会leak，虽说不是经常发生，偶尔抽一下就很蛋疼！另外不知道为啥代码被撤回了，我估计是节点解析问题，或者时不时dnsleak问题，目前还没有解决办法，看下可以解决部分的话重新pr一次吧

**Comment by 1715173329** [comment]
chinadns-ng 确实是在节点启动之后才运行的，理论上不会出现这样的问题，除非 nslookup 使用了过长的时间。

**Comment by 1715173329** [comment]
anyway，目前没有特别好的办法解决，或许可以写 hosts 强制绑定，不知道 passwall 那边是怎么解决这个问题的。

**Comment by chobitsos** [comment]
> asswall 那

我没用过passwall，主要是个人觉得有点臃肿， 太多用不上的功能，没办法跑在低端机器上
我觉得可以参考一下他的代码看看，不知道他们有无开源

**Comment by 1715173329** [comment]
@leochien0102 this should be resovled by dfd40709371a32930e0b413b899e388bbb7814cc, can you try if it works for you?

**Comment by leochien0102** [comment]
> @leochien0102 this should be resovled by [dfd4070](https://github.com/fw876/helloworld/commit/dfd40709371a32930e0b413b899e388bbb7814cc), can you try if it works for you?

切换Branch重新编译，目前使用下来没啥问题
