### ISSUE TITLE
手动添加 服务器 下列格式的不能被正确识别

### ISSUE THREAD

**Issue by lsq726** [fw876/helloworld#1008]
服务器节点  新增  导入配置信息粘贴如下格式  不能正确识别.

trojan://password@name.server.com:443/?sni=name.server.com#server1

ss格式的正确识别了

**Comment by 1715173329** [comment]
具体什么地方不能正确识别？

**Comment by lsq726** [comment]
> 

就是不能正确识别 服务器

**Comment by 1715173329** [comment]
之前根据你给的链接测试并没有什么问题，不过现在已经切换使用标准解析方案，兼容性会更好。

**Comment by lsq726** [comment]
> 之前根据你给的链接测试并没有什么问题，不过现在已经切换使用标准解析方案，兼容性会更好。
感谢，效率。好高🤝
