### ISSUE TITLE
[Feature Request]为TLS添加流控选项

### ISSUE THREAD

**Issue by ShoukakuChuuCC** [fw876/helloworld#1018]
Xray新流控streamSettings和security需要使用tls字段而不是xtls
https://github.com/XTLS/Xray-core/pull/1235

**Comment by ShoukakuChuuCC** [comment]
目前需要勾选XTLS才会出现流控选项 这样会不兼容新流控xtls-rprx-vision

**Comment by GreatMichaelLee** [comment]
> 目前需要勾选XTLS才会出现流控选项 这样会不兼容新流控xtls-rprx-vision

反正我目前是自己改/usr/share/shadowsocksr/gen_config.lua里面，加点小手脚，配合/etc/config/shadowsocksr给最终生成了这个1.6.2所要的/var/etc/ssrplus/tcp-only-ssr-retcp.json

**Comment by 1715173329** [comment]
2d94cabb048f98414057a24ff4afff024e720152

**Comment by Saxon-Sun** [comment]
> [9be84f1](https://github.com/fw876/helloworld/commit/9be84f11841d8eb09e245b26621824873c8dc130)
TLS流控选项还不能够通过URL导入配置进行自动选择
