### ISSUE TITLE
openwrt 22.03 ShadowSocksR Plus+ 苹果12PRO MAX手机端youtube不能播放

### ISSUE THREAD

**Issue by syscca** [fw876/helloworld#1020]
openwrt 22.03 ShadowSocksR Plus+ 协议TROJAN使用阿里云香港节点，
苹果12PRO MAX手机端youtube可以打开不能播放，提示“出错了点按即可重试”，电脑端没有问题。
尝试加入强制走代理的域名，
googleapis.cn
googleapis.com
services.googleapis.cn
services.googleapis.com
xn--ngstr-lra8j.com
1e100.net
hkg07s48-in-f3.1e100.net
hkg07s40-in-f3.1e100.net
gstatic.com
没有效果。

**Comment by 1715173329** [comment]
fw4 is unsupported currently.

**Comment by syscca** [comment]
访问控制加入
强制走代理的WAN IP
142.250.0.0/16
185.199.0.0/16
解决

**Comment by 1715173329** [comment]
官方 22.03 dnsmasq 已经默认不集成 ipset 支持了，需要编译时手动启用。
