### ISSUE TITLE
请求增加 Xray-core 1.6.2版本增加的新流控选项 xtls-rprx-vision

### ISSUE THREAD

**Issue by chika0801** [fw876/helloworld#1021]
更新日志 https://github.com/XTLS/Xray-core/releases

https://github.com/XTLS/Xray-core/discussions/1295

在网页中的流控选项中增加 xtls-rprx-vision xtls-rprx-vision-udp443 选项

配置文件是
"streamSettings" 内须为 "security":"tls"+"tlsSettings"

**Comment by GreatMichaelLee** [comment]
1.6.3 xray-core已出，麻烦大佬失陪一下luci界面和配置哈，多谢，1.6.3应该是比较NB的了。除了握手包用TinT, 其他都裸奔，减少了端的解密负担和提高了带宽利用率，也减少了特征。希望尽快更新啊。谢谢 @fw876 @coolsnowwolf

**Comment by 1715173329** [comment]
duplicate #1018

**Comment by loydcheung** [comment]
好像vision确实能快些，但是在我这好像不太稳定，有时候会连不上，不知道大神们的情况如何。

**Comment by GreatMichaelLee** [comment]
> 好像vision确实能快些，但是在我这好像不太稳定，有时候会连不上，不知道大神们的情况如何。

切包据说还有bug，作者在修

**Comment by loydcheung** [comment]
> > 好像vision确实能快些，但是在我这好像不太稳定，有时候会连不上，不知道大神们的情况如何。
> 
> 
> 
> 切包据说还有bug，作者在修

我已经升级到1.6.4了，好像时不时还是会断，不知道是不是我自己设置的问题。我是用all in one的带fallback的模版，改了新的vision
