### ISSUE TITLE
脸书和推正常打开，谷歌打开慢

### ISSUE THREAD

**Issue by Herakleitus** [fw876/helloworld#1022]
背景
Openwrt:  shadowsocksr-libev client with v2ray plugin ====（https）====Cloudflare CDN====（https）====Nginx反向代理至shadowsocks-libev server with v2ray plugin
使用shadowsock-windows客户端、mac客户端及ShadowRocket稳定都正常，刚刚切到shadowsocksr-libev with v2ray plugin。

问题：
Windows / Mac 刚开机/唤醒的时候， 脸书和Twitter打开很快，但是google会失败几次，过一会才能正常。

家庭环境：
光猫——UBNT ER-X——华为H6 AC——华为H6 AP
其中UBNT装Openwrt 21.02， 192.168.1.1 pppoe拨号 
AC  192.168.2.1 静态IP192.168.1.100链接到UBNT 配置网关192.168.1.1, 首选DNS 192.168.1.1

终端设备通过AP 有线/无线上网

配置截图：
<img width="551" alt="1667711542040" src="https://user-images.githubusercontent.com/102005803/200155317-56365cc2-57f4-49f9-b85c-049e2ec32c82.png">
<img width="722" alt="1667711571847" src="https://user-images.githubusercontent.com/102005803/200155323-84ae350f-1481-4528-9151-c82186ebaa29.png">
服务器节点配置：
<img width="776" alt="1667711659124" src="https://user-images.githubusercontent.com/102005803/200155359-b8122c06-e079-4177-a70d-cdd0a1cfe189.png">

访问控制页、高级设置、SSR Server没有修改没有修改
状态页：
![image](https://user-images.githubusercontent.com/102005803/200155386-9c970340-a9e2-43b8-ade6-0d75839f4f54.png)

请大佬指正看看哪里配的有问题。

**Comment by chobitsos** [comment]
日志

**Comment by Herakleitus** [comment]
https://github.com/coolsnowwolf/lede/issues/4409#issuecomment-950024793 works.
