### ISSUE TITLE
最新代码修改/添加节点信息luci报错

### ISSUE THREAD

**Issue by GreatMichaelLee** [fw876/helloworld#1027]
/usr/lib/lua/luci/dispatcher.lua:474: Failed to execute arcombine dispatcher target for entry '/admin/services/shadowsocksr/servers/cfg084a8f'.
The called action terminated with an exception:
/usr/lib/lua/luci/cbi.lua:53: /usr/lib/lua/luci/model/cbi/shadowsocksr/client-config.lua:660: '}' expected near '='
stack traceback:
	[C]: in function 'assert'
	/usr/lib/lua/luci/dispatcher.lua:474: in function 'dispatch'
	/usr/lib/lua/luci/dispatcher.lua:126: in function </usr/lib/lua/luci/dispatcher.lua:125>

**Comment by hqvv** [comment]
https://github.com/fw876/helloworld/pull/1028#issue-1439788165
