### ISSUE TITLE
请问能不能让用户自己选择订阅的更新频率？

### ISSUE THREAD

**Issue by Rangtian** [fw876/helloworld#1040]
现在SSR Plus+的设置里，订阅自动更新是一天一次。

但 Just My Socks 的节点基本半天就过期，导致每天都得手动更新一次。

**Comment by Rangtian** [comment]
> > 现在SSR Plus+的设置里，订阅自动更新是一天一次。
> > 但 Just My Socks 的节点基本半天就过期，导致每天都得手动更新一次。
> 
> 自己改crontab计划任务 0 */5 * * * /usr/share/shadowsocksr/ssrplusupdate.sh >/var/log/ssrplus.log 每五小时执行一次

我试过，这个会被覆盖。在 SSR Plus+ 的「服务器节点」 里，

如果不勾选自动更新，crontab计划任务里 所有的 ssrplusupdate.sh >/var/log/ssrplus.log 都会被删，不管有几条；
如果勾选自动更新，crontab计划任务里 所有的 ssrplusupdate.sh >/var/log/ssrplus.log 都会被修改为唯一的一条。

十分蛋疼。

**Comment by Rangtian** [comment]
> > ssrplusupdate.sh
> 
> 自己重写个脚本运行ssrplusupdate.sh 然后扔到cron就好了

有道理。。
我去瞅瞅你咋写的，复制粘贴一下。。

**Comment by Saxon-Sun** [comment]
> > > ssrplusupdate.sh
> > 
> > 
> > 自己重写个脚本运行ssrplusupdate.sh 然后扔到cron就好了
> 
> 有道理。。 我去瞅瞅你咋写的，复制粘贴一下。。

不要伸手 方法告诉你了

**Comment by Saxon-Sun** [comment]
> > > > ssrplusupdate.sh
> > > 
> > > 
> > > 自己重写个脚本运行ssrplusupdate.sh 然后扔到cron就好了
> > 
> > 
> > 有道理。。 我去瞅瞅你咋写的，复制粘贴一下。。
> 
> 不要伸手 方法告诉你了

我也没有这个需求

**Comment by Rangtian** [comment]
> > > > ssrplusupdate.sh
> > > 
> > > 
> > > 自己重写个脚本运行ssrplusupdate.sh 然后扔到cron就好了
> > 
> > 
> > 有道理。。 我去瞅瞅你咋写的，复制粘贴一下。。
> 
> 不要伸手 方法告诉你了

你误会了。

我的意思是，我去瞅一眼你的 ssrplusupdate.sh 是怎么写的，把更新订阅的那部分复制粘贴出来。
毕竟只是需要更新订阅，没必要连着 GFW列表 与 CHN 路由表一起频繁更新。

不是说要你在这里写个现成的给我。

**Comment by Saxon-Sun** [comment]
> > > > > ssrplusupdate.sh
> > > > 
> > > > 
> > > > 自己重写个脚本运行ssrplusupdate.sh 然后扔到cron就好了
> > > 
> > > 
> > > 有道理。。 我去瞅瞅你咋写的，复制粘贴一下。。
> > 
> > 
> > 不要伸手 方法告诉你了
> 
> 你误会了。
> 
> 我的意思是，我去瞅一眼你的 ssrplusupdate.sh 是怎么写的，把更新订阅的那部分复制粘贴出来。 毕竟只是需要更新订阅，没必要连着 GFW列表 与 CHN 路由表一起频繁更新。
> 
> 不是说要你在这里写个现成的给我。

把ssrplusupdate.sh复制出来重命名把里面的2-5行删了 就留第一行和第六行 
第六行就是运行订阅

**Comment by Rangtian** [comment]
> > > > > > ssrplusupdate.sh
> > > > > 
> > > > > 
> > > > > 自己重写个脚本运行ssrplusupdate.sh 然后扔到cron就好了
> > > > 
> > > > 
> > > > 有道理。。 我去瞅瞅你咋写的，复制粘贴一下。。
> > > 
> > > 
> > > 不要伸手 方法告诉你了
> > 
> > 
> > 你误会了。
> > 我的意思是，我去瞅一眼你的 ssrplusupdate.sh 是怎么写的，把更新订阅的那部分复制粘贴出来。 毕竟只是需要更新订阅，没必要连着 GFW列表 与 CHN 路由表一起频繁更新。
> > 不是说要你在这里写个现成的给我。
> 
> 把ssrplusupdate.sh复制出来重命名把里面的2-5行删了 就留第一行和第六行 第六行就是运行订阅

搞定，谢谢你！
