### ISSUE TITLE
最近2天编译的SSRP无法使用

### ISSUE THREAD

**Issue by tone88** [fw876/helloworld#1041]
![photo_2022-11-21_11-16-09](https://user-images.githubusercontent.com/47731895/202957411-53254941-1bef-485a-aa1d-68e2b2fbaefa.jpg)
昨天、今天编译的版本SSRP都无法使用，切换回前几天的版本是没有问题的，都是新建的虚拟机测试。  make distclean后编译也是同样的情况，日志里有几个报错 不知道是否和这个有关，麻烦懂的大佬看一下。
![QQ截图20221121112759](https://user-images.githubusercontent.com/47731895/202959175-bfcaf860-45d9-496a-9502-fc3eeee1324b.png)

**Comment by haibo-1985** [comment]
请问下哪个版本没问题？我这两天编译了好几个版本都不行，之前使用恩山F大最新的固件没有问题。我遇到的问题是vmess无法连接，ss没问题。justmysocks的线路。

**Comment by tone88** [comment]
> 请问下哪个版本没问题？我这两天编译了好几个版本都不行，之前使用恩山F大最新的固件没有问题。我遇到的问题是vmess无法连接，ss没问题。justmysocks的线路。

我也是vmess, 从升级79内核后发现的，连着2天编辑都是同样的问题

**Comment by tone88** [comment]
应该是
