### ISSUE TITLE
运行jerrykuku的vssr面板，ssr的面板也会显示运行中

### ISSUE THREAD

**Issue by free-diy** [fw876/helloworld#1044]
![11](https://user-images.githubusercontent.com/71208560/204081498-9bd0e0b8-dfeb-4aec-9256-ded7c12f3000.jpg)
![22](https://user-images.githubusercontent.com/71208560/204081501-735922e6-b645-47d6-ae2a-ac6ecf8a8ffd.jpg)

**Comment by Beginner-Go** [comment]
正常
