### ISSUE TITLE
[功能请求] 增加对hysteria协议多端口(端口跳跃)支持

### ISSUE THREAD

**Issue by chika0801** [fw876/helloworld#1049]
官方文档：https://hysteria.network/zh/docs/port-hopping/

现在填端口的对话框，要填多端口时，想填的内容为：16384,16500-17500，会提示有误，不能保存应用。

**Comment by qianxu2001** [comment]
#1046 可以照着改一下，或者等合并，我这测试功能正常

**Comment by chika0801** [comment]
> #1046 可以照着改一下，或者等合并，我这测试功能正常

感谢你的回复，没注意到已经有pr了，我去编译试试

**Comment by qianxu2001** [comment]
> > #1046 可以照着改一下，或者等合并，我这测试功能正常
> 
> 感谢你的回复，没注意到已经有pr了，我去编译试试

也不需要编译，直接修改 /usr/lib/lua/luci/model/cbi/shadowsocksr/client-config.lua 就行了，立即生效

**Comment by chika0801** [comment]
> > > #1046 可以照着改一下，或者等合并，我这测试功能正常
> > 
> > 
> > 感谢你的回复，没注意到已经有pr了，我去编译试试
> 
> 也不需要编译，直接修改 /usr/lib/lua/luci/model/cbi/shadowsocksr/client-config.lua 就行了，立即生效

懂了谢谢你
