### ISSUE TITLE
在luci页面保存并应用导致netflix分流失效

### ISSUE THREAD

**Issue by jamesbean08** [fw876/helloworld#105]
更新了5.4.50的最新固件并重新配置以后，在luci界面一旦点了保存并应用，会导致所有翻墙流量都走主服务器，luci页面虽然保存应用成功。只有重启路由器才能让让分流重新生效到重启前保存的服务器选择。

没有找到日志可以确认出现问题的原因。

**Comment by sk007** [comment]
> 更新了5.4.50的最新固件并重新配置以后，在luci界面一旦点了保存并应用，会导致所有翻墙流量都走主服务器，luci页面虽然保存应用成功。只有重启路由器才能让让分流重新生效到重启前保存的服务器选择。
> 
> 没有找到日志可以确认出现问题的原因。
截止目前
我的问题还是 开启netflix分流 重启路由器后 fq就不能使用
必须保存并应用或者开机启动项加入
sleep 20 && /etc/init.d/shadowsocksr restart
都是重新刷不保留配置 不存在 版本升级问题导致
我编译的 5月8号版本一切正常

**Comment by jamesbean08** [comment]
> > 更新了5.4.50的最新固件并重新配置以后，在luci界面一旦点了保存并应用，会导致所有翻墙流量都走主服务器，luci页面虽然保存应用成功。只有重启路由器才能让让分流重新生效到重启前保存的服务器选择。
> > 没有找到日志可以确认出现问题的原因。
> 
> 截止目前
> 我的问题还是 开启netflix分流 重启路由器后 fq就不能使用
> 必须保存并应用或者开机启动项加入
> sleep 20 && /etc/init.d/shadowsocksr restart
> 都是重新刷不保留配置 不存在 版本升级问题导致
> 我编译的 5月8号版本一切正常

我直到6.18版本都一切正常，没有出现重启才能生效或者重启不生效的问题。现在出现重启才能生效配置，不确定是内核升级带来的副作用，还是ssr+版本更新后的bug。

固件是自编译，主要改变就是删除了无用的无线和网卡硬件驱动，按需选择了luci apps，勾选了nginx ssl准备做内网映射，修改了分区大小，还添加了第三方adguard home（但是出现问题时还未启用）。供参考。

**Comment by fw876** [comment]
已修复
