### ISSUE TITLE
[功能请求] 增加对hysteria 1.3.1新增的客户端fast open参数支持

### ISSUE THREAD

**Issue by chika0801** [fw876/helloworld#1051]
文档 https://hysteria.network/zh/docs/advanced-usage/

"fast_open": false, // 启用 Fast Open (降低连接建立延迟)

Fast Open [#](https://hysteria.network/zh/docs/advanced-usage/#fast-open)
Fast Open 可以为每个连接建立的过程减少一个 RTT ，但代价是牺牲了 SOCKS5/HTTP/TUN 协议的正确语义。当开启时，客户端会始终马上接受任何连接，不会先和服务端确认是否能连通目标地址。如果随后发现服务端到目标地址连接失败，客户端也会不收发任何数据直接关闭连接。

**Comment by xiechangan123** [comment]
建议看看这个https://vpsgongyi.com/p/2237/  大厂都不待见它，某种意义上已经被bbr代替了，别自寻烦恼了。。。

**Comment by qianxu2001** [comment]
> 建议看看这个https://vpsgongyi.com/p/2237/ 大厂都不待见它，某种意义上已经被bbr代替了，别自寻烦恼了。。。

你没发现这个 fast open 没有 tcp 三个字吗？另外 bbr 对 hysteria 也没有任何提升，hysteria 是 udp 协议的

**Comment by chika0801** [comment]
> 建议看看这个https://vpsgongyi.com/p/2237/ 大厂都不待见它，某种意义上已经被bbr代替了，别自寻烦恼了。。。

你看错了

**Comment by xiechangan123** [comment]
甩锅给作者，起这么个“碰瓷”的名字。。。哈哈，我看错了。。。

**Comment by qianxu2001** [comment]
我改了一下，麻烦你帮忙测试一下可不可行
https://github.com/qianxu2001/helloworld/tree/patch-2

**Comment by chika0801** [comment]
https://github.com/fw876/helloworld/pull/1053
