### ISSUE TITLE
奇诡的BUG，一直没解决

### ISSUE THREAD

**Issue by free-diy** [fw876/helloworld#1056]
最近编译出来的都是这样，国外能访问，国内访问不了！！！

![image](https://user-images.githubusercontent.com/71208560/204537203-bcf31fc9-11fc-4f44-84de-70e4ae1dbfcf.png)
![image](https://user-images.githubusercontent.com/71208560/204537270-33b0ddd6-b827-4e07-bede-d099fd2f0a9c.png)

**Comment by zxlhhyccc** [comment]
> ![image](https://user-images.githubusercontent.com/71208560/204537203-bcf31fc9-11fc-4f44-84de-70e4ae1dbfcf.png) ![image](https://user-images.githubusercontent.com/71208560/204537270-33b0ddd6-b827-4e07-bede-d099fd2f0a9c.png)

无法重现。。。。

**Comment by mitsukileung** [comment]
![无标题](https://user-images.githubusercontent.com/38887306/205030168-2bd9c03e-2aff-4ab3-a8e6-f8ef256f4118.png)

![无标题1](https://user-images.githubusercontent.com/38887306/205030199-d7f4c783-a531-4f9e-a3fb-47ae2d88dd5a.png)

今天编译的，没有你说的情况，设置和你的也是一样

**Comment by free-diy** [comment]
> ![无标题](https://user-images.githubusercontent.com/38887306/205030168-2bd9c03e-2aff-4ab3-a8e6-f8ef256f4118.png)
> 
> ![无标题1](https://user-images.githubusercontent.com/38887306/205030199-d7f4c783-a531-4f9e-a3fb-47ae2d88dd5a.png)
> 
> 今天编译的，没有你说的情况，设置和你的也是一样

我设置的是旁路由

**Comment by minlang112** [comment]
原因：/etc/init.d/shadowsocksr 这个文件是旧的导致的，winscp登录进去之后，把这个文件内容清空，把库里最新文件的内容复制过去，保存退出，重启路由器再重新设置一下ssr+

**Comment by free-diy** [comment]
> 原因：/etc/init.d/shadowsocksr 这个文件是旧的导致的，winscp登录进去之后，把这个文件内容清空，把库里最新文件的内容复制过去，保存退出，重启路由器再重新设置一下ssr+

不行啊，照你的方法试了，国内网还是ping不通

**Comment by minlang112** [comment]
> > 原因：/etc/init.d/shadowsocksr 这个文件是旧的导致的，winscp登录进去之后，把这个文件内容清空，把库里最新文件的内容复制过去，保存退出，重启路由器再重新设置一下ssr+
> 
> 不行啊，照你的方法试了，国内网还是ping不通

目测是用了chinadns-ng和IPV6的问题……

**Comment by free-diy** [comment]
> 

op只开了ipv6客户端，而且我op是旁路由，主路由爱快没开ipv6，所以旁路由op也没有ipv6的地址呀

**Comment by free-diy** [comment]
> > > 原因：/etc/init.d/shadowsocksr 这个文件是旧的导致的，winscp登录进去之后，把这个文件内容清空，把库里最新文件的内容复制过去，保存退出，重启路由器再重新设置一下ssr+
> > 
> > 
> > 不行啊，照你的方法试了，国内网还是ping不通
> 
> 目测是用了chinadns-ng和IPV6的问题。我看了一下代码，看起应该是chinadns-ng分流境内外域名解析的时候没有考虑有人会使用IPV6，国内解析只给了A解析，然后系统如果优先用IPV6访问的话，就会出现打不开网页的问题。我斗胆对代码肤浅的看法，如果你既要用IPV6也要用本插件，就放弃chinadns-ng，国内 DNS 服务器 那个选项不要选任何东西，默认保留 “--请选择--”就是禁用chinadns-ng

试了，没ipv6也一样，国内网ping不通

**Comment by 1715173329** [comment]
旁路由自求多福。就一句访问不了，建议去找运营商。
