### ISSUE TITLE
ssr中加回的chinadns组件

### ISSUE THREAD

**Issue by loydcheung** [fw876/helloworld#1057]
看到ssr中重新加回了chinadns-ng组件，请问为何我编译进去了但是找不到它的设置界面？

**Comment by 1715173329** [comment]
“国内 DNS”就是所有设置了。

**Comment by loydcheung** [comment]
> “国内 DNS”就是所有设置了。

感谢大佬回复，是指“DNS解析方式”吗？dns2tcp、dns2socks和本机端口5335三者任选其一都是默认打开Chinadns吗？

**Comment by 1715173329** [comment]
> > “国内 DNS”就是所有设置了。
> 
> 感谢大佬回复，是指“DNS解析方式”吗？dns2tcp、dns2socks和本机端口5335三者任选其一都是默认打开Chinadns吗？

下面有个单独的“国内 DNS 服务器”选项，设置任意 DNS 即可开启 chinadns-ng。如果没有检查下 chinadns-ng 有没有安装成功，ssrp 有没有正确更新，或者缓存之类的。

**Comment by loydcheung** [comment]
> > > “国内 DNS”就是所有设置了。
> 
> > 
> 
> > 感谢大佬回复，是指“DNS解析方式”吗？dns2tcp、dns2socks和本机端口5335三者任选其一都是默认打开Chinadns吗？
> 
> 
> 
> 下面有个单独的“国内 DNS 服务器”选项，设置任意 DNS 即可开启 chinadns-ng。如果没有检查下 chinadns-ng 有没有安装成功，ssrp 有没有正确更新，或者缓存之类的。

尝试了所有，feeds做了clean后重新编译，浏览器也清了缓存，依然没有出现这个选项。

**Comment by 1715173329** [comment]
type -t -p chinadns-ng

看看输出

**Comment by loydcheung** [comment]
> type -t -p chinadns-ng

输出： /usr/bin/chinadns-ng

**Comment by 1715173329** [comment]
看下 `/usr/lib/lua/luci/model/cbi/shadowsocksr/client.lua` 里面有没有 chinadns-ng 相关的字眼

**Comment by loydcheung** [comment]
> /usr/lib/lua/luci/model/cbi/shadowsocksr/client.lua


.....................
......................
o = s:option(Value, "tunnel_forward", translate("Anti-pollution DNS Server"))                                                
o:value("8.8.4.4:53", translate("Google Public DNS (8.8.4.4)"))                                                              
o:value("8.8.8.8:53", translate("Google Public DNS (8.8.8.8)"))                                                                                     
o:value("208.67.222.222:53", translate("OpenDNS (208.67.222.222)"))                                                                                 
o:value("208.67.220.220:53", translate("OpenDNS (208.67.220.220)"))           
o:value("209.244.0.3:53", translate("Level 3 Public DNS (209.244.0.3)"))      
o:value("209.244.0.4:53", translate("Level 3 Public DNS (209.244.0.4)"))
o:value("4.2.2.1:53", translate("Level 3 Public DNS (4.2.2.1)"))        
o:value("4.2.2.2:53", translate("Level 3 Public DNS (4.2.2.2)"))                                          
o:value("4.2.2.3:53", translate("Level 3 Public DNS (4.2.2.3)"))                                          
o:value("4.2.2.4:53", translate("Level 3 Public DNS (4.2.2.4)"))                                                             
o:value("1.1.1.1:53", translate("Cloudflare DNS (1.1.1.1)"))                                                                 
o:value("114.114.114.114:53", translate("Oversea Mode DNS-1 (114.114.114.114)"))
o:value("114.114.115.115:53", translate("Oversea Mode DNS-2 (114.114.115.115)"))
o:depends("pdnsd_enable", "1")                                                  
o:depends("pdnsd_enable", "2")                                          
o.description = translate("Custom DNS Server format as IP:PORT (default: 8.8.4.4:53)")
o.datatype = "ip4addrport"                                                            
                                                                     
if is_finded("chinadns-ng") then                                             
        o = s:option(Value, "chinadns_forward", translate("Domestic DNS Server"))
        o:value("wan", translate("Use DNS from WAN"))                            
        o:value("wan_114", translate("Use DNS from WAN and 114DNS"))            
        o:value("114.114.114.114:53", translate("Nanjing Xinfeng 114DNS (114.114.114.114)"))
        o:value("119.29.29.29:53", translate("DNSPod Public DNS (119.29.29.29)"))           
        o:value("1.2.4.8:53", translate("CNNIC SDNS (1.2.4.8)"))                 
        o:depends({pdnsd_enable = "1", run_mode = "router"})                          
        o:depends({pdnsd_enable = "2", run_mode = "router"})                          
        o.description = translate("Custom DNS Server format as IP:PORT (default: disabled)")
        o.validate = function(self, value, section)                                         
                if (section and value) then                                      
                        if value == "wan" or value == "wan_114" then             
                                return value                                    
                        end                                                                 
                                                                                            
                        if validation.ip4addrport(value) then                         
                                return value                                          
                        end                                          
                                                                                            
                        return nil, translate("Expecting: %s"):format(translate("valid address:port"))
                end                                                                                   
                                                                                
                return value                                                                
        end                                                                                 
end                                                                              
                                                                                      
return m

**Comment by 1715173329** [comment]
除非你是用的自定义 5335 DNS 服务器，否则不应该出现这样的情况。

**Comment by loydcheung** [comment]
> 除非你是用的自定义 5335 DNS 服务器，否则不应该出现这样的情况。

我用了各种浏览器，多台电脑和手机都试过了，都是这样，奇怪：
<img width="1034" alt="image" src="https://user-images.githubusercontent.com/59357798/205320574-e2993444-7df4-4432-bcd7-48652eb79497.png">

**Comment by 1715173329** [comment]
分流模式呢？只有大陆白名单才有效。

**Comment by loydcheung** [comment]
> 分流模式呢？只有大陆白名单才有效。

原来如此，破案了，我之前是gfw模式，辛苦大佬，感谢。
