### ISSUE TITLE
当条目比较多的时候，servers nodes会显示504 Gateway Time-out

### ISSUE THREAD

**Issue by superwolfboy** [fw876/helloworld#1061]
点servers nodes时无法正常打开，显示504 Gateway Time-out
设备是一个淘汰的光猫zte f420，性能不是很高，单核cpu 1.2Ghz，128的ram。
当节点数量比较少的时候可以正常打开，选择节点，但是节点一多就打不开。
luci是nginx编译。之前做过一次不怎么严谨的测试，使用uhttpd也是这样。
所以现在只能在首页选择节点，基本靠猜。
![image](https://user-images.githubusercontent.com/9411604/206889944-ec419402-04c9-477b-9035-ef08ee97eb51.png)
![image](https://user-images.githubusercontent.com/9411604/206892865-56f5af22-bb92-4b6a-9006-81f8c1d4681d.png)

**Comment by 1715173329** [comment]
要么增加 uhttpd / nginx wait_time，要么就缩减节点列表。性能差就别弄那么多花里胡哨的了。

**Comment by superwolfboy** [comment]
> 要么增加 uhttpd / nginx wait_time，要么就缩减节点列表。性能差就别弄那么多花里胡哨的了。

![028A2476](https://user-images.githubusercontent.com/9411604/208026773-7c8f35b6-e2e7-4474-b6dc-f6cd3a39a874.png)
不过在使用的时候打开youtube还是挺流畅的，这一点倒是真让我意外。
