### ISSUE TITLE
chinadns-ng 的判断逻辑好像有点问题

### ISSUE THREAD

**Issue by yk271** [fw876/helloworld#1066]
将国内 DNS 服务器设置为本地的 AdGuard Home 服务器，在 AdGuard Home 中将某个广告域名屏蔽或重定向至 127.0.0.1 等内网 IP，chinadns-ng 似乎依旧会进行一次国外 DNS 查询并返回客户端国外 DNS 查询结果，但如果域名重定向 IP 是国内的就不会有这种情况。

**Comment by 1715173329** [comment]
要用 adguardhome 就不要用 chinadns-ng 了。
