### ISSUE TITLE
VLESS链接不能正常工作，找到有两项没有正确加入配置文件。有请大佬

### ISSUE THREAD

**Issue by SouHong** [fw876/helloworld#1078]
我使用的机场  VLESS 节点  服务器端口检查OK 不能正常使用。同样的节点PASSWALL可以正常使用。
找到有两项没有正确加入配置文件：（PASSWALL中同样的节点正常取得了这两项的值）
节点中如下两项没有添加到配置文件中
HTTP/2 主机名  [ 节点中是： 伪装 Host Quic加密方式 ]
HTTP/2 路径      [ 节点中是： Path QUIC密钥 gRPC ]
验证方式：修改：/usr/share/shadowsocksr/gen_config.lua
这个文件的218行和219行。或者修改节点手动添加这两项
不能链接的请检查/var/etc/ssrplus/tcp-udp-ssr-retcp.json配置文件中18行"host" 以及下面的"path"是否为空。

应该是添加节点时没有正确读取以上两项。

请各位大佬出手看能否修复类似的问题，造福遇到同类问题的朋友。

**Comment by liuyanantj** [comment]
我有的节点也是，用iOS的小火箭能打开  但是放到SSR就不行  看着pin没问题  应用之后连不上

**Comment by 1715173329** [comment]
检查下 /etc/config/shadowsocksr 有没有 h2_path / h2_host

**Comment by SouHong** [comment]
@1715173329  这两项都没有

**Comment by 1715173329** [comment]
你机场订阅链接发个样本看看。

**Comment by SouHong** [comment]
@1715173329 有联系方式吗？我把我的订阅私发你吧
https://rss.okggrss.buzz/link/U24dObYfZ74ggKPJ?mu=2
类似这种

**Comment by SouHong** [comment]
@1715173329   https://okgg.top

**Comment by 1715173329** [comment]
收到了，明天看看

**Comment by SouHong** [comment]
@1715173329 哪个订阅地址是不正确的

**Comment by 1715173329** [comment]
cnsztl@gmail.com 发到这

**Comment by SouHong** [comment]
@1715173329 

https://rss.okggrss.buzz/link/U24dObYfZ74ggKpJ?mu=2

**Comment by 1715173329** [comment]
应该修了

**Comment by SouHong** [comment]
@1715173329 正常了。辛苦了，再次感谢。

**Comment by Joker-lm** [comment]
> 应该修了

我的节点也是这样，大佬能帮我修改一下吗？

**Comment by Joker-lm** [comment]
安卓手机和hello world 都不行
