### ISSUE TITLE
添加新节点或编辑已有节点出错

### ISSUE THREAD

**Issue by Zeezorn** [fw876/helloworld#1079]
目标平台：
x86/64

固件版本：
OpenWrt 22.03.2

内核版本：
5.10.146

故障问题：
最新编译的luci-app-ssr-plus_186-7_all（20221231编译），点击添加节点或编辑已有节点时，弹出如图故障。

错误日志：
...ib/lua/luci/model/cbi/shadowsocksr/client-config.lua:7: module 'luci.model.ipkg' not found:
	no field package.preload['luci.model.ipkg']
	no file './luci/model/ipkg.lua'
	no file '/usr/share/lua/luci/model/ipkg.lua'
	no file '/usr/share/lua/luci/model/ipkg/init.lua'
	no file '/usr/lib/lua/luci/model/ipkg.lua'
	no file '/usr/lib/lua/luci/model/ipkg/init.lua'
	no file './luci/model/ipkg.so'
	no file '/usr/lib/lua/luci/model/ipkg.so'
	no file '/usr/lib/lua/loadall.so'
	no file './luci.so'
	no file '/usr/lib/lua/luci.so'
	no file '/usr/lib/lua/loadall.so'
stack traceback:
	[C]: in function 'require'
	...ib/lua/luci/model/cbi/shadowsocksr/client-config.lua:7: in function 'func'
	/usr/lib/lua/luci/cbi.lua:66: in function 'load'
	/usr/lib/lua/luci/dispatcher.lua:1385: in function '_cbi'
	/usr/lib/lua/luci/dispatcher.lua:1056: in function 'dispatch'
	/usr/lib/lua/luci/dispatcher.lua:483: in function </usr/lib/lua/luci/dispatcher.lua:482>

![1](https://user-images.githubusercontent.com/31385055/210331214-2c673553-1978-40a2-93a3-260c6b133d3a.png)
![2](https://user-images.githubusercontent.com/31385055/210331224-a9b003fb-803d-45c9-b2f6-8b41949193d2.png)

**Comment by 1715173329** [comment]
没装 luci-lib-ipkg

**Comment by Zeezorn** [comment]
谢谢，安装luci-lib-ipkg后问题解决了
