### ISSUE TITLE
能否增加自动更新的功能？

### ISSUE THREAD

**Issue by xhqpp** [fw876/helloworld#108]
v2ray内核更新的太勤了

**Comment by smallprogram** [comment]
> v2ray内核更新的太勤了

v2ray内核更新不在SSR+控制范围内，属于LEDE编译时更新下载。LEDE源码每次都是在V2ray内核更新几个小时内更新。重新编译升级固件即可，或者使用LEDE中LUCI Application V2rayServer中更新V2ray主程序也可行。

**Comment by xhqpp** [comment]
> > v2ray内核更新的太勤了
> 
> v2ray内核更新不在SSR +控制范围内，属于LEDE编译时更新下载。LEDE继承都是在V2ray内核更新几个小时内更新。重新编译升级固件即可，或者使用LEDE中LUCI应用程序V2rayServer中更新V2ray主程序也可行。

我在V2ray服务器里更新版本到4.26.0，但是在软件包里看到v2ray版本是4.25.1，是怎么回事呢？

**Comment by smallprogram** [comment]
你需要查看SSR+中日志所示的V2ray版本。

**Comment by fw876** [comment]
主要是官方的 v2ray 太大了，默认有大约 28MB+。 如果使用者不小心开启，路由器空间更新后马上爆炸（大部分硬路由）

我们用的 v2ray 是定制后压缩的版本， 3.x MB 而已

**Comment by ryshi** [comment]
能否把压缩这部分单独放出来呢？这样可以留出手动更新v2ray客户端的机会，目前更新只有重新编译，在软路由尝试使用官方v2ray直接导致ssr+插件挂掉

**Comment by smallprogram** [comment]
> 能否把压缩这部分单独放出来呢？这样可以留出手动更新v2ray客户端的机会，目前更新只有重新编译，在软路由尝试使用官方v2ray直接导致ssr+插件挂掉

https://codeload.github.com/v2fly/v2ray-core/tar.gz/v{版本号}
将版本号替换为实际版本。例如
https://codeload.github.com/v2fly/v2ray-core/tar.gz/v4.26.0

其实我觉得没啥意义，你还不如重新多线程编译来的痛快。既能升级v2ray还能升级其他功能。也费不了几分钟。二次编译很快的。

**Comment by ryshi** [comment]
> > 能否把压缩这部分单独放出来呢？这样可以留出手动更新v2ray客户端的机会，目前更新只有重新编译，在软路由尝试使用官方v2ray直接导致ssr+插件挂掉
> 
> [https://codeload.github.com/v2fly/v2ray-core/tar.gz/v{版本号}](https://codeload.github.com/v2fly/v2ray-core/tar.gz/v%7B%E7%89%88%E6%9C%AC%E5%8F%B7%7D)
> 将版本号替换为实际版本。例如
> https://codeload.github.com/v2fly/v2ray-core/tar.gz/v4.26.0
> 
> 其实我觉得没啥意义，你还不如重新多线程编译来的痛快。既能升级v2ray还能升级其他功能。也费不了几分钟。二次编译很快的。

确实，怎么都是折腾一回，只是编译环境没在手边，先收下这新技能包^_^

**Comment by smallprogram** [comment]
> > > 能否把压缩这部分单独放出来呢？这样可以留出手动更新v2ray客户端的机会，目前更新只有重新编译，在软路由尝试使用官方v2ray直接导致ssr+插件挂掉
> > 
> > 
> > [https://codeload.github.com/v2fly/v2ray-core/tar.gz/v{版本号}](https://codeload.github.com/v2fly/v2ray-core/tar.gz/v%7B%E7%89%88%E6%9C%AC%E5%8F%B7%7D)
> > 将版本号替换为实际版本。例如
> > https://codeload.github.com/v2fly/v2ray-core/tar.gz/v4.26.0
> > 其实我觉得没啥意义，你还不如重新多线程编译来的痛快。既能升级v2ray还能升级其他功能。也费不了几分钟。二次编译很快的。
> 
> 确实，怎么都是折腾一回，只是编译环境没在手边，先收下这新技能包^_^

Github Actions 了解一下，本地无需任何编译环境。无论你在天涯海角只要有一台能上网的电脑即可。

**Comment by ryshi** [comment]
> > > > 能否把压缩这部分单独放出来呢？这样可以留出手动更新v2ray客户端的机会，目前更新只有重新编译，在软路由尝试使用官方v2ray直接导致ssr+插件挂掉
> > > 
> > > 
> > > [https://codeload.github.com/v2fly/v2ray-core/tar.gz/v{版本号}](https://codeload.github.com/v2fly/v2ray-core/tar.gz/v%7B%E7%89%88%E6%9C%AC%E5%8F%B7%7D)
> > > 将版本号替换为实际版本。例如
> > > https://codeload.github.com/v2fly/v2ray-core/tar.gz/v4.26.0
> > > 其实我觉得没啥意义，你还不如重新多线程编译来的痛快。既能升级v2ray还能升级其他功能。也费不了几分钟。二次编译很快的。
> > 
> > 
> > 确实，怎么都是折腾一回，只是编译环境没在手边，先收下这新技能包^_^
> 
> Github Actions 了解一下，本地无需任何编译环境。无论你在天涯海角只要有一台能上网的电脑即可。

恩，是个路子 :thumbsup: ，研究研究config那部分怎么配
