### ISSUE TITLE
2023-01-06编译的最新SSR Plus+用ipv6时为何变慢了这么多

### ISSUE THREAD

**Issue by gztingting** [fw876/helloworld#1082]
由于v4 ip被封，套cdn慢得Youtube经常卡断，于是用ipv6，发现一个很大的速度差别。
服务端用的是xray 1.7.0  vless+tls+ws, cn2-gia网络。
①当客户端是windows10 V2rayN 开sock5时，用Chrome浏览器通过访问Youtube，测速可以达到80Mpbs，看8k秒开。
②当客户端Openwrt+SSR Plus+时（GFW模式，DNS2TCP解析），用windows 10 Chrome浏览器访问Youtube，所有页面都可以访问，广告视频也看到，就是所有的视频正片无法打开，少部分被墙网站无法打开（确定是在GFW列表里的）。用iphone的youtube app，视频正片又可以打开了，只是速度非常慢，几十到几百Kbps，经常卡断。
③当客户端是iphone 小火箭时，Youtube app测速可以达到10Mpbs。

软路由上到底是哪里没有设置对呢？

**Comment by 1715173329** [comment]
那我推荐你在客户端挂，ssrplus 不支持 v6

**Comment by gztingting** [comment]
> 那我推荐你在客户端挂，ssrplus 不支持 v6

我想用透明代理（也就是说WiFi局域网内全部无感翻墙）。我看SSRplus+是支持v6的，因为我试了把ip地址改为v6后是可以翻墙的，tracert后发现被墙网站是自动通过Xray封装后发包到我的VPS v6地址的，国内网站则直接v6路由发包到具体访问的国内v6地址的。只是同一时刻，这个速度非常慢。v6路由没有做优化，这是事实，但不至于同一时刻速度和延迟差别这么大。

**Comment by 1715173329** [comment]
你要用 v6 就用 v2raya，ssrplus 没有任何保证。
