### ISSUE TITLE
2023-01-07编译的SSR Plus+翻墙速度慢很多很多

### ISSUE THREAD

**Issue by gztingting** [fw876/helloworld#1084]
之前我发现v6慢很多很多，于是重新编译一个新的。这回用一个没有被封的v4直连（vless tls ws），也是速度慢很多很多。在iPhone7p上用小火箭shadowrocket，YouTube测速可以达到40Mbps，在windows10上用V2rayN也是在40Mbps左右，而在Openwrt SSR plus+后，所有设备的YouTube测速只有100Kbps左右，还经常断。这就奇怪了。恕我愚笨，通过Tracer、Dig、Iperf做简单调试，我也没有发现什么特别的。

请教这位大神，该怎么排解这个速度差异问题，需要什么log我贴出来。

**Comment by pangfeng161** [comment]
这几天编译的似乎有些问题,有时候突然爬来墙,重启又可以,网速忽快忽慢

**Comment by gztingting** [comment]
补充说明，J4125软路由，以前版本的SSR plus+似乎没有这个问题，看CPU负载也就是0-3%之间波动，说明不是算力问题。而且在iPhone7p和iPhone13pm上一样的shadowrocket一样的参数配置，YouTube测速结果是没啥差异的，足以说明客户机算力没有问题

**Comment by pangfeng161** [comment]
我这边发现问题,如果安装chinadns-ng会有TikTok经常刷不出视频,知乎也经常刷不出图片.反倒是去掉chinadns-ng就没问题
