### ISSUE TITLE
IPv6地址的服务器节点连通性检测失败

### ISSUE THREAD

**Issue by qwerttvv** [fw876/helloworld#1087]
v6地址的服务器实际使用是正常的，但是检测会失败，显示fail

![image](https://user-images.githubusercontent.com/56712217/212272447-46a3405b-4c78-4165-ba7c-897fc70b174f.png)

**Comment by 1715173329** [comment]
因为只考虑 v4 的情况，即便因为某些原因你可以连上 v6 的 server，也不提供任何支持。
