### ISSUE TITLE
再次无法更新

### ISSUE THREAD

**Issue by qqsir-dev** [fw876/helloworld#109]
今日最新的LEDE编译后
【GFW列表】数据库	 更新失败！
【国内IP段】数据库	 更新失败！
【Netflix IP段】数据库	 更新失败！

**Comment by smallprogram** [comment]
目测代理线路问题

**Comment by swxk521** [comment]
![image](https://user-images.githubusercontent.com/61259428/87102748-65a56b00-c285-11ea-9a88-00a954cb9898.png)
没有问题
