### ISSUE TITLE
反馈一个luci的小bug

### ISSUE THREAD

**Issue by tone88** [fw876/helloworld#1091]
最新源码编译的X86，在SSRP luci界面点击“服务器节点”后马上点击左边的“客户端”会出Unable to launch the requested CGI program:  /www/cgi-bin/luci: No such file or directory 的提示，这时候F5刷新一下能正常显示，之前的版本是正常显示界面并有个“正在收集数据..”的提示，具体见下图，目前功能上好像并无异常。
错误提示：
![1](https://user-images.githubusercontent.com/47731895/212663188-427e95ad-4178-40e2-8236-9dbc558ba805.png)
之前版本正常提示：
![2](https://user-images.githubusercontent.com/47731895/212663195-8a5a5807-a6a3-469b-b9cb-ee6de1dac087.png)

**Comment by Saxon-Sun** [comment]
解决了吗 我也有这种情况

**Comment by kidcool-gxh** [comment]
我也这种情况，请问解决了么

**Comment by tone88** [comment]
> 我也这种情况，请问解决了么

问题依旧，不过好像也不影响功能，所以暂时不管它了。
