### ISSUE TITLE
[疑问]ipset是谁下发的

### ISSUE THREAD

**Issue by mrpre** [fw876/helloworld#1094]
目前的模式 ss-redir + dnsmasq + pdns 
目前看是惰性执行ipset的，也就是当发起dns的请求匹配gfwlist里面的域名时，才会下发到ipset里面（通过 ipset list gfwlist 查看得到结论）。

目前排除了pdns执行ipset的情况。其次我看 dnsmasq 代码中实际有执行ipset功能的，但是需要开启`--log-queries`功能，但是当前我的dnsmasq 是2.86，没开启该选项，并且看日志，也没有`ipset add xxx` 之类的功能，所以好奇请教下，是哪个功能在执行ipset下发ip呢？

**Comment by 1715173329** [comment]
dnsmasq。非官方固件默认把日志干掉了，自然看不到。
