### ISSUE TITLE
ssrp 能让 支持服务器类型显示trojan go么？

### ISSUE THREAD

**Issue by lsq726** [fw876/helloworld#1095]
ssrp ”支持服务器类型”一直显示trojan go类型么？

在替换trojan 为trojan go 客户端后是能正常运行，不过没有trojan go 选项。
ps：
当然如果能直接在menuconfig增加编译时候 trojan  和trojan go选项就更好了

**Comment by lsq726** [comment]
祝，各位春节快乐！

**Comment by 1715173329** [comment]
不能。trojan-go 的大部分功能与 xray 提供的重叠。
至于“显示”，更没什么用。

**Comment by lsq726** [comment]
> 

ssrp 也可以选Xray么
