### ISSUE TITLE
vless类型节点,GFW模式可以正常使用,"绕过大陆IP"模式会失败.SS节点一切正常

### ISSUE THREAD

**Issue by lqdflying** [fw876/helloworld#1097]
vless类型节点,GFW模式可以正常使用,"绕过大陆IP"模式会失败.SS节点一切正常.
大佬们有和我一样的嘛

**Comment by williamswu2000** [comment]
yes, it happened last week

**Comment by lqdflying** [comment]
i compiled the latest version of code, the issue resolved. so i would close this case.
