### ISSUE TITLE
关于中国大陆 IP 库不全的问题

### ISSUE THREAD

**Issue by yk271** [fw876/helloworld#1099]
ispip.clang.cn 的 IP 库缺少了部分中国大陆阿里云 IP 段，例如：
8.129.0.0
8.134.0.0
8.142.0.0
8.144.0.0
8.146.0.0
导致部分国内请求被代理，因此建议增加一个 IP 库合并使用。

https://github.com/Loyalsoldier/geoip
geoip 正在使用的大陆 IP 库之一：
https://github.com/gaoyifan/china-operator-ip/blob/ip-lists/china.txt

**Comment by minlang112** [comment]
这个1W8的数据不对吧……

**Comment by 1715173329** [comment]
你可以在高级模式自己改数据源。
