### ISSUE TITLE
ssrplus目前在官方的最新的master下更新数据库失败！！！

### ISSUE THREAD

**Issue by zxlhhyccc** [fw876/helloworld#11]
![image](https://user-images.githubusercontent.com/45259624/79869457-f9e4fc00-8413-11ea-88fb-0a604bcba1a3.png)

**Comment by tty228** [comment]
![2020-04-23_112941](https://user-images.githubusercontent.com/33397881/80056008-bd211e00-8555-11ea-9d68-6110cef0f2da.png)

19.07.2 release 无问题
尝试重置配置文件，屏蔽IPV6?

**Comment by fw876** [comment]
不支持 Trunk luci
