### ISSUE TITLE
没有翻译

### ISSUE THREAD

**Issue by forever2019** [fw876/helloworld#110]
如题
添加代理节点类型有个没有翻译
![image](https://user-images.githubusercontent.com/49540243/87069251-72a46900-c249-11ea-90fb-97b189066c0f.png)

**Comment by EnnawYang** [comment]
这要什么翻译？

**Comment by forever2019** [comment]
> 这要什么翻译？

这是SS吗 ?   为什么不直接用SS呢   刚看到都懵逼了

**Comment by fw876** [comment]
历史原因。老版本 SS 是被 SSR 兼容的
新版本 SS 3.x 开始不支持 Openssl，不兼容 SSR
