### ISSUE TITLE
make download失败

### ISSUE THREAD

**Issue by luoyu124578** [fw876/helloworld#1100]
编译下载时 失败，错误ERROR: package/feeds/helloworld/dns2socks failed to build
查看日志发现是下载失败问题，
+ curl -f --connect-timeout 20 --retry 5 --location https://downloads.sourceforge.net/dns2socks/SourceCode.zip
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   311  100   311    0     0    247      0  0:00:01  0:00:01 --:--:--   247
  0     0    0     0    0     0      0      0 --:--:--  0:00:04 --:--:--     0
curl: (35) error:0A000126:SSL routines::unexpected eof while reading
其他mirror也无法下载
+ curl -f --connect-timeout 20 --retry 5 --location https://mirror2.openwrt.org/sources/SourceCode.zip
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0   153    0     0    0     0      0      0 --:--:--  0:00:01 --:--:--     0
curl: (22) The requested URL returned error: 404，其他东西都能下载，速度还挺快，就这个下载失败了

**Comment by luoyu124578** [comment]
开始报错的地方
mkdir -p /home/disk/mount/lede/dl
SHELL= flock /home/disk/mount/lede/tmp/.SourceCode.zip.flock -c '  	/home/disk/mount/lede/scripts/download.pl "/home/disk/mount/lede/dl" "SourceCode.zip" "406b5003523577d39da66767adfe54f7af9b701374363729386f32f6a3a995f4" "" "@SF/dns2socks"    '
+ curl -f --connect-timeout 20 --retry 5 --location https://downloads.sourceforge.net/dns2socks/SourceCode.zip
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   311  100   311    0     0    153      0  0:00:02  0:00:02 --:--:--   153
  0     0    0     0    0     0      0      0 --:--:--  0:00:05 --:--:--     0
curl: (35) error:0A000126:SSL routines::unexpected eof while reading
Download failed.
+ curl -f --connect-timeout 20 --retry 5 --location https://downloads.sourceforge.net/dns2socks/SourceCode.zip
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   311  100   311    0     0    247      0  0:00:01  0:00:01 --:--:--   247
  0     0    0     0    0     0      0      0 --:--:--  0:00:04 --:--:--     0
curl: (35) error:0A000126:SSL routines::unexpected eof while reading
Download failed.
+ curl -f --connect-timeout 20 --retry 5 --location https://downloads.sourceforge.net/dns2socks/SourceCode.zip
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   311  100   311    0     0    213      0  0:00:01  0:00:01 --:--:--   214
  0     0    0     0    0     0      0      0 --:--:--  0:00:04 --:--:--     0
curl: (35) error:0A000126:SSL routines::unexpected eof while reading
Download failed.
+ curl -f --connect-timeout 20 --retry 5 --location https://downloads.sourceforge.net/dns2socks/SourceCode.zip
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   311  100   311    0     0    275      0  0:00:01  0:00:01 --:--:--   274
  0     0    0     0    0     0      0      0 --:--:--  0:00:04 --:--:--     0
curl: (35) error:0A000126:SSL routines::unexpected eof while reading
Download failed.
+ curl -f --connect-timeout 20 --retry 5 --location https://downloads.sourceforge.net/dns2socks/SourceCode.zip
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   311  100   311    0     0    271      0  0:00:01  0:00:01 --:--:--   272
  0     0    0     0    0     0      0      0 --:--:--  0:00:05 --:--:--     0
curl: (35) error:0A000126:SSL routines::unexpected eof while reading
Download failed.
+ curl -f --connect-timeout 20 --retry 5 --location https://sources.cdn.openwrt.org/SourceCode.zip
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0   169    0     0    0     0      0      0 --:--:--  0:00:01 --:--:--     0
curl: (22) The requested URL returned error: 404
Download failed.
+ curl -f --connect-timeout 20 --retry 5 --location https://sources.openwrt.org/SourceCode.zip
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0   169    0     0    0     0      0      0 --:--:--  0:00:02 --:--:--     0
curl: (22) The requested URL returned error: 404
Download failed.
+ curl -f --connect-timeout 20 --retry 5 --location https://mirror2.openwrt.org/sources/SourceCode.zip
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0   153    0     0    0     0      0      0 --:--:--  0:00:01 --:--:--     0
curl: (22) The requested URL returned error: 404
Download failed.
No more mirrors to try - giving up.
make[2]: *** [Makefile:54: /home/disk/mount/lede/dl/SourceCode.zip] Error 2
make[2]: Leaving directory '/home/disk/mount/lede/feeds/helloworld/dns2socks'
time: package/feeds/helloworld/dns2socks/download#0.42#0.08#29.09
    ERROR: package/feeds/helloworld/dns2socks failed to build.
make[1]: *** [package/Makefile:116: package/feeds/helloworld/dns2socks/download] Error 1
make[1]: Leaving directory '/home/disk/mount/lede'
make[1]: Entering directory '/home/disk/mount/lede'
make[2]: Entering directory '/home/disk/mount/lede/target/linux'
make[3]: Entering directory '/home/disk/mount/lede/target/linux/x86'
make[3]: Nothing to be done for 'download'.
make[3]: Leaving directory '/home/disk/mount/lede/target/linux/x86'
make[2]: Leaving directory '/home/disk/mount/lede/target/linux'
time: target/linux/download#0.03#0.00#0.04
make[1]: Leaving directory '/home/disk/mount/lede'

**Comment by 1715173329** [comment]
你网烂了，那能怎么说。其他 mirror 是 openwrt 官方的，自然没有这个文件。

**Comment by luoyu124578** [comment]
我网不烂啊，全局科学，githtub稳定，所有文件里面只有这个下载不了，跳过了这个其他的都能下载成功。。。
