### ISSUE TITLE
自制的v2ray节点电脑手机能用，路由surplus不能用？

### ISSUE THREAD

**Issue by 725216** [fw876/helloworld#1104]
如题，在路由上连响应时间都没有，不通，订阅的链接正常

**Comment by 1715173329** [comment]
配置没有，图也没有，不如上街请个算命大师帮忙算算。

**Comment by chika0801** [comment]
你的SSL证书是不是BT宝塔之类申请的。如果是或不是，检查你上传到VPS的公钥SSL证书是不是全链，如果不是，补全即可。
