### ISSUE TITLE
昨天的源码更新后导入服务器配置要先选服务器节点类型才能导入

### ISSUE THREAD

**Issue by xe7on** [fw876/helloworld#1113]
最新的源码手动导入服务器配置里的服务器节点类型默认是<请选择>，这就导致了如果要导入配置信息就要先把服务器节点类型从<请选择>改为<V2RAY/XRAY>，不改的话导入进去不会自动识别。以前的源码默认选择的是<V2RAY/XRAY>直接就可以导入信息，最新的源码还要手动选一下才能导入，我想问下大佬这是属于BUG还是添加了新的功能？
![Screenshot_20230210_215755](https://user-images.githubusercontent.com/99581097/218110147-828e94f0-1429-409f-9612-8684a4a74835.jpg)

**Comment by 1715173329** [comment]
fixed by 29167911e51930f940465495b8e59513b72afbaf
