### ISSUE TITLE
请问,用潘多 拉sdk编译ssr-plus,选中trojan时,编译报错,怎么解决?

### ISSUE THREAD

**Issue by 725216** [fw876/helloworld#1114]
,选中trojan时,编译报错,报错内容是:
23-02-11 14:49:14 (7.05 MB/s) - written to stdout [1875233]

. /home/ubuntu/1/include/shell.sh; gzip -dc /home/ubuntu/1/dl/zstd-1.3.8.tar.gz | tar -C /home/ubuntu/1/build_dir/target-mipsel_1004kc+dsp_uClibc-1.0.x/zstd-1.3.8/.. -xf -
[ ! -d ./src/ ] || cp -fpR ./src/. /home/ubuntu/1/build_dir/target-mipsel_1004kc+dsp_uClibc-1.0.x/zstd-1.3.8
touch /home/ubuntu/1/build_dir/target-mipsel_1004kc+dsp_uClibc-1.0.x/zstd-1.3.8/.prepared_03986b7fe9855be625f76e19ebc2967a68b329da9893e34099c7d8ad5cb9c940
rm -f /home/ubuntu/1/staging_dir/target-mipsel_1004kc+dsp_uClibc-1.0.x/stamp/.zstd_installed
mkdir -p /home/ubuntu/1/build_dir/target-mipsel_1004kc+dsp_uClibc-1.0.x/zstd-1.3.8
(cd /home/ubuntu/1/build_dir/target-mipsel_1004kc+dsp_uClibc-1.0.x/zstd-1.3.8; CFLAGS="-pipe -mno-branch-likely -mips32r2 -mtune=1004kc -mlong-calls -mdsp -fno-caller-saves -fhonour-copts -Wno-error=unused-but-set-variable -Wno-error=unused-result -msoft-float -iremap/home/ubuntu/1/build_dir/target-mipsel_1004kc+dsp_uClibc-1.0.x/zstd-1.3.8:zstd-1.3.8 -D_FORTIFY_SOURCE=1 -Wl,-z,now -Wl,-z,relro -O3 " CXXFLAGS="-pipe -mno-branch-likely -mips32r2 -mtune=1004kc -mlong-calls -mdsp -fno-caller-saves -fhonour-copts -Wno-error=unused-but-set-variable -Wno-error=unused-result -msoft-float -iremap/home/ubuntu/1/build_dir/target-mipsel_1004kc+dsp_uClibc-1.0.x/zstd-1.3.8:zstd-1.3.8 -D_FORTIFY_SOURCE=1 -Wl,-z,now -Wl,-z,relro -O3 " LDFLAGS="-L/home/ubuntu/1/staging_dir/target-mipsel_1004kc+dsp_uClibc-1.0.x/usr/lib -L/home/ubuntu/1/staging_dir/target-mipsel_1004kc+dsp_uClibc-1.0.x/lib -L/home/ubuntu/1/staging_dir/toolchain-mipsel_1004kc+dsp_gcc-5.5.0_uClibc-1.0.x/usr/lib -L/home/ubuntu/1/staging_dir/toolchain-mipsel_1004kc+dsp_gcc-5.5.0_uClibc-1.0.x/lib -znow -zrelro " cmake -DCMAKE_SYSTEM_NAME=Linux -DCMAKE_SYSTEM_VERSION=1 -DCMAKE_SYSTEM_PROCESSOR=mipsel -DCMAKE_BUILD_TYPE=Release -DCMAKE_C_FLAGS_RELEASE="-DNDEBUG" -DCMAKE_CXX_FLAGS_RELEASE="-DNDEBUG" -DCMAKE_C_COMPILER="/home/ubuntu/1/staging_dir/toolchain-mipsel_1004kc+dsp_gcc-5.5.0_uClibc-1.0.x/bin/mipsel-openwrt-linux-uclibc-gcc" -DCMAKE_C_COMPILER_ARG1="" -DCMAKE_CXX_COMPILER="/home/ubuntu/1/staging_dir/toolchain-mipsel_1004kc+dsp_gcc-5.5.0_uClibc-1.0.x/bin/mipsel-openwrt-linux-uclibc-g++" -DCMAKE_CXX_COMPILER_ARG1="" -DCMAKE_ASM_COMPILER="/home/ubuntu/1/staging_dir/toolchain-mipsel_1004kc+dsp_gcc-5.5.0_uClibc-1.0.x/bin/mipsel-openwrt-linux-uclibc-gcc" -DCMAKE_ASM_COMPILER_ARG1="" -DCMAKE_EXE_LINKER_FLAGS:STRING="-L/home/ubuntu/1/staging_dir/target-mipsel_1004kc+dsp_uClibc-1.0.x/usr/lib -L/home/ubuntu/1/staging_dir/target-mipsel_1004kc+dsp_uClibc-1.0.x/lib -L/home/ubuntu/1/staging_dir/toolchain-mipsel_1004kc+dsp_gcc-5.5.0_uClibc-1.0.x/usr/lib -L/home/ubuntu/1/staging_dir/toolchain-mipsel_1004kc+dsp_gcc-5.5.0_uClibc-1.0.x/lib -znow -zrelro" -DCMAKE_MODULE_LINKER_FLAGS:STRING="-L/home/ubuntu/1/staging_dir/target-mipsel_1004kc+dsp_uClibc-1.0.x/usr/lib -L/home/ubuntu/1/staging_dir/target-mipsel_1004kc+dsp_uClibc-1.0.x/lib -L/home/ubuntu/1/staging_dir/toolchain-mipsel_1004kc+dsp_gcc-5.5.0_uClibc-1.0.x/usr/lib -L/home/ubuntu/1/staging_dir/toolchain-mipsel_1004kc+dsp_gcc-5.5.0_uClibc-1.0.x/lib -znow -zrelro -Wl,-Bsymbolic-functions" -DCMAKE_SHARED_LINKER_FLAGS:STRING="-L/home/ubuntu/1/staging_dir/target-mipsel_1004kc+dsp_uClibc-1.0.x/usr/lib -L/home/ubuntu/1/staging_dir/target-mipsel_1004kc+dsp_uClibc-1.0.x/lib -L/home/ubuntu/1/staging_dir/toolchain-mipsel_1004kc+dsp_gcc-5.5.0_uClibc-1.0.x/usr/lib -L/home/ubuntu/1/staging_dir/toolchain-mipsel_1004kc+dsp_gcc-5.5.0_uClibc-1.0.x/lib -znow -zrelro -Wl,-Bsymbolic-functions" -DCMAKE_AR="/home/ubuntu/1/staging_dir/toolchain-mipsel_1004kc+dsp_gcc-5.5.0_uClibc-1.0.x/bin/mipsel-openwrt-linux-uclibc-gcc-ar" -DCMAKE_NM="/home/ubuntu/1/staging_dir/toolchain-mipsel_1004kc+dsp_gcc-5.5.0_uClibc-1.0.x/bin/mipsel-openwrt-linux-uclibc-gcc-nm" -DCMAKE_RANLIB="/home/ubuntu/1/staging_dir/toolchain-mipsel_1004kc+dsp_gcc-5.5.0_uClibc-1.0.x/bin/mipsel-openwrt-linux-uclibc-gcc-ranlib" -DCMAKE_FIND_ROOT_PATH="/home/ubuntu/1/staging_dir/target-mipsel_1004kc+dsp_uClibc-1.0.x/usr;/home/ubuntu/1/staging_dir/toolchain-mipsel_1004kc+dsp_gcc-5.5.0_uClibc-1.0.x" -DCMAKE_FIND_ROOT_PATH_MODE_PROGRAM=BOTH -DCMAKE_FIND_ROOT_PATH_MODE_LIBRARY=ONLY -DCMAKE_FIND_ROOT_PATH_MODE_INCLUDE=ONLY -DCMAKE_STRIP=: -DCMAKE_INSTALL_PREFIX=/usr -DDL_LIBRARY=/home/ubuntu/1/staging_dir/target-mipsel_1004kc+dsp_uClibc-1.0.x -DCMAKE_PREFIX_PATH=/home/ubuntu/1/staging_dir/target-mipsel_1004kc+dsp_uClibc-1.0.x -DCMAKE_SKIP_RPATH=TRUE  /home/ubuntu/1/build_dir/target-mipsel_1004kc+dsp_uClibc-1.0.x/zstd-1.3.8 )
CMake Error: The source directory "/home/ubuntu/1/build_dir/target-mipsel_1004kc+dsp_uClibc-1.0.x/zstd-1.3.8" does not appear to contain CMakeLists.txt.
Specify --help for usage, or press the help button on the CMake GUI.
Makefile:79: recipe for target '/home/ubuntu/1/build_dir/target-mipsel_1004kc+dsp_uClibc-1.0.x/zstd-1.3.8/.configured_ed00f18ddc9fbd2040d5932fd859f56c' failed
make[2]: *** [/home/ubuntu/1/build_dir/target-mipsel_1004kc+dsp_uClibc-1.0.x/zstd-1.3.8/.configured_ed00f18ddc9fbd2040d5932fd859f56c] Error 1
make[2]: Leaving directory '/home/ubuntu/1/feeds/packages/utils/zstd'
package/Makefile:105: recipe for target 'package/feeds/packages/zstd/compile' failed
make[1]: *** [package/feeds/packages/zstd/compile] Error 2
make[1]: Leaving directory '/home/ubuntu/1'

**Comment by 1715173329** [comment]
zstd 软件包有问题，问 PandoraBox。
