### ISSUE TITLE
SSR-Check的源码在哪儿

### ISSUE THREAD

**Issue by freessrnet3vnet** [fw876/helloworld#1118]
shadowsocks plus在/usr/bin/目录下有一个ssr-check，用来判断是否能访问google，但是没有找到这个源代码
想更改这个源码，使得它能不但能判断是否能访问google，而且判断它的平均下载速度。如果速度过低，也要切换节点。
在这个仓库中没有发现这个源码，请大佬指点。

**Comment by deplives** [comment]
https://github.com/fw876/helloworld/blob/master/luci-app-ssr-plus/Makefile#L36

**Comment by freessrnet3vnet** [comment]
这里也找不到这个文件啊，希望能修改ssr-check，让他具有测速功能。

**Comment by hqvv** [comment]
https://github.com/fw876/helloworld/blob/master/shadowsocksr-libev/src/server/check.c 

欢迎大神贡献代码，我反正已经用 curl 替代了这个东西了。
