### ISSUE TITLE
请问新版本支持19.07.03吗

### ISSUE THREAD

**Issue by xun188** [fw876/helloworld#112]
请问新版本支持19.07.03吗

**Comment by tyadan** [comment]
支持，我在Snapshot下编译可以

**Comment by xun188** [comment]
新版本编译有bug，应该是keep.d文件，安装时候会报错，而且不创建这个目录

**Comment by tyadan** [comment]
<img width="992" alt="Snipaste_2020-07-15_14-13-52" src="https://user-images.githubusercontent.com/13864360/87510076-76027f00-c6a5-11ea-89c0-b322ca456410.png">
我就用最新的代码编译的，使用一切正常哎，就是得从Lean大的代码里面把package下的Lean文件夹复制过来，因为ssr plus部分依赖了这里面的一些包
另外就是编译的时候要去掉dnsmasq的选项，会和依赖的dnsmasq-full冲突
