### ISSUE TITLE
反馈个订阅问题

### ISSUE THREAD

**Issue by jxph1123** [fw876/helloworld#1127]
如下图，TLS主机名解析不出来，每次要手动填写。望大佬能解决，谢谢~~（passwall和手机端的V2rayNG都能正常解析）。如大佬需要，我可以提供订阅地址。
![ssr](https://user-images.githubusercontent.com/35351787/222887518-541b54a9-3a8c-4d39-a102-eaa12aa22afa.png)

**Comment by 1715173329** [comment]
如果你直接用 ssrp 订阅也有问题的话，需要把你的订阅链接给我看看了
邮件到 cnsztl@immortalwrt.org

**Comment by jxph1123** [comment]
> 如果你直接用 ssrp 订阅也有问题的话，需要把你的订阅链接给我看看了 邮件到 [cnsztl@immortalwrt.org](mailto:cnsztl@immortalwrt.org)

现在是从其他地方手动导入单个节点没问题，但是自动订阅还是没有TLS主机名。我已经把订阅地址发你邮箱了，谢谢大佬！

**Comment by jxph1123** [comment]
@1715173329 大佬，自动订阅还是没有解析到TLS主机名，订阅地址发你邮箱了，麻烦抽空修复下，非常感谢～～

**Comment by jxph1123** [comment]
感谢大佬，已正常~~
