### ISSUE TITLE
pdnsd怎么被取消了

### ISSUE THREAD

**Issue by tomxiang1** [fw876/helloworld#1130]
pdnsd怎么被取消了，个人感觉很好用，dns2tcp没有缓存功能，dnsmasq作者也是抠门有缓存1小时的限制，pdnsd就没有限制了，虽然老是老了点，但是好用就行。大佬能不能加回来呀。

**Comment by 1715173329** [comment]
dnsmasq 最长允许缓存一天。我不认为正常人的网络会需要超过这种时间长度的缓存。
dns2tcp 只有 pdnsd 的 13% 的大小，也不需要额外的补丁。

**Comment by tomxiang1** [comment]
> dnsmasq 最长允许缓存一天。我不认为正常人的网络会需要超过这种时间长度的缓存。 dns2tcp 只有 pdnsd 的 13% 的大小，也不需要额外的补丁。

老大，我已经测试过dnsmasq min-cache-ttl最大只能缓存3600秒，也就是1小时，怎么缓存到1天的呢？
