### ISSUE TITLE
切换设置项时界面消失并报错

### ISSUE THREAD

**Issue by umlka** [fw876/helloworld#1131]
比如从"访问控制"切换到 "客户端"时，luci界面会直接消失然后提示这个 "Unable to launch the requested CGI program: /www/cgi-bin/luci: No such file or directory"

**Comment by umlka** [comment]
刚从隔壁VSSR看到，似乎也有相同的报错

**Comment by 1715173329** [comment]
/etc/init.d/rpcd restart
或者重启

这是 luci 本身的问题。

**Comment by umlka** [comment]
不过目前这个问题只在ssrplus上面见到过

**Comment by pipihu** [comment]
> > 
> 
> 目前找到了[解决办法](https://github.com/xiaorouji/openwrt-passwall/blob/luci/luci-app-passwall/root/etc/uci-defaults/luci-passwall#L26-L27)

感谢分享，按照上面的方法在luci-ssr-plus文件中加入
`	set uhttpd.main.max_requests=50
	commit uhttpd`
之后，问题解决。

**Comment by ramondelee** [comment]
> > > 
> > 
> > 
> > 目前找到了[解决办法](https://github.com/xiaorouji/openwrt-passwall/blob/luci/luci-app-passwall/root/etc/uci-defaults/luci-passwall#L26-L27)
> 
> 感谢分享，按照上面的方法在luci-ssr-plus文件中加入 set uhttpd.main.max_requests=50 commit uhttpd 之后，问题解决。

我也遇到了，求教如何操作的？
