### ISSUE TITLE
Xray core更新1.8.0后，新三编译直接失败

### ISSUE THREAD

**Issue by lgfyxx1** [fw876/helloworld#1140]
ERROR: package/other/helloworld/xray-core failed to build.
make: *** [/home/runner/work/AutoBuild-Actions-BETA/AutoBuild-Actions-BETA/openwrt/include/toplevel.mk:230: world] Error 1
make -r world: build failed. Please re-run make with -j1 V=s or V=sc for a higher verbosity level to see what's going on

试了几次都是失败，使用更新前的Xraycore 1.7.5就没问题.

**Comment by 1715173329** [comment]
https://github.com/fw876/helloworld/issues/1134
