### ISSUE TITLE
[功能申请] 支持 Xray 1.8.0版本更新的REALITY 参数组合

### ISSUE THREAD

**Issue by chika0801** [fw876/helloworld#1143]
官方目前只有配置说明 https://github.com/XTLS/REALITY

**Comment by chika0801** [comment]
不好意思，没看仔细，才发现您13号就加了REALITY支持了，打扰了。

**Comment by pcvc** [comment]
@chika0801 加了REALITY支持了吗？怎么界面上不能直接设置？今天刚刚编译的固件升级后没看到可以设置REALITY的。

**Comment by chika0801** [comment]
https://github.com/chika0801/Xray-examples/tree/main/VLESS-XTLS-uTLS-REALITY#shadowsocksr-plus-%E9%85%8D%E7%BD%AE%E7%A4%BA%E4%BE%8B
参考这个

**Comment by pcvc** [comment]
@chika0801 谢谢！我也想直接修改config，能告知一下openwrt里的配置文件是存放在哪里吗？

**Comment by chika0801** [comment]
OP系统我不熟悉，配置文件我知道在 /tmp/etc/ssrplus/tcp-udp-ssr-retcp.json

问题是 /tmp是内存的临时文件样 你改了，还要研究用什么命令重新xray生效。
