### ISSUE TITLE
添加强制走代理域名，保存并应用显示“没有待应用的更改“

### ISSUE THREAD

**Issue by zlwu** [fw876/helloworld#1145]
基于官方的rom（openwrt 22.03.3），添加“强制走代理域名”，“保存并应用”显示“没有待应用的更改“，服务也不重启。
我看了一下/etc/ssrplus/black.list，域名也确实添加进去了，不知道为什么没有检测到配置发生了变化，日志也没有错误信息。

**Comment by 1715173329** [comment]
需要手动在启动项里面重载服务

**Comment by 1715173329** [comment]
系统 启动项，或者 /etc/init.d/shadowsocksr restart
