### ISSUE TITLE
大佬，能不能把访问控制中禁止连接域名排除在外。

### ISSUE THREAD

**Issue by swxk521** [fw876/helloworld#115]
禁止连接域名要生效，要开启SSR去广告。

**Comment by coolsnowwolf** [comment]
本来就属于去广告功能的一部分，合乎逻辑

**Comment by hcym** [comment]
这个方便强大，大雕那个传家宝adplus早就不用了😂

**Comment by 82kg** [comment]
其实 <禁止连接域> 功能是很好的。 但是前提要开启去广告。 开启去广告后，其实有很多网页会不正常，就比如默认的anti-ad。
今日头条app 里的搜索会不正常。但是anti-ad作者又说好的。。。。。。。。。。

**Comment by 82kg** [comment]
> 本来就属于去广告功能的一部分，合乎逻辑

估计楼主想表达的是能不能 把禁止访问域名功能 独立生效。

其实 <禁止连接域> 功能是很好的。 但是前提要开启去广告。 开启去广告后，其实有很多网页会不正常，就比如默认的anti-ad。
今日头条app 里的搜索会不正常。但是anti-ad作者又说好的。。。。。。。。。。
