### ISSUE TITLE
[功能申请] 在 编辑节点 信息界面，添加 VLESS 协议的 "routeOnly":  参数选择框

### ISSUE THREAD

**Issue by chika0801** [fw876/helloworld#1154]
Xray文档 https://xtls.github.io/Xray-docs-next/config/inbound.html#inboundobject

希望增加此参数的选择框，默认不选择，如果需要手动勾选。

选后，使发送到服务端的请求，地址仍为在路由器上DNS解析得到的那个 IP。（配合服务端不用域名嗅探参数）

```
routeOnly: true | false

将嗅探得到的域名仅用于路由，代理目标地址仍为 IP。默认值为 false。
```

**Comment by 1715173329** [comment]
ssrplus 不使用内部的路由功能，开启 sniffer 以应对 DNS 污染，需要关闭自行更改配置生成脚本即可。
