### ISSUE TITLE
Needs new maintainer

### ISSUE THREAD

**Issue by 1715173329** [fw876/helloworld#1158]
Since I've moved to the latest nftables & js luci based OpenWrt 23.xx branch, I cannot continue maintaining this project. Hope someone who familiar with luci-app-ssr-plus can take over the maintenance.

**Comment by syscca** [comment]
想问下你维护的nftables & js luci based OpenWrt 23.xx在那。

**Comment by KevinMX** [comment]
> > Since I've moved to the latest nftables & js luci based OpenWrt 23.xx branch, I cannot continue maintaining this project. Hope someone who familiar with luci-app-ssr-plus can take over the maintenance.
> 
> 好事儿，主流的新技术始终是不能阻挡的，早晚要拥抱这些的
> 
> 那么，23.xx的话，用哪个工具替代ssrp呢？

You may want to check: https://github.com/immortalwrt/homeproxy

**Comment by hqvv** [comment]
> > Since I've moved to the latest nftables & js luci based OpenWrt 23.xx branch, I cannot continue maintaining this project. Hope someone who familiar with luci-app-ssr-plus can take over the maintenance.
> 
> 好事儿，主流的新技术始终是不能阻挡的，早晚要拥抱这些的
> 
> 那么，23.xx的话，用哪个工具替代ssrp呢？

https://github.com/yichya/luci-app-xray/tree/versplit  这个项目也全面升级到 fw4了

**Comment by coolsnowwolf** [comment]
等新技术的问题都解决再说吧，自然会跟进，这不是不可逾越的鸿沟。不想因为新而新。

**Comment by dt99** [comment]
开源社区后劲不足啊

**Comment by zhengmz** [comment]
> 等新技术的问题都解决再说吧，自然会跟进，这不是不可逾越的鸿沟。不想因为新而新。

老大，好奇问一下新技术的问题主要是什么？
