### ISSUE TITLE
ERROR: package/ssr-plus/ipt2socks failed to build.

### ISSUE THREAD

**Issue by umlka** [fw876/helloworld#1189]
- ubuntu-22.04
```bash
SHELL= flock /home/runner/work/Actions-OpenWrt/Actions-OpenWrt/openwrt/tmp/.ipt2socks-1.1.3.tar.gz.flock -c '  	/home/runner/work/Actions-OpenWrt/Actions-OpenWrt/openwrt/scripts/download.pl "/home/runner/work/Actions-OpenWrt/Actions-OpenWrt/openwrt/dl" "ipt2socks-1.1.3.tar.gz" "73a2498dc95934c225d358707e7f7d060b5ce81aa45260ada09cbd15207d27d1" "" "https://codeload.github.com/zfl9/ipt2socks/tar.gz/v1.1.3?"    '
+ curl -f --connect-timeout 20 --retry 5 --location https://codeload.github.com/zfl9/ipt2socks/tar.gz/v1.1.3?/ipt2socks-1.1.3.tar.gz
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100  109k  100  109k    0     0   868k      0 --:--:-- --:--:-- --:--:--  875k
Hash of the downloaded file does not match (file: 5279eb1cb7555cf9292423cc9f672dc43e6e214b3411a6df26a6a1cfa59d88b7, requested: 73a2498dc95934c225d358707e7f7d060b5ce81aa45260ada09cbd15207d27d1) - deleting download.
+ curl -f --connect-timeout 20 --retry 5 --location https://sources.cdn.openwrt.org/ipt2socks-1.1.3.tar.gz
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
  0   169    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
curl: (22) The requested URL returned error: 404
Download failed.
+ curl -f --connect-timeout 20 --retry 5 --location https://sources.openwrt.org/ipt2socks-1.1.3.tar.gz
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
  0   169    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
curl: (22) The requested URL returned error: 404
Download failed.
+ curl -f --connect-timeout 20 --retry 5 --location https://mirror2.openwrt.org/sources/ipt2socks-1.1.3.tar.gz
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
  0   153    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
curl: (22) The requested URL returned error: 404
Download failed.
No more mirrors to try - giving up.
```

**Comment by wuxjjj** [comment]
same problem happened when compile the firmware using P3TERX's action since yesterday.

also find following log during "download package" session

make[2] -C feeds/helloworld/dns2socks download
 make[2] -C feeds/helloworld/chinadns-ng download
 make[2] -C feeds/helloworld/luci-app-ssr-plus download
 make[2] -C feeds/helloworld/dns2tcp download
 make[2] -C feeds/helloworld/lua-neturl download
 make[2] -C feeds/helloworld/ipt2socks download
 make[2] -C feeds/helloworld/microsocks download
 make[2] -C feeds/helloworld/shadowsocksr-libev download
 make[2] -C feeds/helloworld/simple-obfs download
 make[2] -C feeds/helloworld/tcping download
 make[2] -C feeds/helloworld/trojan download
 make[2] -C feeds/helloworld/v2ray-plugin download
 make[2] -C feeds/helloworld/xray-core download
 make[2] -C feeds/luci/collections/luci download
 make[2] -C feeds/luci/applications/luci-app-accesscontrol download
 make[2] -C feeds/luci/applications/luci-app-adbyby-plus download
 make[2] -C feeds/luci/applications/luci-app-advanced-reboot download
 make[2] -C feeds/luci/applications/luci-app-arpbind download
    ERROR: package/feeds/helloworld/ipt2socks failed to build.
make package/download: build failed. Please re-run make with -j1 V=s or V=sc for a higher verbosity level to see what's going on
 make[1] target/download
 make[2] -C target/linux download

**Comment by jmdweem** [comment]
因为ipt2socks这个依赖最近更新导致源码包的hash值变了，你改一下makefile的hash值就行了

**Comment by wuxjjj** [comment]
> 因为ipt2socks这个依赖最近更新导致源码包的hash值变了，你改一下makefile的hash值就行了

谢谢

**Comment by binge8** [comment]
> 因为ipt2socks这个依赖最近更新导致源码包的hash值变了，你改一下makefile的hash值就行了

改hash也不行吧，好像直接下架了，您再看看

**Comment by ypdenet** [comment]
https://mirror2.openwrt.org/sources/ipt2socks-1.1.3.tar.gz  404 Not Found  文件不存在了

**Comment by binge8** [comment]
https://github.com/fw876/helloworld/pull/1191

**Comment by wilson-chan2019** [comment]
进入dl文件夹
wget https://sources.immortalwrt.org/ipt2socks-1.1.3.tar.gz
再重新编译

**Comment by wlk3773208** [comment]
SHELL= flock /home/a/lede/tmp/.ipt2socks-1.1.3.tar.gz.flock -c '  	/home/a/lede/scripts/download.pl "/home/a/lede/dl" "ipt2socks-1.1.3.tar.gz" "5279eb1cb7555cf9292423cc9f672dc43e6e214b3411a6df26a6a1cfa59d88b7" "" "https://codeload.github.com/zfl9/ipt2socks/tar.gz/v1.1.3?"    '
Hash of the local file ipt2socks-1.1.3.tar.gz does not match (file: 73a2498dc95934c225d358707e7f7d060b5ce81aa45260ada09cbd15207d27d1, requested: 5279eb1cb7555cf9292423cc9f672dc43e6e214b3411a6df26a6a1cfa59d88b7) - deleting download.

**Comment by mcusee** [comment]
怎么弄  怎么弄  怎么弄  怎么弄  怎么弄  怎么弄  

进入dl文件夹
wget https://sources.immortalwrt.org/ipt2socks-1.1.3.tar.gz
再重新编译

问题以就出现

**Comment by mcusee** [comment]
make[2] -C feeds/helloworld/dns2socks download
 make[2] -C feeds/helloworld/dns2tcp download
 make[2] -C feeds/helloworld/hysteria download
 make[2] -C feeds/helloworld/ipt2socks download
    ERROR: package/feeds/helloworld/ipt2socks failed to build.
make package/download: build failed. Please re-run make with -j1 V=s or V=sc for a higher verbosity level to see what's going on
 make[1] target/download

**Comment by binge8** [comment]
> make[2] -C feeds/helloworld/dns2socks download make[2] -C feeds/helloworld/dns2tcp download make[2] -C feeds/helloworld/hysteria download make[2] -C feeds/helloworld/ipt2socks download ERROR: package/feeds/helloworld/ipt2socks failed to build. make package/download: build failed. Please re-run make with -j1 V=s or V=sc for a higher verbosity level to see what's going on make[1] target/download

已经修复了，啥也不需要干，正常编译就对了

**Comment by onlyJinx** [comment]
我今天编译的时候也遇到这个问题, 想请教下应该怎么处理
我试着 清空后重新拉取, 但是没办法解决
```
./scripts/feeds clean
./scripts/feeds update -a
./scripts/feeds install -a
```
```
 make[2] -C feeds/helloworld/dns2socks download
 make[2] -C feeds/helloworld/chinadns-ng download
 make[2] -C package/base-files download
 make[2] -C feeds/helloworld/luci-app-ssr-plus download
    ERROR: package/feeds/helloworld/ipt2socks failed to build.
 make[2] -C feeds/helloworld/microsocks download
 make[2] -C package/boot/grub2 download
 make[2] -C package/boot/grub2 download
make package/download: build failed. Please re-run make with -j1 V=s or V=sc for a higher verbosity level to see what's going on
 make[1] target/download
 make[2] -C target/linux download
```

**Comment by onlyJinx** [comment]
忘了加V=s看详细了, 加上去之后发现是下载下来的文件hash之不匹配, 我自己进去`feeds/helloworld/ipt2socks/Makefile`改成一样的就可以了
```
make[2]: Leaving directory '/home/ruo/lede/feeds/helloworld/dns2socks'
time: package/feeds/helloworld/dns2socks/download#0.15#0.05#0.19
make[2]: Entering directory '/home/ruo/lede/feeds/helloworld/dns2tcp'
make[2]: Nothing to be done for 'download'.
make[2]: Leaving directory '/home/ruo/lede/feeds/helloworld/dns2tcp'
time: package/feeds/helloworld/dns2tcp/download#0.14#0.07#0.19
make[2]: Entering directory '/home/ruo/lede/feeds/helloworld/ipt2socks'
mkdir -p /home/ruo/lede/dl
SHELL= flock /home/ruo/lede/tmp/.ipt2socks-1.1.3.tar.gz.flock -c '      /home/ruo/lede/scripts/download.pl "/home/ruo/lede/dl" "ipt2socks-1.1.3.tar.gz" "5279eb1cb7555cf9292423cc9f672dc43e6e214b3411a6df26a6a1cfa59d88b7" "" "https://codeload.github.com/zfl9/ipt2socks/tar.gz/v1.1.3?"    '
Hash of the local file ipt2socks-1.1.3.tar.gz does not match (file: 73a2498dc95934c225d358707e7f7d060b5ce81aa45260ada09cbd15207d27d1, requested: 5279eb1cb7555cf9292423cc9f672dc43e6e214b3411a6df26a6a1cfa59d88b7) - deleting download.
Makefile:45: recipe for target '/home/ruo/lede/dl/ipt2socks-1.1.3.tar.gz' failed
make[2]: *** [/home/ruo/lede/dl/ipt2socks-1.1.3.tar.gz] Error 2
make[2]: Leaving directory '/home/ruo/lede/feeds/helloworld/ipt2socks'
time: package/feeds/helloworld/ipt2socks/download#0.19#0.06#0.25
    ERROR: package/feeds/helloworld/ipt2socks failed to build.
package/Makefile:114: recipe for target 'package/feeds/helloworld/ipt2socks/download' failed
make[1]: *** [package/feeds/helloworld/ipt2socks/download] Error 1
make[1]: Leaving directory '/home/ruo/lede'
make[1]: Entering directory '/home/ruo/lede'
make[2]: Entering directory '/home/ruo/lede/target/linux'
make[3]: Entering directory '/home/ruo/lede/target/linux/x86'
make[3]: Nothing to be done for 'download'.
make[3]: Leaving directory '/home/ruo/lede/target/linux/x86'
make[2]: Leaving directory '/home/ruo/lede/target/linux'
time: target/linux/download#0.06#0.02#0.08
make[1]: Leaving directory '/home/ruo/lede'
```
