### ISSUE TITLE
ERROR: package/feeds/helloworld/ipt2socks failed to build.

### ISSUE THREAD

**Issue by qqsir-dev** [fw876/helloworld#1192]
ERROR: package/feeds/helloworld/ipt2socks failed to build.

**Comment by wilson-chan2019** [comment]
进入dl文件夹
wget https://sources.immortalwrt.org/ipt2socks-1.1.3.tar.gz
再重新编译

**Comment by qqsir-dev** [comment]
> 进入dl文件夹 wget https://sources.immortalwrt.org/ipt2socks-1.1.3.tar.gz 再重新编译

好的，谢谢

**Comment by haohaoget** [comment]
> 

感谢完美解决
