### ISSUE TITLE
使用 trojan 节点时，无法访问该节点服务器其他服务

### ISSUE THREAD

**Issue by coaens** [fw876/helloworld#120]
我一直遇到一个问题，编译的好几个平台的都有。就是在使用 trojan 节点时（以 test.xyz 为该服务器域名为例），无法访问 test.xyz 上的网页，其他像 ssh 等服务也上不去。

我使用的是大陆白名单模式+pdnsd，白名单里设置了 test.xyz 这个域名直连。经过测试，换成同服务器 v2ray 的协议，就不存在这个问题。彻底关闭服务，也能登陆test.xyz。请问这个是什么问题呢？

**Comment by Nats-ji** [comment]
刚才我试了下我的，并没有遇到这个情况。你试试把路由器上的ssrplus关掉，然后用手机客户端trojan连接看看会不会也出现这个情况。

**Comment by coolsnowwolf** [comment]
测试并没有问题

**Comment by coaens** [comment]
> 刚才我试了下我的，并没有遇到这个情况。你试试把路由器上的ssrplus关掉，然后用手机客户端连接trojan看看会不会也出现这个情况。我猜有可能是nginx的配置问题

ssrplus 关闭，手机使用 shadowrocket 用的同样的 trojan 节点的话，不会出现这个问题

**Comment by coaens** [comment]
> 测试并没有问题

这个好像不会必然出现，但是如果改成 trojan 的节点，然后重启路由器的话，出现的几率比较高。改成 v2ray 连上后，再改 trojan 也能连上，但是过上一段时间，就又会连不上。我是在 n1 和 k2p 还有 ac2100 上试的，都有这个问题。

**Comment by zxlhhyccc** [comment]
> > 测试并没有问题
> 
> 这个好像不会必然出现，但是如果改成 trojan 的节点，然后重启路由器的话，出现的几率比较高。改成 v2ray 连上后，再改 trojan 也能连上，但是过上一段时间，就又会连不上。我是在 n1 和 k2p 还有 ac2100 上试的，都有这个问题。

我遇到就是时断时续。。。。

**Comment by Nats-ji** [comment]
不过我遇到的是有些域名打不开，比如steam和一些日本的域名。chrome会提示`Site can't be reached, Server IP address cannot be found`。我觉得有可能是dns查询的问题。把那些域名加入强制走代理就可以正常打开。
