### ISSUE TITLE
最新的潘多拉sdk编译过程中chinadns-ng报错

### ISSUE THREAD

**Issue by 725216** [fw876/helloworld#1215]
不知道怎么弄，请大家帮忙
cc1: note: someone does not honour COPTS correctly, passed 0 times
mipsel-openwrt-linux-uclibc-gcc -pipe -std=c99 -Wall -Wextra -Wvla -O3 -flto -flto-partition=none -fno-pie -fno-PIE -DNDEBUG -c -o dns.o dns.c
cc1: note: someone does not honour COPTS correctly, passed 0 times
mipsel-openwrt-linux-uclibc-gcc -pipe -std=c99 -Wall -Wextra -Wvla -O3 -flto -flto-partition=none -fno-pie -fno-PIE -DNDEBUG -c -o dnl.o dnl.c
cc1: note: someone does not honour COPTS correctly, passed 0 times
mipsel-openwrt-linux-uclibc-gcc -pipe -std=c99 -Wall -Wextra -Wvla -O3 -flto -flto-partition=none -fno-pie -fno-PIE -DNDEBUG -c -o net.o net.c
cc1: note: someone does not honour COPTS correctly, passed 0 times
mipsel-openwrt-linux-uclibc-gcc -pipe -std=c99 -Wall -Wextra -Wvla -O3 -flto -flto-partition=none -fno-pie -fno-PIE -DNDEBUG -c -o ipset.o ipset.c
cc1: note: someone does not honour COPTS correctly, passed 0 times
mipsel-openwrt-linux-uclibc-gcc -pipe -std=c99 -Wall -Wextra -Wvla -O3 -flto -flto-partition=none -fno-pie -fno-PIE -DNDEBUG -c -o nl.o nl.c
cc1: note: someone does not honour COPTS correctly, passed 0 times
mipsel-openwrt-linux-uclibc-gcc -pipe -no-pie -O3 -flto -flto-partition=none -s -o chinadns-ng main.o opt.o dns.o dnl.o net.o ipset.o nl.o
mipsel-openwrt-linux-uclibc-gcc: error: unrecognized command line option '-no-pie'
make[3]: *** [Makefile:52: chinadns-ng] Error 1
make[3]: Leaving directory '/home/rxy/7621/build_dir/target-mipsel_1004kc+dsp_uClibc-1.0.x/chinadns-ng-2023.04.20'
make[2]: *** [Makefile:39: /home/rxy/7621/build_dir/target-mipsel_1004kc+dsp_uClibc-1.0.x/chinadns-ng-2023.04.20/.built] Error 2
make[2]: Leaving directory '/home/rxy/7621/feeds/helloworld/chinadns-ng'
make[1]: *** [package/Makefile:106: package/feeds/helloworld/chinadns-ng/compile] Error 2
make[1]: Leaving directory '/home/rxy/7621'
make: *** [/home/rxy/7621/include/toplevel.mk:194: package/luci-app-ssr-plus/compile] Error 2

**Comment by hcym** [comment]
昨天肯定正常，今天的不知道，没更新就是你的问题了

**Comment by 725216** [comment]
> 昨天肯定正常，今天的不知道，没更新就是你的问题了

用 openwrt官方的正常，潘多拉固件的不正常

**Comment by coolsnowwolf** [comment]
gcc 小于8 的版本不支持这个参数
