### ISSUE TITLE
分流的问题依旧没解决

### ISSUE THREAD

**Issue by RikudouPatrickstar** [fw876/helloworld#122]
Netflix分流依然有问题，会跳到 https://www.netflix.com/cn/ ，版本180-1，用的SSR

**Comment by jy3344511** [comment]
Netflix分流依然有问题，升级到最新版180-1，在Netflix 分流域名列表里，添加新的域名，比如：ababab.com。在Netflix 分流服务器里，指定一个节点，实际使用中是不起作用的，起作用的仍然是主服务器下的节点。旧版的分流其实也是经常不起作用的，要在Netflix--IP地址里，填写域名ababab.com的实际IP地址，才会起作用，但是实际IP地址一般有好几个，只填写一个域名地址是没有用的。

**Comment by swxk521** [comment]
4.19.内核没问题

**Comment by hplee0120** [comment]
有没有使用adguard home，如果使用的是替换53端口或者重定向53端口模式就会有这问题，包括gfw模式。现在两插件最兼容的方案只剩作为dnsmasq的上游用是最保险的，就是adghome的客户端显示不出来

**Comment by RikudouPatrickstar** [comment]
> 有没有使用adguard home，如果使用的是替换53端口或者重定向53端口模式就会有这问题，包括gfw模式。现在两插件最兼容的方案只剩作为dnsmasq的上游用是最保险的，就是adghome的客户端显示不出来

没有，dns服务器只有dnsmasq一个

**Comment by RikudouPatrickstar** [comment]
或许是楼上说的内核原因吧，内核版本是5.4.52
