### ISSUE TITLE
希望能把SS-Shadow-TLS Plugin插件打包进去

### ISSUE THREAD

**Issue by Bformax** [fw876/helloworld#1221]
Hi
自从Trojan被墙了以后，我改用了SS-Shadow-TLS的方案，我用下来也感觉挺好的，就是SSR Plus+还没支持。
目前来看Clash.Meta, Surge，小火箭 都支持SS-Shadow-TLS Plugin，也算是进入主流了。
可惜，我这水平比较渣，没法提Pull Request，只能提个Issue。
SSR Plus+太好用了，既简单又方便，而且非常稳定，
希望有小伙伴能把这个功能加上。

感激不尽

项目地址 https://github.com/ihciah/shadow-tls

**Comment by zxlhhyccc** [comment]
关键是如何使用。。。。

**Comment by AmberisMyShiba** [comment]
If someone could make ShadowTLS as a SIP003 standard plugin for Shadowsocks. It will be an easier job.

**Comment by Bformax** [comment]
各位大佬好，主要是我没这个能力，不然我就不发出来麻烦大家了

就希望有没有大佬正在用这个协议，也在某个时候有点空余的时间，可以做一下

我在这里先谢谢各位啦

**Comment by AmberisMyShiba** [comment]
> Hi 自从Trojan被墙了以后，我改用了SS-Shadow-TLS的方案，我用下来也感觉挺好的，就是SSR Plus+还没支持。 目前来看Clash.Meta, Surge，小火箭 都支持SS-Shadow-TLS Plugin，也算是进入主流了。 可惜，我这水平比较渣，没法提Pull Request，只能提个Issue。 SSR Plus+太好用了，既简单又方便，而且非常稳定， 希望有小伙伴能把这个功能加上。
> 
> 感激不尽
> 
> 项目地址 https://github.com/ihciah/shadow-tls

shadow-tls可以在helloworld上跑起来的，速度还不错。但是这个repo还是在持续开发阶段，上游作者还没有大的更新让其更易于使用和移植，支持的架构也有限，在openwrt上也需要运行一段时间找找bug。
![Uploading Screenshot_2023-07-25-22-46-40-55_40deb401b9ffe8e1df2f1cc5ba480b12.jpg…]()

**Comment by Bformax** [comment]
> > Hi 自从Trojan被墙了以后，我改用了SS-Shadow-TLS的方案，我用下来也感觉挺好的，就是SSR Plus+还没支持。 目前来看Clash.Meta, Surge，小火箭 都支持SS-Shadow-TLS Plugin，也算是进入主流了。 可惜，我这水平比较渣，没法提Pull Request，只能提个Issue。 SSR Plus+太好用了，既简单又方便，而且非常稳定， 希望有小伙伴能把这个功能加上。
> 
> > 感激不尽
> > 项目地址 https://github.com/ihciah/shadow-tls
> 
> shadow-tls可以在helloworld上跑起来的，速度还不错。但是这个repo还是在持续开发阶段，支持的架构也有限，需要给上游作者更多的时间。另外移植到在openwrt上也需要运行一段时间找找bug。过一段时间你的要求就能被实现了。

谢谢大佬回复，不能说要求，只是我的愿景，因为我用起来还算挺好用的，对于现在sin阻断的白名单地区，意义很大，所以向社区提了这个需求
可惜自己水平太烂也没法为社区做贡献…
感谢大佬们的付出

**Comment by AmberisMyShiba** [comment]
系统中shadowsocks-rust  的朋友们，请你们试试看用配置文件运行的方式，打开sslocal  -c config.json，是否能正常运行。
 @zxlhhyccc   @Bformax

注意配置 文件必须有**locals**组，包含至少1组local配置，配置文件参考

{
  "log": {
    "level": 1
  },
  "locals": [
    {
      "local_address": "0.0.0.0",
      "local_port": 1234,
      "protocol": "redir",
      "tcp_redir": "redirect",
      "udp_redir": "tproxy",
      "server": "127.0.0.1",
      "server_port": 306,
      "method": "2022-blake3-aes-128-gcm",
      "password": ""
    }
  ]
}
password 可以用以下命令产生
**root@OpenWrt:~# openssl rand -base64 16**

**Comment by AmberisMyShiba** [comment]
> > > Hi 自从Trojan被墙了以后，我改用了SS-Shadow-TLS的方案，我用下来也感觉挺好的，就是SSR Plus+还没支持。 目前来看Clash.Meta, Surge，小火箭 都支持SS-Shadow-TLS Plugin，也算是进入主流了。 可惜，我这水平比较渣，没法提Pull Request，只能提个Issue。 SSR Plus+太好用了，既简单又方便，而且非常稳定， 希望有小伙伴能把这个功能加上。
> > 
> > 
> > > 感激不尽
> > > 项目地址 https://github.com/ihciah/shadow-tls
> > 
> > 
> > shadow-tls可以在helloworld上跑起来的，速度还不错。但是这个repo还是在持续开发阶段，支持的架构也有限，需要给上游作者更多的时间。另外移植到在openwrt上也需要运行一段时间找找bug。过一段时间你的要求就能被实现了。
> 
> 谢谢大佬回复，不能说要求，只是我的愿景，因为我用起来还算挺好用的，对于现在sin阻断的白名单地区，意义很大，所以向社区提了这个需求 可惜自己水平太烂也没法为社区做贡献… 感谢大佬们的付出
你有时间测试一下shadowtls的节点适配吗？

**Comment by AmberisMyShiba** [comment]
> > > Hi 自从Trojan被墙了以后，我改用了SS-Shadow-TLS的方案，我用下来也感觉挺好的，就是SSR Plus+还没支持。 目前来看Clash.Meta, Surge，小火箭 都支持SS-Shadow-TLS Plugin，也算是进入主流了。 可惜，我这水平比较渣，没法提Pull Request，只能提个Issue。 SSR Plus+太好用了，既简单又方便，而且非常稳定， 希望有小伙伴能把这个功能加上。
> > 
> > 
> > > 感激不尽
> > > 项目地址 https://github.com/ihciah/shadow-tls
> > 
> > 
> > shadow-tls可以在helloworld上跑起来的，速度还不错。但是这个repo还是在持续开发阶段，支持的架构也有限，需要给上游作者更多的时间。另外移植到在openwrt上也需要运行一段时间找找bug。过一段时间你的要求就能被实现了。
> 
> 谢谢大佬回复，不能说要求，只是我的愿景，因为我用起来还算挺好用的，对于现在sin阻断的白名单地区，意义很大，所以向社区提了这个需求 可惜自己水平太烂也没法为社区做贡献… 感谢大佬们的付出

@Bformax 请问你有时间测试一下shadowtls for ssrp的相关功能吗？

**Comment by Bformax** [comment]
> > Hi 自从Trojan被墙了以后，我改用了SS-Shadow-TLS的方案，我用下来也感觉挺好的，就是SSR Plus+还没支持。 目前来看Clash.Meta, Surge，小火箭 都支持SS-Shadow-TLS Plugin，也算是进入主流了。 可惜，我这水平比较渣，没法提Pull Request，只能提个Issue。 SSR Plus+太好用了，既简单又方便，而且非常稳定， 希望有小伙伴能把这个功能加上。
> 
> > 感激不尽
> > 项目地址 https://github.com/ihciah/shadow-tls
> 
> shadow-tls可以在helloworld上跑起来的，速度还不错。但是这个repo还是在持续开发阶段，支持的架构也有限，需要给上游作者更多的时间。另外移植到在openwrt上也需要运行一段时间找找bug。过一段时间你的要求就能被实现了。

Hi 
我收到了多封邮件，这个需要怎么测试呢？

**Comment by AmberisMyShiba** [comment]
> > > Hi 自从Trojan被墙了以后，我改用了SS-Shadow-TLS的方案，我用下来也感觉挺好的，就是SSR Plus+还没支持。 目前来看Clash.Meta, Surge，小火箭 都支持SS-Shadow-TLS Plugin，也算是进入主流了。 可惜，我这水平比较渣，没法提Pull Request，只能提个Issue。 SSR Plus+太好用了，既简单又方便，而且非常稳定， 希望有小伙伴能把这个功能加上。
> > 
> > 
> > > 感激不尽
> > > 项目地址 https://github.com/ihciah/shadow-tls
> > 
> > 
> > shadow-tls可以在helloworld上跑起来的，速度还不错。但是这个repo还是在持续开发阶段，支持的架构也有限，需要给上游作者更多的时间。另外移植到在openwrt上也需要运行一段时间找找bug。过一段时间你的要求就能被实现了。
> 
> Hi 我收到了多封邮件，这个需要怎么测试呢？

The latest PR has supported shadow-TLS.

**Comment by Bformax** [comment]
> > > > Hi 自从Trojan被墙了以后，我改用了SS-Shadow-TLS的方案，我用下来也感觉挺好的，就是SSR Plus+还没支持。 目前来看Clash.Meta, Surge，小火箭 都支持SS-Shadow-TLS Plugin，也算是进入主流了。 可惜，我这水平比较渣，没法提Pull Request，只能提个Issue。 SSR Plus+太好用了，既简单又方便，而且非常稳定， 希望有小伙伴能把这个功能加上。
> > > 
> > > 
> > > > 感激不尽
> > > > 项目地址 https://github.com/ihciah/shadow-tls
> > > 
> > > 
> > > shadow-tls可以在helloworld上跑起来的，速度还不错。但是这个repo还是在持续开发阶段，支持的架构也有限，需要给上游作者更多的时间。另外移植到在openwrt上也需要运行一段时间找找bug。过一段时间你的要求就能被实现了。
> > 
> > 
> > Hi 我收到了多封邮件，这个需要怎么测试呢？
> 
> The latest PR has supported shadow-TLS.

哇哦🎉 非常感谢你的付出，我出差回来就试试
