### ISSUE TITLE
主服务器指定v2ray节点 dns无法解析

### ISSUE THREAD

**Issue by JunyuMu** [fw876/helloworld#126]
刚买的机场，手机端`Shadowrocket`、电脑端`V2RayX`均能正常使用。
路由器上主服务器选择v2ray节点，无法解析国外域名。

![image](https://user-images.githubusercontent.com/15103817/88499236-d96ea400-cff7-11ea-8e90-94a8d14eb68c.png)

```bash
# nslookup
Server:           127.0.0.1
Address:          127.0.0.1#53

*** Can't find google.com: No answer
*** Can't find google.com: No answer
```

是我哪里设置有问题么？

**Comment by smallprogram** [comment]
need vmess url

**Comment by JunyuMu** [comment]
机场不能分享账号。。。
是ws+tls的方式

**Comment by smallprogram** [comment]
大概Config.json的格式总可以吧。乱写个UUID、端口、server地址等

**Comment by JunyuMu** [comment]
![image](https://user-images.githubusercontent.com/15103817/88522736-654cf400-d029-11ea-803b-ab50a5284280.png)

**Comment by JunyuMu** [comment]
这是`Shadowrocket`上复制的JSON

```json
{
  "obfsParam" : "",
  "weight" : 1595568753,
  "title" : "",
  "host" : "server.com",
  "file" : "\/ws",
  "uuid" : "4B2581CA-9A7D-44E1-9927-4C58CC0B9B81",
  "method" : "auto",
  "flag" : "JP",
  "updated" : 1595831405.9798841,
  "obfs" : "websocket",
  "chain" : "",
  "type" : "Vmess",
  "cert" : "",
  "plugin" : "none",
  "user" : "",
  "protoParam" : "",
  "tls" : true,
  "port" : 443,
  "proto" : "",
  "peer" : "",
  "password" : "xxxxxxxxxx",
  "data" : "",
  "ping" : 154,
  "created" : 1595568753.572696
}
```

**Comment by smallprogram** [comment]
> 这是`Shadowrocket`上复制的JSON
> 
> 
> 
> ```json
> 
> {
> 
>   "obfsParam" : "",
> 
>   "weight" : 1595568753,
> 
>   "title" : "",
> 
>   "host" : "server.com",
> 
>   "file" : "\/ws",
> 
>   "uuid" : "4B2581CA-9A7D-44E1-9927-4C58CC0B9B81",
> 
>   "method" : "auto",
> 
>   "flag" : "JP",
> 
>   "updated" : 1595831405.9798841,
> 
>   "obfs" : "websocket",
> 
>   "chain" : "",
> 
>   "type" : "Vmess",
> 
>   "cert" : "",
> 
>   "plugin" : "none",
> 
>   "user" : "",
> 
>   "protoParam" : "",
> 
>   "tls" : true,
> 
>   "port" : 443,
> 
>   "proto" : "",
> 
>   "peer" : "",
> 
>   "password" : "xxxxxxxxxx",
> 
>   "data" : "",
> 
>   "ping" : 154,
> 
>   "created" : 1595568753.572696
> 
> }
> 
> ```

我指的是v2ray的客户端配置.....

**Comment by JunyuMu** [comment]
额。。我没看到在哪导出json。。
