### ISSUE TITLE
SSRP里面的TUIC是不支持IPQ40XX吗

### ISSUE THREAD

**Issue by kvmcore** [fw876/helloworld#1262]
Makefile里面没有arm, 编译菜单也不显示TUIC   :(

![截图 2023-09-05 19-18-24](https://github.com/fw876/helloworld/assets/3048370/b8b6aedf-bcb5-4e2b-b7a9-05668292dc1b)

![截图 2023-09-05 19-20-19](https://github.com/fw876/helloworld/assets/3048370/04f08836-2995-412b-8406-5d9c9f314cfd)

**Comment by AmberisMyShiba** [comment]
自己添加一个，然后PR一下。

**Comment by kvmcore** [comment]
> 已经PR了，等owner有空了merge合并吧。

makefile添加arm后，编译菜单是能显示tuic-client，但是勾选tuic-client，luci-app-ssr-plus会消失不见，应该还有哪里得再改一改 :D

**Comment by AmberisMyShiba** [comment]
> > 已经PR了，等owner有空了merge合并吧。
> 
> makefile添加arm后，编译菜单是能显示tuic-client，但是勾选tuic-client，luci-app-ssr-plus会消失不见，应该还有哪里得再改一改 :D
我查询了一下openwrt的官网，IPQ40XX属于[arm_cortex-a7_neon-vfpv4]架构，tuic官方没有预编译的版本。你放弃吧。

**Comment by AmberisMyShiba** [comment]
> > > > 已经PR了，等owner有空了merge合并吧。
> > > 
> > > 
> > > makefile添加arm后，编译菜单是能显示tuic-client，但是勾选tuic-client，luci-app-ssr-plus会消失不见，应该还有哪里得再改一改 :D
> > > 我查询了一下openwrt的官网，IPQ40XX属于[arm_cortex-a7_neon-vfpv4]架构，tuic官方没有预编译的版本。你放弃吧。
> 
> 讲真，我的IPQ40XX已经用隔壁passwall2跑tuic了，提issue就想看看IPQ40XX能不能通过SSRP跑tuic :D

passwall2用的是sing-box的内核，sing-box是全集成的平台，囊括了主流协议，所以自带tuic的outbound

**Comment by kvmcore** [comment]
> > > > > 已经PR了，等owner有空了merge合并吧。
> > > > 
> > > > 
> > > > makefile添加arm后，编译菜单是能显示tuic-client，但是勾选tuic-client，luci-app-ssr-plus会消失不见，应该还有哪里得再改一改 :D
> > > > 我查询了一下openwrt的官网，IPQ40XX属于[arm_cortex-a7_neon-vfpv4]架构，tuic官方没有预编译的版本。你放弃吧。
> > 
> > 
> > 讲真，我的IPQ40XX已经用隔壁passwall2跑tuic了，提issue就想看看IPQ40XX能不能通过SSRP跑tuic :D
> 
> passwall2用的是sing-box的内核，sing-box是全集成的平台，囊括了主流协议，所以自带tuic的outbound。helloworld和passwall2的开发理念有所不同，一个注重原生协议，用最精简的功能实现最极致的性能，另一个注重集大成的平台，功能多，但是在原生功能的配置上有所妥协。

好吧，主要也是想SSRP能支持tuic for IPQ4XX，毕竟用习惯了，既然不支持也是没有办法，pw2勉强用。

**Comment by AmberisMyShiba** [comment]
> > > > > > 已经PR了，等owner有空了merge合并吧。
> > > > > 
> > > > > 
> > > > > makefile添加arm后，编译菜单是能显示tuic-client，但是勾选tuic-client，luci-app-ssr-plus会消失不见，应该还有哪里得再改一改 :D
> > > > > 我查询了一下openwrt的官网，IPQ40XX属于[arm_cortex-a7_neon-vfpv4]架构，tuic官方没有预编译的版本。你放弃吧。
> > > 
> > > 
> > > 讲真，我的IPQ40XX已经用隔壁passwall2跑tuic了，提issue就想看看IPQ40XX能不能通过SSRP跑tuic :D
> > 
> > 
> > passwall2用的是sing-box的内核，sing-box是全集成的平台，囊括了主流协议，所以自带tuic的outbound。helloworld和passwall2的开发理念有所不同，一个注重原生协议，用最精简的功能实现最极致的性能，另一个注重集大成的平台，功能多，但是在原生功能的配置上有所妥协。
> 
> 好吧，主要也是想SSRP能支持tuic for IPQ4XX，毕竟用习惯了，既然不支持也是没有办法，pw2勉强用。

我没有IPQ4XX的开发环境，你可以先看看tuic的官方release，找找有没有预编译的二进制文件可以在你的机器上运行的，如果有可以运行在IPQ4XX上的二进制文件，那就可以想办法支持。
