### ISSUE TITLE
GO applications build error.

### ISSUE THREAD

**Issue by dementeb** [fw876/helloworld#1269]
Good day.
First of all, thank you for your work and excellent program.
If this is acceptable, I need some help please.
I'm trying to build packages for siflower architecture, gl-inet sft1200 router.
I'm using a manufacturer's SDK that builds for openwrt 18.06, debian 11 OS. I also updated GO Lang, as written in the readme file, and (as a brain storm) - as described in issue #1254.
I successfully assemble many components - shadowsocksr-libev, luci-app-ssr-plus, chinadns-ng and others. But I can't build xray-core, v2ray-core, naiveproxy and some others. The error when assembling them is the same, and I could not find a similar one in other reports and discussions.

I'd appreciate any hints. Thank you.

Here's a build log:

`#
# configuration written to .config
#
make[1]: Entering directory '/home/builder/src/glinet/sdk/sdk/1806/siflower'
make[2]: Entering directory '/home/builder/src/glinet/sdk/sdk/1806/siflower/package/toolchain'
echo "libc" >> /home/builder/src/glinet/sdk/sdk/1806/siflower/staging_dir/target-mipsel_mips-interAptiv_musl/pkginfo/toolchain.default.install
echo "libgcc" >> /home/builder/src/glinet/sdk/sdk/1806/siflower/staging_dir/target-mipsel_mips-interAptiv_musl/pkginfo/toolchain.default.install
echo "libpthread" >> /home/builder/src/glinet/sdk/sdk/1806/siflower/staging_dir/target-mipsel_mips-interAptiv_musl/pkginfo/toolchain.default.install
touch -r /home/builder/src/glinet/sdk/sdk/1806/siflower/build_dir/target-mipsel_mips-interAptiv_musl/toolchain/.built /home/builder/src/glinet/sdk/sdk/1806/siflower/build_dir/target-mipsel_mips-interAptiv_musl/toolchain/.autoremove 2>/dev/null >/dev/null
find /home/builder/src/glinet/sdk/sdk/1806/siflower/build_dir/target-mipsel_mips-interAptiv_musl/toolchain -mindepth 1 -maxdepth 1 -not '(' -type f -and -name '.*' -and -size 0 ')' -and -not -name '.pkgdir' | xargs -r rm -rf
make[2]: Leaving directory '/home/builder/src/glinet/sdk/sdk/1806/siflower/package/toolchain'
time: package/toolchain/compile#0.11#0.03#0.12
make[2]: Entering directory '/home/builder/src/glinet/sdk/sdk/1806/siflower/feeds/base/openwrt-18.06/package/system/ca-certificates'
touch -r /home/builder/src/glinet/sdk/sdk/1806/siflower/build_dir/target-mipsel_mips-interAptiv_musl/ca-certificates/.built /home/builder/src/glinet/sdk/sdk/1806/siflower/build_dir/target-mipsel_mips-interAptiv_musl/ca-certificates/.autoremove 2>/dev/null >/dev/null
find /home/builder/src/glinet/sdk/sdk/1806/siflower/build_dir/target-mipsel_mips-interAptiv_musl/ca-certificates -mindepth 1 -maxdepth 1 -not '(' -type f -and -name '.*' -and -size 0 ')' -and -not -name '.pkgdir' | xargs -r rm -rf
make[2]: Leaving directory '/home/builder/src/glinet/sdk/sdk/1806/siflower/feeds/base/openwrt-18.06/package/system/ca-certificates'
time: package/feeds/base/ca-certificates/compile#0.10#0.03#0.11
make[2]: Entering directory '/home/builder/src/glinet/sdk/sdk/1806/siflower/feeds/gli_pub/golang/golang'
find /home/builder/src/glinet/sdk/sdk/1806/siflower/build_dir/hostpkg/go-1.17.8 -mindepth 1 -maxdepth 1 -not '(' -type f -and -name '.*' -and -size 0 ')' | xargs -r rm -rf
make[2]: Leaving directory '/home/builder/src/glinet/sdk/sdk/1806/siflower/feeds/gli_pub/golang/golang'
time: package/feeds/gli_pub/golang/host-compile#0.14#0.03#0.15
make[2]: Entering directory '/home/builder/src/glinet/sdk/sdk/1806/siflower/feeds/helloworld/hysteria'
rm -f /home/builder/src/glinet/sdk/sdk/1806/siflower/build_dir/target-mipsel_mips-interAptiv_musl/hysteria-app-v2.0.0/.built
touch /home/builder/src/glinet/sdk/sdk/1806/siflower/build_dir/target-mipsel_mips-interAptiv_musl/hysteria-app-v2.0.0/.built_check
CONFIG_GOLANG_MOD_CACHE_WORLD_READABLE="" GO_BUILD_CACHE_DIR="/home/builder/src/glinet/sdk/sdk/1806/siflower/tmp/go-build" GO_MOD_CACHE_DIR="/home/builder/src/glinet/sdk/sdk/1806/siflower/dl/go-mod-cache" GO_MOD_ARGS="-modcacherw" GO_PKG="github.com/apernet/hysteria" GO_INSTALL_EXTRA="" GO_INSTALL_ALL="" GO_SOURCE_ONLY="" GO_BUILD_PKG="github.com/apernet/hysteria/app" GO_EXCLUDES="" GO_GO_GENERATE="" GO_INSTALL_BIN_PATH="/usr/bin" BUILD_DIR="/home/builder/src/glinet/sdk/sdk/1806/siflower/build_dir/target-mipsel_mips-interAptiv_musl/hysteria-app-v2.0.0" GO_BUILD_DIR="/home/builder/src/glinet/sdk/sdk/1806/siflower/build_dir/target-mipsel_mips-interAptiv_musl/hysteria-app-v2.0.0/.go_work/build" GO_BUILD_BIN_DIR="/home/builder/src/glinet/sdk/sdk/1806/siflower/build_dir/target-mipsel_mips-interAptiv_musl/hysteria-app-v2.0.0/.go_work/build/bin/linux_mipsle" GO_BUILD_DEPENDS_PATH="/usr/share/gocode" GO_BUILD_DEPENDS_SRC="/home/builder/src/glinet/sdk/sdk/1806/siflower/staging_dir/target-mipsel_mips-interAptiv_musl/usr/share/gocode/src" GOOS="linux" GOARCH="mipsle" GO386="" GOAMD64="" GOARM="" GOMIPS="softfloat" GOMIPS64="" GOPPC64="" CGO_ENABLED=1 CC="mipsel-openwrt-linux-musl-gcc" CXX="mipsel-openwrt-linux-musl-g++" CGO_CFLAGS="-Os -pipe -mno-branch-likely -fno-caller-saves -fno-plt -fhonour-copts -Wno-error=unused-but-set-variable -Wno-error=unused-result -iremap/home/builder/src/glinet/sdk/sdk/1806/siflower/build_dir/target-mipsel_mips-interAptiv_musl/hysteria-app-v2.0.0:hysteria-app-v2.0.0 -Wformat -Werror=format-security -fstack-protector -D_FORTIFY_SOURCE=1 -Wl,-z,now -Wl,-z,relro" CGO_CPPFLAGS="-I/home/builder/src/glinet/sdk/sdk/1806/siflower/staging_dir/target-mipsel_mips-interAptiv_musl/usr/include -I/home/builder/src/glinet/sdk/sdk/1806/siflower/staging_dir/target-mipsel_mips-interAptiv_musl/include -I/home/builder/src/glinet/sdk/sdk/1806/siflower/staging_dir/toolchain-mipsel_mips-interAptiv_gcc-7.4.0_musl/usr/include -I/home/builder/src/glinet/sdk/sdk/1806/siflower/staging_dir/toolchain-mipsel_mips-interAptiv_gcc-7.4.0_musl/include/fortify -I/home/builder/src/glinet/sdk/sdk/1806/siflower/staging_dir/toolchain-mipsel_mips-interAptiv_gcc-7.4.0_musl/include" CGO_CXXFLAGS="-Os -pipe -mno-branch-likely -fno-caller-saves -fno-plt -fhonour-copts -Wno-error=unused-but-set-variable -Wno-error=unused-result -iremap/home/builder/src/glinet/sdk/sdk/1806/siflower/build_dir/target-mipsel_mips-interAptiv_musl/hysteria-app-v2.0.0:hysteria-app-v2.0.0 -Wformat -Werror=format-security -fstack-protector -D_FORTIFY_SOURCE=1 -Wl,-z,now -Wl,-z,relro" CGO_LDFLAGS="-L/home/builder/src/glinet/sdk/sdk/1806/siflower/staging_dir/target-mipsel_mips-interAptiv_musl/usr/lib -L/home/builder/src/glinet/sdk/sdk/1806/siflower/staging_dir/target-mipsel_mips-interAptiv_musl/lib -L/home/builder/src/glinet/sdk/sdk/1806/siflower/staging_dir/toolchain-mipsel_mips-interAptiv_gcc-7.4.0_musl/usr/lib -L/home/builder/src/glinet/sdk/sdk/1806/siflower/staging_dir/toolchain-mipsel_mips-interAptiv_gcc-7.4.0_musl/lib -znow -zrelro" GOPATH="/home/builder/src/glinet/sdk/sdk/1806/siflower/build_dir/target-mipsel_mips-interAptiv_musl/hysteria-app-v2.0.0/.go_work/build" GOCACHE="/home/builder/src/glinet/sdk/sdk/1806/siflower/tmp/go-build" GOMODCACHE="/home/builder/src/glinet/sdk/sdk/1806/siflower/dl/go-mod-cache" GOENV=off GOTOOLCHAIN=local /usr/bin/env bash /home/builder/src/glinet/sdk/sdk/1806/siflower/feeds/packages/lang/golang//golang-build.sh build -v -buildvcs=false -trimpath -ldflags "all=-buildid '1622429458' -linkmode external -extldflags '-L/home/builder/src/glinet/sdk/sdk/1806/siflower/staging_dir/target-mipsel_mips-interAptiv_musl/usr/lib -L/home/builder/src/glinet/sdk/sdk/1806/siflower/staging_dir/target-mipsel_mips-interAptiv_musl/lib -L/home/builder/src/glinet/sdk/sdk/1806/siflower/staging_dir/toolchain-mipsel_mips-interAptiv_gcc-7.4.0_musl/usr/lib -L/home/builder/src/glinet/sdk/sdk/1806/siflower/staging_dir/toolchain-mipsel_mips-interAptiv_gcc-7.4.0_musl/lib -Wl,-z,now -Wl,-z,relro'"     -installsuffix "softfloat"   -ldflags " -X github.com/apernet/hysteria/app/cmd.appVersion=v2.0.0 -X github.com/apernet/hysteria/app/cmd.appType=release -X github.com/apernet/hysteria/app/cmd.appPlatform=linux -X github.com/apernet/hysteria/app/cmd.appArch=mipsle -buildid '1622429458' -linkmode external -extldflags '-L/home/builder/src/glinet/sdk/sdk/1806/siflower/staging_dir/target-mipsel_mips-interAptiv_musl/usr/lib -L/home/builder/src/glinet/sdk/sdk/1806/siflower/staging_dir/target-mipsel_mips-interAptiv_musl/lib -L/home/builder/src/glinet/sdk/sdk/1806/siflower/staging_dir/toolchain-mipsel_mips-interAptiv_gcc-7.4.0_musl/usr/lib -L/home/builder/src/glinet/sdk/sdk/1806/siflower/staging_dir/toolchain-mipsel_mips-interAptiv_gcc-7.4.0_musl/lib -Wl,-z,now -Wl,-z,relro'"  
Finding targets
no required module provides package github.com/apernet/hysteria/app: go.mod file not found in current directory or any parent directory; see 'go help modules'

Building targets
flag provided but not defined: -buildvcs
usage: go install [build flags] [packages]
Run 'go help install' for details.

make[2]: *** [Makefile:61: /home/builder/src/glinet/sdk/sdk/1806/siflower/build_dir/target-mipsel_mips-interAptiv_musl/hysteria-app-v2.0.0/.built] Error 2
make[2]: Leaving directory '/home/builder/src/glinet/sdk/sdk/1806/siflower/feeds/helloworld/hysteria'
time: package/feeds/helloworld/hysteria/compile#0.11#0.05#0.15
make[1]: *** [package/Makefile:122: package/feeds/helloworld/hysteria/compile] Error 2
make[1]: Leaving directory '/home/builder/src/glinet/sdk/sdk/1806/siflower'
make: *** [/home/builder/src/glinet/sdk/sdk/1806/siflower/include/toplevel.mk:211: package/feeds/helloworld/hysteria/compile] Error 2
`

**Comment by AmberisMyShiba** [comment]
hi dude,Change this:

go env -w GO111MODULE=auto

to this:

go env -w GO111MODULE=off

**Comment by dementeb** [comment]
Thank you very much for your help.
I apologize for the delay, circumstances forced me to be without a PC.
I didn't quite understand where exactly to change this. I tried it in different places ;), but unfortunately without a positive result.
However, the x86 version builds without problems - so I think this is a problem with the gl-inet SDK...

anyway, thank you very much!
