### ISSUE TITLE
吐槽启用 Netflix 分流模式

### ISSUE THREAD

**Issue by nightmare950** [fw876/helloworld#1270]
这样设计很糟糕，对比passwall

**Comment by AmberisMyShiba** [comment]
哪里糟糕了？吐槽也吐得完整一点呀，列举几个槽点看看。

**Comment by nightmare950** [comment]
ssrplus的奈飞分流模式只代理用户写出来的域名
实际操作是需要先知道域名才能分流代理
奈飞的域名已经写进去了，那还有一些网站锁地区只能通过抓包把域名写进去
港澳台的b站，巴哈姆特动画疯，dmm
——————
passwall的奈飞分流模式则是支持gfw列表，全局代理，非中国列表
奈飞，巴哈姆特动画疯，dmm这些属于非中国列表
选择非中国列表就可以访问了，不需要知道域名

**Comment by AmberisMyShiba** [comment]
你这个需求，把奈飞分流服务器设为与主服务器一致不就可以了。

**Comment by chika0801** [comment]
2者设计理念不一样。这边简单即好原则，所以你要复杂的用passwall即可
