### ISSUE TITLE
make[3]: *** [Makefile:80: /workdir/openwrt/build_dir/target-x86_64_musl/v2ray-core-5.7.0/.built] Error 1 make[3]: Leaving directory '/workdir/openwrt/feeds/helloworld/v2ray-core' time: package/feeds/helloworld/v2ray-core/compile#1.07#0.40#1.01     ERROR: package/feeds/helloworld/v2ray-core failed to build. make[2]: *** [package/Makefile:116: package/feeds/helloworld/v2ray-core/compile] Error 1 make[2]: Leaving directory '/workdir/openwrt' make[1]: *** [package/Makefile:110: /workdir/openwrt/staging_dir/target-x86_64_musl/stamp/.package_compile] Error 2 make[1]: Leaving directory '/workdir/openwrt' make: *** [/workdir/openwrt/include/toplevel.mk:231: world] Error 2 Error: Process completed with exit code 2.

### ISSUE THREAD

**Issue by d975xbx** [fw876/helloworld#1279]
make[3]: *** [Makefile:80: /workdir/openwrt/build_dir/target-x86_64_musl/v2ray-core-5.7.0/.built] Error 1
make[3]: Leaving directory '/workdir/openwrt/feeds/helloworld/v2ray-core'
time: package/feeds/helloworld/v2ray-core/compile#1.07#0.40#1.01
    ERROR: package/feeds/helloworld/v2ray-core failed to build.
make[2]: *** [package/Makefile:116: package/feeds/helloworld/v2ray-core/compile] Error 1
make[2]: Leaving directory '/workdir/openwrt'
make[1]: *** [package/Makefile:110: /workdir/openwrt/staging_dir/target-x86_64_musl/stamp/.package_compile] Error 2
make[1]: Leaving directory '/workdir/openwrt'
make: *** [/workdir/openwrt/include/toplevel.mk:231: world] Error 2
Error: Process completed with exit code 2.

**Comment by evenwangcn** [comment]
一样的问题

**Comment by gcp91020** [comment]
add PKG_BUILD_FLAGS:=no-mips16 to Makefile
or modify diy.sh to add it before complie
sed -i 's/PKG_USE_MIPS16/PKG_BUILD_FLAGS:=no-mips16\nPKG_USE_MIPS16/' feeds/helloworld/v2ray-plugin/Makefile
