### ISSUE TITLE
选了hysteria编译就会报错

### ISSUE THREAD

**Issue by Lai-xi** [fw876/helloworld#1284]
报错日志如下
Makefile:53: recipe for target '/home/ub/lede/build_dir/target-x86_64_musl/hysteria-1.3.5/.built' failed
make[3]: *** [/home/ub/lede/build_dir/target-x86_64_musl/hysteria-1.3.5/.built] Error 1
make[3]: Leaving directory '/home/ub/lede/feeds/helloworld/hysteria'
time: package/feeds/helloworld/hysteria/compile#64.98#14.55#39.71
    ERROR: package/feeds/helloworld/hysteria failed to build.
package/Makefile:114: recipe for target 'package/feeds/helloworld/hysteria/compile' failed
make[2]: *** [package/feeds/helloworld/hysteria/compile] Error 1
make[2]: Leaving directory '/home/ub/lede'
package/Makefile:110: recipe for target '/home/ub/lede/staging_dir/target-x86_64_musl/stamp/.package_compile' failed
make[1]: *** [/home/ub/lede/staging_dir/target-x86_64_musl/stamp/.package_compile] Error 2
make[1]: Leaving directory '/home/ub/lede'
/home/ub/lede/include/toplevel.mk:229: recipe for target 'world' failed

**Comment by Jason6111** [comment]
用hy2就没事

**Comment by Lai-xi** [comment]
> 用hy2就没事

请问怎么切换到2呢？插件里好像没看到

**Comment by Jason6111** [comment]
> > 用hy2就没事
> 
> 请问怎么切换到2呢？插件里好像没看到

用我库里改好的

**Comment by Jason6111** [comment]
> > > 用hy2就没事
> > 
> > 
> > 请问怎么切换到2呢？插件里好像没看到
> 
> 用我库里改好的

缝合了两个大神的

**Comment by Jason6111** [comment]
> > 报错日志如下 Makefile:53: recipe for target '/home/ub/lede/build_dir/target-x86_64_musl/hysteria-1.3.5/.built' failed make[3]: *** [/home/ub/lede/build_dir/target-x86_64_musl/hysteria-1.3.5/.built] Error 1 make[3]: Leaving directory '/home/ub/lede/feeds/helloworld/hysteria' time: package/feeds/helloworld/hysteria/compile#64.98#14.55#39.71 ERROR: package/feeds/helloworld/hysteria failed to build. package/Makefile:114: recipe for target 'package/feeds/helloworld/hysteria/compile' failed make[2]: *** [package/feeds/helloworld/hysteria/compile] Error 1 make[2]: Leaving directory '/home/ub/lede' package/Makefile:110: recipe for target '/home/ub/lede/staging_dir/target-x86_64_musl/stamp/.package_compile' failed make[1]: *** [/home/ub/lede/staging_dir/target-x86_64_musl/stamp/.package_compile] Error 2 make[1]: Leaving directory '/home/ub/lede' /home/ub/lede/include/toplevel.mk:229: recipe for target 'world' failed
> 
> +1

尝试先用 https://github.com/Jason6111/helloworld

**Comment by wingarcher** [comment]
不是作者的问题，升级到go 1.21版本了，日志往上翻就能看到，还给了一个URL得说明。

**Comment by Lai-xi** [comment]
> 不是作者的问题，升级到go 1.21版本了，日志往上翻就能看到，还给了一个URL得说明。
所以怎么可以解决呢？

**Comment by wingarcher** [comment]
明天我编译一下试试，理论上把hysteria/Makefile 中的 PKG_VERSION:=2.0.4 修改为 PKG_VERSION:=2.0.3就可以了。
hysteria大大 从2.0.3 升级到 2.0.4的时候就把go版本从1.20升级到1.21了，qtls暂时不支持1.21版本。

**Comment by Lai-xi** [comment]
> 明天我编译一下试试，理论上把hysteria/Makefile 中的 PKG_VERSION:=2.0.4 修改为 PKG_VERSION:=2.0.3就可以了。 hysteria大大 从2.0.3 升级到 2.0.4的时候就把go版本从1.20升级到1.21了，qtls暂时不支持1.21版本。
感谢大佬

**Comment by ainp** [comment]
我也遇到同类问题，尝试用说的方法好像不行

**Comment by ainp** [comment]
> > > 报错日志如下 Makefile:53: recipe for target '/home/ub/lede/build_dir/target-x86_64_musl/hysteria-1.3.5/.built' failed make[3]: *** [/home/ub/lede/build_dir/target-x86_64_musl/hysteria-1.3.5/.built] Error 1 make[3]: Leaving directory '/home/ub/lede/feeds/helloworld/hysteria' time: package/feeds/helloworld/hysteria/compile#64.98#14.55#39.71 ERROR: package/feeds/helloworld/hysteria failed to build. package/Makefile:114: recipe for target 'package/feeds/helloworld/hysteria/compile' failed make[2]: *** [package/feeds/helloworld/hysteria/compile] Error 1 make[2]: Leaving directory '/home/ub/lede' package/Makefile:110: recipe for target '/home/ub/lede/staging_dir/target-x86_64_musl/stamp/.package_compile' failed make[1]: *** [/home/ub/lede/staging_dir/target-x86_64_musl/stamp/.package_compile] Error 2 make[1]: Leaving directory '/home/ub/lede' /home/ub/lede/include/toplevel.mk:229: recipe for target 'world' failed
> > 
> > 
> > +1
> 
> 尝试先用 https://github.com/Jason6111/helloworld
make[3]: *** [Makefile:61: /lede/build_dir/target-x86_64_musl/hysteria-app-v2.0.4/.built] Error 1
make[3]: Leaving directory '/lede/feeds/helloworld/hysteria'
time: package/feeds/helloworld/hysteria/compile#2.50#0.93#18.47
    ERROR: package/feeds/helloworld/hysteria failed to build.
make[2]: *** [package/Makefile:116: package/feeds/helloworld/hysteria/compile] Error 1
make[2]: Leaving directory '/lede'
make[1]: *** [package/Makefile:110: /lede/staging_dir/target-x86_64_musl/stamp/.package_compile] Error 2
make[1]: Leaving directory '/lede'
make: *** [/lede/include/toplevel.mk:231: world] Error 2

**Comment by Jason6111** [comment]
原项目更新了 用原项目试试吧
