### ISSUE TITLE
希望可以加个分流功能

### ISSUE THREAD

**Issue by aheig** [fw876/helloworld#129]
希望可以加个分流功能。
比如10.0.0.2  client走v2服务器节点，10.0.0.9  client走v9服务器节点这样子。不晓得能不能做到

**Comment by Nicepaul** [comment]
如果能有这个功能就太好了，非常需要啊

**Comment by Aes64X** [comment]
出门南北转找项目经理等报价。

**Comment by yysw** [comment]
另外那个流行的fq软件有这个功能

**Comment by aheig** [comment]
> 另外那个流行的fq软件有这个功能

是嘛？
