### ISSUE TITLE
最新的mosdns支持的ssrp，下面两行屏蔽了：DNS 防污染服务，请问是有意为之吗？！

### ISSUE THREAD

**Issue by zxlhhyccc** [fw876/helloworld#1306]
https://github.com/fw876/helloworld/blob/master/luci-app-ssr-plus/luasrc/model/cbi/shadowsocksr/status.lua#L115
https://github.com/fw876/helloworld/blob/master/luci-app-ssr-plus/luasrc/model/cbi/shadowsocksr/status.lua#L172
![image](https://github.com/fw876/helloworld/assets/45259624/0b57bde0-2fe5-444f-9d41-cf4b031c489e)

**Comment by AmberisMyShiba** [comment]
是的啊。lean大刚提交的。[7a5ec10](https://github.com/fw876/helloworld/commit/7a5ec102cfaa5f4e4ded5d5fdb2afd7a4a0e4a6d)
