### ISSUE TITLE
系统日志重新大片的报错信息 user.notice shadowsocksr: ssrplus redir tcp error.restart!

### ISSUE THREAD

**Issue by fxxccp** [fw876/helloworld#1309]
### 下面是日志

![B](https://github.com/fw876/helloworld/assets/112669679/ab2df528-97a2-4d76-8ef7-ef61f8e38fe7)

![03](https://github.com/fw876/helloworld/assets/112669679/f197e7b7-e44c-4c62-b4b3-ea05a56efae7)

====================

### 下面是设置
![01](https://github.com/fw876/helloworld/assets/112669679/74cf0ada-f757-4abf-a1bd-e8c4ef0db68b)

**其它参数设置为默认**

**Comment by zxlhhyccc** [comment]
高级设置里做了吗？
