### ISSUE TITLE
What？！

### ISSUE THREAD

**Issue by Michaol** [fw876/helloworld#1313]
the hell...

**Comment by OldCoding** [comment]
(￣▽￣)"

**Comment by 783545134** [comment]
(￣▽￣)

**Comment by 8MiYile** [comment]
gg

**Comment by LucasIsGood** [comment]
what happened anybody tell me

**Comment by BenjaminX** [comment]
# Add a feed source
echo 'src-git helloworld https://github.com/fw876/helloworld' >>feeds.conf.default
echo '### SSR helloworld ###'

怎么在 feed 中切 branch 到 main 啊？

**Comment by eallion** [comment]
> # Add a feed source
> echo 'src-git helloworld https://github.com/fw876/helloworld' >>feeds.conf.default echo '### SSR helloworld ###'
> 
> 怎么在 feed 中切 branch 到 main 啊？

官方有文档： https://openwrt.org/docs/guide-developer/feeds

```bash
src-git helloworld https://github.com/fw876/helloworld.git;main
```

**Comment by dongfangy2011** [comment]
**src-git helloworld https://github.com/fw876/helloworld.git;main**
