### ISSUE TITLE
hy2跑不起来

### ISSUE THREAD

**Issue by kvmcore** [fw876/helloworld#1316]
首先hy2服务端是没问题的，已在手机端nekobox, shadowrocket测试可用。

目前现状是ssrp显示未运行，日志显示Architecture:  Started!  但又一直报错ssrplus redir tcp error.restart!

麻烦有空的时候检查一下ssrp的hy2配置文件，谢谢

<img width="653" alt="s2023-11-04_03 14 34" src="https://github.com/fw876/helloworld/assets/3048370/01a03294-319a-4cf9-88c9-c00aba47ad15">

<img width="823" alt="s2023-11-04_03 09 02" src="https://github.com/fw876/helloworld/assets/3048370/0b4598ef-47f2-4dde-8a99-8462d26e7f8e">

**Comment by Bigdog-007** [comment]
乱设置，全默认就正常了。别整什么DNS

**Comment by ricksuzade-maker** [comment]
我也遇到这个问题了，hy2无法启动，服务端是好的

**Comment by AmberisMyShiba** [comment]
看提示是tcp透明代理的redirect错误，估计是配置文件使用了tproxy类型的透明代理。所以手机上能用，ssr-plus上只支持tpc的redirect方式，所以就不能用。

**Comment by kvmcore** [comment]
> 看提示是TCP透明代理的REDIRECT错误，估计是配置文件使用了TPROXY类型的透明代理。所以手机上能用，ssr-plus上只支持TCP的redirect方式，所以就不能用。试试看删除原先的节点文件，重新用手动添加的方式配置一个。 如果上述方式还是不能解决问题，用ssh到路由器的的console,运行以下命令，并贴出对应的出错提示 eval $(ps -ef | grep hysteria |grep -v grep|awk '{ print $5,$6,$7,$8 }')

`ps: unrecognized option: e
BusyBox v1.36.1 (2023-10-09 21:45:35 UTC) multi-call binary.

Usage: ps

Show list of processes

	w	Wide output`

**Comment by AmberisMyShiba** [comment]
> > 看提示是TCP透明代理的REDIRECT错误，估计是配置文件使用了TPROXY类型的透明代理。所以手机上能用，ssr-plus上只支持TCP的redirect方式，所以就不能用。试试看删除原先的节点文件，重新用手动添加的方式配置一个。 如果上述方式还是不能解决问题，用ssh到路由器的的console,运行以下命令，并贴出对应的出错提示 eval $(ps -ef | grep hysteria |grep -v grep|awk '{ print $5,$6,$7,$8 }')
> 
> ```
> ps: unrecognized option: e
> BusyBox v1.36.1 (2023-10-09 21:45:35 UTC) multi-call binary.
> 
> Usage: ps
> 
> Show list of processes
> 
> 	w	Wide output
>我认认真真地看issue,在自己的环境上试图重现问题，但是你反馈问题却如此地随意，根本没有足够和有用的信息，这样既不能帮助你解决问题，也是浪费别人的时间精力。我根本是鸡同鸭讲。把你这个issue关闭了吧，我不会再回复你了。

**Comment by kvmcore** [comment]
> > > 看提示是TCP透明代理的REDIRECT错误，估计是配置文件使用了TPROXY类型的透明代理。所以手机上能用，ssr-plus上只支持TCP的redirect方式，所以就不能用。试试看删除原先的节点文件，重新用手动添加的方式配置一个。 如果上述方式还是不能解决问题，用ssh到路由器的的console,运行以下命令，并贴出对应的出错提示 eval $(ps -ef | grep hysteria |grep -v grep|awk '{ print $5,$6,$7,$8 }')
> > 
> > 
> > ```
> > ps: unrecognized option: e
> > BusyBox v1.36.1 (2023-10-09 21:45:35 UTC) multi-call binary.
> > 
> > Usage: ps
> > 
> > Show list of processes
> > 
> > 	w	Wide output
> > ```
> 
> 你贴了个ps命令出错的信息，也没有其他的追加的情况，所以没有足够和有用的信息可以帮你解决问题。请试试看把hysteria的lazy模式设置为开启，是否可以解决问题。这个可能是hysteria官方的一个[bug](https://github.com/apernet/hysteria/issues/820).使用hysteria的可以保持关注。

<img width="1313" alt="hy2" src="https://github.com/fw876/helloworld/assets/3048370/d1f6235f-d8c1-4ee1-b656-b9d4d4391145">

lazy开或不开，结果都一样

**Comment by AmberisMyShiba** [comment]
> > > > 看提示是TCP透明代理的REDIRECT错误，估计是配置文件使用了TPROXY类型的透明代理。所以手机上能用，ssr-plus上只支持TCP的redirect方式，所以就不能用。试试看删除原先的节点文件，重新用手动添加的方式配置一个。 如果上述方式还是不能解决问题，用ssh到路由器的的console,运行以下命令，并贴出对应的出错提示 eval $(ps -ef | grep hysteria |grep -v grep|awk '{ print $5,$6,$7,$8 }')
> > > 
> > > 
> > > ```
> > > ps: unrecognized option: e
> > > BusyBox v1.36.1 (2023-10-09 21:45:35 UTC) multi-call binary.
> > > 
> > > Usage: ps
> > > 
> > > Show list of processes
> > > 
> > > 	w	Wide output
> > > ```
> > 
> > 
> > 你贴了个ps命令出错的信息，也没有其他的追加的情况，所以没有足够和有用的信息可以帮你解决问题。请试试看把hysteria的lazy模式设置为开启，是否可以解决问题。这个可能是hysteria官方的一个[bug](https://github.com/apernet/hysteria/issues/820).使用hysteria的可以保持关注。
> 
> <img alt="hy2" width="1313" src="https://user-images.githubusercontent.com/3048370/283340100-d1f6235f-d8c1-4ee1-b656-b9d4d4391145.png">
> lazy开或不开，结果都一样

我真是一脸黑线，看来你即不懂shell，也看不懂英语。这让人怎么帮你呢！最后还是再给你个提示：按屏幕上的输出结果，把ps后面的-ef去掉。然后自己去摸索吧。
