### ISSUE TITLE
拉取main命令

### ISSUE THREAD

**Issue by xuanranran** [fw876/helloworld#1323]
```
git clone --depth=1 -b main https://github.com/fw876/helloworld package/helloworld
```

**Comment by NEARWN** [comment]
echo "src-git ssrp https://github.com/fw876/helloworld.git;main" >> ./feeds.conf.default

**Comment by xuanranran** [comment]
> echo "src-git ssrp https://github.com/fw876/helloworld.git;main" >> ./feeds.conf.default

额，我这个只用于自托管编译，不是ssh编译
