### ISSUE TITLE
更新一下naiveproxy

### ISSUE THREAD

**Issue by openips** [fw876/helloworld#1324]
最新的naiveproxy到了v119.0.6045.66-1 代码里面的版本太老了 更新一下吧

**Comment by pangfeng161** [comment]
这插件确实不怎样,要不都快一年不更新

**Comment by wekingchen** [comment]
这个forwardproxy插件服务器端很稳，不怎么需要更新，但是客户端的naiveproxy确实最好跟着chrome更新，请大大帮忙升级一下吧。

**Comment by pangfeng161** [comment]
> 这个forwardproxy插件服务器端很稳，不怎么需要更新，但是客户端的naiveproxy确实最好跟着chrome更新，请大大帮忙升级一下吧。

服务端和客户端不需要相同的版本吗?

**Comment by wekingchen** [comment]
> > 这个forwardproxy插件服务器端很稳，不怎么需要更新，但是客户端的naiveproxy确实最好跟着chrome更新，请大大帮忙升级一下吧。
> 
> 服务端和客户端不需要相同的版本吗?

客户端naiveproxy是伪装成chrome的流量，所以需要跟着新版chrome更新

**Comment by openips** [comment]
> 在编译之前，把 naiveproxy 替换成 https://github.com/sbwml/openwrt_helloworld/tree/v5/naiveproxy 就够了，这个是跟随最新版本的，而且不需要编译，因为编一个 naiveproxy 相当于编译了一次 Chromium ，那个耗时相当恐怖

不错 有空我试试

**Comment by pangfeng161** [comment]
确实不错.省很多时间
