### ISSUE TITLE
原版openwrt编译时提示 'mosdns', which does not exist

### ISSUE THREAD

**Issue by hongyou3** [fw876/helloworld#1329]
我在 feeds.conf.default 里添加了这一行
`src-git helloworld https://github.com/fw876/helloworld.git;main`

然后执行`./scripts/feeds update -a` 和 `./scripts/feeds install -a` 有一个 WARNING
```shell
me@idebian:~/openwrt$ ./scripts/feeds install -a
Collecting package info: package/feeds/packages/udp-broadcast-relay-redux-openwr
Collecting package info: done
WARNING: Makefile 'package/feeds/helloworld/luci-app-ssr-plus/Makefile' has a dependency on 'mosdns', which does not exist
Installing all packages from feed packages.
Installing all packages from feed luci.
Installing all packages from feed routing.
Installing all packages from feed telephony.
Installing all packages from feed helloworld.
```

请问我需要如何解决这个问题呢？
![截屏2023-11-09 23 43 40](https://github.com/fw876/helloworld/assets/57251801/da174666-648f-4d18-b1f0-b76e5e2110f7)

**Comment by Beginner-Go** [comment]
缺少mosdns依赖

**Comment by XiaoliChan** [comment]
> 缺少 `mosdns` 依赖

需要把mosdns复制进来吗

**Comment by Beginner-Go** [comment]
不用吧 大雕的 `packages` 库有 mosdns

**Comment by XiaoliChan** [comment]
> 不用吧 大雕的 `packages` 库有 mosdns

题主用的是官方openwrt，没在官方op里面

**Comment by XiaoliChan** [comment]
> 等下用大雕库的冲突了


至于冲突的话，是不会冲突的，`feeds` 安装包的顺序是按照 `feeds`配置文件顺序来安装包的，如果A有mosdns，B也有的话，B就不会安装了

**Comment by Beginner-Go** [comment]
好的
