### ISSUE TITLE
ssrplus无法启动：ssrplus redir tcp error.restart!

### ISSUE THREAD

**Issue by ipsumy** [fw876/helloworld#1331]
编译LEDE+helloword x86固件安装在虚拟机后无法运行，提示 **_ssrplus redir tcp error.restart!_** 并无限重启
日志如下图所示：
![circle_screenshot_1_OpenWrt - 日志 - LuCI](https://github.com/fw876/helloworld/assets/131156018/37653c90-681f-4172-ac45-e1ffc5d81c31)

节点订阅在其他系统中可正常使用，节点信息如下：
![OpenWrt - 服务器节点 - LuCIpng](https://github.com/fw876/helloworld/assets/131156018/cd2aea65-4187-4477-955f-23680d4892c9)

主页配置：
![image](https://github.com/fw876/helloworld/assets/131156018/299c59dc-c334-4a4f-b8fe-104f75205d53)

其他配置均为默认

**Comment by XiaoliChan** [comment]
ssh进入路由器，然后执行`ssr-redir`，看看能不能跑起来

**Comment by ipsumy** [comment]
> ssh进入路由器，然后执行`ssr-redir`，看看能不能跑起来
使用SSH执行`ssr-redir`后显示如下错误：
_**ERROR: Invalid config path.**_

**Comment by XiaoliChan** [comment]
> 使用SSH执行`ssr-redir`后显示如下错误：
> _**ERROR: Invalid config path.**_

那看来是节点配置文件有问题了

**Comment by ipsumy** [comment]
> > 使用SSH执行`ssr-redir`后显示如下错误：
> > _**ERROR: Invalid config path.**_
> 
> 那看来是节点配置文件有问题了

我尝试使用添加配置文件运行‘ssr-redir’后出现如下提示：
![image](https://github.com/fw876/helloworld/assets/131156018/67904773-8753-4fee-b2d2-f35fb4991b29)

**Comment by ipsumy** [comment]
查看了openssl版本，猜测与openssl 3删除了MD5支持有关，正在尝试解决...
![image](https://github.com/fw876/helloworld/assets/131156018/3a3ea1cc-6cbf-4fc9-809f-156b1685f2c6)

**Comment by ipsumy** [comment]
目前已经成功切换openssl版本为1.1.1w
![image](https://github.com/fw876/helloworld/assets/131156018/91daae41-d6e3-4d21-bd26-a875b42db7b7)

编译后运行正常：
![image](https://github.com/fw876/helloworld/assets/131156018/30c04eda-305b-45cc-93c0-132b6de43556)

问题解决！

**Comment by maxjove** [comment]
编译时选择openssl版本吗? 没找到选择项

**Comment by ipsumy** [comment]
> 编译时选择openssl版本吗? 没找到选择项

Openwrt 21.02 版本源码中是1.1.1版本，替换相同编译目录下的openssl文件夹
https://github.com/openwrt/openwrt/tree/openwrt-21.02/package/libs

make clean之后make download 然后编译

**Comment by ipsumy** [comment]
> 编译时选择openssl版本吗? 没找到选择项

Openwrt 22.03 版本源码中是1.1.1版本，替换相同编译目录下的openssl文件夹
https://github.com/openwrt/openwrt/tree/openwrt-22.03/package/libs/openssl

make cleanmake download 然后编译

**Comment by ipsumy** [comment]
Openwrt 22.03 版本源码中是1.1.1版本，替换相同编译目录下的openssl文件夹
https://github.com/openwrt/openwrt/tree/openwrt-22.03/package/libs/openssl

make clean
make download ...
然后编译

**Comment by sbwml** [comment]
https://github.com/sbwml/YAOF/commit/df0e18404aecccf752840e8051d5771bef4e7b4e

**Comment by ylmf56** [comment]
> Openwrt 22.03 版本源码中是1.1.1版本，替换相同编译目录下的openssl文件夹 https://github.com/openwrt/openwrt/tree/openwrt-22.03/package/libs/openssl
> 
> make clean make download ... 然后编译


你好，本人不是程序员，只知道最基本的几个linux命令，          能不能给个完整的代码参考，整个降级过程代码，直接用那种。

**Comment by fun665** [comment]
哇 厉害啊  被这个问题困扰很久了，终于按照这个方法更换openssl1.1.1版本。解决了！感谢！
