### ISSUE TITLE
啥情况，删库了？

### ISSUE THREAD

**Issue by Xuansong-github** [fw876/helloworld#1332]

**Comment by ipsumy** [comment]
默认分支改了，切换为main分支即可

**Comment by xpc0938** [comment]
openwrt feeds.conf.default:
modify "#src-git helloworld https://github.com/fw876/helloworld.git;" 
to "src-git helloworld https://github.com/fw876/helloworld.git;main"

**Comment by Xuansong-github** [comment]
ok

**Comment by NeedforGit** [comment]
> openwrt feeds.conf.default: modify "#src-git helloworld https://github.com/fw876/helloworld.git;" to "src-git helloworld https://github.com/fw876/helloworld.git;main"

感谢！
