### ISSUE TITLE
国外DNS使用MosDNS情况下，开启国内DNS（ChinaDNS），所有节点不通，无法连接

### ISSUE THREAD

**Issue by leochien0102** [fw876/helloworld#1333]
只有禁用MosDNS下的ChinaDNS模式，才可以。本身就是这样设计的还是BUG？

**Comment by XiaoliChan** [comment]
截图，提供详细信息

**Comment by leochien0102** [comment]
开启，连接错误
![screenshot20231112](https://github.com/fw876/helloworld/assets/3915276/aa48664d-2351-4fc0-addc-5b6135302c9a)
![screenshot20231112_1](https://github.com/fw876/helloworld/assets/3915276/95818056-472b-41c2-9543-7bc2b86991a0)
禁用，使用正常
![screenshot20231112_3](https://github.com/fw876/helloworld/assets/3915276/16da75dc-9da1-4ec6-ab21-c34b321cae09)
![screenshot20231112_4](https://github.com/fw876/helloworld/assets/3915276/ef86a8d6-66ce-4238-988a-d002299a60ec)

**Comment by XiaoliChan** [comment]
无法复现，你在开启chinadns模式后，ssh进入路由器，执行 `ps -w | grep mos`

**Comment by leochien0102** [comment]
> 无法复现，你在开启chinadns模式后，ssh进入路由器，执行 `ps -w | grep mos`
> 
> 如果你使用`dns2tcp` + `chinadns` 模式，会不会有这样的问题
mos的进程是在的
![screenshot20231112-6](https://github.com/fw876/helloworld/assets/3915276/9931df46-426e-4772-b2f6-65412b8713c4)
使用dns2tcp+chinadns模式，使用正常
![screenshot20231112-7](https://github.com/fw876/helloworld/assets/3915276/f4941e84-e8f4-40ea-a393-3183a9899f06)
![screenshot20231112-8](https://github.com/fw876/helloworld/assets/3915276/8f1dce15-0783-4fef-a8a4-e763414c7c15)

**Comment by XiaoliChan** [comment]
切换回去`mosdns+chinadns`模式，终端执行 `nslookup www.google.com 127.0.0.1 -p 5335`

**Comment by leochien0102** [comment]
> 切换回去`mosdns+chinadns`模式，终端执行 `nslookup www.google.com 127.0.0.1:5335`

![screenshot20231112-9](https://github.com/fw876/helloworld/assets/3915276/36f8db2d-0454-4929-b20a-ed3638888212)

**Comment by XiaoliChan** [comment]
> ![screenshot20231112-9](https://user-images.githubusercontent.com/3915276/282286309-36f8db2d-0454-4929-b20a-ed3638888212.png)

奇怪...，你是不是自己又搭建了什么DNS
`ls /etc/ssrplus/` `ls /etc/ssrplus/mosdns-chinadns` 给我看看里面有没有数据

**Comment by leochien0102** [comment]
> > ![screenshot20231112-9](https://user-images.githubusercontent.com/3915276/282286309-36f8db2d-0454-4929-b20a-ed3638888212.png)
> 
> 奇怪...
> 
> 你有没有discord，加这个组[DC](https://discord.gg/dvsQkj98)，我远程看看

这会出门去了，晚点再说
