### ISSUE TITLE
新编译，为什么MOSDNS下面没有其它的了

### ISSUE THREAD

**Issue by vi-si** [fw876/helloworld#1336]
请问各位，我已经是新编译，为什么MOSDNS下面没有其它的了。

已经选了
CONFIG_PACKAGE_mosdns=y
CONFIG_PACKAGE_chinadns-ng=y

![捕获](https://github.com/fw876/helloworld/assets/22131050/af0832b7-acc7-4e70-8d25-484f74e35566)

**Comment by vi-si** [comment]
![捕获](https://github.com/fw876/helloworld/assets/22131050/811bdfb6-97f5-4c82-9026-2c4f1f40f598)

**Comment by Cathgao** [comment]
那你想有什么其他的

**Comment by vi-si** [comment]
> 那你还想有什么其他的

![捕获](https://github.com/fw876/helloworld/assets/22131050/7fdb9be6-90ed-461e-bd35-ac415c3e50f5)

**Comment by XiaoliChan** [comment]
[hidden link](https://github.com/XiaoliChan/helloworld/tree/mosdns-support)

**Comment by Cathgao** [comment]
自己查issue和PR，早就说过mosdns不需要什么防泄漏了

**Comment by XiaoliChan** [comment]
> 自己查issue和PR，早就说过mosdns不需要什么防泄漏了

会有什么问题吗？能补充吗，PR是我写的

**Comment by Cathgao** [comment]
因为mosdns本身就有这样的功能

**Comment by XiaoliChan** [comment]
> 因为mosdns本身就有这样的功能

哪里具备了，要调规则的吧，你可以本地起一个mosdns，然后用最简单的转发上流功能，打开ipleak测试

**Comment by Mibore99** [comment]
所以问题到底出在哪里呐，同样编译完了少了两个选项。。

**Comment by Mibore99** [comment]
> > 那你还想有什么其他的
> 
> ![捕获](https://private-user-images.githubusercontent.com/22131050/283002700-7fdb9be6-90ed-461e-bd35-ac415c3e50f5.PNG?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDExNjY4NTQsIm5iZiI6MTcwMTE2NjU1NCwicGF0aCI6Ii8yMjEzMTA1MC8yODMwMDI3MDAtN2ZkYjliZTYtOTBlZC00NjFlLWJkMzUtYWM0MTVjM2U1MGY1LlBORz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzExMjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMTI4VDEwMTU1NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTllZWE1MTc3N2I5Zjg0OTg4MTNkYTI5YWU1NjgzMWRmODUzMmNmMWYzYzcyY2JhNmY4ODJlMjI3MjI1MThlYWQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.djlEGwl3OAv-M5viFYqzHyBczNqjRQounuOMeniFviU)

老哥 解决了吗

**Comment by zxlhhyccc** [comment]
> 会有什么问题吗？能补充吗，PR是我写的，我在issues没看到，就看到一例反馈

大佬，能修一下Hysteria吗？目前Hysteria无法运行。。。。
