### ISSUE TITLE
更新后一直报ssrplus redir tcp error.restart!

### ISSUE THREAD

**Issue by maxjove** [fw876/helloworld#1337]
更新后,编译的新包, 启动番茄一直不成功, 一直报错信息:ssrplus redir tcp error.restart!

**Comment by ipsumy** [comment]
#1331

**Comment by ipsumy** [comment]
我遇到过同样的问题，可以尝试确认一下openssl版本

**Comment by ipsumy** [comment]
我遇到过同样的问题，可以尝试确认一下openssl版本
#1331

**Comment by xiaowonet** [comment]
> 我遇到过同样的问题，可以尝试确认一下openssl版本 #1331

openssl版本是3.0.12-1请问该如何换到1.1.1w版本？

**Comment by sbwml** [comment]
https://github.com/sbwml/YAOF/commit/df0e18404aecccf752840e8051d5771bef4e7b4e

**Comment by maxjove** [comment]
> [sbwml/YAOF@df0e184](https://github.com/sbwml/YAOF/commit/df0e18404aecccf752840e8051d5771bef4e7b4e)

fix
