### ISSUE TITLE
gfwlist-by-loukky更新地址似乎失效了(网络问题,已解决)

### ISSUE THREAD

**Issue by minlang112** [fw876/helloworld#135]
loukky维护的gfwlist，内置的默认源地址已失效多日，无法连接
https://cdn.jsdelivr.net/gh/Loukky/gfwlist-by-loukky/gfwlist.txt
——————
已恢复

**Comment by swxk521** [comment]
没有失效，官方的https://raw.githubusercontent.com/gfwlist/gfwlist/master/gfwlist.txt现在也更新了

**Comment by minlang112** [comment]
> 没有失效，官方的[https://raw.githubusercontent.com/gfwlist/gfwlist/master/gfwlist.txt现在也更新了](https://raw.githubusercontent.com/gfwlist/gfwlist/master/gfwlist.txt%E7%8E%B0%E5%9C%A8%E4%B9%9F%E6%9B%B4%E6%96%B0%E4%BA%86)

嗯，我手动换成git的地址是可以更新的，访问https://cdn.jsdelivr.net/gh/Loukky/gfwlist-by-loukky/gfwlist.txt 是http403，不知道什么情况

**Comment by swxk521** [comment]
我这边访问没问题

**Comment by Benjamin23333** [comment]
> > 没有失效，官方的[https://raw.githubusercontent.com/gfwlist/gfwlist/master/gfwlist.txt现在也更新了](https://raw.githubusercontent.com/gfwlist/gfwlist/master/gfwlist.txt%E7%8E%B0%E5%9C%A8%E4%B9%9F%E6%9B%B4%E6%96%B0%E4%BA%86)
> 
> 嗯，我手动换成git的地址是可以更新的，访问https://cdn.jsdelivr.net/gh/Loukky/gfwlist-by-loukky/gfwlist.txt 是http403，不知道什么情况

我今天白天也是，现在已经恢复正常了
