### ISSUE TITLE
如果SSR Plus设置的节点挂掉，有些国内网站就打开很慢或完全打不开

### ISSUE THREAD

**Issue by minfengyk** [fw876/helloworld#136]
SSR Plus设置的节点正常，DNS解析就很快。如果SSR Plus设置的节点挂掉，有些国内网站就打开很慢或完全打不开,DNS解析就不正常。这时更换正常的节点或关掉SSR Plus，立刻恢复正常。

主机型号 | Intel(R) Core(TM) i3-7100U CPU @ 2.40GHz : 1 Core 2 Thread (CpuMark : 36971.139404 Scores)
CPU 信息 | 2400.000 MHz
固件版本 | OpenWrt R20.7.1 / LuCI Master (git-20.191.36863-eee6bae)
内核版本 | 4.19.123

日志：没有获取到错误日志。

**Comment by swxk521** [comment]
确实有这个问题。一样的固件 软路由

**Comment by Nicepaul** [comment]
我也越到过这样的问题，x64路由器
