### ISSUE TITLE
ssr-plus使用gfwlist模式，安卓手机谷歌Play商店无法下载应用

### ISSUE THREAD

**Issue by zhouzl7** [fw876/helloworld#137]
ssr-plus使用gfwlist模式，安卓手机谷歌Play商店无法下载应用。切换大陆白名单模式则没有问题。请问怎么解决？

**Comment by hcym** [comment]
用白名单啦，谷歌商店是比较苛刻

**Comment by zhouzl7** [comment]
> 用白名单啦，谷歌商店是比较苛刻

嗯嗯，我现在就是切换白名单在用，主要就是想知道gfwlist模式下有没有解决方法，比如添加强制代理域名以及要添加哪些域名？

**Comment by Wilson-coder** [comment]
> > 用白名单啦，谷歌商店是比较苛刻
> 
> 嗯嗯，我现在就是切换白名单在用，主要就是想知道gfwlist模式下有没有解决方法，比如添加强制代理域名以及要添加哪些域名？

以前需要在强制走代理的列表里添加googleapis.cn地址就行了，你试试看现在还行不行？

**Comment by Benjamin23333** [comment]
> > 用白名单啦，谷歌商店是比较苛刻
> 
> 嗯嗯，我现在就是切换白名单在用，主要就是想知道gfwlist模式下有没有解决方法，比如添加强制代理域名以及要添加哪些域名？

services.googleapis.cn
googleapis.cn
我原来也有这样的问题，我是填了这两个成功的
