### ISSUE TITLE
现在这个版本的SSRP, TUIC无法启动

### ISSUE THREAD

**Issue by dover** [fw876/helloworld#1375]
现在这个版本的SSRP, TUIC无法启动。 

同样的配置，在之前的SSRP，TUIC就能正常启动。

**Comment by zxlhhyccc** [comment]
没tuci节点测试，不知道是不是你说的不能启动，所以不知道问题在哪里！能否提供一个节点我测试，我来修复。。。。

**Comment by AmberisMyShiba** [comment]
tuic上游作者断更，将不再被支持。今后随时会移除tuic的支持。
