### ISSUE TITLE
编译后看不到helloworld

### ISSUE THREAD

**Issue by godpusa** [fw876/helloworld#1379]
通过OpenWrt feed添加helloworld后，只看到shadowsocks R plus，看不到helloworld。我编译前选择的时候，也看不到有helloworld相关的菜单选项。

**Comment by Ljzkirito** [comment]
你说的helloworld是vssr吗？[Hello World](https://github.com/jerrykuku/luci-app-vssr)、[Hello World](https://github.com/OpenWrt-Actions/luci-app-vssr)
这里只有ssrplus

**Comment by godpusa** [comment]
好吧，这个github项目叫helloworld，编译后在OP上现实名叫SSRP，显示名叫helloworld的项目在别的地方，搞清楚了，谢谢。
