### ISSUE TITLE
启动ssrp时报错

### ISSUE THREAD

**Issue by leochien0102** [fw876/helloworld#1404]
输出如下
```
# /etc/init.d/shadowsocksr start
/etc/rc.common: /etc/init.d/shadowsocksr: line 1181: syntax error: unterminated quoted string
```

**Comment by zxlhhyccc** [comment]
https://github.com/fw876/helloworld/pull/1405

**Comment by WYC-2020** [comment]
就服这些盲改不测的哈哈

**Comment by zxlhhyccc** [comment]
> 就服这些盲改不测的哈哈

我提交了pr修复了无法启动问题了https://github.com/fw876/helloworld/pull/1405

**Comment by caixin1218** [comment]
> > 就服这些盲改不测的哈哈
> 
> 我提交了pr修复了无法启动问题了#1405

故障依旧，SSR 无法启动。

**Comment by caixin1218** [comment]
16：50 测试后，已经修复好了，可以正常开启服务了。

**Comment by WYC-2020** [comment]
> > 就服这些盲改不测的哈哈
> 
> 我提交了pr修复了无法启动问题了#1405

嗯是的 我测过 没问题
