### ISSUE TITLE
官方22.03 docker下编译报错

### ISSUE THREAD

**Issue by qwerttvv** [fw876/helloworld#1430]
https://github.com/fw876/helloworld/commit/b0e7c59bef7dbaf36a7da250c278f0e798ebb215#commitcomment-140072019

http://ghcr.io/openwrt/sdk:aarch64_cortex-a53-openwrt-22.03

    checking for pcre2-config... no
    checking for pcre2 location... not found
    configure: error: Cannot find pcre2 library. Configure --with-pcre2=DIR
    make[2]: *** [Makefile:75: /builder/build_dir/target-aarch64_cortex-a53_musl/shadowsocksr-libev-2.5.6/.configured_68b329da9893e34099c7d8ad5cb9c940] Error 1
    make[2]: Leaving directory '/feed/shadowsocksr-libev'
    time: package/feeds/packages_ci/shadowsocksr-libev/compile#15.13#2.80#19.36
        ERROR: package/feeds/packages_ci/shadowsocksr-libev failed to build.
    make[1]: *** [package/Makefile:120: package/feeds/packages_ci/shadowsocksr-libev/compile] Error 1
    make[1]: Leaving directory '/builder'
    make: *** [/builder/include/toplevel.mk:223: package/luci-app-ssr-plus/compile] Error 2

**Comment by Elda1994** [comment]
兄弟，你这ssrp 能在官方22.03.x版本下运行么？我刚刚编译了openwrt23.05.4，加入了ssrplus，编译成功，但是ssrplus无法连接外网。
