### ISSUE TITLE
ssr+支持添加wireguard节点但是不能用

### ISSUE THREAD

**Issue by 13736171140** [fw876/helloworld#1442]
/usr/lib/lua/luci/dispatcher.lua:482: Failed to execute arcombine dispatcher target for entry '/admin/services/shadowsocksr/servers/cfg094a8f'.
The called action terminated with an exception:
/usr/lib/lua/luci/cbi.lua:165: Datatype error, bad token "cidr"
stack traceback:
[C]: in function 'assert'
/usr/lib/lua/luci/dispatcher.lua:482: in function 'dispatch'
/usr/lib/lua/luci/dispatcher.lua:129: in function </usr/lib/lua/luci/dispatcher.lua:128>
好不容易把一个文件里的cidr改成cidr4，cidr6解决了wireguard无法保存问题，但是wireguard运行之后不能科学上网，望大佬解决

**Comment by 13736171140** [comment]
> 可否提供一个wireguard节点我来复现问题？

  {
      "local_address": [
        "172.16.0.2/32",
        "2606:4700:110:802c:7e2b:15a:b1b4:1ed9/128"
      ],
      "mtu": 1280,
      "peer_public_key": "bmXOC+F1FxEMF9dyiK2H5/1SUtzH0JuVo51h2wPfgyo=",
      "pre_shared_key": "",
      "private_key": "YFekpxVqP4nm3vb+0Nyl6qsAk9eNXJDg5tvbB8bMgXY=",
      "reserved": "pfJl",
      "server": "162.159.192.173",
      "server_port": 7152,
      "type": "wireguard",
      "domain_strategy": "",
      "tag": "proxy"
    }
你按这个地址填入试试，电脑上nekoray和手机上nekobox上都是正常的

**Comment by zxlhhyccc** [comment]
````
config servers
	option switch_enable '0'
	option type 'v2ray'
	option alias 'vmiss'
	option server '162.159.192.173'
	option local_port '1234'
	option ip '162.159.192.173'
	option server_port '7152'
	option v2ray_protocol 'wireguard'
	option mtu '1280'
	option private_key 'YFekpxVqP4nm3vb+0Nyl6qsAk9eNXJDg5tvbB8bMgXY='
	option peer_pubkey 'bmXOC+F1FxEMF9dyiK2H5/1SUtzH0JuVo51h2wPfgyo='
	list local_addresses '172.0.0.1/32'
`````
![image](https://github.com/fw876/helloworld/assets/45259624/66ce6cf1-dc7d-439e-b1d0-cee6bf9c0141)

能正常运行，但节点不通，是不是上面这样子的配置？

**Comment by 13736171140** [comment]
> **能正常运行，但节点不通，是不是下面这样子的配置？**
> 
> ```
> config servers
> 	option switch_enable '0'
> 	option type 'v2ray'
> 	option alias 'vmiss'
> 	option server '162.159.192.173'
> 	option local_port '1234'
> 	option ip '162.159.192.173'
> 	option server_port '7152'
> 	option v2ray_protocol 'wireguard'
> 	option mtu '1280'
> 	option private_key 'YFekpxVqP4nm3vb+0Nyl6qsAk9eNXJDg5tvbB8bMgXY='
> 	option peer_pubkey 'bmXOC+F1FxEMF9dyiK2H5/1SUtzH0JuVo51h2wPfgyo='
> 	list local_addresses '172.0.0.1/32'
> ```
> 
> ![image](https://private-user-images.githubusercontent.com/45259624/319258381-66ce6cf1-dc7d-439e-b1d0-cee6bf9c0141.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTIxNjc4MzMsIm5iZiI6MTcxMjE2NzUzMywicGF0aCI6Ii80NTI1OTYyNC8zMTkyNTgzODEtNjZjZTZjZjEtZGM3ZC00MzllLWIxZDAtY2VlNmJmOWMwMTQxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MDMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDAzVDE4MDUzM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWE0N2NiNmVhZGRiMDg0MzI4ZWY2OGU3MjdhYjBmOTc2YTQ4ZDEyZmFhMWRmMTQwYmZhMWE5MDE3ZWQwODFjNmImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.NXQrKPbAqxMxzOzrk7LDG4YxikwrkNN7HrmsjKK0xqE)

嗯，配置没问题，可能我用的lean固件的问题，节点是正常能用的，你可以把它复制到nekoray节点是正常科学上网的

**Comment by zxlhhyccc** [comment]
> 你是手动编辑配置文件还是节点里添加的

luci上面使用节点添加。

**Comment by 13736171140** [comment]
> > 你是手动编辑配置文件还是节点里添加的
> 
> luci上面使用节点添加。

对wireguard节点的支持应该有问题

**Comment by zxlhhyccc** [comment]
> 对wireguard节点的支持应该有问题

有个问题请问一下：你的节点是xray搭建的吗？

**Comment by 13736171140** [comment]
> > 对wireguard节点的支持应该有问题
> 
> 有个问题请问一下：你的节点是xray搭建的吗？如果不是xray搭建的，估计xray不兼容！ Xray 是一个代理软件，通常用于网络代理、监控等。WireGuard 是一个快速、简单、安全的 VPN 解决方案。Xray 并不直接支持搭建 WireGuard 节点，因为它主要是一个代理工具。但是，你可以使用 Xray 作为 WireGuard 的代理来增强 WireGuard 的安全性。 如果你想要搭建一个 WireGuard 节点并使用 Xray 来增强安全性，你可以分别进行设置，然后配置 Xray 作为代理。 如下是如何单独搭建 WireGuard 节点的步骤： 安装 WireGuard 软件。 配置 WireGuard（设置密钥、IP 地址等）。 设置允许通过的客户端。 然后，你可以使用 Xray 来代理 WireGuard 流量。

这个节点是warp免费节点，passwall的singbox内核能正常代理，不过比较吃性能，小米ax3000t跑50m cpu就满载了，vmess节点能跑400+

**Comment by zxlhhyccc** [comment]
> 这个节点是warp免费节点，passwall的singbox内核能正常代理，不过比较吃性能，小米ax3000t跑50m cpu就满载了，vmess节点能跑400+

https://xtls.github.io/document/level-2/warp.html#%E5%AE%A2%E6%88%B7%E7%AB%AF%E4%BD%BF%E7%94%A8-warp-%E9%93%BE%E5%BC%8F%E4%BB%A3%E7%90%86

**Comment by zxlhhyccc** [comment]
> 对wireguard节点的支持应该有问题

ssrp的wireguard节点问题解决了，配置文件需增加一行代码：
![image](https://github.com/fw876/helloworld/assets/45259624/d646365a-76ea-411d-add2-5a671ee22a42)
![image](https://github.com/fw876/helloworld/assets/45259624/4e882402-77e0-4cd4-a0b9-4f57c389bff4)
![image](https://github.com/fw876/helloworld/assets/45259624/c27d7dea-41ce-44c4-8135-50afc98a1914)

**Comment by 13736171140** [comment]
> > 对wireguard节点的支持应该有问题
> 
> @13736171140 ssrp的wireguard节点问题解决了，配置文件需增加一行代码： ![image](https://private-user-images.githubusercontent.com/45259624/319901066-d646365a-76ea-411d-add2-5a671ee22a42.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTIzMjA1OTUsIm5iZiI6MTcxMjMyMDI5NSwicGF0aCI6Ii80NTI1OTYyNC8zMTk5MDEwNjYtZDY0NjM2NWEtNzZlYS00MTFkLWFkZDItNWE2NzFlZTIyYTQyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDA1VDEyMzEzNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWU4OTg1YTFhZGM0MGJmZjZlNzQwNzJiNjkxNmMxZjMzYTA3NmFhZmNkODM5NmU4NTE5ZDRiNzg1YTAyZjJkMTcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.yv2HiEpzGM33SdVS95_wlxPEE-Re-wu5I07r8X8cv5w) ![image](https://private-user-images.githubusercontent.com/45259624/319913938-0d1f98d4-9d7c-4830-8e77-37b7ff713ecf.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTIzMjA1OTUsIm5iZiI6MTcxMjMyMDI5NSwicGF0aCI6Ii80NTI1OTYyNC8zMTk5MTM5MzgtMGQxZjk4ZDQtOWQ3Yy00ODMwLThlNzctMzdiN2ZmNzEzZWNmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDA1VDEyMzEzNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWYwZDBmMDQxODhiOGViYzczYTNiNjhlODczOGY4ZGQ5YzgwZTlhNzQwN2Q5ODhkYTJjNjc4OWUyOTljYjUxYTImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.O2tEMvVXlkwJDAW_ZO-BYY4IOGUnoEJ4oEHMEIGH-Gg) ![image](https://private-user-images.githubusercontent.com/45259624/319901334-c27d7dea-41ce-44c4-8135-50afc98a1914.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTIzMjA1OTUsIm5iZiI6MTcxMjMyMDI5NSwicGF0aCI6Ii80NTI1OTYyNC8zMTk5MDEzMzQtYzI3ZDdkZWEtNDFjZS00NGM0LTgxMzUtNTBhZmM5OGExOTE0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDA1VDEyMzEzNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTJhNjRlMDgxYWNmMjA4NDFmMTk1MzA3YmNhZjIzMGUyYjljYzQ4Y2YyODAwN2UwNTcyMGE4ZWM5NDg0Y2FmYTkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.ZdR0LYIXjMf5U5o-gktYEalM7ZAyeHkK4sEW-tPjjdA)

需要加什么代码呀

**Comment by zxlhhyccc** [comment]
> 需要加什么代码呀

已提pr，请按照pr修改代码后使用，已没问题了。
https://github.com/fw876/helloworld/pull/1445

**Comment by 13736171140** [comment]
> > 需要加什么代码呀
> 
> 已提pr，请按照pr修改代码后使用，已没问题了。 #1445

好吧，小白不懂要怎么搞🥺

**Comment by zxlhhyccc** [comment]
> > > 需要加什么代码呀
> > 
> > 
> > 已提pr，请按照pr修改代码后使用，已没问题了。 #1445
> 
> 好吧，小白不懂要怎么搞🥺

看我提的pr啊，对照文件路径添加或修改代码就可以了

**Comment by 13736171140** [comment]
> > > > 需要加什么代码呀
> > > 
> > > 
> > > 已提pr，请按照pr修改代码后使用，已没问题了。 #1445
> > 
> > 
> > 好吧，小白不懂要怎么搞🥺
> 
> 点击这个链接跳转到我的pr ![image](https://private-user-images.githubusercontent.com/45259624/320060058-9835b052-dae3-4edd-a09c-8c8e32c6942e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTIzMzIxNTEsIm5iZiI6MTcxMjMzMTg1MSwicGF0aCI6Ii80NTI1OTYyNC8zMjAwNjAwNTgtOTgzNWIwNTItZGFlMy00ZWRkLWEwOWMtOGM4ZTMyYzY5NDJlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDA1VDE1NDQxMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWM5OWE2ZmMyZGJmYWYxNjM2ZDYyYWE5NTQ3MjdiYmRkN2Q2NDQ5ZTNmYTBjMWM2M2RhMzNhMGNlMTMzODMyMDImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.fP9KjQseSyo47fRku1zhDMdi8haUOpat30_Fb-CAbbo)
> 
> 看我提的pr啊，对照文件路径对对应的文件添加或修改代码就可以了

哦，那我试试，谢谢

**Comment by zxlhhyccc** [comment]
> 哦，那我试试，谢谢

我的pr有三个，按照每个对应的文件路径修改添加代码即可。

**Comment by zxlhhyccc** [comment]
@13736171140 可以用了吧？

**Comment by 13736171140** [comment]
> @13736171140 可以用了吧？

嗯，可以用，不过wireguard不适合在硬路由上使用，很吃性能，CPU和内存很快就见底，然后路由器卡死重启，跟在passwall上一样

**Comment by zxlhhyccc** [comment]
> 嗯，可以用，不过wireguard不适合在硬路由上使用，很吃性能，CPU和内存很快就见底，然后路由器卡死重启，跟在passwall上一样

我是AX6，用起来貌似没多大关系，你的cpu是不是不支持sse、ase之类的加速功能或者固件没有加速功能模块？

**Comment by 13736171140** [comment]
> > 嗯，可以用，不过wireguard不适合在硬路由上使用，很吃性能，CPU和内存很快就见底，然后路由器卡死重启，跟在passwall上一样
> 
> 我是AX6，用起来貌似没多大关系，你的cpu是不是不支持sse、ase之类的加速功能或者固件没有加速功能模块？

因为开了流量监测，turbo acc里的硬件加速都被我关了，平时可用内存就100多m，开启wireguard节点测速内存很快就没了，平时机场的vmess节点开启后就占用不到20m，就算跑满400m，内存占用也就30多m，硬路由配置低不适合开wireguard

**Comment by brandonyeh-star** [comment]
我在软路由Cudy [TR3000上使用ShadowSocksR Plus+透过WireGuard无法正常连线，请问怎麽联繫?但是iPhone, 安卓, NB都可以

**Comment by brandonyeh-star** [comment]
![Image](https://github.com/user-attachments/assets/eef1f247-dfc9-4181-b923-36944f2024b4)

**Comment by brandonyeh-star** [comment]
![Image](https://github.com/user-attachments/assets/a06d7d98-8e2b-437a-9787-0226976c3516)

**Comment by brandonyeh-star** [comment]
> > 哦，那我试试，谢谢
> 
> 我的pr有三个（最后一个是翻译），按照每个对应的文件路径修改添加代码即可，如果你不是源码，就要在路由里找到对应的文件目录修改两个文件即可，只是luci界面修改的代码是英文。或者我远程帮你修改。 ![image](https://github.com/fw876/helloworld/assets/45259624/2fa0d87c-2e1c-4523-ba4b-107aad86fee4)
> 
> /usr/lib/lua/luci/model/cbi/shadowsocksr/client-config.lua /usr/share/shadowsocksr/gen_config.lua

能否帮忙远程修改? 请问怎么联繫?
