### ISSUE TITLE
最新版的TUIC无法启动

### ISSUE THREAD

**Issue by dover** [fw876/helloworld#1444]
OpenWrt版本：[Powered by LuCI Master (git-24.088.44804-94aca21)](https://github.com/coolsnowwolf/luci) / OpenWrt R24.2.2
同一个机场，在最新版无法启动，报错如图：
![error](https://github.com/fw876/helloworld/assets/8148653/69911478-3126-436f-a10f-e5d9c6ad9fe2)
![error2](https://github.com/fw876/helloworld/assets/8148653/ef9077dc-97f1-4188-9842-28d54ab775ca)

OpenWrt版本：[Powered by LuCI Master (git-23.242.63652-d82d969)](https://github.com/coolsnowwolf/luci) / OpenWrt R23.8.23
同一个机场，启动正常，如图：
![pic3](https://github.com/fw876/helloworld/assets/8148653/fb0cd427-f011-46ac-9762-0646037ce545)

请问一下大佬，这是什么原因，该如何解决？

**Comment by zxlhhyccc** [comment]
两个图没明白什么意思！

**Comment by dover** [comment]
> 两个图没明白什么意思！

 同一个机场，最新的ssrplus的tuic无法启动，但之前版本的ssrplus的tuic就正常。想请教一下是什么原因，该怎么解决。

**Comment by dover** [comment]
> > > 两个图没明白什么意思！
> > 
> > 
> > 同一个机场，最新的ssrplus的tuic无法启动，但之前版本的ssrplus的tuic就正常。想请教一下是什么原因，该怎么解决。
> 
> 请问之前是什么版本，没有节点无法复现，能否提供（可发邮件）节点？我已解决了有用户提出的WireGuard协议不能连接的问题，见pr：#1445

 请问大佬给一个你的邮箱，我给你发邮件。

**Comment by zxlhhyccc** [comment]
> 请问大佬给一个你的邮箱，我给你发邮件。

zxlhhy@gmail.com

**Comment by dover** [comment]
> > 请问大佬给一个你的邮箱，我给你发邮件。
> 
> 请发：[zxlhhy@gmail.com](mailto:zxlhhy@gmail.com)

大佬，邮件已发，请查收。

**Comment by zxlhhyccc** [comment]
> 大佬，邮件已发，请查收。

请问你发的邮件是里面有个截图吗？

**Comment by dover** [comment]
> > 大佬，邮件已发，请查收。
> 
> 请问你发的邮件是里面有个截图吗？测试了一下，确实无法运行，明天找一下问题看看。。。

是的，麻烦大佬了。

**Comment by zxlhhyccc** [comment]
> 是的，麻烦大佬了。

我搞了一下，我能让tuic运行，但科学不通，你能提供ssrplus之前能使用的固件和运行后的配置文件（配置文件路径：`/tmp/etc/ssrplus/tcp-udp-ssr-retcp.json`）吗？我比对一下哪里有问题！

**Comment by dover** [comment]
> > 是的，麻烦大佬了。
> 
> 我搞了一下，我能让tuic运行，但科学不通，一下子找不到哪里出了问题(节点会有问题吗？)，你能提供ssrplus之前能使用的固件和运行后的配置文件（配置文件路径：`/tmp/etc/ssrplus/tcp-udp-ssr-retcp.json`）吗？我比对一下哪里有问题！ ![image](https://private-user-images.githubusercontent.com/45259624/321708487-2a6a59b6-91ac-486d-95e8-5ec01bb37f34.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI5MTg2MjAsIm5iZiI6MTcxMjkxODMyMCwicGF0aCI6Ii80NTI1OTYyNC8zMjE3MDg0ODctMmE2YTU5YjYtOTFhYy00ODZkLTk1ZTgtNWVjMDFiYjM3ZjM0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDEyVDEwMzg0MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTI0NjRhMjJhNGViY2I3ZWQwMWUyNmUwOWZjZmNkZDViYWFkNjA3YzA5NjI2NmIxZmQ5MjQyOTU4Mzk4YWY0MGImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.P9ztzCP4Ndryjl3tEuzmkxf-4DQ7lD56G253r8nkzk4)

大佬，发你邮箱了，请查收。

**Comment by zxlhhyccc** [comment]
> 大佬，发你邮箱了，请查收。

已修复，请见PR：
https://github.com/fw876/helloworld/pull/1449

**Comment by dover** [comment]
> > 大佬，发你邮箱了，请查收。
> 
> 已修复，请见PR： #1449

  请问在SSRPLUS里面哪里配置？  我修改了/tmp/etc/ssrplus/tcp-udp-ssr-retcp.json 但是没起作用呢？

**Comment by zxlhhyccc** [comment]
> 请问在SSRPLUS里面哪里配置？ 我修改了/tmp/etc/ssrplus/tcp-udp-ssr-retcp.json 但是没起作用呢？

你点击这个pr连接：https://github.com/fw876/helloworld/pull/1450，有3个提交，如果路由里直接改，你在路由改我pr的前面两个后再重新运行即可，不是改：'/tmp/etc/ssrplus/tcp-udp-ssr-retcp.json'（这个文件是软件运行后生成的配置文件，如果你改这个文件，重新运行还是会恢复，所以肯定不会运行），需在路由里改：'/usr/share/shadowsocksr/gen_config.lua'和'/usr/lib/lua/luci/model/cbi/shadowsocksr/client-config.lua'这两个文件里的代码。

**Comment by zxlhhyccc** [comment]
> 请问在SSRPLUS里面哪里配置？ 我修改了/tmp/etc/ssrplus/tcp-udp-ssr-retcp.json 但是没起作用呢？

可以用了吗？

**Comment by dover** [comment]
> > 请问在SSRPLUS里面哪里配置？ 我修改了/tmp/etc/ssrplus/tcp-udp-ssr-retcp.json 但是没起作用呢？
> 
> 可以用了吗？

 替换了这两个文件，显示启动了，但不能科学。

**Comment by zxlhhyccc** [comment]
> > > 请问在SSRPLUS里面哪里配置？ 我修改了/tmp/etc/ssrplus/tcp-udp-ssr-retcp.json 但是没起作用呢？
> > 
> > 
> > 可以用了吗？
> 
> 替换了这两个文件，显示启动了，但不能科学。
怎么可能！能否远程我看一下？

**Comment by dover** [comment]
> > > > 请问在SSRPLUS里面哪里配置？ 我修改了/tmp/etc/ssrplus/tcp-udp-ssr-retcp.json 但是没起作用呢？
> > > 
> > > 
> > > 可以用了吗？
> > 
> > 
> > 替换了这两个文件，显示启动了，但不能科学。
> 
> **怎么可能！你替换的是哪里的文件？能否远程我看一下？**

用这个：https://github.com/zxlhhyccc/helloworld/raw/a088e00c8f61d67fd6beb9eedfbd51a833644444/luci-app-ssr-plus/luasrc/model/cbi/shadowsocksr/client-config.lua  替换路由器/usr/lib/lua/luci/model/cbi/shadowsocksr/client-config.lua

用这个：https://github.com/zxlhhyccc/helloworld/raw/08b5f100ec01c6a8b08ef9e507addcd375224bb7/luci-app-ssr-plus/root/usr/share/shadowsocksr/gen_config.lua 替换路由器/usr/share/shadowsocksr/gen_config.lua

这个操作应该是正常的吧

**Comment by zxlhhyccc** [comment]
@dover 可否远程一下？

**Comment by dover** [comment]
> @dover 请使用这个pr里的文件替换！前面的那个有点问题： #1450

 用这个pr里面的文件替换了，还是不能科学。

**Comment by zxlhhyccc** [comment]
> 用这个pr里面的文件替换了，还是不能科学。

远程吧！

**Comment by dover** [comment]
> > 用这个pr里面的文件替换了，还是不能科学。
> 
> 远程吧！

不好意思，我忘填h3了。现在全部正常使用了。非常感谢大佬！！！
