### ISSUE TITLE
新版本在iStoreOS设置为“全局模式”会让整个旁路由无法运行

### ISSUE THREAD

**Issue by gcodexman** [fw876/helloworld#1446]
旧版本是没问题的
 
但是新版本在iStoreOS和eSir的OpenWrt固件（单臂旁路由）上一旦设置为 运行模式-全局模式 后 ...路由后台就无法进入、线路不通 、整个路由无法使用了。

请问是什么导致的？

**Comment by zxlhhyccc** [comment]
无法复现。。。。
