### ISSUE TITLE
导入trojor链接时设置allowInsecure或者insecure字段无效，导致无法设置跳过tls证书

### ISSUE THREAD

**Issue by nttisbest** [fw876/helloworld#1486]
在导入链接和订阅的时候都无法选中跳过tls验证，尝试经过订阅转换设置scv为true时在ssrplus上也无法设置上跳过tls。
实测在V2rayN上是有跳过的。

openwrt版本
![image](https://github.com/fw876/helloworld/assets/31788183/06a77388-a907-4eed-99d4-ceea77033117)

![image](https://github.com/fw876/helloworld/assets/31788183/606b8d70-756c-4119-ae2a-31a92444c1bc)

**Comment by nttisbest** [comment]
补充：在调试前端代码未看见在设置trojor的时候获取相应的字段

**Comment by itfish92** [comment]
修改这个文件 /usr/share/shadowsocksr/subscribe.lua
大约第327行
result.insecure = "0" 这个 0 改成 1
保存修改后，删除之前的节点，重新订阅获取

**Comment by zxlhhyccc** [comment]
> 修改这个文件 /usr/share/shadowsocksr/subscribe.lua 大约第327行 result.insecure = "0" 这个 0 改成 1 保存修改后，删除之前的节点，重新订阅获取

默认是遵循官方：
![image](https://github.com/fw876/helloworld/assets/45259624/89ee3c50-5705-42a0-b5ac-be297c55f278)

**Comment by itfish92** [comment]
> > 修改这个文件 /usr/share/shadowsocksr/subscribe.lua 大约第327行 result.insecure = "0" 这个 0 改成 1 保存修改后，删除之前的节点，重新订阅获取
> 
> 默认是遵循官方： ![image](https://private-user-images.githubusercontent.com/45259624/334433971-89ee3c50-5705-42a0-b5ac-be297c55f278.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY5MDQ5MzIsIm5iZiI6MTcxNjkwNDYzMiwicGF0aCI6Ii80NTI1OTYyNC8zMzQ0MzM5NzEtODllZTNjNTAtNTcwNS00MmEwLWI1YWMtYmUyOTdjNTVmMjc4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTI4VDEzNTcxMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWMzMjQ3YjZhOGZlNDMwOGRiMzBjMGE3ZmJmODM1ZDVjYWQ2NzQ0ODU0MjY2YWYyMjc2ZmU5NTA1YTA1OTBkN2UmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.FeS38uuLr-hxjPYxAX3mJCpQ7XcVRqauFdRd5ZAR9lk)

理论上是对的，但是大多数机场你不跳过这个tls证书就不能用
