### ISSUE TITLE
紧急：180-3版本安装后无法联网

### ISSUE THREAD

**Issue by Zeezorn** [fw876/helloworld#149]
问题版本：180-3版本
测试平台：x86 & IPQ4019 RC619AC
故障：无法联网，无log，貌似是最新版本依赖包tcping的问题，退回180-2正常。

**Comment by Mattraks** [comment]
未发现你说问题,
请重新拉取再试

**Comment by Zeezorn** [comment]
重新git pull 
重新feed udpate & install
问题解决。
感谢。
