### ISSUE TITLE
最近2周，package/feeds/helloworld/gn 编译失败

### ISSUE THREAD

**Issue by chaoyinsu1023** [fw876/helloworld#1494]
全新的编译，无论在L大的Lede还是在官方Openwrt上，都无法编译

**Comment by zxlhhyccc** [comment]
> 全新的编译，无论在L大的Lede还是在官方Openwrt上，都无法编译

请更新你编译环境的gcc，谢谢！

**Comment by chaoyinsu1023** [comment]
哦？我试试

**Comment by zxlhhyccc** [comment]
> gcc (Debian 12.2.0-14) 12.2.0，好像最新的了

你编译什么内核？我官方master分支编译我也问题。

**Comment by chaoyinsu1023** [comment]
您是重新下载，然后编译的吗？
我这边新装系统后，重新git clone lede或openwrt (v23.05.3)，再导入helloworld的源，make download 后，make -j1 V=s，分别为 N1 和xiaomi AX3600编译。
上述4种情况下，都出现编译报错。偶尔在make downlaod时，也会报错（ng)

![报错](https://github.com/fw876/helloworld/assets/137598653/c51ac0df-69ef-4edc-a349-69696d681b47)

**Comment by coolsnowwolf** [comment]
缺 clang

**Comment by chaoyinsu1023** [comment]
“卡点”过去了，感谢！
