### ISSUE TITLE
求助，编译报错

### ISSUE THREAD

**Issue by chaoyinsu1023** [fw876/helloworld#1496]
纯openwrt （v23.05.3） 编译通过；

导入 helloworld 后编译报错，全局模式也尝试过了

![报错](https://github.com/fw876/helloworld/assets/137598653/d3e42f4d-fdc4-4ff6-a1b2-83edad36f4c8)

**Comment by chaoyinsu1023** [comment]
按上面的报错提示， 改成“false"后，后面又遇到了这样的情况

![Uploading 报错2.png…]()

**Comment by coolsnowwolf** [comment]
更新 feeds

**Comment by chaoyinsu1023** [comment]
按上面的报错提示， 改成“false"后，后面又遇到了这样的情况

![报错2](https://github.com/fw876/helloworld/assets/137598653/cacebfed-011a-440a-9467-02680a632343)
