### ISSUE TITLE
有没有人遇到最新的6.1和6.6内核运行ssr puls 会崩内核

### ISSUE THREAD

**Issue by Turing-China** [fw876/helloworld#1498]
最新的两个版本的6.1和6.6内核运行ssr puls 会崩内核 passwall也会 但是没有ssr puls崩溃的那么频繁使用openclash就没问题，内核换回到6.1.83也是正常的

**Comment by zxlhhyccc** [comment]
我就是6.1.95内核，运行一切正常，请自己找找原因。

**Comment by Turing-China** [comment]
> 我就是6.1.95内核，运行一切正常，请自己找找原因。

X86设备会崩 其他设备不会

**Comment by hcym** [comment]
x86和87都没有问题

**Comment by Turing-China** [comment]
> x86和87都没有问题

有点奇怪使用coolsnowwolf的源码会 使用官方源码不会

**Comment by KevinMX** [comment]
可能相关：https://github.com/coolsnowwolf/lede/issues/11302

**Comment by Turing-China** [comment]
> 可能相关：[coolsnowwolf/lede#11302](https://github.com/coolsnowwolf/lede/issues/11302)
> 
> 啥也别说了，先来 dmesg 日志看看吧。

我7月1号使用最新的LEDE 源码编译 已无此问题
