### ISSUE TITLE
BUG反馈，走纯IPV6使用ws+tls，应用后XXR服务端处于关闭状态，无法正常运行

### ISSUE THREAD

**Issue by badgv** [fw876/helloworld#150]
使用“高级设备”中的全局socks5代理，服务端使用纯IPV6的ws+tls，浏览器配置后能正常上网.
观察后台进程：
/usr/bin/v2ray/v2ray -config /var/etc/v2-ssr-retcp.json  使用纯ipv6的ws+tls服务器，无法正常启动

**Comment by coolsnowwolf** [comment]
不支持 IPv6

**Comment by hcym** [comment]
能用，我的ibm就用的6
编译时把ipv6相关包加上去就ok了，现成的固件安装一下也可以，

**Comment by badgv** [comment]
> 不支持 IPv6

V2是支持的啊，高级设置的那个 全局socks5，直接使用纯IPV6的ws+tls，是可以正常工作的，就是全局服务器使用纯IPV6的WS+TLS，无法正常启动后台v2进程

**Comment by badgv** [comment]
> 能用，我的ibm就用的6
> 编译时把ipv6相关包加上去就ok了，现成的固件安装一下也可以，

不是编译没有IPV6的包，已经有了IPV6环境，是上游服务器是个纯IPV6的，全局服务器无法正常启动。
