### ISSUE TITLE
hysteria2.5版本的又编译报错了

### ISSUE THREAD

**Issue by CC13594759** [fw876/helloworld#1501]
hysteria2.5版本的又编译报错了

**Comment by sKyissKy** [comment]
GO_PKG:=github.com/apernet/hysteria
GO_PKG_BUILD_PKG:=$(GO_PKG)/app
GO_PKG_LDFLAGS_X = \
	$(GO_PKG)/app/cmd.appVersion=v$(PKG_VERSION) \
	$(GO_PKG)/app/cmd.appType=release \
	$(GO_PKG)/app/cmd.appPlatform=$(GO_OS) \
	$(GO_PKG)/app/cmd.appArch=$(GO_ARCH)

bump 时没加v2

自己改吧

GO_PKG:=github.com/apernet/hysteria
GO_PKG_BUILD_PKG:=$(GO_PKG)/app/v2
GO_PKG_LDFLAGS_X = \
	$(GO_PKG)/app/v2/cmd.appVersion=v$(PKG_VERSION) \
	$(GO_PKG)/app/v2/cmd.appType=release \
	$(GO_PKG)/app/v2/cmd.appPlatform=$(GO_OS) \
	$(GO_PKG)/app/v2/cmd.appArch=$(GO_ARCH)
