### ISSUE TITLE
编译gn报错，大佬帮忙看看呗

### ISSUE THREAD

**Issue by Mibore99** [fw876/helloworld#1526]
用的官方openwrt,云编译的

make[3]: Entering directory '/workdir/openwrt/feeds/helloworld/gn'
MAKEFLAGS="" /workdir/openwrt/staging_dir/host/bin/ninja  -j1 -C /workdir/openwrt/build_dir/hostpkg/gn-2024-08-13-54f5b539/out
ninja: Entering directory `/workdir/openwrt/build_dir/hostpkg/gn-2024-08-13-54f5b539/out'
[1/295] CXX src/base/command_line.o
FAILED: src/base/command_line.o 
clang++ -MMD -MF src/base/command_line.o.d -I../src -I. -DNDEBUG -O3 -fdata-sections -ffunction-sections -Werror -D_FILE_OFFSET_BITS=64 -D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_MACROS -pthread -pipe -fno-exceptions -fno-rtti -fdiagnostics-color -Wall -Wextra -Wno-unused-parameter -Wextra-semi -Wundef -std=c++20 -Wrange-loop-analysis -Wextra-semi-stmt -Wno-deprecated-copy -Wno-implicit-fallthrough -Wno-redundant-move -Wno-unused-variable -Wno-format -Wno-strict-aliasing -Wno-cast-function-type -c ../src/base/command_line.cc -o src/base/command_line.o
make[3]: *** [Makefile:58: /workdir/openwrt/build_dir/hostpkg/gn-2024-08-13-54f5b539/.built] Error 1
error: unknown warning option '-Wno-cast-function-type'; did you mean '-Wno-bad-function-cast'? [-Werror,-Wunknown-warning-option]
ninja: build stopped: subcommand failed.
make[3]: Leaving directory '/workdir/openwrt/feeds/helloworld/gn'
time: package/feeds/helloworld/gn/host-compile#0.07#0.06#0.12
    ERROR: package/feeds/helloworld/gn [host] failed to build.
make[2]: *** [package/Makefile:127: package/feeds/helloworld/gn/host/compile] Error 1
make[2]: Leaving directory '/workdir/openwrt'
make[1]: *** [package/Makefile:123: /workdir/openwrt/staging_dir/target-aarch64_generic_musl/stamp/.package_compile] Error 2
make[1]: Leaving directory '/workdir/openwrt'
make: *** [/workdir/openwrt/include/toplevel.mk:232: world] Error 2
Error: Process completed with exit code 2.

**Comment by xiangfeidexiaohuo** [comment]
云编译应该报错很久了

**Comment by bfthcom** [comment]
gn [host] failed to build. 
  Same Error..............
gn [host] failed to build.

**Comment by Mibore99** [comment]
> 云编译应该报错很久了

得魔改

**Comment by Mibore99** [comment]
解决了  得升级gcc

**Comment by Mibore99** [comment]
升级gcc到13还是有这个问题

**Comment by xiangfeidexiaohuo** [comment]
> 升级gcc到13还是有这个问题

都已经迷茫了

**Comment by zxlhhyccc** [comment]
能CI检测通过证明没有问题，请排查你的编译环境。

**Comment by Mibore99** [comment]
确实是编译环境的问题，更改ubuntu版本搞定

**Comment by Lai-xi** [comment]
> 确实是编译环境的问题，更改ubuntu版本搞定

请问是更改到什么版本？我之前用的2004报错，改成2204还是报错

**Comment by Mibore99** [comment]
> > 确实是编译环境的问题，更改ubuntu版本搞定
> 
> 请问是更改到什么版本？我之前用的2004报错，改成2204还是报错

我改的24.04

**Comment by Lai-xi** [comment]
> > > 确实是编译环境的问题，更改ubuntu版本搞定
> > 
> > 
> > 请问是更改到什么版本？我之前用的2004报错，改成2204还是报错
> 
> 我改的24.04

我试一下 谢谢

**Comment by Lai-xi** [comment]
> > > 确实是编译环境的问题，更改ubuntu版本搞定
> > 
> > 
> > 请问是更改到什么版本？我之前用的2004报错，改成2204还是报错
> 
> 我改的24.04

两分钟就报错了噗。。。

**Comment by xiangfeidexiaohuo** [comment]
> > > > > > 确实是编译环境的问题，更改ubuntu版本搞定
> > > > > 
> > > > > 
> > > > > 请问是更改到什么版本？我之前用的2004报错，改成2204还是报错
> > > > 
> > > > 
> > > > 我改的24.04
> > > 
> > > 
> > > 两分钟就报错了噗。。。
> > 
> > 
> > 其实如果你不是刚需naiveproxy这个，就去掉naiveproxy就好。
> 
> 确实naiveproxy总是编译报错的元凶

我试过把环境升到2404LTS，x86带naiveproxy，确实能正常编译，所以升级系统环境确实ok；但是rockchip，uboot那部分又报错，所以就只能去掉naiveproxy了，当然仅限于大雕的Lede；官方openwrt或者imm的，升级2404就能解决，不管是x86或者rochchip，升级2404没啥问题。

**Comment by zxlhhyccc** [comment]
> 我试过把环境升到2404LTS，x86带naiveproxy，确实能正常编译，所以升级系统环境确实ok；但是rockchip，uboot那部分又报错，所以就只能去掉naiveproxy了，当然仅限于大雕的Lede；官方openwrt或者imm的，升级2404就能解决，不管是x86或者rochchip，升级2404没啥问题。

我的环境是18.04都没有问题，前提是编译环境的相关软件要更新到最新。

**Comment by Lai-xi** [comment]
1804的环境不是已经没有了吗？我上两个月用1804直接卡在部署环境不动
&nbsp;


dukhch
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "zxl ***@***.***&gt;; 
发送时间: 2024年8月31日(星期六) 下午5:54
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [fw876/helloworld] 编译gn报错，大佬帮忙看看呗 (Issue #1526)





  
我试过把环境升到2404LTS，x86带naiveproxy，确实能正常编译，所以升级系统环境确实ok；但是rockchip，uboot那部分又报错，所以就只能去掉naiveproxy了，当然仅限于大雕的Lede；官方openwrt或者imm的，升级2404就能解决，不管是x86或者rochchip，升级2404没啥问题。
  
我的环境是18.04都没有问题，前提是编译环境的相关软件要更新到最新。
 
&mdash;

**Comment by Elda1994** [comment]
请问最后是怎么解决的哇，我现在也遇到了一样的问题，gn报错。我用的是官方openwrt21.02.2版本，加入了helloworld插件，已经取消了naviproxy的勾选，但依然还是报gn编译错误。已经重新反复编译多次...

**Comment by Lai-xi** [comment]
> 请问最后是怎么解决的哇，我现在也遇到了一样的问题，gn报错。我用的是官方openwrt21.02.2版本，加入了helloworld插件，已经取消了naviproxy的勾选，但依然还是报gn编译错误。已经重新反复编译多次...


我把云编译机器改成ubuntu-latest就好了
