### ISSUE TITLE
更新订阅服务后，SplitHTTP 路径为空

### ISSUE THREAD

**Issue by wekingchen** [fw876/helloworld#1527]
更新完订阅服务后，SplitHTTP 路径一栏没有内容，请大佬看看是不是有bug需要修复一下呢？订阅地址的格式没问题，在v2ray和passwall里面都能正确识别。

**Comment by zxlhhyccc** [comment]
无该类订阅类链接，可否邮件提供一个订阅链接我测试一下，我来修改它。

**Comment by wekingchen** [comment]
vless://011125b3-3174-4be9-bb66-435875a9c70b@vless.qq.com:443?encryption=none&security=tls&pbk=YOwK8sDJPwbpHljXJIKoOmXwIL-w6J8cb7xxINMaKm4&sid=e17f60d1cd385f5b&spx=%2Fjdf0gfc&type=splithttp&path=%2Fpath#TestLink

格式如上

**Comment by zxlhhyccc** [comment]
不好意思，今天太晚，明天我看看能否修一下。

**Comment by zxlhhyccc** [comment]
> vless://[011125b3-3174-4be9-bb66-435875a9c70b@vless.qq.com](mailto:011125b3-3174-4be9-bb66-435875a9c70b@vless.qq.com):443?encryption=none&security=tls&pbk=YOwK8sDJPwbpHljXJIKoOmXwIL-w6J8cb7xxINMaKm4&sid=e17f60d1cd385f5b&spx=%2Fjdf0gfc&type=splithttp&path=%2Fpath#TestLink

貌似格式有错误，为何两个path？

**Comment by wekingchen** [comment]
谢谢大佬

**Comment by wekingchen** [comment]
有两个path的原因是path值我设的就是"/path"

**Comment by zxlhhyccc** [comment]
> 有两个path的原因是path值我设的就是"/path"

感觉你这个订阅链接有问题，v2rayN和ssrp导入的都不一样。但ssrp如果把订阅链接取消tls就可以导入。

**Comment by wekingchen** [comment]
![微信截图_20240828103015](https://github.com/user-attachments/assets/1c32b5c4-7430-4ccd-954b-5381f0bd2638)
![微信截图_20240828103106](https://github.com/user-attachments/assets/cdfb044b-ffe6-4d16-89c5-7fcc7cc91ee3)
![微信截图_20240828103210](https://github.com/user-attachments/assets/99b5df93-ee12-48bc-bad7-7b1abb42b370)
passwall导入正常呢

**Comment by wekingchen** [comment]
ssrp也可以导入，但是请看导入进去就是SplitHTTP 路径一栏是空的
![微信截图_20240828105659](https://github.com/user-attachments/assets/b092fc4f-6f0a-405d-80ac-3023cc514d9e)
![微信截图_20240828105717](https://github.com/user-attachments/assets/58475f5a-3d01-44f7-99ce-47de1ffd5eac)

**Comment by zxlhhyccc** [comment]
V2rayN导入进去后SplitHTTP 路径也没有，而且UUID与ssrp导入的不一致。

**Comment by wekingchen** [comment]
V2rayN导出的就是这样呢：

vless://011125b3-3174-4be9-bb66-435875a9c70b@vless.qq.com:443?encryption=none&security=tls&pbk=YOwK8sDJPwbpHljXJIKoOmXwIL-w6J8cb7xxINMaKm4&sid=e17f60d1cd385f5b&spx=%2Fjdf0gfc&type=splithttp&path=%2Fpath#TestLink

**Comment by zxlhhyccc** [comment]
> V2rayN导出的就是这样呢：
> 
> vless://[011125b3-3174-4be9-bb66-435875a9c70b@vless.qq.com](mailto:011125b3-3174-4be9-bb66-435875a9c70b@vless.qq.com):443?encryption=none&security=tls&pbk=YOwK8sDJPwbpHljXJIKoOmXwIL-w6J8cb7xxINMaKm4&sid=e17f60d1cd385f5b&spx=%2Fjdf0gfc&type=splithttp&path=%2Fpath#TestLink

我改了一下，去掉&security=tls就转换为路径，不仅仅是splithttp，ws、h2都是这个情况。。。

**Comment by zxlhhyccc** [comment]
我还是怀疑订阅链接有问题，我没办法了，只能请大屌大佬修了。

**Comment by wekingchen** [comment]
谢谢大佬

**Comment by zxlhhyccc** [comment]
@wekingchen 问题应该已经解决了，见我提交的PR：
https://github.com/fw876/helloworld/pull/1537

**Comment by zxlhhyccc** [comment]
@wekingchen 我的pr已合并，现在可以正常导入配置了。

**Comment by wekingchen** [comment]
谢谢大佬，我现在卡在toolchain/gcc切换到12后固件编译报错上了，等搞定再试试

**Comment by zxlhhyccc** [comment]
> 谢谢大佬，我现在卡在toolchain/gcc切换到12后固件编译报错上了，等搞定再试试

12是啥东西？gcc版本吗？

**Comment by wekingchen** [comment]
是的，lede昨天升级到12之后老是编译不过去

**Comment by zxlhhyccc** [comment]
> 是的，lede昨天升级到12之后老是编译不过去

应该是不可能编译不了，clean后再编译试试。

**Comment by wekingchen** [comment]
https://github.com/coolsnowwolf/lede/issues/12462
https://github.com/coolsnowwolf/lede/issues/12464
好多人都有同样的问题，可能需要大屌大佬看看了

**Comment by zxlhhyccc** [comment]
@wekingchen 
添加这个补丁应该可以解决你的问题。
```
From 0000000000000000000000000000000000000000 Mon Sep 17 00:00:00 2001
From: Hauke Mehrtens <hauke@hauke-m.de>
Date: Sun, 14 Apr 2024 15:33:51 +0200
Subject: Support POSIX basename() from musl libc

Musl libc 1.2.5 removed the definition of the basename() function from
string.h and only provides it in libgen.h as the POSIX standard
defines it.

This change fixes compilation with musl libc 1.2.5.
````
build_dir/target-mips_24kc_musl/tini-0.19.0/src/tini.c:227:36: error: implicit declaration of function 'basename' [-Wimplicit-function-declaration]
  227 |         fprintf(file, "%s (%s)\n", basename(name), TINI_VERSION_STRING);
build_dir/target-mips_24kc_musl/tini-0.19.0/src/tini.c:227:25: error: format '%s' expects argument of type 'char *', but argument 3 has type 'int' [-Werror=format=]
  227 |         fprintf(file, "%s (%s)\n", basename(name), TINI_VERSION_STRING);
      |                        ~^          ~~~~~~~~~~~~~~
      |                         |          |
      |                         char *     int
      |                        %d

````

basename() modifies the input string, copy it first with strdup(), If
strdup() returns NULL the code will handle it.

Signed-off-by: Hauke Mehrtens <hauke@hauke-m.de>
---
 src/tini.c | 15 +++++++++++----
 1 file changed, 11 insertions(+), 4 deletions(-)

--- a/src/tini.c
+++ b/src/tini.c
@@ -14,6 +14,7 @@
 #include <stdlib.h>
 #include <unistd.h>
 #include <stdbool.h>
+#include <libgen.h>
 
 #include "tiniConfig.h"
 #include "tiniLicense.h"
@@ -224,14 +225,19 @@ int spawn(const signal_configuration_t*
 }
 
 void print_usage(char* const name, FILE* const file) {
-	fprintf(file, "%s (%s)\n", basename(name), TINI_VERSION_STRING);
+	char *dirc, *bname;
+
+	dirc = strdup(name);
+	bname = basename(dirc);
+
+	fprintf(file, "%s (%s)\n", bname, TINI_VERSION_STRING);
 
 #if TINI_MINIMAL
-	fprintf(file, "Usage: %s PROGRAM [ARGS] | --version\n\n", basename(name));
+	fprintf(file, "Usage: %s PROGRAM [ARGS] | --version\n\n", bname);
 #else
-	fprintf(file, "Usage: %s [OPTIONS] PROGRAM -- [ARGS] | --version\n\n", basename(name));
+	fprintf(file, "Usage: %s [OPTIONS] PROGRAM -- [ARGS] | --version\n\n", bname);
 #endif
-	fprintf(file, "Execute a program under the supervision of a valid init process (%s)\n\n", basename(name));
+	fprintf(file, "Execute a program under the supervision of a valid init process (%s)\n\n", bname);
 
 	fprintf(file, "Command line options:\n\n");
 
@@ -261,6 +267,7 @@ void print_usage(char* const name, FILE*
 	fprintf(file, "  %s: Send signals to the child's process group.\n", KILL_PROCESS_GROUP_GROUP_ENV_VAR);
 
 	fprintf(file, "\n");
+	free(dirc);
 }
 
 void print_license(FILE* const file) {
````

**Comment by wekingchen** [comment]
可以了，感谢大佬的帮助

**Comment by zxlhhyccc** [comment]
> 可以了，感谢大佬的帮助

订阅正常了么？

**Comment by wekingchen** [comment]
嗯嗯，正常了，感谢！
