### ISSUE TITLE
请问一下，官方openwrt r23.05.3需要特别设置下防火墙才可以使用ssr plus吗？

### ISSUE THREAD

**Issue by Elda1994** [fw876/helloworld#1529]
我是自己编译的官方的Openwrt r23.05.3分支，然后加入了helloworld插件，编译成功了，但是ssr plus一直无法连接国外的网站。系统日志了没有查到报错，但是考虑到r23.05分支，升级了防火墙为firewall4，所以求助一下， 是不是需要特定配置一下防火墙，才可以连通外网？

**Comment by Elda1994** [comment]
原来是helloworld 本身没有适配官方Op23.05.x，问题关闭，切换openwrt低版本解决吧

**Comment by 1021683053** [comment]
你的问题解决了吗？

**Comment by Elda1994** [comment]
> 你的问题解决了吗？

最后还是没完全解决，后面经过一系列折腾，ssrp勉强算是能用了，但是用一会就会报dns污染错误，找不出来原因。我最后换回了以前编译的openwrt，暂时也不打算再编译最新版ssrp了，以前的能用就行
