### ISSUE TITLE
如果启用tls，传输协议：ws、HTTPUpgrade 、HTTP/2、SplitHTTP的路径和TLS 主机名均无法导入。

### ISSUE THREAD

**Issue by zxlhhyccc** [fw876/helloworld#1530]
我搞了几天搞不定，请大佬们修复一下。
![image](https://github.com/user-attachments/assets/0f70c0b0-b9b5-4f87-b133-de3e3382a084)

**Comment by zxlhhyccc** [comment]
@chika0801 请大佬修复一下导入配置信息在启用tls时比如是传输协议HTTPUpgrade但不能导入HTTPUpgrade 路径、tls_host主机的问题。

**Comment by chika0801** [comment]
@zxlhhyccc 最近其它事多，我空了研究一下，不好意思了。

**Comment by zxlhhyccc** [comment]
@chika0801 OK!

**Comment by zxlhhyccc** [comment]
@chika0801 大佬，能否抽个空研究一下导入配置问题？

**Comment by zxlhhyccc** [comment]
@chika0801 大佬，我已提交了pr，见`https://github.com/fw876/helloworld/pull/1537`，请大佬审核修正一下。
