### ISSUE TITLE
编译helloworld报gn错误，求解决。

### ISSUE THREAD

**Issue by Elda1994** [fw876/helloworld#1533]
openwrt版本：openwrt r21.02.2

编译环境：海外vps

报错代码：
make[3]: Leaving directory '/home/21.02.2/openwrt/feeds/helloworld/luci-app-ssr-plus'
time: package/feeds/helloworld/luci-app-ssr-plus/compile#0.92#0.61#1.64
make[3]: Entering directory '/home/21.02.2/openwrt/feeds/helloworld/gn'
install -d -m0755 /home/21.02.2/openwrt/staging_dir/hostpkg/bin/
install -m0755 /home/21.02.2/openwrt/build_dir/hostpkg/gn-2024-08-13-54f5b539/out/gn /home/21.02.2/openwrt/staging_dir/hostpkg/bin/
install: cannot stat '/home/21.02.2/openwrt/build_dir/hostpkg/gn-2024-08-13-54f5b539/out/gn': No such file or directory
make[3]: *** [Makefile:58: /home/21.02.2/openwrt/staging_dir/hostpkg/stamp/.gn_installed] Error 1
make[3]: Leaving directory '/home/21.02.2/openwrt/feeds/helloworld/gn'
time: package/feeds/helloworld/gn/host-compile#0.16#0.06#0.20
    ERROR: package/feeds/helloworld/gn [host] failed to build.
make[2]: *** [package/Makefile:114: package/feeds/helloworld/gn/host/compile] Error 1
make[2]: Leaving directory '/home/21.02.2/openwrt'
make[1]: *** [package/Makefile:110: /home/21.02.2/openwrt/staging_dir/target-aarch64_cortex-a53_musl/stamp/.package_compile] Error 2
make[1]: Leaving directory '/home/21.02.2/openwrt'
make: *** [/home/21.02.2/openwrt/include/toplevel.mk:230: world] Error 2

是否自行找解决办法：
已经谷歌很久了，golang版本已经自行替换了高版本，vps已经执行sudo apt install clang，vps上的gcc版本为11+。希望得到解决答案。

额外问题：openwrt 23.05.4版本加入Helloworld插件后，可以顺利编译成功，但是我的路由器是N1，刷入N1后，ssr plus无法连接外网，其他一切正常。

**Comment by zxlhhyccc** [comment]
编译gn与golang无关，但与gcc的版本相关，gcc版本升级到13.10版本试试。CI检测通过，请查找你的编译环境问题。

**Comment by Elda1994** [comment]
> 编译gn与golang无关，但与gcc的版本相关，gcc版本升级到13.10版本试试。CI检测通过，请查找你的编译环境问题。
> 
> 看报错提示，应该是gn为生成二进制文件导致。
> 
> ![image](https://private-user-images.githubusercontent.com/45259624/364015635-6f3fa6d8-1dc8-44cc-b1bc-36bc72d6be5a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjUzNzI2ODUsIm5iZiI6MTcyNTM3MjM4NSwicGF0aCI6Ii80NTI1OTYyNC8zNjQwMTU2MzUtNmYzZmE2ZDgtMWRjOC00NGNjLWIxYmMtMzZiYzcyZDZiZTVhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MDMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTAzVDE0MDYyNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTU5ZDFkNDU5ZjA2MmIzZWE4YjZhMDA0Y2YwOTUxNjJmM2FiYjAyMjE4ZjExMWY4Zjg5OGU1N2E2ZGY0OTc2ZmEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.GGB1_GPCZFf6BDAmwW1rTLiN6HX0kfeMUatobcriFtI)

是的，报错信息是显示没有生成gn执行文件，该文件夹下确实也没有。我已经执行了：make feeds/package/helloworld/gn/compile V=99命令，但是最终编译还是报gn错误...尬住了

**Comment by zxlhhyccc** [comment]
> 额外问题：openwrt 23.05.4版本加入Helloworld插件后，可以顺利编译成功，但是我的路由器是N1，刷入N1后，ssr plus无法连接外网，其他一切正常。

旁路由吧，你旁路由设置错误。。。。

**Comment by Elda1994** [comment]
> > 额外问题：openwrt 23.05.4版本加入Helloworld插件后，可以顺利编译成功，但是我的路由器是N1，刷入N1后，ssr plus无法连接外网，其他一切正常。
> 
> 旁路由吧，你旁路由设置错误。。。。 另外，你的编译环境是什么系统？建议系统ubuntu18.04、20.04或者22.04，并将gcc更新到13.10版本，应该没有问题。

问题已经解决，谢谢。N1是主路由，旁路由都不太行。vps编译环境是 ubuntu 20.04。

**Comment by Elda1994** [comment]
问题已经解决了，贴一下我的最终解决办法：
sed -i "/helloworld/d" "feeds.conf.default"
./scripts/feeds clean
sed -i 'src-git small https://github.com/kenzok8/small' feeds.conf.default
./scripts/feeds update -a
rm -rf feeds/packages/lang/golang
git clone https://github.com/kenzok8/golang feeds/packages/lang/golang
./scripts/feeds install -a 
make -j1 V=s
p.s 感觉这应该就是所谓的玄学吧，加入helloworld源死活编译不过去，最后换了Kenzok8的源，顺利编译过...但是kenzok8的small仓库同步的不也是helloworld的代码吗？？？anyway，这个解答挂在这里，希望能帮助更多遇到这个问题的人。

**Comment by zxlhhyccc** [comment]
和哪个源没有关系，有关系的就是你的编译环境。。。
