### ISSUE TITLE
最新编译的ssr plus，浏览外网网页报错“你的连接不是专用连接”

### ISSUE THREAD

**Issue by Elda1994** [fw876/helloworld#1535]
经过漫长的编译，官方openwrt21.02.2刷入了最新版ssr plus，但是导入节点让ssr plus成功运行后，浏览google等网页，总是有概率报“你的连接不是专用连接”这个错误，再次点击回车登录后又可以登录google等网站。节点本身应该没问题，因为在v2rayN中正常使用。请问这个问题，该怎么解决呢？
![image](https://github.com/user-attachments/assets/b62e3b67-32f1-4b0a-a761-a6ddcfe76541)

**Comment by Cathgao** [comment]
dns被污染，解析到错误IP，导致证书与域名不匹配

**Comment by Elda1994** [comment]
> dns被污染，解析到错误IP，导致证书与域名不匹配

我是内网搭建的adguardhome，老哥有什么办法解决么？

**Comment by zxlhhyccc** [comment]
> 我是内网搭建的adguardhome，老哥有什么办法解决么？

你咋搭建的？看起来你搭建的有问题。
