### ISSUE TITLE
Neftlix分流模式对新域名无效

### ISSUE THREAD

**Issue by yysw** [fw876/helloworld#154]
系统：OpenWrt R20.7.20 / LuCI Master (git-20.223.26773-d18ef13) 
app版本：180.5

Netflix域名里加入YouTube等域名不生效，YouTube流量仍然走默认代理。

**Comment by Mizeron** [comment]
同上，添加pix站后也是走主代理

**Comment by Mattraks** [comment]
需要等待dns缓存过期才能生效
清理dns缓存才能立刻生效

**Comment by yysw** [comment]
> 需要等待dns缓存过期才能生效
> 清理dns缓存才能立刻生效

能确认吗？  我等了好久都不生效啊。
重启dnsmasq？
