### ISSUE TITLE
Xray-core v24.9.30   连接失败

### ISSUE THREAD

**Issue by zhrui0517** [fw876/helloworld#1546]
openwrt，Xray-core更新到v24.9.30，就一直连接失败。
服务端已更新，试了其他客户端连接正常。

**Comment by wekingchen** [comment]
遇到一样的问题

**Comment by ds0tm8340** [comment]
我也一样，听说是那个软件的锅，而不是这个库

**Comment by wekingchen** [comment]
> 我也一样，听说是那个软件的锅，而不是这个库

同样的v24.9.30，passwall就能运行成功，就是这个库需要做兼容啦

**Comment by ds0tm8340** [comment]
> > 我也一样，听说是那个软件的锅，而不是这个库
> 
> 同样的v24.9.30，passwall就能运行成功，就是这个库需要做兼容啦

因为passwall用的是老版本啊。。。他们每个用的版本是不一样的，应该是ssrplus要做兼容，又要为爱打工啦~

**Comment by zxlhhyccc** [comment]
> openwrt，Xray-core更新到v24.9.30，就一直连接失败。
> 服务端已更新，试了其他客户端连接正常。

无新版本服务端节点，暂无法复现，能否提供新版本的节点我测试修改，如愿意提供请私发邮箱：zxlhhy@163.com

**Comment by wekingchen** [comment]
> > openwrt，Xray-core更新到v24.9.30，就一直连接失败。
> > 服务端已更新，试了其他客户端连接正常。
> 
> 新版本Xray改动非常大，比如已移除quic之类，目前无新版本服务端节点，暂无法复现，能否提供新版本的节点我测试修改，如愿意提供请私发邮箱：[zxlhhy@163.com](mailto:zxlhhy@163.com) ![image](https://private-user-images.githubusercontent.com/45259624/376046643-aabe87d9-0152-4eb8-a397-b5cd5735b663.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg5ODI3OTYsIm5iZiI6MTcyODk4MjQ5NiwicGF0aCI6Ii80NTI1OTYyNC8zNzYwNDY2NDMtYWFiZTg3ZDktMDE1Mi00ZWI4LWEzOTctYjVjZDU3MzViNjYzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDE1VDA4NTQ1NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWMzNDM0MWY5MmFkNDg2NDUzMjliMGM0OTFlN2Q1MGZkNzMzZDY0NTY2MGY5NDk2MTYyZTQ0M2YyYmJlMDFjZDYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.IQFn2vpVFlE6pggYNjbMOCIAXtA_8SuhJpEKuekiVrE)

大佬，v24.9.30的节点已经发你邮箱啦

**Comment by zxlhhyccc** [comment]
> 大佬，v24.9.30的节点已经发你邮箱啦

好的，明天抽空我测试一下，按照你的节点情况我来修改一下。

**Comment by taowazi007** [comment]
客户端用之前18的不行的，要重写客户config

**Comment by zxlhhyccc** [comment]
> 客户端用之前18的不行的，要重写客户config

对的，所以先要搞清楚config是什么格式。。。

**Comment by zxlhhyccc** [comment]
> 大佬，v24.9.30的节点已经发你邮箱啦

兄弟，能私发一下你服务端的配置吗？总是有个问题困扰着我。。。。

**Comment by wekingchen** [comment]
> > 大佬，v24.9.30的节点已经发你邮箱啦
> 
> 兄弟，能私发一下你服务端的配置吗？总是有个问题困扰着我。。。。

已发了，请大佬看看

**Comment by Biercenter** [comment]
今天用openwrt官方23.05.5编译出来，然后打包后无法代理了，看了下imagebuilder自动给安了官方最新版xray-24.9.30版了。

**Comment by zxlhhyccc** [comment]
> 已发了，请大佬看看

已在搞，但事情不顺利啊，晚上准备强制搞一下。

**Comment by zxlhhyccc** [comment]
> 已发了，请大佬看看

目前初步判断配置问题不大，估计是启动脚本要适配新的版本，因为看起来是dns无法解析导致。

**Comment by wekingchen** [comment]
> > 已发了，请大佬看看
> 
> 目前初步判断配置问题不大，已确定是启动脚本要适配新的版本，因为看起来是dns无法解析导致。 已找到问题了，现在已正常链接了，明天再测试其他科学是否也无问题再提PR，争取新版本和旧版本均适配。。。。 ![image](https://private-user-images.githubusercontent.com/45259624/378110679-9e5df939-fa84-4396-9497-875c377c3c7f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjkzOTAzNDAsIm5iZiI6MTcyOTM5MDA0MCwicGF0aCI6Ii80NTI1OTYyNC8zNzgxMTA2NzktOWU1ZGY5MzktZmE4NC00Mzk2LTk0OTctODc1YzM3N2MzYzdmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDIwVDAyMDcyMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWFiYmU2ODZjZWRlYjM1OTBmYmU2ODEyNDcwMWY1Y2VkNzNjNTc5YjBmMzI4NDY3NGFkNjI1OTJmMWI4NTM1NTMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0._UGH48vVCKCsfubTPCW6dE5w2gDCL1A4e9JjOd7hnSA) ![image](https://private-user-images.githubusercontent.com/45259624/378110703-0233855a-f82b-4096-8801-a6b4046424d1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjkzOTAzNDAsIm5iZiI6MTcyOTM5MDA0MCwicGF0aCI6Ii80NTI1OTYyNC8zNzgxMTA3MDMtMDIzMzg1NWEtZjgyYi00MDk2LTg4MDEtYTZiNDA0NjQyNGQxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDIwVDAyMDcyMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPThkYWM3ZWJlMTQzNDIyMWVjMjEzZmI1ZDZhMDAxMDBiNTBkYjY1ZjU1NDVhNzYwMDI2NzdkZDliZGI2NmFhZWMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.dUAxm6MRUxv9S4pUDAGbgk6pXuz4djq7-PQT48l3z_g)

太好了，谢谢大佬

**Comment by zxlhhyccc** [comment]
> 太好了，谢谢大佬

不好意思，今天一天在外面没时间搞，明天争取提PR。。。。

**Comment by zxlhhyccc** [comment]
@wekingchen 已经修复了最新版本链接失败问题，也兼容旧版本，见PR：https://github.com/fw876/helloworld/pull/1559

**Comment by wekingchen** [comment]
> @wekingchen 已经修复了最新版本链接失败问题，也兼容旧版本，见PR：#1559

大佬V5

**Comment by zxlhhyccc** [comment]
> 大佬V5

实际上旧版服务端节点已可以使用新版本的Xray。。。

**Comment by wekingchen** [comment]
> > 大佬V5
> 
> 实际上旧版服务端节点已可以使用新版本的Xray。。。 另外，请问你的节点改了是吗？能暂时别改或者把节点我先测试吗？因为我还要测试、修改socks。。。。，那个pr不保证socks没问题。。。

抱歉抱歉，我以为搞好了，明天我恢复一下

**Comment by wekingchen** [comment]
> @wekingchen 已重新提了PR，昨日的PR代码不完善，今天提的PR应该完全兼容了1.18.24及以下版本，见：#1560 目前运行的是旧版本的节点，现在就是测试新版本socks，我认为无问题，但还是测试一下比较保险，明天烦请恢复你的节点我测试socks，谢谢。

节点已经恢复了，可以测试了

**Comment by zxlhhyccc** [comment]
> 节点已经恢复了，可以测试了

请问你的节点是哪里的VPS？速度很快的，我也想购买。

**Comment by zhrui0517** [comment]
> > 节点已经恢复了，可以测试了
> 
> 请问你的节点是哪里的VPS？速度很快的，我也想购买。

@wekingchen 同求

**Comment by wekingchen** [comment]
是最近比较热的Claw，阿里云HK线路，新商家要注意点风险，季付应该问题不大，我买的是这款现在还有货：
hk 3.5刀，季付优惠后2.8刀/月
配置：1c1g 500g  1000m
直达链接（不含aff）: https://claw.cloud/cart.php?a=add&pid=11
折扣:  20%
优惠码：Z3ZUF1RT5F

**Comment by zxlhhyccc** [comment]
> 是最近比较热的Claw，阿里云HK线路，新商家要注意点风险，季付应该问题不大，我买的是这款现在还有货： hk 3.5刀，季付优惠后2.8刀/月 配置：1c1g 500g 1000m 直达链接（不含aff）: https://claw.cloud/cart.php?a=add&pid=11 折扣: 20% 优惠码：Z3ZUF1RT5F

@wekingchen 已重新提了PR，见：https://github.com/fw876/helloworld/pull/1561    ，已经完美修复，所有问题已解决，现在准备添加分片功能，以确保不会出现断流现象，但需要测试没问题，所以请暂时别停止你的节点，谢谢！

**Comment by zxlhhyccc** [comment]
是这个吗？
![image](https://github.com/user-attachments/assets/69cfddb8-0c4d-4379-b9d4-20006a2c367e)

**Comment by wekingchen** [comment]
是这个，选季付然后用优惠码，折扣下来每月2.8刀

**Comment by zxlhhyccc** [comment]
> 是这个，选季付然后用优惠码，折扣下来每月2.8刀

你搭建的节点搞了什么bbr加速之类的吗？你的节点是脚本搭建还是手动搭建？脚本的话有脚本链接么？

**Comment by wekingchen** [comment]
用一键脚本开了bbr优化
bash <(curl -Lso- https://git.io/kernel.sh)

然后节点是用docker自己搭的

**Comment by zxlhhyccc** [comment]
不会用docker搭建节点，你用docker咋搭建的？

**Comment by wekingchen** [comment]
简单
docker run -d -p 9000:9000 --name xray --restart=always -v /etc/xray:/etc/xray teddysun/xray

配置档就正常配

**Comment by zxlhhyccc** [comment]
> 简单 docker run -d -p 9000:9000 --name xray --restart=always -v /etc/xray:/etc/xray teddysun/xray
> 
> 配置档就正常配

不走443端口？

**Comment by wekingchen** [comment]
嗯，我用caddy反代走的443，bbr是宿主机上加速的

**Comment by zhrui0517** [comment]
done

**Comment by zxlhhyccc** [comment]
@wekingchen 兄弟，你的节点又停了么，因官方分支的dnsmasq路径变化，我还要修改代码以便兼容。。。。

**Comment by wekingchen** [comment]
> @wekingchen 兄弟，你的节点又停了么，因官方分支的dnsmasq路径变化，我还要修改代码以便兼容。。。。

又改回来了

**Comment by zxlhhyccc** [comment]
> 又改回来了

好的，我搞完了后告知你关闭可以吗？

**Comment by wekingchen** [comment]
> > 又改回来了
> 
> 好的，我搞完了后告知你关闭可以吗？

好的

**Comment by wekingchen** [comment]
> > 又改回来了
> 
> 好的，我搞完了后告知你关闭可以吗？

@zxlhhyccc 大佬，这个版本编译出来的xray可以正常运行，但它之后的版本编译出来就不能运行xray了呢，能帮忙检查下吗？
![image](https://github.com/user-attachments/assets/72e6aa5b-ffd0-4d47-b9d6-a3124407f748)

**Comment by zhrui0517** [comment]
> > > 又改回来了
> > 
> > 
> > 好的，我搞完了后告知你关闭可以吗？
> 
> @zxlhhyccc 大佬，这个版本编译出来的xray可以正常运行，但它之后的版本编译出来就不能运行xray了呢，能帮忙检查下吗？ ![image](https://private-user-images.githubusercontent.com/22815621/381432778-72e6aa5b-ffd0-4d47-b9d6-a3124407f748.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzAyNzYwMDIsIm5iZiI6MTczMDI3NTcwMiwicGF0aCI6Ii8yMjgxNTYyMS8zODE0MzI3NzgtNzJlNmFhNWItZmZkMC00ZDQ3LWI5ZDYtYTMxMjQ0MDdmNzQ4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMzAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDMwVDA4MDgyMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTBjY2U4MzllZDFiZjgyZjZmYTg0MWI0ZjA3Yzg1NDE2ZGFlMTFiZmQzNjk4M2Q1MTViZTM4ZDhjZjY0MjAxZDcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.FwvKP6EQDmKRWfNCEvWf_MokZ2ZnX9FAEQjgNptG1WM)

把配置文件删了 重新更新一下试试看 我也遇到这个问题就是这么恢复的

**Comment by wekingchen** [comment]
> > > > 又改回来了
> > > 
> > > 
> > > 好的，我搞完了后告知你关闭可以吗？
> > 
> > 
> > @zxlhhyccc 大佬，这个版本编译出来的xray可以正常运行，但它之后的版本编译出来就不能运行xray了呢，能帮忙检查下吗？ ![image](https://private-user-images.githubusercontent.com/22815621/381432778-72e6aa5b-ffd0-4d47-b9d6-a3124407f748.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzAyNzYwMDIsIm5iZiI6MTczMDI3NTcwMiwicGF0aCI6Ii8yMjgxNTYyMS8zODE0MzI3NzgtNzJlNmFhNWItZmZkMC00ZDQ3LWI5ZDYtYTMxMjQ0MDdmNzQ4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMzAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDMwVDA4MDgyMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTBjY2U4MzllZDFiZjgyZjZmYTg0MWI0ZjA3Yzg1NDE2ZGFlMTFiZmQzNjk4M2Q1MTViZTM4ZDhjZjY0MjAxZDcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.FwvKP6EQDmKRWfNCEvWf_MokZ2ZnX9FAEQjgNptG1WM)
> 
> 把配置文件删了 重新更新一下试试看 我也遇到这个问题就是这么恢复的

是删除/etc/config/shadowsocksr这个文件吗？

**Comment by zhrui0517** [comment]
> > > > > 又改回来了
> > > > 
> > > > 
> > > > 好的，我搞完了后告知你关闭可以吗？
> > > 
> > > 
> > > @zxlhhyccc 大佬，这个版本编译出来的xray可以正常运行，但它之后的版本编译出来就不能运行xray了呢，能帮忙检查下吗？ ![image](https://private-user-images.githubusercontent.com/22815621/381432778-72e6aa5b-ffd0-4d47-b9d6-a3124407f748.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzAyNzYwMDIsIm5iZiI6MTczMDI3NTcwMiwicGF0aCI6Ii8yMjgxNTYyMS8zODE0MzI3NzgtNzJlNmFhNWItZmZkMC00ZDQ3LWI5ZDYtYTMxMjQ0MDdmNzQ4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMzAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDMwVDA4MDgyMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTBjY2U4MzllZDFiZjgyZjZmYTg0MWI0ZjA3Yzg1NDE2ZGFlMTFiZmQzNjk4M2Q1MTViZTM4ZDhjZjY0MjAxZDcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.FwvKP6EQDmKRWfNCEvWf_MokZ2ZnX9FAEQjgNptG1WM)
> > 
> > 
> > 把配置文件删了 重新更新一下试试看 我也遇到这个问题就是这么恢复的
> 
> 是删除/etc/config/shadowsocksr这个文件吗？

对 你试试看
