### ISSUE TITLE
使用订阅就无法连接

### ISSUE THREAD

**Issue by BallM8964** [fw876/helloworld#1547]
最新编译的固件，SSRP添加订阅后，直接使用订阅节点提示谷歌检测错误，也连不上。然后诡异的是，如果手工添加节点，就都正常，谷歌测试也能过。

最初以为是之前的固件里面有什么配置文件不对，然后在PVE虚机上新开了1个镜像从头做起，还是同样的问题。

找了了自己去年10月份编译的版本，也新开了一个镜像对比测试，则完全正常。

现在折中的办法就是新建一个去年10月编译的版本镜像，然后 “保留配置升级” 到最新编译的版本，又是正常的。

猜测是关于订阅（转换？）部分的代码可能存在问题

**Comment by BallM8964** [comment]
补充说明：订阅是我自己用github文件转换成加密文件通过netlify自动发布，CFT前置域名做CDN规避GFW屏蔽的。
之前使用的历代版本都没问题（基本上是每年编译1-2个版本来更新），这次版本编译可能间隔了1年太久了，不了解合进了什么新东西，还请帮忙检查一下，感谢！

**Comment by zxlhhyccc** [comment]
> 补充说明：订阅是我自己用github文件转换成加密文件通过netlify自动发布，CFT前置域名做CDN规避GFW屏蔽的。 之前使用的历代版本都没问题（基本上是每年编译1-2个版本来更新），这次版本编译可能间隔了1年太久了，不了解合进了什么新东西，还请帮忙检查一下，感谢！

无法复现，估计还是你的订阅链接有问题，如果可以能否私发订阅链接，我测试一下看是否需要修改一些代码。

**Comment by BallM8964** [comment]
> > 补充说明：订阅是我自己用github文件转换成加密文件通过netlify自动发布，CFT前置域名做CDN规避GFW屏蔽的。 之前使用的历代版本都没问题（基本上是每年编译1-2个版本来更新），这次版本编译可能间隔了1年太久了，不了解合进了什么新东西，还请帮忙检查一下，感谢！
> 
> 无法复现，估计还是你的订阅链接有问题，如果可以能否私发订阅链接，我测试一下如果确实有问题看是否需要修改一些代码。

不常用git发私信，实在没找到怎么发，也没有找到您的邮箱，麻烦您给我发一个私信或者邮件，我来回复。
订阅链接应该不会有啥问题，一直用了很多年了，从ss vmess trojan vless各种订阅格式一路用过来的，在安卓、苹果的各类客户端上都能正常使用。

**Comment by Jason6111** [comment]
> > > 补充说明：订阅是我自己用github文件转换成加密文件通过netlify自动发布，CFT前置域名做CDN规避GFW屏蔽的。 之前使用的历代版本都没问题（基本上是每年编译1-2个版本来更新），这次版本编译可能间隔了1年太久了，不了解合进了什么新东西，还请帮忙检查一下，感谢！
> > 
> > 
> > 无法复现，估计还是你的订阅链接有问题，如果可以能否私发订阅链接，我测试一下如果确实有问题看是否需要修改一些代码。
> 
> 不常用git发私信，实在没找到怎么发，也没有找到您的邮箱，麻烦您给我发一个私信或者邮件，我来回复。 订阅链接应该不会有啥问题，一直用了很多年了，从ss vmess trojan vless各种订阅格式一路用过来的，在安卓、苹果的各类客户端上都能正常使用。

提示订阅地址空白？你随便选一个配置进去 再保存看看应该就能用了 应该是
flow = ((server.xtls == '1') or (server.tls == '1') or (server.reality == '1')) and server.tls_flow or nil
			security = (server.xtls == '1') and "xtls" or (server.tls == '1') and "tls" or (server.reality == '1') and "reality" or nil,
			tlsSettings = (server.tls == '1') and (server.tls_host or server.fingerprint) and {
这两行的问题 我把这两个改回原来的就没问题

**Comment by BallM8964** [comment]
> > > > 补充说明：订阅是我自己用github文件转换成加密文件通过netlify自动发布，CFT前置域名做CDN规避GFW屏蔽的。 之前使用的历代版本都没问题（基本上是每年编译1-2个版本来更新），这次版本编译可能间隔了1年太久了，不了解合进了什么新东西，还请帮忙检查一下，感谢！
> > > 
> > > 
> > > 无法复现，估计还是你的订阅链接有问题，如果可以能否私发订阅链接，我测试一下如果确实有问题看是否需要修改一些代码。
> > 
> > 
> > 不常用git发私信，实在没找到怎么发，也没有找到您的邮箱，麻烦您给我发一个私信或者邮件，我来回复。 订阅链接应该不会有啥问题，一直用了很多年了，从ss vmess trojan vless各种订阅格式一路用过来的，在安卓、苹果的各类客户端上都能正常使用。
> 
> 提示订阅地址空白？你随便选一个配置进去 再保存看看应该就能用了 应该是 flow = ((server.xtls == '1') or (server.tls == '1') or (server.reality == '1')) and server.tls_flow or nil security = (server.xtls == '1') and "xtls" or (server.tls == '1') and "tls" or (server.reality == '1') and "reality" or nil, tlsSettings = (server.tls == '1') and (server.tls_host or server.fingerprint) and { 这两行的问题 我把这两个改回原来的就没问题

地址不是空白，节点能加载出来，但是如果使用订阅的节点，实际上是不通的。但是切到手工添加的节点就OK。
很奇怪的故障。

**Comment by zxlhhyccc** [comment]
> 不常用git发私信，实在没找到怎么发，也没有找到您的邮箱，麻烦您给我发一个私信或者邮件，我来回复。
> 订阅链接应该不会有啥问题，一直用了很多年了，从ss vmess trojan vless各种订阅格式一路用过来的，在安卓、苹果的各类客户端上都能正常使用。

请私信：zxlhhy@163.com

**Comment by Jason6111** [comment]
> > > > > 补充说明：订阅是我自己用github文件转换成加密文件通过netlify自动发布，CFT前置域名做CDN规避GFW屏蔽的。 之前使用的历代版本都没问题（基本上是每年编译1-2个版本来更新），这次版本编译可能间隔了1年太久了，不了解合进了什么新东西，还请帮忙检查一下，感谢！
> > > > 
> > > > 
> > > > 无法复现，估计还是你的订阅链接有问题，如果可以能否私发订阅链接，我测试一下如果确实有问题看是否需要修改一些代码。
> > > 
> > > 
> > > 不常用git发私信，实在没找到怎么发，也没有找到您的邮箱，麻烦您给我发一个私信或者邮件，我来回复。 订阅链接应该不会有啥问题，一直用了很多年了，从ss vmess trojan vless各种订阅格式一路用过来的，在安卓、苹果的各类客户端上都能正常使用。
> > 
> > 
> > 提示订阅地址空白？你随便选一个配置进去 再保存看看应该就能用了 应该是 flow = ((server.xtls == '1') or (server.tls == '1') or (server.reality == '1')) and server.tls_flow or nil security = (server.xtls == '1') and "xtls" or (server.tls == '1') and "tls" or (server.reality == '1') and "reality" or nil, tlsSettings = (server.tls == '1') and (server.tls_host or server.fingerprint) and { 这两行的问题 我把这两个改回原来的就没问题
> 
> 地址不是空白，节点能加载出来，但是如果使用订阅的节点，实际上是不通的。但是切到手工添加的节点就OK。 很奇怪的故障。

![IMG_3941](https://github.com/user-attachments/assets/d4733387-9c85-437c-ae7b-e2556ccf2105)尝试改回去 我这么做是可以的

**Comment by Jason6111** [comment]
> > 尝试改回去 我这么做是可以的
> 
> 你这个是破坏了![image](https://private-user-images.githubusercontent.com/45259624/375403255-0e605eec-060f-435d-b0b2-ad674f198b7a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg1Njg0MjEsIm5iZiI6MTcyODU2ODEyMSwicGF0aCI6Ii80NTI1OTYyNC8zNzU0MDMyNTUtMGU2MDVlZWMtMDYwZi00MzVkLWIwYjItYWQ2NzRmMTk4YjdhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDEwVDEzNDg0MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTMwZDFlMTBmMDMxMGYyYmI4MTk0NWZkMmVkMzQyYTM5NmQ5ZjVjZWY0ODEwY2EwYTIxODFmNWExZTBiN2JhMzYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.5L0T4ivlwAOXhW5CUyNUZ-vRurRz7mglyh9iwNZEOho)，会导致配置导入信息很多参数为空，当时是我改动的代码，我测试没问题，修改代码要看上下文代码的要求。所以我认为问题不是出在这两行代码，只有用实际订阅才能排查。

好吧可能出的问题何我不一样 我是订阅为空 要么就是之前订阅好的无法使用 必须进去手动保存后才能使用

**Comment by BallM8964** [comment]
> > 不常用git发私信，实在没找到怎么发，也没有找到您的邮箱，麻烦您给我发一个私信或者邮件，我来回复。
> > 订阅链接应该不会有啥问题，一直用了很多年了，从ss vmess trojan vless各种订阅格式一路用过来的，在安卓、苹果的各类客户端上都能正常使用。
> 
> 请私信：[zxlhhy@163.com](mailto:zxlhhy@163.com)

订阅地址已经邮件发了，还请帮忙检查看看，烦劳了

**Comment by zxlhhyccc** [comment]
> 订阅地址已经邮件发了，还请帮忙检查看看，烦劳了

今天身体有点不舒服，明天抽个时间我测试一下，有问题的话我争取修修。。。

**Comment by zxlhhyccc** [comment]
> 订阅地址已经邮件发了，还请帮忙检查看看，烦劳了

1、经测试，你的服务器可能使用的旧版的Xray，而你的客户端Xray使用的可能是新版本，比如：2024.9.30版本，此时能运行但会导致无法科学，因为新版本的Xray中已经移除 QUIC、DomainSocket 传输层，移除对远古配置的兼容代码，因此建议你使用1.8.24及以下版本绝对没问题（此仓库就是1.8.24版本）。
2、待新版本搭建的服务端订阅后如果还是无法科学，到时再来修改代码，因为本人无新版本的订阅链接或者节点。

**Comment by BallM8964** [comment]
> > 订阅地址已经邮件发了，还请帮忙检查看看，烦劳了
> 
> 已修复，见PR：#1551
> 
> 提示：因新版本Xray改动较大，本人无新版本的节点无法测试修改，所以暂勿使用新版本的Xray，如：2024.9.30，目前可以使用的版本是1.8.24版本及以下。

服务端的版本最高1.8.24，大部分还在1.8.23
客户端的版本就是这个库最新的的1.8.24，没有跟project X 的 按年月日的版本。
新的代码等周末抽空编译测试一下。
万分感谢！

**Comment by BallM8964** [comment]
> > 订阅地址已经邮件发了，还请帮忙检查看看，烦劳了
> 
> 已修复，见PR：#1551
> 
测试失败了。和以前故障一样。
另外不知道为啥，一更新以后，虽然Makfile里面写的是1.8.24，但是实际下载了24.9.30编译的。
我重新git clone一份LEDE，还是一样，见截图。
![Uploading 2024-10-19_142220.png…]()

**Comment by BallM8964** [comment]
> > 订阅地址已经邮件发了，还请帮忙检查看看，烦劳了
> 
> 已修复，见PR：#1551
> 
> 提示：因新版本Xray改动较大，本人无新版本的节点无法测试修改，所以暂勿使用新版本的Xray，如：2024.9.30，目前可以使用的版本是1.8.24版本及以下。

找到xray core版本异常的罪魁祸首以后，修改为1.8.24，重新编译，编译后不保留配置刷新系统，确认订阅异常的问题解决了。
感谢大佬！再三膜拜！

**Comment by zxlhhyccc** [comment]
@BallM8964 我已修复最新版本的Xray使用旧版本的服务器节点了，见PR：https://github.com/fw876/helloworld/pull/1560
