### ISSUE TITLE
Xray的Makefile文件里面版本是1.8.24，make download下来版本是 24.9.30

### ISSUE THREAD

**Issue by BallM8964** [fw876/helloworld#1555]
而且居然也能编译过了。。。
好奇怪，我查了xray-core目录下的Makefile文件，helloworld.index都是正确的，手工按Makefile文件链接下载也是对的
size: 650254 Oct 19 13:31  xray-core-v1.8.24.tar.gz
size: 630029 Oct 19 13:08  xray-core-24.9.30.tar.gz
两个文件尺寸明显是不一样的。

为了避免异常，重新git clone做的。

真是奇了怪了
![image](https://github.com/user-attachments/assets/89fbe2c3-9fb3-478e-9d07-e5a8a251f30e)

**Comment by BallM8964** [comment]
可能找到原因了，/lede/feeds/packages/net/xray-core/Makefile 文件里面是 24.9.30

![image](https://github.com/user-attachments/assets/fa9b7065-fc19-4b1a-ab51-65c098d8ce5d)

**Comment by BallM8964** [comment]
溯源找到了，这个是为了新的luci单独写的一个放xray core的地方？
看时间是昨天新增的。。。。
坑啊！！！


![image](https://github.com/user-attachments/assets/3d5bb02a-0605-4684-9b4a-b080479fbb39)

**Comment by Biercenter** [comment]
ssr+不兼容新版的xray，看到大佬在适配了。我用官方23.05.5版imagebuilder打包出来也是新版的xray24版了，最后只能用7z修改xray的版本号，改成比官方源的新才安装上旧版的xray，太折腾了。
