### ISSUE TITLE
关于SOCKS5 代理服务端(全局) 设置的建议

### ISSUE THREAD

**Issue by garryforreg** [fw876/helloworld#156]
在高级设置里添加这么一项设置容易让人摸不着头脑.
我理解这个配置的作用是可以指定线路,相当于给客户端一个分流的作用.

那这个是不是可以和服务端设置里面的 socks5服务器合并.
服务端那边不管是socks5还是ssr服务端,增加一个选项,选项里面可以选择具体的线路,也可以选择自动.
选自动就走系统的主服务器逻辑,选具体线路就是一个分流服务端,完全覆盖了前面的配置而且整体看起来更统一.

**Comment by Mattraks** [comment]
全局是局域网用的,服务端是外网使用的

**Comment by garryforreg** [comment]
"全局" 外网不能使用吗? 加个端口映射外网一样用 
"服务端" 局域网也一样可以使用啊

不知道为什么强行做这种区分

**Comment by Mattraks** [comment]
你是不是没搞清楚用途啊
全局是完全走代理,这个不加密完全是给局域网使用的如专用游戏设备之类
服务端是根据你的当前设置的运行模式分流

**Comment by garryforreg** [comment]
不知道你是不是没看清我最上面写的建议:

> 服务端那边不管是socks5还是ssr服务端,增加一个选项,选项里面可以选择具体的线路,也可以选择自动.

按这种方式设置后,俩个功能不是完全可以统一? 选了**具体的线路**就是全局走指定的线路代理,选**自动**就是按当前设置的运行模式来分流

**Comment by Mattraks** [comment]
如果你认为需要,请自行尝试合并
另外两种模式处理方式不同请谨慎处理

**Comment by garryforreg** [comment]
目前的这种方式,只能在全局代理那里指定一条线路进行分流,如果有多条线路需要分流就满足不了了
按我上面提的建议就可以实现多线分流
我只是提个建议,采不采纳就看作者们觉得是否有必要了

**Comment by Mattraks** [comment]
目前从稳定性考虑不建议搞很多分流,影响性能还容易崩

**Comment by garryforreg** [comment]
好吧,看来目前想要多线分流功能只能去选openclash了

**Comment by Mattraks** [comment]
这终究是服务端也无法达到分流的目的
