### ISSUE TITLE
最新的官方openwrt主线开发版下ssrp不能使了

### ISSUE THREAD

**Issue by qwerttvv** [fw876/helloworld#1571]
头几天编译的fw4的还没问题，从昨天发现，配置文件没变，软件设置没变，ssrp挂了

然后我试了firewall和firewall4，都不行，官方和immortalwrt也都试了，不行

看更新记录，有一波 iptables: update to 1.8.10 ，回退后编译了，还是不行，看近期别的更新记录也看不出个所以然……

表现就是服务可以正常跑起来，绿字 ShadowsocksR Plus+ RUNNING， 但是状态 里 【谷歌】连通性检查 失败，客户端无法访问外网，只有全局模式才能用

哦对， dns是dns2tcp的8888

**Comment by QYC-Unity** [comment]
遇到了同样的问题

**Comment by Biercenter** [comment]
应该是@zxlhhyccc大佬提交的修正还没通过 #1570 等通过了就可以了

**Comment by hcym** [comment]
pass，clash也不对劲，只能v2raya
23.05正常

**Comment by zxlhhyccc** [comment]
> 头几天编译的fw4的还没问题，从昨天发现，配置文件没变，软件设置没变，ssrp挂了
> 
> 然后我试了firewall和firewall4，都不行，官方和immortalwrt也都试了，不行
> 
> 看更新记录，有一波 iptables: update to 1.8.10 ，回退后编译了，还是不行，看近期别的更新记录也看不出个所以然……
> 
> 表现就是服务可以正常跑起来，绿字 ShadowsocksR Plus+ RUNNING， 但是状态 里 【谷歌】连通性检查 失败，客户端无法访问外网，只有全局模式才能用
> 
> 哦对， dns是dns2tcp的8888

我就是openwrt官方主线正常使用。。。。请使用我提交的PR：https://github.com/fw876/helloworld/pull/1570

**Comment by zxlhhyccc** [comment]
> 你能不能有时间试一下官方开发板最新递交编译一个，如果可以用，你看看你是fw4还是旧版，nft和ipt相关组件给咱拉一个单子参考参考

我现在就是最新的官方openwrt，请看版本号，我现在切换为ss rust，一样的正常运行使用：
![image](https://github.com/user-attachments/assets/2fa84b4b-cbaf-4adf-ba50-66c05c429da8)
![image](https://github.com/user-attachments/assets/05795494-6434-4936-b1a8-7f0e983ae236)
![image](https://github.com/user-attachments/assets/6b0cef54-3b2f-4327-bb88-5125563d7f45)
![image](https://github.com/user-attachments/assets/afda4a22-1f7d-457c-9f09-0a987cbf2f82)

**Comment by zxlhhyccc** [comment]
我已添加了Xray的分片功能，有谁能测试一下吗？详见：

**Comment by zxlhhyccc** [comment]
> 你看看你防火墙和dnsmasq怎么设置的

防火墙你想看哪里？防火墙我就是官方默认，啥都没加。。。
我没用dnsmasq，而是smartdns转发，等会测试用dnsmasq转发试试。。。

**Comment by zxlhhyccc** [comment]
> 你gfw模式可用？

貌似gfw模式不可用，我一般不用gfw模式。

**Comment by zxlhhyccc** [comment]
> 另外你要有时间，试试我那个smartdns的设置，配置在我那边开的issue里，你看看你重启路由器正常吗？谨慎啊，有可能死机……

smartdns我一直正常，估计是你配置问题。

**Comment by zxlhhyccc** [comment]
> 你gfw模式可用？

gfw模式估计是ipt新版引起了问题，要去排查ipt和ssrp脚本。

**Comment by zxlhhyccc** [comment]
> 你gfw模式可用？

gfw模式我已找到问题了，现在已经可以正常使用gfw模式了。
![image](https://github.com/user-attachments/assets/d30cae76-97ed-48b3-8d30-8217fc902e31)
![image](https://github.com/user-attachments/assets/b104595d-3a88-4922-92fa-6ada12ae4fe4)

**Comment by zxlhhyccc** [comment]
> $IPT -A SS_SPEC_WAN_AC -j SS_SPEC_WAN_FW
> 
> 这个吗？会对以前的机智有不良影响吗？
> 
> 晚点回去看看

对以前的机制如有影响再说咯，找到原因就好办了。。。。

**Comment by hcym** [comment]
2305安稳过日子
明年再说
🥺😂

**Comment by zxlhhyccc** [comment]
> 我新旧机制的固件都有，我晚点儿回去试试

那新旧机制的加这行代码测试一下，结果请告知，谢谢！

**Comment by zxlhhyccc** [comment]
> 新机制固件正在编译，一会儿就好，晚上回去试

OK！

**Comment by zxlhhyccc** [comment]
> 新机制固件正在编译，一会儿就好，晚上回去试

咋样？可以了吗？

**Comment by zxlhhyccc** [comment]
我没使用fw4，那我就不知道了，我是fw3.。。

**Comment by zxlhhyccc** [comment]
> dns没问题吧，刷回去以前固件就好了，开的没缓存的dns2tcp

我不知道你是什么原因，我这里一切正常。。。。
IPset这个包你编译了吗？

**Comment by zxlhhyccc** [comment]
> ipset - 7.21-r1

你不编译fw4试试。。。。

**Comment by zxlhhyccc** [comment]
> 我也试过Revert "iptables: update to 1.8.10"，是不行的
> 
> [qwerttvv/immortalwrt@32e8c0d](https://github.com/qwerttvv/immortalwrt/commit/32e8c0dd1a75c1ae9bb7073f209fd0ef00939def)

回退还要改netfilter.mk，另外，你的ipt里咋多了一个shysdev？去掉试试。。。

**Comment by zxlhhyccc** [comment]
> 试了，不行，只不过固件在本地已经删了，github编译的有些乱，没标记，不知道哪个是哪个了

重新编译刷机，我远程看看可否？毕竟我这里无法复现。。。。

**Comment by zxlhhyccc** [comment]
> 你那个pr里相关部分先删了得了

删什么？没必要啥，gfw模式本来要修复的。

**Comment by zxlhhyccc** [comment]
> 你那个pr里相关部分先删了得了

刚看了一下dnsmasq，难道是它的原因？明天远程看看你的情况再说了。

**Comment by zxlhhyccc** [comment]
@qwerttvv 问题解决了吗？

**Comment by zxlhhyccc** [comment]
> 没，早起出来时候试了一下fw4+nft的，不行，其余仨没试，晚上回去的

我怀疑一个地方，就等远程你的路由我改一下启动脚本试试，怀疑是dnsmasq的路径问题

**Comment by zxlhhyccc** [comment]
> 什么路径啊，我现在打开squashfs-sysupgrade.bin的init.d看看
> 
> 早起应该试的是 https://github.com/qwerttvv/t6/releases/tag/2024.10.28-0117_M2-ss-VIKINGYFY 这就是fw4+nft

我改了init，晚上远程试试，理论上应该没有问题了，openclash估计也是dnsmasq路径问题引起的。。。。

**Comment by zxlhhyccc** [comment]
> 这玩意改动最近还挺频繁，不过我也看不懂是真的…这密密麻麻的……

我测试没问题了，你有tg吗？我把init启动脚本发你试试。。。

**Comment by zxlhhyccc** [comment]
@qwerttvv 我已修复，请见最新的commit： https://github.com/fw876/helloworld/commit/7869f77ecb697e4b569621d6eda3ce8650bab7b4
