### ISSUE TITLE
保存并应用按钮不生效

### ISSUE THREAD

**Issue by jiaopengzi** [fw876/helloworld#1574]
在新版:固件：LEDE R24.10.24 / LuCI openwrt-23.05 branch git-24.300.80039-252ad36
ssrp:Main node:Xray 24.10.16 (Xray, Penetrates Everything.) OpenWrt (go1.23.1 linux/amd64) Started!

在 ssrp 中->访问控制 中的【不走代理的域名】【强制走代理的域名】【禁止连接的域名】【Netflix分流域名列表】四个选项中的 按钮保存并应用不生效。如下图。 
其他选项是保存并应用按钮正常

不生效的按钮
![image](https://github.com/user-attachments/assets/b50d5c15-21c8-4062-b7c2-719a700265ee)

![image](https://github.com/user-attachments/assets/2cb4e393-15cc-4d63-9cc0-0370bd182a88)

正常按钮
![image](https://github.com/user-attachments/assets/59bb8104-ef96-4b15-9cfc-857cb72c2690)

**Comment by zxlhhyccc** [comment]
这些是写入普通文件的列表中，不涉及到插件的配置变更。其次，保存应用后实际已写入列表。

**Comment by jiaopengzi** [comment]
原来的就 UI 是可以的，保存应用再启动的。还是说新版 UI 的设计逻辑变了。这个弹窗响应的逻辑相较于原来老 UI 交互就不太合理了。

**Comment by zxlhhyccc** [comment]
> 原来的就 UI 是可以的，保存应用再启动的。还是说新版 UI 的设计逻辑变了。这个弹窗响应的逻辑相较于原来老 UI 交互就不太合理了。

旧版的UI一直是这个逻辑吧。。。。

**Comment by jiaopengzi** [comment]
可能是我记错了。不折腾他了，谢谢您的解答。

**Comment by zxlhhyccc** [comment]
@jiaopengzi 你的问题已解决，见PR： https://github.com/fw876/helloworld/pull/1634

**Comment by jiaopengzi** [comment]
> @jiaopengzi你的问题已解决，见PR：#1634

nice
