### ISSUE TITLE
最新修改客户端启动不了

### ISSUE THREAD

**Issue by guhill1** [fw876/helloworld#1576]
最新修改客户端启动不了
固件ImmortalWrt SNAPSHOT 
LuCI Master 24.299.28356~df6a913
平台x86
节点xray vless reality 24.9.30
日志显示正常
![2024-10-29_123511](https://github.com/user-attachments/assets/b342e6bd-daae-4662-bfa3-3a684ee736cf)
昨天中午还可以正常使用

**Comment by taowazi007** [comment]
gen_config.lua还原两天前的码就可以了

**Comment by guhill1** [comment]
> gen_config.lua还原两天前的码就可以了

好的,谢谢

**Comment by mmeiwenlong** [comment]
怎么还原，

**Comment by coolsnowwolf** [comment]
xray 么

**Comment by DanielChen008** [comment]
> xray 么

对，我是 xray-reality，也是昨晚编译后 SSR 无法启动，始终是“未运行”。

**Comment by taowazi007** [comment]
> 怎么还原，

对照2天前的gen_config.lua源码改变，改动/usr/share/shadowsocksr/gen_config.lua

**Comment by zxlhhyccc** [comment]
> 昨天中午还可以正常使用

![image](https://github.com/user-attachments/assets/41c2eabe-4672-46b5-a0e5-0b099504b46a)
![image](https://github.com/user-attachments/assets/6c237aad-1692-43c2-985d-d400e4875691)

**Comment by DanielChen008** [comment]
> > 昨天中午还可以正常使用
> 
> 一切都正常，不知道你是什么情况，如果你确实不能启动，能否私发节点我测试？[zxlhhy@163.com](mailto:zxlhhy@163.com) 或者把你启动后生成的配置发我看看，可以隐去你的节点信息。。。
> 
> ![image](https://private-user-images.githubusercontent.com/45259624/381130007-41c2eabe-4672-46b5-a0e5-0b099504b46a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzAyMDcwMzksIm5iZiI6MTczMDIwNjczOSwicGF0aCI6Ii80NTI1OTYyNC8zODExMzAwMDctNDFjMmVhYmUtNDY3Mi00NmI1LWEwZTUtMGIwOTk1MDRiNDZhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDI5VDEyNTg1OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWY2NDAwMDFlYWU1ZTNmOGM5MTk1Nzg2YWFkNzRhNDc0NDdkMWNmM2MxMTQ0Nzk2NjkwMGI2ZDk5ZDBmZWZiNTcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.xujViggFLTBbiAbsfS_zpWkOS50Suuls0gxuQ9vQ2nI) ![image](https://private-user-images.githubusercontent.com/45259624/381130416-6c237aad-1692-43c2-985d-d400e4875691.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzAyMDcwMzksIm5iZiI6MTczMDIwNjczOSwicGF0aCI6Ii80NTI1OTYyNC8zODExMzA0MTYtNmMyMzdhYWQtMTY5Mi00M2MyLTk4NWQtZDQwMGU0ODc1NjkxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDI5VDEyNTg1OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTAxMWNjOTc2MTM4NWQ5Y2ZiZDhhYjQ2NWNiYzgzMGQxOWM4MTllYThlNzJkYjNkNjBiYzgyMDA2OGI5NTliMzEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.GWABLWP3i53MV773xc2dyWBoBulZoyZ9J6NLIc5s2q0)

看 L 大那边有个同样的 Issue 在讨论，说是直接升才会这样，建议删除配置重新配一次 Server 。我正在编译，待会试试~

**Comment by zxlhhyccc** [comment]
> 看 L 大那边有个同样的 Issue 在讨论，说是直接升才会这样，建议删除配置重新配一次 Server 。我正在编译，待会试试~

ssrp启动后看一下dnsmasq路径：
![image](https://github.com/user-attachments/assets/29676ff2-fbce-4f8c-a2fd-648339dd4530)

**Comment by zxlhhyccc** [comment]
> xray 么

大屌大佬，我们都没问题，怀疑是其自身原因。。。。

**Comment by DanielChen008** [comment]
> > 看 L 大那边有个同样的 Issue 在讨论，说是直接升才会这样，建议删除配置重新配一次 Server 。我正在编译，待会试试~
> 
> 直接升是什么意思，保留配置刷固件吗？如果是，一直都是建议不保留配置升级。另外，ssrp启动后看一下dnsmasq路径：
> 
<img width="1439" alt="image" src="https://github.com/user-attachments/assets/67039144-49da-448a-94b7-c4c48a94ce44">
<img width="1043" alt="image" src="https://github.com/user-attachments/assets/214e43e2-e2a8-4592-b378-b98d7c768428">

**Comment by zxlhhyccc** [comment]
可以把DHCP单独保留，然后升级后复制进去就可以。。。

**Comment by DanielChen008** [comment]
> 你dnsmasq目前还是旧版吗？可以把DHCP单独保留，然后升级后复制进去就可以。。。请贴出你的配置： ![image](https://private-user-images.githubusercontent.com/45259624/381160034-77b6f37d-13ef-4e17-ac83-77287c50f331.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzAyMTE5MjUsIm5iZiI6MTczMDIxMTYyNSwicGF0aCI6Ii80NTI1OTYyNC8zODExNjAwMzQtNzdiNmYzN2QtMTNlZi00ZTE3LWFjODMtNzcyODdjNTBmMzMxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDI5VDE0MjAyNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQ2ZGEzNmE1OThlODZjMmQyNTZhZTRjNWRiOWU3MGE0YmUyZTE2MGMxZjViMjljZDkzN2M2NDg4YWRlZGM3ZjYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.jQx8P3B-WsLWMZstfn8e4-gGObdwpej0yc9NnC1ceOA) 节点信息你可以任意代替。。。

在您回复的期间，我已经按您的建议弄了，哈哈哈～
找了张新的 TF 卡，用今晚编译的新固件写卡后，插回 R4S 启动后从头开始重新配了一遍，顺带备份了老系统里的 /etc/config/dhcp 文件，把里面的 DHCP 清单复制到了新系统下，不然重新手动一个个的添加确实要疯了 ～
干净的系统，确实，SSR 正常启动运行了～

感谢，感谢～！

**Comment by zxlhhyccc** [comment]
> 在您回复的期间，我已经按您的建议弄了，哈哈哈～ 找了张新的 TF 卡，用今晚编译的新固件写卡后，插回 R4S 启动后从头开始重新配了一遍，顺带备份了老系统里的 /etc/config/dhcp 文件，把里面的 DHCP 清单复制到了新系统下，不然重新手动一个个的添加确实要疯了 ～ 干净的系统，确实，SSR 正常启动运行了～
> 
> 感谢，感谢～！

以后请先找找问题成因再提问题。。。谢谢！

**Comment by DanielChen008** [comment]
> > 在您回复的期间，我已经按您的建议弄了，哈哈哈～ 找了张新的 TF 卡，用今晚编译的新固件写卡后，插回 R4S 启动后从头开始重新配了一遍，顺带备份了老系统里的 /etc/config/dhcp 文件，把里面的 DHCP 清单复制到了新系统下，不然重新手动一个个的添加确实要疯了 ～ 干净的系统，确实，SSR 正常启动运行了～
> > 感谢，感谢～！
> 
> 以后请先找找问题成因再提问题。。。谢谢！

不是我提的……=.=! 遇到了同样的问题来逛 issue 看到有人在问罢了…… 总之，已解决，thx

**Comment by guhill1** [comment]
> > 昨天中午还可以正常使用
> 
> 一切都正常，不知道你是什么情况，如果你确实不能启动，能否私发节点我测试？[zxlhhy@163.com](mailto:zxlhhy@163.com) 或者把你启动后生成的配置发我看看，可以隐去你的节点信息。。。
> 
> ![image](https://private-user-images.githubusercontent.com/45259624/381130007-41c2eabe-4672-46b5-a0e5-0b099504b46a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzAyMjY2MDgsIm5iZiI6MTczMDIyNjMwOCwicGF0aCI6Ii80NTI1OTYyNC8zODExMzAwMDctNDFjMmVhYmUtNDY3Mi00NmI1LWEwZTUtMGIwOTk1MDRiNDZhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDI5VDE4MjUwOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTA2MmQ0MWE4NWFhNDZmNDhlODhlZWFmYmZhZjYwMjk4YWI5NmFlZWNiMzZiYjljYzcwYTY3ZWNhNTM0YzQwMzMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.A5uXpEV8vQopiNmhjQQ7cCFFe1AdVCyQYzsOqIu7QAI) ![image](https://private-user-images.githubusercontent.com/45259624/381130416-6c237aad-1692-43c2-985d-d400e4875691.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzAyMjY2MDgsIm5iZiI6MTczMDIyNjMwOCwicGF0aCI6Ii80NTI1OTYyNC8zODExMzA0MTYtNmMyMzdhYWQtMTY5Mi00M2MyLTk4NWQtZDQwMGU0ODc1NjkxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDI5VDE4MjUwOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTAxNDQ2NmQwZmQwZWY2NmMzZDY3YjA2OGU4NmZlYTllMjBjMTAzODE0YjllMDUxNjVkN2Y2NzI2MGQ5MjUxMzEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.lv-XxM0QyZc2qoeJA07voEizWH3zkcZ7inoEP77OvDw) ![image](https://private-user-images.githubusercontent.com/45259624/381132294-bafc12bf-7f28-44a4-a857-286e322164af.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzAyMjY2MDgsIm5iZiI6MTczMDIyNjMwOCwicGF0aCI6Ii80NTI1OTYyNC8zODExMzIyOTQtYmFmYzEyYmYtN2YyOC00NGE0LWE4NTctMjg2ZTMyMjE2NGFmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDI5VDE4MjUwOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTg0MjY4YTRiODA1OTYwMzg0NGVlNTEyZjY0N2Q1M2VhN2EwMWVjZjk2ZTQwODlhNzMzNjU2NzkyNTUzZWU0ODEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.IO7hVgzfKm8IdyZeYsHEL1VRDUu0a8gsosD-EQKvcjU)



> > 昨天中午还可以正常使用
> 
> 一切都正常，不知道你是什么情况，如果你确实不能启动，能否私发节点我测试？[zxlhhy@163.com](mailto:zxlhhy@163.com) 或者把你启动后生成的配置发我看看，可以隐去你的节点信息。。。
> 
> ![image](https://private-user-images.githubusercontent.com/45259624/381130007-41c2eabe-4672-46b5-a0e5-0b099504b46a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzAyMjY2MDgsIm5iZiI6MTczMDIyNjMwOCwicGF0aCI6Ii80NTI1OTYyNC8zODExMzAwMDctNDFjMmVhYmUtNDY3Mi00NmI1LWEwZTUtMGIwOTk1MDRiNDZhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDI5VDE4MjUwOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTA2MmQ0MWE4NWFhNDZmNDhlODhlZWFmYmZhZjYwMjk4YWI5NmFlZWNiMzZiYjljYzcwYTY3ZWNhNTM0YzQwMzMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.A5uXpEV8vQopiNmhjQQ7cCFFe1AdVCyQYzsOqIu7QAI) ![image](https://private-user-images.githubusercontent.com/45259624/381130416-6c237aad-1692-43c2-985d-d400e4875691.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzAyMjY2MDgsIm5iZiI6MTczMDIyNjMwOCwicGF0aCI6Ii80NTI1OTYyNC8zODExMzA0MTYtNmMyMzdhYWQtMTY5Mi00M2MyLTk4NWQtZDQwMGU0ODc1NjkxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDI5VDE4MjUwOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTAxNDQ2NmQwZmQwZWY2NmMzZDY3YjA2OGU4NmZlYTllMjBjMTAzODE0YjllMDUxNjVkN2Y2NzI2MGQ5MjUxMzEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.lv-XxM0QyZc2qoeJA07voEizWH3zkcZ7inoEP77OvDw) ![image](https://private-user-images.githubusercontent.com/45259624/381132294-bafc12bf-7f28-44a4-a857-286e322164af.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzAyMjY2MDgsIm5iZiI6MTczMDIyNjMwOCwicGF0aCI6Ii80NTI1OTYyNC8zODExMzIyOTQtYmFmYzEyYmYtN2YyOC00NGE0LWE4NTctMjg2ZTMyMjE2NGFmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDI5VDE4MjUwOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTg0MjY4YTRiODA1OTYwMzg0NGVlNTEyZjY0N2Q1M2VhN2EwMWVjZjk2ZTQwODlhNzMzNjU2NzkyNTUzZWU0ODEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.IO7hVgzfKm8IdyZeYsHEL1VRDUu0a8gsosD-EQKvcjU)

您好,我也参考上面解决了,方法是,恢复出厂设置,把出厂设置里面新的 /etc/config/shadowsocksr 保留下来,然后再添加节点,其余可以保留旧的,一切正常! 感谢您的卓越贡献.
