### ISSUE TITLE
update.lua还是没有处理好新版本dnsmasq的问题

### ISSUE THREAD

**Issue by qwerttvv** [fw876/helloworld#1585]
上次把因为新dnsmasq配置改变引起的无法启动的问题修了，见
https://github.com/fw876/helloworld/commit/8c362ba2cdb11aa26acbe93789ce76ad76705f85
感谢

后来发现你去web页面手动更新gfw列表会报错
can't create '/dnsmasq-ssrplus.d/gfw_list.conf': No such file or directory

所以就是这个更新还得修修
https://github.com/fw876/helloworld/commit/8c362ba2cdb11aa26acbe93789ce76ad76705f85

@zxlhhyccc 

当前如果你想手动更新列表，那么你更新完了如果列表有变化，你就手动重启一下ssrp，或者去换个节点再保存并应用，这样就可以了

**Comment by zxlhhyccc** [comment]
> 后来发现你去web页面手动更新gfw列表会报错
> can't create '/dnsmasq-ssrplus.d/gfw_list.conf': No such file or directory

经多次测试，不存在你说的问题。



> 这样会改变原list的内容列表的顺序吧？我给改了一下……
> 
> 因为现在有些列表会优化list内容的顺序，使dnsmasq遍历匹配效率更高
> 
> 所以不如大师你一并改了好了，改成下边这样，就可以按原始顺序生成内容了
> 
> 并且以下代码和原始代码比较，增加的开销微乎其微，现在的列表基本都在4000到6000条的模样，可以说0性能开销增加吧

这个修改感觉不错，准备合并到仓库。

**Comment by zxlhhyccc** [comment]
> > 后来发现你去web页面手动更新gfw列表会报错
> > can't create '/dnsmasq-ssrplus.d/gfw_list.conf': No such file or directory
> 
> 经多次并各种方式测试（包括使用smartdns、dnsmasq方式），不存在你说的问题。
> 
> > 这样会改变原list的内容列表的顺序吧？我给改了一下……
> > 因为现在有些列表会优化list内容的顺序，使dnsmasq遍历匹配效率更高
> > 所以不如大师你一并改了好了，改成下边这样，就可以按原始顺序生成内容了
> > 并且以下代码和原始代码比较，增加的开销微乎其微，现在的列表基本都在4000到6000条的模样，可以说0性能开销增加吧
> 
> 这个修改感觉不错，准备合并到仓库。

**Comment by zxlhhyccc** [comment]
> 你这改的还是不对吧，点更新现在根目录多了个文件夹
> 
> ![Image](https://private-user-images.githubusercontent.com/56712217/383710168-f3b49541-3511-44c7-98ff-720d0e8459f1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzA5OTM4NzQsIm5iZiI6MTczMDk5MzU3NCwicGF0aCI6Ii81NjcxMjIxNy8zODM3MTAxNjgtZjNiNDk1NDEtMzUxMS00NGM3LTk4ZmYtNzIwZDBlODQ1OWYxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTA3VDE1MzI1NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTRkYjA3MWFiMTk1ODg3YTEzOWM3OWJhNDZiZmYxYTA4OWY0MzEwNGI5MmQ0MmZlOWJiZWEyNzFmMjQyYmZlNDYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.j38jS2tfZ9gjWwxYR7kwdlzsYGoflXANT2N3QvH94cA)

已修复：
