### ISSUE TITLE
SSR plus 启动不了

### ISSUE THREAD

**Issue by doumeki** [fw876/helloworld#1588]
问题类似这个，https://github.com/fw876/helloworld/issues/1493,但这里说的是openssl太新的原因，我尝试使用5月的commit+3.0.13的openssl是可以的，可见可能不是openssl的问题。
发现是VMESS协议的就不行，SS的没有问题。
日志：
2024-11-14 00:34:44: Main node:Xray 24.10.16 (Xray, Penetrates Everything.) OpenWrt (go1.23.1 linux/amd64) Started!
2024-11-14 00:34:44: ----------start------------
2024-11-14 00:34:37: ssrplus redir tcp error.restart!
最后发现是这个commit（[4ae54d202d6e9e41748ef8d2849b685341cd4f7c](https://github.com/fw876/helloworld/commit/4ae54d202d6e9e41748ef8d2849b685341cd4f7c)）后，vmess就启动不了，向后退一个版本就可以。看日志是添加了fragement,本人小白也不知道有什么，本来也用不上这些高级功能，能否添加一个不用fragement的开关，能让这个配置可以启动。

![image](https://github.com/user-attachments/assets/c9daed6e-443f-4fc4-8a7a-aed98e1dab4f)

**Comment by zxlhhyccc** [comment]
fragement功能是Vless功能，与fragement毫无关系，Xray的vmess的配置文件格式在Xray的新版本下已经改变，我没此类节点，能否私信此类节点我测试和修复？

**Comment by doumeki** [comment]
@zxlhhyccc 可以的，怎么私信给你呢

**Comment by zxlhhyccc** [comment]
@doumeki 请发邮件：zxlhhy@163.com

**Comment by zxlhhyccc** [comment]
@doumeki 使用你发的节点，可正常运行正常连接，请检查你自己的原因。

![image](https://github.com/user-attachments/assets/7f8658e0-2728-4a3c-9d15-4b63a22954b2)
![image](https://github.com/user-attachments/assets/23da6936-0ff8-43a5-acbc-e49940ff4638)
