### ISSUE TITLE
很奇怪，突然不能读gfw_list，说是不存在，后缀也很奇怪

### ISSUE THREAD

**Issue by rongcenter** [fw876/helloworld#1599]
Sat Nov 16 21:07:54 2024 daemon.crit dnsmasq[1]: cannot read /tmp/dnsmasq.d/dnsmasq-ssrplus.d/gfw_list.conffMkaee: No such file or directory
Sat Nov 16 21:07:54 2024 daemon.crit dnsmasq[1]: FAILED to start up
Sat Nov 16 21:07:54 2024 daemon.err miniupnpd[6049]: could not open lease file: /var/upnp.leases
Sat Nov 16 21:07:54 2024 daemon.notice miniupnpd[6049]: HTTP listening on port 5000
Sat Nov 16 21:07:54 2024 daemon.notice miniupnpd[6049]: Listening for NAT-PMP/PCP traffic on port 5351
Sat Nov 16 21:07:55 2024 daemon.err procd: Got unexpected signal 1
Sat Nov 16 21:07:55 2024 daemon.crit dnsmasq[1]: cannot read /tmp/dnsmasq.d/dnsmasq-ssrplus.d/gfw_list.confdOoNBB: No such file or directory

**Comment by zxlhhyccc** [comment]
> 今天刚编译的，更新后就出现日志中not read，后面又点了一次更新，日志中没出现了

请使用我刚提交的优化了的PR：https://github.com/fw876/helloworld/pull/1601

**Comment by rongcenter** [comment]
> > 今天刚编译的，更新后就出现日志中not read，后面又点了一次更新，日志中没出现了
> 
> 请使用我刚提交的优化了的PR（原修改适配官方dnsmasq最新路径并兼容旧版dnsmasq路径的代码是我提交的，但有点问题）：#1601 [b9db3ef](https://github.com/fw876/helloworld/commit/b9db3ef527e86d57eef4fa8812e983a540e2c73e)

谢谢大佬

**Comment by zxlhhyccc** [comment]
> 谢谢大佬

如问题解决，请关闭，谢谢！

**Comment by KumaTea** [comment]
后续版本也存在这个问题

参考 #1573 ，关闭 `Apple 域名解析优化` 之后就解决了
