### ISSUE TITLE
不勾选自动更新，保存页面会报错

### ISSUE THREAD

**Issue by venpong** [fw876/helloworld#1627]
我的节点是自建的，通过vless://链接形式导入的，没有订阅链接，我不想开启定时更新订阅功能，当我取消勾选页面"自动更新"按钮，并点击"保存"的时候，页面会提示错误，我记得这个以前是可以取消勾选保存的，这个是否是个问题？

![微信图片_20241208171214](https://github.com/user-attachments/assets/8f08683a-2db1-4364-a226-3f784c305596)

**Comment by venpong** [comment]
gpt告诉我只需要把这一行改为true就可以了，我编译试一下看看。
![45131733711205_ pic](https://github.com/user-attachments/assets/13793deb-1e58-43c9-8ee5-4f92ecb92376)

**Comment by zxlhhyccc** [comment]
> gpt告诉我只需要把这一行改为true就可以了，我编译试一下看看。

不好意思，忘记删除这一行。

**Comment by venpong** [comment]
> > gpt告诉我只需要把这一行改为true就可以了，我编译试一下看看。
> 
> 不好意思，忘记删除这一行。

我按照上面的改了，编译后但是还是一样的报错，还是等大佬出手吧。

**Comment by venpong** [comment]
ok,我删掉这一行再编译试试

**Comment by zxlhhyccc** [comment]
> ok,我删掉这一行再编译试试

删除后是否可行了？

**Comment by venpong** [comment]
> > ok,我删掉这一行再编译试试
> 
> 删除后是否可行了？

不行，我的设备是acrh17，我把这一行改成true和删掉这一行，然后保存配置在web页面升级刷入bin文件，没有效果，不知道是不是因为我保存配置导致的，但是不保存配置刷入后又要配置好一会，会影响家人上网。

**Comment by zxlhhyccc** [comment]
@venpong 保存配置不受影响，不知道你具体什么情况。

**Comment by venpong** [comment]
> @venpong 已修复，见PR： #1630

谢谢大佬
