### ISSUE TITLE
[建议] 重构PDNSD缓存

### ISSUE THREAD

**Issue by Loyea** [fw876/helloworld#163]
我看了下PDNSD缓存做法是直接将TTL修改为3600也就是一小时，在切换节点的时候会清空所有的缓存dns结果。

但是这么做缺点是客户端中的dns缓存也长达一小时，ssr+已经切换了节点客户端也不会去请求新的dns结果，仍然会连接之前的ip地址。

我建议改成ssr+这里缓存一小时，但是发给客户端的ttl改成60左右，反正就是比较短的时间。这样客户端dns过期了也可以继续从ssr+缓存里面重新取，基本不会花费很长时间。而ssr+切换节点之后清空所有缓存，客户端也可以较快重新请求dns。

**Comment by SharerMax** [comment]
你应该看dnsmasq的缓存是怎么实现的
