### ISSUE TITLE
shadowsocksr.lua 114行代码错误

### ISSUE THREAD

**Issue by ccjcu** [fw876/helloworld#1650]
luci-app-ssr-plus/luasrc/controller/shadowsocksr.lua 114行代码错误

			原始代码 retstring .. "<font><b style='color:green'>[" .. server_name .. "] OK.</b></font><br />"
			retstring = retstring .. "<font><b style='color:green'>[" .. server_name .. "] OK.</b></font><br />"

**Comment by wekingchen** [comment]
谢谢分享，刚好遇到这个问题了

**Comment by zxlhhyccc** [comment]
https://github.com/fw876/helloworld/pull/1651

**Comment by Biercenter** [comment]
一样呃
`Runtime error
Unhandled exception during request dispatching
/usr/lib/lua/luci/ucodebridge.lua:23: error loading module 'luci.controller.shadowsocksr' from file '/usr/lib/lua/luci/controller/shadowsocksr.lua':
/usr/lib/lua/luci/controller/shadowsocksr.lua:114: '=' expected near '..'

In error(), file [C]
called from function [anonymous function] (/usr/lib/lua/luci/ucodebridge.lua:23)
called from function ((tail call))
In [anonymous function](), file /usr/share/ucode/luci/runtime.uc, line 148, byte 45:
  called from function build_pagetree (/usr/share/ucode/luci/dispatcher.uc:382:73)
  called from function menu_json (/usr/share/ucode/luci/dispatcher.uc:439:26)
  called from function [anonymous function] (/usr/share/ucode/luci/dispatcher.uc:898:24)
  called from anonymous function (/www/cgi-bin/luci:39:13)

 `        return lcall.call(modname, method, ...args);`
  Near here ----------------------------------------^`

**Comment by hong0980** [comment]
retstring .. "<font><b style='color:green'>[" .. server_name .. "] OK.</b></font><br />"
改成
retstring = "<font><b style='color:green'>[" .. server_name .. "] OK.</b></font><br />"

**Comment by Biercenter** [comment]
> retstring .. "[" .. server_name .. "] OK." 改成 retstring = "[" .. server_name .. "] OK."

改后可以了。最新提交的修复也通过了好像。
