### ISSUE TITLE
可以加入 定时 自动跑Cloudflare 好的IP节点的功能吗 这样可以套上 cnd  来解决线路不好的问题

### ISSUE THREAD

**Issue by cnhap** [fw876/helloworld#169]
原项目地址在下面  我现在是人工 跑出IP来 在软路由里改IP 弄的很费劲 
https://github.com/badafans/better-cloudflare-ip

**Comment by hcym** [comment]
一二个星期跑一次足够吧，基本是备用，高高低低的不太稳定

**Comment by cnhap** [comment]
> 一二个星期跑一次足够吧，基本是备用，高高低低的不太稳定

每个小时都在跑 都在换   我在内陆 本身电信线路就不好.

**Comment by zxlhhyccc** [comment]
> > 一二个星期跑一次足够吧，基本是备用，高高低低的不太稳定
> 
> 每个小时都在跑 都在换 我在内陆 本身电信线路就不好.连传说的CN2 GIA-E 线路都只能跑到 5.46Mbps

我是多拨，200m带宽单线多拨，比如2拨，该如何跑？
