### ISSUE TITLE
开启SSR+的服务端后的混淆参数后无法连接

### ISSUE THREAD

**Issue by xxp2277** [fw876/helloworld#174]
昨天(2020-9-3)编译的版本(菲讯n1)，发现开启服务端(chacha20/origin/http_simple)用于免流时，登录网厅查询详单发现约4/5流量未被标记为电信爱看流量。故尝试在服务器端填入与手机端相同的混淆参数为ltevod.tv189.cn\r\n
，保存&应用后无法正常连接。此时系统日志提示：

Fri Sep  4 12:27:13 2020 kern.err /usr/bin/ssr-server[11169]: http_simple: not match host, host: ltevod.tv189.cn\r\n
Fri Sep  4 12:27:13 2020 kern.err /usr/bin/ssr-server[11169]: server_decode
Fri Sep  4 12:27:13 2020 kern.err /usr/bin/ssr-server[11169]: http_simple: not match host, host: ltevod.tv189.cn\r\n
Fri Sep  4 12:27:13 2020 kern.err /usr/bin/ssr-server[11169]: server_decode
Fri Sep  4 12:27:13 2020 kern.err /usr/bin/ssr-server[11169]: http_simple: not match host, host: ltevod.tv189.cn\r\n
Fri Sep  4 12:27:13 2020 kern.err /usr/bin/ssr-server[11169]: server_decode
Fri Sep  4 12:27:13 2020 kern.err /usr/bin/ssr-server[11169]: http_simple: not match host, host: ltevod.tv189.cn\r\n
Fri Sep  4 12:27:13 2020 kern.err /usr/bin/ssr-server[11169]: server_decode
Fri Sep  4 12:27:14 2020 kern.err /usr/bin/ssr-server[11169]: http_simple: not match host, host: ltevod.tv189.cn\r\n
Fri Sep  4 12:27:14 2020 kern.err /usr/bin/ssr-server[11169]: server_decode
Fri Sep  4 12:27:14 2020 kern.err /usr/bin/ssr-server[11169]: http_simple: not match host, host: ltevod.tv189.cn\r\n
Fri Sep  4 12:27:14 2020 kern.err /usr/bin/ssr-server[11169]: server_decode
Fri Sep  4 12:27:15 2020 kern.err /usr/bin/ssr-server[11169]: http_simple: not match host, host: ltevod.tv189.cn\r\n
Fri Sep  4 12:27:15 2020 kern.err /usr/bin/ssr-server[11169]: server_decode
Fri Sep  4 12:27:15 2020 kern.err /usr/bin/ssr-server[11169]: http_simple: not match host, host: ltevod.tv189.cn\r\n
Fri Sep  4 12:27:15 2020 kern.err /usr/bin/ssr-server[11169]: server_decode

最近几个月使用的python版本的服务器端，正常使用。故不知道ssr+版本是从什么时候更新导致在填入混淆参数后无法连接的问题。

**Comment by Mattraks** [comment]
host里面加\r\n是什么操作?

**Comment by xxp2277** [comment]
> 
> 
> host里面加\r\n是什么操作?

我也不清楚，之前别人分享的免流参数，据说用在手机SSR客户端可以减少漏流量。
经测试，另一个手机没有我这个手机所谓漏4/5的流量，只不过那个SSR服务器端的参数只能为空（去掉\r\n甚至更改为www.baidu.com手机端均无法成功连接）
