### ISSUE TITLE
有文件下载不下来,编译出错啊,

### ISSUE THREAD

**Issue by lxwq** [fw876/helloworld#177]
z/lean/staging_dir/hostpkg/bin/python3" ; /home/zz/lean/staging_dir/hostpkg/bin/ninja -C "out/Release" naive ; )
+ cut -d= -f2 src/chrome/VERSION
+ cut -d. -f1-4
+ tr \n .
+ have_version=85.0.4183.83
+ cat CHROMIUM_VERSION
+ want_version=85.0.4183.83
+ [ 85.0.4183.83 = 85.0.4183.83 ]
+ exit 0
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:--  0:00:19 --:--:--     0
curl: (28) Connection timed out after 20000 milliseconds
Warning: Transient problem: timeout Will retry in 1 seconds. 5 retries left.
  0     0    0     0    0     0      0      0 --:--:--  0:00:20 --:--:--     0
curl: (28) Connection timed out after 20000 milliseconds
Warning: Transient problem: timeout Will retry in 2 seconds. 4 retries left.
  0     0    0     0    0     0      0      0 --:--:--  0:00:19 --:--:--     0
curl: (28) Connection timed out after 20000 milliseconds
Warning: Transient problem: timeout Will retry in 4 seconds. 3 retries left.
  0     0    0     0    0     0      0      0 --:--:--  0:00:20 --:--:--     0
curl: (28) Connection timed out after 20000 milliseconds
Warning: Transient problem: timeout Will retry in 8 seconds. 2 retries left.
  0     0    0     0    0     0      0      0 --:--:--  0:00:20 --:--:--     0
curl: (28) Connection timed out after 20000 milliseconds
Warning: Transient problem: timeout Will retry in 16 seconds. 1 retries left.
  0     0    0     0    0     0      0      0 --:--:--  0:00:20 --:--:--     0
curl: (28) Connection timed out after 20000 milliseconds
tar (child): /home/zz/lean/dl/clang-n356902-4e813bbd-1.tgz: Cannot open: No such file or directory
tar (child): Error is not recoverable: exiting now
tar: Child returned status 2
tar: Error is not recoverable: exiting now
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:--  0:00:20 --:--:--     0
curl: (28) Connection timed out after 20000 milliseconds
Warning: Transient problem: timeout Will retry in 1 seconds. 5 retries left.
  0     0    0     0    0     0      0      0 --:--:--  0:00:20 --:--:--     0
curl: (28) Connection timed out after 20000 milliseconds
Warning: Transient problem: timeout Will retry in 2 seconds. 4 retries left.
  0     0    0     0    0     0      0      0 --:--:--  0:00:20 --:--:--     0
curl: (28) Connection timed out after 20000 milliseconds
Warning: Transient problem: timeout Will retry in 4 seconds. 3 retries left.
  0     0    0     0    0     0      0      0 --:--:--  0:00:20 --:--:--     0
curl: (28) Connection timed out after 20000 milliseconds
Warning: Transient problem: timeout Will retry in 8 seconds. 2 retries left.
  0     0    0     0    0     0      0      0 --:--:--  0:00:20 --:--:--     0
curl: (28) Connection timed out after 20000 milliseconds
Warning: Transient problem: timeout Will retry in 16 seconds. 1 retries left.
  0     0    0     0    0     0      0      0 --:--:--  0:00:20 --:--:--     0
curl: (28) Connection timed out after 20000 milliseconds
unzip:  cannot find or open /home/zz/lean/dl/gn-git_revision:7d7e8deea36d126397bda2cf924682504271f0e1.zip, /home/zz/lean/dl/gn-git_revision:7d7e8deea36d126397bda2cf924682504271f0e1.zip.zip or /home/zz/lean/dl/gn-git_revision:7d7e8deea36d126397bda2cf924682504271f0e1.zip.ZIP.
bash: ./gn/out/gn: No such file or directory
没有出国上网的条件,怎么办?

**Comment by lxwq** [comment]
已经手动下载了文件,放入DL文件夹下还是不行,这段代码如何修改?
# Download GN tool
[ ! -f "gn/out/gn" ] && {
	mkdir -p "gn/out"
	GN_VERSION="$(grep "'gn_version':" "buildtools/DEPS" | cut -d"'" -f4)"
	[ ! -f "${dl_dir}/gn-${GN_VERSION}.zip" ] && curl -f --connect-timeout 20 --retry 5 --location --insecure "https://chrome-infra-packages.appspot.com/dl/gn/gn/linux-amd64/+/${GN_VERSION}" -o "${dl_dir}/gn-${GN_VERSION}.zip"
	unzip -o "${dl_dir}/gn-${GN_VERSION}.zip" -d "gn/out"
}

**Comment by lxwq** [comment]
真是悲催,下了最新版的,手动解压,编译出错;在代码里翻出两个月前的版本git_revision:7d7e8deea36d126397bda2cf924682504271f0e1下载,手动解压,正常编译中,

**Comment by hzjnet** [comment]
下载后还是编译2不成功，提示如下：
bash: ./gn/out/gn: No such file or directory
bash: /openwrt/openwrt-sou-down-17.01.6/staging_dir/target-arm_cortex-a15+neon-vfpv4_musl-1.1.20_eabi/host/bin/ninja: No such file or directory
make[3]: *** [/openwrt/openwrt-sou-down-17.01.6/build_dir/target-arm_cortex-a15+neon-vfpv4_musl-1.1.20_eabi/naiveproxy-85.0.4183.83-1/.built] Error 127
make[3]: Leaving directory `/openwrt/app/17016d0912/lienol/package/naiveproxy'

**Comment by lxwq** [comment]
> 下载后还是编译2不成功，提示如下：
> bash: ./gn/out/gn: No such file or directory
> bash: /openwrt/openwrt-sou-down-17.01.6/staging_dir/target-arm_cortex-a15+neon-vfpv4_musl-1.1.20_eabi/host/bin/ninja: No such file or directory
> make[3]: *** [/openwrt/openwrt-sou-down-17.01.6/build_dir/target-arm_cortex-a15+neon-vfpv4_musl-1.1.20_eabi/naiveproxy-85.0.4183.83-1/.built] Error 127
> make[3]: Leaving directory `/openwrt/app/17016d0912/lienol/package/naiveproxy'

今天升级后再编译,过不了啦,可能是GN版本的问题,多换几个版本试试,

**Comment by lxwq** [comment]
> 下载后还是编译2不成功，提示如下：
> bash: ./gn/out/gn: No such file or directory
> bash: /openwrt/openwrt-sou-down-17.01.6/staging_dir/target-arm_cortex-a15+neon-vfpv4_musl-1.1.20_eabi/host/bin/ninja: No such file or directory
> make[3]: *** [/openwrt/openwrt-sou-down-17.01.6/build_dir/target-arm_cortex-a15+neon-vfpv4_musl-1.1.20_eabi/naiveproxy-85.0.4183.83-1/.built] Error 127
> make[3]: Leaving directory `/openwrt/app/17016d0912/lienol/package/naiveproxy'

我是用别的电脑出国上网,下载GN,解压到/build_dir/target-x86_64_musl/naiveproxy-85.0.4183.83-3/src/gn/out
测试是可以编译通过的,
今天出错是因为naiveproxy升级到85.0.4183.83-3,AFDO我没升,所以编译出错,升级AFDO后正常,(也是别的电脑出国上网,手动下载升级,没办法,这台LINUX出不了国,)

**Comment by hzjnet** [comment]
AFDO这是什么啊？  我的报错前面是一堆正常的gn/out/aaa行，明显下载的gn正常能解压：
( cd /openwrt/openwrt-sou-down-17.01.6/build_dir/target-arm_cortex-a15+neon-vfpv4_musl-1.1.20_eabi/naiveproxy-85.0.4183.83-1 ; ./tools/import-upstream.sh ; . ./init_env.sh "arm" "ipq806x" "cortex-a15" "neon-vfpv4" "/openwrt/openwrt-sou-down-17.01.6/staging_dir/toolchain-arm_cortex-a15+neon-vfpv4_gcc-7.5.0_musl-1.1.20_eabi" "/openwrt/openwrt-sou-down-17.01.6/dl"; export naive_flags="${naive_flags} ${naive_ccache_flags}" ; export OP_STAGING_DIR="/openwrt/openwrt-sou-down-17.01.6/staging_dir/target-arm_cortex-a15+neon-vfpv4_musl-1.1.20_eabi" ; mkdir -p out ; ./gn/out/gn gen "out/Release" --args="${naive_flags}" --script-executable="/openwrt/openwrt-sou-down-17.01.6/staging_dir/target-arm_cortex-a15+neon-vfpv4_musl-1.1.20_eabi/host/bin/python3" ; /openwrt/openwrt-sou-down-17.01.6/staging_dir/target-arm_cortex-a15+neon-vfpv4_musl-1.1.20_eabi/host/bin/ninja -C "out/Release" naive ; )
Archive:  /openwrt/openwrt-sou-down-17.01.6/dl/gn-git_revision:7d7e8deea36d126397bda2cf924682504271f0e1.zip.ZIP
 extracting: gn/out/aaa/.clang-format
  inflating: gn/out/aaa/.editorconfig
  inflating: gn/out/aaa/.gitignore
  inflating: gn/out/aaa/.style.yapf
  inflating: gn/out/aaa/AUTHORS
  inflating: gn/out/aaa/LICENSE
  inflating: gn/out/aaa/OWNERS
  inflating: gn/out/aaa/README.md
  inflating: gn/out/aaa/build/build_aix.ninja.template
  inflating: gn/out/aaa/build/build_haiku.ninja.template
  inflating: gn/out/aaa/build/build_linux.ninja.template
  inflating: gn/out/aaa/build/build_mac.ninja.template
  inflating: gn/out/aaa/build/build_openbsd.ninja.template
  inflating: gn/out/aaa/build/build_win.ninja.template
  inflating: gn/out/aaa/build/full_test.py
  inflating: gn/out/aaa/build/gen.py
  inflating: gn/out/aaa/docs/cross_compiles.md
  inflating: gn/out/aaa/docs/faq.md
  inflating: gn/out/aaa/docs/language.md
  inflating: gn/out/aaa/docs/quick_start.md
  inflating: gn/out/aaa/docs/reference.md
  inflating: gn/out/aaa/docs/standalone.md
  inflating: gn/out/aaa/docs/style_guide.md
 extracting: gn/out/aaa/examples/ios/.gitignore
  inflating: gn/out/aaa/examples/ios/.gn
  inflating: gn/out/aaa/examples/ios/BUILD.gn

**Comment by lxwq** [comment]
> naiveproxy已经升级到85.0.4183.83-3
你的怎么还是显示naiveproxy-85.0.4183.83-1呢?
是不是没有PULL最新版本啊
在./feeds/helloworld/naiveproxy/src/init_env.sh中会去gogoleapis下载AFDO和Clang，以前GN的指定的版本,
# AFDO profile
[ ! -f "chrome/android/profiles/afdo.prof" ] && {
	AFDO_NAME="$(cat "chrome/android/profiles/newest.txt")"
	[ ! -f "${dl_dir}/${AFDO_NAME}" ] && curl -f --connect-timeout 20 --retry 5 --location --insecure "https://storage.googleapis.com/chromeos-prebuilt/afdo-job/llvm/${AFDO_NAME}" -o "${dl_dir}/${AFDO_NAME}"
	bzip2 -cd > "chrome/android/profiles/afdo.prof" < "${dl_dir}/${AFDO_NAME}"
}

# Download Clang
[ ! -d "third_party/llvm-build/Release+Asserts/bin" ] && {
	mkdir -p "third_party/llvm-build/Release+Asserts"
	CLANG_REVISION="$(python3 "tools/clang/scripts/update.py" --print-revision)"
	[ ! -f "${dl_dir}/clang-${CLANG_REVISION}.tgz" ] && curl -f --connect-timeout 20 --retry 5 --location --insecure "https://commondatastorage.googleapis.com/chromium-browser-clang/Linux_x64/clang-${CLANG_REVISION}.tgz" -o "${dl_dir}/clang-${CLANG_REVISION}.tgz"
	tar -xzf "${dl_dir}/clang-${CLANG_REVISION}.tgz" -C "third_party/llvm-build/Release+Asserts"
}

# Download GN tool
[ ! -f "gn/out/gn" ] && {
	mkdir -p "gn/out"
	GN_VERSION="$(grep "'gn_version':" "buildtools/DEPS" | cut -d"'" -f4)"
	[ ! -f "${dl_dir}/gn-${GN_VERSION}.zip" ] && curl -f --connect-timeout 20 --retry 5 --location --insecure "https://chrome-infra-packages.appspot.com/dl/gn/gn/linux-amd64/+/${GN_VERSION}" -o "${dl_dir}/gn-${GN_VERSION}.zip"
	unzip -o "${dl_dir}/gn-${GN_VERSION}.zip" -d "gn/out"
