### ISSUE TITLE
编译失败，缺少依赖

### ISSUE THREAD

**Issue by Atroc-0625** [fw876/helloworld#179]
WARNING: Makefile 'package/feeds/helloworld/naiveproxy/Makefile' has a dependency on 'libnss', which does not exist
环境：lean/openwrt

**Comment by klever1988** [comment]
同样

**Comment by swxk521** [comment]
云编译没问题

**Comment by smallprogram** [comment]
本地编译没问题

**Comment by gsblay** [comment]
本地编译，同样问题，好像使新加的 naiveproxy 的依赖，不选中可以顺利编译成功.

**Comment by klever1988** [comment]
出问题的是稳定版分支
https://github.com/coolsnowwolf/openwrt
https://github.com/coolsnowwolf/packages/tree/openwrt-19.07/libs 没有nss

**Comment by jarod520** [comment]
确实，稳定版分支编译出错，同样的报错。

**Comment by kyarazhan** [comment]
稳定版分支编译出错，有大佬解决了没？

**Comment by Zeezorn** [comment]
sudo apt-get update && sudo apt-get upgrade
sudo apt-get install curl
make package/feeds/helloworld/naiveproxy/clean
make V=s

**Comment by Zeezorn** [comment]
> > sudo apt-get update && sudo apt-get upgrade
> > sudo apt-get install curl
> > make package/feeds/helloworld/naiveproxy/clean
> > make package/feeds/helloworld/luci-app-ssr-plus/compile V=s
> 
> 误人子弟

我就是这么解决的，因为naiveproxy编译过程只能调用curl，调用不了wget。
这位兄台如此高调，难不成有更好的解决方法？何不共享出来给大家学习一下？

**Comment by schen39** [comment]
> > > sudo apt-get更新&& sudo apt-get升級
> > > sudo apt-get install curl 
> > > make package / feeds / helloworld / naiveproxy / clean 
> > > make package / feeds / helloworld / luci-app-ssr-plus / compile V = s
> > 
> > 
> > 誤人子弟
> 
> 我就是這麼解決的，因為naiveproxy編譯過程只能調用curl，調用不了wget。
> 這位兄台如此高調，難不成有更好的解決方法？何不共享出來給大家學習一下？

有问题大伙一起讨论研究麽，不过确实此方法亲测无效

**Comment by kyarazhan** [comment]
> sudo apt-get update && sudo apt-get upgrade
> sudo apt-get install curl
> make package/feeds/helloworld/naiveproxy/clean
> make package/feeds/helloworld/luci-app-ssr-plus/compile V=s

大佬，你这个方法是不是单独编译 ssr-plus这个包的啊？小白求教！！

**Comment by bin20088** [comment]
> > > sudo apt-get update && sudo apt-get upgrade
> > > sudo apt-get install curl
> > > make package/feeds/helloworld/naiveproxy/clean
> > > make package/feeds/helloworld/luci-app-ssr-plus/compile V=s
> > 
> > 
> > 误人子弟
> 
> 我就是这么解决的，因为naiveproxy编译过程只能调用curl，调用不了wget。
> 这位兄台如此高调，难不成有更好的解决方法？何不共享出来给大家学习一下？

前面已经说的很明白了，不光是curl的问题，还缺少依赖

**Comment by bin20088** [comment]
> > > > sudo apt-get更新&& sudo apt-get升級
> > > > sudo apt-get install curl
> > > > make package / feeds / helloworld / naiveproxy / clean
> > > > make package / feeds / helloworld / luci-app-ssr-plus / compile V = s
> > > 
> > > 
> > > 誤人子弟
> > 
> > 
> > 我就是這麼解決的，因為naiveproxy編譯過程只能調用curl，調用不了wget。
> > 這位兄台如此高調，難不成有更好的解決方法？何不共享出來給大家學習一下？
> 
> 有问题大伙一起讨论研究麽，不过确实此方法亲测无效

都不用测，看一眼不就知道了行不行

**Comment by Zeezorn** [comment]
> > sudo apt-get update && sudo apt-get upgrade
> > sudo apt-get install curl
> > make package/feeds/helloworld/naiveproxy/clean
> > make package/feeds/helloworld/luci-app-ssr-plus/compile V=s
> 
> 大佬，你这个方法是不是单独编译 ssr-plus这个包的啊？小白求教！！

是单独编译的，不过前提是以前完整成功编译过固件，如果之前没有完整编译过，中间依然会报错。

**Comment by bin20088** [comment]
> > > sudo apt-get update && sudo apt-get upgrade
> > > sudo apt-get install curl
> > > make package/feeds/helloworld/naiveproxy/clean
> > > make package/feeds/helloworld/luci-app-ssr-plus/compile V=s
> > 
> > 
> > 大佬，你这个方法是不是单独编译 ssr-plus这个包的啊？小白求教！！
> 
> 是单独编译的，不过前提是以前完整成功编译过固件，如果之前没有完整编译过，中间依然会报错。

大哥，你先消停一会吧，既然是缺少依赖，跟是不是单独编译还是之前有没有成功编译过要什么关系呢？。别瞎说八道。前面也说了，只要不选naiveproxy就没问题。

**Comment by Zeezorn** [comment]
> > > > sudo apt-get update && sudo apt-get upgrade
> > > > sudo apt-get install curl
> > > > make package/feeds/helloworld/naiveproxy/clean
> > > > make package/feeds/helloworld/luci-app-ssr-plus/compile V=s
> > > 
> > > 
> > > 大佬，你这个方法是不是单独编译 ssr-plus这个包的啊？小白求教！！
> > 
> > 
> > 是单独编译的，不过前提是以前完整成功编译过固件，如果之前没有完整编译过，中间依然会报错。
> 
> 大哥，你先消停一会吧，既然是缺少依赖，跟是不是单独编译还是之前有没有成功编译过有什么关系呢？。别瞎说八道。前面也说了，只要不选naiveproxy就没问题。

如果不编译naiveproxy这个包，那还编译这个版本干嘛，编译出来也装不上，此版本依赖naiveproxy

**Comment by bin20088** [comment]
> > > > > sudo apt-get update && sudo apt-get upgrade
> > > > > sudo apt-get install curl
> > > > > make package/feeds/helloworld/naiveproxy/clean
> > > > > make package/feeds/helloworld/luci-app-ssr-plus/compile V=s
> > > > 
> > > > 
> > > > 大佬，你这个方法是不是单独编译 ssr-plus这个包的啊？小白求教！！
> > > 
> > > 
> > > 是单独编译的，不过前提是以前完整成功编译过固件，如果之前没有完整编译过，中间依然会报错。
> > 
> > 
> > 大哥，你先消停一会吧，既然是缺少依赖，跟是不是单独编译还是之前有没有成功编译过有什么关系呢？。别瞎说八道。前面也说了，只要不选naiveproxy就没问题。
> 
> 如果不编译naiveproxy这个包，那还编译这个版本干嘛，编译出来也装不上，此版本依赖naiveproxy

说了让你消停会，就是不听，非要出来现眼。你说的这两件事连基本常识都没有，这也没关系，你先自己测试一下再来说话OK?

**Comment by Zeezorn** [comment]
> > > > > > sudo apt-get update && sudo apt-get upgrade
> > > > > > sudo apt-get install curl
> > > > > > make package/feeds/helloworld/naiveproxy/clean
> > > > > > make package/feeds/helloworld/luci-app-ssr-plus/compile V=s
> > > > > 
> > > > > 
> > > > > 大佬，你这个方法是不是单独编译 ssr-plus这个包的啊？小白求教！！
> > > > 
> > > > 
> > > > 是单独编译的，不过前提是以前完整成功编译过固件，如果之前没有完整编译过，中间依然会报错。
> > > 
> > > 
> > > 大哥，你先消停一会吧，既然是缺少依赖，跟是不是单独编译还是之前有没有成功编译过有什么关系呢？。别瞎说八道。前面也说了，只要不选naiveproxy就没问题。
> > 
> > 
> > 如果不编译naiveproxy这个包，那还编译这个版本干嘛，编译出来也装不上，此版本依赖naiveproxy
> 
> 说了让你消停会，就是不听，非要出来现眼。你说的这两件事连基本常识都没有，这也没关系，你先自己测试一下再来说话OK?

好，我消停会，和我怼了那么久，我是编译成功了，你倒是给个解决方案啊，别让大伙失望哦，看好你哟~

**Comment by bin20088** [comment]
幼稚

**Comment by bin20088** [comment]
> > > > > > > sudo apt-get update && sudo apt-get upgrade
> > > > > > > sudo apt-get install curl
> > > > > > > make package/feeds/helloworld/naiveproxy/clean
> > > > > > > make package/feeds/helloworld/luci-app-ssr-plus/compile V=s
> > > > > > 
> > > > > > 
> > > > > > 大佬，你这个方法是不是单独编译 ssr-plus这个包的啊？小白求教！！
> > > > > 
> > > > > 
> > > > > 是单独编译的，不过前提是以前完整成功编译过固件，如果之前没有完整编译过，中间依然会报错。
> > > > 
> > > > 
> > > > 大哥，你先消停一会吧，既然是缺少依赖，跟是不是单独编译还是之前有没有成功编译过有什么关系呢？。别瞎说八道。前面也说了，只要不选naiveproxy就没问题。
> > > 
> > > 
> > > 如果不编译naiveproxy这个包，那还编译这个版本干嘛，编译出来也装不上，此版本依赖naiveproxy
> > 
> > 
> > 说了让你消停会，就是不听，非要出来现眼。你说的这两件事连基本常识都没有，这也没关系，你先自己测试一下再来说话OK?
> 
> 好，我消停会，和我怼了那么久，我是编译成功了，你倒是给个解决方案啊，别让大伙失望哦，看好你哟~

幼稚

**Comment by klever1988** [comment]
svn co https://github.com/project-openwrt/packages/trunk/libs/nss
mv nss lede/package/

**Comment by bin20088** [comment]
> svn co https://github.com/project-openwrt/packages/trunk/libs/nss
> mv nss lede/package/

大哥，什么lede？lede那边没问题的，是openwrt这个仓库有问题。svn co https://github.com/project-openwrt/packages/trunk/libs/nss package/nss       svn co https://github.com/project-openwrt/packages/trunk/libs/nspr package/nspr

**Comment by jarod520** [comment]
> > svn co https://github.com/project-openwrt/packages/trunk/libs/nss
> > mv nss lede/package/
> 
> 大哥，什么lede？lede那边没问题的，是openwrt这个仓库有问题。
> svn co https://github.com/project-openwrt/packages/trunk/libs/nss package/nss
> svn co https://github.com/project-openwrt/packages/trunk/libs/nspr package/nspr

不错问题解决了。还有个问题是passwall也有缺少依赖能告知怎么解决吗？
WARNING: Makefile 'package/luci-app-passwall/Makefile' has a dependency on 'https-dns-proxy', which does not exist

**Comment by bin20088** [comment]
> > > svn co https://github.com/project-openwrt/packages/trunk/libs/nss
> > > mv nss lede/package/
> > 
> > 
> > 大哥，什么lede？lede那边没问题的，是openwrt这个仓库有问题。
> > svn co https://github.com/project-openwrt/packages/trunk/libs/nss package/nss
> > svn co https://github.com/project-openwrt/packages/trunk/libs/nspr package/nspr
> 
> 不错问题解决了。还有个问题是passwall也有缺少依赖能告知怎么解决吗？
> WARNING: Makefile 'package/luci-app-passwall/Makefile' has a dependency on 'https-dns-proxy', which does not exist

这个问题原因也很清楚，是因为openwrt这个仓库自带的的https-dns-proxy版本太旧，而passwall需要的是新版的https-dns-proxy，svn co https://github.com/openwrt/packages/trunk/net/https-dns-proxy package/https-dns-proxy   但是我记得有另外一个插件又依赖这个旧的版本，彻底在源码里改成新版的后那另外一个又会提示缺这个。思路有了 ，剩下的自己想办法解决吧

**Comment by kyarazhan** [comment]
> > svn co https://github.com/project-openwrt/packages/trunk/libs/nss
> > mv nss lede/package/
> 
> 大哥，什么lede？lede那边没问题的，是openwrt这个仓库有问题。
> svn co https://github.com/project-openwrt/packages/trunk/libs/nss package/nss
> svn co https://github.com/project-openwrt/packages/trunk/libs/nspr package/nspr

有效

**Comment by minfengyk** [comment]
我是本地编译的稳定版分支，下载nss、nspr放在package/lean目录，可以成功编译。

**Comment by pangfeng161** [comment]
> 本地编译，同样问题，好像使新加的 naiveproxy 的依赖，不选中可以顺利编译成功.

怎样不选中,能介绍下具体步骤吗?

**Comment by pangfeng161** [comment]
> 我是本地编译的稳定版分支，下载nss、nspr放在package/lean目录，可以成功编译。

能提供下载地址吗,这几天弄得烦

**Comment by bin20088** [comment]
> > 我是本地编译的稳定版分支，下载nss、nspr放在package/lean目录，可以成功编译。
> 
> 能提供下载地址吗,这几天弄得烦

你也是真够懒，往上看看不会吗？github里搜不会吗？

**Comment by minfengyk** [comment]
> > 我是本地编译的稳定版分支，下载nss、nspr放在package/lean目录，可以成功编译。
> 
> 能提供下载地址吗,这几天弄得烦

Lean大源码仓库：https://github.com/coolsnowwolf/packages  
Lienol源码仓库：https://github.com/Lienol/openwrt-packages
在这里下，两个都可以。有时Lienol源码更新快一点。

**Comment by klever1988** [comment]
L大已经合并nss和nspr到稳定分支了，issue可以关闭

**Comment by feristar** [comment]
> > > sudo apt-get update && sudo apt-get upgrade
> > > sudo apt-get install curl
> > > make package/feeds/helloworld/naiveproxy/clean
> > > make package/feeds/helloworld/luci-app-ssr-plus/compile V=s
> > 
> > 
> > 误人子弟
> 
> 我就是这么解决的，因为naiveproxy编译过程只能调用curl，调用不了wget。
> 这位兄台如此高调，难不成有更好的解决方法？何不共享出来给大家学习一下？

你这方法确实好用，搞定了，多谢分享

**Comment by XiaoBaiLearning** [comment]
> 本地编译没问题

本地编译大大的问题存在
