### ISSUE TITLE
K2P 128M内存adbyby启动后再启v2， tcp代理进程启动就被杀

### ISSUE THREAD

**Issue by niphor** [fw876/helloworld#183]
上周给K2P编译了新固件，发现adbyby开启后，ssr+里选择v2的代理，启动后 TCP代理进程 v2-ssr-retcp 会被立马杀死，只留个UDP的

系统只有adbyby、ssr+(纯酸酸、V2)、upnp、kms没有其他多余

ssr+选择的是单进程、gfw、所有端口

后观察
1.关闭adbyby后可以启动
2.不启用UDP代理可以启动TCP代理和adbyby
3.如果先启动ssr+在启动adbyby则两个都可以启动，但是如果操作量一大，v2 tcp的立马就被kill
4.如果代理选酸酸则都可以正常运行

日志没有输出具体原因，手动修改init.d的脚本，查看进程输出，也只是打了2行信息之后直接就没了，应该是被直接kill掉了...

考虑是不是128MB内存太小了，V2跑不动了?
现在我是手动改的启动脚本 v2 tcp+udp 一个进程的方式，才勉强2个应用都启动着

P.S. 还有个疑问就是 为啥要杀就只杀 tcp那个，不会杀adbyby或者 udp 那个...

**Comment by KevinMX** [comment]
内存炸啦。加个zram上去看看吧。

**Comment by niphor** [comment]
@KevinMX 好的大佬，我编译个试试

P.S. 昨天翻了半天issue,居然漏了您这个...

**Comment by niphor** [comment]
@KevinMX 请问zram-swap 您有改设置么？
我编译好后日志里看见他分配了60多的zram，但是adbyby+ v2 单线程（tcp+udp）还是会kill tcp

**Comment by KevinMX** [comment]
把adbyby关了试试吧。之前我只开v2ray都会OOM的……别难为K2P了，让它乖乖做个AP吧。跑高强度加解密实在是太难了……

**Comment by niphor** [comment]
好吧，我暂时改了下启动脚本 v2ray跑单个进程+adbyby 还算可以

主要是 这台扔老家给家里人用的，主要用adbyby去广告，要跑科学是为了更新anti-Ad的规则....生活就是这么艰难....
