### ISSUE TITLE
用Pandorabox编译v2ray失败

### ISSUE THREAD

**Issue by yaott2020-666** [fw876/helloworld#185]
如题，下面是错误信息

src/v2ray.com/core/transport/internet/websocket/connection.go:10:2: cannot find package "github.com/gorilla/websocket" in any of:
        /home/yaott/pan/staging_dir/target-mipsel_1004kc+dsp_uClibc-1.0.x/host/lib/go-cross/src/github.com/gorilla/websocket (from $GOROOT)
        /home/yaott/pan/build_dir/target-mipsel_1004kc+dsp_uClibc-1.0.x/v2ray-core-4.28.2/.go_work/build/src/github.com/gorilla/websocket (from $GOPATH)
src/v2ray.com/core/transport/internet/tcp/hub.go:11:2: cannot find package "github.com/pires/go-proxyproto" in any of:
        /home/yaott/pan/staging_dir/target-mipsel_1004kc+dsp_uClibc-1.0.x/host/lib/go-cross/src/github.com/pires/go-proxyproto (from $GOROOT)
        /home/yaott/pan/build_dir/target-mipsel_1004kc+dsp_uClibc-1.0.x/v2ray-core-4.28.2/.go_work/build/src/github.com/pires/go-proxyproto (from $GOPATH)
src/v2ray.com/core/common/antireplay/antireplay.go:4:2: cannot find package "github.com/seiflotfy/cuckoofilter" in any of:
        /home/yaott/pan/staging_dir/target-mipsel_1004kc+dsp_uClibc-1.0.x/host/lib/go-cross/src/github.com/seiflotfy/cuckoofilter (from $GOROOT)
        /home/yaott/pan/build_dir/target-mipsel_1004kc+dsp_uClibc-1.0.x/v2ray-core-4.28.2/.go_work/build/src/github.com/seiflotfy/cuckoofilter (from $GOPATH)
src/v2ray.com/core/app/router/condition.go:8:2: cannot find package "go.starlark.net/starlark" in any of:
        /home/yaott/pan/staging_dir/target-mipsel_1004kc+dsp_uClibc-1.0.x/host/lib/go-cross/src/go.starlark.net/starlark (from $GOROOT)
        /home/yaott/pan/build_dir/target-mipsel_1004kc+dsp_uClibc-1.0.x/v2ray-core-4.28.2/.go_work/build/src/go.starlark.net/starlark (from $GOPATH)
src/v2ray.com/core/app/router/condition.go:9:2: cannot find package "go.starlark.net/syntax" in any of:
        /home/yaott/pan/staging_dir/target-mipsel_1004kc+dsp_uClibc-1.0.x/host/lib/go-cross/src/go.starlark.net/syntax (from $GOROOT)
        /home/yaott/pan/build_dir/target-mipsel_1004kc+dsp_uClibc-1.0.x/v2ray-core-4.28.2/.go_work/build/src/go.starlark.net/syntax (from $GOPATH)
src/v2ray.com/core/proxy/shadowsocks/config.go:11:2: cannot find package "golang.org/x/crypto/chacha20poly1305" in any of:
        /home/yaott/pan/staging_dir/target-mipsel_1004kc+dsp_uClibc-1.0.x/host/lib/go-cross/src/golang.org/x/crypto/chacha20poly1305 (from $GOROOT)
        /home/yaott/pan/build_dir/target-mipsel_1004kc+dsp_uClibc-1.0.x/v2ray-core-4.28.2/.go_work/build/src/golang.org/x/crypto/chacha20poly1305 (from $GOPATH)
src/v2ray.com/core/external/github.com/marten-seemann/qtls/13.go:25:2: cannot find package "golang.org/x/crypto/curve25519" in any of:
        /home/yaott/pan/staging_dir/target-mipsel_1004kc+dsp_uClibc-1.0.x/host/lib/go-cross/src/golang.org/x/crypto/curve25519 (from $GOROOT)
        /home/yaott/pan/build_dir/target-mipsel_1004kc+dsp_uClibc-1.0.x/v2ray-core-4.28.2/.go_work/build/src/golang.org/x/crypto/curve25519 (from $GOPATH)
../../../../../staging_dir/target-mipsel_1004kc+dsp_uClibc-1.0.x/host/lib/go-cross/src/crypto/ed25519/ed25519.go:32:2: cannot find package "golang.org/x/crypto/ed25519/internal/edwards25519" in any of:
        /home/yaott/pan/staging_dir/target-mipsel_1004kc+dsp_uClibc-1.0.x/host/lib/go-cross/src/vendor/golang.org/x/crypto/ed25519/internal/edwards25519 (vendor tree)
        /home/yaott/pan/staging_dir/target-mipsel_1004kc+dsp_uClibc-1.0.x/host/lib/go-cross/src/golang.org/x/crypto/ed25519/internal/edwards25519 (from $GOROOT)
        /home/yaott/pan/build_dir/target-mipsel_1004kc+dsp_uClibc-1.0.x/v2ray-core-4.28.2/.go_work/build/src/golang.org/x/crypto/ed25519/internal/edwards25519 (from $GOPATH)
src/v2ray.com/core/proxy/shadowsocks/config.go:12:2: cannot find package "golang.org/x/crypto/hkdf" in any of:
        /home/yaott/pan/staging_dir/target-mipsel_1004kc+dsp_uClibc-1.0.x/host/lib/go-cross/src/golang.org/x/crypto/hkdf (from $GOROOT)
        /home/yaott/pan/build_dir/target-mipsel_1004kc+dsp_uClibc-1.0.x/v2ray-core-4.28.2/.go_work/build/src/golang.org/x/crypto/hkdf (from $GOPATH)
src/v2ray.com/core/proxy/vmess/encoding/auth.go:10:2: cannot find package "golang.org/x/crypto/sha3" in any of:
        /home/yaott/pan/staging_dir/target-mipsel_1004kc+dsp_uClibc-1.0.x/host/lib/go-cross/src/golang.org/x/crypto/sha3 (from $GOROOT)
        /home/yaott/pan/build_dir/target-mipsel_1004kc+dsp_uClibc-1.0.x/v2ray-core-4.28.2/.go_work/build/src/golang.org/x/crypto/sha3 (from $GOPATH)
src/v2ray.com/core/app/dns/dnscommon.go:9:2: cannot find package "golang.org/x/net/dns/dnsmessage" in any of:
        /home/yaott/pan/staging_dir/target-mipsel_1004kc+dsp_uClibc-1.0.x/host/lib/go-cross/src/golang.org/x/net/dns/dnsmessage (from $GOROOT)
        /home/yaott/pan/build_dir/target-mipsel_1004kc+dsp_uClibc-1.0.x/v2ray-core-4.28.2/.go_work/build/src/golang.org/x/net/dns/dnsmessage (from $GOPATH)
src/v2ray.com/core/proxy/http/client.go:14:2: cannot find package "golang.org/x/net/http2" in any of:
        /home/yaott/pan/staging_dir/target-mipsel_1004kc+dsp_uClibc-1.0.x/host/lib/go-cross/src/golang.org/x/net/http2 (from $GOROOT)
        /home/yaott/pan/build_dir/target-mipsel_1004kc+dsp_uClibc-1.0.x/v2ray-core-4.28.2/.go_work/build/src/golang.org/x/net/http2 (from $GOPATH)
src/v2ray.com/core/transport/internet/http/hub.go:13:2: cannot find package "golang.org/x/net/http2/h2c" in any of:
        /home/yaott/pan/staging_dir/target-mipsel_1004kc+dsp_uClibc-1.0.x/host/lib/go-cross/src/golang.org/x/net/http2/h2c (from $GOROOT)
        /home/yaott/pan/build_dir/target-mipsel_1004kc+dsp_uClibc-1.0.x/v2ray-core-4.28.2/.go_work/build/src/golang.org/x/net/http2/h2c (from $GOPATH)
src/v2ray.com/core/transport/internet/sockopt_linux.go:7:2: cannot find package "golang.org/x/sys/unix" in any of:
        /home/yaott/pan/staging_dir/target-mipsel_1004kc+dsp_uClibc-1.0.x/host/lib/go-cross/src/golang.org/x/sys/unix (from $GOROOT)
        /home/yaott/pan/build_dir/target-mipsel_1004kc+dsp_uClibc-1.0.x/v2ray-core-4.28.2/.go_work/build/src/golang.org/x/sys/unix (from $GOPATH)
src/v2ray.com/core/app/commander/commander.go:12:2: cannot find package "google.golang.org/grpc" in any of:
        /home/yaott/pan/staging_dir/target-mipsel_1004kc+dsp_uClibc-1.0.x/host/lib/go-cross/src/google.golang.org/grpc (from $GOROOT)
        /home/yaott/pan/build_dir/target-mipsel_1004kc+dsp_uClibc-1.0.x/v2ray-core-4.28.2/.go_work/build/src/google.golang.org/grpc (from $GOPATH)
src/v2ray.com/core/app/log/command/config_grpc.pb.go:8:2: cannot find package "google.golang.org/grpc/codes" in any of:
        /home/yaott/pan/staging_dir/target-mipsel_1004kc+dsp_uClibc-1.0.x/host/lib/go-cross/src/google.golang.org/grpc/codes (from $GOROOT)
        /home/yaott/pan/build_dir/target-mipsel_1004kc+dsp_uClibc-1.0.x/v2ray-core-4.28.2/.go_work/build/src/google.golang.org/grpc/codes (from $GOPATH)
src/v2ray.com/core/app/log/command/config_grpc.pb.go:9:2: cannot find package "google.golang.org/grpc/status" in any of:
        /home/yaott/pan/staging_dir/target-mipsel_1004kc+dsp_uClibc-1.0.x/host/lib/go-cross/src/google.golang.org/grpc/status (from $GOROOT)
        /home/yaott/pan/build_dir/target-mipsel_1004kc+dsp_uClibc-1.0.x/v2ray-core-4.28.2/.go_work/build/src/google.golang.org/grpc/status (from $GOPATH)
../../../../../staging_dir/target-mipsel_1004kc+dsp_uClibc-1.0.x/host/lib/go-cross/src/github.com/golang/protobuf/proto/buffer.go:11:2: cannot find package "google.golang.org/protobuf/encoding/prototext" in any of:
        /home/yaott/pan/staging_dir/target-mipsel_1004kc+dsp_uClibc-1.0.x/host/lib/go-cross/src/vendor/google.golang.org/protobuf/encoding/prototext (vendor tree)
        /home/yaott/pan/staging_dir/target-mipsel_1004kc+dsp_uClibc-1.0.x/host/lib/go-cross/src/google.golang.org/protobuf/encoding/prototext (from $GOROOT)
        /home/yaott/pan/build_dir/target-mipsel_1004kc+dsp_uClibc-1.0.x/v2ray-core-4.28.2/.go_work/build/src/google.golang.org/protobuf/encoding/prototext (from $GOPATH)
../../../../../staging_dir/target-mipsel_1004kc+dsp_uClibc-1.0.x/host/lib/go-cross/src/github.com/golang/protobuf/proto/buffer.go:12:2: cannot find package "google.golang.org/protobuf/encoding/protowire" in any of:
        /home/yaott/pan/staging_dir/target-mipsel_1004kc+dsp_uClibc-1.0.x/host/lib/go-cross/src/vendor/google.golang.org/protobuf/encoding/protowire (vendor tree)
        /home/yaott/pan/staging_dir/target-mipsel_1004kc+dsp_uClibc-1.0.x/host/lib/go-cross/src/google.golang.org/protobuf/encoding/protowire (from $GOROOT)
        /home/yaott/pan/build_dir/target-mipsel_1004kc+dsp_uClibc-1.0.x/v2ray-core-4.28.2/.go_work/build/src/google.golang.org/protobuf/encoding/protowire (from $GOPATH)
../../../../../staging_dir/target-mipsel_1004kc+dsp_uClibc-1.0.x/host/lib/go-cross/src/github.com/golang/protobuf/proto/deprecated.go:13:2: cannot find package "google.golang.org/protobuf/proto" in any of:
        /home/yaott/pan/staging_dir/target-mipsel_1004kc+dsp_uClibc-1.0.x/host/lib/go-cross/src/vendor/google.golang.org/protobuf/proto (vendor tree)
        /home/yaott/pan/staging_dir/target-mipsel_1004kc+dsp_uClibc-1.0.x/host/lib/go-cross/src/google.golang.org/protobuf/proto (from $GOROOT)
        /home/yaott/pan/build_dir/target-mipsel_1004kc+dsp_uClibc-1.0.x/v2ray-core-4.28.2/.go_work/build/src/google.golang.org/protobuf/proto (from $GOPATH)
../../../../../staging_dir/target-mipsel_1004kc+dsp_uClibc-1.0.x/host/lib/go-cross/src/github.com/golang/protobuf/proto/defaults.go:8:2: cannot find package "google.golang.org/protobuf/reflect/protoreflect" in any of:
        /home/yaott/pan/staging_dir/target-mipsel_1004kc+dsp_uClibc-1.0.x/host/lib/go-cross/src/vendor/google.golang.org/protobuf/reflect/protoreflect (vendor tree)
        /home/yaott/pan/staging_dir/target-mipsel_1004kc+dsp_uClibc-1.0.x/host/lib/go-cross/src/google.golang.org/protobuf/reflect/protoreflect (from $GOROOT)
        /home/yaott/pan/build_dir/target-mipsel_1004kc+dsp_uClibc-1.0.x/v2ray-core-4.28.2/.go_work/build/src/google.golang.org/protobuf/reflect/protoreflect (from $GOPATH)
../../../../../staging_dir/target-mipsel_1004kc+dsp_uClibc-1.0.x/host/lib/go-cross/src/github.com/golang/protobuf/proto/extensions.go:15:2: cannot find package "google.golang.org/protobuf/reflect/protoregistry" in any of:
        /home/yaott/pan/staging_dir/target-mipsel_1004kc+dsp_uClibc-1.0.x/host/lib/go-cross/src/vendor/google.golang.org/protobuf/reflect/protoregistry (vendor tree)
        /home/yaott/pan/staging_dir/target-mipsel_1004kc+dsp_uClibc-1.0.x/host/lib/go-cross/src/google.golang.org/protobuf/reflect/protoregistry (from $GOROOT)
        /home/yaott/pan/build_dir/target-mipsel_1004kc+dsp_uClibc-1.0.x/v2ray-core-4.28.2/.go_work/build/src/google.golang.org/protobuf/reflect/protoregistry (from $GOPATH)
../../../../../staging_dir/target-mipsel_1004kc+dsp_uClibc-1.0.x/host/lib/go-cross/src/github.com/golang/protobuf/proto/extensions.go:16:2: cannot find package "google.golang.org/protobuf/runtime/protoiface" in any of:
        /home/yaott/pan/staging_dir/target-mipsel_1004kc+dsp_uClibc-1.0.x/host/lib/go-cross/src/vendor/google.golang.org/protobuf/runtime/protoiface (vendor tree)
        /home/yaott/pan/staging_dir/target-mipsel_1004kc+dsp_uClibc-1.0.x/host/lib/go-cross/src/google.golang.org/protobuf/runtime/protoiface (from $GOROOT)
        /home/yaott/pan/build_dir/target-mipsel_1004kc+dsp_uClibc-1.0.x/v2ray-core-4.28.2/.go_work/build/src/google.golang.org/protobuf/runtime/protoiface (from $GOPATH)
../../../../../staging_dir/target-mipsel_1004kc+dsp_uClibc-1.0.x/host/lib/go-cross/src/github.com/golang/protobuf/proto/buffer.go:13:2: cannot find package "google.golang.org/protobuf/runtime/protoimpl" in any of:
        /home/yaott/pan/staging_dir/target-mipsel_1004kc+dsp_uClibc-1.0.x/host/lib/go-cross/src/vendor/google.golang.org/protobuf/runtime/protoimpl (vendor tree)
        /home/yaott/pan/staging_dir/target-mipsel_1004kc+dsp_uClibc-1.0.x/host/lib/go-cross/src/google.golang.org/protobuf/runtime/protoimpl (from $GOROOT)
        /home/yaott/pan/build_dir/target-mipsel_1004kc+dsp_uClibc-1.0.x/v2ray-core-4.28.2/.go_work/build/src/google.golang.org/protobuf/runtime/protoimpl (from $GOPATH)
Makefile:308: recipe for target '/home/yaott/pan/build_dir/target-mipsel_1004kc+dsp_uClibc-1.0.x/v2ray-core-4.28.2/.built' failed
make[2]: *** [/home/yaott/pan/build_dir/target-mipsel_1004kc+dsp_uClibc-1.0.x/v2ray-core-4.28.2/.built] Error 1
make[2]: Leaving directory '/home/yaott/pan/package/v2ray'
package/Makefile:105: recipe for target 'package/v2ray/compile' failed
make[1]: *** [package/v2ray/compile] Error 2
make[1]: Leaving directory '/home/yaott/pan'
/home/yaott/pan/include/toplevel.mk:192: recipe for target 'package/v2ray/compile' failed
make: *** [package/v2ray/compile] Error 2

**Comment by Mr-xn** [comment]
> 如题，下面是错误信息
> 
> src/v2ray.com/core/transport/internet/websocket/connection.go:10:2: cannot find package "github.com/gorilla/websocket" in any of:
> /home/yaott/pan/staging_dir/target-mipsel_1004kc+dsp_uClibc-1.0.x/host/lib/go-cross/src/github.com/gorilla/websocket (from $GOROOT)
> /home/yaott/pan/build_dir/target-mipsel_1004kc+dsp_uClibc-1.0.x/v2ray-core-4.28.2/.go_work/build/src/github.com/gorilla/websocket (from $GOPATH)
> src/v2ray.com/core/transport/internet/tcp/hub.go:11:2: cannot find package "github.com/pires/go-proxyproto" in any of:
> /home/yaott/pan/staging_dir/target-mipsel_1004kc+dsp_uClibc-1.0.x/host/lib/go-cross/src/github.com/pires/go-proxyproto (from $GOROOT)
> /home/yaott/pan/build_dir/target-mipsel_1004kc+dsp_uClibc-1.0.x/v2ray-core-4.28.2/.go_work/build/src/github.com/pires/go-proxyproto (from $GOPATH)
> src/v2ray.com/core/common/antireplay/antireplay.go:4:2: cannot find package "github.com/seiflotfy/cuckoofilter" in any of:
> /home/yaott/pan/staging_dir/target-mipsel_1004kc+dsp_uClibc-1.0.x/host/lib/go-cross/src/github.com/seiflotfy/cuckoofilter (from $GOROOT)
> /home/yaott/pan/build_dir/target-mipsel_1004kc+dsp_uClibc-1.0.x/v2ray-core-4.28.2/.go_work/build/src/github.com/seiflotfy/cuckoofilter (from $GOPATH)
> src/v2ray.com/core/app/router/condition.go:8:2: cannot find package "go.starlark.net/starlark" in any of:
> /home/yaott/pan/staging_dir/target-mipsel_1004kc+dsp_uClibc-1.0.x/host/lib/go-cross/src/go.starlark.net/starlark (from $GOROOT)
> /home/yaott/pan/build_dir/target-mipsel_1004kc+dsp_uClibc-1.0.x/v2ray-core-4.28.2/.go_work/build/src/go.starlark.net/starlark (from $GOPATH)
> src/v2ray.com/core/app/router/condition.go:9:2: cannot find package "go.starlark.net/syntax" in any of:
> /home/yaott/pan/staging_dir/target-mipsel_1004kc+dsp_uClibc-1.0.x/host/lib/go-cross/src/go.starlark.net/syntax (from $GOROOT)
> /home/yaott/pan/build_dir/target-mipsel_1004kc+dsp_uClibc-1.0.x/v2ray-core-4.28.2/.go_work/build/src/go.starlark.net/syntax (from $GOPATH)
> src/v2ray.com/core/proxy/shadowsocks/config.go:11:2: cannot find package "golang.org/x/crypto/chacha20poly1305" in any of:
> /home/yaott/pan/staging_dir/target-mipsel_1004kc+dsp_uClibc-1.0.x/host/lib/go-cross/src/golang.org/x/crypto/chacha20poly1305 (from $GOROOT)
> /home/yaott/pan/build_dir/target-mipsel_1004kc+dsp_uClibc-1.0.x/v2ray-core-4.28.2/.go_work/build/src/golang.org/x/crypto/chacha20poly1305 (from $GOPATH)
> src/v2ray.com/core/external/github.com/marten-seemann/qtls/13.go:25:2: cannot find package "golang.org/x/crypto/curve25519" in any of:
> /home/yaott/pan/staging_dir/target-mipsel_1004kc+dsp_uClibc-1.0.x/host/lib/go-cross/src/golang.org/x/crypto/curve25519 (from $GOROOT)
> /home/yaott/pan/build_dir/target-mipsel_1004kc+dsp_uClibc-1.0.x/v2ray-core-4.28.2/.go_work/build/src/golang.org/x/crypto/curve25519 (from $GOPATH)
> ../../../../../staging_dir/target-mipsel_1004kc+dsp_uClibc-1.0.x/host/lib/go-cross/src/crypto/ed25519/ed25519.go:32:2: cannot find package "golang.org/x/crypto/ed25519/internal/edwards25519" in any of:
> /home/yaott/pan/staging_dir/target-mipsel_1004kc+dsp_uClibc-1.0.x/host/lib/go-cross/src/vendor/golang.org/x/crypto/ed25519/internal/edwards25519 (vendor tree)
> /home/yaott/pan/staging_dir/target-mipsel_1004kc+dsp_uClibc-1.0.x/host/lib/go-cross/src/golang.org/x/crypto/ed25519/internal/edwards25519 (from $GOROOT)
> /home/yaott/pan/build_dir/target-mipsel_1004kc+dsp_uClibc-1.0.x/v2ray-core-4.28.2/.go_work/build/src/golang.org/x/crypto/ed25519/internal/edwards25519 (from $GOPATH)
> src/v2ray.com/core/proxy/shadowsocks/config.go:12:2: cannot find package "golang.org/x/crypto/hkdf" in any of:
> /home/yaott/pan/staging_dir/target-mipsel_1004kc+dsp_uClibc-1.0.x/host/lib/go-cross/src/golang.org/x/crypto/hkdf (from $GOROOT)
> /home/yaott/pan/build_dir/target-mipsel_1004kc+dsp_uClibc-1.0.x/v2ray-core-4.28.2/.go_work/build/src/golang.org/x/crypto/hkdf (from $GOPATH)
> src/v2ray.com/core/proxy/vmess/encoding/auth.go:10:2: cannot find package "golang.org/x/crypto/sha3" in any of:
> /home/yaott/pan/staging_dir/target-mipsel_1004kc+dsp_uClibc-1.0.x/host/lib/go-cross/src/golang.org/x/crypto/sha3 (from $GOROOT)
> /home/yaott/pan/build_dir/target-mipsel_1004kc+dsp_uClibc-1.0.x/v2ray-core-4.28.2/.go_work/build/src/golang.org/x/crypto/sha3 (from $GOPATH)
> src/v2ray.com/core/app/dns/dnscommon.go:9:2: cannot find package "golang.org/x/net/dns/dnsmessage" in any of:
> /home/yaott/pan/staging_dir/target-mipsel_1004kc+dsp_uClibc-1.0.x/host/lib/go-cross/src/golang.org/x/net/dns/dnsmessage (from $GOROOT)
> /home/yaott/pan/build_dir/target-mipsel_1004kc+dsp_uClibc-1.0.x/v2ray-core-4.28.2/.go_work/build/src/golang.org/x/net/dns/dnsmessage (from $GOPATH)
> src/v2ray.com/core/proxy/http/client.go:14:2: cannot find package "golang.org/x/net/http2" in any of:
> /home/yaott/pan/staging_dir/target-mipsel_1004kc+dsp_uClibc-1.0.x/host/lib/go-cross/src/golang.org/x/net/http2 (from $GOROOT)
> /home/yaott/pan/build_dir/target-mipsel_1004kc+dsp_uClibc-1.0.x/v2ray-core-4.28.2/.go_work/build/src/golang.org/x/net/http2 (from $GOPATH)
> src/v2ray.com/core/transport/internet/http/hub.go:13:2: cannot find package "golang.org/x/net/http2/h2c" in any of:
> /home/yaott/pan/staging_dir/target-mipsel_1004kc+dsp_uClibc-1.0.x/host/lib/go-cross/src/golang.org/x/net/http2/h2c (from $GOROOT)
> /home/yaott/pan/build_dir/target-mipsel_1004kc+dsp_uClibc-1.0.x/v2ray-core-4.28.2/.go_work/build/src/golang.org/x/net/http2/h2c (from $GOPATH)
> src/v2ray.com/core/transport/internet/sockopt_linux.go:7:2: cannot find package "golang.org/x/sys/unix" in any of:
> /home/yaott/pan/staging_dir/target-mipsel_1004kc+dsp_uClibc-1.0.x/host/lib/go-cross/src/golang.org/x/sys/unix (from $GOROOT)
> /home/yaott/pan/build_dir/target-mipsel_1004kc+dsp_uClibc-1.0.x/v2ray-core-4.28.2/.go_work/build/src/golang.org/x/sys/unix (from $GOPATH)
> src/v2ray.com/core/app/commander/commander.go:12:2: cannot find package "google.golang.org/grpc" in any of:
> /home/yaott/pan/staging_dir/target-mipsel_1004kc+dsp_uClibc-1.0.x/host/lib/go-cross/src/google.golang.org/grpc (from $GOROOT)
> /home/yaott/pan/build_dir/target-mipsel_1004kc+dsp_uClibc-1.0.x/v2ray-core-4.28.2/.go_work/build/src/google.golang.org/grpc (from $GOPATH)
> src/v2ray.com/core/app/log/command/config_grpc.pb.go:8:2: cannot find package "google.golang.org/grpc/codes" in any of:
> /home/yaott/pan/staging_dir/target-mipsel_1004kc+dsp_uClibc-1.0.x/host/lib/go-cross/src/google.golang.org/grpc/codes (from $GOROOT)
> /home/yaott/pan/build_dir/target-mipsel_1004kc+dsp_uClibc-1.0.x/v2ray-core-4.28.2/.go_work/build/src/google.golang.org/grpc/codes (from $GOPATH)
> src/v2ray.com/core/app/log/command/config_grpc.pb.go:9:2: cannot find package "google.golang.org/grpc/status" in any of:
> /home/yaott/pan/staging_dir/target-mipsel_1004kc+dsp_uClibc-1.0.x/host/lib/go-cross/src/google.golang.org/grpc/status (from $GOROOT)
> /home/yaott/pan/build_dir/target-mipsel_1004kc+dsp_uClibc-1.0.x/v2ray-core-4.28.2/.go_work/build/src/google.golang.org/grpc/status (from $GOPATH)
> ../../../../../staging_dir/target-mipsel_1004kc+dsp_uClibc-1.0.x/host/lib/go-cross/src/github.com/golang/protobuf/proto/buffer.go:11:2: cannot find package "google.golang.org/protobuf/encoding/prototext" in any of:
> /home/yaott/pan/staging_dir/target-mipsel_1004kc+dsp_uClibc-1.0.x/host/lib/go-cross/src/vendor/google.golang.org/protobuf/encoding/prototext (vendor tree)
> /home/yaott/pan/staging_dir/target-mipsel_1004kc+dsp_uClibc-1.0.x/host/lib/go-cross/src/google.golang.org/protobuf/encoding/prototext (from $GOROOT)
> /home/yaott/pan/build_dir/target-mipsel_1004kc+dsp_uClibc-1.0.x/v2ray-core-4.28.2/.go_work/build/src/google.golang.org/protobuf/encoding/prototext (from $GOPATH)
> ../../../../../staging_dir/target-mipsel_1004kc+dsp_uClibc-1.0.x/host/lib/go-cross/src/github.com/golang/protobuf/proto/buffer.go:12:2: cannot find package "google.golang.org/protobuf/encoding/protowire" in any of:
> /home/yaott/pan/staging_dir/target-mipsel_1004kc+dsp_uClibc-1.0.x/host/lib/go-cross/src/vendor/google.golang.org/protobuf/encoding/protowire (vendor tree)
> /home/yaott/pan/staging_dir/target-mipsel_1004kc+dsp_uClibc-1.0.x/host/lib/go-cross/src/google.golang.org/protobuf/encoding/protowire (from $GOROOT)
> /home/yaott/pan/build_dir/target-mipsel_1004kc+dsp_uClibc-1.0.x/v2ray-core-4.28.2/.go_work/build/src/google.golang.org/protobuf/encoding/protowire (from $GOPATH)
> ../../../../../staging_dir/target-mipsel_1004kc+dsp_uClibc-1.0.x/host/lib/go-cross/src/github.com/golang/protobuf/proto/deprecated.go:13:2: cannot find package "google.golang.org/protobuf/proto" in any of:
> /home/yaott/pan/staging_dir/target-mipsel_1004kc+dsp_uClibc-1.0.x/host/lib/go-cross/src/vendor/google.golang.org/protobuf/proto (vendor tree)
> /home/yaott/pan/staging_dir/target-mipsel_1004kc+dsp_uClibc-1.0.x/host/lib/go-cross/src/google.golang.org/protobuf/proto (from $GOROOT)
> /home/yaott/pan/build_dir/target-mipsel_1004kc+dsp_uClibc-1.0.x/v2ray-core-4.28.2/.go_work/build/src/google.golang.org/protobuf/proto (from $GOPATH)
> ../../../../../staging_dir/target-mipsel_1004kc+dsp_uClibc-1.0.x/host/lib/go-cross/src/github.com/golang/protobuf/proto/defaults.go:8:2: cannot find package "google.golang.org/protobuf/reflect/protoreflect" in any of:
> /home/yaott/pan/staging_dir/target-mipsel_1004kc+dsp_uClibc-1.0.x/host/lib/go-cross/src/vendor/google.golang.org/protobuf/reflect/protoreflect (vendor tree)
> /home/yaott/pan/staging_dir/target-mipsel_1004kc+dsp_uClibc-1.0.x/host/lib/go-cross/src/google.golang.org/protobuf/reflect/protoreflect (from $GOROOT)
> /home/yaott/pan/build_dir/target-mipsel_1004kc+dsp_uClibc-1.0.x/v2ray-core-4.28.2/.go_work/build/src/google.golang.org/protobuf/reflect/protoreflect (from $GOPATH)
> ../../../../../staging_dir/target-mipsel_1004kc+dsp_uClibc-1.0.x/host/lib/go-cross/src/github.com/golang/protobuf/proto/extensions.go:15:2: cannot find package "google.golang.org/protobuf/reflect/protoregistry" in any of:
> /home/yaott/pan/staging_dir/target-mipsel_1004kc+dsp_uClibc-1.0.x/host/lib/go-cross/src/vendor/google.golang.org/protobuf/reflect/protoregistry (vendor tree)
> /home/yaott/pan/staging_dir/target-mipsel_1004kc+dsp_uClibc-1.0.x/host/lib/go-cross/src/google.golang.org/protobuf/reflect/protoregistry (from $GOROOT)
> /home/yaott/pan/build_dir/target-mipsel_1004kc+dsp_uClibc-1.0.x/v2ray-core-4.28.2/.go_work/build/src/google.golang.org/protobuf/reflect/protoregistry (from $GOPATH)
> ../../../../../staging_dir/target-mipsel_1004kc+dsp_uClibc-1.0.x/host/lib/go-cross/src/github.com/golang/protobuf/proto/extensions.go:16:2: cannot find package "google.golang.org/protobuf/runtime/protoiface" in any of:
> /home/yaott/pan/staging_dir/target-mipsel_1004kc+dsp_uClibc-1.0.x/host/lib/go-cross/src/vendor/google.golang.org/protobuf/runtime/protoiface (vendor tree)
> /home/yaott/pan/staging_dir/target-mipsel_1004kc+dsp_uClibc-1.0.x/host/lib/go-cross/src/google.golang.org/protobuf/runtime/protoiface (from $GOROOT)
> /home/yaott/pan/build_dir/target-mipsel_1004kc+dsp_uClibc-1.0.x/v2ray-core-4.28.2/.go_work/build/src/google.golang.org/protobuf/runtime/protoiface (from $GOPATH)
> ../../../../../staging_dir/target-mipsel_1004kc+dsp_uClibc-1.0.x/host/lib/go-cross/src/github.com/golang/protobuf/proto/buffer.go:13:2: cannot find package "google.golang.org/protobuf/runtime/protoimpl" in any of:
> /home/yaott/pan/staging_dir/target-mipsel_1004kc+dsp_uClibc-1.0.x/host/lib/go-cross/src/vendor/google.golang.org/protobuf/runtime/protoimpl (vendor tree)
> /home/yaott/pan/staging_dir/target-mipsel_1004kc+dsp_uClibc-1.0.x/host/lib/go-cross/src/google.golang.org/protobuf/runtime/protoimpl (from $GOROOT)
> /home/yaott/pan/build_dir/target-mipsel_1004kc+dsp_uClibc-1.0.x/v2ray-core-4.28.2/.go_work/build/src/google.golang.org/protobuf/runtime/protoimpl (from $GOPATH)
> Makefile:308: recipe for target '/home/yaott/pan/build_dir/target-mipsel_1004kc+dsp_uClibc-1.0.x/v2ray-core-4.28.2/.built' failed
> make[2]: *** [/home/yaott/pan/build_dir/target-mipsel_1004kc+dsp_uClibc-1.0.x/v2ray-core-4.28.2/.built] Error 1
> make[2]: Leaving directory '/home/yaott/pan/package/v2ray'
> package/Makefile:105: recipe for target 'package/v2ray/compile' failed
> make[1]: *** [package/v2ray/compile] Error 2
> make[1]: Leaving directory '/home/yaott/pan'
> /home/yaott/pan/include/toplevel.mk:192: recipe for target 'package/v2ray/compile' failed
> make: *** [package/v2ray/compile] Error 2

试试使用Ubuntu 18 desktop 版本 我的可以整体编译成功 也可以单独编译v2ray(在有一次完整编译后) [v2ray_4.28.2-1_arm_cortex-a9.ipk](https://github.com/Mr-xn/k3_packages_backup/blob/master/packages/arm_cortex-a9/base/v2ray_4.28.2-1_arm_cortex-a9.ipk)

**Comment by yaott2020-666** [comment]
搞定了，是go版本过低的问题，将Pandorabox的go版本改成1.15.2就可以了，另外wsl编译ssrplus会出错，我是用ubuntu18.04的server版才搞定的
