### ISSUE TITLE
是否支持vless，配置vless要去掉客戶端的alertid，但是我把alertid留空，提交之後默認會填寫16

### ISSUE THREAD

**Issue by tstart** [fw876/helloworld#186]
rt，服務器配置中已經有Vmess/VLESS ID (UUID)字樣，貌似支持。

**Comment by Mr-xn** [comment]
> rt，服務器配置中已經有Vmess/VLESS ID (UUID)字樣，貌似支持。

在没有支持之前 你可以尝试ssh进去直接修改json配置文件 在运行即可

**Comment by tstart** [comment]
> > rt，服務器配置中已經有Vmess/VLESS ID (UUID)字樣，貌似支持。
> 
> 在没有支持之前 你可以尝试ssh进去直接修改json配置文件 在运行即可

那就是还没完全支持了，如果修改了配置文件，下次编辑提交还是需要重复修改吧。

**Comment by smallprogram** [comment]
你重新编译一下，早就支持了。确认一下源码是否更新
