### ISSUE TITLE
好像使用ssrplus+的 trojan打不开https://trojan-tutor.github.io/

### ISSUE THREAD

**Issue by ztfot** [fw876/helloworld#194]
使用Passwall可以打开https://trojan-tutor.github.io/
使用ssrplus+下的v2ray也可以打开，但是使用trojan却无法打开这个网址

**Comment by CYaNu** [comment]
没发现问题

**Comment by ztfot** [comment]
> 没发现问题

能打得开嘛？

**Comment by iii80** [comment]
打不开，对比能打开的机器发现证书好像有问题。能打开的证书是有效的正确的，打不开的是证书过期的，不知道是不是这个问题造成的无法访问。

**Comment by ztfot** [comment]
> 打不开，对比能打开的机器发现证书好像有问题。能打开的证书是有效的正确的，打不开的是证书过期的，不知道是不是这个问题造成的无法访问。

我实在是不知道为什么

**Comment by ztfot** [comment]
> 打不开，对比能打开的机器发现证书好像有问题。能打开的证书是有效的正确的，打不开的是证书过期的，不知道是不是这个问题造成的无法访问。

我检查过了，证书均正确有效，但是还是打不开
