### ISSUE TITLE
ssr勾选自动更新节点信息后，每次更新都会出现PDNSD报错信息

### ISSUE THREAD

**Issue by tone88** [fw876/helloworld#20]
直接上图
![photo_2020-04-28_09-04-30](https://user-images.githubusercontent.com/47731895/80435606-8ec58900-892f-11ea-87dc-97c6373dea5c.jpg)

选的晚上4点自动更新，更新后会出现上面的错误信息，也不知道有什么影响。
 之前的版本没这问题！

**Comment by EnnawYang** [comment]
早就有了，不过没发现有什么影响

**Comment by tone88** [comment]
> 早就有了，不过没发现有什么影响

就这2天更新后才有的吧，23号的版本没发现有这个问题。 不过确实没发现有什么影响。

**Comment by EnnawYang** [comment]
> > 早就有了，不过没发现有什么影响
> 
> 就这2天更新后才有的吧，23号的版本没发现有这个问题。 不过确实没发现有什么影响。

不清楚了 只知道看到有几天了，具体什么时候有的不记得了

**Comment by github-xihe** [comment]
是的，这两天同样出现了。不过没有发现什么影响

**Comment by iamggs** [comment]
一样的问题，大约从上一个版本176-7+v2ray_4.23.1-1开始的，每次默认的凌晨2点自动更新的时候出现，手动更新貌似又不出现，搞不懂。
`* 04/30 02:00:33| pdnsd: error: tcp and udp initialization failed. Exiting.
* 04/30 02:00:33| pdnsd: error: Could not bind to udp socket: Address in use
* 04/30 02:00:33| pdnsd: error: Could not bind tcp socket: Address in use
2020-04-30 02:00:32 V2Ray 4.23.1 (OpenWrt) Lean (go1.14 linux/amd64) Started!
2020-04-30 02:00:18 V2Ray 4.23.1 (OpenWrt) Lean (go1.14 linux/amd64) Started!
2020-04-30 02:00:17 订阅更新成功
2020-04-30 02:00:17 新增节点数量: 0 删除节点数量: 1`

**Comment by iamggs** [comment]
经过[@Mattraks](https://github.com/Mattraks) 修改，貌似不报错了。
