### ISSUE TITLE
希望能支持 trojan-go 的客户端

### ISSUE THREAD

**Issue by wesleywxie** [fw876/helloworld#200]
Trojan-GO 已经从各方面可以说已经超越原版 Trojan 了，希望能支持Trojan-GO的相关配置

**Comment by norikohxb** [comment]
同求哦，我是看了腹语哥的内网测试说trojan-go优于trojan

**Comment by Lrvineshaw** [comment]
有人解释过了，golang对于性能低的路由器压力很大，不建议用

**Comment by ryshi** [comment]
v2ray就是用golang写的，这个不会是障碍

**Comment by realsteam** [comment]
同希望能加入trojan-go

**Comment by entr0pee** [comment]
> 同求哦，我是看了腹语哥的内网测试说trojan-go优于trojan

就是那个面瘫烂洋葱？瞪着眼说R4s把x86按地上摩擦的sb阿婆主？

**Comment by ajiter** [comment]
同求.。希望大神能加入trojan-go
