### ISSUE TITLE
#建议# SSR-plus插件，订阅节点关键字过滤能否增加一个取反操作选项

### ISSUE THREAD

**Issue by lePig** [fw876/helloworld#202]
就是比如，`订阅节点关键字过滤`：`香港/新加坡`。那么在订阅节点的时候只保留**香港节点**和**新加坡节点**。

大部分机场提供的地区节点挺多的，日本、美国、新加坡、香港、英国、台湾、澳门等等。

虽然现在关键字过滤也能实现，但是每次刷机后都要输入一大坨排除的节点，好烦呐。 

可以在`订阅节点关键字过滤`下面增加一个复选框，文案：`当勾选时，将保留列表中的关键字的节点，否则，将丢弃包含列表里的关键字的节点。`

还是希望开发者大大们有空可以采纳一下，感谢您的辛勤付出。

**Comment by YoungsunLi** [comment]
获取订阅地址处一般都有高级选项, 可以在那里过滤地区, 并获得一个仅包含过滤后节点列表的订阅链接.

**Comment by lePig** [comment]
@YoungsunLi 很多都没有。只有通用链接。这几年用了大概十几个机场，有区域指定就2个左右。所以才有这样的建议提出。

**Comment by lePig** [comment]
同样，我知道也有在线订阅转换这样的功能，可以指定某个区域节点。但是在插件上实现不是更好吗。

**Comment by YoungsunLi** [comment]
> 同样，我知道也有在线订阅转换这样的功能，可以指定某个区域节点。但是在插件上实现不是更好吗。

当然插件有的话也方便

**Comment by YoungsunLi** [comment]
我刚编译了一个最新版本(2020年10月9日20点), 发现已经其已经有了订阅节点关键字过滤功能. 可以满足你的需求.

**Comment by lePig** [comment]
@YoungsunLi  你好，能否截图看看呢？我现在用的是恩山大神编译的10.3号的版本。谢谢

**Comment by YoungsunLi** [comment]
> @YoungsunLi 你好，能否截图看看呢？我现在用的是恩山大神编译的10.3号源码的版本。谢谢

不好意思, 我认真看了一遍你的问题, 发现我理解错了, 我说的这个 `订阅节点关键字过滤` 功能, 就是你上述的那个每次输入一大坨排除的节点的功能. 🤐

**Comment by lePig** [comment]
@YoungsunLi  好的谢谢，没事。
