### ISSUE TITLE
DNS Leak / DNS泄漏

### ISSUE THREAD

**Issue by bailaowai** [fw876/helloworld#203]
I ran a dns test while using a v2ray on the universal plug-in shadowsocksR + and there was a leak. Is there anyone else having this issue?

我在通用插件shadowsocksR+上使用v2ray时运行了一个dns测试，结果出现了漏洞。还有其他人有这个问题吗？

**Comment by Lrvineshaw** [comment]
这个问题和plus没关系

**Comment by taricano** [comment]
你知道怎么做吗？

**Comment by bailaowai** [comment]
I figured it out. On the wan interface into advance options, an alternative DNS must be used. This eliminates the leaks completely.

**Comment by moralrebuild** [comment]
域名泄露(dns leak)本人测试也有。看来大家都裸奔！
