### ISSUE TITLE
希望增加一个v2ray内核手动在线更新的选项

### ISSUE THREAD

**Issue by 759071793** [fw876/helloworld#205]
希望增加一个v2ray内核手动在线更新的选项
谢谢大雕，有时候小更新不想每次升级都编译一次。

**Comment by qq1316237299** [comment]
谢谢大佬

**Comment by LGA1150** [comment]
`make package/v2ray/compile` 然后手动安装 ipk 就行了

**Comment by co1q84** [comment]
以前可以用v2ray server升级，改到v2fly后，就不行了

**Comment by qq1316237299** [comment]
主要用于x86 系统上 嘛

**Comment by martin0607** [comment]
直接去内核官网手动下载替换啊，又不用编译

**Comment by 759071793** [comment]
了解了，谢谢各位的回复，只有每次都编译下了😂

**Comment by 759071793** [comment]
> 直接去内核官网手动下载替换啊，又不用编译

麻烦大佬告知一下路径，我找了半天没找到。。。
