### ISSUE TITLE
【bug反馈】最新版本访问控制 - 白名单功能失效

### ISSUE THREAD

**Issue by pwrliang** [fw876/helloworld#21]
- 固件: Friendlywrt - R2S型号使用官方代码编译，package和luci的feeds都是用的openwrt官方openwrt-19.07分支
- ssrplus：commit id为1f523fbb70eab053f85cf0b308933ae78f5bd7ef
- 问题：配置白名单域名后在下游设备上无效，这个问题在半个月前的某次修改后出现。

复现操作：

* 在访问控制-白名单域名中添加域名

> ipify.org
api.ipify.org

* 运行模式选择大陆白名单

然后保存设置，甚至保存设置后重启了路由器。

然后进入一台路由器lan所连接的机器，输入：

> user@host-name:~$ curl api.ipify.org
13.75.109.xxx

返回的ip - 13.75.109.xxx是我的代理ip，并不是我真实的ip。

查看dnsmasq配置文件：

> root@FriendlyWrt:~ cat /tmp/dnsmasq.ssr/whitelist_forward.conf
ipset=/.ipify.org/whitelist
ipset=/.api.ipify.org/whitelist
root@FriendlyWrt:~#

> root@FriendlyWrt:~ ipset list whitelist
Name: whitelist
Type: hash:net
Revision: 6
Header: family inet hashsize 1024 maxelem 65536
Size in memory: 464
References: 1
Number of entries: 0
Members:

但是在路由器上执行curl api.ipify.org返回的是真实的ip

> root@FriendlyWrt:~ curl api.ipify.org
221.222.221.xxx

再次执行ipset，发现已经有记录了

> root@FriendlyWrt:~ ipset list whitelist
Name: whitelist
Type: hash:net
Revision: 6
Header: family inet hashsize 1024 maxelem 65536
Size in memory: 976
References: 1
Number of entries: 8
Members:
54.225.66.103
54.225.179.85
54.225.178.192
54.225.71.235
50.19.115.217
23.21.59.179
50.16.234.229
54.243.162.249

**Comment by pwrliang** [comment]
相关问题：https://github.com/coolsnowwolf/lede/issues/4409

**Comment by Mattraks** [comment]
其实并没有什么问题，该功能原理需要通过dns来实现
清除本机dns缓存过一会访问就不走代理了

**Comment by maodou38** [comment]
没有用啊 执行了pdnsd-ctl empty-cache
但是强制走代理设置baidu.com后实测走的还是直连

**Comment by RockNHawk** [comment]
我参考这篇别人的回复可以解决：

我近期也遇到了同样的问题，即“不走代理的域名”和“强制走代理的域名”两个名单无效，我试了各种方法，最后发现我这里是DNS的问题，解决方法：

关闭OpenWRT-Turbo ACC网络加速-DNS缓存。
SSR PLUS-状态-重置PDNSD缓存（SSR PLUS-客户端-DNS解析方式默认为“使用PDNSD TCP查询并缓存”）。
如果电脑使用的是Chrome浏览器，在设置中将“使用安全DNS”选项关闭（基于Chromium内核的浏览器应该都有这个选项）。
清空电脑浏览器、操作系统内的DNS缓存（两个都要清理，方法Google）。
将电脑的首选DNS设为软路由而不是主路由（我使用的是旁路由模式）。
仅供参考，希望有用：）
