### ISSUE TITLE
绕过中国大陆Ip模式问题

### ISSUE THREAD

**Issue by zhf883680** [fw876/helloworld#210]
2020.10.10拉取代码进行编译
当我选择 绕过中国大陆Ip模式 时候  访问网站 发现都走了代理  如B站 TB JD 
切换会GFW模式正常

当我回滚版本到前几个月的版本的时候  一切正常    OpenWrt R20.7.7 / LuCI Master (git-20.191.36863-eee6bae)

**Comment by Cosmos-Break** [comment]
我也是这样

**Comment by iseeyou** [comment]
绕过中国大陆Ip 不生效
