### ISSUE TITLE
终于用上最新的lede了不用再用3月21日的。但是这个纪录能否不见

### ISSUE THREAD

**Issue by norikohxb** [fw876/helloworld#22]
用上了最新的lede了。但是发现他竟然采集另外一个网段的智能家居的的upnp信息
整个系统日志都给200多个智能家居（另外一个网段，直接用主路由出去）的信息刷屏了。
请问fw876将来可以解决吗？
感谢咯
以下是系统日志。
![QQ截图20200430231635](https://user-images.githubusercontent.com/12111990/80727882-db2fe500-8b38-11ea-9aba-fe3c90cc2f21.jpg)

**Comment by Mattraks** [comment]
关闭UPnP启用安全模式
设置MiniUPnP 的 ACL

**Comment by norikohxb** [comment]
我这样设置对吗？错误纪录还在。
![QQ截图20200502110029](https://user-images.githubusercontent.com/12111990/80853531-31e60d80-8c64-11ea-9881-a2bdc85290db.jpg)

**Comment by Mattraks** [comment]
那你就关闭lede的UPnP用ros的UPnP

**Comment by Sheep-12** [comment]
![20200502183536](https://user-images.githubusercontent.com/30239165/80861853-c328a480-8ca3-11ea-88ac-2d73e9330b4c.png)
我的ssrp+ 一堆报错,我都懒得看系统日志了,反正使用正常没问题

**Comment by Mattraks** [comment]
你这是梯子不稳，ssr原装问题

**Comment by norikohxb** [comment]
> 那你就关闭lede的UPnP用ros的UPnP

我就是不可以关闭upnp，关闭了，我的老安卓的youtube的app，如果没有upnp，就无法正常看视频了。

**Comment by coolsnowwolf** [comment]
这个不是 SSR Plus 的问题

**Comment by norikohxb** [comment]
> 这个不是 SSR Plus 的问题

感谢lean大的回帖。请问这个错误有办法消除吗，局域网内不同网段的192.168.8.x的设备太多了，这个信息都要刷屏了霸屏了
![ccc](https://user-images.githubusercontent.com/12111990/80968345-63203280-8e4a-11ea-8c35-6029214526d2.JPG)

**Comment by norikohxb** [comment]
> 这个不是 SSR Plus 的问题

还请lean大能做有空的时候帮忙指点一二
![lede](https://user-images.githubusercontent.com/12111990/81071983-0db25700-8f18-11ea-9667-2c2c9bcaa729.JPG)
