### ISSUE TITLE
shadowsocks—libev版本已经不更了转向rust了，还有tcp fast open选项已经弃用，希望有大佬维护一下

### ISSUE THREAD

**Issue by swxk521** [fw876/helloworld#224]

**Comment by xiechangan123** [comment]
忍不住回一句，你确定不更了？

**Comment by hcym** [comment]
基本没影响的东西，都是自己吓自己，

**Comment by 70599** [comment]
> 忍不住回一句，你确定不更了？

这有啥确定不了的。
没有功能更新了（仅对现有代码做bug修复）。

**Comment by 70599** [comment]
而且确实如楼主描述，现行活跃分支rust已经弃用tcp fast open。
rust分支加入了基于连接速度的多服务器均衡负载等特性，希望这边luci-app能跟进一下。
