### ISSUE TITLE
订阅无法更新，如图。

### ISSUE THREAD

**Issue by libinanshu** [fw876/helloworld#23]
![QQ截图20200430235247](https://user-images.githubusercontent.com/44538423/80731806-f81ae700-8b3d-11ea-9c37-99e6299b8d5a.png)

**Comment by coolsnowwolf** [comment]
下载失败

**Comment by libinanshu** [comment]
> 下载失败

这是老妈开车的机场，之前编译的固件是阔以订阅的，这新版本点击更新日志立即就显示内容为空，机场各方面都看过都是正常的。只编译默认选项基础功能。

**Comment by Mattraks** [comment]
直接用浏览器能打开订阅地址吗？

**Comment by libinanshu** [comment]
> 直接用浏览器能打开订阅地址吗？

能打开

**Comment by libinanshu** [comment]
> > 直接用浏览器能打开订阅地址吗？
> 
> 能打开

刚才更新源码重新编译了，能正常订阅了。

**Comment by Mattraks** [comment]
正常了就关闭吧
