### ISSUE TITLE
无法使用SSR Plus访问YouTube

### ISSUE THREAD

**Issue by predators46** [fw876/helloworld#240]
我尝试使用SSR Plus访问YouTube，但YouTube无法播放视频

**Comment by XiaoliChan** [comment]
> 我尝试使用SSR Plus访问YouTube，但YouTube无法播放视频

没有这个问题，请检查dns

**Comment by predators46** [comment]
> > 我尝试使用SSR Plus访问YouTube，但YouTube无法播放视频
> 
> 没有这个问题，请检查dns

谢谢您的回复。我应该在哪里更改DNS？我尝试过在SSR Plus菜单中更改DNS，YouTube无法播放视频，而V2ray也无法播放视频
