### ISSUE TITLE
naiveproxy: bump to 87.0.4280.66-1 编译不过去

### ISSUE THREAD

**Issue by openips** [fw876/helloworld#241]
patch没有加上吧

**Comment by fuqiang03** [comment]
@openips 
我的也没有过去不知道什么原因
![QQ截图20201215170207](https://user-images.githubusercontent.com/26851715/102193658-53e08780-3ef7-11eb-95e1-99f18ecaa03e.png)
![QQ截图20201215170217](https://user-images.githubusercontent.com/26851715/102193663-54791e00-3ef7-11eb-97b8-8418f7ac81d9.png)
