### ISSUE TITLE
最新的修复不能使划分了多个lan接口的情况进行代理

### ISSUE THREAD

**Issue by EnnawYang** [fw876/helloworld#242]
我的机器划分了两个lan，接口`lan(eth0)`和`lan2(eth1-3)`，`lan(eth0)`可以正常进行代理，`lan2(eth1-3`)就不行，https://github.com/fw876/helloworld/pull/233/files# ，今天的这个改动只能获取到第一个lan接口，其他的接口就不能正常使用代理了
![Snipaste_2020-11-28_21-31-57](https://user-images.githubusercontent.com/6705663/100516780-2ab6bc00-31c1-11eb-94b4-f5137374ae7a.png)

**Comment by greekstreet** [comment]
临时方案你可以在 usr/bin/ssr-rules 文件里找到如下行，在后面加你其他 lan 口的规则就行了。
$IPT -I PREROUTING 1 ${IFNAME:+-i $IFNAME} -p tcp $EXT_ARGS $MATCH_SET \
 	-m comment --comment "$TAG" -j SS_SPEC_WAN_AC

**Comment by zxlhhyccc** [comment]
> 临时方案你可以在 usr/bin/ssr-rules 文件里找到如下行，在后面加你其他 lan 口的规则就行了。
> $IPT -I PREROUTING 1 ${IFNAME:+-i $IFNAME} -p tcp $EXT_ARGS $MATCH_SET
> -m comment --comment "$TAG" -j SS_SPEC_WAN_AC

如何加？

**Comment by EnnawYang** [comment]
> > 临时方案你可以在 usr/bin/ssr-rules 文件里找到如下行，在后面加你其他 lan 口的规则就行了。
> > $IPT -I PREROUTING 1 ${IFNAME:+-i $IFNAME} -p tcp $EXT_ARGS $MATCH_SET
> > -m comment --comment "$TAG" -j SS_SPEC_WAN_AC
> 
> 如何加？

dalao 您好像没我这个问题吧？

**Comment by zxlhhyccc** [comment]
> > > 临时方案你可以在 usr/bin/ssr-rules 文件里找到如下行，在后面加你其他 lan 口的规则就行了。
> > > $IPT -I PREROUTING 1 ${IFNAME:+-i $IFNAME} -p tcp $EXT_ARGS $MATCH_SET
> > > -m comment --comment "$TAG" -j SS_SPEC_WAN_AC
> > 
> > 
> > 如何加？
> 
> dalao 您好像没我这个问题吧？

硬路由不就是有几个lan口么？软路由能可以划几个lan口

**Comment by EnnawYang** [comment]
> > > > 临时方案你可以在 usr/bin/ssr-rules 文件里找到如下行，在后面加你其他 lan 口的规则就行了。
> > > > $IPT -I PREROUTING 1 ${IFNAME:+-i $IFNAME} -p tcp $EXT_ARGS $MATCH_SET
> > > > -m comment --comment "$TAG" -j SS_SPEC_WAN_AC
> > > 
> > > 
> > > 如何加？
> > 
> > 
> > dalao 您好像没我这个问题吧？
> 
> 硬路由不就是有几个lan口么？软路由能可以划几个lan口

我就是软路由啊，划了两个lan

**Comment by greekstreet** [comment]
> > 临时方案你可以在 usr/bin/ssr-rules 文件里找到如下行，在后面加你其他 lan 口的规则就行了。
> > $IPT -I PREROUTING 1 ${IFNAME:+-i $IFNAME} -p tcp $EXT_ARGS $MATCH_SET
> > -m comment --comment "$TAG" -j SS_SPEC_WAN_AC
> 
> 如何加？

依葫芦画瓢啊。比如他这个 lan2 有三个接口名称，那就如下：
`
	for addl_iface in $(uci -q get network.lan2.ifname); do
 		$IPT -I PREROUTING 1 ${addl_iface:+-i $addl_iface} -p tcp $EXT_ARGS $MATCH_SET \
 		-m comment --comment "$TAG" -j SS_SPEC_WAN_AC
 	done
`
或者手动一个一个加：
`
$IPT -I PREROUTING 1 -i eth1 -p tcp $EXT_ARGS $MATCH_SET \
 		-m comment --comment "$TAG" -j SS_SPEC_WAN_AC
`
eth2、eth3以此类推。

**Comment by EnnawYang** [comment]
@Mattraks 新的pr我测试过了 正常使用
