### ISSUE TITLE
xtls作者从v2ray独立出来了，搞了个xray

### ISSUE THREAD

**Issue by Lrvineshaw** [fw876/helloworld#243]
https://github.com/XTLS/Xray-core
能不能支持一下~
根据测试来看，效果远超v2ray

**Comment by hcym** [comment]
远超那是鬼话，不过trojan终于可以负载均衡了，也是大喜过望。

**Comment by zxlhhyccc** [comment]
> 远超那是鬼话，不过trojan终于可以负载均衡了，也是大喜过望。

ssrp没有负载均衡的功能吧？

**Comment by hcym** [comment]
haproxy啊，有的，最近trojan不能用负载均衡，也是莫名其妙的事，只能用v2均衡，昨天用pass的编译xray居然可以了，真的大喜过望，速度快慢没什么感觉，不慢就是了。方便性大大提高

**Comment by hackyes** [comment]
NEWIFI3 MT7621 实测，V2RAY的XTLS跑满CPU只能跑50M多，换了XRAY，跑到了70M多，提升真的不少，TROJAN也就跑满50M多。强烈要求把XRAY加进去，我现在是手动把V2RAY替换成XRAY的，配置通用

**Comment by snakwu** [comment]
> NEWIFI3 MT7621 实测，V2RAY的XTLS跑满CPU只能跑50M多，换了XRAY，跑到了70M多，提升真的不少，TROJAN也就跑满50M多。强烈要求把XRAY加进去，我现在是手动把V2RAY替换成XRAY的，配置通用

请问服务端通用吗？我直接在节点中用xray替换v2ray，不正常访问国外

**Comment by hcym** [comment]
TCP和kcp的肯定通用，没什么感觉，就是用trojan协议可以负载均衡了，原版的最近几个月不行，再以前是可以的，也算怪事

**Comment by zxlhhyccc** [comment]
> haproxy

haproxy在ssrp界面没用显示，应该是单独使用吧？！

**Comment by Myoko** [comment]
鸡场用户肯定用不到XRAY！所以对鸡场用户而言这东西没什么用 自建除外

**Comment by yubanmeiqin9048** [comment]
> haproxy啊，有的，最近trojan不能用负载均衡，也是莫名其妙的事，只能用v2均衡，昨天用pass的编译xray居然可以了，真的大喜过望，速度快慢没什么感觉，不慢就是了。方便性大大提高

haproxy可以直接和SSRP配合使用吗？ssrp里没有负载均衡
