### ISSUE TITLE
ssr plus的xray执行路径和passwall冲突

### ISSUE THREAD

**Issue by hetao8980823** [fw876/helloworld#249]
passwall的xray路径是 /usr/bin/xray/xray     ssrlpus的路径是/usr/bin/xray  这样冲突了导致ssrplus的xray无法启动
手动修改 /etc/init.d/shadowsocksr 第118行 
xray) ret="/usr/bin/xray/xray" && [ ! -f "$ret" ] && ret="/usr/bin/xray" ;;

**Comment by AU-Linsanity** [comment]
修改后 xray立刻可以使用,但是 重启路由器...整个ssrplus都无法使用了...

**Comment by hetao8980823** [comment]
> 修改后xray立刻可以使用，但是重新启动路由器...整个ssrplus都无法使用了...

等大佬修复把

**Comment by hetao8980823** [comment]
> 修改后 xray立刻可以使用,但是 重启路由器...整个ssrplus都无法使用了...

直接改成/usr/bin/xray/xray 多加一个/xray

**Comment by AU-Linsanity** [comment]
> > 修改后 xray立刻可以使用,但是 重启路由器...整个ssrplus都无法使用了...
> 
> 直接改成/usr/bin/xray/xray 多加一个/xray

我试过了 也不行 日志显示env: can't execute 'etc/init.d/shadowsocksr' :Exec format error,
覆盖原文件 就正常了 但是xray依旧不行.日志显示找不到,应该就是路径问题

**Comment by hetao8980823** [comment]
已经修复
