### ISSUE TITLE
游戏模式，设置了大陆白名单，王者荣耀还是会走代理udp

### ISSUE THREAD

**Issue by Atroc-0625** [fw876/helloworld#251]
设置了游戏模式，并且是大陆白名单，王者荣耀还是会走代理udp出去，如果把代理的udp关闭，游戏将无法连接，所以可以确定王者荣耀走了udp代理模式。
内核版本5.4.79
helloworld是今天刚刚编译的版本。

**Comment by liuzipeng** [comment]
看来不止我一个人出现这个问题

**Comment by Saxon-Sun** [comment]
我也发现这个问题了 得gwlist才行  大陆白名单会变成全局udp代理

**Comment by zwillhill** [comment]
http也有类似问题，设置白名单，打开tb经常是全球版，换成gfw模式又出不去，不过我的是4月份的版本
