### ISSUE TITLE
xtls节点无法启动，vmess正常

### ISSUE THREAD

**Issue by HoldOnBro** [fw876/helloworld#255]
截止commit `fcd98f50655b79e46d99ffb7ff9f64d7af437bae`

**Comment by guochan2019** [comment]
XRay+VLESS+TCP+XTLS(direct)正常使用中

**Comment by HoldOnBro** [comment]
> XRay+VLESS+TCP+XTLS(direct)正常使用中

编译的最新的commit？

**Comment by hackyes** [comment]
/usr/share/shadowsocksr/genv2config.lua
105行 mux = (server.xtls ~= "1") and {
改成 mux = {

**Comment by HoldOnBro** [comment]
> /usr/share/shadowsocksr/genv2config.lua
> 105行 mux = (server.xtls ~= "1") and {
> 改成 mux = {

感谢，修改后启动成功，运行正常
