### ISSUE TITLE
建议添加自定义dns功能，谢谢！

### ISSUE THREAD

**Issue by snakwu** [fw876/helloworld#259]
建议添加一个自定义dns功能，这样对于有自己搭建dns时可以脱离pdns的依赖，谢谢！

**Comment by Lrvineshaw** [comment]
本来就有这功能

**Comment by snakwu** [comment]
@Lrvineshaw  本机5353作为dns的只限于127.0.0.0：5353，并不是这个功能

**Comment by coolsnowwolf** [comment]
![image](https://user-images.githubusercontent.com/31687149/102091802-42956d80-3e5a-11eb-9c2e-1985fad561d5.png)

**Comment by snakwu** [comment]
@coolsnowwolf L大，我指的是不用通过pdns中转，直接用自己的dns来解释，这样设置pdns一样在运行的，能被过了pdns转发到自定义dns了

**Comment by snakwu** [comment]
可能是我表达得不够清楚，目前的使用自定义dns是通过pdns的tcp转发到自己的dns的，我希望可以增加个直接用自定义dns去解释，不用再通过pdns转发，这样对有自建的dns用户来说，效率应该是最高的，不用通过多一层pdns来中转，谢谢

**Comment by coolsnowwolf** [comment]
这个相当于 PDNSD 中继缓存而已，有缓存效率更好

**Comment by snakwu** [comment]
> 这个相当于 PDNSD 中继缓存而已，有缓存效率更好

既然有了自建dns的缓存，就无需多一层pdns来缓存了吧？两重的缓存比真的用自建的来得直接高效，问题少！
