### ISSUE TITLE
xray

### ISSUE THREAD

**Issue by jackson-lx** [fw876/helloworld#262]
新的代码编译后xray没有了

**Comment by EnnawYang** [comment]
有

**Comment by jackson-lx** [comment]
上一个版本，编译后，在服务器节点---添加---服务器类型里有xray选项，新编译的就没有了，只有vless选项，是不是名称由xray改为了vless，也是调用的xray的核心？

**Comment by jackson-lx** [comment]
我用了上一个版本与新编译的版本，上一个有xray，服务器配置里不勾选“允许不安全链接”也可以用，新编译的版本，不勾选“允许不安全链接”是上不了网的。

**Comment by inbogota** [comment]
附议
最新版本的xray，使用xtls splice，不勾选「允许不安全链接」，依旧启动不了xray，这个bug已经持续两个版本了

**Comment by ak479822** [comment]
![2](https://user-images.githubusercontent.com/63394186/101785590-e8359d80-3b37-11eb-8989-80abac9cabea.jpg)
刚刚用新代码编译完的固件，确实是没有Xray选项，如图！
