### ISSUE TITLE
昨晚编译的最新版SSR无法更新GFW等列表

### ISSUE THREAD

**Issue by ricksuzade-maker** [fw876/helloworld#263]
昨晚更新的最新build，无法更新GFW、国内外、AWS列表，均显示更新失败

**Comment by gsblay** [comment]
应该是你自己的原因，同样最新源码，编译后没问题！

**Comment by jackson-lx** [comment]
编译时在菜单需要选上wget就可以了

**Comment by zxlhhyccc** [comment]
> 编译时在菜单需要选上wget就可以了

最新的wget源码有变化，只编译了wget，你可以通过软链接添加wget-ssl
