### ISSUE TITLE
SSR编译出错

### ISSUE THREAD

**Issue by lgfyxx1** [fw876/helloworld#264]
提示：

* check_data_file_clashes: Package xray wants to install file /workdir/openwrt/build_dir/target-mipsel_24kc_musl/root-ramips/usr/bin/v2ray
	But that file is already provided by package  * v2ray
 * opkg_install_cmd: Cannot install package luci-app-ssr-plus.
 * check_data_file_clashes: Package xray wants to install file /workdir/openwrt/build_dir/target-mipsel_24kc_musl/root-ramips/usr/bin/v2ray
	But that file is already provided by package  * v2ray
 * opkg_install_cmd: Cannot install package xray.
 * check_data_file_clashes: Package xray wants to install file /workdir/openwrt/build_dir/target-mipsel_24kc_musl/root-ramips/usr/bin/v2ray
	But that file is already provided by package  * v2ray
 * opkg_install_cmd: Cannot install package luci-app-passwall.
请问是啥原因，怎么解决呀。

**Comment by Ljzkirito** [comment]
你是不是`CONFIG_XRAY_COMPATIBILITY_MODE`与`v2ray`都选中了

**Comment by Yofo-me** [comment]
> 你是不是`CONFIG_XRAY_COMPATIBILITY_MODE`与`v2ray`都打算了

![image](https://user-images.githubusercontent.com/55388087/101857149-d2f55900-3ba1-11eb-8d71-9394d34dd8b7.png)
这两个不可以同时勾选吗

**Comment by Ljzkirito** [comment]
`CONFIG_XRAY_COMPATIBILITY_MODE`是指这个
![image](https://user-images.githubusercontent.com/66788052/101861204-764a6c00-3baa-11eb-8428-2707fa2d65bc.png)
V2ray Compatibility mode不能与V2ray同时选中

**Comment by jackson-lx** [comment]
我同时编译了ssr与passwall，两个都选了xray与v2ray，也编译成功了的

**Comment by lgfyxx1** [comment]
感谢各位大佬帮忙 成功解决

**Comment by lgfyxx1** [comment]
应该是你用的lede的源码吧？有的别的源码就不行，会报我这个错> 我同时编译了ssr与passwall，两个都选了xray与v2ray，也编译成功了的

**Comment by jackson-lx** [comment]
我使用的是原版openwrt编译，早181的ssr与4-3的passwall同时编译都是可以用的，目前没有什么问题，只是流控没有最新的splice模式选项

lgfyxx1 <notifications@github.com>于2020年12月13日 周日15:59写道：
