### ISSUE TITLE
Naiveproxy 在OpenWrt 透明代理比较本地 Socks代理的性能下降30%左右

### ISSUE THREAD

**Issue by xh116** [fw876/helloworld#268]
个人认为naiveproxy 对仅tcp需求翻墙的人来说是目前最好的方案。（不支持udp）

测试环境:
op 透明代理 ：
_ssrp+ =181-2  / naiveproxy=87.0.4280.66-1-1_

socks 5 代理：
debian 10  +naiveproxy 官方客户端 + switchyomega 插件

测试时间：
凌晨3点40左右（此时网络波动较小）

![op透明代理](https://user-images.githubusercontent.com/37950502/101950256-ebac5000-3c2f-11eb-9e4d-2a594f97025b.gif)
![本地socks代理](https://user-images.githubusercontent.com/37950502/101950267-efd86d80-3c2f-11eb-9ee2-8a9000866033.gif)
<img width="519" alt="op透明代理" src="https://user-images.githubusercontent.com/37950502/101950277-f49d2180-3c2f-11eb-93f1-d87e4b760449.png">
<img width="495" alt="本地socks代理" src="https://user-images.githubusercontent.com/37950502/101950281-f7981200-3c2f-11eb-9290-aed5e57dfedd.png">

ps: 之前的版本86.xxxx测试速度上没有这么大区别.

**Comment by Lrvineshaw** [comment]
xray你不用？

**Comment by xh116** [comment]
> xray你不用？

稳定成熟第一
