### ISSUE TITLE
刚刚编译的，SSR 无法启动

### ISSUE THREAD

**Issue by tone88** [fw876/helloworld#273]
如图：
![photo_2020-12-12_16-32-39](https://user-images.githubusercontent.com/47731895/101979456-3366c200-3c98-11eb-9ceb-0b40257d6501.jpg)

今天最新源码编译，X86 ESXI虚拟机环境

**Comment by Zack0617** [comment]
我也是同样的问题

**Comment by Zack0617** [comment]
我也同样的问题，在官方master下无法启动

**Comment by Sloaix** [comment]
还是没解决，焦头烂额。准备回滚到之前的版本。

**Comment by xxp2277** [comment]
同样无法启动的来说声，和楼主的截图一样的日志。

**Comment by ostrichii** [comment]
+1
