### ISSUE TITLE
v2ray无法启动

### ISSUE THREAD

**Issue by kettean** [fw876/helloworld#275]
错误提示：Main node:Can't find  program, can't start!

**Comment by lanfenglin** [comment]
一样的，不法启动。

**Comment by tone88** [comment]
我也一样的问题。。。普遍现象？

**Comment by Benjamin23333** [comment]
我也是，同时链接添加或者订阅v2ray节点服务器类型都会奇怪的变成ss，你们看下你们的节点详情里面有没有这样的情况

**Comment by xiangfeidexiaohuo** [comment]
Main node:Can't find  program, can't start!

不更新 没事  更新了 就这样

**Comment by pangfeng161** [comment]
这几天更新基本都有bug

**Comment by badcrazy** [comment]
发现v2ray没自动编译进去，自己装一个
