### ISSUE TITLE
不提需求，发现个在公司午饭时间编译新固件的问题

### ISSUE THREAD

**Issue by DanielChen008** [fw876/helloworld#279]
Before ：
协议选择 VLESS，如果是 VLESS + TCP + XTLS的 Server，SSR+里配置顺序就是勾选 TLS ，填 Host，再勾选 XTLS ，选择 FLOW；

After：
协议选择 VLESS，配置里默认有 TLS 和 XTLS ，均为未勾选状态，勾选其中一个，另一个隐藏；那么我现在 Server 端没变，勾选了 XTLS，选好 FLOW ，就连不上了…

这个变化是 Xray 那边的调整么？

**Comment by iotsys** [comment]
我也是这个问题，之前没有用过，不知道配置流程，提交的修复还搞错了，我赶紧去关了。主要原因是现在你配置xtls因为没有能够先钩选tls，所以生成的配置文件中"security"依然还是"none"

**Comment by DanielChen008** [comment]
> 我也是这个问题，之前没有用过，不知道配置流程，提交的修复还搞错了，我赶紧去关了。主要原因是现在你配置xtls因为没有能够先钩选tls，所以生成的配置文件中"security"依然还是"none"

确实就是这样的，这可能是个前端的JS问题，两个 checkbox 变成了二选一…

**Comment by jackson-lx** [comment]
目前就是ssr最早加入xray的版本使用正常，就是没有核心最新的xtls-rprx-splice模式，不知道1.1.3的xray核心的效果
