### ISSUE TITLE
最新的版本XTLS无法使用

### ISSUE THREAD

**Issue by 819-dev** [fw876/helloworld#280]
luci版本：181-3，xray
服务端：XTLS-rprx-direct
luci如果选择xtls-rprx-direct，可以运行，但是无法出墙。改为TLS后正常使用了。181-2无此问题
之前的配置文件内容为：
config servers
        option switch_enable '0'
        option type 'vless'
        option server '123.com'
        option server_port '443'
        option vmess_id 'c21252f7-4f45-4544-9e09-3599acc3333a'
        option vless_encryption 'none'
        option transport 'tcp'
        option tcp_guise 'none'
        option insecure '0'
        option tls '1'
        option tls_host '123.com'
        option xtls '1'
        option vless_flow 'xtls-rprx-direct'
        option local_port '1234'
        option ip '1.2.3.4'
        option alias 'xtls
现在的配置文件为：
config servers
        option switch_enable '0'
        option type 'vless'
        option alias '123'
        option server '123.com'
        option server_port '443'
        option vmess_id 'c21252f7-4f45-4544-9e09-3599acc3333a'
        option vless_encryption 'none'
        option transport 'tcp'
        option tcp_guise 'none'
        option xtls '1'
        option vless_flow 'xtls-rprx-splice'
        option insecure '0'
        option local_port '1234''

**Comment by DanielChen008** [comment]
勤劳的开发者们已收到反馈，似乎已经修改好，等待合并分支ing ，只有再 pull 一次，重新编译一版即可。

**Comment by 819-dev** [comment]
> 勤劳的开发者们已收到反馈，似乎已经修改好，等待合并分支ing ，只有再 pull 一次，重新编译一版即可。

等待合并
