### ISSUE TITLE
运行ss即使搭配了pdnsd还是会有dns污染，ssr和V2RAY就没有污染

### ISSUE THREAD

**Issue by yezhizinever** [fw876/helloworld#281]
这个问题好像存在挺长时间了，请问现在有什么dns设置方案可以解决ss的污染问题吗

**Comment by liuzipeng** [comment]
+1  我也有这个问题 
可通过https://www.google.com.tw/ 来验证
 完全相同的配置文件的ss和ssr 下 
ss解析到了facebook 的服务器 ，无法正常访问、而ssr则能正确的打开google台湾。

**Comment by moralrebuild** [comment]
希望把这个安全漏洞和功能bug给修复了。

**Comment by liuzipeng** [comment]
我也有这个问题 ，希望尽快修复

**Comment by qiang-yu** [comment]
pdnsd 必须走 翻 才能不被污染，单纯一个 pdnsd + tcp 查询 是不足以躲过污染的

**Comment by hplee0120** [comment]
同样遇到，使用同一个节点使用ss部分网站打不开，换用ssr或者v2后正常。
