### ISSUE TITLE
xray 在4.14 4.19 等低版本内核编译时不通过

### ISSUE THREAD

**Issue by lqzhj** [fw876/helloworld#282]
xray 在4.14 4.19 等低版本内核编译时不通过

Building targets
github.com/xtls/go
# github.com/xtls/go
pkg/mod/github.com/xtls/go@v0.0.0-20201118062508-3632bf3b7499/auth.go:29:7: undefined: ecdsa.VerifyASN1
pkg/mod/github.com/xtls/go@v0.0.0-20201118062508-3632bf3b7499/key_schedule.go:177:16: xShared.FillBytes undefined (type *big.Int has no field or method FillBytes)

Cleaning module download cache (golang/go#27455)

make[3]: *** [Makefile:146: /home/lqzhj/R7800/build_dir/target-arm_cortex-a15+neon-vfpv4_musl_eabi/Xray-core-1.1.3/.built] Error 2
make[3]: Leaving directory '/home/lqzhj/R7800/package/lean/xray'
time: package/lean/xray/compile#6.32#1.84#21.78
make[2]: *** [package/Makefile:113: package/lean/xray/compile] Error 2
make[2]: Leaving directory '/home/lqzhj/R7800'
make[1]: *** [package/Makefile:107: /home/lqzhj/R7800/staging_dir/target-arm_cortex-a15+neon-vfpv4_musl_eabi/stamp/.package_compile] Error 2
make[1]: Leaving directory '/home/lqzhj/R7800'
make: *** [/home/lqzhj/R7800/include/toplevel.mk:227：world] 错误 2

**Comment by swxk521** [comment]
编译可以通过
我的是x86 4.14内核

**Comment by Ljzkirito** [comment]
xray&v2ray一直要求使用最新的golang进行编译，建议先检查golang版本，可以在你发的错误日志的上面几行找到，如果小于 v1.15.5，建议升级golang后再试

**Comment by coolsnowwolf** [comment]
golang 版本的问题，晚点我跟进下

**Comment by lqzhj** [comment]
> golang 版本的问题，晚点我跟进下

解决，tks
