### ISSUE TITLE
套CF之后VMESS无法使用

### ISSUE THREAD

**Issue by HoldOnBro** [fw876/helloworld#284]
![image](https://user-images.githubusercontent.com/16101088/102458235-e9f2ea00-407e-11eb-86dd-59d73c582e5d.png)
使用域名地址则能正常使用，其它客户端（passwall、openclash）无此问题

**Comment by fq6** [comment]
套cdn后wshost那里必须填写   现在的逻辑是勾选了tls默认关闭wshost    所以现在出问题了用不了

**Comment by zxlhhyccc** [comment]
> 套cdn后wshost那里必须填写 现在的逻辑是勾选了tls默认关闭wshost 所以现在出问题了用不了 @Mattraks

勾选了tls确实是默认关闭wshost，导致wshost无法使用。。。

**Comment by fq6** [comment]
> > wshost 后套 cdn 后必须填写。现在逻辑是勾选tls关闭wshost，现在出问题了@Mattraks>> 勾选tls 确实是wshost 关闭默认，导致wshost 无法使用。请马特拉克斯修复...>>临时解决方案是将genv2config.lua的292行改为：o:depends（“传输”，“ws”）。>> 另请看pr...> ![图片]（https://user-images.githubusercontent.com/45259624/102511553-e46bc300-40c3-11eb-81e4-d3590353e29a.png）
 这个只保留一个host对于那些非填wshost的有些节点就会用不了   比如垃圾vps套cdn的

**Comment by HoldOnBro** [comment]
事实是只填tls host不填ws host的话，ws+tls的v2节点就套不了cdn了🤷️，群内消息我也看过了，其它插件如passwall等能同时配置两个host的都能正常使用。 @Mattraks
