### ISSUE TITLE
加入XRAY之后，现在要使用V2RAY服务该如何操作？

### ISSUE THREAD

**Issue by Zeezorn** [fw876/helloworld#286]
现在用VMESS和VLESS是不是默认就是启动XRAY了？
目前大多数服务端都是V2RAY，随着版本迭代，客户端用XRAY很容易造成不兼容。
服务端升级成XRAY个别机器还可以，批量改就很麻烦了。
建议增加V2RAY OR XRAY的选项开关。

**Comment by DanielChen008** [comment]
我和你相反，我已经全面过渡到  Xray 了
编译的时候会同时出现 Xray 和 V2ray，你选 V2ray 就是用 v 核心，选 Xray 就是 x 核心；
毕竟上次 L大那边投票，好像大家的意见都是不要合并

**Comment by Zeezorn** [comment]
> 我和你相反，我已经全面过渡到 Xray 了
> 编译的时候会同时出现 Xray 和 V2ray，你选 V2ray 就是用 v 核心，选 Xray 就是 x 核心；
> 毕竟上次 L大那边投票，好像大家的意见都是不要合并

一服一人，迁移成本很低
多人一服，要统一服务端和客户端成本就有点高了。
希望能V2和XRAY并存。

**Comment by microlao** [comment]
现在V2RAY核心和Xray核心是分开的 除非你使用XRAY兼容模式

**Comment by xiaocenter** [comment]
> 编译的时候都勾选，V2RAY核心和Xray核心文件是分开的 除非你使用XRAY兼容模式

希望只保留xray 目前xray 全兼容V2 协议啥的  而且有更好的xtls  对于低配机器很有用   建议只保留xray
