### ISSUE TITLE
新编译版本更新列表错误

### ISSUE THREAD

**Issue by jackson-lx** [fw876/helloworld#287]
![QQ截图20201219000218](https://user-images.githubusercontent.com/61775032/102634954-90c5ac00-418d-11eb-9138-2dc4b109dfc8.jpg)
上一个版本没有问题 ，已经安装了WGET。

**Comment by zxlhhyccc** [comment]
确实是这个情况。。。。

**Comment by coolsnowwolf** [comment]
这个是 trunk 版本的问题
