### ISSUE TITLE
SSR模式下系统日志出现的错误刷屏问题

### ISSUE THREAD

**Issue by jxph1123** [fw876/helloworld#290]
在SSR模式下运行，系统日志接近每5分钟出现如下错误，能正常使用，只是系统日志刷屏了。换了个机场一样出现，以前版本没有这么频繁。Xray模式下没有这个问题。

Sun Dec 20 14:01:36 2020 kern.err /usr/bin/ssr-redir[17855]: server recv: Connection reset by peer
Sun Dec 20 14:06:47 2020 kern.err /usr/bin/ssr-redir[17853]: server recv: Connection reset by peer
Sun Dec 20 14:11:57 2020 kern.err /usr/bin/ssr-redir[17851]: server recv: Connection reset by peer
Sun Dec 20 14:17:07 2020 kern.err /usr/bin/ssr-redir[17855]: server recv: Connection reset by peer
Sun Dec 20 14:22:17 2020 kern.err /usr/bin/ssr-redir[17849]: server recv: Connection reset by peer
Sun Dec 20 14:27:27 2020 kern.err /usr/bin/ssr-redir[17849]: server recv: Connection reset by peer
Sun Dec 20 14:32:37 2020 kern.err /usr/bin/ssr-redir[17849]: server recv: Connection reset by peer
Sun Dec 20 14:37:47 2020 kern.err /usr/bin/ssr-redir[17853]: server recv: Connection reset by peer
Sun Dec 20 14:42:57 2020 kern.err /usr/bin/ssr-redir[17851]: server recv: Connection reset by peer
Sun Dec 20 14:48:07 2020 kern.err /usr/bin/ssr-redir[17855]: server recv: Connection reset by peer
Sun Dec 20 14:53:18 2020 kern.err /usr/bin/ssr-redir[17855]: server recv: Connection reset by peer
Sun Dec 20 14:56:22 2020 kern.err /usr/bin/ssr-redir[17849]: server recv: Connection reset by peer
Sun Dec 20 14:58:28 2020 kern.err /usr/bin/ssr-redir[17851]: server recv: Connection reset by peer
Sun Dec 20 15:03:38 2020 kern.err /usr/bin/ssr-redir[17851]: server recv: Connection reset by peer
Sun Dec 20 15:08:48 2020 kern.err /usr/bin/ssr-redir[17849]: server recv: Connection reset by peer
Sun Dec 20 15:13:59 2020 kern.err /usr/bin/ssr-redir[17849]: server recv: Connection reset by peer
Sun Dec 20 15:19:09 2020 kern.err /usr/bin/ssr-redir[17851]: server recv: Connection reset by peer
Sun Dec 20 15:24:19 2020 kern.err /usr/bin/ssr-redir[17853]: server recv: Connection reset by peer
Sun Dec 20 15:29:29 2020 kern.err /usr/bin/ssr-redir[17855]: server recv: Connection reset by peer
Sun Dec 20 15:34:39 2020 kern.err /usr/bin/ssr-redir[17849]: server recv: Connection reset by peer
Sun Dec 20 15:39:49 2020 kern.err /usr/bin/ssr-redir[17853]: server recv: Connection reset by peer
Sun Dec 20 15:43:03 2020 kern.err /usr/bin/ssr-redir[17855]: server recv: Connection reset by peer
Sun Dec 20 15:43:03 2020 kern.err /usr/bin/ssr-redir[17851]: server recv: Connection reset by peer
Sun Dec 20 15:44:59 2020 kern.err /usr/bin/ssr-redir[17855]: server recv: Connection reset by peer
Sun Dec 20 15:50:09 2020 kern.err /usr/bin/ssr-redir[17851]: server recv: Connection reset by peer
Sun Dec 20 15:55:19 2020 kern.err /usr/bin/ssr-redir[17855]: server recv: Connection reset by peer
Sun Dec 20 16:00:29 2020 kern.err /usr/bin/ssr-redir[17853]: server recv: Connection reset by peer
Sun Dec 20 16:05:39 2020 kern.err /usr/bin/ssr-redir[17849]: server recv: Connection reset by peer
Sun Dec 20 16:10:50 2020 kern.err /usr/bin/ssr-redir[17855]: server recv: Connection reset by peer
Sun Dec 20 16:16:00 2020 kern.err /usr/bin/ssr-redir[17849]: server recv: Connection reset by peer
Sun Dec 20 16:21:10 2020 kern.err /usr/bin/ssr-redir[17851]: server recv: Connection reset by peer
Sun Dec 20 16:26:21 2020 kern.err /usr/bin/ssr-redir[17855]: server recv: Connection reset by peer
Sun Dec 20 16:31:31 2020 kern.err /usr/bin/ssr-redir[17851]: server recv: Connection reset by peer
Sun Dec 20 16:36:41 2020 kern.err /usr/bin/ssr-redir[17855]: server recv: Connection reset by peer
Sun Dec 20 16:41:51 2020 kern.err /usr/bin/ssr-redir[17855]: server recv: Connection reset by peer
Sun Dec 20 16:47:01 2020 kern.err /usr/bin/ssr-redir[17855]: server recv: Connection reset by peer

**Comment by EnnawYang** [comment]
正常  无视即可

**Comment by jxph1123** [comment]
如果这个报警在ShadowSocksR Plus+ 本身自带的日志里，可以无视。现在是在系统日志里面刷屏，导致系统日志里面啥都看不到了，只有这个了。

**Comment by coolsnowwolf** [comment]
节点被干扰，TCP Socket 超时

**Comment by jxph1123** [comment]
谢谢！等他的了，就是奇怪同样的机场，前面的版本都没有这个现象，昨天升版本出现的。

**Comment by xiaobaishu1** [comment]
> 节点被干扰,TCP套接字超时

大雕啥时候加上trojan-go呢？
