### ISSUE TITLE
新版BUG提交，自定义国外域名DNS服务器设置有问题，已修复代码，求大神合并代码，不会git push

### ISSUE THREAD

**Issue by softtip** [fw876/helloworld#292]
自从2020.12.12的comit更新以后，存在如下问题：
opernwrt pppoe上网，在helloworld主界面设置国外域名DNS服务器，如果自定义的DNS服务器跟科学上网主服务器ip不一样，那么一切正常；如果自定义的国外域名服务器IP和科学上网主服务器IP一样，那么科学上网状态中【谷歌】连通性检查 失败，无法科学上网
举例 科学上网服务器A 域名abc.com IP 9.9.9.9，服务器B 域名123.com IP 10.10.10.10
A服务器和B服务器有开启了SSR TROJAN DNS解析服务
如果设置主服务器为A（域名abc.com IP 9.9.9.9）：
不论是SSR还是TROJAN，测试结果如下
自定义的DNS服务器为8.8.4.4，科学上网正常，
自定义的DNS服务器为B服务器的IP 10.10.10.10，科学上网正常
自定义的DNS服务器为A服务器自己的IP 9.9.9.9，科学上网失败

如果设置主服务器为B（域名123.com IP 10.10.10.10）：
不论是SSR还是TROJAN，测试结果如下
自定义的DNS服务器为8.8.4.4，科学上网正常，
自定义的DNS服务器为A服务器的IP 9.9.9.9，科学上网正常
自定义的DNS服务器为B服务器自己的IP 10.10.10.10，科学上网失败

因为奈飞DNS解锁必须用到自定义DNS服务器，而自定义服务器一般是科学上网服务器上架设的，所以没法绕开

原因找到了：
https://github.com/fw876/helloworld/commit/812aac9cee800f1aa635aa05c7e862900931a63c
这个comit有错误
问题文件/etc/init.d/shadowsocksr

并且修改if为elif

应该将
local router_proxy=$(uci_get_by_type access_control router_proxy)
	**if [ -n "$UDP_RELAY_SERVER" ]; then**
		if [ "$kcp_flag" == "0" ]; then
			local type=$(uci_get_by_name $UDP_RELAY_SERVER type)
修改为
local router_proxy=$(uci_get_by_type access_control router_proxy)
	**if [ "$GLOBAL_SERVER" == "$UDP_RELAY_SERVER" -a "$kcp_flag" == "0" ]; then
		ARG_UDP="-u"
	elif [ -n "$UDP_RELAY_SERVER" ]; then**
		if [ "$kcp_flag" == "0" ]; then
			local type=$(uci_get_by_name $UDP_RELAY_SERVER type)

注意上面的elif，黑体部分为修改部分

因为不会git push，求大神合并修复后的代码

**Comment by coolsnowwolf** [comment]
THX

**Comment by xsm1997** [comment]
这样修改反而会带来”**在主服务器和UDP代理服务器配置为同一个时，VLESS甚至所有UDP代理失效**“的问题。

由于这时候ARG_UDP使用了-u的flag，会导致iptables mangle TPROXY的端口使用local_port（也就是TCP的端口），而TCP端口的默认配置为1234，UDP默认为1357，会导致所有需要代理的UDP通信中断。修改TCP代理端口为1357可暂时解决问题。

关于 @softtip 所述问题，按照我的理解，您无法科学上网的原因可能是**服务器IP默认直连**，而通过UDP的DNS查询直连会被污染，导致Google无法连通。实际上我没有搞懂您的commit实际上是在做什么，在我看来，这个commit只是在主服务器和UDP代理服务器是同一个、并且没有开启kcp时，把UDP流量TPROXY到一个**实际不存在**的端口上（如1234）。可能您配置的TCP代理端口也是1357？但这种情况下改和不改又没有很大区别了。由于您的commit是UDP server相关的，所以我默认您是采用UDP的方式查询DNS。但此方式容易被污染，而且容易被攻击。建议使用TCP或DoH的方式进行DNS查询。

@coolsnowwolf lean大，首先建议回滚这个commit。另外，在ssr-rules里面，把所有目标端口为53的流量都进行了直连操作。这个操作是否刻意为之？如果把这条去掉，并加以优化，可能可以解决 @softtip 的问题。最后，希望lean大加强code review。

**Comment by softtip** [comment]
我之所以这么修改是因为12.14日以前以前这里代码就是这么写的，使用正常，后来被12.14那个comit改掉这句代码后不正常了，我只是拼凑下恢复原有的代码，至于故障重现和现象，我描述的很清楚，你可以测试，如果有更好的解决办法当然最好

Kuma <notifications@github.com>于2020年12月22日 周二22:41写道：

**Comment by softtip** [comment]
不是DNS污染问题，而是不修复代码前如果主服务器和DNS为同一个，nslookup
DNS直接不解析，并非被污染，你实际测试一下即可发现，如果方便建议实际测试


Sheng Chen <qwertycs@gmail.com>于2020年12月23日 周三01:48写道：

**Comment by softtip** [comment]
说一千道一万还是812aac9cee800f1aa635aa05c7e862900931a63c这个comit有问题，实质上812aac9cee800f1aa635aa05c7e862900931a63c这个commit如果不存在，一切正常，UDP也好NETFLIX也罢都没问题，没明白它为什么要把udp定义到1357端口去，

**Comment by coolsnowwolf** [comment]
任何软件都会有 Bug，这是个开源的项目，有新功能上线伴随的新Bug也很正常

而且某些功能上，新提交的代码不一定完全了解为何原作者这里要这么写，以为是无关紧要的改动，也很正常

**Comment by xsm1997** [comment]
@coolsnowwolf 也请revert掉我提交的commit，不然VLESS/VMess的udp还是会有问题。
