### ISSUE TITLE
白名单好像有点问题

### ISSUE THREAD

**Issue by WXfeng-boy** [fw876/helloworld#3]
国内网站也走流量了

**Comment by coolsnowwolf** [comment]
具体说下？

**Comment by WXfeng-boy** [comment]
重置了下软路由，可以了，保存配置升级，就是切换到白名单模式，国内也是走的梯子流量

**Comment by fanck0605** [comment]
> 重置了下软路由，可以了。保存配置升级，切换到白名单模式，国内也是走的梯子流量

@coolsnowwolf 我也是遇到同样的问题，使用 `绕过中国大陆IP模式`，在[ip111](http://www.ip111.cn/)里，`从国内测试` 显示国外IP，国内也是走的梯子流量。
