### ISSUE TITLE
无法解析多玩的域名(www.duowan.com)

### ISSUE THREAD

**Issue by r0achnnan9p** [fw876/helloworld#30]
1.关于你要提交的问题
Q：是否搜索了issue (使用 "x" 选择)
[ x] 没有类似的issue

2. 详细叙述
默认编译安装，没开任何其他玩意，只是配置了下PPPOE拨号，然后依然打不开多玩的网站。
查看解析记录，www.duowan.com返回的IP是127.0.0.1。
在软路由本身查询dns也是返回的这个本机地址。

补充一下：
电信分配给我的DNS是222.246.129.80，59.51.78.210。默认情况下，我解析www.duowan.com返回127.0.0.1。如下图：
![image](https://user-images.githubusercontent.com/35089045/81295010-5269f980-90a2-11ea-962c-17125bfd6665.png)
![image](https://user-images.githubusercontent.com/35089045/81295021-59910780-90a2-11ea-90a9-0a4fbb77c7cf.png)

但是我在openwrt-网络-Turbo ACC 网络加速设置-DNS加速中，设置这两个DNS，就能返回正常值。如下图：
![image](https://user-images.githubusercontent.com/35089045/81295056-67df2380-90a2-11ea-9055-afce4fbd3263.png)
![image](https://user-images.githubusercontent.com/35089045/81295227-a96fce80-90a2-11ea-9be1-e574afc3f1b8.png)

这应该是一个的BUG？？？

(2) 路由器型号和固件版本

主机型号 | Intel(R) Atom(TM) CPU D2500 @ 1.86GHz : 2 Core 2 Thread
固件版本 | OpenWrt R20.4.8 / LuCI Master (git-20.088.29068-cebe120)
内核版本 | 4.19.115

(3) 详细日志
没有日志

**Comment by smallprogram** [comment]
你看一下路由的host文件是否被修改了

**Comment by r0achnnan9p** [comment]
> 你看一下路由的host文件是否被修改了，再不行换换DNS

![image](https://user-images.githubusercontent.com/35089045/81293219-868feb00-909f-11ea-83b2-883a6a06df46.png)


查了hosts和ISP获取到的DNS，没发现异常，是不是dnsmasq错误的劫持了这个域名？我测了下duowan.com并没有被指向127.0.0.1。
![image](https://user-images.githubusercontent.com/35089045/81293354-c787ff80-909f-11ea-9365-535a4f6cc7f3.png)

**Comment by smallprogram** [comment]
这不是正常解析了IP了吗。没毛病啊。先到你路由53做DNS解析，再到221.228.107.96

**Comment by r0achnnan9p** [comment]
> 这不是正常解析了IP了吗。没毛病啊。先到你路由53做DNS解析，再到221.228.107.96

默认不开DNS加速就有问题，但不是所有域名都这样，目前就发现了www.duowan.com有问题，但duowan.com又正常。

**Comment by smallprogram** [comment]
DNS加速别开了。他缓存一部分解析结果，你在访问网络时，如果存在缓存结果就不去远程DNS服务器解析了，在本地路由上就返回解析结果。让你打开网站速度变快。但是实测有些时候访问远程DDNS域名会有解析结果IP不对的情况。我基本上都是把DNS关了，在网络，接口中多添加几个自定义的DNS服务器，比如223.5.5.5，114.114.114.114，180.76.76.76再加上运营商提供的DNS。其实效果要比DNS加速强的多。
