### ISSUE TITLE
最新编译，v2节点无法使用

### ISSUE THREAD

**Issue by WYC-2020** [fw876/helloworld#300]
![image](https://user-images.githubusercontent.com/34025388/103206310-8b5b2500-4936-11eb-9302-998cc27740d9.png)
![image](https://user-images.githubusercontent.com/34025388/103206320-90b86f80-4936-11eb-8e1b-5fa4b7c42594.png)

**Comment by 0x5e** [comment]
+1 无有效日志

**Comment by Ausaci** [comment]
我也遇到了相同的问题，主程序181-4版本，V2核心4.34.0，主程序回退到181-1版本可用。
我用的是VLESS协议，在添加node的时候选择TLS就自动把WebSocket Host隐藏了，直接在config文件里添加node也不可用，不知道是不是这方面的锅。
