### ISSUE TITLE
gfw列表模式无效

### ISSUE THREAD

**Issue by iamggs** [fw876/helloworld#301]
4小时之前编译：
1、只能使用【绕过中国大陆ip模式】；
2、【状态】菜单更新【GFW列表】数据库正常，显示：【GFW列表】数据库 5254 条记录；
3、查看/etc/ssr/gfw_list.conf和gfw_base.conf均有内容：
gfw_list.conf部分内容如下：
```
server=/030buy.com/127.0.0.1#5335
ipset=/030buy.com/gfwlist
server=/0rz.tw/127.0.0.1#5335
ipset=/0rz.tw/gfwlist
server=/10.tt/127.0.0.1#5335
ipset=/10.tt/gfwlist
...
```
gfw_base.conf部分内容如下：
```
ipset=/91smartyun.pt/gfwlist
ipset=/adobe.com/gfwlist
ipset=/amazonaws.com/gfwlist
ipset=/ampproject.org/gfwlist
ipset=/apple.news/gfwlist
ipset=/aws.amazon.com/gfwlist
...
```
会是哪儿有问题？

**Comment by iamggs** [comment]
补充说明：
1、GFWList更新URL使用默认：gfwlist/gfwlist；
2、DNS解析使用：pdnsd tcp；
3、国外域名dns使用：8.8.4.4。

**Comment by jackson-lx** [comment]
![11](https://user-images.githubusercontent.com/61775032/103265766-52c85380-49e9-11eb-84a4-611aef8b752d.jpg)
上两个版本还能更新，后面改动了又更新不了

**Comment by iamggs** [comment]
> ![11](https://user-images.githubusercontent.com/61775032/103265766-52c85380-49e9-11eb-84a4-611aef8b752d.jpg)
> 上两个版本还能更新，后面改动了又更新不了

啥时候编译的？最后一般对更新有升级修改。我这儿更新正常，但gfwlist模式下无法FQ。

**Comment by jackson-lx** [comment]
今天刚刚编译的

iamggs <notifications@github.com>于2020年12月29日 周二16:11写道：

**Comment by MrRight-Debug** [comment]
you can find a new list and add it by yourself

**Comment by datout** [comment]
> > ![11](https://user-images.githubusercontent.com/61775032/103265766-52c85380-49e9-11eb-84a4-611aef8b752d.jpg)
> > 上两个版本还能更新，后面改动了又更新不了
> 
> 啥时候编译的？最后一般对更新有升级修改。我这儿更新正常，但gfwlist模式下无法FQ。

我也是可以正常更新列表，但是gfw模式失效，绕过大陆可以，请问如何解决的

**Comment by jackson-lx** [comment]
我不编译第三方coremark插件，问题已经解决

datout <notifications@github.com>于2021年1月31日 周日15:51写道：

**Comment by bosense** [comment]
你好，这个不编译coremark插件就可以解决吗？

**Comment by jackson-lx** [comment]
是的，经过编译了几个固件，发现就是这个插件不支持原版

bosense <notifications@github.com>于2021年2月2日 周二14:19写道：
