### ISSUE TITLE
建议加入 Trojan-go 选择

### ISSUE THREAD

**Issue by qiang-yu** [fw876/helloworld#302]
Trojan-go 是 trojan 的变种，比 trojan 有更大的优势，如下

1. 支持 websocket，可以套 CDN 使用 （Trojan 不能套 cdn ）
2. 支持 udp ，并且实现了 udp 的 FullCone ，这点目前没看到有别的软件能实现 FullCone 的
3. 测试套 CF 之后，晚高峰依然速度不错，之前 v2ray 套 cdn 之后速度特别差 
4. 支持 mux ，多路复用，性能比 Trojan 更好
5. 支持 tcp redirect 和 tproxy，可以透明爬 
6.自带代理功能， 一个端口自适用  socks5 和 http proxy ，不需要用 v2ray 来做 http --> socks5，省事

目前 Trojan-go 唯一的缺点就是 客户端 没有好用的， 希望 helloworld 加上 Trojan-go 的支持，这样就无需别的客户端了

**Comment by hqvv** [comment]
https://github.com/Mattraks/helloworld

**Comment by qiang-yu** [comment]
> https://github.com/Mattraks/helloworld

Preview 分支昨天刚加上了 trojan-go 啊，老铁给力

**Comment by ajiter** [comment]
强烈支持加入trojan-go

**Comment by coolsnowwolf** [comment]
等待测试好更新即可

**Comment by acd889** [comment]
分流不能用

**Comment by mingxiaoyu** [comment]
> 等待测试好更新即可

然后6天过去了
