### ISSUE TITLE
nginx下变更配置导致服务启动不了

### ISSUE THREAD

**Issue by jun129** [fw876/helloworld#304]
nginx下变更配置后，服务无法启动
必须ssh下service shadowsocksr reload才可以

**Comment by jun129** [comment]
![1](https://user-images.githubusercontent.com/40011276/103446698-8511d380-4cbd-11eb-98b9-6be52e81b844.png)
![2](https://user-images.githubusercontent.com/40011276/103446701-86430080-4cbd-11eb-8c29-bbb76f4c92a3.png)

**Comment by jun129** [comment]
service shadowsocksr reload 也会报错

**Comment by 0x5e** [comment]
+1 浏览器直接切换节点，保存&应用无效，service shadowsocksr start/reload 之后启动成功

**Comment by jun129** [comment]
> +1 浏览器直接切换节点，保存&应用无效，service shadowsocksr start/reload 之后启动成功

你是用的nginx还是uhttpd？

**Comment by 0x5e** [comment]
@jun129 nginx

**Comment by jun129** [comment]
用ps看了一下，就是xray没启动
我看了半天/etc/init.d/shadowsocksr，搞不懂。。。
实在不行就只能编译v2ray看看能不能启动。

**Comment by 0x5e** [comment]
@jun129 只编译v2不编译xray也是一样效果，没有变化

**Comment by jun129** [comment]
> @jun129 只编译v2不编译xray也是一样效果，没有变化

我试过查看权限问题，但是nobody的pdnsd都能启动，就不是权限问题。现在在考虑是不是文件大小的问题，不论v2ray还是xray执行文件都8M 其他的都只有几百K，不知道是不是NGINX的UWSGI限制执行文件大小？

**Comment by Rhuua** [comment]
所以老兄你的问题解决没有？
我的是机器重启后才能正确加载配置启动，否则都是加载不出xray的核心，无限重启服务。
看到你的issue，应该也是重启服务才能加载的问题。
固件重新拉取编译很多次了，应该不是编译出错。

**Comment by jun129** [comment]
> 所以老兄你的问题解决没有？
> 我的是机器重启后才能正确加载配置启动，否则都是加载不出xray的核心，无限重启服务。
> 看到你的issue，应该也是重启服务才能加载的问题。
> 固件重新拉取编译很多次了，应该不是编译出错。

目前编译如果用nginx还是一样的。如果修改配置需要用ssh重启ssr，才可以，否则无法加载xray

**Comment by Rhuua** [comment]
> > 所以老兄你的问题解决没有？
> > 我的是机器重启后才能正确加载配置启动，否则都是加载不出xray的核心，无限重启服务。
> > 看到你的issue，应该也是重启服务才能加载的问题。
> > 固件重新拉取编译很多次了，应该不是编译出错。
> 
> 目前编译如果用nginx还是一样的。如果修改配置需要用ssh重启ssr，才可以，否则无法加载xray

感谢答复~那我还是去掉nginx试一下吧。
一开始我是以为那个nginx选项是跟其它组件独立的，打算用它做反向代理的。
现在觉得还是v2重要哈哈~

**Comment by jun129** [comment]
> > > 所以老兄你的问题解决没有？
> > > 我的是机器重启后才能正确加载配置启动，否则都是加载不出xray的核心，无限重启服务。
> > > 看到你的issue，应该也是重启服务才能加载的问题。
> > > 固件重新拉取编译很多次了，应该不是编译出错。
> > 
> > 
> > 目前编译如果用nginx还是一样的。如果修改配置需要用ssh重启ssr，才可以，否则无法加载xray
> 
> 感谢答复..那我还是去掉nginx试一下吧。
> 一开始我是以为那个nginx选项是跟其它组件独立的，打算用它做反向代理的。
> 现在觉得还是v2重要哈哈

你可以尝试下 然后回来报个结果 看是不是nginx的锅

**Comment by Rhuua** [comment]
确实是nginx的问题，取消编译nginx就正常了。
另外，编译nginx的时候似乎还不能关掉管理页面的https，而由于证书问题导致每次登进后台浏览器都会警告一次。。
只能期待后续优化了。。
（题外话：也不知道是校园网问题还是固件问题，更新后似乎还不能上ipv6的网。。明明获取到了地址但就连路由器本身都上不了。。本来更新固件的目的就是解决这个问题。。（题外话就不用特地回复了，我发发牢骚而已））

**Comment by jun129** [comment]
> 确实是nginx的问题，取消编译nginx就正常了。
> 另外，编译nginx的时候似乎还不能关掉管理页面的https，而由于证书问题导致每次登进后台浏览器都会警告一次。。
> 只能期待后续优化了。。
> （题外话：也不知道是校园网问题还是固件问题，更新后似乎还不能上ipv6的网。。明明获取到了地址但就连路由器本身都上不了。。本来更新固件的目的就是解决这个问题。。（题外话就不用特地回复了，我发发牢骚而已））
问题解决了就好，没有遇到过不能关闭https的问题，我个人是建议只编译NGINX或者uhttpd
