### ISSUE TITLE
请教关于SSRP+中的PING延迟

### ISSUE THREAD

**Issue by zhangj3** [fw876/helloworld#306]
大佬们你们好：
请问SSRP+中的PING延迟，ping的是中转服务器的延迟还是谷歌的啊？
感觉像是ping的中转服务器的，如果是的话，有没有计划加入Ping谷歌的功能？
谢谢

**Comment by liuzipeng** [comment]
新版本是tcping延迟 ping谷歌的话占用会不会太高？每个节点都用一下

**Comment by zhangj3** [comment]
> 新版本是tcping延迟 ping谷歌的话占用会不会太高？每个节点都用一下

希望能给个选项，毕竟tcping中转节点没有任何意思啊，ping/tcping 谷歌才能说明梯子状态是OK的
