### ISSUE TITLE
关于SSRPLUS中内置Pdnsd流量转发问题

### ISSUE THREAD

**Issue by meloncn** [fw876/helloworld#308]
你好！
现编译ssrplus于openwrt中，ssrplus组件使用Xray替代V2ray的安装。实际使用过程中发现Pdnsd在使用vmess节点时无法转发dns流量到目标服务器导致终端提示dns没有返回IP。这个仅在使用vmess节点时出现，使用SSR节点则一切正常。请求得到您的帮助！

**Comment by jacob2826** [comment]
@interestingcn 遇到同样问题，请问后续是如何解决的？

**Comment by interestingcn** [comment]
> @interestingcn 遇到同样问题，请问后续是如何解决的？

时间过于久远，我也忘记当时如何操作的了，1.继续使用v2ray而非xray 2.使用passwall
