### ISSUE TITLE
开机自启动失败

### ISSUE THREAD

**Issue by jamesbean08** [fw876/helloworld#309]
最新编译的版本无论重启前是何状态，开机启动必失败，系统启动后手动可以成功启动ssr+。在系统日志有如下失败日志：

Wed Jan  6 19:32:37 2021 daemon.notice procd: /etc/rc.d/S95shadowsocksr: ipset v7.4: Missing second mandatory argument to command add
Wed Jan  6 19:32:37 2021 daemon.notice procd: /etc/rc.d/S95shadowsocksr: Try `ipset help' for more information.
Wed Jan  6 19:32:37 2021 user.err ssr-rules[3141]: Start failed!
Wed Jan  6 19:32:37 2021 daemon.notice procd: /etc/rc.d/S95shadowsocksr: ssr-rules[3141]: Start failed!

ssr+日志如下，启动成功日志为手动启动：
-----------end------------
2021-01-06 19:43:00 Netflix shunt:Xray 1.2.0 (OpenWrt) Custom (go1.15.6 linux/amd64) Started!
2021-01-06 19:42:59 Main node:Xray 1.2.0 (OpenWrt) Custom (go1.15.6 linux/amd64) Started!
----------start------------
-----------end------------
2021-01-06 19:32:39 广告过滤加载完毕。
2021-01-06 19:32:37 未启动主节点，广告过滤正在加载。
2021-01-06 19:32:37 禁止连接的域名加载完毕。
2021-01-06 19:32:37 未启动主节点，禁止连接的域名正在加载。
----------start------------
2021-01-06 19:32:30 boot！

补充一下系统是X64 r20.12.12，ssr+版本181-4，客户端设置是gfw列表模式，开启了广告过滤，主节点和netflix节点是两个vless+xtls

**Comment by jamesbean08** [comment]
目前我在init.d ssr脚本boot部分start前加了sleep 60延迟一分钟启动，重新生成rc.d启动脚本以后ssr+延迟启动正常，系统日志也没有报错。看来是启动顺序的问题。

问题暂时先留着看看有没有更优解。

**Comment by coolsnowwolf** [comment]
会自动守护后再次启动的，无需理会

**Comment by jamesbean08** [comment]
> 会自动守护后再次启动的，无需理会

好的，明白了，谢谢解答。
