### ISSUE TITLE
接口控制问题

### ISSUE THREAD

**Issue by dengchan0416** [fw876/helloworld#311]
我是多WAN口上网，一条电信200M三拨，一条联通500M。在控口控制里已经选了联通WAN口，流量还是走了电信口。
注：WAN联通500M,其它都是电信200M
![Snipaste_2021-01-07_10-05-34](https://user-images.githubusercontent.com/41529838/103843053-132cf600-50d2-11eb-9b17-3e9623533aaa.png)
![2](https://user-images.githubusercontent.com/41529838/103843062-17591380-50d2-11eb-8cb6-daedcd7f3efd.png)

**Comment by coolsnowwolf** [comment]
这个是 source 的选择，而不是 dest 的选择。 内部流量转发多WAN 依赖内置路由表

**Comment by dengchan0416** [comment]
> 这个是 source 的选择，而不是 dest 的选择。 内部流量转发多WAN 依赖内置路由表
@coolsnowwolf 那这个接口控制是用来做什么，有什么功能
