### ISSUE TITLE
点击更新所有服务器订阅节点，会一直叠加

### ISSUE THREAD

**Issue by han3sui** [fw876/helloworld#314]
当点击更新所有服务器订阅节点，节点列表里的节点会越来越多，并且重复。

**Comment by EnnawYang** [comment]
可能和机场有关系，我用的几家只有一家会有这个问题

**Comment by han3sui** [comment]
> 可能和机场有关系，我用的几家只有一家会有这个问题

我看机场多次请求，返回的订阅内容是一样的

**Comment by caicaicai21** [comment]
subscribe.lua 判断的问题，我是自己修改了，用着很舒服。

**Comment by han3sui** [comment]
> subscribe.lua 判断的问题，我是自己修改了，用着很舒服。

大佬提个pr吧

**Comment by caicaicai21** [comment]
> > subscribe.lua 判断的问题，我是自己修改了，用着很舒服。
> 
> 大佬提个pr吧

这个不适合提交pr，因为有可能会影响到别人原有体验，我都是fork一个改的，自己用。

**Comment by han3sui** [comment]
好吧，是因为有些节点走了CDN，感觉这个比对应该改改啊

**Comment by caicaicai21** [comment]
> 好吧，是因为有些节点走了CDN，感觉这个比对应该改改啊

其实你把 subscribe.lua 第339 行
![image](https://user-images.githubusercontent.com/26214093/105620941-30392700-5e3d-11eb-80e1-575842fe59e7.png)
result.hashkey = md5(jsonStringify(result))
改成
result.hashkey = md5(alias)
就好了

**Comment by han3sui** [comment]
> > 好吧，是因为有些节点走了CDN，感觉这个比对应该改改啊
> 
> 其实你把 subscribe.lua 第339 行
> ![image](https://user-images.githubusercontent.com/26214093/105620941-30392700-5e3d-11eb-80e1-575842fe59e7.png)
> result.hashkey = md5(jsonStringify(result))
> 改成
> result.hashkey = md5(alias)
> 就好了

好滴，感谢。
