### ISSUE TITLE
SSR+开启后不定时占满连接数

### ISSUE THREAD

**Issue by tiantanghai** [fw876/helloworld#32]
打开SSR+后，功能正常，正常情况下连接数保持在10%左右，不一定什么时间就会占满系统的连接数，根据观察应该不是缓慢增长上去的，可能很快。犯病时控制台持续输出nf_conntrack: table full, dropping packet。重启SSR+后症状消失。
环境：x86服务器，部署VMWare EXSI6.7 虚拟机跑软路由

**Comment by LitingLin** [comment]
最大连接数调到几百万不就完事了

**Comment by tiantanghai** [comment]
> 最大连接数调到几百万不就完事了

。。。系统的最大值是65535

**Comment by LitingLin** [comment]
/etc/sysctl.d/11-nf-conntrack.conf

net.netfilter.nf_conntrack_max=4194304
net.netfilter.nf_conntrack_buckets=1048576

反正内存大，使劲操

**Comment by kfen** [comment]
和楼主一样有类似问题出现，但我感觉应该还是tcping导致的，你也可以进SSH看下（命令top），这两天我看到也有其他网友反馈类似问题。估计tcpping进程没正常结束掉，卡了N个在那里。

类似问题：https://github.com/coolsnowwolf/lede/issues/4745
