### ISSUE TITLE
ssr-rules 这个文件好像有错误

### ISSUE THREAD

**Issue by icanoncn** [fw876/helloworld#323]
您好，今天测试路由器的时候，好像发现了一个错误：
https://github.com/fw876/helloworld/blob/master/luci-app-ssr-plus/root/usr/bin/ssr-rules
这个文件的第238行

> 		$IPT -A SS_SPEC_TPROXY -p udp -m set --match-set ss_spec_wan_ac dst -j RETURN

$IPT 应该是 小写的 $ipt 吧？

> 		$ipt -A SS_SPEC_TPROXY -p udp -m set --match-set ss_spec_wan_ac dst -j RETURN

如果用大写，运行 ss-rules 会出现如下的错误：
iptables: No chain/target/match by that name.

改成小写就正常了
😂

**Comment by EnnawYang** [comment]
？原来困扰我好几天的问题是这个？ 不过我是开机的时候才会报错

**Comment by icanoncn** [comment]
@EnnawYang 看来问题9天前就已经解决了，只是现在才能看到，我早发了几个小时。
