### ISSUE TITLE
SOCKS5 代理服务端（全局） 不能用

### ISSUE THREAD

**Issue by mingxiaoyu** [fw876/helloworld#327]
在合并Trojan go 之后， 这个功能失效

**Comment by skyeyc** [comment]
main node和socks5 node都用trojan的话，socks5就失效，socks5换成ss和ssr可用

**Comment by mingxiaoyu** [comment]
> main node和socks5 node都用trojan的话，socks5就失效，socks5换成ss和ssr可用

我一直用的是vless . 在 没有上Trojan go 版本之前都好好的。

**Comment by monsterzzzz** [comment]
一直vless，根本没装trojan-go，socks5代理也不能用，这波更新之前是正常的

**Comment by monsterzzzz** [comment]
如果选择vless服务器，socks5全局代理那里根本就不能生成配置文件，估计是哪里错了
如果选择trojan服务器，socks5全局代理那里能生产配置文件，但也是错的，run_type应为client，生成的是nat，这样导致socks5代理无效

**Comment by coolsnowwolf** [comment]
@Mattraks 看一下这个问题？

**Comment by mingxiaoyu** [comment]
@Mattraks 直接替换你修改的文件，貌似没有修复啊

**Comment by monsterzzzz** [comment]
貌似修改后正常

**Comment by mingxiaoyu** [comment]
> 貌似修改后正常

vless  然后socks5 没问题？

**Comment by monsterzzzz** [comment]
全局、udp、socks5选了三个不同的vless服务器，至少全局和socks5没问题，udp没测试
