### ISSUE TITLE
WARNING: No feed for package 'wget-ssl' found

### ISSUE THREAD

**Issue by BOBINIUNIU** [fw876/helloworld#329]
已经把整个openwrt目录删了重新clone还是一样的错误，编译通不过。

**Comment by Archie87** [comment]
同上

**Comment by caicaicai21** [comment]
官方Openwrt吗？wget-ssl是L大的源码里面定义的，官方源是没有的哦。

**Comment by caicaicai21** [comment]
如果是官方OpenWrt，可能需要改一下wget的Makefile呢，或者用L大源码的wget替换官方的。

**Comment by BOBINIUNIU** [comment]
> 如果是官方OpenWrt，可能需要改一下wget的Makefile呢，或者用L大源码的wget替换官方的。

没有用官方的源码，直接clone L大的https://github.com/coolsnowwolf/openwrt稳定版分支的源码

**Comment by schen39** [comment]
把lede里的wget复制过来编译

**Comment by caicaicai21** [comment]
> > 如果是官方OpenWrt，可能需要改一下wget的Makefile呢，或者用L大源码的wget替换官方的。
> 
> 没有用官方的源码，直接clone L大的[https://github.com/coolsnowwolf/openwrt稳定版分支的源码](https://github.com/coolsnowwolf/openwrt%E7%A8%B3%E5%AE%9A%E7%89%88%E5%88%86%E6%94%AF%E7%9A%84%E6%BA%90%E7%A0%81)

按道理来说，应该是有的。没有的话只能手动搞一下了，直接把lede分支里面的wget(/package/lean/wget)复制到openwrt的/package/lean文件夹里面，再试试。

**Comment by BOBINIUNIU** [comment]
> > > 如果是官方OpenWrt，可能需要改一下wget的Makefile呢，或者用L大源码的wget替换官方的。
> > 
> > 
> > 没有用官方的源码，直接clone L大的[https://github.com/coolsnowwolf/openwrt稳定版分支的源码](https://github.com/coolsnowwolf/openwrt%E7%A8%B3%E5%AE%9A%E7%89%88%E5%88%86%E6%94%AF%E7%9A%84%E6%BA%90%E7%A0%81)
> 
> 按道理来说，应该是有的。没有的话只能手动搞一下了，直接把lede分支里面的wget(/package/lean/wget)复制到openwrt的/package/lean文件夹里面，再试试。

感谢回复
果然在 https://github.com/coolsnowwolf/openwrt/tree/lede-17.01/package/lean 目录下没有wget这个文件夹
不知道是不是什么时候删掉了，之前是可以正常编译的

**Comment by BOBINIUNIU** [comment]
问题已解决，将lede分支下package/lean/wget拷贝到openwrt分支的相同目录下即可。关闭问题
