### ISSUE TITLE
昨晚官方op 19.07升级了lua，然后就不能用了，能解决么？

### ISSUE THREAD

**Issue by badcrazy** [fw876/helloworld#33]
ShadowSocksR Plus+ 设置（支持SS/SSR/V2RAY/TROJAN/SOCKS5/TUN）
500 内部服务器错误
对不起，服务器遇到未知错误。
/usr/lib/lua/luci/template.lua:97: Failed to execute template 'cbi/map'.
A runtime error occurred: /usr/lib/lua/luci/template.lua:74: Failed to load template 'shadowsocksr/status'.
Error while parsing template '/usr/lib/lua/luci/view/shadowsocksr/status.htm':
Syntax error in /usr/lib/lua/luci/view/shadowsocksr/status.htm:1: unfinished string near '"

**Comment by Mattraks** [comment]
[LuCI 管理界面: 一些的 GUI 软件包可能出现丢失 “cbi.lua” 的问题，安装 luci-compat 软件包可以修复
](https://openwrt.org/zh/releases/19.07/notes-19.07.2)

**Comment by badcrazy** [comment]
> ci-compat 软件包可以修复

这个包早就装了，之前也是看了你给人家的回复才知道的，之前一直正常使用，昨晚我看很多组件可以更新，就全更新了，结果ssr+就这样了，看了下luci-compat貌似也更新了，现在版本是git-20.128.71839-5366acb-1，难道是这个的锅？
