### ISSUE TITLE
Socks5 节点无法运行

### ISSUE THREAD

**Issue by Atroc-0625** [fw876/helloworld#332]
![image](https://user-images.githubusercontent.com/37469514/105361666-e382ff80-5c34-11eb-90ac-c249f3bbf512.png)

**Comment by fma89** [comment]
我也是一样问题，ssrplus182.7,182.8都这个问题，回退回181.4正常了。
报错信息如下
Thu Jan 21 22:06:31 2021 user.notice dnsmasq: Allowing 127.0.0.0/8 responses
Thu Jan 21 22:06:34 2021 daemon.info dnsmasq[50425]: Connected to system UBus
Thu Jan 21 22:06:59 2021 user.notice shadowsocksr: ssrplus redir tcp error.restart!
Thu Jan 21 22:06:59 2021 user.notice dnsmasq: DNS rebinding protection is active, will discard upstream RFC1918 responses!

**Comment by Atroc-0625** [comment]
是的，感觉加了trojan-go，开始有问题，我用trojan-go,会github无法访问，我之前用trojan没问题，服务端是trojan-go。

**Comment by coolsnowwolf** [comment]
@Mattraks 建议直接用 ipt2socks 代替 redsocks2 吧

**Comment by Mattraks** [comment]
> @Mattraks 建议直接用 ipt2socks 代替 redsocks2 吧

Give up on Tun?

**Comment by swxk521** [comment]
tun没多大用吧

**Comment by EnnawYang** [comment]
刚编译的socks5套娃模式也不能用（

**Comment by Atroc-0625** [comment]
是的，应该还有bug，还没被发现，最近改动有些大。

**Comment by coolsnowwolf** [comment]
@Mattraks 可以考虑用 XRAY 或者 https://github.com/lcdbin/ip2socks-go 这个代替了其实

**Comment by Atroc-0625** [comment]
> 是的，感觉加了trojan-go，开始有问题，我用trojan-go,会github无法访问，我之前用trojan没问题，服务端是trojan-go。

trojan-go无法访问个别网站的这个问题，感觉修复了，但是socks5还是无法正常运行。

**Comment by coolsnowwolf** [comment]
看起来是新版本 ipt2socks 的问题，用了老版本  ipt2socks -alt 替代暂时作为 workaround

**Comment by WXfeng-boy** [comment]
> 看起来是新版本 ipt2socks 的问题，用了老版本 ipt2socks -alt 替代暂时作为 workaround

刚编译了最新版，socks5还是无法启动

**Comment by EnnawYang** [comment]
> > 看起来是新版本 ipt2socks 的问题，用了老版本 ipt2socks -alt 替代暂时作为 workaround
> 
> 刚编译了最新版，socks5还是无法启动

![Snipaste_2021-01-25_18-35-13](https://user-images.githubusercontent.com/6705663/105694584-1599a780-5f3c-11eb-8872-82f1c215f209.png)
可以启动

**Comment by WXfeng-boy** [comment]
> > > 看起来是新版本 ipt2socks 的问题，用了老版本 ipt2socks -alt 替代暂时作为 workaround
> > 
> > 
> > 刚编译了最新版，socks5还是无法启动
> 
> ![Snipaste_2021-01-25_18-35-13](https://user-images.githubusercontent.com/6705663/105694584-1599a780-5f3c-11eb-8872-82f1c215f209.png)
> 可以启动

这个是可以，说的socks5，不是xray里的socks

**Comment by swxk521** [comment]
SSR服务端里sock5也不正常

**Comment by Atroc-0625** [comment]
183-5 还是无法启动socks5

**Comment by swxk521** [comment]
![image](https://user-images.githubusercontent.com/61259428/105800668-3dd3e580-5fd2-11eb-918c-d685ccf70745.png)
sock5启动成功，连不通。。。。
