### ISSUE TITLE
插件更新后，编译失败

### ISSUE THREAD

**Issue by lqhorochi** [fw876/helloworld#336]
Collected errors:
 * satisfy_dependencies_for: Cannot satisfy the following dependencies for luci-app-ssr-plus:
 * 	xray
 * opkg_install_cmd: Cannot install package luci-app-ssr-plus.
make[2]: *** [package/Makefile:68: package/install] Error 255
make[2]: Leaving directory '/home/kenneth/lede'
make[1]: *** [package/Makefile:108: /home/kenneth/lede/staging_dir/target-x86_64_musl/stamp/.package_install] Error 2
make[1]: Leaving directory '/home/kenneth/lede'
make: *** [/home/kenneth/lede/include/toplevel.mk:224：world] 错误 2

**Comment by TwoBall** [comment]
手动下一个1.2.3版本的xray

**Comment by lqhorochi** [comment]
> 手动下一个1.2.3版本的xray

然后怎么操作,具体一点,谢谢

**Comment by TwoBall** [comment]
简单点 make distclean

**Comment by SamoyeHN** [comment]
> 简单点 make distclean

试过了，不管用。

**Comment by SamoyeHN** [comment]
全删了，重来可以！
