### ISSUE TITLE
182-9编译后怎么是这样

### ISSUE THREAD

**Issue by tianiue** [fw876/helloworld#337]
![QQ截图20210124091146](https://user-images.githubusercontent.com/61725402/105618616-5ef6d380-5e24-11eb-8252-70e751878677.jpg)
![QQ截图20210124091156](https://user-images.githubusercontent.com/61725402/105618618-60c09700-5e24-11eb-91bd-ba88a952ab9d.jpg)
![QQ截图20210124091206](https://user-images.githubusercontent.com/61725402/105618619-60c09700-5e24-11eb-9036-f8347dc312f6.jpg)
![QQ截图20210124091215](https://user-images.githubusercontent.com/61725402/105618620-61592d80-5e24-11eb-9e6b-c3c30fa1afc8.jpg)
![QQ截图20210124091224](https://user-images.githubusercontent.com/61725402/105618623-64ecb480-5e24-11eb-983d-b594580bef9f.jpg)

**Comment by EnnawYang** [comment]
配置文件损坏，ssh使用 ` cp /rom/etc/config/shadowsocksr /etc/config/ `恢复默认设置

**Comment by tianiue** [comment]
> 配置文件损坏，ssh使用`cp /rom/etc/config/shadowsocksr /etc/config/`恢复默认设置

操作了还是这样

**Comment by tianiue** [comment]
重新编译一遍正常了
