### ISSUE TITLE
ssrp启用分流时无法访问Netflix

### ISSUE THREAD

**Issue by lonelysoul** [fw876/helloworld#339]
x86固件，固件代码用原版代码不做更改；
主服务器 和 Netflix 分流服务器 选择一样时，Chrome报“检查 www.netflix.com 中是否有拼写错误。”；使用“chrome://net-internals/#dns”清理Chrome的dns缓存后报错依旧。更换Mac浏览器依然无法访问。（ssrp其他参数默认）

将“Netflix 分流服务器 ”停用之后，发现可以访问Netflix。

代码拉去时间约上午10点。

**Comment by lonelysoul** [comment]
重启路由、重启电脑后发现，以上配置无法打开YouTube。
相当于ssrp不生效了。
（启用了IPv6）
目前取消了分流服务器配置使用。

**Comment by zusterben** [comment]
众所周知，这东西和ipv6天生不兼容，开也只能是在服务器和你本地同时支持的情况下才能开，不存在只有一个支持就能开的情况

**Comment by lonelysoul** [comment]
你说的对。初步猜测是ipv6问题。
昨晚已编译不带ipv6的固件，今晚验证。

获取 Outlook for iOS<https://aka.ms/o0ukef>
________________________________
发件人: sterben <notifications@github.com>
发送时间: Monday, January 25, 2021 10:35:46 AM
收件人: fw876/helloworld <helloworld@noreply.github.com>
抄送: lonelysoul <wangchengming@outlook.com>; Author <author@noreply.github.com>
主题: Re: [fw876/helloworld] ssrp启用分流时无法访问Netflix (#339)


众所周知，这东西和ipv6天生不兼容，开也只能是在服务器和你本地同时支持的情况下才能开，不存在只有一个支持就能开的情况

―

**Comment by foxhoundhcm** [comment]
也不一定，我这里的情况是打开ipv6支持，关闭ipv6解析。同一服务器使用vless tcp就不能访问Netflix，使用vmess+ws就可以，不知道是不是xray那边的问题，还没有进一步详细测试。
