### ISSUE TITLE
xray无法自动安装

### ISSUE THREAD

**Issue by lxwq** [fw876/helloworld#340]
./script/feeds install -a时xray没有自动安装进去
要手动在package/feeds/helloworld下建立一个软链接
试了很多方法,
./script/feeds uninstall -a后再安装也不行,
最后只能用ln手动搞了一下,
不知道是哪的问题

**Comment by czxinshui** [comment]
Makefile 'package/feeds/passwall/luci-app-passwall/Makefile' has a dependency on 'xray', which does not exist

**Comment by czxinshui** [comment]
Makefile 'package/feeds/helloworld/luci-app-ssr-plus/Makefile' has a dependency on 'xray', which does not exist

**Comment by cn0068** [comment]
我也遇到同样的问题，请问如何手动解决？

**Comment by xsm1997** [comment]
遇到同样的问题，手动软连接解决。

**Comment by cn0068** [comment]
> 遇到同样的问题，手动软连接解决。

请问如何手动软连接？

**Comment by gsblay** [comment]
./script/feeds clean
./script/feeds update -a
./script/feeds install -a
这样执行以后正常。

**Comment by cn0068** [comment]
> ./script/feeds clean
> ./script/feeds update -a
> ./script/feeds install -a
> 这样执行以后正常。

试过多次，无效

**Comment by gsblay** [comment]
执行命令之前，进入feeds目录，把 helloworld 和 helloworld.tmp 两个文件夹删除。
再执行命令，我这样没问题。

**Comment by yuan-1995** [comment]
rm -rf ./tmp
