### ISSUE TITLE
最新版ssrplus使用不同的tcp和udp节点会导致原tcp节点连接失败

### ISSUE THREAD

**Issue by Hyy2001X** [fw876/helloworld#342]
节点类型 ssr

情况为主服务器与UDP中继服务器不能选择两个不同的节点，会导致状态-谷歌连接失败，无法访问国外网站
UDP中继服务器选择与主服务器相同或禁用时则正常
使用旧版182-5之前的版本则正常

**Comment by coolsnowwolf** [comment]
fix

**Comment by Hyy2001X** [comment]
大雕威武！
