### ISSUE TITLE
编译报错

### ISSUE THREAD

**Issue by chchia** [fw876/helloworld#347]
Collected errors:
 * satisfy_dependencies_for: Cannot satisfy the following dependencies for luci-app-ssr-plus:
 *      xray

今天pull的最新版本。

**Comment by Myoko** [comment]
XRAY 报错了 
其实感觉 V2RAY 可以删除了！现在有 XRAY就够了

**Comment by lqhorochi** [comment]
Updating feed 'helloworld' from 'https://github.com/fw876/helloworld' ...
已经是最新的。
Create index file './feeds/helloworld.index' 
WARNING: Makefile 'package/feeds/helloworld/luci-app-ssr-plus/Makefile' has a dependency on 'xray', which does not exist

Collected errors:
 * satisfy_dependencies_for: Cannot satisfy the following dependencies for luci-app-ssr-plus:
 * 	xray
 * opkg_install_cmd: Cannot install package luci-app-ssr-plus.
make[2]: *** [package/Makefile:68: package/install] Error 255
make[2]: Leaving directory '/home/kenneth/lede'
make[1]: *** [package/Makefile:108: /home/kenneth/lede/staging_dir/target-x86_64_musl/stamp/.package_install] Error 2
make[1]: Leaving directory '/home/kenneth/lede'
make: *** [/home/kenneth/lede/include/toplevel.mk:224：world] 错误 2

报错了....

**Comment by XiaoliChan** [comment]
`https://github.com/coolsnowwolf/lede/issues/6265`

**Comment by getkg** [comment]
> Updating feed 'helloworld' from 'https://github.com/fw876/helloworld' ...
> 已经是最新的。
> Create index file './feeds/helloworld.index'
> WARNING: Makefile 'package/feeds/helloworld/luci-app-ssr-plus/Makefile' has a dependency on 'xray', which does not exist
> 
> Collected errors:
> 
> * satisfy_dependencies_for: Cannot satisfy the following dependencies for luci-app-ssr-plus:
> * xray
> * opkg_install_cmd: Cannot install package luci-app-ssr-plus.
>   make[2]: *** [package/Makefile:68: package/install] Error 255
>   make[2]: Leaving directory '/home/kenneth/lede'
>   make[1]: *** [package/Makefile:108: /home/kenneth/lede/staging_dir/target-x86_64_musl/stamp/.package_install] Error 2
>   make[1]: Leaving directory '/home/kenneth/lede'
>   make: *** [/home/kenneth/lede/include/toplevel.mk:224：world] 错误 2
> 
> 报错了....

我也是这里报错 。访问这个域名就是404

**Comment by getkg** [comment]
Finding targets
go: github.com/ghodss/yaml@v1.0.1-0.20190212211648-25d852aebe32: Get "https://proxy.golang.org/github.com/ghodss/yaml/@v/v1.0.1-0.20190212211648-25d852aebe32.mod": dial tcp 172.217.27.145:443: connect: connection refused

Building targets
go: github.com/ghodss/yaml@v1.0.1-0.20190212211648-25d852aebe32: Get "https://proxy.golang.org/github.com/ghodss/yaml/@v/v1.0.1-0.20190212211648-25d852aebe32.mod": dial tcp 172.217.27.145:443: connect: connection refused

Makefile:142: recipe for target '/home/get/openwrt/lede/build_dir/target-mipsel_24kc_musl/Xray-core-1.2.3/.built' failed
make[3]: *** [/home/get/openwrt/lede/build_dir/target-mipsel_24kc_musl/Xray-core-1.2.3/.built] Error 1
make[3]: Leaving directory '/home/get/openwrt/lede/feeds/helloworld/xray'
time: package/feeds/helloworld/xray/compile#0.27#4.17#88.71
package/Makefile:111: recipe for target 'package/feeds/helloworld/xray/compile' failed
make[2]: *** [package/feeds/helloworld/xray/compile] Error 2
make[2]: Leaving directory '/home/get/openwrt/lede'
package/Makefile:107: recipe for target '/home/get/openwrt/lede/staging_dir/target-mipsel_24kc_musl/stamp/.package_compile' failed
make[1]: *** [/home/get/openwrt/lede/staging_dir/target-mipsel_24kc_musl/stamp/.package_compile] Error 2
make[1]: Leaving directory '/home/get/openwrt/lede'
/home/get/openwrt/lede/include/toplevel.mk:222: recipe for target 'world' failed
