### ISSUE TITLE
选上xray后编译出错!!!

### ISSUE THREAD

**Issue by lqhorochi** [fw876/helloworld#350]
k:~/lede$ ./scripts/feeds update -a && ./scripts/feeds install -a
Updating feed 'packages' from 'https://github.com/coolsnowwolf/packages' ...
已经是最新的。
Create index file './feeds/packages.index' 
Updating feed 'luci' from 'https://github.com/coolsnowwolf/luci' ...
已经是最新的。
Create index file './feeds/luci.index' 
Updating feed 'routing' from 'https://git.openwrt.org/feed/routing.git' ...
已经是最新的。
Create index file './feeds/routing.index' 
Updating feed 'telephony' from 'https://git.openwrt.org/feed/telephony.git' ...
已经是最新的。
Create index file './feeds/telephony.index' 
Updating feed 'freifunk' from 'https://github.com/freifunk/openwrt-packages.git' ...
已经是最新的。
Create index file './feeds/freifunk.index' 
Updating feed 'helloworld' from 'https://github.com/fw876/helloworld' ...
已经是最新的。
Create index file './feeds/helloworld.index' 
**WARNING: Makefile 'package/feeds/helloworld/luci-app-ssr-plus/Makefile' has a dependency on 'xray', which does not exis**t
Installing all packages from feed packages.
Installing all packages from feed luci.
Installing all packages from feed routing.
Installing all packages from feed telephony.
Installing all packages from feed freifunk.
Installing all packages from feed helloworld.

Collected errors:
 * satisfy_dependencies_for: Cannot satisfy the following dependencies for luci-app-ssr-plus:
 * 	xray
 * opkg_install_cmd: Cannot install package luci-app-ssr-plus.
make[2]: *** [package/Makefile:68: package/install] Error 255
make[2]: Leaving directory '/home/kenneth/lede'
make[1]: *** [package/Makefile:108: /home/kenneth/lede/staging_dir/target-x86_64_musl/stamp/.package_install] Error 2
make[1]: Leaving directory '/home/kenneth/lede'
make: *** [/home/kenneth/lede/include/toplevel.mk:224：world] 错误 2

**Comment by lanfenglin** [comment]
package/feeds/helloworld/luci-app-ssr-plus/xray，把这个快捷文件删除后，就可以重新拉取编译了

**Comment by lqhorochi** [comment]
> package/feeds/helloworld/luci-app-ssr-plus/xray，把这个快捷文件删除后，就可以重新拉取编译了

删除一样.最新源码还是有点问题，等修复

**Comment by EnnawYang** [comment]
> > package/feeds/helloworld/luci-app-ssr-plus/xray，把这个快捷文件删除后，就可以重新拉取编译了
> 
> 删除一样.最新源码还是有点问题，等修复

没有问题

**Comment by willisworley** [comment]
```
HEAD is now at 0739ed3... 0.3 Increase connection timeout
Packing checkout...
mv: cannot move '/home/ubuntu/lede/tmp/dl/tcping-0.3-0739ed3b2ab6a344a2e309f004455a2fa0fad1fe.tar.gz' to 'Download/': Not a directory
Makefile:41: recipe for target 'Download/tcping-0.3-0739ed3b2ab6a344a2e309f004455a2fa0fad1fe.tar.gz' failed
make[3]: *** [Download/tcping-0.3-0739ed3b2ab6a344a2e309f004455a2fa0fad1fe.tar.gz] Error 1
make[3]: Leaving directory '/home/ubuntu/lede/package/feeds/helloworld/tcping'
time: package/feeds/helloworld/tcping/compile#0.54#0.08#2.23
package/Makefile:111: recipe for target 'package/feeds/helloworld/tcping/compile' failed
make[2]: *** [package/feeds/helloworld/tcping/compile] Error 2
make[2]: Leaving directory '/home/ubuntu/lede'

```

"Download/" 编译出错问题
