### ISSUE TITLE
Xray与trojan-Go合并之后只要开了MUX就无法上网

### ISSUE THREAD

**Issue by Cathgao** [fw876/helloworld#351]
服务端为最新版Trojan-Go，配置文件也有4路复用的配置。在Windows上使用Trojan-Go的客户端开启MUX也一切正常。但自package里Xray与Trojan合并之后，路由器一旦打开mux就无法上网。
服务器Trojan有如下错误
```
Jan 27 13:36:31 vultrguest trojan-go[105654]: [ERROR] 2021/01/27 13:36:31 github.com/p4gefau1t/trojan-go/proxy.(*Proxy).relayConnLoop.func1.1:proxy.go:66 proxy failed to dial connection | freedom failed to dial v1.mux.cool:**** | dial tcp: lookup v1.mux.cool on 108.61.10.10:53: no such host
Jan 27 13:36:31 vultrguest trojan-go[105654]: [INFO]  2021/01/27 13:36:31 user ********************  from ****:16767 tunneling to v1.mux.cool:**** closed sent: 0 B recv: 0 B
 
```
关闭mux后正常

**Comment by swxk521** [comment]
trojan-go不知道，服务端用xray ，trojan mux开启正常

**Comment by ywyha** [comment]
我使用客户端里的那个trajon-go，结果没有mux选项，然后发现xray里有trajon而且有MUX选项，我尝试使用trajon +tls+ws+mux，我发现连接失败，不知道xray里的trajon支持trajon-go的特性吗……

**Comment by swxk521** [comment]
> 我使用客户端里的那个trajon-go，结果没有mux选项，然后发现xray里有trajon而且有MUX选项，我尝试使用trajon +tls+ws+mux，我发现连接失败，不知道xray里的trajon支持trajon-go的特性吗……

服务端和客户端都用的xray    协议是  trojan+tls+ws+mux，正常  ，用CF套上，virmach速度挺快的。

**Comment by ywyha** [comment]
> > 我使用客户端里的那个trajon-go，结果没有mux选项，然后发现xray里有trajon而且有MUX选项，我尝试使用trajon +tls+ws+mux，我发现连接失败，不知道xray里的trajon支持trajon-go的特性吗……
> 
> 服务端和客户端都用的xray 协议是 trojan+tls+ws+mux，正常
> 
> 在这里感谢大佬们，也感谢xray的作者，整合的不错。

好奇怪，我也是用的那个 V2RAY/XRAY中的trajon+ws+tls+mux ，我咋就连不上网呢？用客户端那个trajon-go就能连上，但是那个不知道为啥怎么没有MUX设置啊……

**Comment by Cathgao** [comment]
> > > 我使用客户端里的那个trajon-go，结果没有mux选项，然后发现xray里有trajon而且有MUX选项，我尝试使用trajon +tls+ws+mux，我发现连接失败，不知道xray里的trajon支持trajon-go的特性吗……
> > 
> > 
> > 服务端和客户端都用的xray 协议是 trojan+tls+ws+mux，正常
> > 在这里感谢大佬们，也感谢xray的作者，整合的不错。
> 
> 好奇怪，我也是用的那个 V2RAY/XRAY中的trajon+ws+tls+mux ，我咋就连不上网呢？用客户端那个trajon-go就能连上，但是那个不知道为啥怎么没有MUX设置啊……

你本地客户端用的哪个Trojan-Go，我用的这个是有MUX选项的。https://github.com/p4gefau1t/trojan-go

**Comment by ywyha** [comment]
> > > > 我使用客户端里的那个trajon-go，结果没有mux选项，然后发现xray里有trajon而且有MUX选项，我尝试使用trajon +tls+ws+mux，我发现连接失败，不知道xray里的trajon支持trajon-go的特性吗……
> > > 
> > > 
> > > 服务端和客户端都用的xray 协议是 trojan+tls+ws+mux，正常
> > > 在这里感谢大佬们，也感谢xray的作者，整合的不错。
> > 
> > 
> > 好奇怪，我也是用的那个 V2RAY/XRAY中的trajon+ws+tls+mux ，我咋就连不上网呢？用客户端那个trajon-go就能连上，但是那个不知道为啥怎么没有MUX设置啊……
> 
> 你本地客户端用的哪个Trojan-Go，我用的这个是有MUX选项的。https://github.com/p4gefau1t/trojan-go

哈喽，我又尝试重新编译刷了一次，我的情况跟楼主一样开了MUX插件连外网就失效，尝试关闭MUX，恢复正常，反复测试都是如此……

**Comment by qiang-yu** [comment]
如果你服务端用的是 trojan-go，那这个插件目前已经取消了 trojan-go，用的是 xray 替代，xray 不兼容你那个服务端

要正确使用，就把你的服务端也换成 xray，然后用这个插件的 xray，走tojan+tls+mux就能成

说白了，xray 不兼容 trojan-go，所以你跑不通

**Comment by Cathgao** [comment]
> 如果你服务端用的是 trojan-go，那这个插件目前已经取消了 trojan-go，用的是 xray 替代，xray 不兼容你那个服务端
> 
> 要正确使用，就把你的服务端也换成 xray，然后用这个插件的 xray，走tojan+tls+mux就能成
> 
> 说白了，xray 不兼容 trojan-go，所以你跑不通

那xray服务端能兼容Trojan和Trojan-Go客户端吗

**Comment by coolsnowwolf** [comment]
目前看起来是 XRAY 的 Trojan-Go 模式的 MUX 支持问题，请上 XRAY 项目主页提出

**Comment by ywyha** [comment]
> 目前看起来是 XRAY 的 Trojan-Go 模式的 MUX 支持问题，请上 XRAY 项目主页提出

明白了，谢谢大雕大佬

**Comment by coolsnowwolf** [comment]
首先做个科普：
trojan是协议，trojan-gfw/trojan-go是trojan的实现，一个c语言编写，一个go语言编写。
xray的trojan支持是从v2ray继承来的，包括mux。ray系的mux公认存在一定问题（不建议使用，还没有修），
trojan-go的是smux，它们是不兼容的。
smux#217 还没有合并进xary主分支，另外xtls也没有合进trojan-go主分支
（人话：目前阶段要用smux请保持客户端服务端为trojan-go，要用xtls请保持客户端服务端为xray）

**Comment by Cathgao** [comment]
> 首先做个科普：
> trojan是协议，trojan-gfw/trojan-go是trojan的实现，一个c语言编写，一个go语言编写。
> xray的trojan支持是从v2ray继承来的，包括mux。ray系的mux公认存在一定问题（不建议使用，还没有修），
> trojan-go的是smux，它们是不兼容的。
> smux#217 还没有合并进xary主分支，另外xtls也没有合进trojan-go主分支
> （人话：目前阶段要用smux请保持客户端服务端为trojan-go，要用xtls请保持客户端服务端为xray）

那请问是否可以先让trojan-go独立于xray为单独的编译选项？服务器因为不止一个人用的原因没法立刻更换为xray。谢谢！

**Comment by qiang-yu** [comment]
> > 首先做个科普：
> > trojan是协议，trojan-gfw/trojan-go是trojan的实现，一个c语言编写，一个go语言编写。
> > xray的trojan支持是从v2ray继承来的，包括mux。ray系的mux公认存在一定问题（不建议使用，还没有修），
> > trojan-go的是smux，它们是不兼容的。
> > smux#217 还没有合并进xary主分支，另外xtls也没有合进trojan-go主分支
> > （人话：目前阶段要用smux请保持客户端服务端为trojan-go，要用xtls请保持客户端服务端为xray）
> 
> 那请问是否可以先让trojan-go独立于xray为单独的编译选项？服务器因为不止一个人用的原因没法立刻更换为xray。谢谢！

新版本已经移除了原生 trojan-go，改用 xray 替代，但是 xray 本身并不完全兼容 trojan-go 的 mux ，所以会出错

你编译老版本，就是编译  trojan-go 被移除之前的那个 commit 版本就可以，我就是这么干的，用老版本，里面是
原生的 trojan-go ，配合服务器原生的 trojan-go，完美

往前翻，找早一点的版本就可以正常运行
git clone https://github.com/fw876/helloworld.git package/helloworld
cd package/helloworld
git reset --hard 477f961 // 用老的版本

自己动手加 mux 吧，我是自己修改的，在 /usr/share/shadowsocksr/gen_config.lua 这个文件里面
这是我今天自己编译手动修改的东西，我也是要用 trojan-go 只能自己动手改了
