### ISSUE TITLE
GFW模式无法正常翻墙

### ISSUE THREAD

**Issue by datout** [fw876/helloworld#355]
(1) 具体问题
编译了多次，SSR PLUS 的GFW模式失效，无法翻墙，gfw列表也能更新。在绕过大陆模式各异正常访问。

(2) 路由器型号和固件版本
A：X86 OpenWrt R21.1.18  

内核版本 | 5.4.92

**Comment by roy63258015** [comment]
关游览器清空下DNS试试看

datout <notifications@github.com> 于2021年1月31日周日 下午6:10写道：

**Comment by datout** [comment]
> 关游览器清空下DNS试试看 datout <notifications@github.com> 于2021年1月31日周日 下午6:10写道：
> […](#)

清除过了 没起作用

**Comment by iamggs** [comment]
给我一样的问题，最近两三个月的编译的版本（包括最新的183-7），线路是v2ray类型，通通不能使用gfw模式，只能绕过大陆或全局。之前也发过issues，没有结果。

**Comment by hcym** [comment]
今天早上编译的正常，没什么事

**Comment by elarkasi** [comment]
同样的问题
固件版本	OpenWrt R21.2.1 / LuCI Master (git-21.035.34289-13f96d1)
内核版本	5.4.0-1028-raspi

**Comment by hcym** [comment]
gfw列表模式肯定没事，大雕的源码用haproxy只能这个，用路由模式卡死，单节点没事

**Comment by Mart11n** [comment]
+1,不知道问题出在哪里
