### ISSUE TITLE
GFW模式下，部分域名不能连接

### ISSUE THREAD

**Issue by bosense** [fw876/helloworld#357]
例如：www.google.com，不能连接，但account.google.com就可以，请问有没有解决办法，或者只能等待更新，谢谢

**Comment by coolsnowwolf** [comment]
IPv6 问题？

**Comment by bosense** [comment]
> IPv6 问题？

没关系吧，绕过中国大陆ip段模式，就没有这个问题

**Comment by datout** [comment]
同样这个问题，gfw模式不能翻墙，绕过大陆没有问题

**Comment by zusterben** [comment]
上游列表被投毒了，无解，只能替换成老的版本就没问题了

**Comment by ricksuzade-maker** [comment]
还有投毒这种骚操作。。。我也是醉了

**Comment by zusterben** [comment]
使用被投毒的列表会表现出各种随机性，以全局代理居多，也可能是全局不代理或者随机一些不代理
直接换半年以前的列表就行，其他不需要动

**Comment by bosense** [comment]
> 使用被投毒的列表会表现出各种随机性，以全局代理居多，也可能是全局不代理或者随机一些不代理
> 直接换半年以前的列表就行，其他不需要动

能单独更换列表吗，如能，怎么更换，谢谢

**Comment by datout** [comment]
> 使用被投毒的列表会表现出各种随机性，以全局代理居多，也可能是全局不代理或者随机一些不代理
> 直接换半年以前的列表就行，其他不需要动

同求 如何替换

**Comment by Benjamin23333** [comment]
我试了一下，没问题啊，可以访问www.google.com啊，用的最新列表

**Comment by bosense** [comment]
> 我试了一下，没问题啊，可以访问www.google.com啊，用的最新列表，gfw模式，备选的其他三个gfw列表也没有问题

关键你什么时间编译的，我前两天编译的

**Comment by Benjamin23333** [comment]
> > 我试了一下，没问题啊，可以访问www.google.com啊，用的最新列表，gfw模式，备选的其他三个gfw列表也没有问题
> 
> 关键你什么时间编译的，我前两天编译的

最新版本啊，一定是最新的commit之后编译的

**Comment by datout** [comment]
> > > 我试了一下，没问题啊，可以访问www.google.com啊，用的最新列表，gfw模式，备选的其他三个gfw列表也没有问题
> > 
> > 
> > 关键你什么时间编译的，我前两天编译的
> 
> 最新版本啊，一定是最新的commit之后编译的，183-5

早上重新 更新了下列表后 居然好了 ，你试试看

**Comment by bosense** [comment]
不好意思，我的是hosts里有google这个域名，删掉好了，奇怪的是，仅在gfw模式下，使用hosts里存储的域名解析地址？

**Comment by Benjamin23333** [comment]
> 不好意思，我的是hosts里有google这个域名，删掉好了，奇怪的是，仅在gfw模式下，使用hosts里存储的域名解析地址？

你在host文件里吧google指向某一个ip之后，当路由器那里，路由器只看到你想访问那个ip，所以google.com的访问就出问题了呗
