### ISSUE TITLE
gfw2ipset.sh：白名单列表生成语句中，能否取消”server=/&/127.0.0.1\n“

### ISSUE THREAD

**Issue by hue715** [fw876/helloworld#359]
**非常感谢各位大佬的工作，在使用本项目中，我有一些疑问：**
- dnsmasq默认使用lan中设置的dns，在gfw2ipset.sh生成白名单列表后，再设置白名单的dns server为本地是否多余？

- 另外如果dnsmasq的dns端口改为非53，且白名单的dns server设为127.0.0.1，则所有白名单中的域名都无法解析。

因此能否取消gfw2ipset.sh白名单设置中的”server=\/&\/127.0.0.1\n“
### gfw2ipset.sh白名单设置：
![屏幕截图 2021-02-02 000458](https://user-images.githubusercontent.com/22958922/106545651-cad3ed00-6544-11eb-88ca-3b59f322def2.png)

**Comment by dongjuanyong** [comment]
按标准这种情况应该用“#”

> The special server address '#' means, "use the standard servers", so --server=/google.com/1.2.3.4 --server=/www.google.com/# will send queries for *.google.com to 1.2.3.4, except *www.google.com which will be forwarded as usual.

**Comment by hue715** [comment]
> 按标准这种情况应该用“#”
> 
> > The special server address '#' means, "use the standard servers", so --server=/google.com/1.2.3.4 --server=/www.google.com/# will send queries for *.google.com to 1.2.3.4, except *www.google.com which will be forwarded as usual.

这说的应该是解析时的例外情况。
我想说的是ssr-plus白名单中的域名本来就应该用本地的，或者运营商提供的dns解析（dnsmasq应该可以自动设置的），应该不用“server=”再指定一个解析服务器的。

**Comment by dongjuanyong** [comment]
> "use the standard servers"

这不就是走系统resolv的意思么，你看明白没

**Comment by hue715** [comment]
> > "use the standard servers"
> 
> 这不就是走系统resolv的意思么，你看明白没

以下是Google机翻，#表示：除了www.google.com使用标准服务器（也就是resolv.conf.auto文件中的本地DNS），其余*.google.com都使用1.2.3.4解析
![image](https://user-images.githubusercontent.com/22958922/106571829-9d9e3380-6572-11eb-9af8-a6ec39ee0f10.png)

**Comment by dongjuanyong** [comment]
我给你举个例子：
gstatic.com是被墙的没错吧，于是你把它的解析指向其他的dns
但connectivitycheck.gstatic.com可以直连，为了效率，你应该把它的解析指向本机resolv
你要是不设白名单自然也可以，但gfwlist就是这么设计的，里面@@开头的就是能够直连的域名，把这先放在白名单中合情合理

**Comment by hue715** [comment]
我自行修改gfw2ipset.sh文件内容，关闭该issue
