### ISSUE TITLE
trojan-Go配置好不能启动

### ISSUE THREAD

**Issue by luii2020** [fw876/helloworld#361]
trojan-Go配置好后启动ssr＋不生效
TCP透明代理 未运行
DNS 防污染服务 运行
ShadowsocksR Plus+ 未运行
希望修复这个bug，另外既然保留trojan-Go就应该添加mux

**Comment by qiang-yu** [comment]
1. 往前翻，找早一点的版本就可以正常运行 

git clone https://github.com/fw876/helloworld.git package/helloworld
cd package/helloworld
git reset --hard  477f96149d01ac893899bc3c545aa01fb8b4344d   // 用老的版本

2. 自己动手加 mux 吧，我是自己修改的，在 /usr/share/shadowsocksr/gen_config.lua 这个文件里面

这是我今天自己编译手动修改的东西，我也是要用 trojan-go 只能自动改了

**Comment by coolsnowwolf** [comment]
首先做个科普：
trojan是协议，trojan-gfw/trojan-go是trojan的实现，一个c语言编写，一个go语言编写。
xray的trojan支持是从v2ray继承来的，包括mux。ray系的mux公认存在一定问题（不建议使用，还没有修），
trojan-go的是smux，它们是不兼容的。
smux#217 还没有合并进xary主分支，另外xtls也没有合进trojan-go主分支
（人话：目前阶段要用smux请保持客户端服务端为trojan-go，要用xtls请保持客户端服务端为xray）

**Comment by qiang-yu** [comment]
> 首先做个科普：
> trojan是协议，trojan-gfw/trojan-go是trojan的实现，一个c语言编写，一个go语言编写。
> xray的trojan支持是从v2ray继承来的，包括mux。ray系的mux公认存在一定问题（不建议使用，还没有修），
> trojan-go的是smux，它们是不兼容的。
> smux#217 还没有合并进xary主分支，另外xtls也没有合进trojan-go主分支
> （人话：目前阶段要用smux请保持客户端服务端为trojan-go，要用xtls请保持客户端服务端为xray）

L大，现在 shadowsocks-plus 会不会太臃肿了，里面支持的协议太多，需要兼容的地方太多，不同的实现有差异
要兼容所有协议本身会比较困难

要不要考虑拆分一下，分成几个不同的包，让个人自己按照需求编译对应的包，这样会不会更好？

或者做成插件方式

比如
1. 公用部分，实现 tcp\udp 的 redirect ，以及 local 的 socket5 代理 （iptsocks 实现？）
2. 多个插件，分别是不同协议，让需要的人自己编译对应插件

这样会不会更好一些？

**Comment by Ai1954** [comment]
trojan-go希望添加一个二次加密

**Comment by hxlls** [comment]
> > 首先做个科普：
> > trojan是协议，trojan-gfw/trojan-go是trojan的实现，一个c语言编写，一个go语言编写。
> > xray的trojan支持是从v2ray继承来的，包括mux。ray系的mux公认存在一定问题（不建议使用，还没有修），
> > trojan-go的是smux，它们是不兼容的。
> > smux#217 还没有合并进xary主分支，另外xtls也没有合进trojan-go主分支
> > （人话：目前阶段要用smux请保持客户端服务端为trojan-go，要用xtls请保持客户端服务端为xray）
> 
> L大，现在 shadowsocks-plus 会不会太臃肿了，里面支持的协议太多，需要兼容的地方太多，不同的实现有差异
> 要兼容所有协议本身会比较困难
> 
> 要不要考虑拆分一下，分成几个不同的包，让个人自己按照需求编译对应的包，这样会不会更好？
> 
> 或者做成插件方式
> 
> 比如
> 
> 1. 公用部分，实现 tcp\udp 的 redirect ，以及 local 的 socket5 代理 （iptsocks 实现？）
> 2. 多个插件，分别是不同协议，让需要的人自己编译对应插件
> 
> 这样会不会更好一些？

编译时候本来就有可选，在大项里面有几个小项，默认只选了其中几个，如果自己有特殊需求，勾选对应的就不行了？

**Comment by qiang-yu** [comment]
> > > 首先做个科普：
> > > trojan是协议，trojan-gfw/trojan-go是trojan的实现，一个c语言编写，一个go语言编写。
> > > xray的trojan支持是从v2ray继承来的，包括mux。ray系的mux公认存在一定问题（不建议使用，还没有修），
> > > trojan-go的是smux，它们是不兼容的。
> > > smux#217 还没有合并进xary主分支，另外xtls也没有合进trojan-go主分支
> > > （人话：目前阶段要用smux请保持客户端服务端为trojan-go，要用xtls请保持客户端服务端为xray）
> > 
> > 
> > L大，现在 shadowsocks-plus 会不会太臃肿了，里面支持的协议太多，需要兼容的地方太多，不同的实现有差异
> > 要兼容所有协议本身会比较困难
> > 要不要考虑拆分一下，分成几个不同的包，让个人自己按照需求编译对应的包，这样会不会更好？
> > 或者做成插件方式
> > 比如
> > 
> > 1. 公用部分，实现 tcp\udp 的 redirect ，以及 local 的 socket5 代理 （iptsocks 实现？）
> > 2. 多个插件，分别是不同协议，让需要的人自己编译对应插件
> > 
> > 这样会不会更好一些？
> 
> 编译时候本来就有可选，在大项里面有几个小项，默认只选了其中几个，如果自己有特殊需求，勾选对应的就不行了？

你可以试试，不勾选某个模块，然后编译好的程序依然有选项，但是没有对应的程序，所以就会出现，明明设置了，但是根本起不来

比如，你编译不选 v2ray 模块，但是，你最终的程序配置的时候依然有 v2ray 的选项，只是程序没带 v2ctl v2ray 这两个程序，结果就是，配置了，但是起不来

**Comment by luii2020** [comment]
> 首先做个科普：
> trojan是协议，trojan-gfw/trojan-go是trojan的实现，一个c语言编写，一个go语言编写。
> xray的trojan支持是从v2ray继承来的，包括mux。ray系的mux公认存在一定问题（不建议使用，还没有修），
> trojan-go的是smux，它们是不兼容的。
> smux#217 还没有合并进xary主分支，另外xtls也没有合进trojan-go主分支
> （人话：目前阶段要用smux请保持客户端服务端为trojan-go，要用xtls请保持客户端服务端为xray）

好吧，mux就算了，但是我编译最新的版本trojan-go还是不能启动。我复制日志给L大你看看，用xray的trojan协议当然无问题，但是希望修复下bug，二楼的方法是回滚旧版本，是可行的，但希望能处理好新版本bug

2021-02-05 19:50:17: -----------end------------
2021-02-05 19:50:16: Main node:Xray 1.2.4 (OpenWrt) Custom (go1.15.7 linux/amd64) Started!
2021-02-05 19:50:16: ----------start------------
2021-02-05 19:50:09: -----------end------------
2021-02-05 19:50:07: Main node:Trojan-Go 0.8.2 Started!
2021-02-05 19:50:07: ----------start------------
2021-02-05 19:50:07: ssrplus redir tcp error.restart!
2021-02-05 19:49:37: -----------end------------
2021-02-05 19:49:36: Main node:Trojan-Go 0.8.2 Started!
2021-02-05 19:49:35: ----------start------------
2021-02-05 19:49:29: -----------end------------
2021-02-05 19:49:29: 禁止连接的域名加载完毕。
2021-02-05 19:49:29: 未启动主节点，禁止连接的域名正在加载。
2021-02-05 19:49:29: ----------start------------
2020-04-25 23:48:53: -----------end------------
2020-04-25 23:48:53: 禁止连接的域名加载完毕。
2020-04-25 23:48:53: 未启动主节点，禁止连接的域名正在加载。
2020-04-25 23:48:53: ----------start------------
2020-04-25 23:48:53: boot！

**Comment by GreatMichaelFu** [comment]
这个issue修复了没有？

**Comment by qiang-yu** [comment]
> 这个issue修复了没有？

不会修复的，只有用 trojan-go 的人才认为这是 bug，主流意见是认为应该淘汰 trojan-go 用 xray 取代

所以，用 trojan-go 的属于小众人群，自己用就自己解决，或者，也可以考虑放弃 trojan-go 改用 xray ，跟上主流意见

**Comment by Cathgao** [comment]
> > 这个issue修复了没有？
> 
> 不会修复的，只有用 trojan-go 的人才认为这是 bug，主流意见是认为应该淘汰 trojan-go 用 xray 取代
> 
> 所以，用 trojan-go 的属于小众人群，自己用就自己解决，或者，也可以考虑放弃 trojan-go 改用 xray ，跟上主流意见

我没有在哪里看到您所说的“主流意见”是淘汰trojan-Go，而我在Xray-core的项目下看到的“公认意见”是ray系的mux都有问题

**Comment by luii2020** [comment]
ssr+有trojan-go选项，却不能使用trojan-go，不是bug是什么？要不就完全删去，要不就修复bug，这是项目应该有的态度，不能因为xray可以实现trojan而放弃修复bug

**Comment by 1715173329** [comment]
> 你编译不选 v2ray 模块，但是，你最终的程序配置的时候依然有 v2ray 的选项

@qiang-yu 不选就不会显示，3q2x
btw，v2ray 已被 xray 完全替代

**Comment by 1715173329** [comment]
@luii2020 有个东西叫做 Deprecated，已弃用

**Comment by 1715173329** [comment]
> 而我在Xray-core的项目下看到的“公认意见”是ray系的mux都有问题

@Cathgao Trojan-Go 的 smux 为独立实现，与 v2ray / xray 的 mux 无半点关系

**Comment by Cathgao** [comment]
> > 而我在Xray-core的项目下看到的“公认意见”是ray系的mux都有问题
> 
> @Cathgao Trojan-Go 的 smux 为独立实现，与 v2ray / xray 的 mux 无半点关系

你理解错了我的意思。我的意思是既然ray系的mux本身有问题，而xray又不能完整支持trojan-Go的smux特性，就不应该用xray完全替代xray-Go，应该保留trojan-Go的独立选项可以选择

**Comment by 1715173329** [comment]
> 而xray又不能完整支持trojan-Go的smux特性

XRay Trojan + XTLS 的性能更加优异，并有 FullConeNAT 支持
并且，在 XRay 的实现中已经包括了 Trojan-GFW 完整功能和 Trojan-Go 绝大部分功能
在当初讨论时（或许您当时并未在现场），最后得出的结果是弃用 Trojan-Go 并使用 XRay 取代之
我们并不想在源码中单独为此保留一个重复率如此高的软件

或许您可以加入 XRay Trojan

**Comment by qiang-yu** [comment]
> ssr+有trojan-go选项，却不能使用trojan-go，不是bug是什么？要不就完全删去，要不就修复bug，这是项目应该有的态度，不能因为xray可以实现trojan而放弃修复bug

放心，后面会完全删去的，目前还没来得及删而已

**Comment by luii2020** [comment]
> > ssr+有trojan-go选项，却不能使用trojan-go，不是bug是什么？要不就完全删去，要不就修复bug，这是项目应该有的态度，不能因为xray可以实现trojan而放弃修复bug
> 
> 放心，后面会完全删去的，目前还没来得及删而已
好吧，问句是不是gcp不能装trojan？提示挖矿禁账号，Trojan-go也不敢装，另外xray一键脚本提供者也不建议安装在gcp，虽然我装了xray+tcp＋xtls+web，正在用没出现问题，希望有人能解惑

**Comment by Cathgao** [comment]
> > 而xray又不能完整支持trojan-Go的smux特性
> 
> XRay Trojan + XTLS 的性能更加优异，并有 FullConeNAT 支持
> 并且，在 XRay 的实现中已经包括了 Trojan-GFW 完整功能和 Trojan-Go 绝大部分功能
> 在当初讨论时（或许您当时并未在现场），最后得出的结果是弃用 Trojan-Go 并使用 XRay 取代之
> 我们并不想在源码中单独为此保留一个重复率如此高的软件
> 
> 或许您可以加入 XRay Trojan

谢谢解答。不过同一服务器的其他客户端都是用的trojan-Go并开启mux，我不知道更换服务端之后会不会造成其他客户端上网失败。而且我看xray-core那边说有计划修复mux和加入smux支持，我先观察下吧

**Comment by swxk521** [comment]
trojan代码删了算了，用XRAY就行了。
