### ISSUE TITLE
SSR Plus中xray/v2ray的mkcp配置缺少seed混淆密码项

### ISSUE THREAD

**Issue by ymcoming** [fw876/helloworld#369]
这个混淆密码seed，出在v2ray 4.24.2，参见https://github.com/v2ray/v2ray-core/releases/tag/v4.24.2
xray也继承了此特性，希望能加上，谢谢！

---------------------------------------------
seed: string

v4.24.2+，可选的混淆密码，使用 AES-128-GCM 算法混淆流量数据，客户端和服务端需要保持一致，启用后会输出"NewAEADAESGCMBasedOnSeed Used"到命令行。本混淆机制不能用于保证通信内容的安全，但可能可以对抗部分封锁，在开发者测试环境下开启此设置后没有出现原版未混淆版本的封端口现象。

**Comment by ymcoming** [comment]
补充：看了下代码，好像2020年11月时，已经加上。可能是最近改成xray后，没有在添加节点的配置上显示出来。手动去路由器改文件，增加一行	option seed 'passwordxxx'，就能正常运行。

请修改一下，让其能在添加节点的表内显示，方便填入。谢谢！

**Comment by swxk521** [comment]
支持一下

**Comment by hsb888** [comment]
> 补充：看了下代码，好像2020年11月时，已经加上。可能是最近改成xray后，没有在添加节点的配置上显示出来。手动去路由器改文件，增加一行 option seed 'passwordxxx'，就能正常运行。
> 
> 请修改一下，让其能在添加节点的表内显示，方便填入。谢谢！

请问节点文件位置在哪啊
