### ISSUE TITLE
建议能否增加个自动选择最快节点功能

### ISSUE THREAD

**Issue by rshi0212** [fw876/helloworld#370]
建议能否增加个自动选择最快节点功能

**Comment by XiaoliChan** [comment]
凡事没有最字

**Comment by hiboy007** [comment]
可以添加订阅节点智能排序功能，每隔自定义时间与服务器测速一次，然后根据速度对节点进行排序。

**Comment by 1715173329** [comment]
下次要不要内置一个“最”快的节点？

**Comment by rshi0212** [comment]
是的，最好有自定义排序功能，可以选择按节点名称排序，按测速排序，按节点类型排序，现在机场节点一旦发生变化，自动更新后，顺序就乱了。

在 2021/2/9 19:00, hiboy007 写道:

**Comment by hxlls** [comment]
什么叫最快？ping 低的速度不一定快，速度上限高的不一定ping 低，哪来的最？提需求也要自己先考虑下这些把

**Comment by wutong-C** [comment]
额...
