### ISSUE TITLE
是否可能使路由器本身不走代理？

### ISSUE THREAD

**Issue by whc2001** [fw876/helloworld#371]
如题，路由器上需要跑脚本要对比WAN口的IP和通过WebAPI获取的公网IP，但插件启动后会导致路由器本身发出的请求通过代理，进而导致WebAPI获取的IP与WAN口的IP不一致（获取到的是代理服务器的IP）。已经尝试开内网主机模式并将LAN口本身加入黑名单，但没有作用：

![QQ图片20210208083029](https://user-images.githubusercontent.com/16266909/107164034-ee38e500-69e7-11eb-97e5-a0ac61a45172.png)

![屏幕截图 2021-02-08 084054](https://user-images.githubusercontent.com/16266909/107164282-605df980-69e9-11eb-85c1-82ce67e56349.png)

**Comment by xxp2277** [comment]
将ipv4.icanhazip.com加入访问控制中的“不走代理的域名”中。

**Comment by whc2001** [comment]
谢谢，目前的情况这样够用了
