### ISSUE TITLE
编译出错

### ISSUE THREAD

**Issue by lqhorochi** [fw876/helloworld#376]
Collected errors:
 * check_data_file_clashes: Package xray wants to install file /home/kenneth/lede/build_dir/target-x86_64_musl/root-x86/usr/bin/xray
	But that file is already provided by package  * xray-core
 * opkg_install_cmd: Cannot install package xray.
make[2]: *** [package/Makefile:68: package/install] Error 255
make[2]: Leaving directory '/home/kenneth/lede'
make[1]: *** [package/Makefile:108: /home/kenneth/lede/staging_dir/target-x86_64_musl/stamp/.package_install] Error 2
make[1]: Leaving directory '/home/kenneth/lede'
make: *** [/home/kenneth/lede/include/toplevel.mk:224：world] 错误 2

**Comment by leonliao78** [comment]
最近的lean源码openwrt编译时如果勾上xray内核必然失败，大家有没有遇到这问题？准确地说，是xray-core升级到1.3.0版以后出现的，之前的1.2.4版没这个问题。

**Comment by 1715173329** [comment]
不要混合使用源码，否则请自行处理依赖问题。
