### ISSUE TITLE
XRAY 加速游戏 NAT类型严格 想问大佬怎么解决

### ISSUE THREAD

**Issue by yl1677866238** [fw876/helloworld#377]

**Comment by sxx1314** [comment]
Xray-core 现支持 FullCone 和 Symmetric 两种模式，而 VLESS、VMess、Mux 暂不支持 FullCone，需要 Symmetric 模式

**Comment by hackyes** [comment]
> Xray-core现有支持FullCone和Symmetric两种模式，而VLESS，VMess，Mux暂不支持FullCone，需要对称模式

1.3 已经支持了
VLESS & VMess & Mux UDP FullCone NAT
服务端也要换成1.3

**Comment by yl1677866238** [comment]
1.3版本不是没发布吗





发自我的iPhone


------------------ 原始邮件 ------------------
发件人: hackyes <notifications@github.com&gt;
发送时间: 2021年2月13日 17:12
收件人: fw876/helloworld <helloworld@noreply.github.com&gt;
抄送: yl1677866238 <1677866238@qq.com&gt;, Author <author@noreply.github.com&gt;
主题: 回复：[fw876/helloworld] XRAY 加速游戏 NAT类型严格 想问大佬怎么解决 (#377)





  
Xray-core现有支持FullCone和Symmetric两种模式，而VLESS，VMess，Mux暂不支持FullCone，需要对称模式
  
1.3 已经支持了
 VLESS &amp; VMess &amp; Mux UDP FullCone NAT
 服务端也要换成1.3
