### ISSUE TITLE
可否通过MAC地址来做访问控制

### ISSUE THREAD

**Issue by jh0072110** [fw876/helloworld#38]
我的设备内网IP地址时不时…跳来跳去的，如果能添加通过MAC地址来做访问控制，会容易许多，感激不尽

**Comment by EnnawYang** [comment]
先固定下ip不好吗

**Comment by jh0072110** [comment]
> 先固定下ip不好吗

emmm也不是所有设备都能主动设置固定IP的…吧？

**Comment by coolsnowwolf** [comment]
OP 里面， DHCP 地址和 MAC 地址强相关，重装后依然是固定的

**Comment by jh0072110** [comment]
> OP 里面， DHCP 地址和 MAC 地址强相关，重装后依然是固定的

那我这个倒霉下载宝怎么不停的跳IP…看起来该换了……

**Comment by smallprogram** [comment]
> > OP 里面， DHCP 地址和 MAC 地址强相关，重装后依然是固定的
> 
> 那我这个倒霉下载宝怎么不停的跳IP…看起来该换了……

做静态DHCP把，虽然我也很赞同你的提议
