### ISSUE TITLE
重新编译了几次才找到问题所在

### ISSUE THREAD

**Issue by DanielChen008** [fw876/helloworld#39]
v2ray 节点配置默认把 Camouflage Type 选成了HTTP，我服务器端又没这个配置，导致我按照往常添加结点配置后死活不能用，以前都正常，是最近更新成默认 HTTP 了么？搞了一晚才发现把 Camouflage Type 选成“无”即可…

就此提问：Camouflage Type  是做什么用的？

**Comment by demo0102** [comment]
同一个问题，感谢

**Comment by coolsnowwolf** [comment]
应该是最近的commit 群友改的

**Comment by Mattraks** [comment]
之前配置根本没使用Camouflage Type所以没有问题,
现在配置兼容了http伪装,之前版本Camouflage Type默认http,是遗留问题
Fixed #17
