### ISSUE TITLE
hello world运行trojan后，PDNSD指向ADGUARD HOME作为DNS，AD后台看到能成功解析DNS，但youtube播放黑屏，一直转圈。

### ISSUE THREAD

**Issue by lu989898** [fw876/helloworld#393]
指向8.8.8.8能够正常使用。
![image](https://user-images.githubusercontent.com/39394489/108486135-b2035f80-72d8-11eb-91f2-38f4caf5d75a.png)

**Comment by lingzhuxin** [comment]
我俩基本一样的问题……真的没整明白这个dns的转发

**Comment by aorosora** [comment]
https://github.com/fw876/helloworld

**Comment by Cathgao** [comment]
可能ADGH解析出来的地址不是你飞机走的最快的地址，建议分开两路解析
