### ISSUE TITLE
订阅节点的BUG

### ISSUE THREAD

**Issue by mjyhj** [fw876/helloworld#397]
1：name: 🇭🇰 香港(中國)-T1, server: hk.1.tj.test.me
2：name: 🇭🇰 香港(中国)-V1, server: hk.1.v2.test.me
3：name: 🇭🇰 香港(中國)-S1, server: hk.1.ss.test.me
4：name: 🇭🇰 香港(中國)-S2, server: hk.2.ss.test.me
5：name: 🇭🇰 香港(中國)-S3, server: hk.1.ss.test.me
6：name: 美國(洛杉磯)-S1, server: us.1.ss.test.me
7：name: 美國(洛杉磯)-S2, server: us.1.ss.test.me
8：name: 美國(洛杉磯)-S3, server: us.1.ss.test.me
9：name: 🇯🇵 日本(東京)-S1, server: jp.1.ss.test.me
10：name: 🇯🇵 日本(東京)-S2, server: jp.1.ss.test.me
11：name: 🇯🇵 日本(東京)-S3, server: jp.1.ss.test.me
（3、5相同 6-8相同 9-11相同）

1.例如有个奇葩机场，几个节点指向的域名是一样的，导致更新订阅的时候会一直添加相同域名的节点。
香港(中國)-S1，S3 会随机添加1个
美國(洛杉磯)-S1，S2，S3 会随机添加2个
日本(東京)-S1，S2，S3 会随机添加2个

2.添加丢弃节点 不生效
/(中國)-S3/(洛杉磯)-S2/(洛杉磯)-S3/(東京)-S2/(東京)-S3
貌似是符号的原因导致的

**Comment by 1715173329** [comment]
#314
