### ISSUE TITLE
请教一下这个和jerrykuku的helloworld的差别是不是一个有空格一个没有？

### ISSUE THREAD

**Issue by norikohxb** [fw876/helloworld#4]
看名字好熟悉啊，helloworld，只不过咱们这个是没有带空格的
另外一个jerrykuku的是hello world带空格的请教一下，两个有连带关系吗？

**Comment by fyngd** [comment]
没有关系

**Comment by norikohxb** [comment]
以后就在这里更新看问题了，不错不错。苦了lean大估计压力很大。现在有人接过雷锋的枪很好的。

**Comment by kang-mk** [comment]
https://firmware.koolshare.cn/LEDE_X64_fw867/
😂确实熟悉

**Comment by ch1993128** [comment]
lean的项目过来的，这个和政策是不一致的，注意保护好自己
