### ISSUE TITLE
可否自定义SERVER模式时的IP？

### ISSUE THREAD

**Issue by huangsijun17** [fw876/helloworld#403]
希望可以自定义服务端自动分配的IP端，以便于局网内其他设备的防火墙管理访问者的IP。

**Comment by 1715173329** [comment]
意义不明。

**Comment by huangsijun17** [comment]
> 意义不明。

现在连上来的设备是在10.x.x.x IP端下面的具体多大的段我没注意，我想自己改成192.168.64.0/24这个IP段。
我现在局域网内有其他设备的防火墙是限制连入设备的IP端的。
