### ISSUE TITLE
将ssrplus编译进固件，需要勾选那些选项

### ISSUE THREAD

**Issue by cc-monkey** [fw876/helloworld#410]
把ssrplus编译进lienol固件里，需要勾选那些选项，一直没有高清楚，请教一下，万分感谢。
![Snipaste_2021-03-02_15-26-54](https://user-images.githubusercontent.com/49584605/109755651-55316e80-7c21-11eb-98d9-456d55198aae.jpg)

**Comment by slslll** [comment]
第一个勾上就行，后面是需要的对于不同协议的支持，按需勾选

**Comment by cc-monkey** [comment]
谢谢你，我勾选方括号内的选项和不够方括号的选项，最后编译出来的固件没有区别。这点有点疑惑。我只勾选了luci-app-ssr-plus，方括号一个不选和都选上，没有任何区别。

**Comment by slslll** [comment]
应该是有区别的，如果不钩xray是用不了v2ray的，也就是用不了vmess协议

**Comment by blue-troy** [comment]
若只使用v2ray 能否只勾选
- luci-app-ssr-plus 
- xray

**Comment by 1715173329** [comment]
是
