### ISSUE TITLE
ssr-switch需要延迟一下

### ISSUE THREAD

**Issue by wlshdjj** [fw876/helloworld#412]
发现开机前4秒就频繁开始切换，实际上开机前10秒网络还不稳定，甚至拨号都没拨上，就不要那么早切换了。

**Comment by zhangj3** [comment]
开机前10秒网络为啥还不稳定
我查了下系统日志 09秒有日志输出，14秒的时候就已经拨号成功了。
再者你可以在这边设置的，检查周期设置的长一些喽
![image](https://user-images.githubusercontent.com/49198958/109919349-79f61680-7cf3-11eb-807b-38d02687fb59.png)
