### ISSUE TITLE
最近勾选上xray编译稳定版的openwrt会出现报错

### ISSUE THREAD

**Issue by slslll** [fw876/helloworld#413]
用lean的openwrt项目源码编译（这个可以理解成稳定版吗）
选MT7621平台
<img width="308" alt="Snipaste_2021-03-04_07-58-04" src="https://user-images.githubusercontent.com/38198381/109889388-3f26bb00-7cc0-11eb-8237-b2b81e895b73.png">
勾选上xray插件
<img width="361" alt="Snipaste_2021-03-04_07-58-28" src="https://user-images.githubusercontent.com/38198381/109889492-6ed5c300-7cc0-11eb-9fc5-1bec64abb4dd.png">
编译时会报如下错误
<img width="922" alt="Snipaste_2021-03-04_07-53-06" src="https://user-images.githubusercontent.com/38198381/109889493-6ed5c300-7cc0-11eb-9854-47f37d1b7622.png">

**Comment by ziyangdaoren** [comment]
同样的问题，编译到xv2ray报错

**Comment by slslll** [comment]
发现了，勾选xray的时候不能同时勾选v2ray server，不然编译报错

**Comment by simonchan6688** [comment]
并没有勾选v2ray server....... 
4月之前正常，4月2日后同样出错，不知何故！

Makefile:135: recipe for target '/home/user/openwrt/build_dir/target-mipsel_24kc_musl/Xray-core-1.4.2/.built' failed
make[3]: *** [/home/user/openwrt/build_dir/target-mipsel_24kc_musl/Xray-core-1.4.2/.built] Error 1
make[3]: Leaving directory '/home/user/openwrt/feeds/helloworld/xray-core'
time: package/feeds/helloworld/xray-core/compile#2.59#2.43#2.69
package/Makefile:111: recipe for target 'package/feeds/helloworld/xray-core/compile' failed
make[2]: *** [package/feeds/helloworld/xray-core/compile] Error 2
make[2]: Leaving directory '/home/user/openwrt'
package/Makefile:107: recipe for target '/home/user/openwrt/staging_dir/target-mipsel_24kc_musl/stamp/.package_compile' failed
make[1]: *** [/home/user/openwrt/staging_dir/target-mipsel_24kc_musl/stamp/.package_compile] Error 2
make[1]: Leaving directory '/home/user/openwrt'
/home/user/openwrt/include/toplevel.mk:225: recipe for target 'world' failed

**Comment by slslll** [comment]
等更新，希望可以解决
