### ISSUE TITLE
[提议] 使用 xray-plugin 取代 v2ray-plugin

### ISSUE THREAD

**Issue by 1715173329** [fw876/helloworld#416]
xray 完全兼容 v2ray，插件也应当一致兼容。
xray 修复了大量 v2ray 的历史遗留问题，理应性能更好。
目前同时存在两个插件，保留一个即可。

Cc: @coolsnowwolf 
Cc: @Mattraks

**Comment by swxk521** [comment]
我感觉都没啥用，用这个插件，不如直接用xray里的trojan或vless
不用插件也可以用xray里的ss

**Comment by 1715173329** [comment]
> 我感觉都没啥用，用这个插件，不如直接用xray里的trojan或vless
> 不用插件也可以用xray里的ss

你不用，但机场的节点会用。

**Comment by ricksuzade-maker** [comment]
如果xray-plugin支持http方式混淆的话，支持替换
