### ISSUE TITLE
R2S 重启后SSR+无法运行

### ISSUE THREAD

**Issue by inbogota** [fw876/helloworld#436]
R2S 重启后SSR+显示正常启动，也有启动日志，但实际无效。

用SSR+的谷歌连通性检查测试，也是无法连接。清空过DNS缓存，亦无效。

只有停用主服务器，再启动一次才可以恢复正常。

望修复

**Comment by ruderal04o** [comment]
是不是选择了访问控制里面的接口控制里面的接口，如果是，取消好像可以缓解这个问题
