### ISSUE TITLE
xray+xtls不勾选允许不安全连接不能正常连接到服务器

### ISSUE THREAD

**Issue by CrBoom** [fw876/helloworld#437]
服务端xray+xtls,certbot签的证书,必须要勾选允许不安全连接才能连上,win下xray客户端一切正常(不用勾选)

**Comment by neavo** [comment]
有同样的问题，我用的是阿里云的免费证书

**Comment by Cathgao** [comment]
先看看你的证书有没有问题，访问一下你的域名

**Comment by Ming526** [comment]
你好，访问我的域名，的确登录不上了，所以我也只能勾选“允许不安全链接”，这个域名咋改，改了之后还得搭建一次。
