### ISSUE TITLE
ssr 当 tcp 和 udp 节点不同时，TCP不通

### ISSUE THREAD

**Issue by whalechoi** [fw876/helloworld#438]
## 3.15最新代码编译
+ 当这俩节点不同的时候，显然除了`udp-only-ssr-reudp.json`之外都不需要`-U`选项
![screenshot1](https://user-images.githubusercontent.com/27819307/111321633-167cc900-86a3-11eb-96b7-556cfb96f4bd.png)  

+ 当这俩节点相同的时候，则没有问题
![screenshot2](https://user-images.githubusercontent.com/27819307/111321951-63f93600-86a3-11eb-9c4b-7a6435b48032.png)  

这应该算是个老问题了 #342

**Comment by coolsnowwolf** [comment]
@Mattraks 我之前已经修复过一次了，再看下？

**Comment by whalechoi** [comment]
> @Mattraks 我之前已经修复过一次了，再看下？

对，之前那次修好了，最近几天编译的版本又出现这个问题了 :(

**Comment by pumafly** [comment]
昨天我还提了这个，以为发错地方又关闭了
我也是这样 不过我不会看日志
