### ISSUE TITLE
接口访问控制问题。

### ISSUE THREAD

**Issue by sxf5487** [fw876/helloworld#441]
<img width="711" alt="image" src="https://user-images.githubusercontent.com/50735006/111714874-96ff1d80-888d-11eb-8098-68542dc678d3.png">
如图，新增了WG接口，用于WireGuard使用，访问控制中勾选了可以正常使用，但是一旦重启Op系统就需要重新保存应用才能生效（实际是勾选的）。

**Comment by coolsnowwolf** [comment]
这个有可能是因为 WG 接口在重启后还没有连接成功，所以不会产生 wg0 接口，规则失效。可以在 WG 的 hotplug 中增加重启 SSR Plus 的命令

**Comment by sxf5487** [comment]
恩，重启后确实WG接口是没有连接的。

**Comment by sxf5487** [comment]
96-wg:

#!/bin/sh
[ "$ACTION" = ifup ] || exit 0
[ "$INTERFACE" = wg ] || exit 0

/etc/init.d/shadowsockr restart

大佬，这样写，并且命名为96-wg，修改权限为755是否就可以了。

备注：很少接触脚本，麻烦有空帮忙看看，非常感谢！

**Comment by coolsnowwolf** [comment]
应该是可以的，最好设置下延迟，例如 10s
