### ISSUE TITLE
编译出错求助！环境ubuntu20.04,勾选ssrp就会出错,似乎问题在shadowsocks-rust

### ISSUE THREAD

**Issue by levin9590** [fw876/helloworld#443]
make[3]: Entering directory '/home/can/lede/feeds/helloworld/shadowsocks-rust'
rm -f /home/can/lede/build_dir/target-mipsel_24kc_musl/shadowsocks-rust-1.9.2/.built
touch /home/can/lede/build_dir/target-mipsel_24kc_musl/shadowsocks-rust-1.9.2/.built_check
/home/can/lede/staging_dir/host/bin/upx --lzma --best /home/can/lede/build_dir/target-mipsel_24kc_musl/shadowsocks-rust-1.9.2/sslocal
                       Ultimate Packer for eXecutables
                          Copyright (C) 1996 - 2018
UPX 3.95        Markus Oberhumer, Laszlo Molnar & John Reiser   Aug 26th 2018

        File size         Ratio      Format      Name
   --------------------   ------   -----------   -----------
upx: /home/can/lede/build_dir/target-mipsel_24kc_musl/shadowsocks-rust-1.9.2/sslocal: CantPackException: bad e_shstrndx

Packed 0 files.
Makefile:110: recipe for target '/home/can/lede/build_dir/target-mipsel_24kc_musl/shadowsocks-rust-1.9.2/.built' failed
make[3]: *** [/home/can/lede/build_dir/target-mipsel_24kc_musl/shadowsocks-rust-1.9.2/.built] Error 1
make[3]: Leaving directory '/home/can/lede/feeds/helloworld/shadowsocks-rust'
time: package/feeds/helloworld/shadowsocks-rust/compile#0.17#0.05#0.21
package/Makefile:111: recipe for target 'package/feeds/helloworld/shadowsocks-rust/compile' failed
make[2]: *** [package/feeds/helloworld/shadowsocks-rust/compile] Error 2
make[2]: Leaving directory '/home/can/lede'
package/Makefile:107: recipe for target '/home/can/lede/staging_dir/target-mipsel_24kc_musl/stamp/.package_compile' failed
make[1]: *** [/home/can/lede/staging_dir/target-mipsel_24kc_musl/stamp/.package_compile] Error 2
make[1]: Leaving directory '/home/can/lede'
/home/can/lede/include/toplevel.mk:222: recipe for target 'world' failed
make: *** [world] Error 2

**Comment by levin9590** [comment]
自己顶一个先。mt7621,照前面帖子里一兄弟的提示：记得在Network>Web Servers/Proxies里去掉 rust相关选项，结果一样，还是报错

**Comment by ddzzhen** [comment]
取消upx压缩就行了

**Comment by ddzzhen** [comment]
经过测试，mipsel_24kc架构，选择upx压缩编译错误，100%重现，取消所有upx压缩，可以编译成功，但是启用后，ss-redir链接的sslocal，国外dns解析无效，可以暂时使用libev版本

**Comment by levin9590** [comment]
请问怎么取消upx压缩? 出的固件体积估计得变大

> 经过测试，mipsel_24kc架构，选择upx压缩编译错误，100%重现，取消所有upx压缩，可以编译成功，但是启用后，ss-redir链接的sslocal，国外dns解析无效，可以暂时使用libev版本

**Comment by ddzzhen** [comment]
> 请问怎么取消upx压缩? 出的固件体积估计得变大
> 搜索找到了位置. 固件体积变大了16M闪存同样的配置原来15M现在出不了固件了
> 
> > 经过测试，mipsel_24kc架构，选择upx压缩编译错误，100%重现，取消所有upx压缩，可以编译成功，但是启用后，ss-redir链接的sslocal，国外dns解析无效，可以暂时使用libev版本

在Network>Web Servers/Proxies里
