### ISSUE TITLE
GFW列表与奈飞列表无法更新

### ISSUE THREAD

**Issue by gpeditmsc1986** [fw876/helloworld#447]
![ff61f6507494e83ebfd2d7ea5065dba](https://user-images.githubusercontent.com/50704932/112155362-315db900-8c20-11eb-8364-4c29fd98f4be.png)
![5d12e4ee767252511dcb0c0a8a47711](https://user-images.githubusercontent.com/50704932/112155367-328ee600-8c20-11eb-93af-294504ab3fa0.png)
![ce2a8844fccf8803ba104a6dcc1444b](https://user-images.githubusercontent.com/50704932/112155369-33c01300-8c20-11eb-9089-a41997afc596.png)

**Comment by liuzipeng** [comment]
更新版本试试？

**Comment by gpeditmsc1986** [comment]
> 更新版本试试？

现在习惯用Stable Version版本，只是默认的无法更新，手动改地址多次才可以更新，不知道是什么情况。

**Comment by xiechangan123** [comment]
因为gfw地址源码早就更新了，你可以重新编译或者手动替换

**Comment by gpeditmsc1986** [comment]
> 因为gfw地址源码早就更新了，你可以重新编译或手动替换

这个就是昨天编译的，已经手动改地址了，可以更新成功，只是我编译的是稳定版

**Comment by ddzzhen** [comment]
说明出国没有成功

**Comment by gpeditmsc1986** [comment]
> 说明出国没有成功
![image](https://user-images.githubusercontent.com/50704932/112476742-32702100-8dad-11eb-913d-b61ef4bff1b2.png)

和这个没有关系，自定义的可以，默认的就保险
