### ISSUE TITLE
新编译的 酸酸乳 SOCKS5 代理服务端（全局） 未运行

### ISSUE THREAD

**Issue by yonggedebaqi** [fw876/helloworld#448]
新编译的 酸酸乳 SOCKS5 代理服务端（全局） 未运行
请问是什么问题？

![111](https://user-images.githubusercontent.com/43800614/112403921-51899700-8d4a-11eb-8978-17a8a7f21399.jpg)
![222](https://user-images.githubusercontent.com/43800614/112403929-54848780-8d4a-11eb-8f0d-7ffbda99e73a.jpg)
![333](https://user-images.githubusercontent.com/43800614/112403933-551d1e00-8d4a-11eb-9e96-47365fc35e25.jpg)

**Comment by EnnawYang** [comment]
来人给算一卦
