### ISSUE TITLE
游戏模式使用trojan协议会一段时间后变成udpblocked

### ISSUE THREAD

**Issue by Nats-ji** [fw876/helloworld#45]
无奈最近ssr被封严重，只好用trojan代替来加速游戏。但是游戏模式服务器设置成trojan之后，刚开始用NatTypeTester测试结果是PortRestrictedCone，过几分钟后就会变成UdpBlocked。
而且即使一开始用NatTypeTester测试结果为PortRestrictedCone，在Nintendo Switch上测试的结果却是Nat type Failed。使用的主服务器和游戏模式服务器为同一个trojan服务器。不知道有没有其他人遇到相同情况。

**Comment by smallprogram** [comment]
个人感觉是运营商封锁。

**Comment by Nats-ji** [comment]
> 个人感觉是运营商封锁。

据我理解的trojan的工作原理应该是把udp转变成tcp流量传送到远端服务器的，浏览网页什么的都是正常的，和运营商应该没有关系。

**Comment by fw876** [comment]
这个大概率是因为 Trojan 的 UDP 进程崩了，目前无法修复

**Comment by Nats-ji** [comment]
我把mwan3移除之后貌似就一直没再出过问题了
