### ISSUE TITLE
DNS解析方式 建议

### ISSUE THREAD

**Issue by liuzipeng** [fw876/helloworld#452]
能否在DNS解析方式里设置一个可以关闭dns防污染功能，应为所有dns都走ss出去的话 
对于使用 **iplc中转dns** 和 **使用国内无污染dns** 的用户来说有点不方便

**Comment by BGzErol** [comment]
想请教一下ssrp的dns防污染功能究竟是个什么原理，一直很好奇但就是找不到资料

**Comment by liuzipeng** [comment]
> 想请教一下ssrp的dns防污染功能究竟是个什么原理，一直很好奇但就是找不到资料

通过本地sock5代理中转国外dns的53端口到本机的5335端口 然后使用ipset将gfwlist的域名指向到本机的5335端口解析
