### ISSUE TITLE
pdnsd 端口问题

### ISSUE THREAD

**Issue by JSZMonkey** [fw876/helloworld#453]
当本地有一个5335端口的dns服务器时，ssrp选择本地5335没有问题，当dns模式选为 pdnsd 或者r2socket 就会报错（本地5335dns服务器没有关闭的时候）

**Comment by JSZMonkey** [comment]
建议将本地5335端口的 DNS 选项 改为 表单格式 让用户自己填比如 ：本地自定义DNS

**Comment by jikkyfu** [comment]
@JSZMonkey 谢谢，你刚那个问题的解答。我更换了端口就不报错了。
