### ISSUE TITLE
xray-core最新版本是1.4.0,makefile里面写的1.4.1

### ISSUE THREAD

**Issue by KevinZjYang** [fw876/helloworld#459]
如题：导致编译的时候下载xray-core失败。

**Comment by EnnawYang** [comment]
最新的就是1.41

**Comment by KevinZjYang** [comment]
xray-core的项目确实是1.4.1，但是编译时下载地址是https://sources.openwrt.org/xray-core-1.4.1.tar.gz。直接404.

**Comment by KevinZjYang** [comment]
> 最新的就是1.4.1

xray-core的项目确实是1.4.1，但是编译时下载地址是https://sources.openwrt.org/xray-core-1.4.1.tar.gz 直接404.

**Comment by EnnawYang** [comment]
https://codeload.github.com/XTLS/xray-core/tar.gz/v1.4.1?/xray-core-1.4.1.tar.gz

**Comment by KevinZjYang** [comment]
> https://codeload.github.com/XTLS/xray-core/tar.gz/v1.4.1?/xray-core-1.4.1.tar.gz 编译使用的是此地址

那我就不知道了。我刚才重新拉的代码，make -j8 download 然后就报错了，说这个下载失败。

**Comment by KevinZjYang** [comment]
Makefile:135: recipe for target '/home/kevin/lede/build_dir/target-x86_64_musl/Xray-core-1.4.1/.built' failed
make[3]: *** [/home/kevin/lede/build_dir/target-x86_64_musl/Xray-core-1.4.1/.built] Error 1
make[3]: Leaving directory '/home/kevin/lede/feeds/helloworld/xray-core'
time: package/feeds/helloworld/xray-core/compile#1.22#0.75#51.95
package/Makefile:111: recipe for target 'package/feeds/helloworld/xray-core/compile' failed
make[2]: *** [package/feeds/helloworld/xray-core/compile] Error 2
make[2]: Leaving directory '/home/kevin/lede'
package/Makefile:107: recipe for target '/home/kevin/lede/staging_dir/target-x86_64_musl/stamp/.package_compile' failed
make[1]: *** [/home/kevin/lede/staging_dir/target-x86_64_musl/stamp/.package_compile] Error 2
make[1]: Leaving directory '/home/kevin/lede'
/home/kevin/lede/include/toplevel.mk:222: recipe for target 'world' failed
make: *** [world] Error 2

**Comment by CrBoom** [comment]
全局代理,export HTTPS_PROXY
