### ISSUE TITLE
大佬，在服务端里的 socks5配置，能否增加一个 不启用密码的选项

### ISSUE THREAD

**Issue by 82kg** [fw876/helloworld#46]
![TIM截图20200526090643](https://user-images.githubusercontent.com/31686230/82850824-6762db80-9f30-11ea-92d8-1214c3125f44.png)

能否增加个选项，不使用用户名和密码。。。

**Comment by fw876** [comment]
这个出外网的，不加密码变肉机

**Comment by 82kg** [comment]
> 这个出外网的，不加密码变肉机

好像还真是 外网端口直接开的。。。   我以为需要手动转发。。
