### ISSUE TITLE
选了Xray还有必要选Trojan吗

### ISSUE THREAD

**Issue by vvyoko** [fw876/helloworld#468]
路由器是K2P
翻了下发现这个
https://github.com/fw876/helloworld/issues/188

意思是Xray的Trojan效率不如原版？
那么在两个都编译的情况下添加Trojan节点是以哪个优先呢？

另外请问下 故障自动切换 有效吗，我这好像从没切过节点（期间有一次节点失效我自己手动去换的。）

**Comment by SekiBetu** [comment]
https://github.com/badO1a5A90/Performance/blob/main/performance_test/Xray/speed_test_20201202.md
![image](https://user-images.githubusercontent.com/38283893/113704867-4aca2f00-970f-11eb-8c6b-d3b7e33d38bd.png)
CPU限制到同样低的情况下，网速差距，自行比较

**Comment by 1715173329** [comment]
正如 issue 中提到，golang 在 mips 下表现非常拉垮。
