### ISSUE TITLE
> 新版本是tcping延迟 ping谷歌的话占用会不会太高？每个节点都用一下

### ISSUE THREAD

**Issue by xxp2277** [fw876/helloworld#469]
> 新版本是tcping延迟 ping谷歌的话占用会不会太高？每个节点都用一下

希望能给个选项，毕竟tcping中转节点没有任何意思啊，ping/tcping 谷歌才能说明梯子状态是OK的

_Originally posted by @zhangj3 in https://github.com/fw876/helloworld/issues/306#issuecomment-755197664_
发表下自己的意见：我同意@zhangj3的观点，对于中转机场，tcping谷歌才有意义，经常碰到某些机场国内中转服务器没问题，SSRP+显示连接测试ok，ping延迟<100ms，但是切换过去就断外网。当然如果是由于tcping谷歌会导致性能下降严重甚至可能造成SSRP+崩溃，只能保持现在的设置也没话说。

**Comment by coolsnowwolf** [comment]
做个假设，如果需要检测所有节点，例如有 100 个 vray，就需要启动 100 个 vray 的实例，然后走 tcpping socks5 代理过去检测，你的路由器可以同时跑多少个 vray 程序呢？

**Comment by zhangj3** [comment]
> 做个假设，如果需要检测所有节点，例如有 100 个 vray，就需要启动 100 个 vray 的实例，然后走 tcpping socks5 代理过去检测，你的路由器可以同时跑多少个 vray 程序呢？

大雕竟然亲自回复了，我目前用的J4105 裸跑的OP，因为听说openclash是tcping节点并且自动切换的，用了OpenClash几天，4个机场一共120+节点都在一起，内存可用数跟用SSRP差不多，95%~96%可用，CPU占用率是高一些的，测试如下：
狂点openclash里的测速十几下后，CPU使用率 是0.35, 0.17, 0.13，平常是0.10, 0.08, 0.06左右。


--

**Comment by xxp2277** [comment]
> 
> 
> 做个假设，如果需要检测所有节点，例如有 100 个 vray，就需要启动 100 个 vray 的实例，然后走 tcpping socks5 代理过去检测，你的路由器可以同时跑多少个 vray 程序呢？

大雕，首先感谢你的回复。
目前大部分机器（比如我）性能达不到并发100+的实例去检测，但这个功能可以考虑呀，初期做个选择开关和并发数的设置，用户端的结果应该是luci界面上显示慢一些（也许要几分钟才能测完显示出来？）。毕竟https://github.com/coolsnowwolf/lede/issues/3359都敢支持AMD Ryzen 3990x去开128线程，我知道好多大佬的机器性能严重过剩，建议开发此功能让他们折腾一下，也让SSRP更加完善。

**Comment by z826540272** [comment]
tcping不能检测谷歌延迟,要检测谷歌延迟用的是Curl.

**Comment by z826540272** [comment]
> 做个假设，如果需要检测所有节点，例如有 100 个 vray，就需要启动 100 个 vray 的实例，然后走 tcpping socks5 代理过去检测，你的路由器可以同时跑多少个 vray 程序呢？

希望增加curl测试当前节点延迟的功能,直接自动显示在主菜单,没性能消耗

**Comment by zhangj3** [comment]
> > 新版本是tcping延迟 ping谷歌的话占用会不会太高？每个节点都用一下
> 
> 希望能给个选项，毕竟tcping中转节点没有任何意思啊，ping/tcping 谷歌才能说明梯子状态是OK的
> 
> _Originally posted by @zhangj3 in [#306 (comment)](https://github.com/fw876/helloworld/issues/306#issuecomment-755197664)_
> 发表下自己的意见：我同意@zhangj3的观点，对于中转机场，tcping谷歌才有意义，经常碰到某些机场国内中转服务器没问题，SSRP+显示连接测试ok，ping延迟<100ms，但是切换过去就断外网。当然如果是由于tcping谷歌会导致性能下降严重甚至可能造成SSRP+崩溃，只能保持现在的设置也没话说。

我用了一个月多的openclash，如上面朋友说的，curl可能更有意义...当然我分不清curl跟tcping具体区别在哪里
