### ISSUE TITLE
无法启用

### ISSUE THREAD

**Issue by KevinZjYang** [fw876/helloworld#47]
4月16日编译完后正常使用，5月23号，编译完后，无法开启。一直处于未运行状态。

**Comment by smallprogram** [comment]
删了源码重新获取。单线程编译试试

**Comment by KevinZjYang** [comment]
> 删了源码重新获取。单线程编译试试

使用Actions编译的，每次都是重新拉代码的，并且是单线程。

**Comment by coolsnowwolf** [comment]
条件不足，无法判断

**Comment by KevinZjYang** [comment]
我在EXSI新建了一个测试的openwrt可以开启，我重新编译一下，试试吧。

**Comment by smallprogram** [comment]
> > 删了源码重新获取。单线程编译试试
> 
> 使用Actions编译的，每次都是重新拉代码的，并且是单线程。

我之前也是Action编译，后来出过一些诡异的问题。就本地编译了。更新代码后也出过一些问题，基本上删源码重新本地编译都能解决。

**Comment by KevinZjYang** [comment]
![image](https://user-images.githubusercontent.com/31529584/82928678-1c3edc00-9fb5-11ea-81e5-76b383a58533.png)
重新编译了还是不可以。

**Comment by fw876** [comment]
路由器版本，订阅信息什么的都没有，猜谜吗？

**Comment by KevinZjYang** [comment]
在EXSI安装的operwrt x64.订阅是正常的，因为降级到4月16号编译的版本一切正常。

**Comment by KevinZjYang** [comment]
编译的6月3号版本，更新后可以正常开启了。
