### ISSUE TITLE
任何模式下都无法代理http3

### ISSUE THREAD

**Issue by blackshot-zard** [fw876/helloworld#474]
最近chrome89默认打开了h3/导致不管是gfw还是大陆白名单亦或是全局都无法代理使用h3协议的网页，常见的如使用cf作为cdn的网页,举例 ip.cn 首次打开是可以代理的，之后就无法走代理了，虽然有临时解决方案
打开 chrome://flags
搜索QUIC找到Experimental QUIC protocol 点击disabled就行了
还希望这个问题能在软路由上得到解决

**Comment by coolsnowwolf** [comment]
UDP 代理开启

**Comment by blackshot-zard** [comment]
> UDP 代理开启

开启了都试过了，也无法会被绕过

**Comment by 1715173329** [comment]
See #478
