### ISSUE TITLE
最新源码编译时v2ray-plugin出错

### ISSUE THREAD

**Issue by lqhorochi** [fw876/helloworld#475]
最新源码编译时v2ray-plugin出错

日志如下:
Finding targets
go: downloading github.com/v2fly/v2ray-core/v4 v4.37.3
verifying github.com/v2fly/v2ray-core/v4@v4.37.3: checksum mismatch
	downloaded: h1:FGmf5rtUo3xGHyZGJi8jEa7AKin05ROfPtegmGbkCKg=
	go.sum:     h1:Kf9Qot2lLYccEzQfoCdt9img6zo5Vf+PEaoTMfa2S8k=

SECURITY ERROR
This download does NOT match an earlier download recorded in go.sum.
The bits may have been replaced on the origin server, or an attacker may
have intercepted the download attempt.

For more information, see 'go help module-auth'.

Building targets
no Go files in /home/kenneth/lede/build_dir/target-x86_64_musl/v2ray-plugin-4.37.3/.go_work/build

make[3]: *** [Makefile:74: /home/kenneth/lede/build_dir/target-x86_64_musl/v2ray-plugin-4.37.3/.built] Error 1
make[3]: Leaving directory '/home/kenneth/lede/package/lean/v2ray-plugin'
time: package/lean/v2ray-plugin/compile#0.26#0.11#0.49
make[2]: *** [package/Makefile:113: package/lean/v2ray-plugin/compile] Error 2
make[2]: Leaving directory '/home/kenneth/lede'
make[1]: *** [package/Makefile:107: /home/kenneth/lede/staging_dir/target-x86_64_musl/stamp/.package_compile] Error 2
make[1]: Leaving directory '/home/kenneth/lede'
make: *** [/home/kenneth/lede/include/toplevel.mk:224：world] 错误 2

**Comment by tianiue** [comment]
昨天到现在，同样问题

**Comment by icecubi** [comment]
把go.sum里面的h1:Kf9Qot2lLYccEzQfoCdt9img6zo5Vf=改成h1:FGmf5rtUo3xGHyZGJi8jEa7AKin05ROfPtegmGbkCKg=
