### ISSUE TITLE
SSR 游戏模式UDP转发无效！

### ISSUE THREAD

**Issue by NeedforGit** [fw876/helloworld#476]
昨天编译出来的 SSR 游戏模式UDP转发无效，游戏主机测试网络一直显示 NAT失败。SS, trojan 等模式的 udp 转发正常，测试也正常。

换成4月8日 编译的 就没有问题了，请问怎样解决？

感谢！

**Comment by z826540272** [comment]
我v2ray和ssr测试同样，希望修复

**Comment by GitorNothing** [comment]
我最新编译的，用ssr线路，PS4同样出现nat错误，希望修复

**Comment by 1715173329** [comment]
Try with #504.

**Comment by NeedforGit** [comment]
@1715173329 感谢大神的修复！但我昨天云编译了新的X64固件，测试SSR线路的游戏模式，UDP转发还是有问题，PS4 NAT失败。然后我用4月8号之前的旧 shadowsocksr 文件 替换新的，，再测试，UDP转发就正常了，PS4 NAT测试也正常。

我对比了新旧 2个 shadowsocksr 文件，发现 start_udp 项下内容不同，新的 shadowsocksr 文件内少了以下几行代码：

[ "$(printf '%s' "$ss_program" | awk -F '/' '{print $NF}')" = "${type}local" ] &&
			local ss_extra_arg="--protocol redir -u" || local ss_extra_arg="-U"

具体对比图：

旧的 shadowsocksr :

![微信图片_20210507123014](https://user-images.githubusercontent.com/48271689/117398073-132ded00-af30-11eb-9d59-fec771e6fb7b.png)


新的 shadowsocksr:
![微信图片_20210507123249](https://user-images.githubusercontent.com/48271689/117398191-6a33c200-af30-11eb-990b-8a19c08f05eb.png)

我在想是不是少了的这2行代码，才使得SSR线路的 UDP转发 失效呢？
目前虽然替换文件也能用，但每次编译完固件都替换，太麻烦了。
能修复吗？

再次感谢大神们的无私奉献！

**Comment by 1715173329** [comment]
新代码中，udp 参数已经写入配置文件中，故不再独立添加（更好地兼容 ss-rust）
如果可以，请将您的配置文件脱敏，然后上传至此处。

**Comment by NeedforGit** [comment]
> 新代码中，udp 参数已经写入配置文件中，故不再独立添加（更好地兼容 ss-rust）
> 如果可以，请将您的配置文件脱敏，然后上传至此处。

感谢回复！
请问您所说的配置文件，是指的什么？路由上的 ssr-plus 的 config 配置文件吗？

另外，会不会是我云编译时选择插件的问题？云编译时,ssr-plus项下我只选了 shadowsocks, 没有选 shadowsocks-rust, 另外也选了red2socks. 是否需要同时勾选 shadowsocks 和 shadowsocks-rust，并把red2socks 勾掉不选？

再次感谢，给您添麻烦了。

**Comment by 1715173329** [comment]
> 请问您所说的配置文件，是指的什么？路由上的 ssr-plus 的 config 配置文件吗？

是 ssr 的配置文件，配置文件地址可以在 init 中查询到

> 另外，会不会是我云编译时选择插件的问题？

这个不影响

**Comment by NeedforGit** [comment]
> > 请问您所说的配置文件，是指的什么？路由上的 ssr-plus 的 config 配置文件吗？
> 
> 是 ssr 的配置文件，配置文件地址可以在 init 中查询到

请问，您说的ssr的配置文件是这个文件吗？ /tmp/etc/ssrplus/tcp-udp-ssr-retcp.json

**Comment by 1715173329** [comment]
> 请问，您说的ssr的配置文件是这个文件吗？ /tmp/etc/ssrplus/tcp-udp-ssr-retcp.json

你开了游戏模式的话应该不止这一个文件，如果可以麻烦都贴上来（备注文件名）

**Comment by NeedforGit** [comment]
> > 请问，您说的ssr的配置文件是这个文件吗？ /tmp/etc/ssrplus/tcp-udp-ssr-retcp.json
> 
> 你开了游戏模式的话应该不止这一个文件，如果可以麻烦都贴上来（备注文件名）

好的，等我晚上回家后弄以下，非常感谢！

**Comment by NeedforGit** [comment]
> > 请问，您说的ssr的配置文件是这个文件吗？ /tmp/etc/ssrplus/tcp-udp-ssr-retcp.json
> 
> 你开了游戏模式的话应该不止这一个文件，如果可以麻烦都贴上来（备注文件名）

各配置文件如下，具体的文件名可以查看各图片最上方的路径

![微信图片_20210507224052](https://user-images.githubusercontent.com/48271689/117466773-a9403280-af85-11eb-964f-93d11511971b.jpg)
![微信图片_20210507224111](https://user-images.githubusercontent.com/48271689/117466849-bb21d580-af85-11eb-9fb9-f0f4ea6e9a07.jpg)
![微信图片_20210507224059](https://user-images.githubusercontent.com/48271689/117466881-c2e17a00-af85-11eb-98fc-845140c54db7.png)
![微信图片_20210507224105](https://user-images.githubusercontent.com/48271689/117466891-c4ab3d80-af85-11eb-9421-8468c59ad6c7.jpg)

我今天又重新云编译了新的固件，还是不行。但发现了新问题：

新的shadowsocksr 文件下：
1. 当udp转发端口设为 仅常用端口，并关闭 访问控制中的增强游戏模式时，PS4测试网络 nat 正常，但由于不是转发所有端口，游戏加速不起作用。
2.  当udp转发端口设为 仅常用端口，并开启 访问控制中的增强游戏模式时，PS4测试网络 nat 失败。
3. 当udp转发端口设为 全部端口，无论开启或者关闭 增强游戏模式，PS4测试网络 nat 均失败。

然后我又把4月8号之前的旧shadowsocksr文件覆盖了新的，然后设置 udp转发端口设为 全部端口，并开启游戏增强模式，PS4测试网络 nat 正常。

并且我对照了一下 新旧 shadowsocksr 下的ssr配置文件，没有区别，都一样。
所以是不是还是那2行代码的问题？或者有其他问题？

希望能对大佬有所帮助！感谢！

**Comment by 1715173329** [comment]
看来我得上机测测了。。

**Comment by NeedforGit** [comment]
> 看来我得上机测测了。。

感谢！期待您的测试结果！

**Comment by 1715173329** [comment]
修了修了，原来是 ssr 本身的问题。。

**Comment by NeedforGit** [comment]
> 修了修了，原来是 ssr 本身的问题。。

感谢大佬！终于修复了！等大雕通过后我新编译一个试试！

**Comment by NeedforGit** [comment]
> 修了修了，原来是 ssr 本身的问题。。

昨天终于全新编译试了一下，完美解决！感谢大佬！
