### ISSUE TITLE
QUIC协议无法走代理

### ISSUE THREAD

**Issue by Mitsuhaxy** [fw876/helloworld#478]
经抓包测试，使用ssrp 绕过中国大陆模式启用udp中继并代理所有端口的情况下，启用了quic协议的国外网站会不走代理，全局模式也是一样
可以使用网站 https://whoer.net/ 测试，就算开了代理也能识别到国内ip，原因就是这个网站使用了QUIC协议，并且没有走代理。
UDP测试通过，普通UDP可以正常走代理。

**Comment by 1715173329** [comment]
这是刻意为之，因为 QUIC 所基于的 UDP 协议在大陆 QoS 情况十分严重。
即使是国内对国内，QoS 情况依然严重。
因此为了解决某些人油管“跑分”不高的情况，也为了优化体验，直连所有 QUIC 流量（谷歌这类的 ip 大陆无法正常访问），迫使它们走 TCP。

如果你有特殊需要，可以去掉相关规则。

**Comment by Mitsuhaxy** [comment]
> 这是刻意为之，因为 QUIC 所基于的 UDP 协议在大陆 QoS 情况十分严重。
> 即使是国内对国内，QoS 情况依然严重。
> 因此为了解决某些人油管“跑分”不高的情况，也为了优化体验，直连所有 QUIC 流量（谷歌这类的 ip 大陆无法正常访问），迫使它们走 TCP。
> 
> 如果你有特殊需要，可以去掉相关规则。

哦哦，了解。没有特殊需求，只是求证一下，谢谢解答。

**Comment by liuzipeng** [comment]
> 这是刻意为之，因为 QUIC 所基于的 UDP 协议在大陆 QoS 情况十分严重。
> 即使是国内对国内，QoS 情况依然严重。
> 因此为了解决某些人油管“跑分”不高的情况，也为了优化体验，直连所有 QUIC 流量（谷歌这类的 ip 大陆无法正常访问），迫使它们走 TCP。
> 
> 如果你有特殊需要，可以去掉相关规则。

了解一下，如何去掉相关规则？

**Comment by 1715173329** [comment]
> 了解一下，如何去掉相关规则？

https://github.com/fw876/helloworld/blob/217af055d7eb974e90a9ee23402ec0404279e5ed/luci-app-ssr-plus/root/usr/bin/ssr-rules#L222
https://github.com/fw876/helloworld/blob/217af055d7eb974e90a9ee23402ec0404279e5ed/luci-app-ssr-plus/root/usr/bin/ssr-rules#L223

去掉上面两行

**Comment by liuzipeng** [comment]
> > 了解一下，如何去掉相关规则？
> 
> https://github.com/fw876/helloworld/blob/217af055d7eb974e90a9ee23402ec0404279e5ed/luci-app-ssr-plus/root/usr/bin/ssr-rules#L222
> 
> 
> https://github.com/fw876/helloworld/blob/217af055d7eb974e90a9ee23402ec0404279e5ed/luci-app-ssr-plus/root/usr/bin/ssr-rules#L223
> 
> 去掉上面两行

好的 谢谢大佬

**Comment by 1715173329** [comment]
如无其他问题，请关闭此 issue。
