### ISSUE TITLE
ssrplus能否适配官方master下的数据库更新失败问题？！

### ISSUE THREAD

**Issue by zxlhhyccc** [fw876/helloworld#48]

**Comment by zxlhhyccc** [comment]
ssrplus编译到官方master下，在软路由上能正常更新数据库，为啥在硬路由上更新失败，诡异的问题！！！

**Comment by fw876** [comment]
实测没问题

**Comment by zxlhhyccc** [comment]
> 实测没问题

谢谢，已解决，源码包写上了wget依赖但实际未选上，同时需要配置libustream-*任意一个依赖，源码包中未写上此依赖。。。。

**Comment by dyingway** [comment]
$ `opkg install wget`
