### ISSUE TITLE
直连域名无效！

### ISSUE THREAD

**Issue by la8896** [fw876/helloworld#482]
設置了直连域名,但還是經代理！

**Comment by secretandanon** [comment]
Yeah! That's true. It's a bug. I hope developers fix it soon. 
eg. sharepoint.com

**Comment by hootigger** [comment]
设置强制走代理好像也无效

**Comment by secretandanon** [comment]
Yes.

**Comment by la8896** [comment]
希望大神能夠Fix Bug
感謝

**Comment by yunxi993** [comment]
微信通知延迟

**Comment by 1715173329** [comment]
确保你的所有 DNS 请求最终是交由 dnsmasq 处理。
不要使用 adguardhome 或者 smartdns 等其他工具替代。
