### ISSUE TITLE
請問Hello World、Passwall、ShadowsocksR Plus能夠增加支援Websocket 0-RTT

### ISSUE THREAD

**Issue by la8896** [fw876/helloworld#484]
即在客户端的路径后加上?ed=2048

客户端，服务端均升至Xray-core v1.4.0 +，只需在客户端的路径后加上?ed=2048即可减少1-RTT
https://www.youtube.com/watch?v=jsiieQy4OjQ

**Comment by 1715173329** [comment]
你可以自己在节点配置的 path 后面加上。
