### ISSUE TITLE
pdnsd-ctl命令无法正常使用

### ISSUE THREAD

**Issue by IRN-Kawakaze** [fw876/helloworld#485]
启动ssrplus，设置dns解析方式为pdnsd。之后在ssh运行`pdnsd-ctl status`或`pdnsd-ctl empty-cache`会报错：
`Error: could not open socket /var/pdnsd/pdnsd.status: No such file or directory`

排查了一下，发现目前pdnsd.status文件位于`/var/etc/ssrplus/pdnsd/pdnsd.status`，并不是pdnsd-ctl默认的`/var/pdnsd/pdnsd.status`。

手动运行`mkdir -p /var/pdnsd`和`ln -s /var/etc/ssrplus/pdnsd/pdnsd.status /var/pdnsd/pdnsd.status`创建软链接可以解决，但是每次都手动不太方便。
修改pdnsd-alt的Makefile和pdnsd.init里的CACHEDIR也能解决，但是担心会和别的依赖pdnsd的插件冲突。

希望大佬们看看有没有更合适的方法处理一下。

**Comment by Mattraks** [comment]
root@OpenWrt:~# pdnsd-ctl help
pdnsd-ctl, version pdnsd-1.2.9b-par

Usage: pdnsd-ctl [-c cachedir] [-q] <command> [arguments]

Command-line options:
-c	cachedir
	Set the cache directory to cachedir (must match pdnsd setting).
	The default is '/var/pdnsd'.


`pdnsd-ctl -c '/var/etc/ssrplus/pdnsd' status`

**Comment by IRN-Kawakaze** [comment]
> root@OpenWrt:~# pdnsd-ctl help
> pdnsd-ctl, version pdnsd-1.2.9b-par
> 
> Usage: pdnsd-ctl [-c cachedir] [-q] [arguments]
> 
> Command-line options:
> -c cachedir
> Set the cache directory to cachedir (must match pdnsd setting).
> The default is '/var/pdnsd'.
> 
> `pdnsd-ctl -c '/var/etc/ssrplus/pdnsd' status`

原来可以指定目录，没注意到。感谢指点。
