### ISSUE TITLE
Helloworld 不会把自身节点(节点列表)加入直连列表

### ISSUE THREAD

**Issue by z826540272** [fw876/helloworld#487]
电脑使用v2rayN软件,
导致代理套代理.
已测试节点列表都没有加入直连列表.
测试方法,tcping,延迟 1ms,说明经过iptables转发.

Passwall测试 当前正在使用的节点和节点列表节点都是正常tcping延迟,没有走代理

希望增加将节点列表所有节点自动加入直连的功能

**Comment by liuzipeng** [comment]
入口一样就不会代理

**Comment by z826540272** [comment]
> 入口一样就不会代理

比较希望有passwall那种把列表里所有节点加入直连的功能，方便测试
