### ISSUE TITLE
服务器地址为 IPv6，且选择绕过大陆模式时无法启动

### ISSUE THREAD

**Issue by LGA1150** [fw876/helloworld#489]
疑似这行的问题，因为往 IPv4 ipset 里添加 IPv6 地址肯定会失败，去掉 `|| return 1` 就可以启动了
https://github.com/fw876/helloworld/blob/35ff9388784abe99234f315899485988acc431d5/luci-app-ssr-plus/root/usr/bin/ssr-rules#L92

另外检测端口用的 tcping 也不支持 IPv6，一直显示的 fail

**Comment by hcym** [comment]
大雕和ipv6有仇😂，重度用户用官方20.02源码吧，原生支持的非常好，光猫拨号三层路由都正常，就是科学插件要费心

**Comment by hcym** [comment]
1151啊😯 我日，有眼无珠，大大雕不需要指点爱情

**Comment by 1715173329** [comment]
No such plan to support ipv6 right now

**Comment by hecheng337** [comment]
受 Fail2Ban 的一个 [bug](https://github.com/fail2ban/fail2ban/issues/3365#issuecomment-1258354533) 启发，我发现这实际上是意外空行 `\n` 导致的问题。

> https://github.com/fw876/helloworld/blob/e0e8533c9867b2e80849dcfc42f12a41313493ad/luci-app-ssr-plus/root/usr/bin/ssr-rules#L273-L301

`get_wan_ip` 从**两个服务器地址**、**不走代理的 wan ip** 里过滤出 IPv4 地址
如果它的返回值为空，第 **299** 行会留下一个空行。
上面 `ipset_r()` 里的 `sed -e "s/^/add ss_spec_wan_ac /"` 替换之后，就会传给 ipset 一个参数不全的指令

- ipset v7.6: Missing second mandatory argument to command add
Try `ipset help' for more information.

解决办法很简单。去 **Access Control** -> **WAN IP访问控制** -> **不走代理的WAN IP** 里随便加一个v4地址就好了
