### ISSUE TITLE
在上传过程中进行速度测试时，ssr plus vless vmess断开连接

### ISSUE THREAD

**Issue by predators46** [fw876/helloworld#491]
有没有人可以帮助我。我尝试使用vmess进行ssr plus并在上传速度测试错误时进行了速度测试，并且vmess已断开连接并重新连接。 speedtest执行上载测试时，出现vmess错误。我用的是youko路由器yk1 openwrt 19.07.4

**Comment by acooler15** [comment]
额，抱歉，没看懂😢
