### ISSUE TITLE
naiveproxy编译不过,补丁打不上去

### ISSUE THREAD

**Issue by lxwq** [fw876/helloworld#494]
删除001-Remove-concurrency-limit.patch后可以正常编译,

**Comment by zxlhhyccc** [comment]
自己的问题。。。。

**Comment by mingxiaoyu** [comment]
Patch failed!  Please fix ./patches/001-Remove-concurrency-limit.patch!

的确编译错误

**Comment by flyhong666** [comment]
是有这个问题，取消这个以及相关依赖也行，反正这个没啥用。

**Comment by hxlls** [comment]
确实存在这个问题

**Comment by EnnawYang** [comment]
灯爷NB！

**Comment by Beginner-Go** [comment]
> 灯爷NB！

你tg多少

**Comment by bluskai** [comment]
同样的问题

**Comment by EnnawYang** [comment]
> > 灯爷NB！
> 
> 你tg多少

啊这

**Comment by Beginner-Go** [comment]
> > > 灯爷NB！
> > 
> > 
> > 你tg多少
> 
> 啊这

交流下

**Comment by zxlhhyccc** [comment]
> 同样的问题

看都不看回复就说同样的问题？

**Comment by 1715173329** [comment]
灯爷 NB！
