### ISSUE TITLE
感谢作者 顺带提一点愚见

### ISSUE THREAD

**Issue by AwesomeSky** [fw876/helloworld#5]
非常感谢作者接过这个群友们人人都需要的插件 辛苦了！！非常感谢

SSR+我在实际使用过程中发现 GFWList对移动端的支持并不是很好 而PC端 跑绕过国内IP模式 又会产生很多不必要的流量 作者可否设置类似Adbyby类似的白名单制度 可以自定义某些设备跑在绕过IP模式/GFWLIST模式

**Comment by smallprogram** [comment]
+1

**Comment by Bnosora** [comment]
访问控制 - lanip访问控制

**Comment by AwesomeSky** [comment]
> 访问控制 - lanip访问控制

我说的不是不同的设备走不走代理的问题 而是不同设备设置不同名单模式的问题

**Comment by Bnosora** [comment]
> > 访问控制 - lanip访问控制
> 
> 我说的不是不同的设备走不走代理的问题 而是不同设备设置不同名单模式的问题

知道，你点进去看。

**Comment by AwesomeSky** [comment]
> > > 访问控制 - lanip访问控制
> > 
> > 
> > 我说的不是不同的设备走不走代理的问题 而是不同设备设置不同名单模式的问题
> 
> 知道，你点进去看。

请问如何设置
![Screenshot_20200419_074839_com android chrome](https://user-images.githubusercontent.com/28689540/79676768-fab33d80-821b-11ea-8565-73d1ad506b0a.jpg)

**Comment by Bnosora** [comment]
> > > > 访问控制 - lanip访问控制
> > > 
> > > 
> > > 我说的不是不同的设备走不走代理的问题 而是不同设备设置不同名单模式的问题
> > 
> > 
> > 知道，你点进去看。
> 
> 请问如何设置
> ![Screenshot_20200419_074839_com android chrome](https://user-images.githubusercontent.com/28689540/79676768-fab33d80-821b-11ea-8565-73d1ad506b0a.jpg)

增强游戏模式约等于白名单，默认模式设成gfwlist，需要大陆白名单模式的设备填进增强游戏模式里。

**Comment by AwesomeSky** [comment]
> > > > > 访问控制 - lanip访问控制
> > > > 
> > > > 
> > > > 我说的不是不同的设备走不走代理的问题 而是不同设备设置不同名单模式的问题
> > > 
> > > 
> > > 知道，你点进去看。
> > 
> > 
> > 请问如何设置
> > ![Screenshot_20200419_074839_com android chrome](https://user-images.githubusercontent.com/28689540/79676768-fab33d80-821b-11ea-8565-73d1ad506b0a.jpg)
> 
> 增强游戏模式约等于白名单，默认模式设成gfwlist，需要大陆白名单模式的设备填进增强游戏模式里。

游戏增强模式是UDP 跟白名单没什么关系

**Comment by Bnosora** [comment]
> > > > > > 访问控制 - lanip访问控制
> > > > > 
> > > > > 
> > > > > 我说的不是不同的设备走不走代理的问题 而是不同设备设置不同名单模式的问题
> > > > 
> > > > 
> > > > 知道，你点进去看。
> > > 
> > > 
> > > 请问如何设置
> > > ![Screenshot_20200419_074839_com android chrome](https://user-images.githubusercontent.com/28689540/79676768-fab33d80-821b-11ea-8565-73d1ad506b0a.jpg)
> > 
> > 
> > 增强游戏模式约等于白名单，默认模式设成gfwlist，需要大陆白名单模式的设备填进增强游戏模式里。
> 
> 游戏增强模式是UDP 跟白名单没什么关系

`$IPT -A SS_SPEC_WAN_AC -m set --match-set gmlan src -m set ! --match-set china dst -j SS_SPEC_WAN_FW`这条就是ssr-rule里关于增强游戏模式的tcp规则，如果你的主模式是gfwlist模式，这条会自动添加进iptables里。

**Comment by AwesomeSky** [comment]
> > > > > > > 访问控制 - lanip访问控制
> > > > > > 
> > > > > > 
> > > > > > 我说的不是不同的设备走不走代理的问题 而是不同设备设置不同名单模式的问题
> > > > > 
> > > > > 
> > > > > 知道，你点进去看。
> > > > 
> > > > 
> > > > 请问如何设置
> > > > ![Screenshot_20200419_074839_com android chrome](https://user-images.githubusercontent.com/28689540/79676768-fab33d80-821b-11ea-8565-73d1ad506b0a.jpg)
> > > 
> > > 
> > > 增强游戏模式约等于白名单，默认模式设成gfwlist，需要大陆白名单模式的设备填进增强游戏模式里。
> > 
> > 
> > 游戏增强模式是UDP 跟白名单没什么关系
> 
> `$IPT -A SS_SPEC_WAN_AC -m set --match-set gmlan src -m set ! --match-set china dst -j SS_SPEC_WAN_FW`这条就是ssr-rules里关于增强游戏模式的tcp规则，如果你的主模式是gfwlist模式，这条会自动添加进iptables里。

好的 我试一下

**Comment by AwesomeSky** [comment]
> > > > > > > 访问控制 - lanip访问控制
> > > > > > 
> > > > > > 
> > > > > > 我说的不是不同的设备走不走代理的问题 而是不同设备设置不同名单模式的问题
> > > > > 
> > > > > 
> > > > > 知道，你点进去看。
> > > > 
> > > > 
> > > > 请问如何设置
> > > > ![Screenshot_20200419_074839_com android chrome](https://user-images.githubusercontent.com/28689540/79676768-fab33d80-821b-11ea-8565-73d1ad506b0a.jpg)
> > > 
> > > 
> > > 增强游戏模式约等于白名单，默认模式设成gfwlist，需要大陆白名单模式的设备填进增强游戏模式里。
> > 
> > 
> > 游戏增强模式是UDP 跟白名单没什么关系
> 
> `$IPT -A SS_SPEC_WAN_AC -m set --match-set gmlan src -m set ! --match-set china dst -j SS_SPEC_WAN_FW`这条就是ssr-rules里关于增强游戏模式的tcp规则，如果你的主模式是gfwlist模式，这条会自动添加进iptables里。

确实有效 一直以为这个是对应首页的UDP游戏模式 感谢
