### ISSUE TITLE
把SSR-PLUS放到openwrt源代码下编译出来的只有英文界面

### ISSUE THREAD

**Issue by Tonkercke** [fw876/helloworld#500]
如题，我使用的是openwrt官方19.7.7的源代码，编译方式是将luci-app-ssr-plus源代码文件夹直接放到feed/luci/applications/目录下，按照流程编译出来之后的固件中，SSR-PLUS的界面全都是英文的（代理功能都正常），只有极个别选项是中文的，不知是哪里的问题，希望回复一下。

**Comment by zxlhhyccc** [comment]
> 如题，我使用的是openwrt官方19.7.7的源代码，编译方式是将luci-app-ssr-plus源代码文件夹直接放到feed/luci/applications/目录下，按照流程编译出来之后的固件中，SSR-PLUS的界面全都是英文的（代理功能都正常），只有极个别选项是中文的，不知是哪里的问题，希望回复一下。

汉化包的名字问题，将zh-cn改成zh_Hans后再编译吧。。。

**Comment by Tonkercke** [comment]
换了名字之后可以正常显示中文了。
