### ISSUE TITLE
Openwrt21.02版本无法编译

### ISSUE THREAD

**Issue by kexix** [fw876/helloworld#502]
Openwrt21.02版本无法编译，会有很多报错，建议优化下源码

**Comment by Dimitri2020007** [comment]
openwrt 21.02编译这玩意需要一个叫redsocks2的依赖

lean大的lede/package/lean目录下面就有一个redsocks2的依赖

粘到openwrt 21.02源码上就可以继续编译了啊

不知道你用的是openwrt官方的源码还是lienol修改的openwrt的源码

如果是后者

编译难度比较大

官方openwrt就少个redsocks2插件

lienol修改的openwrt不止是少个redsocks2、还少了很多和该插件相关的依赖
