### ISSUE TITLE
WARNING: Makefile 'package/feeds/helloworld/luci-app-ssr-plus/Makefile' has a dependency on 'v2ray-plugin', which does not exist

### ISSUE THREAD

**Issue by azgh** [fw876/helloworld#507]
WARNING: Makefile 'package/feeds/helloworld/luci-app-ssr-plus/Makefile' has a dependency on 'v2ray-plugin', which does not exist

`v2ray-plugin`源码出问题了

**Comment by zxlhhyccc** [comment]
> WARNING: Makefile 'package/feeds/helloworld/luci-app-ssr-plus/Makefile' has a dependency on 'v2ray-plugin', which does not exist
> 
> `v2ray-plugin`源码出问题了

是依赖包没有吧？

**Comment by EnnawYang** [comment]
> > WARNING: Makefile 'package/feeds/helloworld/luci-app-ssr-plus/Makefile' has a dependency on 'v2ray-plugin', which does not exist
> > `v2ray-plugin`源码出问题了
> 
> 是依赖包没有吧？

feeds没有正确更新呗

**Comment by XinSSS** [comment]
> > > WARNING: Makefile 'package/feeds/helloworld/luci-app-ssr-plus/Makefile' has a dependency on 'v2ray-plugin', which does not exist
> > > `v2ray-plugin`源码出问题了
> > 
> > 
> > 是依赖包没有吧？
> 
> feeds没有正确更新呗，反正问题全部甩锅”源码问题“

如何更新? 我也遇到了这个问题
一是我的ssrp插件并没有勾选v2ray-plugin, 二是编译前, feed update install命令也是执行过的
