### ISSUE TITLE
feed update && install 和修改config时警告缺少v2ray-plugin依赖

### ISSUE THREAD

**Issue by iShao** [fw876/helloworld#519]
问题同标题, 而且SSRP没有并没有选择v2ray, 那为什么会报这个错误提示呢, 有点奇怪, 有人知道如何解决这个问题吗?

**Comment by wekingchen** [comment]
试试先feed clear一下呢？

**Comment by lxwq** [comment]
手动在pckage/feeds/helloworld下建个软链接试试
ln -s v2ray-plugin ../../../feeds/helloworld/v2ray-plugin/
不知道为什么,helloworld新加的软件包总是不能自动安装,

**Comment by iShao** [comment]
> 试试先feed clear一下呢？

试过一次feeds clean

**Comment by iShao** [comment]
> 手动在pckage/feeds/helloworld下建个软链接试试
> ln -s ../../../feeds/helloworld/v2ray-plugin/ v2ray-plugin
> 不知道为什么,helloworld新加的软件包总是不能自动安装,

好的 我试试

**Comment by XinSSS** [comment]
按照 @lxwq 的方法解决这个问题了...同时最新的代码又出现了多个shadowsocksr-libev-ssr的依赖缺失警告, 也是用同样的方法链接了shadowsocksr-libev解决了

**Comment by iShao** [comment]
> 手动在pckage/feeds/helloworld下建个软链接试试
> ln -s ../../../feeds/helloworld/v2ray-plugin/ v2ray-plugin
> 不知道为什么,helloworld新加的软件包总是不能自动安装,

OK,解决了, 谢谢
