### ISSUE TITLE
安装helloworld feeds源缺少依赖

### ISSUE THREAD

**Issue by Dimitri2020007** [fw876/helloworld#520]
源码是今天最新的源码

受影响的组件：

package/feeds/helloworld/luci-app-ssr-plus/Makefile

缺少的依赖：

shadowsocksr-libev-ssr-check

shadowsocksr-libev-ssr-redir

shadowsocksr-libev-ssr-server

安装日志：

WARNING: Makefile 'package/feeds/helloworld/luci-app-ssr-plus/Makefile' has a dependency on 'shadowsocksr-libev-ssr-check', which does not exist
WARNING: Makefile 'package/feeds/helloworld/luci-app-ssr-plus/Makefile' has a dependency on 'shadowsocksr-libev-ssr-redir', which does not exist
WARNING: Makefile 'package/feeds/helloworld/luci-app-ssr-plus/Makefile' has a dependency on 'shadowsocksr-libev-ssr-server', which does not exist

**Comment by EnnawYang** [comment]
哦

**Comment by lxwq** [comment]
cd ~/lede/package/feeds/helloworld
ln -s  ../../../feeds/helloworld/shadowsocksr-libev/ shadowsocksr-libev

**Comment by pangfeng161** [comment]
这个怎么解决,也碰到

**Comment by fuokgfw** [comment]
你是没用L大的固件编译的吧，去他的包里找到这几个文件放文件夹就行了，忘记了是DL文件夹还是其他的了

**Comment by Dimitri2020007** [comment]
> 你是没用L大的固件编译的吧，去他的包里找到这几个文件放文件夹就行了，忘记了是DL文件夹还是其他的了

我用的openwrt 21.02分支编译的

**Comment by fuokgfw** [comment]
去L大文件夹里自己找，少什么就拉什么，说真的，忘记是在哪个文件夹了

**Comment by wekingchen** [comment]
> cd ~/lede/package/feeds/helloworld
> ln -s ../../../feeds/helloworld/shadowsocksr-libev/ shadowsocksr-libev

照这样做，解决了

**Comment by mcbbsandnz** [comment]
> 这个怎么解决,也碰到

直接删掉lede文件夹重新git clone就行了

**Comment by cattypapa** [comment]
楼主，我最近也在用openwrtv19.07.7的源码尝试加入Helloword插件编译，请问一下楼主，Helloworld文件夹应该放在哪个文件夹下面呀？是放在feeds/luci/applications下面呢？还是/package/呢？

**Comment by Dimitri2020007** [comment]
> 楼主，我最近也在用openwrtv19.07.7的源码尝试加入Helloword插件编译，请问一下楼主，Helloworld文件夹应该放在哪个文件夹下面呀？是放在feeds/luci/applications下面呢？还是/package/呢？

这个只需要在feeds.conf.default文件里头添加helloworld源就行

然后执行./srcipt/feeds update -a && ./srcipt/feeds install -a

**Comment by cattypapa** [comment]
我最开始就是这么干的，在feeds里面加了helloworld的源，然后...编译就报下面的错误，我已经折腾三天了，好心累，大佬能帮帮我么？下面是错误代码：
go: extracting github.com/cheekybits/genny v1.0.0
go: finding github.com/v2fly/v2ray-core/v4 v4.38.3
go: finding github.com/golang/protobuf v1.5.2
go: finding google.golang.org/protobuf v1.26.0
go: finding github.com/pires/go-proxyproto v0.5.0
go: finding golang.org/x/sys v0.0.0-20210415045647-66c3f260301c
go: finding github.com/gorilla/websocket v1.4.2
go: finding github.com/lucas-clemente/quic-go v0.20.1
go: finding golang.org/x/crypto v0.0.0-20210415154028-4f45737414dc
go: finding github.com/cheekybits/genny v1.0.0
build github.com/shadowsocks/v2ray-plugin: cannot load io/fs: malformed module path "io/fs": missing dot in first path element

Building targets
build .: cannot find module for path .

Cleaning module download cache (golang/go#27455)

make[3]: *** [Makefile:74: /home/catty/openwrt/build_dir/target-aarch64_generic_musl/v2ray-plugin-4.38.3/.built] Error 1
make[3]: Leaving directory '/home/catty/openwrt/package/feeds/helloworld/v2ray-plugin'
time: package/feeds/helloworld/v2ray-plugin/compile#1.45#0.74#24.92
make[2]: *** [package/Makefile:113: package/feeds/helloworld/v2ray-plugin/compile] Error 2
make[2]: Leaving directory '/home/catty/openwrt'
make[1]: *** [package/Makefile:107: /home/catty/openwrt/staging_dir/target-aarch64_generic_musl/stamp/.package_compile] Error 2
make[1]: Leaving directory '/home/catty/openwrt'
make: *** [/home/catty/openwrt/include/toplevel.mk:227：world] 错误 2

**Comment by Dimitri2020007** [comment]
> 我最开始就是这么干的，在feeds里面加了helloworld的源，然后...编译就报下面的错误，我已经折腾三天了，好心累，大佬能帮帮我么？下面是错误代码：
> go: extracting github.com/cheekybits/genny v1.0.0
> go: finding github.com/v2fly/v2ray-core/v4 v4.38.3
> go: finding github.com/golang/protobuf v1.5.2
> go: finding google.golang.org/protobuf v1.26.0
> go: finding github.com/pires/go-proxyproto v0.5.0
> go: finding golang.org/x/sys v0.0.0-20210415045647-66c3f260301c
> go: finding github.com/gorilla/websocket v1.4.2
> go: finding github.com/lucas-clemente/quic-go v0.20.1
> go: finding golang.org/x/crypto v0.0.0-20210415154028-4f45737414dc
> go: finding github.com/cheekybits/genny v1.0.0
> build github.com/shadowsocks/v2ray-plugin: cannot load io/fs: malformed module path "io/fs": missing dot in first path element
> 
> Building targets
> build .: cannot find module for path .
> 
> Cleaning module download cache ([golang/go#27455](https://github.com/golang/go/issues/27455))
> 
> make[3]: *** [Makefile:74: /home/catty/openwrt/build_dir/target-aarch64_generic_musl/v2ray-plugin-4.38.3/.built] Error 1
> make[3]: Leaving directory '/home/catty/openwrt/package/feeds/helloworld/v2ray-plugin'
> time: package/feeds/helloworld/v2ray-plugin/compile#1.45#0.74#24.92
> make[2]: *** [package/Makefile:113: package/feeds/helloworld/v2ray-plugin/compile] Error 2
> make[2]: Leaving directory '/home/catty/openwrt'
> make[1]: *** [package/Makefile:107: /home/catty/openwrt/staging_dir/target-aarch64_generic_musl/stamp/.package_compile] Error 2
> make[1]: Leaving directory '/home/catty/openwrt'
> make: *** [/home/catty/openwrt/include/toplevel.mk:227：world] 错误 2

19.07编译helloworld依赖差太多

21.02上编译helloworld效果会好点

只需要往openwrt/package源码里复制redsocks2就可以正常编译helloworld

**Comment by cattypapa** [comment]
行，谢谢大哥了，我重新用21的源码编译试试

**Comment by weweyes** [comment]
shadowsocksr-libev-ssr-check

shadowsocksr-libev-ssr-redir

shadowsocksr-libev-ssr-server

这三个依赖包哪位大佬有？openwrt19.07缺少上面三个依赖编译出错

**Comment by nudewolf** [comment]
rm -rf tmp && ./scripts/feeds install -f -p helloworld shadowsocksr-libev
