### ISSUE TITLE
源缺少依赖

### ISSUE THREAD

**Issue by la8896** [fw876/helloworld#523]
make: *** [world] Error 1
make -r world: build failed. Please re-run make with -j1 V=s or V=sc for a higher verbosity level to see what's going on
/workdir/openwrt/include/toplevel.mk:222: recipe for target 'world' failed
WARNING: Makefile 'package/feeds/kenzo/luci-app-vssr/Makefile' has a dependency on 'shadowsocksr-libev-alt', which does not exist
WARNING: Makefile 'package/feeds/kenzo/luci-app-vssr/Makefile' has a dependency on 'shadowsocksr-libev-server', which does not exist

**Comment by EnnawYang** [comment]
vssr和这里有什么关系吗？

**Comment by lxwq** [comment]
缺少shadowsocksr-libev-alt,去helloworld里挖一个就可以了,
