### ISSUE TITLE
openwrtv19.07.7源码编译报错，求解决

### ISSUE THREAD

**Issue by learnman1994** [fw876/helloworld#527]
我是拉取的openwrt官方源代码编译的，编译到最后阶段，报下面的错误，折腾了很久，实在不知道怎么解决，求大佬帮忙。

go: finding github.com/lucas-clemente/quic-go v0.20.1
go: finding golang.org/x/sys v0.0.0-20210415045647-66c3f260301c
go: finding golang.org/x/crypto v0.0.0-20210415154028-4f45737414dc
go: finding github.com/cheekybits/genny v1.0.0
build github.com/shadowsocks/v2ray-plugin: cannot load io/fs: malformed module path "io/fs": missing dot in first path element

Building targets
build .: cannot find module for path .

Cleaning module download cache (golang/go#27455)

make[3]: *** [Makefile:74: /home/catty/openwrt/build_dir/target-aarch64_generic_musl/v2ray-plugin-4.38.3/.built] Error 1
make[3]: Leaving directory '/home/catty/openwrt/package/helloworld/v2ray-plugin'
time: package/helloworld/v2ray-plugin/compile#1.19#0.80#15.59
make[2]: *** [package/Makefile:113: package/helloworld/v2ray-plugin/compile] Error 2

**Comment by 725216** [comment]
一样的错误

**Comment by coolsnowwolf** [comment]
golang 版本过低，不支持新版 xray 编译

**Comment by 1715173329** [comment]
需要自行升级到 golang 1.17。
