### ISSUE TITLE
近期更新出现缺少依赖shadowsocksr-libev-xxx错误

### ISSUE THREAD

**Issue by yaleyip** [fw876/helloworld#529]
近期更新出现缺少依赖shadowsocksr-libev-xxx错误。找不到原因，求助。

WARNING: Makefile 'package/feeds/helloworld/luci-app-ssr-plus/Makefile' has a dependency on 'shadowsocksr-libev-ssr-check', which does not exist
WARNING: Makefile 'package/feeds/helloworld/luci-app-ssr-plus/Makefile' has a dependency on 'shadowsocksr-libev-ssr-local', which does not exist
WARNING: Makefile 'package/feeds/helloworld/luci-app-ssr-plus/Makefile' has a dependency on 'shadowsocksr-libev-ssr-redir', which does not exist
WARNING: Makefile 'package/feeds/helloworld/luci-app-ssr-plus/Makefile' has a dependency on 'shadowsocksr-libev-ssr-server', which does not exist
WARNING: Makefile 'package/openwrt-packages/luci-app-vssr/Makefile' has a dependency on 'shadowsocksr-libev-alt', which does not exist
WARNING: Makefile 'package/openwrt-packages/luci-app-vssr/Makefile' has a dependency on 'shadowsocksr-libev-ssr-local', which does not exist
WARNING: Makefile 'package/openwrt-packages/luci-app-vssr/Makefile' has a dependency on 'shadowsocksr-libev-server', which does not exist

**Comment by icefiregx** [comment]
今天编译出现了下面错误：
Collected errors:
 * satisfy_dependencies_for: Cannot satisfy the following dependencies for luci-app-ssr-plus:
 *      shadowsocksr-libev-ssr-check
 *      shadowsocksr-libev-ssr-local
 *      shadowsocksr-libev-ssr-redir
 * opkg_install_cmd: Cannot install package luci-app-ssr-plus.

**Comment by Dimitri2020007** [comment]
已经有重复issue

https://github.com/fw876/helloworld/issues/520

**Comment by nudewolf** [comment]
rm -rf tmp && ./scripts/feeds install -f -p helloworld shadowsocksr-libev

**Comment by yaleyip** [comment]
解决部分问题。

WARNING: Makefile 'package/openwrt-packages/luci-app-vssr/Makefile' has a dependency on 'shadowsocksr-libev-alt', which does not exist
WARNING: Makefile 'package/openwrt-packages/luci-app-vssr/Makefile' has a dependency on 'shadowsocksr-libev-server', which does not exist
