### ISSUE TITLE
SSR不能科学上网

### ISSUE THREAD

**Issue by owen-gu** [fw876/helloworld#538]
最近几次更新好像SSR不能科学上网， V2RAY可以。
编译4月份版本没有问题

**Comment by EnnawYang** [comment]
天天用SSR，好着呢

**Comment by owen-gu** [comment]
> 天天用SSR，好着呢

那可能是我的问题，  但是非常奇怪， 我最新版就是不行，  刷老版可以

**Comment by wuhansusu** [comment]
我昨天编译的 没问题

**Comment by owen-gu** [comment]
> 我昨天编译的 没问题
我的情况是shadowsockr 不行， V2RAY可以
应该不是设置问题， 订阅的。  回到4月份版本都没有问题。
