### ISSUE TITLE
21.02.0-rc2 兼容有问题

### ISSUE THREAD

**Issue by wbxnewboy** [fw876/helloworld#542]
* pkg_hash_fetch_best_installation_candidate: Packages for luci-app-passwall found, but incompatible with the architectures configured
 * opkg_install_cmd: Cannot install package luci-app-passwall.

**Comment by EnnawYang** [comment]
所以passwall和这里有什么关系？

**Comment by wbxnewboy** [comment]
不好意思 发错地方了
抱歉
