### ISSUE TITLE
v2ray跑不起来

### ISSUE THREAD

**Issue by wxs-dev** [fw876/helloworld#545]
有一段时间没上来看了，最近是不是xray替代了v2ray?
机场还是用V2ray，那么我这样配置编译有问题吗？
![image](https://user-images.githubusercontent.com/58886165/120659331-d9152400-c4b8-11eb-80d8-3bef7635afe3.png)

配置完后，我打开.config看，发现v2ray-core没有一起编译。

![image](https://user-images.githubusercontent.com/58886165/120660164-9ef85200-c4b9-11eb-886b-b1a26064ca43.png)

然后v2ray就跑不起来了

![image](https://user-images.githubusercontent.com/58886165/120659933-6b1d2c80-c4b9-11eb-8c32-5bc12c9d6539.png)

有朋友知道怎么解决吗？

**Comment by yunxi993** [comment]
微信通知延迟

**Comment by wggglggg** [comment]
[feeds+config.zip](https://github.com/fw876/helloworld/files/6639174/feeds%2Bconfig.zip)

一个feeds,一个config,  因为我的.config里面好像有钩选Poweroff关机插件, 根据作者的要求 不要用写到feeds里 update，要手动直接git clone到package下,或者你去掉poweroff钩后再编, 好像除了poweroff, 其它的feeds里面都可以直接用, 最好本地编, 在线编还没搞明白怎么把poweroff　克隆到指定的目录.
