### ISSUE TITLE
希望添加订阅关键字

### ISSUE THREAD

**Issue by liubangjain** [fw876/helloworld#55]
大佬你好
      现在的hellowrold是过滤掉关键字的节点，不知能不能反过来操作呢？有些机场节点的名字信息经常变，而有节点的网络类型例如：bgp、cn2等信息没变，可不可以添加只添加关键字里cn2的节点，这样操作简单，也不要考虑节点信息的其他变化。
     希望可以支持，谢谢。

**Comment by iamggs** [comment]
支持这个，其实有过滤（黑名单）就应该有允许（白名单）。

**Comment by makepoloSeton** [comment]
不如更进一步，在屏蔽关键词丢弃节点后，把所谓白名单作成按照关键词分组，把未被屏蔽的节点按照关键词分组，比如“美国，日本”等等，没出现在分组关键词的再单独列为“其他”组，然后在插件第一页做一个分组选择项。这样分类后选节点也方便些
