### ISSUE TITLE
如何使用命令行开关SSR Plus？

### ISSUE THREAD

**Issue by HK-Journalist** [fw876/helloworld#553]
```
uci set shadowsocksr.@global[0].global_server='nil'
uci del shadowsocksr.@global[0].udp_relay_server
uci set shadowsocksr.@global[0].netflix_server='nil'
uci commit shadowsocksr
```
会变成这个样子，实际上并没有关掉。
![image](https://user-images.githubusercontent.com/50702502/121691868-0f2a5780-cafa-11eb-8eae-7fa883338fea.png)

**Comment by acooler15** [comment]
试试`/etc/init.d/shadowsocksr stop`

**Comment by rshi0212** [comment]
如何使用命令行调整主服务器？

**Comment by acooler15** [comment]
> 如何使用命令行调整主服务器？

这个就比较麻烦了，需要配合uci命令了

**Comment by rshi0212** [comment]
麻烦请指教啊～

发自我的iPhone

**Comment by HK-Journalist** [comment]
> 麻烦请指教啊～ 发自我的iPhone
> […](#)
> 在 2021年6月20日，00:04，acooler15 ***@***.***> 写道： ﻿ 如何使用命令行调整主服务器？ 这个就比较麻烦了，需要配合uci命令了 — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe.

你先手动切换到你要用的节点，然后打开`/etc/config/shadowshocksr`，找到
```
config global
	option global_server 'cfg0f4a8f'
```
其中'cfg0f4a8f'代表你要使用的服务器，记住它。
```
# 关闭
uci set shadowsocksr.@global[0].global_server='nil'
uci commit shadowsocksr
/etc/init.d/shadowsocksr stop
```
```
uci set shadowsocksr.@global[0].global_server='cfg0f4a8f'
uci commit shadowsocksr
/etc/init.d/shadowsocksr start # 启动
# /etc/init.d/shadowsocksr restart # 重启
```
