### ISSUE TITLE
重新干净编译出错

### ISSUE THREAD

**Issue by qqsir-dev** [fw876/helloworld#555]
SHELL= flock /home/qqsir/lede/tmp/.root-copy.flock -c 'cp -fpR /home/qqsir/lede/build_dir/target-x86_64_musl/naiveproxy-91.0.4472.77-1/.pkgdir/naiveproxy/. /home/qqsir/lede/staging_dir/target-x86_64_musl/root-x86/'
touch /home/qqsir/lede/staging_dir/target-x86_64_musl/root-x86/stamp/.naiveproxy_installed
mkdir -p /home/qqsir/lede/bin/targets/x86/64/packages /home/qqsir/lede/build_dir/target-x86_64_musl/naiveproxy-91.0.4472.77-1/ipkg-x86_64/naiveproxy/CONTROL /home/qqsir/lede/staging_dir/target-x86_64_musl/pkginfo
install -d -m0755 /home/qqsir/lede/build_dir/target-x86_64_musl/naiveproxy-91.0.4472.77-1/ipkg-x86_64/naiveproxy/usr/bin
install -m0755 /home/qqsir/lede/build_dir/target-x86_64_musl/naiveproxy-91.0.4472.77-1/src/out/Release/naive /home/qqsir/lede/build_dir/target-x86_64_musl/naiveproxy-91.0.4472.77-1/ipkg-x86_64/naiveproxy/usr/bin/naive
find /home/qqsir/lede/build_dir/target-x86_64_musl/naiveproxy-91.0.4472.77-1/ipkg-x86_64/naiveproxy -name 'CVS' -o -name '.svn' -o -name '.#*' -o -name '*~'| xargs -r rm -rf
export CROSS="x86_64-openwrt-linux-musl-"  NO_RENAME=1 ; NM="x86_64-openwrt-linux-musl-nm" STRIP="/home/qqsir/lede/staging_dir/host/bin/sstrip -z" STRIP_KMOD="/home/qqsir/lede/scripts/strip-kmod.sh" PATCHELF="/home/qqsir/lede/staging_dir/host/bin/patchelf" /home/qqsir/lede/scripts/rstrip.sh /home/qqsir/lede/build_dir/target-x86_64_musl/naiveproxy-91.0.4472.77-1/ipkg-x86_64/naiveproxy
rstrip.sh: /home/qqsir/lede/build_dir/target-x86_64_musl/naiveproxy-91.0.4472.77-1/ipkg-x86_64/naiveproxy/usr/bin/naive: shared object
(cd /home/qqsir/lede/build_dir/target-x86_64_musl/naiveproxy-91.0.4472.77-1/ipkg-x86_64/naiveproxy/CONTROL; ( echo "$CONTROL"; printf "Description: "; echo "$DESCRIPTION" | sed -e 's,^[[:space:]]*, ,g'; ) > control; chmod 644 control; ( echo "#!/bin/sh"; echo "[ \"\${IPKG_NO_SCRIPT}\" = \"1\" ] && exit 0"; echo "[ -s "\${IPKG_INSTROOT}/lib/functions.sh" ] || exit 0"; echo ". \${IPKG_INSTROOT}/lib/functions.sh"; echo "default_postinst \$0 \$@"; ) > postinst; ( echo "#!/bin/sh"; echo "[ -s "\${IPKG_INSTROOT}/lib/functions.sh" ] || exit 0"; echo ". \${IPKG_INSTROOT}/lib/functions.sh"; echo "default_prerm \$0 \$@"; ) > prerm; chmod 0755 postinst prerm;  )
install -d -m0755 /home/qqsir/lede/bin/packages/x86_64/helloworld
/home/qqsir/lede/staging_dir/host/bin/fakeroot /home/qqsir/lede/scripts/ipkg-build -m "" /home/qqsir/lede/build_dir/target-x86_64_musl/naiveproxy-91.0.4472.77-1/ipkg-x86_64/naiveproxy /home/qqsir/lede/bin/packages/x86_64/helloworld
Packaged contents of /home/qqsir/lede/build_dir/target-x86_64_musl/naiveproxy-91.0.4472.77-1/ipkg-x86_64/naiveproxy into /home/qqsir/lede/bin/packages/x86_64/helloworld/naiveproxy_91.0.4472.77-1-1_x86_64.ipk
echo "naiveproxy" >> /home/qqsir/lede/staging_dir/target-x86_64_musl/pkginfo/naiveproxy.default.install
make[3]: Leaving directory '/home/qqsir/lede/feeds/helloworld/naiveproxy'
time: package/feeds/helloworld/naiveproxy/compile#1484.46#81.86#454.72
make[2]: Leaving directory '/home/qqsir/lede'
make[1]: *** [package/Makefile:110: /home/qqsir/lede/staging_dir/target-x86_64_musl/stamp/.package_compile] Error 2

**Comment by acooler15** [comment]
没有找到有用的报错信息，是`make -j1 V=s'编译的吗？

**Comment by gztingting** [comment]
我也遇到了，这两天编译皆如此，昨晚干脆不选ssr+编译测试通过。
