### ISSUE TITLE
不知道是哪的问题

### ISSUE THREAD

**Issue by qqsir-dev** [fw876/helloworld#561]
Vmess订阅节点的连接测试都显示失败，ping有毫秒数也可以用，SS的订阅节点都没问题。

**Comment by qqsir-dev** [comment]
和蔼有PDNSD的执行重置总是错误

**Comment by qqsir-dev** [comment]
刚刚编译的固件出的这两个问题

**Comment by acooler15** [comment]
![image](https://user-images.githubusercontent.com/19186382/122238704-eee00b80-cef2-11eb-91b1-b14d7e373e46.png)
vmless测试可能用的curl，能提供一个节点信息么？不需要Vmess ID和AlterId

**Comment by qqsir-dev** [comment]
服务器节点类型	
V2Ray/XRay

 输入不正确的参数组合可能会导致服务无法启动
别名（可选）	
香港C | 广移专线02 | 解锁NF | x1.5
V2Ray/XRay 协议	
VMess
服务器地址	
cm.syhwdz.top
端口	
40411
AlterId	
32
Vmess/VLESS ID (UUID)	
7**********************1c
加密方式	
AUTO
传输协议	
WebSocket
WebSocket Path	
/cctv13/hd.m3u8
TLS

**Comment by acooler15** [comment]
TLS是打勾的吧？

**Comment by qqsir-dev** [comment]
我滴个妈呀，用刚刚最新的编译了固件后问题更大了，网都没了，然后管理界面输入密码一直错误，都进不去，后来没办法，虚拟机那边恢复到5月4日的版本了，也不知道是LEDE 那边的问题还是这边的了，好好检查一下吧

**Comment by acooler15** [comment]
> 我滴个妈呀，用刚刚最新的编译了固件后问题更大了，网都没了，然后管理界面输入密码一直错误，都进不去，后来没办法，虚拟机那边恢复到5月4日的版本了，也不知道是LEDE 那边的问题还是这边的了，好好检查一下吧

...这次新固件需要不保留配置升级

**Comment by qqsir-dev** [comment]
因为之前升级出问题了，所以我虚拟机直接装了一下最新的，一开始能进去，但是无法获取订阅，我就重启了一下然后就又进不去了，一直提示密码错误，命令行改了也不行，就是密码错误，方便加我微信吗？我是一只贴着更新咱们固件的，都是自己编译，有问题好了解一下，1211748

**Comment by qqsir-dev** [comment]
如果不保留配置升级的话应该提示一下，不然出现问题进不去管理页面就很麻烦了，不过我刚刚直接装的最新的，没有配置，所以开始能进去，后来我增加订阅链接获取不到任何节点，我就重启了一下就又进不了管理界面了，一直提示密码错误

**Comment by qqsir-dev** [comment]
我再装一次新的，仔细测试一下

**Comment by qqsir-dev** [comment]
密码问题可能是我操作失误，但是纯新的是无法订阅的，两个订阅都不行，而且网也用不了，百度的连接性测试也是失败的，而且网页也打不开，还是检查一下吧，恢复到老版本很顺利的就都没问题了

**Comment by qqsir-dev** [comment]
哦，我编译的时候没发现hellowworld有更新，LEDE是有的就是一堆++++++-------

**Comment by qqsir-dev** [comment]
今天最新的编译固件可以正常了，但是又回到原点，Vmess节点的连接测试仍然是失败的，但是PING是有毫秒的，并且也可以正常使用，只是Vmess连接测试失败，SS和SSR的没问题

**Comment by acooler15** [comment]
> 今天最新的编译固件可以正常了，但是又回到原点，Vmess节点的连接测试仍然是失败的，但是PING是有毫秒的，并且也可以正常使用，只是Vmess连接测试失败，SS和SSR的没问题

额，websocket 测试使用了curl，这个pr是我搞的，当时没有考虑到使用tls时证书自签名的情况。。。

**Comment by qqsir-dev** [comment]
不会呀～～～～～我 要是会我就自己弄了.........

**Comment by qqsir-dev** [comment]
这个到不急，反正能用，什么时候修复都可以，谢谢了
