### ISSUE TITLE
全局模式 开启UDP 不能使用

### ISSUE THREAD

**Issue by sk007** [fw876/helloworld#566]
开启UDP+全局模式
所有网络不能使用

**Comment by sk007** [comment]
需要设置为 代理常用端口 才可以使用
如果代理所有端口 就导致不能使用 
在海外打游戏受影响

**Comment by jsjcjsjc** [comment]
老哥,你是加速游戏吗?
我尝试了一下也不行啊,你是怎么设置的?

**Comment by deplives** [comment]
> 需要设置为 代理常用端口 才可以使用 如果代理所有端口 就导致不能使用 连接海外打游戏受影响

我刚试了一下，开启代理所有端口，我的switch可以测试为指定的IP，联机差不多，比裸连好
