### ISSUE TITLE
fc92437 强制代理无效

### ISSUE THREAD

**Issue by deplives** [fw876/helloworld#568]
版本为 fc9243766276176630abe991de0c53343b4e8f2b
已知某域名(domain)不在GFWList中，开启GFWList模式，将某域名(domain)添加到强制代理中，保存并刷新pdnsd，后又重新启动openwrt，发现某域名(domain)依旧不使用代理

**Comment by finalcreator** [comment]
强制走代理 无效 ,好伤

**Comment by 1715173329** [comment]
请确定 DNSMasq 为你的根 DNS 服务器，没有使用 AdGuardHome / SmartDNS 等接管。

**Comment by klever1988** [comment]
做完那些操作之后，你还需要在pc端清除掉系统和浏览器的dns缓存。
