### ISSUE TITLE
websocket连接测试 显示fail

### ISSUE THREAD

**Issue by ruderal04o** [fw876/helloworld#569]
websocket在服务节点页显示连接测试 显示fail但是实际上是可以连接的，难道我编译的时候没编译到什么关键组件吗？请赐教

**Comment by coolsnowwolf** [comment]
手动安装 curl

**Comment by ruderal04o** [comment]
> 手动安装 curl

嗯，已经重新编译过最新版本了，用GRPC显示OK，websocket就是fail。curl编译的时候已经一同编译了，用您的固件呢。

**Comment by ruderal04o** [comment]
> 手动安装 curl
找到问题了，服务器地址不能为IP，改成域名就好了

**Comment by lovelyOK** [comment]
我也遇到这个问题，因为必须要用IP，，希望大佬能够修复。（5月份的时候的版本是没有这个问题的）
