### ISSUE TITLE
luci界面点击“保存&应用”后xray不能启动

### ISSUE THREAD

**Issue by acooler15** [fw876/helloworld#586]
树莓派4B 4G内存
在luci界面（/cgi-bin/luci/admin/services/shadowsocksr/client）点击“保存&应用”后xray不能启动，但是在命令行中运行`/etc/init.d/shadowsocksr restart`、`/etc/init.d/shadowsocksr reload`、`/sbin/luci-reload shadowsocksr`都能正常启动。

发现当在luci界面（/cgi-bin/luci/admin/services/shadowsocksr/client）点击“保存&应用”时，xray会抛出`mmap: cannot allocate memory`错误。

xray运行时的内存情况：
![image](https://user-images.githubusercontent.com/19186382/123832453-ee566480-d937-11eb-8358-8691de8a68ec.png)

**Comment by zym5368** [comment]
楼主解决了吗？一样的情况。。自从有这个xray开始就在页面启动不了。。ssrp,passwall,vssr都是一样的问题，就是xray启动不了，ss的节点是没问题的，v2的节点就启动不了xray.编译了n个版本都是这个问题。

**Comment by acooler15** [comment]
> 楼主解决了吗？一样的情况。。自从有这个xray开始就在页面启动不了。。ssrp,passwall,vssr都是一样的问题，就是xray启动不了，ss的节点是没问题的，v2的节点就启动不了xray.编译了n个版本都是这个问题。

沒有呢，好像是nginx的问题，看到一个解决方案 #issuecomment-873083100 还没有试

**Comment by acooler15** [comment]
> 楼主解决了吗？一样的情况。。自从有这个xray开始就在页面启动不了。。ssrp,passwall,vssr都是一样的问题，就是xray启动不了，ss的节点是没问题的，v2的节点就启动不了xray.编译了n个版本都是这个问题。

找到了另一个解决办法，修改文件`/etc/uwsgi/vassals/luci-webui.ini`，将`limit-as`的值改为大于4803的值。
![image](https://user-images.githubusercontent.com/19186382/125880626-6b03054c-b688-4d77-a176-91d8c28ff0dd.png)
值需要大于这个：
![image](https://user-images.githubusercontent.com/19186382/125880704-12778351-773c-4531-8cc0-bf82a96b1510.png)
