### ISSUE TITLE
GFW 列表、国内 IP 段更新失败

### ISSUE THREAD

**Issue by GWONGJYULEI** [fw876/helloworld#587]
能正常使用代理，但是更新数据库时提示更新失败

**Comment by GWONGJYULEI** [comment]
已找到原因：更新地址已被墙

解决方法：

GFWList更新URL 自定义为：
`https://raw.githubusercontent.com/Loyalsoldier/v2ray-rules-dat/release/gfw.txt`

将
`ispip.clang.cn`
添加到“强制走代理域名”，同时需要在服务器端做好放行

即可恢复正常更新

**Comment by yunxi993** [comment]
.
