### ISSUE TITLE
编译xray-core出现cannot load embed: malformed module path "embed": missing dot in first path element错误

### ISSUE THREAD

**Issue by aaronchin** [fw876/helloworld#590]
编译target Allwinner A1X/A20/A30时出现 xray-core错误
build github.com/xtls/xray-core/main: cannot load embed: malformed module path "embed": missing dot in first path element
Building targets
build .: cannot find module for path .
Cleaning module download cache (golang/go#27455)
但是在编译其他target例如Allwinner H5 mt7621 IPQ40xx 以及X86时都正常

**Comment by 1715173329** [comment]
Cannot reproduction your problem.
