### ISSUE TITLE
ssrplus+使用gRPC关闭mux就不能连接

### ISSUE THREAD

**Issue by ShoukakuChuuCC** [fw876/helloworld#593]
Xray的gRPC自带mux，所以不想开启Ray系的mux（Ray系的问题较多）
但是节点配置不开启mux就无法正常连接
ssrp+ version 184-9
设备Raspberry Pi 4 Model B Rev 1.1
OpenWrt R21.7.1.100 (2021-07-10) / LuCI Master (git-21.188.53404-317d4ad)

**Comment by ShoukakuChuuCC** [comment]
在xray的官方tg群问了下群友 他x86用ssrp+是能关闭mux后连接的

**Comment by GWONGJYULEI** [comment]
终于找到在 SSRP 上一直连不上 gRPC 的原因了，原来是没有开 MUX……
我先开了 MUX 就能连上了
不知道大佬有没有时间补充一下 gRPC 下的 multiMode 选项呢？
