### ISSUE TITLE
关于 SSR Plus+ 的 dns 解析分流规则与 ip 代理分流规则的不一致问题分析与建议

### ISSUE THREAD

**Issue by lynncui00** [fw876/helloworld#597]
#### 本人情况
刚使用 lede 不到 2 天的纯小白一枚。

#### 直观体验存在的问题情况
- SSR Plus+ 使用 “绕大陆 IP 模式”，其他模式应该不存在这个问题现象。
- 开启 SSR Plus+ 后，访问某些国内网站的图片视频资源，明显比没开启的时候慢。

#### 问题简单分析
- 国内某些网站的 CDN 资源，解析出来的 IP 可能不一定在国内，也许在东南亚。
- 在代理的 ip 分流规则里面，这些 ip 会通过 vps 节点（美国）进行代理，导致链路物理距离变长，延迟变高。

#### SSR Plus+ dns 解析原理简单分析
- 域名解析的时候，GFW 名单里面的域名，SSR Plus+ 内部使用 vps 节点去解析，所以解析出来的结果一般离 vps 节点更近，这种域名大概率解析出来是国外 ip，所以最后通过 ip 分流走 vps 代理的话，理论上是最优的。
- 非 GFW 名单里面的域名，走国内 Dns 服务商 (默认应该是运营商给的) 解析，解析出来的结果离本人国内上网实际地点更近，这种域名大概率解析出来是国内 ip， 所以最后通过 ip 分流走直连，也是最优的。
- 问题出现在不一致的地方，就是非 GFW 名单的域名，解析出来是国外 ip， 同时最后 ip 分流走的是 vps 节点，这个在大部分情况下也许也是最优的。
- 唯一存在的问题就是前面描述的情况，全球 CDN 的资源解析出来在 东南亚，但最后绕行 美国 vps 节点。
- 所以本质上这个问题对于 SSR Plus+ 是一个很小的问题，但也不妨碍我们讨论这个问题。

#### 如何解决这种不一致问题？
- 无法通过域名判断解析出来的 ip 到底是国内还是国外的。
- 原则上只能通过统计和经验，通过域名名单的方式，无限逼近一致。
- 但域名解析千变万化，这本身不是一个靠谱的解决思路。

#### 必须从软件源头解决问题
- 由于目前通过远端 vps 解析 or 直连解析，是 SSR Plus+ 内部控制的逻辑，所以个人认为必须修改 SSR Plus+ 才能解决这个问题。
- 通过第三方的 dns 插件是无法规避这个问题的。

#### 解决思路建议
-  参考 google 的 [Backup Requests](http://static.googleusercontent.com/media/research.google.com/zh-CN//people/jeff/Berkeley-Latency-Mar2012.pdf)
- SSR Plus+ 对于所有域名（无论是否 GFW), 直接双发解析，R1. 通过 vps 节点走国外解析 R2. 直连国内解析
- 如果 R2 返回的是国内 ip，则直接使用 ip
- 如果 R2 返回的是国外 ip，则等待 R1 的结果，使用 R1 解析出来的 ip

#### 仍然存在的问题
- 如果 R2 解析出来的是国外 ip， 但 R1 解析出来的是国内 ip ？

_当然我在路由器这方面纯无知小白，接触的东西也不多，所以也许这个问题已经解决了？也是这些分析是错误的？_

**Comment by coolsnowwolf** [comment]
按照原理来说，不在 gfwlist 的域名确实有可能被解释为 CDN 地址，一般 CDN 地址都是“本地ISP的DNS” 负责解析的，极少会出现解析到国外的情况

**Comment by lynncui00** [comment]
是的，确实是一个概率比较低，也是一个很小的问题，发出来讨论的目的是看是否已经解决了？或者不解决其实也无碍，只是没那么的完美。
基本上出现问题的场景大概率是以下两种情况：
1. 某些允许外链的 app，其中外链对应的 CDN 在国内无源，最近的可能是香港或东南亚。
2. 某些非 GFW 的国外 app，同样在国内无源，最近的可能是香港或东南亚。

以上这两种情况最优的是通过 vps 节点去解析离 vps 最近的 ip。

**Comment by hplee0120** [comment]
同样的情况，后来使用passwall感觉因为有chinadns-ng对于国内外需不需要走远程的判断比较合理。你可以试试。ssrp好像只有gfw列表的域名才会强制走远程，但是实际还有很多被污染但是并未收录在gfw列表的国外网站。之前也有也看过对于ssrp的相同建议，但是大雕似乎有其他的考虑和说法，所以没有采用chinadns-ng的方式分流

**Comment by lynncui00** [comment]
对 passwall 了解还不是很深入，按我粗浅的理解，chinadns-ng 看起来只是个第三方插件？
1. passwall 能驱动 chinadns-ng 通过 passwall 的 vps 代理节点进行 dns 解析吗？
2. chinadns-ng 能驱动 passwall 并且利用 passwall 的 vps 节点进行 dns 解析吗？

如果任意一方都无法进行驱动，那么可能得到是比 SSR Plus+ 现在更差的结果。
整个的链路可能是：
1. 国外的域名通过 chinadns-ng 去解析，但没有经过 vps 节点，解析出来的是离自己最近的国外 ip
2. passwall 使用中国列表以外模式，这个 ip 会走 vps 节点进行代理，但并不是离 vps 最近的 ip

_亦或者两者已经做了非常深度的融合？欢迎分享一下。_

**Comment by hplee0120** [comment]
> 对 passwall 了解还不是很深入，按我粗浅的理解，chinadns-ng 看起来只是个第三方插件？
> 
> 1. passwall 能驱动 chinadns-ng 通过 passwall 的 vps 代理节点进行 dns 解析吗？
> 2. chinadns-ng 能驱动 passwall 并且利用 passwall 的 vps 节点进行 dns 解析吗？
> 
> 如果任意一方都无法进行驱动，那么可能得到是比 SSR Plus+ 现在更差的结果。
> 整个的链路可能是：
> 
> 1. 国外的域名通过 chinadns-ng 去解析，但没有经过 vps 节点，解析出来的是离自己最近的国外 ip
> 2. passwall 使用中国列表以外模式，这个 ip 会走 vps 节点进行代理，但并不是离 vps 最近的 ip
> 
> _亦或者两者已经做了非常深度的融合？欢迎分享一下。_

chinadns-ng的作用你可以自己看下这个文档，它的作用就是差不多你上面提到的需求，国内域名使用国内dns查询，如果返回国外ip或是gfw内的域名则用可信dns进行查询。而passwall是套用这个工具用于国内外分流，如果查询的是国内域名则使用系统dns直连，如果返回的是国外的结果则使用可信dns走远程代理。我觉得你前面提到的国内和国外的解析需求实际就是chinadns-ng的功能
https://github.com/zfl9/chinadns-ng
https://github.com/xiaorouji/openwrt-passwall

**Comment by lynncui00** [comment]
@hplee0120 感谢，我研究一下

**Comment by lynncui00** [comment]
@hplee0120 刚看了 chinadns-ng 的文档，不知道我的理解对不对。
1. 关键的配置是 chinadns-ng 的可信 dns 配置。
2. 这个可信 dns 需要通过 passwall 的 tcp 节点走代理去解析。
3. 所以是一个套娃的配置，passwall(自定义dns) -> chinadns-ng -> 可信dns -> passwall(pdnsd通过tcp节点请求dns)

**Comment by hplee0120** [comment]
> @hplee0120 刚看了 chinadns-ng 的文档，不知道我的理解对不对。
> 
> 1. 关键的配置是 chinadns-ng 的可信 dns 配置。
> 2. 这个可信 dns 需要通过 passwall 的 tcp 节点走代理去解析。
> 3. 所以是一个套娃的配置，passwall(自定义dns) -> chinadns-ng -> 可信dns -> passwall(pdnsd通过tcp节点请求dns)
> 
> 所以 SSR Plus+ 也可以套娃
> ssr plus+(本机端口5535的dns服务) -> chinadns-ng -> 可信dns -> ssr plus+(使用pdnsd tcp查询并缓存)

不知道我的猜测是否正确，正如你上面说的，ssrp内部的逻辑就是那样的，所以我不确认ssrp套上chinadns-ng是否可以达到同样的效果，我的理解是就算ssrp套上chinadns-ng，效果只是使用chinadns-ng替换了pdnsd而已，至于是否得到可信dns的结果后走不走远程代理，这部分应该是内部逻辑写好的？跟套哪个服务关系不大

**Comment by lynncui00** [comment]
> > @hplee0120 刚看了 chinadns-ng 的文档，不知道我的理解对不对。
> > 
> > 1. 关键的配置是 chinadns-ng 的可信 dns 配置。
> > 2. 这个可信 dns 需要通过 passwall 的 tcp 节点走代理去解析。
> > 3. 所以是一个套娃的配置，passwall(自定义dns) -> chinadns-ng -> 可信dns -> passwall(pdnsd通过tcp节点请求dns)
> > 
> > 所以 SSR Plus+ 也可以套娃
> > ssr plus+(本机端口5535的dns服务) -> chinadns-ng -> 可信dns -> ssr plus+(使用pdnsd tcp查询并缓存)
> 
> 不知道我的猜测是否正确，正如你上面说的，ssrp内部的逻辑就是那样的，所以我不确认ssrp套上chinadns-ng是否可以达到同样的效果，我的理解是就算ssrp套上chinadns-ng，效果只是使用chinadns-ng替换了pdnsd而已，至于是否得到可信dns的结果后走不走远程代理，这部分应该是内部逻辑写好的？跟套哪个服务关系不大
> 打个比方，比如你打开一个被墙的网站，因为这个域名命中gfw列表所以ssrp才会决定将它发给pdnsd或者你自定义的5335端口的进行远程解析，如果这个域名不在gfw列表里，ssrp是不会把它发到pdnsd或者你其他的服务远程进行解析的。这应该还是内部逻辑决定的，ssrp原本的设计似乎就是只有gfw列表才会走远程，其他的默认都是直连。
> 这是结合以往的issues的讨论和建议想起来的，也可能有不对的地方

问题的根源出现在，访问国外可信dns的时候，有没有走代理。至于拿到了 dns 结果后的处理就只是遵守代理模式分流即可（这里讨论的模式是指 绕过大陆 ip 模式，即通过国外 ip 一律走代理）。
1. SSR Plus+ 通过 GFW 判断要不要走代理。
2. chinadns-ng 直接访问国外可信 dns，并不会走代理。
3. 目前看只有套娃才能解决这里讨论的问题，但能不能套还没实践过（取决于SSR Plus+ or passwal 使用了自定义的 dns 后，本身的隧道访问 dns 端口是否仍然能继续提供服务）

**Comment by hplee0120** [comment]
passwall因为本身适配了这个chinadns-ng，所以应该实现的就是你想要的结果。只要确定返回的是国外的，直接走远程代理。
而ssrp本身的逻辑根据以往的讨论是只有命中gfw列表才会走远程。其他的还是采用直连
![E1F98CD6-2354-4F93-9998-46F6CDB5FDD7](https://user-images.githubusercontent.com/55278556/126030124-45375331-bc80-4ac3-9007-badad37933ad.jpeg)
![8574881F-7C08-45F8-AE86-E408BFCF74FE](https://user-images.githubusercontent.com/55278556/126030135-dcf2022a-6a63-4d33-83fd-5cfc8d7daf70.jpeg)

**Comment by lynncui00** [comment]
我理解作者的思路可能是这样：
1. 双发 dns 解析存在并行机制，并行机制会带来系统极大的不稳定性（非常认同）。
2. 如果使用串行方式也可以解决这个问题，即当国内 dns 解析出来了国外 ip 后， 再通过代理重新解析一遍（会导致解析了两次）。

能够用简单的方式解决问题，那就坚决不要搞复杂，如果做一个 trade off 的话，我会选择 2， 因为他解决的是一个较为的稀有场景。

passwall 文档比较少，可能要慢慢研究折腾了，先 close。

**Comment by realconnor** [comment]
1. CDN的问题要相对可靠地解决，一般来说都要耦合本地DNS与代理两者。路由器收到的来自客户端的业务，比如TCP包，由于互联网协议的分层设计原则，关于目的节点的信息是存储在头部IP地址和端口；但是这些信息是先前由本地DNS应答产生的，很难做到返回的结果是代理服务器附近的CDN，或者说要做到代价较大。
2. 一种思路就是在本地DNS应答的时候，在本地记录应答结果和DNS请求的FQDN（完整域名）映射，将需要代理的连接，在转发之前反推出FQDN，再由代理服务器在远端根据FQDN重新请求DNS记录，这样可以确保需要代理的CDN是准确的，不会出现”美国访问东南亚再回去，最后送回中国这种事“。
3. 个人使用经验的话，Clash就是这个模式，如果特别困扰这些问题，可以一试。

**Comment by 1715173329** [comment]
如果你使用 SSR / V2ray / Xray，那么大可不必担心，它们默认开启域名嗅探，将由远程解析域名，本地结果仅作参考。
但问题在于传统的 SS / Trojan-GFW，并不支持此功能，如果本地结果被投毒或者解析不正确，将会直接影响最终连接，这确实是一个问题。当然，现在的 *ray 已经内置了它们，可以直接使用由 *ray 提供的相应实现，ssrplus 中包含了这部分逻辑。
使用 mosdns 之类的解析器会有所帮助，但其整体大小（本体+规则）对于路由器而言有些庞大。
