### ISSUE TITLE
状态里三个数据库更新均无法使用，更新失败

### ISSUE THREAD

**Issue by qqsir-dev** [fw876/helloworld#60]
【GFW列表】数据库	 更新失败！
【国内IP段】数据库	 更新失败！
【Netflix IP段】数据库	 更新失败！

**Comment by EnnawYang** [comment]
![Snipaste_2020-06-03_08-27-59](https://user-images.githubusercontent.com/6705663/83582469-26904580-a574-11ea-9632-5b2ff22f9abe.png)

**Comment by qqsir-dev** [comment]
我是刚刚编译完就这样了，编译前是可以更新的。

**Comment by ydhang** [comment]
是的 gfw模式 上不了油管 大陆白名单可以 之前编译的还可以用 前天晚上编译后 就用不了了

**Comment by zxlhhyccc** [comment]
> 是的 gfw模式 上不了油管 大陆白名单可以 之前编译的还可以用 前天晚上编译后 就用不了了

可以使用，是你缺少了依赖，我也是找了好久的原因才发现。。。。

**Comment by ydhang** [comment]
> > 是的 gfw模式 上不了油管 大陆白名单可以 之前编译的还可以用 前天晚上编译后 就用不了了
> 
> 可以使用，是你缺少了依赖，我也是找了好久的原因才发现。。。。见我前面的issue吧，我写了需要的依赖。。。。

感谢，具体是哪几个依赖？

**Comment by coolsnowwolf** [comment]
主要是 wget，新版本op 叫做 wget-gnu
