### ISSUE TITLE
184-9，GFW模式，微信聊天打开别人发过来的图片巨慢无比

### ISSUE THREAD

**Issue by yeefanwong** [fw876/helloworld#600]
如题，微信打开别人发过来的图片要转好多圈才能显示出来，关闭ssrp马上秒开。

**Comment by softtip** [comment]
测试环境：iphone 12promax
Merge pull request #596 from 1715173329/quic-drop这个commit有问题
SSR开启后，无论手机是否走ssr，都会导致微信打开聊天图片巨慢无比

luci-app-ssr-plus/root/usr/bin/ssr-rules 改回RETURN一切正常了
$ipt -A SS_SPEC_TPROXY -p udp --dport 443 -j RETURN
$ipt -A SS_SPEC_TPROXY -p udp --dport 80 -j RETURN

**Comment by zorrose82** [comment]
> 测试环境：iphone 12promax
> Merge pull request #596 from 1715173329/quic-drop这个commit有问题
> SSR开启后，无论手机是否走ssr，都会导致微信打开聊天图片巨慢无比
> 
> luci-app-ssr-plus/root/usr/bin/ssr-rules 改回RETURN一切正常了
> $ipt -A SS_SPEC_TPROXY -p udp --dport 443 -j RETURN
> $ipt -A SS_SPEC_TPROXY -p udp --dport 80 -j RETURN

修改后立马就快了

**Comment by softtip** [comment]
> > 测试环境：iphone 12promax
> > Merge pull request #596 from 1715173329/quic-drop这个commit有问题
> > SSR开启后，无论手机是否走ssr，都会导致微信打开聊天图片巨慢无比
> > luci-app-ssr-plus/root/usr/bin/ssr-rules 改回RETURN一切正常了
> > $ipt -A SS_SPEC_TPROXY -p udp --dport 443 -j RETURN
> > $ipt -A SS_SPEC_TPROXY -p udp --dport 80 -j RETURN
> 
> 修改后立马就快了

2021.8.5大雕的源码更行后已解决修复

**Comment by zorrose82** [comment]
> > > 测试环境：iphone 12promax
> > > Merge pull request #596 from 1715173329/quic-drop这个commit有问题
> > > SSR开启后，无论手机是否走ssr，都会导致微信打开聊天图片巨慢无比
> > > luci-app-ssr-plus/root/usr/bin/ssr-rules 改回RETURN一切正常了
> > > $ipt -A SS_SPEC_TPROXY -p udp --dport 443 -j RETURN
> > > $ipt -A SS_SPEC_TPROXY -p udp --dport 80 -j RETURN
> > 
> > 
> > 修改后立马就快了
> 
> 2021.8.5大雕的源码更行后已解决修复

谢谢，我现在去编译。。。
