### ISSUE TITLE
Merge pull request #596 from 1715173329/quic-drop导致微信打开图片巨慢无比

### ISSUE THREAD

**Issue by softtip** [fw876/helloworld#601]
测试环境：iphone 12promax
Merge pull request #596 from 1715173329/quic-drop这个commit有问题
SSR开启后，无论手机是否走ssr，都会导致微信打开聊天图片巨慢无比

luci-app-ssr-plus/root/usr/bin/ssr-rules 改回RETURN一切正常了
$ipt -A SS_SPEC_TPROXY -p udp --dport 443 -j RETURN
$ipt -A SS_SPEC_TPROXY -p udp --dport 80 -j RETURN

请维护者撤销有问题这两个有问题的commit
Merge pull request #596 from 1715173329/quic-drop
luci-app-ssr-plus: drop QUIC traffic

**Comment by deplives** [comment]
目前没有遇到改问题

**Comment by softtip** [comment]
跟手机也有关系，iPhone8plus xsmax14.3都没问题，12 pro max 14.3就有问题
这两句代码改回去就一切正常，否则就是巨慢无比

Bob zhang ***@***.***>于2021年7月20日 周二13:08写道：

**Comment by softtip** [comment]
已解决，微信的问题，彻底关闭微信再开就好，微信运行久了就会这样
