### ISSUE TITLE
必须依赖libustream-openssl

### ISSUE THREAD

**Issue by haohaoget** [fw876/helloworld#607]
必须依赖libustream-openssl，与libustream-mbedtls冲突无法编译有什么方法可以不依赖libustream-openssl吗？

**Comment by hcym** [comment]
去掉那一个不就完事，除非你不用ssr

**Comment by haohaoget** [comment]
> 去掉那一个不就完事，除非你不用ssr

没法去掉两个都是-*-，只要把ssr取消就可以去掉libustream-openssl，我以前编译ssr就可以直接取消libustream-openssl的是哪个版本更新导致ssr必须依赖openssl呢？

**Comment by aueu** [comment]
https://github.com/fw876/helloworld/pull/571

这个引入的

**Comment by pzxiaoyi** [comment]
> #571
> 
> 这个引入的

希望能改成libustream-mbedtls，这样子就不会冲突了。谢谢

**Comment by aueu** [comment]
> > #571
> > 这个引入的
> 
> 希望能改成libustream-mbedtls，这样子就不会冲突了。谢谢

libustream-openssl
libustream-mbedtls
libustream-wolfssl

这个应该自己编译的时候自己选，确实不应该直接写死
可能 commitor 有另外的考量，也可能这个项目下的一些 app 有特殊依赖
希望能有说明

**Comment by coolsnowwolf** [comment]
主要是为了节省空间，一个固件里面没必要默认有 3套不同的 SSL 的 lib ，而且 mbedtls 性能低
