### ISSUE TITLE
来自IPSec VPN的流量走不了SSR+

### ISSUE THREAD

**Issue by kqkq** [fw876/helloworld#609]
编译的最新的Lean‘s Openwrt，SSR+使用的Trojan协议。

开启了IPSec VPN，在外部可以成功连接VPN，可以正常访问内网设备、可以正常连接百度等互联网网站，但所有被墙网站无法访问，不论开全局模式还是GFW列表模式都不行，似乎从IPSec VPN过来的流量不会经过SSR+

经过搜索，发现了 https://github.com/coolsnowwolf/lede/issues/5262 这个issue里提到了一个解决方法

```
iptables -t nat -I PREROUTING -p tcp -m policy --dir in --pol ipsec --proto esp -j SS_SPEC_WAN_AC
iptables -t mangle -I PREROUTING -p udp -m policy --dir in --pol ipsec --proto esp -j SS_SPEC_TPROXY
```

经尝试后无效，而且似乎在 `/var/etc/shadowsocksr.include` 中已经有了这条规则，查看iptables似乎也添加成功了

```
# iptables -t nat -L
Chain PREROUTING (policy ACCEPT)
target     prot opt source               destination
SS_SPEC_WAN_AC  tcp  --  anywhere             anywhere             policy match dir in pol ipsec proto esp
......
```

求问下一步该如何debug🤔 非常感谢！

**Comment by coolsnowwolf** [comment]
SSRPlus 允许的接口

**Comment by kqkq** [comment]
> SSRPlus 允许的接口

非常感谢！按照您的指导，在SSRPlus的访问控制 - 接口控制中勾选了VPN接口就解决了！

**Comment by luoyulong-CQMU** [comment]
nice
