### ISSUE TITLE
pdnsd拒绝ipv6解析导致DNS随机解析不存在问题

### ISSUE THREAD

**Issue by z826540272** [fw876/helloworld#612]
经常打不开一些网站,常见于Google网站
pdnsd-ctl dump |grep -A 2 "domain negated"
可以查询到
删除 			reject= ::/0;
			reject_policy= negate;
后问题解决

**Comment by z826540272** [comment]
解决办法,废掉pdnsd DNS缓存,或者修改pdnsd源码过滤ipv6结果.

**Comment by XiaoliChan** [comment]
Same issue
![image](https://user-images.githubusercontent.com/30458572/128598192-ee38aad4-c6f2-444b-b8cb-169ca91e2a60.png)

**Comment by XiaoliChan** [comment]
@z826540272 You should revert your commit :)

**Comment by 4860575** [comment]
> 经常打不开一些网站，常见于谷歌网站> pdnsd-ctl 转储 |grep-A 2“域否定”> 可以查询到> 删除拒绝= */0；>拒绝_policy=否定；> 后问题解决
s我的终端（mac os）现在默认解析服务器是op的ipv6地址。一开始我还以为是梯子问题，现在ok了

**Comment by XiaoliChan** [comment]
Fixed.
