### ISSUE TITLE
dns解析模式使用PDNSD时会出现google play store无法访问的问题

### ISSUE THREAD

**Issue by Benjamin23333** [fw876/helloworld#615]
昨天更新版本后是用了一段时间，发现ssp在dns解析模式使用PDNSD时会出现google play store无法访问的问题，甚至也出现google.com.hk间歇性访问的现象，在“状态”页面进行谷歌的连接性检查显示错误，重置PDNSD缓存后，连接性回归正常，但是仍无法访问google play，过一会连接性检查再次显示错误，重置PDNSD缓存后，连接性又回归正常，多次复现，但仍然无法访问google play，改为使用DNS2SOKS后一切正常
![1628379300193](https://user-images.githubusercontent.com/54323063/128616328-e09dd7a0-023d-480b-9b96-dcb610cbe3b5.jpg)

**Comment by 4860575** [comment]
注释掉 reject=::/0;
 	    reject_policy=negate;
           reject_recursively=on;
试一下

**Comment by Benjamin23333** [comment]
> 注释掉 reject=::/0;
> reject_policy=negate;
> reject_recursively=on;
> 试一下
> 或者重启一下pdnsd

你说的注释掉的这些，在哪个文件里

**Comment by z826540272** [comment]
PDNSD的bug,过滤ipv6地址 缓存会不稳定,过段时间就返回NX DOMAIN

**Comment by z826540272** [comment]
> 注释掉 reject=::/0;
> reject_policy=negate;
> reject_recursively=on;
> 试一下
> 或者重启一下pdnsd

直接用dns2socks就行了
