### ISSUE TITLE
编译时出错

### ISSUE THREAD

**Issue by qqsir-dev** [fw876/helloworld#621]
make[2]: *** [Makefile:85: /home/qqsir/lede/dl/xray-plugin-1.4.2.tar.gz] Error 2
make[2]: Leaving directory '/home/qqsir/lede/feeds/helloworld/xray-plugin'
time: package/feeds/helloworld/xray-plugin/download#0.11#0.03#0.34
    ERROR: package/feeds/helloworld/xray-plugin failed to build.
make[1]: *** [package/Makefile:116: package/feeds/helloworld/xray-plugin/download] Error 1
make[1]: *** Waiting for unfinished jobs....
make[2]: Entering directory '/home/qqsir/lede/feeds/luci/applications/luci-app-samba'
make[2]: Nothing to be done for 'download'.
make[2]: Leaving directory '/home/qqsir/lede/feeds/luci/collections/luci'
time: package/feeds/luci/luci/download#0.15#0.05#0.44
mkdir -p /home/qqsir/lede/dl
SHELL= flock /home/qqsir/lede/tmp/.grub-2.06.tar.xz.flock -c '

**Comment by EnnawYang** [comment]
git pull

**Comment by EnnawYang** [comment]
已经修过了，我这编译也通过

**Comment by EnnawYang** [comment]
是feeds的话更新下feeds

**Comment by qqsir-dev** [comment]
feeds也update了，怎么还是不行啊？？？

**Comment by EnnawYang** [comment]
那我咋知道，难不成脸黑？根据你刚刚在lede库里的issue来看，你拉取的源码是修复之前的  
https://github.com/EnnawYang/build-openwrt-and-repack/actions/runs/1119529993 ， 我的刚刚编译好，昨晚的是失败的

**Comment by qqsir-dev** [comment]
我整个都删除了，重新来一遍看看，谢谢！
