### ISSUE TITLE
DNS解系

### ISSUE THREAD

**Issue by jackson-lx** [fw876/helloworld#623]
在使用passwall的时候，使用google的情况还是会出现偶尔打不开的情况，作者是否也可以国内的DNS解析上加上DOH或是DOT的选项呢？目前阿理的DOH与DOT可以在chorme的浏览器器运行。不知道这个问题能不能有助于解决google搜索有时会打不开的情况。

**Comment by XiaoliChan** [comment]
First, your feedback is for PassWall project, but this is HelloWorld repository.

Second, the PDNSD resolver seen does not support DOH or DOT, but you can specify other DNS resolvers under port 5353 you want, like CoreDNS, Unbound, and so on.
