### ISSUE TITLE
谷歌搜索链接失败

### ISSUE THREAD

**Issue by jackson-lx** [fw876/helloworld#627]
作者你好，我在使用SSP的时候，访问油管等其它网都没有问题，唯有google.com搜索，时而会出现打不开的情况，而在打不开谷歌搜索的同时，油管等其它网也是没有问题的，在什么都不动，不断点击刷新，有的时候几十秒就恢复正常，有的时候会有1两分钟，打开之后就不会有问题了，过个半天或是一天，又出现这种情况，是否在ssp中单独有对google.com搜索的优化可能？

**Comment by flyhong666** [comment]
一切正常正常。。。改用白名单试试呗。。。
