### ISSUE TITLE
系统日志错误(具体原因未知）：daemon.err /usr/bin/ss-redir[6552]: accept: No file descriptors available

### ISSUE THREAD

**Issue by kfen** [fw876/helloworld#63]
自己也摸索很久，没找到具体原因出在哪。
后来看了下之前网友lssues也有类似问题出现，貌似之后也没有具体原因以及解决办法。
比如：https://github.com/coolsnowwolf/lede/issues/4301

https://github.com/coolsnowwolf/lede/issues/3451

https://github.com/coolsnowwolf/lede/issues/4126

大量的错误日志：daemon.err /usr/bin/ss-redir[6552]: accept: No file descriptors available

相隔几天就会出现，无规律，很奇怪。

**Comment by zxlhhyccc** [comment]
> 自己也摸索很久，没找到具体原因出在哪。
> 后来看了下之前网友lssues也有类似问题出现，貌似之后也没有具体原因以及解决办法。
> 比如：[coolsnowwolf/lede#4301](https://github.com/coolsnowwolf/lede/issues/4301)
> 
> [coolsnowwolf/lede#3451](https://github.com/coolsnowwolf/lede/issues/3451)
> 
> 大量的错误日志：daemon.err /usr/bin/ss-redir[6552]: accept: No file descriptors available
> 
> 相隔几天就会出现，无规律，很奇怪。

未发现该问题。。。。

**Comment by coolsnowwolf** [comment]
文件描述符满了

**Comment by kfen** [comment]
> 文件描述符满了

感谢大雕啊，已解决。

**Comment by itfish92** [comment]
大佬,这个日志报错怎么解决啊?我的也一直报这个错误
