### ISSUE TITLE
op重启后ssrp加载的节点不生效

### ISSUE THREAD

**Issue by bonnyandsky** [fw876/helloworld#635]
ssrp版本号
luci-app-ssr-plus | 184-9
op系统重启后【谷歌】连通性检查都是失败的,要关闭节点,重新打开才可以正常使用
![1](https://user-images.githubusercontent.com/30990861/131613108-71293d84-b83c-492f-9252-0766593dad88.png)
![2](https://user-images.githubusercontent.com/30990861/131613113-b69e710a-ea65-42b7-9896-f518bd3374e0.png)

**Comment by 1715173329** [comment]
无法复现该问题，请尝试使用最新源码并重新测试。
