### ISSUE TITLE
docker 中openwrt 使用两个adguardhome 后dns 解析问题

### ISSUE THREAD

**Issue by lo-w** [fw876/helloworld#636]
hello,
目前遇到一点dns解析的问题. 希望有大佬可以稍微指点一下.

环境:
自编译lean 的openwrt 且安装在docker 环境中
启动了两个adguard home 用来做dns 加速解析

在未启动ssr plus 的情况下 两个pod的解析都没有任何问题
pod for 国内.
/opt/adguardhome/work # nslookup www.baidu.com
Server:         127.0.0.11
Address:        127.0.0.11:53

Non-authoritative answer:
www.baidu.com   canonical name = www.a.shifen.com
Name:   www.a.shifen.com
Address: 180.101.49.12
Name:   www.a.shifen.com
Address: 180.101.49.11

pod for 国外.
/opt/adguardhome/work # nslookup www.google.com
Server:         127.0.0.11
Address:        127.0.0.11:53

Non-authoritative answer:
Name:   www.google.com
Address: 108.160.165.141

在启动ssr plus 的情况下, 访问国外dns 设置为默认的list (8.8.8.8/8.8.4.4) dns解析没有问题
pod for 国内.
/opt/adguardhome/work # nslookup www.baidu.com
Server:         127.0.0.11
Address:        127.0.0.11:53

Non-authoritative answer:
www.baidu.com   canonical name = www.a.shifen.com
Name:   www.a.shifen.com
Address: 180.101.49.11
Name:   www.a.shifen.com
Address: 180.101.49.12

pod for 国外.
/opt/adguardhome/work # nslookup www.google.com
Server:         127.0.0.11
Address:        127.0.0.11:53

Non-authoritative answer:
Name:   www.google.com
Address: 172.253.115.147
Name:   www.google.com
Address: 172.253.115.105
Name:   www.google.com
Address: 172.253.115.106
Name:   www.google.com
Address: 172.253.115.104
Name:   www.google.com
Address: 172.253.115.99
Name:   www.google.com
Address: 172.253.115.103

在启动ssr plus 的情况下, 将访问国外dns 设置为国外的pod ip时
所有的dns解析失效了. 并且gui 中测试上游dns 无响应, 提示: 无法使用，请检查你输入的是否正确
pod for 国外.
/opt/adguardhome/work # nslookup www.google.com
Server:         127.0.0.11
Address:        127.0.0.11:53

*** Can't find www.google.com: No answer

*** Can't find www.google.com: No answer

BR//lo

**Comment by lo-w** [comment]
hello,

经过查看adguardhome 的log 和收集的tcpdump, 分析如下
在未开启ssr plus 情况下, 当adguardhome 发起dnsquery请求. 对应的dns server 能够有正常的返回,
在开启ssr plus 情况下,  当adguardhome 发起dnsquery请求. 对应的请求会被gateway redirect回adguardhome, 形成了一个回环的请求, 导致每次对dns server 的请求被不停的重定向到发起端. 
这个问题在 lean 的openwrt 和ssr plus 下都有发现. 不知道是不是dnsmasq full 的行为.

![image](https://user-images.githubusercontent.com/40700499/132127016-8cce5d9a-0769-462e-81a2-2473d7ee02f2.png)

BR//lo

**Comment by lo-w** [comment]
[dns.zip](https://github.com/fw876/helloworld/files/7111597/dns.zip)
相关的log
BR//lo

**Comment by lo-w** [comment]
没有任何的回复就关了?
BR//lo

**Comment by 1715173329** [comment]
I don't see the point of continuing wasting time on this.
