### ISSUE TITLE
go get : xxx  local error: tls: bad record MAC

### ISSUE THREAD

**Issue by Yofo-me** [fw876/helloworld#637]
![image](https://user-images.githubusercontent.com/55388087/131819722-ff058397-d34d-4ddf-a1fa-c84e47f56d5c.png)
只要是本地编译就报这个错误，编译环境已全局科学了的，能访问YOUTUBE，终端下curl -I youtube.com或者ping google.com都能成功。很奇怪

**Comment by 1715173329** [comment]
你网寄了。
