### ISSUE TITLE
807X开了NSS加速，游戏模式不起作用

### ISSUE THREAD

**Issue by pwater65** [fw876/helloworld#638]
AX6和中兴MF269都一样，把switch的ip添加到了游戏模式，还是显示NAT F，而且获取到的ip还是主节点的IP，而不是游戏模式节点的IP。同一节点x86正常

**Comment by 1715173329** [comment]
这个是 NSS-ECM 驱动导致的问题，如果对 UDP 需求强烈可以暂时先关闭 ecm。
`/etc/init.d/qca-nss-ecm {stop,disable}`
