### ISSUE TITLE
naiveproxy在openwrt一起编译时出现错误

### ISSUE THREAD

**Issue by clk01** [fw876/helloworld#649]
大佬好！
最近在openwrt编译时会出现naiveproxy错误，导致编译无法继续，希望到可以查看一下是不是有依赖下载地址不正确。
谢谢。

**Comment by rq1025330** [comment]
mt7621出现这个问题

**Comment by clk01** [comment]
> mt7621出现这个问题
啊忘了说型号。 谢谢提醒了我。我编译的是小米路由器4c MediaTek MT7628AN。

**Comment by clk01** [comment]
> mt7621出现这个问题

啊忘了说型号。 谢谢提醒了我。我编译的是小米路由器4c MediaTek MT7628AN。

**Comment by smallprogram** [comment]
VPS实测没毛病。应该是你本地网络的问题

**Comment by rq1025330** [comment]
云编译的  cr6606  9月6日后就不能编译成功了

**Comment by clk01** [comment]
> 本地开全局没毛病，VPS使用wget下载也没毛病。应该是你网络环境问题。

github的云编译和本地编译都不行。

**Comment by deplives** [comment]
今早刚编译过，没问题，检查网络环境，而且你这一句编译出现错误，连个日志也没有，怎么排查问题

**Comment by m-aslo** [comment]
我這裏也遇到這個問題。不知道什麼原因。

`Done. Made 381 targets from 130 files in 303ms
MAKEFLAGS="" /home/useradmin/Code/lede/staging_dir/host/bin/ninja  -j1 -C "/home/useradmin/Code/lede/build_dir/target-mipsel_24kc_musl/naiveproxy-93.0.4577.63-1/src/out/Release" naive
ninja: Entering directory `/home/useradmin/Code/lede/build_dir/target-mipsel_24kc_musl/naiveproxy-93.0.4577.63-1/src/out/Release'
[1/2110] CC obj/base/third_party/xdg_mime/xdg_mime/xdgmimemagic.o
FAILED: obj/base/third_party/xdg_mime/xdg_mime/xdgmimemagic.o 
../../third_party/llvm-build/Release+Asserts/bin/clang -MMD -MF obj/base/third_party/xdg_mime/xdg_mime/xdgmimemagic.o.d -DOFFICIAL_BUILD -D_FILE_OFFSET_BITS=64 -D_LARGEFILE_SOURCE -D_LARGEFILE64_SOURCE -DNO_UNWIND_TABLES -D_GNU_SOURCE -D_LIBCPP_HAS_MUSL_LIBC -D__UCLIBC__ -DCR_CLANG_REVISION=\"llvmorg-13-init-15163-g98033fdc-1\" -D_LIBCPP_ABI_UNSTABLE -D_LIBCPP_DISABLE_VISIBILITY_ANNOTATIONS -D_LIBCXXABI_DISABLE_VISIBILITY_ANNOTATIONS -D_LIBCPP_ENABLE_NODISCARD -DCR_LIBCXX_REVISION=79a2e924d96e2fc1e4b937c42efd08898fa472d7 -DCR_SYSROOT_HASH=eb577cef43088b7e0540950c74f994267631d4cd -DNDEBUG -DNVALGRIND -DDYNAMIC_ANNOTATIONS_ENABLED=0 -I../.. -Igen -I../../buildtools/third_party/libc++ -fno-delete-null-pointer-checks -fno-ident -fno-strict-aliasing --param=ssp-buffer-size=4 -fstack-protector -fno-unwind-tables -fno-asynchronous-unwind-tables -fPIC -pthread -fcolor-diagnostics -fmerge-all-constants -fcrash-diagnostics-dir=../../tools/clang/crashreports -mllvm -instcombine-lower-dbg-declare=0 -fcomplete-member-pointers --target=mipsel-openwrt-linux-musl -march=mipsel -mcpu=mips32r2 -msoft-float -mtune=24kc -Wno-builtin-macro-redefined -D__DATE__= -D__TIME__= -D__TIMESTAMP__= -Xclang -fdebug-compilation-dir -Xclang . -no-canonical-prefixes -O2 -fdata-sections -ffunction-sections -fno-unique-section-names -fno-omit-frame-pointer -g0 -ftrivial-auto-var-init=pattern -fprofile-instr-use=../../chrome/build/pgo_profiles/chrome-linux-4577-1629902302-97a75bab19e52f72bda9d9d33032dd998433e8c2.profdata -Wno-profile-instr-unprofiled -Wno-profile-instr-out-of-date -Wno-backend-plugin -fvisibility=hidden -Xclang -add-plugin -Xclang find-bad-constructs -Xclang -plugin-arg-find-bad-constructs -Xclang checked-ptr-as-trivial-member -Xclang -plugin-arg-find-bad-constructs -Xclang check-ipc -Wheader-hygiene -Wstring-conversion -Wtautological-overlap-compare -Wall -Wno-unused-variable -Wno-c++11-narrowing -Wno-misleading-indentation -Wno-missing-field-initializers -Wno-unused-parameter -Wno-unneeded-internal-declaration -Wno-undefined-var-template -Wenum-compare-conditional -Wno-psabi -Wno-ignored-pragma-optimize -Wno-final-dtor-non-final-class -Wno-builtin-assume-aligned-alignment -Wno-deprecated-copy -Wno-non-c-typedef-for-linkage -Wno-unused-but-set-parameter -Wno-unused-but-set-variable -std=c11 --sysroot=../../../../../../staging_dir/toolchain-mipsel_24kc_gcc-8.4.0_musl -Wno-implicit-fallthrough -c ../../base/third_party/xdg_mime/xdgmimemagic.c -o obj/base/third_party/xdg_mime/xdg_mime/xdgmimemagic.o
fatal error: error in backend: Relocation for CG Profile could not be created: unknown relocation name
PLEASE submit a bug report to https://crbug.com and run tools/clang/scripts/process_crashreports.py (only works inside Google) which will upload a report and include the crash backtrace, preprocessed source, and associated run script.
Stack dump:
0.	Program arguments: ../../third_party/llvm-build/Release+Asserts/bin/clang -MMD -MF obj/base/third_party/xdg_mime/xdg_mime/xdgmimemagic.o.d -DOFFICIAL_BUILD -D_FILE_OFFSET_BITS=64 -D_LARGEFILE_SOURCE -D_LARGEFILE64_SOURCE -DNO_UNWIND_TABLES -D_GNU_SOURCE -D_LIBCPP_HAS_MUSL_LIBC -D__UCLIBC__ -DCR_CLANG_REVISION=\"llvmorg-13-init-15163-g98033fdc-1\" -D_LIBCPP_ABI_UNSTABLE -D_LIBCPP_DISABLE_VISIBILITY_ANNOTATIONS -D_LIBCXXABI_DISABLE_VISIBILITY_ANNOTATIONS -D_LIBCPP_ENABLE_NODISCARD -DCR_LIBCXX_REVISION=79a2e924d96e2fc1e4b937c42efd08898fa472d7 -DCR_SYSROOT_HASH=eb577cef43088b7e0540950c74f994267631d4cd -DNDEBUG -DNVALGRIND -DDYNAMIC_ANNOTATIONS_ENABLED=0 -I../.. -Igen -I../../buildtools/third_party/libc++ -fno-delete-null-pointer-checks -fno-ident -fno-strict-aliasing --param=ssp-buffer-size=4 -fstack-protector -fno-unwind-tables -fno-asynchronous-unwind-tables -fPIC -pthread -fcolor-diagnostics -fmerge-all-constants -fcrash-diagnostics-dir=../../tools/clang/crashreports -mllvm -instcombine-lower-dbg-declare=0 -fcomplete-member-pointers --target=mipsel-openwrt-linux-musl -march=mipsel -mcpu=mips32r2 -msoft-float -mtune=24kc -Wno-builtin-macro-redefined -D__DATE__= -D__TIME__= -D__TIMESTAMP__= -Xclang -fdebug-compilation-dir -Xclang . -no-canonical-prefixes -O2 -fdata-sections -ffunction-sections -fno-unique-section-names -fno-omit-frame-pointer -g0 -ftrivial-auto-var-init=pattern -fprofile-instr-use=../../chrome/build/pgo_profiles/chrome-linux-4577-1629902302-97a75bab19e52f72bda9d9d33032dd998433e8c2.profdata -Wno-profile-instr-unprofiled -Wno-profile-instr-out-of-date -Wno-backend-plugin -fvisibility=hidden -Xclang -add-plugin -Xclang find-bad-constructs -Xclang -plugin-arg-find-bad-constructs -Xclang checked-ptr-as-trivial-member -Xclang -plugin-arg-find-bad-constructs -Xclang check-ipc -Wheader-hygiene -Wstring-conversion -Wtautological-overlap-compare -Wall -Wno-unused-variable -Wno-c++11-narrowing -Wno-misleading-indentation -Wno-missing-field-initializers -Wno-unused-parameter -Wno-unneeded-internal-declaration -Wno-undefined-var-template -Wenum-compare-conditional -Wno-psabi -Wno-ignored-pragma-optimize -Wno-final-dtor-non-final-class -Wno-builtin-assume-aligned-alignment -Wno-deprecated-copy -Wno-non-c-typedef-for-linkage -Wno-unused-but-set-parameter -Wno-unused-but-set-variable -std=c11 --sysroot=../../../../../../staging_dir/toolchain-mipsel_24kc_gcc-8.4.0_musl -Wno-implicit-fallthrough -c ../../base/third_party/xdg_mime/xdgmimemagic.c -o obj/base/third_party/xdg_mime/xdg_mime/xdgmimemagic.o
1.	<eof> parser at end of file
2.	Code generation
#0 0x00000000031b0248 (../../third_party/llvm-build/Release+Asserts/bin/clang+0x31b0248)
clang: error: clang frontend command failed with exit code 70 (use -v to see invocation)
clang version 13.0.0 (https://github.com/llvm/llvm-project/ 98033fdc50e61273b1d5c77ba5f0f75afe3965c1)
Target: mipsel-openwrt-linux-musl
Thread model: posix
InstalledDir: ../../third_party/llvm-build/Release+Asserts/bin
clang: note: diagnostic msg: 
********************

PLEASE ATTACH THE FOLLOWING FILES TO THE BUG REPORT:
Preprocessed source(s) and associated run script(s) are located at:
clang: note: diagnostic msg: ../../tools/clang/crashreports/xdgmimemagic-2412dd.c
clang: note: diagnostic msg: ../../tools/clang/crashreports/xdgmimemagic-2412dd.sh
clang: note: diagnostic msg: 

********************
ninja: build stopped: subcommand failed.
make[3]: *** [Makefile:139: /home/useradmin/Code/lede/build_dir/target-mipsel_24kc_musl/naiveproxy-93.0.4577.63-1/.built] Error 1
make[3]: Leaving directory '/home/useradmin/Code/lede/feeds/helloworld/naiveproxy'
time: package/feeds/helloworld/naiveproxy/compile#0.43#0.47#0.73
    ERROR: package/feeds/helloworld/naiveproxy failed to build.
make[2]: *** [package/Makefile:116: package/feeds/helloworld/naiveproxy/compile] Error 1
make[2]: Leaving directory '/home/useradmin/Code/lede'
make[1]: *** [package/Makefile:110: /home/useradmin/Code/lede/staging_dir/target-mipsel_24kc_musl/stamp/.package_compile] Error 2
make[1]: Leaving directory '/home/useradmin/Code/lede'
make: *** [/home/useradmin/Code/lede/include/toplevel.mk:230：world] 错误 2
`

**Comment by smallprogram** [comment]
https://github.com/fw876/helloworld/pull/651
