### ISSUE TITLE
openwrt v21.02 编译错误

### ISSUE THREAD

**Issue by yfdoor** [fw876/helloworld#652]
helloword 在最新的 v21.02.0编译下会报如下错误，去掉 ssr 后可以编译正常。有人遇到过类似的问题，有解决方案吗？

> 
2021-09-15T01:27:57.9223091Z  * check_data_file_clashes: Package libustream-openssl20201210 wants to install file /home/runner/work/OpenWrt/OpenWrt/openwrt/build_dir/target-x86_64_musl/root-x86/lib/libustream-ssl.so
2021-09-15T01:27:57.9224387Z Configuring libnghttp2-14.
2021-09-15T01:27:57.9225882Z 	But that file is already provided by package  * libustream-wolfssl20201210
2021-09-15T01:27:57.9226879Z Configuring ca-bundle.
2021-09-15T01:27:57.9227976Z  * opkg_install_cmd: Cannot install package libustream-openssl20201210.
2021-09-15T01:27:57.9228666Z Configuring libcurl4.
2021-09-15T01:27:57.9252523Z  * check_data_file_clashes: Package libustream-openssl20201210 wants to install file /home/runner/work/OpenWrt/OpenWrt/openwrt/build_dir/target-x86_64_musl/root-x86/lib/libustream-ssl.so
2021-09-15T01:27:57.9255608Z 	But that file is already provided by package  * libustream-wolfssl20201210
2021-09-15T01:27:57.9257029Z  * opkg_install_cmd: Cannot install package luci-app-ssr-plus.
2021-09-15T01:27:57.9258031Z make[2]: *** [package/Makefile:69: package/install] Error 255
> 

ACTION LINK: [link](https://github.com/yfdoor/OpenWrt/actions/runs/1235633392)

**Comment by jgsports** [comment]
这几天我也是有同样的错误，只要用github actions云编译带ssr plus 的lean openwrt，就无法完成，试了好多个设备型号

**Comment by acooler15** [comment]
问题很明显，libustream-wolfssl与libustream-openssl冲突了。

**Comment by yfdoor** [comment]
> 问题很明显，libustream-wolfssl与libustream-openssl冲突了。

我看到是这个error 了，可是怎么解决呢，望指教

**Comment by acooler15** [comment]
改luci-app-ssr-plus的Makefile，将libustream-openssl改为libustream-wolfssl。
或者
取消选中libustream-wolfssl(在Libraries里)



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2021年9月20日(周一) 晚上9:09
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [fw876/helloworld] openwrt v21.02 编译错误 (#652)




  
问题很明显，libustream-wolfssl与libustream-openssl冲突了。
  
我看到是这个error 了，可是怎么解决呢，望指教
 
—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by acooler15** [comment]
> > 问题很明显，libustream-wolfssl与libustream-openssl冲突了。
> 
> 我看到是这个error 了，可是怎么解决呢，望指教

```
include $(TOPDIR)/rules.mk

PKG_NAME:=luci-app-ssr-plus
PKG_VERSION:=184
PKG_RELEASE:=9

PKG_CONFIG_DEPENDS:= \
	CONFIG_PACKAGE_$(PKG_NAME)_INCLUDE_Kcptun \
	CONFIG_PACKAGE_$(PKG_NAME)_INCLUDE_NaiveProxy \
	CONFIG_PACKAGE_$(PKG_NAME)_INCLUDE_Redsocks2 \
	CONFIG_PACKAGE_$(PKG_NAME)_INCLUDE_Shadowsocks_Libev_Client \
	CONFIG_PACKAGE_$(PKG_NAME)_INCLUDE_Shadowsocks_Libev_Server \
	CONFIG_PACKAGE_$(PKG_NAME)_INCLUDE_Shadowsocks_Rust_Client \
	CONFIG_PACKAGE_$(PKG_NAME)_INCLUDE_Shadowsocks_Rust_Server \
	CONFIG_PACKAGE_$(PKG_NAME)_INCLUDE_ShadowsocksR_Libev_Client \
	CONFIG_PACKAGE_$(PKG_NAME)_INCLUDE_ShadowsocksR_Libev_Server \
	CONFIG_PACKAGE_$(PKG_NAME)_INCLUDE_Simple_Obfs \
	CONFIG_PACKAGE_$(PKG_NAME)_INCLUDE_Trojan \
	CONFIG_PACKAGE_$(PKG_NAME)_INCLUDE_V2ray_Plugin \
	CONFIG_PACKAGE_$(PKG_NAME)_INCLUDE_Xray

LUCI_TITLE:=SS/SSR/V2Ray/Trojan/NaiveProxy/Socks5/Tun LuCI interface
LUCI_PKGARCH:=all
LUCI_DEPENDS:=+coreutils +coreutils-base64 +dns2socks +dnsmasq-full +ipset \
	+ip-full +iptables-mod-tproxy +lua +libuci-lua +microsocks +pdnsd-alt \
	+tcping +resolveip +shadowsocksr-libev-ssr-check +uclient-fetch \
	+DEFAULT_libustream-wolfssl:libustream-wolfssl \
	+(!DEFAULT_libustream-wolfssl):libustream-openssl \
	+PACKAGE_$(PKG_NAME)_INCLUDE_Kcptun:kcptun-client \
	+PACKAGE_$(PKG_NAME)_INCLUDE_NaiveProxy:naiveproxy \
	+PACKAGE_$(PKG_NAME)_INCLUDE_Redsocks2:redsocks2 \
	+PACKAGE_$(PKG_NAME)_INCLUDE_Shadowsocks_Libev_Client:shadowsocks-libev-ss-local \
	+PACKAGE_$(PKG_NAME)_INCLUDE_Shadowsocks_Libev_Client:shadowsocks-libev-ss-redir \
	+PACKAGE_$(PKG_NAME)_INCLUDE_Shadowsocks_Libev_Server:shadowsocks-libev-ss-server \
	+PACKAGE_$(PKG_NAME)_INCLUDE_Shadowsocks_Rust_Client:shadowsocks-rust-sslocal \
	+PACKAGE_$(PKG_NAME)_INCLUDE_Shadowsocks_Rust_Server:shadowsocks-rust-ssserver \
	+PACKAGE_$(PKG_NAME)_INCLUDE_ShadowsocksR_Libev_Client:shadowsocksr-libev-ssr-local \
	+PACKAGE_$(PKG_NAME)_INCLUDE_ShadowsocksR_Libev_Client:shadowsocksr-libev-ssr-redir \
	+PACKAGE_$(PKG_NAME)_INCLUDE_ShadowsocksR_Libev_Server:shadowsocksr-libev-ssr-server \
	+PACKAGE_$(PKG_NAME)_INCLUDE_Simple_Obfs:simple-obfs \
	+PACKAGE_$(PKG_NAME)_INCLUDE_Trojan:trojan \
	+PACKAGE_$(PKG_NAME)_INCLUDE_Trojan:ipt2socks \
	+PACKAGE_$(PKG_NAME)_INCLUDE_V2ray_Plugin:v2ray-plugin \
	+PACKAGE_$(PKG_NAME)_INCLUDE_Xray:curl \
	+PACKAGE_$(PKG_NAME)_INCLUDE_Xray:xray-core

define Package/$(PKG_NAME)/config
config PACKAGE_$(PKG_NAME)_INCLUDE_Kcptun
	bool "Include Kcptun"
	default n

config PACKAGE_$(PKG_NAME)_INCLUDE_NaiveProxy
	bool "Include NaiveProxy"
	depends on !(arc||armeb||mips||mips64||powerpc)
	default n

config PACKAGE_$(PKG_NAME)_INCLUDE_Redsocks2
	bool "Include Redsocks2"
	default n

config PACKAGE_$(PKG_NAME)_INCLUDE_Shadowsocks_Libev_Client
	bool "Include Shadowsocks Libev Client"
	default y if i386||x86_64||arm

config PACKAGE_$(PKG_NAME)_INCLUDE_Shadowsocks_Libev_Server
	bool "Include Shadowsocks Libev Server"
	default y if i386||x86_64||arm

config PACKAGE_$(PKG_NAME)_INCLUDE_Shadowsocks_Rust_Client
	bool "Include Shadowsocks Rust Client"
	depends on aarch64||arm||i386||mips||mipsel||x86_64
	default y if aarch64

config PACKAGE_$(PKG_NAME)_INCLUDE_Shadowsocks_Rust_Server
	bool "Include Shadowsocks Rust Server"
	depends on aarch64||arm||i386||mips||mipsel||x86_64
	default y if aarch64

config PACKAGE_$(PKG_NAME)_INCLUDE_ShadowsocksR_Libev_Client
	bool "Include ShadowsocksR Libev Client"
	default y

config PACKAGE_$(PKG_NAME)_INCLUDE_ShadowsocksR_Libev_Server
	bool "Include ShadowsocksR Libev Server"
	default y if i386||x86_64||arm

config PACKAGE_$(PKG_NAME)_INCLUDE_Simple_Obfs
	bool "Include Shadowsocks Simple Obfs Plugin"
	default y if i386||x86_64||arm

config PACKAGE_$(PKG_NAME)_INCLUDE_Trojan
	bool "Include Trojan"
	default n

config PACKAGE_$(PKG_NAME)_INCLUDE_V2ray_Plugin
	bool "Include Shadowsocks V2ray Plugin"
	default n

config PACKAGE_$(PKG_NAME)_INCLUDE_Xray
	bool "Include Xray"
	default y if aarch64||arm||i386||x86_64
endef

define Package/$(PKG_NAME)/conffiles
/etc/config/shadowsocksr
/etc/ssrplus/
endef

include $(TOPDIR)/feeds/luci/luci.mk

# call BuildPackage - OpenWrt buildroot signature

```
这个Makefile应该可以在大雕的op和openwrt官方的master分支与openwrt-21.02分支上使用

**Comment by yfdoor** [comment]
> > > 问题很明显，libustream-wolfssl与libustream-openssl冲突了。
> > 
> > 
> > 我看到是这个error 了，可是怎么解决呢，望指教
> 
> ```
> include $(TOPDIR)/rules.mk
> 
> PKG_NAME:=luci-app-ssr-plus
> PKG_VERSION:=184
> PKG_RELEASE:=9
> 
> PKG_CONFIG_DEPENDS:= \
> 	CONFIG_PACKAGE_$(PKG_NAME)_INCLUDE_Kcptun \
> 	CONFIG_PACKAGE_$(PKG_NAME)_INCLUDE_NaiveProxy \
> 	CONFIG_PACKAGE_$(PKG_NAME)_INCLUDE_Redsocks2 \
> 	CONFIG_PACKAGE_$(PKG_NAME)_INCLUDE_Shadowsocks_Libev_Client \
> 	CONFIG_PACKAGE_$(PKG_NAME)_INCLUDE_Shadowsocks_Libev_Server \
> 	CONFIG_PACKAGE_$(PKG_NAME)_INCLUDE_Shadowsocks_Rust_Client \
> 	CONFIG_PACKAGE_$(PKG_NAME)_INCLUDE_Shadowsocks_Rust_Server \
> 	CONFIG_PACKAGE_$(PKG_NAME)_INCLUDE_ShadowsocksR_Libev_Client \
> 	CONFIG_PACKAGE_$(PKG_NAME)_INCLUDE_ShadowsocksR_Libev_Server \
> 	CONFIG_PACKAGE_$(PKG_NAME)_INCLUDE_Simple_Obfs \
> 	CONFIG_PACKAGE_$(PKG_NAME)_INCLUDE_Trojan \
> 	CONFIG_PACKAGE_$(PKG_NAME)_INCLUDE_V2ray_Plugin \
> 	CONFIG_PACKAGE_$(PKG_NAME)_INCLUDE_Xray
> 
> LUCI_TITLE:=SS/SSR/V2Ray/Trojan/NaiveProxy/Socks5/Tun LuCI interface
> LUCI_PKGARCH:=all
> LUCI_DEPENDS:=+coreutils +coreutils-base64 +dns2socks +dnsmasq-full +ipset \
> 	+ip-full +iptables-mod-tproxy +lua +libuci-lua +microsocks +pdnsd-alt \
> 	+tcping +resolveip +shadowsocksr-libev-ssr-check +uclient-fetch \
> 	+DEFAULT_libustream-wolfssl:libustream-wolfssl \
> 	+(!DEFAULT_libustream-wolfssl):libustream-openssl \
> 	+PACKAGE_$(PKG_NAME)_INCLUDE_Kcptun:kcptun-client \
> 	+PACKAGE_$(PKG_NAME)_INCLUDE_NaiveProxy:naiveproxy \
> 	+PACKAGE_$(PKG_NAME)_INCLUDE_Redsocks2:redsocks2 \
> 	+PACKAGE_$(PKG_NAME)_INCLUDE_Shadowsocks_Libev_Client:shadowsocks-libev-ss-local \
> 	+PACKAGE_$(PKG_NAME)_INCLUDE_Shadowsocks_Libev_Client:shadowsocks-libev-ss-redir \
> 	+PACKAGE_$(PKG_NAME)_INCLUDE_Shadowsocks_Libev_Server:shadowsocks-libev-ss-server \
> 	+PACKAGE_$(PKG_NAME)_INCLUDE_Shadowsocks_Rust_Client:shadowsocks-rust-sslocal \
> 	+PACKAGE_$(PKG_NAME)_INCLUDE_Shadowsocks_Rust_Server:shadowsocks-rust-ssserver \
> 	+PACKAGE_$(PKG_NAME)_INCLUDE_ShadowsocksR_Libev_Client:shadowsocksr-libev-ssr-local \
> 	+PACKAGE_$(PKG_NAME)_INCLUDE_ShadowsocksR_Libev_Client:shadowsocksr-libev-ssr-redir \
> 	+PACKAGE_$(PKG_NAME)_INCLUDE_ShadowsocksR_Libev_Server:shadowsocksr-libev-ssr-server \
> 	+PACKAGE_$(PKG_NAME)_INCLUDE_Simple_Obfs:simple-obfs \
> 	+PACKAGE_$(PKG_NAME)_INCLUDE_Trojan:trojan \
> 	+PACKAGE_$(PKG_NAME)_INCLUDE_Trojan:ipt2socks \
> 	+PACKAGE_$(PKG_NAME)_INCLUDE_V2ray_Plugin:v2ray-plugin \
> 	+PACKAGE_$(PKG_NAME)_INCLUDE_Xray:curl \
> 	+PACKAGE_$(PKG_NAME)_INCLUDE_Xray:xray-core
> 
> define Package/$(PKG_NAME)/config
> config PACKAGE_$(PKG_NAME)_INCLUDE_Kcptun
> 	bool "Include Kcptun"
> 	default n
> 
> config PACKAGE_$(PKG_NAME)_INCLUDE_NaiveProxy
> 	bool "Include NaiveProxy"
> 	depends on !(arc||armeb||mips||mips64||powerpc)
> 	default n
> 
> config PACKAGE_$(PKG_NAME)_INCLUDE_Redsocks2
> 	bool "Include Redsocks2"
> 	default n
> 
> config PACKAGE_$(PKG_NAME)_INCLUDE_Shadowsocks_Libev_Client
> 	bool "Include Shadowsocks Libev Client"
> 	default y if i386||x86_64||arm
> 
> config PACKAGE_$(PKG_NAME)_INCLUDE_Shadowsocks_Libev_Server
> 	bool "Include Shadowsocks Libev Server"
> 	default y if i386||x86_64||arm
> 
> config PACKAGE_$(PKG_NAME)_INCLUDE_Shadowsocks_Rust_Client
> 	bool "Include Shadowsocks Rust Client"
> 	depends on aarch64||arm||i386||mips||mipsel||x86_64
> 	default y if aarch64
> 
> config PACKAGE_$(PKG_NAME)_INCLUDE_Shadowsocks_Rust_Server
> 	bool "Include Shadowsocks Rust Server"
> 	depends on aarch64||arm||i386||mips||mipsel||x86_64
> 	default y if aarch64
> 
> config PACKAGE_$(PKG_NAME)_INCLUDE_ShadowsocksR_Libev_Client
> 	bool "Include ShadowsocksR Libev Client"
> 	default y
> 
> config PACKAGE_$(PKG_NAME)_INCLUDE_ShadowsocksR_Libev_Server
> 	bool "Include ShadowsocksR Libev Server"
> 	default y if i386||x86_64||arm
> 
> config PACKAGE_$(PKG_NAME)_INCLUDE_Simple_Obfs
> 	bool "Include Shadowsocks Simple Obfs Plugin"
> 	default y if i386||x86_64||arm
> 
> config PACKAGE_$(PKG_NAME)_INCLUDE_Trojan
> 	bool "Include Trojan"
> 	default n
> 
> config PACKAGE_$(PKG_NAME)_INCLUDE_V2ray_Plugin
> 	bool "Include Shadowsocks V2ray Plugin"
> 	default n
> 
> config PACKAGE_$(PKG_NAME)_INCLUDE_Xray
> 	bool "Include Xray"
> 	default y if aarch64||arm||i386||x86_64
> endef
> 
> define Package/$(PKG_NAME)/conffiles
> /etc/config/shadowsocksr
> /etc/ssrplus/
> endef
> 
> include $(TOPDIR)/feeds/luci/luci.mk
> 
> # call BuildPackage - OpenWrt buildroot signature
> ```
> 
> 这个Makefile应该可以在大雕的op和openwrt官方的master分支与openwrt-21.02分支上使用

好的，多谢，大佬可以直接 PR 到这里吗？这样大家都可以修复这个问题

**Comment by jgsports** [comment]
使用了acooler15的方法，还是出错，疑似是github的行为
Run cd openwrt
2 thread compile
 make[1] world
 make[2] tools/compile
 make[2] package/cleanup
 make[3] -C tools/flock compile
 make[3] -C tools/xz compile
 make[3] -C tools/sed compile
 make[3] -C tools/patch compile
 make[3] -C tools/tar compile
 make[3] -C tools/m4 compile
 make[3] -C tools/autoconf-archive compile
 make[3] -C tools/pkgconf compile
 make[3] -C tools/ninja compile
 make[3] -C tools/cpio compile
 make[3] -C tools/lzma compile
 make[3] -C tools/mtools compile
 make[3] -C tools/patch-image compile
 make[3] -C tools/sstrip compile
 make[3] -C tools/ucl compile
 make[3] -C tools/xxd compile
 make[3] -C tools/zip compile
 make[3] -C tools/expat compile
 make[3] -C tools/autoconf compile
 make[3] -C tools/libressl compile
 make[3] -C tools/automake compile
 make[3] -C tools/missing-macros compile
 make[3] -C tools/dosfstools compile
 make[3] -C tools/upx compile
 make[3] -C tools/libtool compile
 make[3] -C tools/cmake compile
 make[3] -C tools/mkimage compile
 make[3] -C tools/mklibs compile
 make[3] -C tools/mm-macros compile
 make[3] -C tools/patchelf compile
 make[3] -C tools/gmp compile
 make[3] -C tools/flex compile
 make[3] -C tools/e2fsprogs compile
 make[3] -C tools/fakeroot compile
 make[3] -C tools/gengetopt compile
 make[3] -C tools/mpfr compile
 make[3] -C tools/bison compile
 make[3] -C tools/mpc compile
 make[3] -C tools/bc compile
 make[3] -C tools/findutils compile
 make[3] -C tools/padjffs2 compile
 make[3] -C tools/quilt compile
 make[3] -C tools/zlib compile
 make[3] -C tools/zstd compile
 make[3] -C tools/firmware-utils compile
 make[3] -C tools/make-ext4fs compile
 make[3] -C tools/mtd-utils compile
 make[3] -C tools/squashfskit4 compile
 make[2] toolchain/compile
 make[3] -C toolchain/gdb compile
 make[3] -C toolchain/binutils compile
 make[3] -C toolchain/fortify-headers compile
 make[3] -C toolchain/gcc/initial compile
 make[3] -C toolchain/kernel-headers compile
 make[3] -C toolchain/musl compile
 make[3] -C toolchain/gcc/final compile
 make[2] target/compile
 make[3] -C target/linux compile
 make[2] buildinfo
 make[2] package/compile
 make[3] diffconfig buildversion feedsversion
 make[3] -C package/libs/libjson-c host-compile
 make[3] -C package/libs/toolchain compile
 make[3] -C package/libs/ncurses host-compile
 make[3] -C package/system/fwtool host-compile
 make[3] -C package/system/usign host-compile
 make[3] -C package/system/openwrt-keyring compile
 make[3] -C feeds/packages/libs/libev compile
 make[3] -C feeds/packages/libs/libsodium compile
 make[3] -C feeds/packages/libs/udns compile
 make[3] -C package/libs/pcre compile
 make[3] -C feeds/helloworld/tcping compile
 make[3] -C feeds/luci/modules/luci-base host-compile
 make[3] -C feeds/packages/utils/attr compile
 make[3] -C package/libs/gmp compile
 make[3] -C package/libs/libcap compile
 make[3] -C package/lean/dns2socks compile
 make[3] -C package/lean/microsocks compile
 make[3] -C package/lean/pdnsd-alt compile
 make[3] -C package/libs/mbedtls compile
 make[3] -C package/libs/libmnl compile
 make[3] -C package/libs/gettext compile
 make[3] -C package/libs/libiconv compile
 make[3] -C package/utils/bzip2 compile
 make[3] -C package/libs/argp-standalone compile
make: *** wait: No child processes.  Stop.
make: *** Waiting for unfinished jobs....
make: *** wait: No child processes.  Stop.
Error: The operation was canceled.

**Comment by acooler15** [comment]
> > > > 问题很明显，libustream-wolfssl与libustream-openssl冲突了。
> > > 
> > > 
> > > 我看到是这个error 了，可是怎么解决呢，望指教
> > 
> > 
> > ```
> > include $(TOPDIR)/rules.mk
> > 
> > PKG_NAME:=luci-app-ssr-plus
> > PKG_VERSION:=184
> > PKG_RELEASE:=9
> > 
> > PKG_CONFIG_DEPENDS:= \
> > 	CONFIG_PACKAGE_$(PKG_NAME)_INCLUDE_Kcptun \
> > 	CONFIG_PACKAGE_$(PKG_NAME)_INCLUDE_NaiveProxy \
> > 	CONFIG_PACKAGE_$(PKG_NAME)_INCLUDE_Redsocks2 \
> > 	CONFIG_PACKAGE_$(PKG_NAME)_INCLUDE_Shadowsocks_Libev_Client \
> > 	CONFIG_PACKAGE_$(PKG_NAME)_INCLUDE_Shadowsocks_Libev_Server \
> > 	CONFIG_PACKAGE_$(PKG_NAME)_INCLUDE_Shadowsocks_Rust_Client \
> > 	CONFIG_PACKAGE_$(PKG_NAME)_INCLUDE_Shadowsocks_Rust_Server \
> > 	CONFIG_PACKAGE_$(PKG_NAME)_INCLUDE_ShadowsocksR_Libev_Client \
> > 	CONFIG_PACKAGE_$(PKG_NAME)_INCLUDE_ShadowsocksR_Libev_Server \
> > 	CONFIG_PACKAGE_$(PKG_NAME)_INCLUDE_Simple_Obfs \
> > 	CONFIG_PACKAGE_$(PKG_NAME)_INCLUDE_Trojan \
> > 	CONFIG_PACKAGE_$(PKG_NAME)_INCLUDE_V2ray_Plugin \
> > 	CONFIG_PACKAGE_$(PKG_NAME)_INCLUDE_Xray
> > 
> > LUCI_TITLE:=SS/SSR/V2Ray/Trojan/NaiveProxy/Socks5/Tun LuCI interface
> > LUCI_PKGARCH:=all
> > LUCI_DEPENDS:=+coreutils +coreutils-base64 +dns2socks +dnsmasq-full +ipset \
> > 	+ip-full +iptables-mod-tproxy +lua +libuci-lua +microsocks +pdnsd-alt \
> > 	+tcping +resolveip +shadowsocksr-libev-ssr-check +uclient-fetch \
> > 	+DEFAULT_libustream-wolfssl:libustream-wolfssl \
> > 	+(!DEFAULT_libustream-wolfssl):libustream-openssl \
> > 	+PACKAGE_$(PKG_NAME)_INCLUDE_Kcptun:kcptun-client \
> > 	+PACKAGE_$(PKG_NAME)_INCLUDE_NaiveProxy:naiveproxy \
> > 	+PACKAGE_$(PKG_NAME)_INCLUDE_Redsocks2:redsocks2 \
> > 	+PACKAGE_$(PKG_NAME)_INCLUDE_Shadowsocks_Libev_Client:shadowsocks-libev-ss-local \
> > 	+PACKAGE_$(PKG_NAME)_INCLUDE_Shadowsocks_Libev_Client:shadowsocks-libev-ss-redir \
> > 	+PACKAGE_$(PKG_NAME)_INCLUDE_Shadowsocks_Libev_Server:shadowsocks-libev-ss-server \
> > 	+PACKAGE_$(PKG_NAME)_INCLUDE_Shadowsocks_Rust_Client:shadowsocks-rust-sslocal \
> > 	+PACKAGE_$(PKG_NAME)_INCLUDE_Shadowsocks_Rust_Server:shadowsocks-rust-ssserver \
> > 	+PACKAGE_$(PKG_NAME)_INCLUDE_ShadowsocksR_Libev_Client:shadowsocksr-libev-ssr-local \
> > 	+PACKAGE_$(PKG_NAME)_INCLUDE_ShadowsocksR_Libev_Client:shadowsocksr-libev-ssr-redir \
> > 	+PACKAGE_$(PKG_NAME)_INCLUDE_ShadowsocksR_Libev_Server:shadowsocksr-libev-ssr-server \
> > 	+PACKAGE_$(PKG_NAME)_INCLUDE_Simple_Obfs:simple-obfs \
> > 	+PACKAGE_$(PKG_NAME)_INCLUDE_Trojan:trojan \
> > 	+PACKAGE_$(PKG_NAME)_INCLUDE_Trojan:ipt2socks \
> > 	+PACKAGE_$(PKG_NAME)_INCLUDE_V2ray_Plugin:v2ray-plugin \
> > 	+PACKAGE_$(PKG_NAME)_INCLUDE_Xray:curl \
> > 	+PACKAGE_$(PKG_NAME)_INCLUDE_Xray:xray-core
> > 
> > define Package/$(PKG_NAME)/config
> > config PACKAGE_$(PKG_NAME)_INCLUDE_Kcptun
> > 	bool "Include Kcptun"
> > 	default n
> > 
> > config PACKAGE_$(PKG_NAME)_INCLUDE_NaiveProxy
> > 	bool "Include NaiveProxy"
> > 	depends on !(arc||armeb||mips||mips64||powerpc)
> > 	default n
> > 
> > config PACKAGE_$(PKG_NAME)_INCLUDE_Redsocks2
> > 	bool "Include Redsocks2"
> > 	default n
> > 
> > config PACKAGE_$(PKG_NAME)_INCLUDE_Shadowsocks_Libev_Client
> > 	bool "Include Shadowsocks Libev Client"
> > 	default y if i386||x86_64||arm
> > 
> > config PACKAGE_$(PKG_NAME)_INCLUDE_Shadowsocks_Libev_Server
> > 	bool "Include Shadowsocks Libev Server"
> > 	default y if i386||x86_64||arm
> > 
> > config PACKAGE_$(PKG_NAME)_INCLUDE_Shadowsocks_Rust_Client
> > 	bool "Include Shadowsocks Rust Client"
> > 	depends on aarch64||arm||i386||mips||mipsel||x86_64
> > 	default y if aarch64
> > 
> > config PACKAGE_$(PKG_NAME)_INCLUDE_Shadowsocks_Rust_Server
> > 	bool "Include Shadowsocks Rust Server"
> > 	depends on aarch64||arm||i386||mips||mipsel||x86_64
> > 	default y if aarch64
> > 
> > config PACKAGE_$(PKG_NAME)_INCLUDE_ShadowsocksR_Libev_Client
> > 	bool "Include ShadowsocksR Libev Client"
> > 	default y
> > 
> > config PACKAGE_$(PKG_NAME)_INCLUDE_ShadowsocksR_Libev_Server
> > 	bool "Include ShadowsocksR Libev Server"
> > 	default y if i386||x86_64||arm
> > 
> > config PACKAGE_$(PKG_NAME)_INCLUDE_Simple_Obfs
> > 	bool "Include Shadowsocks Simple Obfs Plugin"
> > 	default y if i386||x86_64||arm
> > 
> > config PACKAGE_$(PKG_NAME)_INCLUDE_Trojan
> > 	bool "Include Trojan"
> > 	default n
> > 
> > config PACKAGE_$(PKG_NAME)_INCLUDE_V2ray_Plugin
> > 	bool "Include Shadowsocks V2ray Plugin"
> > 	default n
> > 
> > config PACKAGE_$(PKG_NAME)_INCLUDE_Xray
> > 	bool "Include Xray"
> > 	default y if aarch64||arm||i386||x86_64
> > endef
> > 
> > define Package/$(PKG_NAME)/conffiles
> > /etc/config/shadowsocksr
> > /etc/ssrplus/
> > endef
> > 
> > include $(TOPDIR)/feeds/luci/luci.mk
> > 
> > # call BuildPackage - OpenWrt buildroot signature
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 这个Makefile应该可以在大雕的op和openwrt官方的master分支与openwrt-21.02分支上使用
> 
> 好的，多谢，大佬可以直接 PR 到这里吗？这样大家都可以修复这个问题

这个方案是有问题的，因为除了`libustream-wolfssl`、`libustream-openssl`还有一个`libustream-mbedtls`，`adblock`好像用的就是这个`libustream-mbedtls`

**Comment by yfdoor** [comment]
主分支已更新，编译正常。
