### ISSUE TITLE
最新编译的版本 每次重启后 都无法使用

### ISSUE THREAD

**Issue by sk007** [fw876/helloworld#66]
新版本重启后都显示 运行中  
但是不能使用  
需要保存应用一下才可以

===========================================
以下是以前的版本 刷回去都是没有问题的

固件版本 | OpenWrt R20.5.9 / LuCI Master (git-20.117.60969-420c61a)

内核版本 | 4.19.122

**Comment by coolsnowwolf** [comment]
信息太少，无法重现

**Comment by sk007** [comment]
> 信息太少，无法重现

路由器pppoe拨号 配置好v2 保存应用后可以使用     但是 一重启 就不行了 状态显示 运行中 需要 保存应用 后才可以正常

**Comment by hplee0120** [comment]
测试了几次发现问题发生在保留配置升级固件后。就会有这种状况，重启后显示正在运行但是需要自己保存并应用一下才正常。如果是全新安装固件的话就没有该问题，可以重启后正常运行。

**Comment by sk007** [comment]
> 测试有一些发现问题发生在保留配置升级固件后。就会有这种状况，重启后显示正在运行但是需要自己保存并应用一下才正常。如果是全新安装固件的话就没有该问题，可以重启后正常运行。

全新 也一样 一样重启后不能使用 可以多重启几次 试试

**Comment by hplee0120** [comment]
> > 测试有一些发现问题发生在保留配置升级固件后。就会有这种状况，重启后显示正在运行但是需要自己保存并应用一下才正常。如果是全新安装固件的话就没有该问题，可以重启后正常运行。
> 
> 全新 也一样 一样重启后不能使用 可以多重启几次 试试

刚才使用dd命令刷写固件后重启了两遍没有问题。

**Comment by sk007** [comment]
> > > 测试有一些发现问题发生在保留配置升级固件后。就会有这种状况，重启后显示正在运行但是需要自己保存并应用一下才正常。如果是全新安装固件的话就没有该问题，可以重启后正常运行。
> > 
> > 
> > 全新 也一样 一样重启后不能使用 可以多重启几次 试试
> 
> 刚才使用dd命令刷写固件后重启了两遍没有问题。

原因已经找到 是最新版本的 开启服务端后 就出现以上问题
必须 删除 服务端账户 关闭启动服务端
