### ISSUE TITLE
编译选择 xray 核心，导入vless链接配置不正确

### ISSUE THREAD

**Issue by Ho-Lay** [fw876/helloworld#665]
导入vless链接，Path和Host；别名 为空

示范连接：
vless://596811c3-7e75-45ea-931b-47e5bbb3c51e@104.19.92.69:443?encryption=none&security=tls&type=ws&host=gfw.gobb.workers.dev&path=%2f596811c3-7e75-45ea-931b-47e5bbb3c51e-vless#Heroku

**Comment by hcym** [comment]
下午试的正常，麻烦也没觉得差距，还是删了。pass和ssr+都可以

**Comment by 1715173329** [comment]
标准的别名是包含在 url 里面的，e.g. `&remarks=Heroku`

**Comment by 1715173329** [comment]
Fixed in e64cb50f571559a1f651700e189c5adcfad633ee.
