### ISSUE TITLE
replace wget-ssl with uclient-fetch 这次变更导致 uclient-fetch 错误

### ISSUE THREAD

**Issue by deplives** [fw876/helloworld#669]
替换为uclient-fetch后更新提示：Failed to send request: Operation not permitted
具体的commit是 098309d42b5f290adb746749791b338d99849300

**Comment by acooler15** [comment]
没有遇到过，url是https吗？

**Comment by 1715173329** [comment]
请贴上 URL 及详细日志。

**Comment by acooler15** [comment]
> 请贴上 URL 及详细日志。

把Issues关些吧，有些都半年了。。。

**Comment by wlshdjj** [comment]
wget这makefile真TM精神病患者乱改，反复无常无法适从。

**Comment by acooler15** [comment]
？



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2021年10月3日(周日) 中午11:04
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [fw876/helloworld] replace wget-ssl with uclient-fetch 这次变更导致 uclient-fetch 错误 (#669)




 
wget这makefile真TM精神病患者乱改，反复无常无法适从。
