### ISSUE TITLE
更新之后“make menuconfig”出现错误

### ISSUE THREAD

**Issue by harleywong** [fw876/helloworld#670]
Collecting package info: done
tmp/.config-package.in:65200: syntax error
tmp/.config-package.in:65199: invalid statement
tmp/.config-package.in:65200: invalid statement
tmp/.config-package.in:65201: invalid statement
tmp/.config-package.in:65202: invalid statement

**Comment by Jason6111** [comment]
我的也是 求帮助

**Comment by acooler15** [comment]
怪我😅，没有先git commit，然后测试，结果测试完之后，不小心粘贴上一个 Include。
将Makefile的第60行的`depends Include`改为`depends on`应该就行了。我稍后提下PR

**Comment by Jason6111** [comment]
> 怪我😅，没有先git commit，然后测试，结果测试完之后，不小心粘贴上一个 Include。
> 将Makefile的第60行的`depends Include`改为`depends on`应该就行了。我稍后提下PR

哈哈哈 辛苦啦

**Comment by harleywong** [comment]
> 😅，
> 马凯菲`depends Include``depends on`

感谢！先编一版，再等更新！

**Comment by acooler15** [comment]
> > 😅，
> > 马凯菲`` depends Include``depends on ``
> 
> 感谢！先编一版，再等更新！

不用谢，毕竟是我搞错的。

**Comment by yonggedebaqi** [comment]
这么低级的错误不可原谅

**Comment by gswangmd-gssi** [comment]
今天云编译一直过不去，原来是这个原因，希望尽快更新。

**Comment by Beginner-Go** [comment]
> 这么低级的错误不可原谅

是的，要是有您大佬的贡献，就不会出现“低级错误”了。

**Comment by EnnawYang** [comment]
> 这么低级的错误不可原谅

您的意思是即使是元老级人物也不允许犯一丁点错误？更何况开源社区新手遍地（包括我），像您这么说的话任何存在低级issue的项目都不允许存在了？
