### ISSUE TITLE
开启SSR+的情况下 会劫持 不走代理的局域网LAN IP 的DNS查询

### ISSUE THREAD

**Issue by Werner9** [fw876/helloworld#677]
>  dig fonts.googleapis.com @223.5.5.5
> 
> ; <<>> DiG 9.17.15 <<>> fonts.googleapis.com @223.5.5.5
> ;; global options: +cmd
> ;; Got answer:
> ;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 16871
> ;; flags: qr rd ra; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 1
> 
> ;; OPT PSEUDOSECTION:
> ; EDNS: version: 0, flags:; udp: 1232
> ;; QUESTION SECTION:
> ;fonts.googleapis.com.		IN	A
> 
> ;; ANSWER SECTION:
> fonts.googleapis.com.	2795	IN	A	142.250.66.42
> 
> ;; Query time: 0 msec
> ;; SERVER: 223.5.5.5#53(223.5.5.5) (UDP)
> ;; WHEN: Thu Sep 30 14:13:03 China Standard Time 2021
> ;; MSG SIZE  rcvd: 65

查询后返回境外IP

**Comment by 1715173329** [comment]
DNS 劫持是全局的，你可以自行调整防火墙规则。
网络 -> 防火墙 -> 自定义规则。
