### ISSUE TITLE
lede+ssr 如何配置才可以作为局域网网关实现全屋设备翻墙

### ISSUE THREAD

**Issue by ZPerling** [fw876/helloworld#679]
新手小白，现在使用了rapi3 + lede + ssr 作为了软路由，rapi3 lan口连接在家庭路由器lan口，现在想把路由器默认下发的网关改为rapi3的lan口ip作为家庭设备的默认网关，lede怎么样配置可以作为网关实现全屋设备翻墙呢，谢谢

**Comment by xiechangan123** [comment]
rapi3的wan口直插 路由器（AP模式）任一个lan口，全村人都能翻墙了，跟网关有啥关系

**Comment by ZPerling** [comment]
> rapi3的wan口直插 路由器（AP模式）任一个lan口，全村人都能翻墙了，跟网关有啥关系

直接插上的话，各个设备不得把rapi配置为代理才可以翻墙吗

**Comment by xiechangan123** [comment]
> > rapi3的wan口直插 路由器（AP模式）任一个lan口，全村人都能翻墙了，跟网关有啥关系
> 
> 直接插上的话，各个设备不得把rapi配置为代理才可以翻墙吗

知道什么叫DHCP么？自动就给你搞好了，只要你把路由AP设置好了，其他的lede都给你整好了

**Comment by ZPerling** [comment]
> > > rapi3的wan口直插 路由器（AP模式）任一个lan口，全村人都能翻墙了，跟网关有啥关系
> > 
> > 
> > 直接插上的话，各个设备不得把rapi配置为代理才可以翻墙吗
> 
> 知道什么叫DHCP么？自动就给你搞好了，只要你把路由AP设置好了，其他的lede都给你整好了

嗯，现在有个新的问题，翻墙访问google啥的没问题，但是国内的站点通通都打不开，可能是什么原因呢

**Comment by EnnawYang** [comment]
> 
> 嗯，现在有个新的问题，翻墙访问google啥的没问题，但是国内的站点通通都打不开，可能是什么原因呢

“旁”路由的原因

**Comment by ZPerling** [comment]
> > 嗯，现在有个新的问题，翻墙访问google啥的没问题，但是国内的站点通通都打不开，可能是什么原因呢
> 
> “旁”路由的原因

我ssh登录到旁路由上，在这上边直接curl www.baidu.com 是没问题的，就是在其他设备上不行，很奇怪

**Comment by 1715173329** [comment]
旁路由你把握不住，谷歌下学习配置单臂路由吧。

**Comment by ZPerling** [comment]
iptables -t nat -I POSTROUTING -j MASQUERADE

加上这条iptables规则后解决
