### ISSUE TITLE
一个很神奇的Bug（多次复现已确认）

### ISSUE THREAD

**Issue by jh0072110** [fw876/helloworld#68]
在使用ss和trojan进行代理时，有一些网站上不去（包括白名单/全局），在v2下没问题。
举例，完全无利益相关，这两个网站100%无法连接（ss/trojan下）
https://tools.sprov.xyz/v2ray/
https://news.gamme.com.tw/
已经在服务器端排除完毕（同一服务器的几种协议，v2成功连接）
同时通过手机某火箭使用ss/trojan连接上述网站均可成功

反正折腾好几天，应该是个bug，但具体哪里不合适…我是真的搞不懂了，希望大佬有空能检查一下THX

**Comment by xiaoguoyi** [comment]
ss大陆白名单可以访问，建议换节点

**Comment by jh0072110** [comment]
> ss大陆白名单可以访问，建议换节点

我配置的是v2ray-plugin的无法访问，trojan是怎么着都无法访问，您可能没有认真看我的描述，我同服务器下有些协议可以访问，有些却不行，而且这个有些不行是只有在ssrp下的不行，故提此issue
最终目的还是要解决问题，不是解决提出问题的人，不是吗

**Comment by fw876** [comment]
测试过不能重现

**Comment by coaens** [comment]
之前看有人说貌似是 dns 污染问题，v2因为有内建的dns解析所以不会有这个问题

**Comment by coaens** [comment]
> 测试过不能重现

我这边能复现这个问题，同一个节点，使用 trojan 会 ssl 报错，v2就没问题。

**Comment by jh0072110** [comment]
> > 测试过不能重现
> 
> 我这边能复现这个问题，同一个节点，使用 trojan 会 ssl 报错，v2就没问题。

感动，之前大佬回复完我又一度以为是自己的问题，用最新版本编译后用ss的v2ray-plugin(https)模式和trojan(trojan-go)依旧有这个问题TAT

**Comment by hcym** [comment]
我的正常，还是haproxy均衡的三个trojan节点，其中一个是Twitter的黑名单😙🤣，不能上推特

**Comment by xsm1997** [comment]
> > > 测试过不能重现
> > 
> > 
> > 我这边能复现这个问题，同一个节点，使用 trojan 会 ssl 报错，v2就没问题。
> 
> 感动，之前大佬回复完我又一度以为是自己的问题，用最新版本编译后用ss的v2ray-plugin(https)模式和trojan(trojan-go)依旧有这个问题TAT

**一句话解决方法：在ssrp中强制走代理的域名列表中添加这两个域名，即可访问。**

分析：
这个不是Bug，是网站已经被dns污染，但gfwlist并没有收录，导致解析的IP是被污染的IP（我这里解析出的是facebook的IP）。
而v2ray可以连通，ss和trojan不可连通，推测是因为v2ray的流量探测这个feature。这个feature默认打开，如果你使用的是国内IP白名单模式，解析到的被污染的IP的流量会经由v2ray处理，而v2ray会识别出https请求头的sni域名信息，把IP请求还原成域名请求，所以可以正常浏览。ssrp的代理因为使用的是Linux iptables redirect方式所以代理程序只能接收到IP而不是域名，v2ray这个流量探测把被污染的IP请求还原成了原始的且正确的域名，所以可以正常访问。而ss和trojan无此功能，故访问被污染的IP无法联通。
上面的ssl报错也是这个原理，由于污染的IP恰好可以访问并开启了https服务，导致访问的网站证书不正确，浏览器报ssl证书错误。

如果您方便的话可以给gfwlist提交Issue或PR，而不是在ssrp。

附上dig调试结果。
```
root@KumaRouter:~# dig @114.114.114.114 news.gamme.com.tw

; <<>> DiG 9.16.4 <<>> @114.114.114.114 news.gamme.com.tw
; (1 server found)
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 5358
;; flags: qr rd ra; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 0

;; QUESTION SECTION:
;news.gamme.com.tw.		IN	A

;; ANSWER SECTION:
news.gamme.com.tw.	96	IN	A	69.171.234.18

;; Query time: 59 msec
;; SERVER: 114.114.114.114#53(114.114.114.114)
;; WHEN: Fri Jul 17 21:23:23 CST 2020
;; MSG SIZE  rcvd: 51

root@KumaRouter:~# dig @127.0.0.1 -p 5335 news.gamme.com.tw +tcp

; <<>> DiG 9.16.4 <<>> @127.0.0.1 -p 5335 news.gamme.com.tw +tcp
; (1 server found)
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 43331
;; flags: qr rd ra; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 512
;; QUESTION SECTION:
;news.gamme.com.tw.		IN	A

;; ANSWER SECTION:
news.gamme.com.tw.	204	IN	A	104.155.199.1

;; Query time: 307 msec
;; SERVER: 127.0.0.1#5335(127.0.0.1)
;; WHEN: Fri Jul 17 21:23:38 CST 2020
;; MSG SIZE  rcvd: 62

root@KumaRouter:~#
```

**Comment by XeonLang** [comment]
添加强制走代理以后可以访问，ss+v2ray-plugin没有任何问题

**Comment by jh0072110** [comment]
> 添加强制走代理以后可以访问，ss+v2ray-plugin没有任何问题

我最后发现好像是设置成pdnsd的问题…奇怪哈哈哈哈

**Comment by XeonLang** [comment]
> > 添加强制走代理以后可以访问，ss+v2ray-plugin没有任何问题
> 
> 我最后发现好像是设置成pdnsd的问题…奇怪哈哈哈哈

我一直用的pdnsd，也没有问题的
