### ISSUE TITLE
使用V2Ray/XRay节点类型Shadowsocks协议的协议时，ShadowsocksR Plus+ 提示未运行

### ISSUE THREAD

**Issue by oceange8** [fw876/helloworld#683]
如题：无意中发现标题所示问题。

示范：ss://YWVzLTI1Ni1nY206QmRSV0MzOEw1SlVETVRZTk54SkdjVXdCQDg5LjI0OS43My4xOTc6NDkzOTY#github.com/freefq%20-%20%E6%AF%94%E5%88%A9%E6%97%B6%20%2014

**Comment by 1715173329** [comment]
目前无法复现该问题。
