### ISSUE TITLE
oversea mode 114.114.114.114有问题

### ISSUE THREAD

**Issue by ntgeralt** [fw876/helloworld#688]
你好，我发现个问题
广移家宽用114.114.114.114打开谷歌抽风性可用。用下面的114.114.115.115则正常
不知我个人问题还是真的存在

**Comment by tao593** [comment]
你可真逗114是给国外翻墙回国用过的，oversea mode中文翻译为“海外模式”你在国内你用海外模式？

**Comment by ntgeralt** [comment]
@tao593 别太戾气，两年前用过smartdns里面的oversea 还真是用来解析国外
![image](https://user-images.githubusercontent.com/8230651/142903642-9078d82f-730d-4acd-88ac-ce771cf9a287.png)

另外天灵标注为question，他直接告诉我114不是这样用的那问题直接可以关闭的

**Comment by 1715173329** [comment]
请注意，ssrplus 中的 oversea 是海外用户使用大陆节点解析大陆域名所用。
因此，请不要在连向海外的节点使用此类 DNS。
如果 DNS 污染问题难以解决，请使用 V2ray / Xray。
