### ISSUE TITLE
luci-app-ssr变为“luci-app-squid”?

### ISSUE THREAD

**Issue by gavin8282** [fw876/helloworld#698]
使用openwrt-19.07.8，在feeds.conf.default中添加了“src-git helloworld https://github.com/fw876/helloworld.git”
git a2011cd90f5c9739115652c3ff26238f73da13a1
![image](https://user-images.githubusercontent.com/24975201/138555251-bde45001-5122-4fb3-98ba-2396958f3e95.png)

**Comment by wekingchen** [comment]
> 找到问题了，我的target.mk里没有“libustream-openssl”

请问该如何修改呢？我也遇到这个问题了

**Comment by rawslife** [comment]
我也遇到这个问题了，在后面的复选框里面随便选一个上面就显示出来了，我的版本：openwrt18.06

**Comment by wekingchen** [comment]
知道了，在make menuconfig进行配置时，LuCI->Collection下的luci-ssl-openssl选上之后，luci-app-ssr就显示出来了
