### ISSUE TITLE
如何编译单独的Socks5，不要其他的？

### ISSUE THREAD

**Issue by iseeyou** [fw876/helloworld#716]
一直搞不清楚Socks5是哪个带的，V2Ray/XRay，ShadowsocksR，Trojan？
编译选择的时候单选哪个会只出现Socks5呢？因为其他协议用不上。
我尝试单独编译试了半天，好像不行，必须要选择两个编译才会出现Socks5。
求解...

**Comment by 1715173329** [comment]
socks5 客户端支持由 ipt2socks 提供，由 trojan 选中。
socks5 服务端支持由 microsocks 提供，必选依赖。

或许应该单独增加一个 ipt2socks 的选项。

**Comment by iseeyou** [comment]
> socks5 客户端支持由 ipt2socks 提供，由 trojan 选中。 socks5 服务端支持由 microsocks 提供，必选依赖。
> 
> 或许应该单独增加一个 ipt2socks 的选项。

谢谢，已经解决。
强烈建议单独加个ipt2socks。

**Comment by 1715173329** [comment]
已添加。
