### ISSUE TITLE
[功能请求]Xray-gRPC健康检查&VMess Zero加密方式

### ISSUE THREAD

**Issue by ShoukakuChuuCC** [fw876/helloworld#718]
健康检查功能 相关PR：
https://github.com/XTLS/Xray-core/pull/633
仅在客户端配置即可

VMess+Zero加密方式和VLess性能差不多了 希望能够添加

还有希望当选择传输协议为gRPC时 能把Mux变更为gRPC的multiMode复选框开关（目前grpc+mux应该就是打开了multiMode，但好像还有很多人不懂

**Comment by 1715173329** [comment]
#747
