### ISSUE TITLE
云编译总是出现naiveproxy failed to build

### ISSUE THREAD

**Issue by qqsir-dev** [fw876/helloworld#720]
ERROR: package/lean/helloworld/naiveproxy failed to build

**Comment by tao593** [comment]
去掉naiveproxy勾选就好了，我也是，去掉就好了，但是如果你要用naiveproxy协议，那就只有问大佬了，我反正不用这个协议，我在依赖里面只勾选了XRAY

**Comment by qqsir-dev** [comment]
好的，谢谢

**Comment by NueXini** [comment]
试一试把hash修改为
`5f693c4779c1d6802e509c2c1e5f130017fd6634a0ccd3a0de47be419c068f5e`

https://github.com/fw876/helloworld/blob/116ed0833db07f70a8279143257fa4936bcf364f/naiveproxy/Makefile#L94

**Comment by leopardciaw** [comment]
也出错了，下面这个地方，无论如何下载不下来。
[Makefile:130: /workdir/openwrt/dl/chrome-linux-4664-1636557077-6e390f4e505916531ca2ab0c895d5903ab4d88a9.profdata]

**Comment by NueXini** [comment]
> 也出错了，下面这个地方，无论如何下载不下来。 [Makefile:130: /workdir/openwrt/dl/chrome-linux-4664-1636557077-6e390f4e505916531ca2ab0c895d5903ab4d88a9.profdata]

贴出完整的错误日志，编译的时候hash校验不通过，会从cdn下载文件，cdn不会下载成功的，404错误，所以

发log出来！
发log出来！
发log出来！

**Comment by oceange8** [comment]
出现同样错误
