### ISSUE TITLE
奈飞分流模式不工作

### ISSUE THREAD

**Issue by guhill** [fw876/helloworld#731]
奈飞分流模式不工作,仍然使用主服务器代理
有时候固件重启一下正常了,有时候重启一下又不正常

主服务器
[VLESS]:----------------

游戏模式UDP中继服务器
停用

Netflix 分流服务器
[VMESS]:---------|V2ray

分流服务器（前置）代理

 帮助 分流服务器流量通过主服务节点中转代理转发

多线程并发转发
单线程

运行模式
绕过中国大陆IP模式

需要代理的端口

仅常用端口（不走P2P流量到代理）
DNS解析方式

使用PDNSD TCP查询并缓存
访问国外域名DNS服务器

XXXXXX

**Comment by 1715173329** [comment]
确认你的所有 DNS 请求完全交由 dnsmasq 处理，没有使用 AdGuardHome 或 SmartDNS 一类软件劫持 53 端口。
确认你设备的 DNS 已指向路由器，Private DNS / Secure DNS 已关闭。

**Comment by guhill** [comment]
> 确认你的所有 DNS 请求完全交由 dnsmasq 处理，没有使用 AdGuardHome 或 SmartDNS 一类软件劫持 53 端口。 确认你设备的 DNS 已指向路由器，Private DNS / Secure DNS 已关闭。

谢谢大佬回复,又做了下测试,固件使用x64 ssrpOpenWrt 12.3版,没有使用smartdns和adguard,

访问国外域名DNS服务器
Google Public DNS (8.8.4.4)

lan设置
使用自定义的 DNS 服务器
8.8.4.4

DHCP/DNS设置
dns转发 空
目前还是只走主服务器

**Comment by guhill** [comment]
目前通过修改节点和重启固件正常了,谢谢
