### ISSUE TITLE
openwrt固件中配置不走代理的域名之后依然会走代理

### ISSUE THREAD

**Issue by Naturalforce** [fw876/helloworld#738]
我用nodejs写了一个脚本用来更新我cloudflare的dns解析记录，但是我在ip更新日志里发现了频繁的ip更新记录

以下是近期的皮更新记录，183.128.xxx.xxx为我实际的ip，其他为节点ip

`[Sun Dec 05 2021 16:16:18 GMT+0000]  IPv4: 183.128.xxx.xxx => 159.223.56.179`
`[Sun Dec 05 2021 16:28:18 GMT+0000]  IPv4: 159.223.56.179 => 206.119.184.100`
`[Sun Dec 05 2021 16:40:21 GMT+0000]  IPv4: 206.119.184.100 => 183.128.xxx.xxx`
`[Sun Dec 05 2021 16:52:20 GMT+0000]  IPv4: 183.128.xxx.xxx => 114.24.30.85`
`[Sun Dec 05 2021 17:04:19 GMT+0000]  IPv4: 114.24.30.85 => 167.99.64.71`
`[Sun Dec 05 2021 17:16:20 GMT+0000]  IPv4: 167.99.64.71 => 159.65.133.255`
`[Sun Dec 05 2021 17:28:20 GMT+0000]  IPv4: 159.65.133.255 => 159.65.135.130`
`[Sun Dec 05 2021 17:40:22 GMT+0000]  IPv4: 159.65.135.130 => 8.211.177.160`
`[Sun Dec 05 2021 17:46:21 GMT+0000]  IPv4: 8.211.177.160 => 183.128.xxx.xxx`
`[Sun Dec 05 2021 18:13:22 GMT+0000]  IPv4: 183.128.xxx.xxx => 159.223.56.179`
`[Sun Dec 05 2021 18:24:22 GMT+0000]  IPv4: 159.223.56.179 => 183.128.xxx.xxx`
`[Sun Dec 05 2021 18:25:23 GMT+0000]  IPv4: 183.128.xxx.xxx => 206.119.184.100`
`[Sun Dec 05 2021 18:36:23 GMT+0000]  IPv4: 206.119.184.100 => 183.128.xxx.xxx`
`[Sun Dec 05 2021 18:37:24 GMT+0000]  IPv4: 183.128.xxx.xxx => 1.169.17.135`
`[Sun Dec 05 2021 18:46:24 GMT+0000]  IPv4: 1.169.17.135 => 183.128.xxx.xxx`
`[Sun Dec 05 2021 18:49:24 GMT+0000]  IPv4: 183.128.xxx.xxx => 114.24.30.85`
`[Sun Dec 05 2021 19:00:24 GMT+0000]  IPv4: 114.24.30.85 => 183.128.xxx.xxx`
`[Sun Dec 05 2021 19:01:24 GMT+0000]  IPv4: 183.128.xxx.xxx => 167.99.64.71`
`[Sun Dec 05 2021 19:12:25 GMT+0000]  IPv4: 167.99.64.71 => 183.128.xxx.xxx`
`[Sun Dec 05 2021 19:13:25 GMT+0000]  IPv4: 183.128.xxx.xxx => 159.65.133.255`
`[Sun Dec 05 2021 19:24:25 GMT+0000]  IPv4: 159.65.133.255 => 183.128.xxx.xxx`
`[Sun Dec 05 2021 19:25:25 GMT+0000]  IPv4: 183.128.xxx.xxx => 159.65.135.130`
`[Sun Dec 05 2021 19:36:26 GMT+0000]  IPv4: 159.65.135.130 => 183.128.xxx.xxx`
`[Sun Dec 05 2021 19:37:26 GMT+0000]  IPv4: 183.128.xxx.xxx => 8.211.177.160`
`[Sun Dec 05 2021 19:46:26 GMT+0000]  IPv4: 8.211.177.160 => 183.128.xxx.xxx`
`[Sun Dec 05 2021 20:01:28 GMT+0000]  IPv4: 183.128.xxx.xxx => 8.211.177.160`
`[Sun Dec 05 2021 20:25:31 GMT+0000]  IPv4: 8.211.177.160 => 194.5.79.246`
`[Sun Dec 05 2021 20:37:28 GMT+0000]  IPv4: 194.5.79.246 => 20.187.98.134`
`[Sun Dec 05 2021 20:46:29 GMT+0000]  IPv4: 20.187.98.134 => 183.128.xxx.xxx`
`[Sun Dec 05 2021 20:49:29 GMT+0000]  IPv4: 183.128.xxx.xxx => 20.187.98.134`
`[Sun Dec 05 2021 21:00:29 GMT+0000]  IPv4: 20.187.98.134 => 183.128.xxx.xxx`
`[Sun Dec 05 2021 21:01:29 GMT+0000]  IPv4: 183.128.xxx.xxx => 20.187.98.134`
`[Sun Dec 05 2021 21:12:30 GMT+0000]  IPv4: 20.187.98.134 => 183.128.xxx.xxx`
`[Sun Dec 05 2021 21:13:30 GMT+0000]  IPv4: 183.128.xxx.xxx => 20.187.98.134`
`[Sun Dec 05 2021 21:24:31 GMT+0000]  IPv4: 20.187.98.134 => 183.128.xxx.xxx`
`[Sun Dec 05 2021 21:37:32 GMT+0000]  IPv4: 183.128.xxx.xxx => 114.24.30.85`
`[Sun Dec 05 2021 21:46:32 GMT+0000]  IPv4: 114.24.30.85 => 183.128.xxx.xxx`
`[Sun Dec 05 2021 21:49:32 GMT+0000]  IPv4: 183.128.xxx.xxx => 206.119.184.100`
`[Sun Dec 05 2021 21:54:33 GMT+0000]  IPv4: 206.119.184.100 => 183.128.xxx.xxx`
`[Sun Dec 05 2021 22:12:32 GMT+0000]  IPv4: 183.128.xxx.xxx => 159.223.56.179`
`[Sun Dec 05 2021 22:24:33 GMT+0000]  IPv4: 159.223.56.179 => 206.119.184.100`
`[Sun Dec 05 2021 22:36:34 GMT+0000]  IPv4: 206.119.184.100 => 1.169.17.135`
`[Sun Dec 05 2021 22:46:34 GMT+0000]  IPv4: 1.169.17.135 => 183.128.xxx.xxx`
`[Sun Dec 05 2021 22:48:35 GMT+0000]  IPv4: 183.128.xxx.xxx => 114.24.30.85`
`[Sun Dec 05 2021 23:00:35 GMT+0000]  IPv4: 114.24.30.85 => 183.128.xxx.xxx`
`[Sun Dec 05 2021 23:12:35 GMT+0000]  IPv4: 183.128.xxx.xxx => 159.65.133.255`
`[Sun Dec 05 2021 23:24:36 GMT+0000]  IPv4: 159.65.133.255 => 159.65.135.130`
`[Sun Dec 05 2021 23:36:36 GMT+0000]  IPv4: 159.65.135.130 => 8.211.177.160`
`[Sun Dec 05 2021 23:46:37 GMT+0000]  IPv4: 8.211.177.160 => 183.128.xxx.xxx`
`[Mon Dec 06 2021 00:00:38 GMT+0000]  IPv4: 183.128.xxx.xxx => 8.211.177.160`
`[Mon Dec 06 2021 00:24:41 GMT+0000]  IPv4: 8.211.177.160 => 194.5.79.246`
`[Mon Dec 06 2021 00:36:39 GMT+0000]  IPv4: 194.5.79.246 => 20.187.98.134`
`[Mon Dec 06 2021 00:46:41 GMT+0000]  IPv4: 20.187.98.134 => 183.128.xxx.xxx`
`[Mon Dec 06 2021 00:48:39 GMT+0000]  IPv4: 183.128.xxx.xxx => 20.187.98.134`
`[Mon Dec 06 2021 01:12:45 GMT+0000]  IPv4: 20.187.98.134 => 183.128.xxx.xxx`
`[Mon Dec 06 2021 01:36:42 GMT+0000]  IPv4: 183.128.xxx.xxx => 114.24.30.85`
`[Mon Dec 06 2021 01:46:42 GMT+0000]  IPv4: 114.24.30.85 => 183.128.xxx.xxx`
`[Mon Dec 06 2021 01:48:43 GMT+0000]  IPv4: 183.128.xxx.xxx => 206.119.184.100`
`[Mon Dec 06 2021 01:53:42 GMT+0000]  IPv4: 206.119.184.100 => 183.128.xxx.xxx`

以下是我的ip检测更新脚本，基本方法就是通过IPv4和IPv6访问ip.sb，以返回值作为判定
`const axios = require('axios');`
`const fs = require('fs');`
`const { exec } = require('child_process');`
``
`const r = axios.create({`
`  baseURL: 'https://api.cloudflare.com/client/v4/zones/domaintoken/dns_records/',`
`  method: 'PUT',`
`  headers: {`
`    "X-Auth-Email": "email",`
`    "X-Auth-Key": "authtoken",`
`    "Content-Type": "application/json",`
`  }`
`})`
``
`setInterval(() => {exec('curl -4 ip.sb', (err, stdout, stderr) => {`
`  fs.readFile('./.addr4', 'utf-8', (err, data) => {`
`    if (err) {`
`      fs.writeFile('./.addr4', '', () => { });`
`    } else {`
`      if (stdout == data) {`
`        return;`
`      }`
`    }`
`    r({`
`      url: 'ipv4token',`
`      data: {`
`        "type": "A", "name": "xxxxlol.com", "content": stdout, "ttl": 300, "proxied": false`
`      }`
`    }).then(res => {`
`      fs.writeFile('./.addr4', stdout, () => { });`
`      fs.appendFile('./update.log', logGenerator(`IPv4: ${data.replace('\n', '').replace('\r', '')} => ${stdout}`), () => { });`
`    }).catch(err => {`
`      fs.writeFile('./error.log', logGenerator(JSON.stringify(err)));`
`    })`
`  })`
`});`
``
`exec('curl -6 ip.sb', (err, stdout, stderr) => {`
`  fs.readFile('./.addr6', 'utf-8', (err, data) => {`
`    if (err) {`
`      fs.writeFile('./.addr6', '', () => { });`
`    } else {`
`      if (stdout == data) {`
`        return;`
`      }`
`    }`
`    r({`
`      url: 'ipv6token',`
`      data: {`
`        "type": "AAAA", "name": "xxxxlol.com", "content": stdout, "ttl": 300, "proxied": false`
`      }`
`    }).then(res => {`
`      fs.writeFile('./.addr6', stdout, () => { });`
`      fs.appendFile('./update.log', logGenerator(`IPv6: ${data.replace('\r', '').replace('\n', '')} => ${stdout}`), () => { });`
`    }).catch(err => {`
`      fs.writeFile('./error.log', logGenerator(JSON.stringify(err)));`
`    })`
`  })`
`});`
`}, 60000);`
``
``
`function logGenerator(msg) {`
`  return '[' + new Date().toString().replace(' (Coordinated Universal Time)', '')+ ']  ' + msg;`
`}`

以下是openwrt的配置

![image](https://user-images.githubusercontent.com/29086850/144776240-9eb31ac2-dcd2-4e7b-ac62-203e56bdfcfc.png)

![image](https://user-images.githubusercontent.com/29086850/144776209-28c82b2d-b699-4137-9dcf-c31339c7b281.png)

麻烦各位大佬帮忙诊断一下问题出在哪里，多谢！

**Comment by deplives** [comment]
除了这个问题，还有强制代理也不会走代理，之前就提过issue https://github.com/fw876/helloworld/issues/568

**Comment by Naturalforce** [comment]
> 除了这个问题，还有强制代理也不会走代理，之前就提过issue #568

确实有提到过，我也开了adbyby+，不过我ssr+使用的单独的dns查询缓存服务，应该不会影响到吧

**Comment by deplives** [comment]
> > 除了这个问题，还有强制代理也不会走代理，之前就提过issue #568
> 
> 确实有提到过，我也开了adbyby+，不过我ssr+使用的单独的dns查询缓存服务，应该不会影响到吧

提568这个issue之前我自己就排除过，甚至编译了一个只包含ssrp的固件，其他能去的全都去掉了，然而强制代理还是没有被强制，所以才提的issue，然而大佬们一句话就给关了

**Comment by 1715173329** [comment]
1. 如果你的接口有公网 ip，那么直接从接口读取即可
    e.g. `ifstatus wan | jsonfilter -e '@["ipv4-address"][0].address'`，v6 同理
    luci-app-ddns（ddns-scripts-cloudflare / ddns-scripts_cloudflare.com-v4）已经提供该功能，没有必要重新造轮子

2. ACL 基本要求
    1. 此路由器是作为网关存在，不是所谓“旁路由”
    2. 所有 DNS 请求必须交由 dnsmasq 处理，可以设定其他 DNS，但首个获取到请求的必须是 dnsmasq

**Comment by deplives** [comment]
补充一下我的情况和我遇到的问题：
1. op作为主路由拨号上网，直击安装在软路由上，没有虚拟机
2. 没有任何其他dns，只在pppoe自定义了dns，没有开启 网络加速中dns缓存
在上面的情况下遇到的问题
1. 在dnsmasq的配置文件中确实存在已经存在强制代理/强制不代理的域名规则
2. 配置的强制代理/强制不代理依旧没有走代理或者走了代理

**Comment by Naturalforce** [comment]
> * 如果你的接口有公网 ip，那么直接从接口读取即可
>   e.g. `ifstatus wan | jsonfilter -e '@["ipv4-address"][0].address'`，v6 同理
>   luci-app-ddns（ddns-scripts-cloudflare / ddns-scripts_cloudflare.com-v4）已经提供该功能，没有必要重新造轮子
> * ACL 基本要求
>   
>   1. 此路由器是作为网关存在，不是所谓“旁路由”
>   2. 所有 DNS 请求必须交由 dnsmasq 处理，可以设定其他 DNS，但首个获取到请求的必须是 dnsmasq
>   3. 设备的 DNS 应该指向路由器，没有启用 Private / Secure DNS。

1.我并没有用路由器的ddns，因为我同时有ipv6，于是我写的脚本放在了路由器下的服务器上，因为对于sh我并不是很熟悉所以才写的nodejs脚本去发送请求。
2.对于ACL的话，因为我经常需要连接到家里，所以暂时使用“不走代理的LAN IP”暂时先解决掉问题，这两天我再改回之前的配置等一下日志在发上来

**Comment by Benjamin23333** [comment]
我今天也遇到类似的问题，我今天使用酷安，贴吧这两个国内app时发现图片加载不出来，关掉ssr+之后就可以加载出来了，我怀疑是不是我这两个软件的图片URL走了代理的dns，但是我把openwrt重置了之后又好了，就挺玄学的😂

**Comment by Naturalforce** [comment]
> * ACL 基本要求
>   
>   1. 此路由器是作为网关存在，不是所谓“旁路由”
>   2. 所有 DNS 请求必须交由 dnsmasq 处理，可以设定其他 DNS，但首个获取到请求的必须是 dnsmasq
>   3. 设备的 DNS 应该指向路由器，没有启用 Private / Secure DNS。

今天凌晨和早上，再次出现了两次ip.sb被代理的情况，其中115.204.68.192是我本地的ip，103.97.201.229是节点ip
`
[Wed Dec 08 2021 18:00:58 GMT+0000]  IPv4: 115.204.68.192 => 103.97.201.229
[Wed Dec 08 2021 18:02:57 GMT+0000]  IPv4: 103.97.201.229 => 115.204.68.192
[Wed Dec 08 2021 23:37:13 GMT+0000]  IPv4: 115.204.68.192 => 103.97.201.229
[Wed Dec 08 2021 23:38:13 GMT+0000]  IPv4: 103.97.201.229 => 115.204.68.192
`

设备的dns会搜索lan区域，应该是指向路由器的
/etc/resolv.conf
`
nameserver 127.0.0.53
options edns0 trust-ad
search lan
`

**Comment by klever1988** [comment]
ip.sb使用cloudflare cdn服务，cf的cdn前端ip就那么多个，是很多使用cf cdn的域名共享的IP。
打个比方，aaa.com使用cf cdn，并且cf的解析使得aaa.com使用和ip.sb一样的前端IP，在你访问ip.sb之前，如果先访问了aaa.com使解析的IP被打入了要走代理的gfwlist ipset，那么即使ip.sb设置了不走代理也一样会走代理。

**Comment by Naturalforce** [comment]
> ip.sb使用cloudflare cdn服务，cf的cdn前端ip就那么多个，是很多使用cf cdn的域名共享的IP。
> 打个比方，aaa.com使用cf cdn，并且cf的解析使得aaa.com使用和ip.sb一样的前端IP，在你访问ip.sb之前，如果先访问了aaa.com使解析的IP被打入了要走代理的gfwlist ipset，那么即使ip.sb设置了不走代理也一样会走代理。

原来如此，我没有想到这一点，多谢解惑
