### ISSUE TITLE
请求支持trojan-go

### ISSUE THREAD

**Issue by ITdesk01** [fw876/helloworld#74]
仓库地址https://github.com/p4gefau1t/trojan-go

**Comment by SharerMax** [comment]
不还是Trojan么？

**Comment by ITdesk01** [comment]
> 不还是Trojan么？

Trojan的加强版（关键支撑cdn）
使用Go实现的完整Trojan代理，与Trojan协议以及Trojan-GFW版本的配置文件格式兼容。安全，高效，轻巧，易用。

支持使用多路复用提升并发性能，使用路由模块实现国内直连。

支持CDN流量中转(基于WebSocket over TLS/SSL)。

支持使用AEAD对Trojan流量二次加密(基于Shadowsocks AEAD)

支持可插拔的传输层插件，允许替换TLS，使用其他加密隧道传输Trojan协议流量

**Comment by hcym** [comment]
体验没有原版的好，套cf也不如v2规范有序。关键是这哥们加法太多，还是原版简洁明了

**Comment by ITdesk01** [comment]
> 体验没有原版的好，套cf也不如v2规范有序。关键是这哥们加法太多，还是原版简洁明了

我觉得cdn是一个亮点，更新也算快，完善总是要时间的，没有人去试，怎么能加快完善进度呢，原版虽然简单明了，但不能套还是差点

**Comment by norikohxb** [comment]
同求啊，现在trojan go不是据说很快了

**Comment by coLATin** [comment]
> 同求啊，现在trojan go不是据说很快了

的确比v2r快，在同个vps上，重装系统都试了一下，trojan-go非常不错，也习惯helloworld了，希望能加上trojan-go，配合cloudflare，trojan是没法做cdn加速的

**Comment by zjwangmin** [comment]
同求加上
