### ISSUE TITLE
Openwrt官方源码无法启动

### ISSUE THREAD

**Issue by Cathgao** [fw876/helloworld#740]
在OpenWrt官方最新源码基础上加入了ssrp与依赖的sock包，编译成功并启动。但启动SSRP失败

```
2021-12-07 19:23:27: Main node:Error loading shared library libboost_system.so.1.77.0: No such file or directory (needed by /var/etc/ssrplus/bin/trojan) , 1 Threads Started!
2021-12-07 19:23:26: ----------start------------
2021-12-07 19:23:19: ssrplus redir tcp error.restart!
2021-12-07 19:22:48: -----------end------------
2021-12-07 19:22:25: Main node:Error loading shared library libboost_system.so.1.77.0: No such file or directory (needed by /var/etc/ssrplus/bin/trojan) , 1 Threads Started!
2021-12-07 19:22:24: ----------start------------
2021-12-07 19:22:18: ssrplus redir tcp error.restart!
2021-12-07 19:21:48: -----------end------------
2021-12-07 19:21:31: Main node:Error loading shared library libboost_system.so.1.77.0: No such file or directory (needed by /var/etc/ssrplus/bin/trojan) , 1 Threads Started!
2021-12-07 19:21:28: ----------start------------
2021-12-07 19:21:07: -----------end------------
2021-12-07 19:21:01: 禁止连接的域名加载完毕。
2021-12-07 19:21:01: 未启动主节点，禁止连接的域名正在加载。
2021-12-07 19:21:01: ----------start------------
2021-12-05 17:50:55: -----------end------------
2021-12-05 17:50:50: 禁止连接的域名加载完毕。
2021-12-05 17:50:50: 未启动主节点，禁止连接的域名正在加载。
2021-12-05 17:50:50: ----------start------------
2021-12-05 17:50:50: boot！
```

请问这个libboost_system.so如何编译进去？

**Comment by 1715173329** [comment]
请重新编译 trojan。
make package/trojan/{clean,compile} -j$(nproc)

**Comment by Cathgao** [comment]
系统信息：

<html>
<body>
<h3 style="box-sizing: border-box; margin: 0px 0px 0.5rem; padding: 0px 0px 1rem; font-family: &quot;Microsoft Yahei&quot;, &quot;WenQuanYi Micro Hei&quot;, sans-serif, &quot;Helvetica Neue&quot;, Helvetica, &quot;Hiragino Sans GB&quot;; font-weight: 400; color: rgb(64, 64, 64); line-height: 1; font-size: 1.4rem; display: block; width: 1542px; border-bottom: thin solid rgb(238, 238, 238); font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">系统</h3><div style="box-sizing: border-box; margin: 0px; padding: 0px; color: rgb(0, 0, 0); font-family: &quot;Microsoft Yahei&quot;, &quot;WenQuanYi Micro Hei&quot;, sans-serif, &quot;Helvetica Neue&quot;, Helvetica, &quot;Hiragino Sans GB&quot;; font-size: 12.8px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">

主机名 | OpenWrt
-- | --
型号 | Lenovo Y1
架构 | MediaTek MT7620A ver:2 eco:6
目标平台 | ramips/mt7620
固件版本 | OpenWrt SNAPSHOT r18297-7e89421a7c / LuCI Master git-21.341.29668-6162b10
内核版本 | 5.4.162
本地时间 | 2021-12-07 19:27:42
运行时间 | 0h 19m 10s
平均负载 | 0.83, 1.13, 0.88

</div>
</body>
</html>

**Comment by 1715173329** [comment]
简而言之，在 boost 库更新后，Trojan 并没有被重新构建，仍然链接到旧的版本上，导致无法启动。
此时，重新编译 trojan 即可解决。

**Comment by Cathgao** [comment]
> 简而言之，在 boost 库更新后，Trojan 并没有被重新构建，仍然链接到旧的版本上，导致无法启动。 此时，重新编译 trojan 即可解决。

已解决，非常感谢解答

**Comment by chiyu521** [comment]
chiyu@chiyu-HP:~/lede$ make package/trojan/{clean,compile} -j$(nproc) V=s
make[1]: Entering directory '/home/chiyu/lede'
make[2]: Entering directory '/home/chiyu/lede/feeds/helloworld/trojan'
rm -rf /home/chiyu/lede/build_dir/target-x86_64_musl/trojan-1.16.0
rm -f /home/chiyu/lede/staging_dir/target-x86_64_musl/stamp/.trojan_installed
rm -f /home/chiyu/lede/staging_dir/target-x86_64_musl/packages/trojan.list
make[2]: Leaving directory '/home/chiyu/lede/feeds/helloworld/trojan'
time: package/feeds/helloworld/trojan/clean#0.12#0.03#0.13
make[1]: Leaving directory '/home/chiyu/lede'
make[1]: Entering directory '/home/chiyu/lede'
make[2]: Entering directory '/home/chiyu/lede/feeds/packages/libs/boost'
make[2]: Entering directory '/home/chiyu/lede/package/libs/toolchain'
Selected Boost API sysv for architecture x86_64 and cpu type " " 
echo "libc" >> /home/chiyu/lede/staging_dir/target-x86_64_musl/pkginfo/toolchain.default.install
echo "libgcc" >> /home/chiyu/lede/staging_dir/target-x86_64_musl/pkginfo/toolchain.default.install
echo "libatomic" >> /home/chiyu/lede/staging_dir/target-x86_64_musl/pkginfo/toolchain.default.install
echo "libstdcpp" >> /home/chiyu/lede/staging_dir/target-x86_64_musl/pkginfo/toolchain.default.install
echo "libpthread" >> /home/chiyu/lede/staging_dir/target-x86_64_musl/pkginfo/toolchain.default.install
echo "librt" >> /home/chiyu/lede/staging_dir/target-x86_64_musl/pkginfo/toolchain.default.install
make[2]: Leaving directory '/home/chiyu/lede/package/libs/toolchain'
time: package/libs/toolchain/compile#0.14#0.04#0.17
make[2]: Entering directory '/home/chiyu/lede/package/firmware/linux-firmware'
make[2]: Entering directory '/home/chiyu/lede/package/firmware/prism54-firmware'
mkdir -p /home/chiyu/lede/dl
SHELL= flock /home/chiyu/lede/tmp/.boost_1_78_0.tar.bz2.flock -c '  	/home/chiyu/lede/scripts/download.pl "/home/chiyu/lede/dl" "boost_1_78_0.tar.bz2" "8681f175d4bdb26c52222665793eef08490d7758529330f98d3b29dd0735bccc" "" "@SF/boost/boost/1.78.0" "https://dl.bintray.com/boostorg/release/1.78.0/source/"    '
mkdir -p /home/chiyu/lede/dl
SHELL= flock /home/chiyu/lede/tmp/.linux-firmware-20211216.tar.xz.flock -c '  	/home/chiyu/lede/scripts/download.pl "/home/chiyu/lede/dl" "linux-firmware-20211216.tar.xz" "eeddb4e6bef31fd1a3757f12ccc324929bbad97855c0b9ec5ed780f74de1837d" "" "@KERNEL/linux/kernel/firmware"    '
make[2]: Nothing to be done for 'compile'.
make[2]: Leaving directory '/home/chiyu/lede/package/firmware/prism54-firmware'
time: package/firmware/prism54-firmware/compile#0.15#0.03#0.21
make[2]: Leaving directory '/home/chiyu/lede/feeds/packages/libs/boost'
time: package/feeds/packages/boost/host-compile#1.03#0.33#1.09
make[2]: Entering directory '/home/chiyu/lede/feeds/packages/libs/boost'
Selected Boost API sysv for architecture x86_64 and cpu type " " 
mkdir -p /home/chiyu/lede/dl
SHELL= flock /home/chiyu/lede/tmp/.boost_1_78_0.tar.bz2.flock -c '  	/home/chiyu/lede/scripts/download.pl "/home/chiyu/lede/dl" "boost_1_78_0.tar.bz2" "8681f175d4bdb26c52222665793eef08490d7758529330f98d3b29dd0735bccc" "" "@SF/boost/boost/1.78.0" "https://dl.bintray.com/boostorg/release/1.78.0/source/"    '
echo "rt2800-usb-firmware" >> /home/chiyu/lede/staging_dir/target-x86_64_musl/pkginfo/linux-firmware.default.install
echo "ath9k-htc-firmware" >> /home/chiyu/lede/staging_dir/target-x86_64_musl/pkginfo/linux-firmware.default.install
echo "ath10k-board-qca9888" >> /home/chiyu/lede/staging_dir/target-x86_64_musl/pkginfo/linux-firmware.default.install
echo "ath10k-firmware-qca9888" >> /home/chiyu/lede/staging_dir/target-x86_64_musl/pkginfo/linux-firmware.default.install
echo "ath10k-board-qca988x" >> /home/chiyu/lede/staging_dir/target-x86_64_musl/pkginfo/linux-firmware.default.install
echo "ath10k-firmware-qca988x" >> /home/chiyu/lede/staging_dir/target-x86_64_musl/pkginfo/linux-firmware.default.install
echo "ath10k-board-qca9984" >> /home/chiyu/lede/staging_dir/target-x86_64_musl/pkginfo/linux-firmware.default.install
echo "ath10k-firmware-qca9984" >> /home/chiyu/lede/staging_dir/target-x86_64_musl/pkginfo/linux-firmware.default.install
echo "brcmfmac-firmware-43602a1-pcie" >> /home/chiyu/lede/staging_dir/target-x86_64_musl/pkginfo/linux-firmware.default.install
echo "bnx2-firmware" >> /home/chiyu/lede/staging_dir/target-x86_64_musl/pkginfo/linux-firmware.default.install
echo "bnx2x-firmware" >> /home/chiyu/lede/staging_dir/target-x86_64_musl/pkginfo/linux-firmware.default.install
make[2]: Leaving directory '/home/chiyu/lede/package/firmware/linux-firmware'
time: package/firmware/linux-firmware/compile#1.11#0.28#1.31
make[2]: Entering directory '/home/chiyu/lede/package/kernel/linux'
can't open file '/home/chiyu/lede/build_dir/target-x86_64_musl/linux-x86_64/linux-5.10.88/.config' at /home/chiyu/lede/scripts/kconfig.pl line 32.
echo "boost-chrono" >> /home/chiyu/lede/staging_dir/target-x86_64_musl/pkginfo/boost.default.install
echo "boost-date_time" >> /home/chiyu/lede/staging_dir/target-x86_64_musl/pkginfo/boost.default.install
echo "boost-program_options" >> /home/chiyu/lede/staging_dir/target-x86_64_musl/pkginfo/boost.default.install
echo "boost-random" >> /home/chiyu/lede/staging_dir/target-x86_64_musl/pkginfo/boost.default.install
echo "boost-system" >> /home/chiyu/lede/staging_dir/target-x86_64_musl/pkginfo/boost.default.install
echo "boost" >> /home/chiyu/lede/staging_dir/target-x86_64_musl/pkginfo/boost.default.install
make[2]: Leaving directory '/home/chiyu/lede/feeds/packages/libs/boost'
time: package/feeds/packages/boost/compile#1.07#0.37#1.13
grep: /home/chiyu/lede/build_dir/target-x86_64_musl/linux-x86_64/linux-5.10.88/modules.builtin: No such file or directory
ERROR: module '/home/chiyu/lede/build_dir/target-x86_64_musl/linux-x86_64/linux-5.10.88/drivers/md/md-mod.ko' is missing.
make[2]: *** [modules/block.mk:316: /home/chiyu/lede/bin/targets/x86/64/packages/kmod-md-mod_5.10.88-1_x86_64.ipk] Error 1
make[2]: Leaving directory '/home/chiyu/lede/package/kernel/linux'
time: package/kernel/linux/compile#1.68#0.10#1.80
    ERROR: package/kernel/linux failed to build.
make[1]: *** [package/Makefile:116: package/kernel/linux/compile] Error 1
make[1]: Leaving directory '/home/chiyu/lede'
make: *** [/home/chiyu/lede/include/toplevel.mk:230：package/trojan/compile] 错误 2

不知道如何修复
