### ISSUE TITLE
编译出错，求助

### ISSUE THREAD

**Issue by jxph1123** [fw876/helloworld#748]
升级最新版出错，求助。

Finding targets
go: golang.org/x/crypto@v0.0.0-20211209193657-4570a0811e8b requires
	golang.org/x/net@v0.0.0-20211112202133-69e39bad7dc2: missing go.sum entry; to add it:
	go mod download golang.org/x/net

Building targets
go: golang.org/x/crypto@v0.0.0-20211209193657-4570a0811e8b requires
	golang.org/x/net@v0.0.0-20211112202133-69e39bad7dc2: missing go.sum entry; to add it:
	go mod download golang.org/x/net

Makefile:79: recipe for target '/home/etek/openwrt/build_dir/target-mipsel_24kc_musl/Xray-core-1.5.1/.built' failed
make[3]: *** [/home/etek/openwrt/build_dir/target-mipsel_24kc_musl/Xray-core-1.5.1/.built] Error 1
make[3]: Leaving directory '/home/etek/openwrt/feeds/helloworld/xray-core'
time: package/feeds/helloworld/xray-core/compile#0.20#0.35#0.64
package/Makefile:111: recipe for target 'package/feeds/helloworld/xray-core/compile' failed
make[2]: *** [package/feeds/helloworld/xray-core/compile] Error 2
make[2]: Leaving directory '/home/etek/openwrt'
package/Makefile:107: recipe for target '/home/etek/openwrt/staging_dir/target-mipsel_24kc_musl/stamp/.package_compile' failed
make[1]: *** [/home/etek/openwrt/staging_dir/target-mipsel_24kc_musl/stamp/.package_compile] Error 2
make[1]: Leaving directory '/home/etek/openwrt'
/home/etek/openwrt/include/toplevel.mk:225: recipe for target 'world' failed
make: *** [world] Error 2

**Comment by 1715173329** [comment]
不支持 openwrt 19.07 的 go toolchain，或者你网烂了。

**Comment by jxph1123** [comment]
我就是编译 L大的稳定版 openwrt 19.07 ，头两天可以，今天更新了就不行了

**Comment by pangfeng161** [comment]
有什么解决的方式?

**Comment by a1073185067** [comment]
我也是这个问题

**Comment by jxph1123** [comment]
重新拉源码重新编译就可以了，关闭了
