### ISSUE TITLE
./scripts/update -a  更新helloworld失败

### ISSUE THREAD

**Issue by LeanFly** [fw876/helloworld#749]
Updating feed 'helloword' from 'https://github.com/fw876/helloworld.git' ...
fatal: Not possible to fast-forward, aborting.
failed.

**Comment by Beginner-Go** [comment]
被大雕 -f 了

**Comment by Gzxhwq** [comment]
因为force push了
./scripts/feeds clean吧

**Comment by 1715173329** [comment]
Fixed.
