### ISSUE TITLE
[功能请求]希望能推出禁用dns缓存的选项

### ISSUE THREAD

**Issue by ShoukakuChuuCC** [fw876/helloworld#754]
我想禁用dns缓存，我不需要它，它会在我的环境中产生不良反应。

**Comment by 1715173329** [comment]
https://github.com/fw876/helloworld/blob/3c14800d884b31f11e3593367b49f32d3e54c719/luci-app-ssr-plus/root/etc/init.d/shadowsocksr#L188-L189

你可以自行更改配置，或者直接不使用 ssrplus 的 DNS daemon。
