### ISSUE TITLE
今天刚刚编译发现个库错误

### ISSUE THREAD

**Issue by chiyu521** [fw876/helloworld#757]
SSR日志提示
Main node:Error loading shared library libboost_system.so.1.76.0: No such file or directory (needed by /var/etc/ssrplus/bin/trojan) , 4 Threads Started!
我去查看了文件并不缺少trojan

**Comment by chiyu521** [comment]
原因找到了 新编译的库已经升级到libboost_system.so.1.78.0了 helloword 还没升级

**Comment by 1715173329** [comment]
#740
