### ISSUE TITLE
ssr更新后无法正常启动

### ISSUE THREAD

**Issue by lipwah** [fw876/helloworld#761]
ssr版本184-10
![99999](https://user-images.githubusercontent.com/56858494/148002254-20773ba7-2582-46fb-881d-a31a882cbdd8.png)
![88888](https://user-images.githubusercontent.com/56858494/148002603-7320703f-76e9-4a2d-8b11-6cae2c81ef34.png)

**Comment by 1715173329** [comment]
实在是不知道你想要表达什么
