### ISSUE TITLE
编译官方的 18.06 Openwrt 时，没有 luci-app-ssr-plus 这个选项

### ISSUE THREAD

**Issue by Ho-Lay** [fw876/helloworld#764]
编译官方的 18.06 Openwrt ，LuCI ---> Applications 里面没有 luci-app-ssr-plus 这个选项，请问大佬该怎样解决？

**Comment by 1715173329** [comment]
1. 官方 18.06 已经不受支持了
2. 看 README

**Comment by Ho-Lay** [comment]
> 1. 官方 18.06 已经不受支持了
> 2. 自行选上 libusteam-openssl
> 3. 看 README

好的  谢谢
