### ISSUE TITLE
在SSR选了GFW，怎样登录微软中国不用经代理。

### ISSUE THREAD

**Issue by dengchan0416** [fw876/helloworld#767]
已经选了GFW，登录微软中国还是用了代理。怎样改回登录识别是国内
![image](https://user-images.githubusercontent.com/41529838/148669330-3d8aa404-9396-4b46-94f7-09de8c7d656f.png)

**Comment by 1715173329** [comment]
https://github.com/v2ray/domain-list-community/blob/master/data/microsoft

**Comment by dengchan0416** [comment]
> https://github.com/v2ray/domain-list-community/blob/master/data/microsoft

怎么搞。。看不懂，是把这里的网址放到不代理吗？

**Comment by poctopus** [comment]
看你的gfwlist中是否包含了列表中的域名。

**Comment by Benjamin23333** [comment]
用第二个Loyalsoldier那个列表就好了

**Comment by WhiteHDD** [comment]
ssr的”访问控制-不走代理“中添加域名
