### ISSUE TITLE
读取Torjan订阅时候不能正确读取“允许不安全”选项，导致中转的Torjan节点不能使用。

### ISSUE THREAD

**Issue by sunzjy** [fw876/helloworld#768]
正常情况下，落地节点关闭“允许不安全”，中转连接开启“允许不安全”，可保证数据加密安全。暂时情况下无论中转怎么设置，最终读取后都是关闭“允许不安全”。

**Comment by 1715173329** [comment]
> 中转连接开启“允许不安全”，可保证数据加密安全

？

**Comment by sunzjy** [comment]
> > 中转连接开启“允许不安全”，可保证数据加密安全
> 
> ？

落地节是关闭“允许不安全”及设置了SNI的。

**Comment by sunzjy** [comment]
这样设置主要是希望通过SNI设置达到域前置效果。

**Comment by 1715173329** [comment]
直接说，根据 Trojan 分享链接（草案），没有这个选项
https://p4gefau1t.github.io/trojan-go/developer/url/

另外，中转到落地怎么设置与你没有关系
