### ISSUE TITLE
關於移除 alterId 配置项并强制启用 VMess AEAD 认证問題

### ISSUE THREAD

**Issue by sage-E3845** [fw876/helloworld#772]
我讓機場主換了VMess AEAD之後，機場主表示aead頻繁給他墻端口，當時MD5的時候沒有這個問題，目前機場主已哭暈在厠所

**Comment by zusterben** [comment]
现在的情况就是你越遮遮掩掩墙就认为你干的事是不能见光的，如果你光明正大的告诉墙你在看片，那么他基本就不会管你
