### ISSUE TITLE
ssrp全局透明代理下无法使用choco等软件

### ISSUE THREAD

**Issue by cxgreat2014** [fw876/helloworld#776]
ssrp全局透明代理下无法使用choco等软件，如图：

![WJ5T3U(SW8R4BTHG@TJRV59](https://user-images.githubusercontent.com/15062548/150562969-07d65b91-b082-4fd0-bd16-ecec8b26f5fa.png)

但相同节点使用passwall又可以，所以怀疑是ssrp的问题。

**Comment by Beginner-Go** [comment]
把那个网址添加到 `代理域名` 里试试？
