### ISSUE TITLE
无法支持多个订阅地址

### ISSUE THREAD

**Issue by maxjove** [fw876/helloworld#78]
目前测试无法支持多个订阅地址, 更新订阅始终只更新第一个订阅地址的节点,第二个订阅地址里的节点出发更新到.
![image](https://user-images.githubusercontent.com/3186008/84642103-93212200-af2e-11ea-8864-186cce5f6a54.png)

**Comment by SharerMax** [comment]
请提供日志

**Comment by maxjove** [comment]
对方服务问题,关闭
