### ISSUE TITLE
openwrt master分支下，已经加入read里的相关依赖，出现报错。请大佬指点一下

### ISSUE THREAD

**Issue by Lancet-z** [fw876/helloworld#780]
编译后始终有这个报错

* check_data_file_clashes: Package dnsmasq-full wants to install file /workdir/openwrt/build_dir/target-x86_64_musl/root-x86/etc/hotplug.d/ntp/25-dnsmasqsec
Configuring iptables-mod-tproxy.
	But that file is already provided by package  * dnsmasq
Configuring microsocks.
 * check_data_file_clashes: Package dnsmasq-full wants to install file /workdir/openwrt/build_dir/target-x86_64_musl/root-x86/etc/init.d/dnsmasq
Configuring tcping.
	But that file is already provided by package  * dnsmasq
Configuring libnghttp2-14.
 * check_data_file_clashes: Package dnsmasq-full wants to install file /workdir/openwrt/build_dir/target-x86_64_musl/root-x86/etc/uci-defaults/50-dnsmasq-migrate-resolv-conf-auto.sh
Configuring libcurl4.
	But that file is already provided by package  * dnsmasq
Configuring curl.
 * check_data_file_clashes: Package dnsmasq-full wants to install file /workdir/openwrt/build_dir/target-x86_64_musl/root-x86/usr/lib/dnsmasq/dhcp-script.sh
Configuring xray-core.
	But that file is already provided by package  * dnsmasq
Configuring luci-app-ssr-plus.
 * check_data_file_clashes: Package dnsmasq-full wants to install file /workdir/openwrt/build_dir/target-x86_64_musl/root-x86/usr/sbin/dnsmasq
Configuring grub2-bios-setup.
	But that file is already provided by package  * dnsmasq
Configuring odhcp6c.
 * check_data_file_clashes: Package dnsmasq-full wants to install file /workdir/openwrt/build_dir/target-x86_64_musl/root-x86/usr/share/acl.d/dnsmasq_acl.json
Configuring unzip.
	But that file is already provided by package  * dnsmasq
Configuring uci.
 * check_data_file_clashes: Package dnsmasq-full wants to install file /workdir/openwrt/build_dir/target-x86_64_musl/root-x86/usr/share/dnsmasq/dhcpbogushostname.conf
Configuring grub2.
	But that file is already provided by package  * dnsmasq
Configuring dropbear.
 * check_data_file_clashes: Package dnsmasq-full wants to install file /workdir/openwrt/build_dir/target-x86_64_musl/root-x86/usr/share/dnsmasq/rfc6761.conf
Configuring kmod-hwmon-core.
	But that file is already provided by package  * dnsmasq
Configuring luci-theme-openwrt-2020.
 * opkg_install_cmd: Cannot install package dnsmasq-full.
Configuring libgmp10.
 * check_data_file_clashes: Package dnsmasq-full wants to install file /workdir/openwrt/build_dir/target-x86_64_musl/root-x86/etc/hotplug.d/ntp/25-dnsmasqsec
Configuring luci-compat.
	But that file is already provided by package  * dnsmasq
Configuring mtd.
 * check_data_file_clashes: Package dnsmasq-full wants to install file /workdir/openwrt/build_dir/target-x86_64_musl/root-x86/etc/init.d/dnsmasq
Configuring odhcpd-ipv6only.
	But that file is already provided by package  * dnsmasq
Configuring procd-seccomp.
 * check_data_file_clashes: Package dnsmasq-full wants to install file /workdir/openwrt/build_dir/target-x86_64_musl/root-x86/etc/uci-defaults/50-dnsmasq-migrate-resolv-conf-auto.sh
Configuring urandom-seed.
	But that file is already provided by package  * dnsmasq
 * check_data_file_clashes: Package dnsmasq-full wants to install file /workdir/openwrt/build_dir/target-x86_64_musl/root-x86/usr/lib/dnsmasq/dhcp-script.sh
	But that file is already provided by package  * dnsmasq
 * check_data_file_clashes: Package dnsmasq-full wants to install file /workdir/openwrt/build_dir/target-x86_64_musl/root-x86/usr/sbin/dnsmasq
	But that file is already provided by package  * dnsmasq
 * check_data_file_clashes: Package dnsmasq-full wants to install file /workdir/openwrt/build_dir/target-x86_64_musl/root-x86/usr/share/acl.d/dnsmasq_acl.json
Configuring luci-proto-ppp.
	But that file is already provided by package  * dnsmasq
 * check_data_file_clashes: Package dnsmasq-full wants to install file /workdir/openwrt/build_dir/target-x86_64_musl/root-x86/usr/share/dnsmasq/dhcpbogushostname.conf
	But that file is already provided by package  * dnsmasq
 * check_data_file_clashes: Package dnsmasq-full wants to install file /workdir/openwrt/build_dir/target-x86_64_musl/root-x86/usr/share/dnsmasq/rfc6761.conf
	But that file is already provided by package  * dnsmasq
 * opkg_install_cmd: Cannot install package luci-app-ssr-plus.
make[2]: *** [package/Makefile:70: package/install] Error 255
make[1]: *** [package/Makefile:111: /workdir/openwrt/staging_dir/target-x86_64_musl/stamp/.package_install] Error 2
Configuring libcomerr0.
Configuring ppp.
Configuring rpcd-mod-iwinfo.
Configuring luci-mod-network.
Configuring luci-mod-admin-full.
Configuring libnettle8.
Configuring luci-i18n-ssr-plus-zh-cn.
Configuring logd.
Configuring shadowsocks-libev-ss-local.
Configuring luci-proto-ipv6.
Configuring shadowsocksr-libev-ssr-local.
Configuring libss2.
Configuring libext2fs2.
Configuring e2fsprogs.
Configuring libcares.
Configuring kmod-pps.
Configuring uhttpd.
Configuring shadowsocks-libev-ss-redir.
Configuring shadowsocksr-libev-ssr-redir.
Configuring luci-i18n-base-zh-cn.
Configuring kmod-ptp.
Configuring uhttpd-mod-ubus.
Configuring rpcd-mod-rrdns.
Configuring luci.
Configuring shadowsocks-libev-ss-server.
Configuring luci-i18n-opkg-zh-cn.
Configuring v2ray-core.
Configuring kmod-button-hotplug.
Configuring kmod-i2c-algo-bit.
Configuring urngd.
Configuring luci-i18n-firewall-zh-cn.
Configuring ppp-mod-pppoe.
Configuring coreutils-nohup.
make[2]: Leaving directory '/workdir/openwrt'
make[1]: Leaving directory '/workdir/openwrt'
make: *** [/workdir/openwrt/include/toplevel.mk:230: world] Error 2
Error: Process completed with exit code 2.

**Comment by Lancet-z** [comment]
附上编译时配置文件

diy-1

echo 'src-git passwall https://github.com/xiaorouji/openwrt-passwall' >>feeds.conf.default
echo 'src-git helloworld https://github.com/fw876/helloworld' >>feeds.conf.default
#添加驱动
cd ./package/kernel
git clone https://github.com/goldkeyber112/openwrt-r8168.git

diy-2

sed -i 's/192.168.1.1/192.168.10.1/g' package/base-files/files/bin/config_generate
#修正连接数（by ベ七秒鱼ベ）
sed -i '/customized in this file/a net.netfilter.nf_conntrack_max=165535' package/base-files/files/etc/sysctl.conf
#添加额外软件包
#mkdir -p package/helloworld
for i in "dns2socks" "microsocks" "ipt2socks" "pdnsd-alt" "redsocks2"; do \
  svn checkout "https://github.com/immortalwrt/packages/trunk/net/$i" "package/helloworld/$i"; \
done

svn checkout https://github.com/coolsnowwolf/lede/trunk/tools/ucl tools/ucl
svn checkout https://github.com/coolsnowwolf/lede/trunk/tools/upx tools/upx

sed -i 'N;24a\tools-y += ucl upx' tools/Makefile
sed -i 'N;40a\$(curdir)/upx/compile := $(curdir)/ucl/compile' tools/Makefile

**Comment by SGPublic** [comment]
这是 `CONFIG_PACKAGE_dnsmasq` 和 `CONFIG_PACKAGE_dnsmasq-full` 冲突了。

手动编译的话 `make menuconfig` 取消选中 `->
 Base System-> dnsmasq`，

Action 云编译的话提前在 `.config` 里面添加
```
# CONFIG_PACKAGE_dnsmasq is not set
```

**Comment by Lancet-z** [comment]
> 这是 和 冲突了。`CONFIG_PACKAGE_dnsmasq``CONFIG_PACKAGE_dnsmasq-full`
> 
> 手动编译的话 取消选中 ，`make menuconfig``-> Base System -> dnsmasq`
> 
> Action 云编译的话提前在 里面添加`.config`
> 
> ```
> # CONFIG_PACKAGE_dnsmasq is not set
> ```

好的谢谢，我再试试看

**Comment by Lancet-z** [comment]
> 

大佬，我因为我也是拉取的官方最新源码进行云编译，所有参考了你的项目。diy-1里，添加依赖的命令

svn checkout https://github.com/coolsnowwolf/lede/trunk/tools/ucl tools/ucl
svn checkout https://github.com/coolsnowwolf/lede/trunk/tools/upx tools/upx

是不是需要将ttps://github.com/coolsnowwolf/lede/trunk/tools/upx这个部分替换成自己项目的地址。如果是官方最新分支是不是也要像你项目中的那样替换为

svn checkout xxxxxx/trunk/sgpublic/tools/upx tools/upx

**Comment by SGPublic** [comment]
不需要，我只是为了控制版本而已
