### ISSUE TITLE
为什么SS的加密方式只有这几个？

### ISSUE THREAD

**Issue by Lintao-Zeng** [fw876/helloworld#781]
![](https://github.com/Lintao-Zeng/Test/raw/master/QQ%E6%88%AA%E5%9B%BE20220128191752.png)

**Comment by 1715173329** [comment]
https://shadowsocks.org/en/wiki/Stream-Ciphers.html
"Stream ciphers are completely broken and will be removed soon. New users must use AEAD ciphers."
