### ISSUE TITLE
建议自动更新节点的时候先删除所有节点，或者将这作为一个可选项

### ISSUE THREAD

**Issue by yubanmeiqin9048** [fw876/helloworld#79]
有时候鸡场节点有变动，自动更新就会有好几个没用的节点，但是没用的节点并没有删除

**Comment by Hey-Leo** [comment]
### 可无视，不重要的
没有批量管理的功能，一些节点多的话，不想要的只能一个一个删除，删除后一更新又全回来，（ 似乎可以用关键字过滤 ，但是关键字容易一锅端，不然就要独立的特征，这样关键字又一个个录进去，突然发现过滤是个好东西，好像隔壁vssr没这 ），太多节点在那里点开自动ping不是会很慢

**Comment by SharerMax** [comment]
请提供日志
