### ISSUE TITLE
“服务端”功能，不兼容IPV6？

### ISSUE THREAD

**Issue by huangsijun17** [fw876/helloworld#796]
[电信也开始退家宽的IPV4公网](https://bbs.kafan.cn/thread-2227022-1-1.html)了，我测试了一下手机走IPV6连路由器，失败了。
防火墙需要额外设置？
Acrh-17 OpenWrt R20.12.12

**Comment by jxph1123** [comment]
防火墙需要设置，移动的IP6都封了80口，IP6访问只能其他端口，还得过防火墙

**Comment by loryncien** [comment]
看不懂代码，感觉好像是的。
四川移动，ipv6回家，开启ss服务端，在ssrp里面就不行，而passwall里面或单独的v2ray服务端插件可以。现在也一直用后面的工具回家。

**Comment by 1715173329** [comment]
不支持 ipv6，请自行设定防火墙。

**Comment by loryncien** [comment]
> 看不懂代码，感觉好像是的。 四川移动，IPv6 回家，开启 SS 服务端，在 ssrp 里面开启就不行，而在 passwall 里面或单独的 v2ray 服务端插件可以。现在也一直用 passwall 服务端回家。

每个服务端测试删除后再创建，使用同一端口，SS服务端相同配置：
- ssrp socks5 服务端， telegram ipv6能连接
- ssrp SS 服务端， quantumult X 回家 不能连
- passwall SS 服务端， quantumult X 回家 能连
