### ISSUE TITLE
请教一下自动切换后能否让节点一直用下去？

### ISSUE THREAD

**Issue by TunBiXia-Bitcoin** [fw876/helloworld#798]
大佬们好，请教一下自动切换后能否让节点一直用下去？
现在发现主节点恢复后又切换会主节点了，可否一直用切换后的节点？
感谢。

**Comment by 1715173329** [comment]
这不符合逻辑。

**Comment by TunBiXia-Bitcoin** [comment]
> 这不符合逻辑。

其实是符合逻辑的，因为每个节点都是平等的，并不存在所谓的主节点。
