### ISSUE TITLE
反馈一个问题，出现的原因大致是编译顺序的问题

### ISSUE THREAD

**Issue by Pastechn** [fw876/helloworld#8]
首次编译时，容易报错：`bash: po2lmo: command not found`
这应该是因为编译 hello world 需要把 luci-base 先编译出来，但是目前顺序可能是先编译了 hello world 导致出现问题，此时使用 `make package/feeds/luci/luci-base/compile V=99` 编译出 luci-base 后再编译就不会报错。
这个问题虽然出现的频率不高，但是也不低，这几天已经遇到好几个群友出现这个问题了，不知道能不能优化一下，尽量避免这个问题的出现。

**Comment by lqdflying** [comment]
我也遇见了,解决方法和楼主一样,额外还有一个问题,
默认的https://mirror2.openwrt.org/sources/cryptopp564.zip源码地址失效了,导致编译失败
我找了个能用的源码包地址,这里一并附上解决方法:
修改:package/lean/libcryptopp/Makefile里的这一行:
`PKG_SOURCE_URL:=https://src.fedoraproject.org/lookaside/pkgs/rpms/cryptopp/cryptopp564.zip/4ee7e5cdd4a45a14756c169eaf2a77fc`

**Comment by garypang13** [comment]
我也遇到了,我的解决办法是把package.mk换成luci.mk, 这样语言包就会单独编译成ipk,这样才是luci最规范的写法.

**Comment by mcucore** [comment]
我也遇上了，应该是全新编译一定会出错，编译plus+时要用的PO2LMO还没被编译出来。

**Comment by snakwu** [comment]
> 我也遇到了,我的解决办法是把package.mk换成luci.mk, 这样语言包就会单独编译成ipk,这样才是luci最规范的写法.

其体怎么改法，谢谢

**Comment by garypang13** [comment]
> > 我也遇到了,我的解决办法是把package.mk换成luci.mk, 这样语言包就会单独编译成ipk,这样才是luci最规范的写法.
> 
> 其体怎么改法，谢谢

可以参考这个 https://github.com/garypang13/Actions-OpenWrt-Nginx/blob/master/diy.sh

主要是这几行命令
```
sed -i "/bin\/upx/d" package/*/*/*/Makefile
sed -i "/po2lmo /d" package/*/custom/*/Makefile
sed -i "/luci\/i18n/d" package/*/custom/*/Makefile
sed -i "/*\.po/d" package/*/custom/*/Makefile
sed -i '$a $(foreach pkg,$(LUCI_BUILD_PACKAGES),$(eval $(call BuildPackage,$(pkg))))' package/*/*/luci-*/Makefile
sed -i 's/$(INCLUDE_DIR)\/package.mk/$(TOPDIR)\/feeds\/luci\/luci.mk/g' package/*/*/luci-app-*/Makefile
```

**Comment by snakwu** [comment]
> > > 我也遇到了,我的解决办法是把package.mk换成luci.mk, 这样语言包就会单独编译成ipk,这样才是luci最规范的写法.
> > 
> > 
> > 其体怎么改法，谢谢
> 
> 可以参考这个 https://github.com/garypang13/Actions-OpenWrt-Nginx/blob/master/diy.sh
> 
> 主要是这几行命令
> 
> ```
> sed -i "/po2lmo /d" package/*/custom/*/Makefile
> sed -i "/luci\/i18n/d" package/*/custom/*/Makefile
> sed -i "/*\.po/d" package/*/custom/*/Makefile
> sed -i "/foreach pkg/d" feeds/luci/luci.mk;
> sed -i '$a $(foreach pkg,$(LUCI_BUILD_PACKAGES),$(eval $(call BuildPackage,$(pkg))))' package/*/*/luci-*/Makefile
> sed -i 's/$(INCLUDE_DIR)\/package.mk/$(TOPDIR)\/feeds\/luci\/luci.mk/g' package/*/*/luci-app-*/Makefile
> ```

试了没有独立生成语言包!

**Comment by coolsnowwolf** [comment]
这个其实是为了兼容 BB （14.07） 和官改的遗留问题

**Comment by liwenjie119** [comment]
本地-j1全新编译同样出问题了，于是按照上面的先编译luci-base才好；但是云编译正常编译完成，不知道到底啥情况

**Comment by kktt007** [comment]
# 我也有错误
![我也有错误](https://img.vim-cn.com/9a/fd62d259015baae5a683b64ca4168ad8738f21.png)

**Comment by jw10126121** [comment]
> > > 我也遇到了,我的解决办法是把package.mk换成luci.mk, 这样语言包就会单独编译成ipk,这样才是luci最规范的写法.
> > 
> > 
> > 其体怎么改法，谢谢
> 
> 可以参考这个 https://github.com/garypang13/Actions-OpenWrt-Nginx/blob/master/diy.sh
> 
> 主要是这几行命令
> 
> ```
> sed -i "/po2lmo /d" package/*/custom/*/Makefile
> sed -i "/luci\/i18n/d" package/*/custom/*/Makefile
> sed -i "/*\.po/d" package/*/custom/*/Makefile
> sed -i "/foreach pkg/d" feeds/luci/luci.mk;
> sed -i '$a $(foreach pkg,$(LUCI_BUILD_PACKAGES),$(eval $(call BuildPackage,$(pkg))))' package/*/*/luci-*/Makefile
> sed -i 's/$(INCLUDE_DIR)\/package.mk/$(TOPDIR)\/feeds\/luci\/luci.mk/g' package/*/*/luci-app-*/Makefile
> ```

也就是说，通过sed命令，去修改源码下的这几处，就可以不用先编译luci-base(make package/feeds/luci/luci-base/compile V=99)?，这样做，会不会造成什么问题，或者说改不全的地方

**Comment by garypang13** [comment]
> > > > 我也遇到了,我的解决办法是把package.mk换成luci.mk, 这样语言包就会单独编译成ipk,这样才是luci最规范的写法.
> > > 
> > > 
> > > 其体怎么改法，谢谢
> > 
> > 
> > 可以参考这个 https://github.com/garypang13/Actions-OpenWrt-Nginx/blob/master/diy.sh
> > 主要是这几行命令
> > ```
> > sed -i "/po2lmo /d" package/*/custom/*/Makefile
> > sed -i "/luci\/i18n/d" package/*/custom/*/Makefile
> > sed -i "/*\.po/d" package/*/custom/*/Makefile
> > sed -i "/foreach pkg/d" feeds/luci/luci.mk;
> > sed -i '$a $(foreach pkg,$(LUCI_BUILD_PACKAGES),$(eval $(call BuildPackage,$(pkg))))' package/*/*/luci-*/Makefile
> > sed -i 's/$(INCLUDE_DIR)\/package.mk/$(TOPDIR)\/feeds\/luci\/luci.mk/g' package/*/*/luci-app-*/Makefile
> > ```
> 
> 也就是说，通过sed命令，去修改源码下的这几处，就可以不用先编译luci-base(make package/feeds/luci/luci-base/compile V=99)?，这样做，会不会造成什么问题，或者说改不全的地方

我自己一直在用这个方法, 还没遇到什么问题,

**Comment by jw10126121** [comment]
> > > > > 我也遇到了,我的解决办法是把package.mk换成luci.mk, 这样语言包就会单独编译成ipk,这样才是luci最规范的写法.
> > > > 
> > > > 
> > > > 其体怎么改法，谢谢
> > > 
> > > 
> > > 可以参考这个 https://github.com/garypang13/Actions-OpenWrt-Nginx/blob/master/diy.sh
> > > 主要是这几行命令
> > > ```
> > > sed -i "/po2lmo /d" package/*/custom/*/Makefile
> > > sed -i "/luci\/i18n/d" package/*/custom/*/Makefile
> > > sed -i "/*\.po/d" package/*/custom/*/Makefile
> > > sed -i "/foreach pkg/d" feeds/luci/luci.mk;
> > > sed -i '$a $(foreach pkg,$(LUCI_BUILD_PACKAGES),$(eval $(call BuildPackage,$(pkg))))' package/*/*/luci-*/Makefile
> > > sed -i 's/$(INCLUDE_DIR)\/package.mk/$(TOPDIR)\/feeds\/luci\/luci.mk/g' package/*/*/luci-app-*/Makefile
> > > ```
> > 
> > 
> > 也就是说，通过sed命令，去修改源码下的这几处，就可以不用先编译luci-base(make package/feeds/luci/luci-base/compile V=99)?，这样做，会不会造成什么问题，或者说改不全的地方
> 
> 我自己一直在用这个方法, 还没遇到什么问题,

因为我看到你的diy.sh里面，还有其他修改，比如
sed -i 's/..\/..\/luci.mk/$(TOPDIR)\/feeds\/luci\/luci.mk/g' package/*/*/*/Makefile
find package/*/custom/*/ -maxdepth 2 ! -path "*shadowsocksr-libev*" -name "Makefile" ! -path "*rblibtorrent1*" -name "Makefile" \
| xargs -i sed -i "s/PKG_SOURCE_VERSION:=[0-9a-z]\{15,\}/PKG_SOURCE_VERSION:=latest/g" {}
find package/*/custom/*/ -maxdepth 2 -name "Makefile" | xargs -i sed -i "s/SUBDIRS=/M=/g" {}
sed -i 's/$(VERSION) &&/$(VERSION) ;/g' include/download.mk
sed -i 's/PKG_BUILD_DIR:=/PKG_BUILD_DIR?=/g' feeds/luci/luci.mk
sed -i 's/$(INCLUDE_DIR)\/package.mk/$(TOPDIR)\/feeds\/luci\/luci.mk/g' package/*/*/luci-app-*/Makefile
sed -i "/foreach pkg/d" feeds/luci/luci.mk;
sed -i "/foreach pkg/d" package/*/*/luci-*/Makefile
sed -i '$a $(foreach pkg,$(LUCI_BUILD_PACKAGES),$(eval $(call BuildPackage,$(pkg))))' package/*/*/luci-*/Makefile
find package/*/custom/*/ -maxdepth 1 -d -name "i18n" | xargs -i rename -v 's/i18n/po/' {}
find package/*/custom/*/ -maxdepth 2 -d -name "zh-cn" | xargs -i rename -v 's/zh-cn/zh_Hans/' {}
sed -i "/bin\/upx/d" package/*/*/*/Makefile
sed -i "/po2lmo /d" package/*/custom/*/Makefile
sed -i "/luci\/i18n/d" package/*/custom/*/Makefile
sed -i "/*\.po/d" package/*/custom/*/Makefile
所以确认一下，非常感谢。。。

**Comment by jw10126121** [comment]
> > > > > 我也遇到了,我的解决办法是把package.mk换成luci.mk, 这样语言包就会单独编译成ipk,这样才是luci最规范的写法.
> > > > 
> > > > 
> > > > 其体怎么改法，谢谢
> > > 
> > > 
> > > 可以参考这个 https://github.com/garypang13/Actions-OpenWrt-Nginx/blob/master/diy.sh
> > > 主要是这几行命令
> > > ```
> > > sed -i "/po2lmo /d" package/*/custom/*/Makefile
> > > sed -i "/luci\/i18n/d" package/*/custom/*/Makefile
> > > sed -i "/*\.po/d" package/*/custom/*/Makefile
> > > sed -i "/foreach pkg/d" feeds/luci/luci.mk;
> > > sed -i '$a $(foreach pkg,$(LUCI_BUILD_PACKAGES),$(eval $(call BuildPackage,$(pkg))))' package/*/*/luci-*/Makefile
> > > sed -i 's/$(INCLUDE_DIR)\/package.mk/$(TOPDIR)\/feeds\/luci\/luci.mk/g' package/*/*/luci-app-*/Makefile
> > > ```
> > 
> > 
> > 也就是说，通过sed命令，去修改源码下的这几处，就可以不用先编译luci-base(make package/feeds/luci/luci-base/compile V=99)?，这样做，会不会造成什么问题，或者说改不全的地方
> 
> 我自己一直在用这个方法, 还没遇到什么问题,

sed -i 's/PKG_BUILD_DIR:=/PKG_BUILD_DIR?=/g' $root/feeds/luci/luci.mk
sed -i "/foreach pkg/d" $root/package/*/*/luci-*/Makefile
find $root/package/*/*/ -maxdepth 1 -d -name "i18n" | xargs -i rename -v 's/i18n/po/' {}
find $root/package/*/*/ -maxdepth 2 -d -name "zh-cn" | xargs -i rename -v 's/zh-cn/zh_Hans/' {}
sed -i "/bin\/upx/d" $root/package/*/*/*/Makefile
这5句，不改的话，好像有点问题。。。。
特别是 sed -i "/foreach pkg/d" $root/package/*/*/luci-*/Makefile

**Comment by garypang13** [comment]
find $root/package/// -maxdepth 1 -d -name "i18n" | xargs -i rename -v 's/i18n/po/' {}
find $root/package/// -maxdepth 2 -d -name "zh-cn" | xargs -i rename -v 's/zh-cn/zh_Hans/' {}
这两句是特别针对luci19.07的.如果是用的luci18.06则可以忽略.
sed -i "/foreach pkg/d" $root/package///luci-*/Makefile这一句可以加上,但要在其他那几句的前面.

**Comment by jw10126121** [comment]
> ```
> find $root/package/// -maxdepth 1 -d -name "i18n" | xargs -i rename -v 's/i18n/po/' {}
> find $root/package/// -maxdepth 2 -d -name "zh-cn" | xargs -i rename -v 's/zh-cn/zh_Hans/' {}
> ```
> 
> 这两句是特别针对luci19.07的.如果是用的luci18.06则可以忽略.
> `sed -i "/foreach pkg/d" $root/package///luci-*/Makefile`
> 这一句可以加上,但要在其他那几句的前面.

用了这11句，各种报错，看来是我的配置用不了了，也感谢
