### ISSUE TITLE
不支持vless节点的订阅

### ISSUE THREAD

**Issue by binhe-cpu** [fw876/helloworld#801]
请问不支持vless节的订阅吗？节点导入vless一节点没问题。

**Comment by czxinshui** [comment]
打开编译文件helloworld/luci-app-ssr-plus/root/usr/share/shadowsocksr/subscribe.lua
删除掉第221-224行
-- [https://www.v2fly.org/config/protocols/vmess.html#vmess-md5-认证信息-淘汰机制](https://www.v2fly.org/config/protocols/vmess.html#vmess-md5-%E8%AE%A4%E8%AF%81%E4%BF%A1%E6%81%AF-%E6%B7%98%E6%B1%B0%E6%9C%BA%E5%88%B6)
if info.aid and (tonumber(info.aid) > 0) then
result.server = nil
end
再编译就可以订阅成功了
