### ISSUE TITLE
当代主服务器节点出现故障的时候国内也无法访问

### ISSUE THREAD

**Issue by xyz8899** [fw876/helloworld#808]
运行模式：绕过中国大陆IP模式
其他设置基本是默认的

情况：
当主服务器使用的节点出现故障的时候，国内网站也无法打开
同样环境下使用PassWall却没有这样的问题

**Comment by 1715173329** [comment]
什么叫做无法打开？具体表现为何？

**Comment by xyz8899** [comment]
> 什么叫做无法打开？具体表现为何？

就是无法联网、网站无法打开，百度都无法使用
