### ISSUE TITLE
ss节点用不了

### ISSUE THREAD

**Issue by xiaoyouke01** [fw876/helloworld#813]
![1](https://user-images.githubusercontent.com/71208560/156271886-86f2c214-4e6a-401f-a371-3b6d69a0fad6.jpg)
![2](https://user-images.githubusercontent.com/71208560/156271988-2587508d-7e56-43a6-b73f-af6444d942f1.jpg)
![image](https://user-images.githubusercontent.com/71208560/156274024-476506fb-e7b2-4241-8e58-7f785a69a143.png)

ss节点启动不了

**Comment by tone88** [comment]
redir tcp error  这个错误我也遇到过，而且现在遇到的问题是只要打开了服务端里的SS服务端，整个SSRP 就会一直不停的重启，日志见#811

**Comment by leochien0102** [comment]
> 

没开ss服务端，所以这2个问题不太一样

**Comment by 1715173329** [comment]
N1 is never officially supported by OpenWrt.

**Comment by hcym** [comment]
树莓4完美无缺，n1还没刷，明天早上醒来再说
