### ISSUE TITLE
已更新最新版，重启路由器，ssrp显示运行中，实际不能fq！

### ISSUE THREAD

**Issue by WXfeng-boy** [fw876/helloworld#82]
得需要保存应用才行，或者开机添加一个重启命令sleep 20 && /etc/init.d/shadowsocksr restart！

**Comment by aloph** [comment]
dhcpv6的支持没有编译进去，可以关闭dhcpv6试试

**Comment by WXfeng-boy** [comment]
> dhcpv6的支持没有编译进去，可以关闭dhcpv6试试

没编译进去，默认都是禁用的

**Comment by sk007** [comment]
> 得需要保存应用才行，或者开机添加一个重启命令sleep 20 && /etc/init.d/shadowsocksr restart！

是开启了Netflix 分流服务器 导致
关闭Netflix 分流服务器 后重启就正常了
