### ISSUE TITLE
ss是不是还有问题

### ISSUE THREAD

**Issue by xiaoyouke01** [fw876/helloworld#822]
旁路由下，ss节点用iplc，就打不开google，播放不了youtube
![无标题1](https://user-images.githubusercontent.com/71208560/157998488-9b90529e-7450-49b6-85f3-100e16f61e11.jpg)
![无标题2](https://user-images.githubusercontent.com/71208560/157998492-853403d2-f82d-4a8a-ad5a-06da4a45d890.jpg)
旁路由下，用vmess节点，打开任何网站就没问题
![无标题3](https://user-images.githubusercontent.com/71208560/157998544-f5d964ee-1ba6-400f-a4e4-459c0de8592f.jpg)
![无标题4](https://user-images.githubusercontent.com/71208560/157998547-4ea2c8f2-7c7b-456b-899e-e3dc9a46ca26.jpg)

**Comment by hcym** [comment]
我的正常运行，昨天晚上编译的，n1章鱼和x86都行

**Comment by xiaoyouke01** [comment]
网络环境不一样，看清楚是旁路由模式

> 我的正常运行，昨天晚上编译的，n1章鱼和x86都行

**Comment by 1715173329** [comment]
典型的 DNS 问题。设置成主路由即可，或继续用 v2ray/xray。
