### ISSUE TITLE
SSRP使用“绕过中国大陆IP模式”时，数据流量则会绕过openwrt自带的防火墙。

### ISSUE THREAD

**Issue by Zeezorn** [fw876/helloworld#823]
SSRP使用“绕过中国大陆IP模式”时，数据流量则会绕过openwrt自带的防火墙。
打开SSRP后，在“防火墙 - 通信规则”内设置一条规则：禁止转发某MAC地址发出的任何协议流量到任何区域。
此时该MAC地址的主机可以访问海外网站，而不能访问国内网站。
关闭SSRP之后，防火墙能拦截所有海内外流量。
很显然，SSRP在打开的状态下，海外流量绕过了openwrt自带的防火墙。
看起来像是个小小的BUG，不知技术上能否解决这一问题，谢谢。

**Comment by 1715173329** [comment]
可以试试在 `访问控制` -> `LAN IP 访问控制` -> `不走代理的局域网LAN IP` 添加相关条例。

**Comment by Zeezorn** [comment]
> 可以试试在 `访问控制` -> `LAN IP 访问控制` -> `不走代理的局域网LAN IP` 添加相关条例。

这样是可以，但如果防火墙规则里设定一个设备每天只能8：00~17：00访问互联网的话，操作起来不是很方便，每天到时间点要去SSRP里的“不走代理的局域网LAN IP”添加or删除一下IP。

**Comment by tone88** [comment]
GFW模式也一样。

**Comment by 1715173329** [comment]
目前无解。
如有需要可以配合 crontab 等工具
