### ISSUE TITLE
v2raya编译报错

### ISSUE THREAD

**Issue by MXJNZ6** [fw876/helloworld#824]
github.com/adrg/xdg@v0.4.0: reading https://goproxy.bj.bcebos.com/github.com/adrg/xdg/@v/v0.4.0.mod: 424 Failed Dependency
好像是这个链接有问题，复制到浏览器打开提示{"code":"MirrorFailed","message":"The command you provide is v/v0.4.0.mod:, it is not well formed.","requestId":"0f59175a-7bd1-4dd1-8c41-f3f05e5986b6"}

**Comment by MXJNZ6** [comment]
去除了v2raya下的goproxy和upx后报错:
Building targets
/home/mxj/lede/dl/go-mod-cache/github.com/gin-gonic/gin@v1.7.1/binding/form_mapping.go:16:2: no required module provides package github.com/gin-gonic/gin/internal/json; to add it:
	go get github.com/gin-gonic/gin/internal/json
package github.com/v2rayA/v2rayA
	imports github.com/gin-gonic/gin
	imports github.com/mattn/go-isatty: build constraints exclude all Go files in /home/mxj/lede/dl/go-mod-cache/github.com/mattn/go-isatty@v0.0.12
/home/mxj/lede/dl/go-mod-cache/github.com/v2fly/v2ray-core/v4@v4.42.2-0.20210928173456-a9979057dcaa/common/protocol/headers.go:6:2: no required module provides package github.com/v2fly/v2ray-core/v4/common/bitmask; to add it:
	go get github.com/v2fly/v2ray-core/v4/common/bitmask
/home/mxj/lede/dl/go-mod-cache/github.com/v2fly/v2ray-core/v4@v4.42.2-0.20210928173456-a9979057dcaa/common/protocol/server_spec.go:7:2: no required module provides package github.com/v2fly/v2ray-core/v4/common/dice; to add it:
	go get github.com/v2fly/v2ray-core/v4/common/dice
/home/mxj/lede/dl/go-mod-cache/github.com/v2fly/v2ray-core/v4@v4.42.2-0.20210928173456-a9979057dcaa/common/protofilter/filter.go:5:2: no required module provides package github.com/v2fly/v2ray-core/v4/common/environment/envctx; to add it:
	go get github.com/v2fly/v2ray-core/v4/common/environment/envctx
/home/mxj/lede/dl/go-mod-cache/github.com/v2fly/v2ray-core/v4@v4.42.2-0.20210928173456-a9979057dcaa/common/protofilter/filter.go:6:2: no required module provides package github.com/v2fly/v2ray-core/v4/common/environment/filesystemcap; to add it:
	go get github.com/v2fly/v2ray-core/v4/common/environment/filesystemcap
/home/mxj/lede/dl/go-mod-cache/github.com/v2fly/v2ray-core/v4@v4.42.2-0.20210928173456-a9979057dcaa/transport/internet/udp/dispatcher.go:12:2: no required module provides package github.com/v2fly/v2ray-core/v4/common/protocol/udp; to add it:
	go get github.com/v2fly/v2ray-core/v4/common/protocol/udp
/home/mxj/lede/dl/go-mod-cache/github.com/v2fly/v2ray-core/v4@v4.42.2-0.20210928173456-a9979057dcaa/common/log/logger.go:10:2: no required module provides package github.com/v2fly/v2ray-core/v4/common/signal/done; to add it:
	go get github.com/v2fly/v2ray-core/v4/common/signal/done
/home/mxj/lede/dl/go-mod-cache/github.com/v2fly/v2ray-core/v4@v4.42.2-0.20210928173456-a9979057dcaa/common/log/logger.go:11:2: no required module provides package github.com/v2fly/v2ray-core/v4/common/signal/semaphore; to add it:
	go get github.com/v2fly/v2ray-core/v4/common/signal/semaphore
/home/mxj/lede/dl/go-mod-cache/github.com/v2fly/v2ray-core/v4@v4.42.2-0.20210928173456-a9979057dcaa/v2ray.go:10:2: no required module provides package github.com/v2fly/v2ray-core/v4/features; to add it:
	go get github.com/v2fly/v2ray-core/v4/features
/home/mxj/lede/dl/go-mod-cache/github.com/v2fly/v2ray-core/v4@v4.42.2-0.20210928173456-a9979057dcaa/app/observatory/observer.go:23:2: no required module provides package github.com/v2fly/v2ray-core/v4/features/extension; to add it:
	go get github.com/v2fly/v2ray-core/v4/features/extension
/home/mxj/lede/dl/go-mod-cache/github.com/v2fly/v2ray-core/v4@v4.42.2-0.20210928173456-a9979057dcaa/transport/internet/dialer.go:7:2: no required module provides package github.com/v2fly/v2ray-core/v4/transport/internet/tagged; to add it:
	go get github.com/v2fly/v2ray-core/v4/transport/internet/tagged
/home/mxj/lede/dl/go-mod-cache/github.com/v2ray!a/shadowsocks!r@v1.0.4/obfs/tls12_ticket_auth.go:14:2: no required module provides package github.com/v2rayA/shadowsocksR/tools; to add it:
	go get github.com/v2rayA/shadowsocksR/tools
/home/mxj/lede/dl/go-mod-cache/go4.org/intern@v0.0.0-20211027215823-ae77deb06f29/intern.go:22:2: no required module provides package go4.org/unsafe/assume-no-moving-gc; to add it:
	go get go4.org/unsafe/assume-no-moving-gc

**Comment by MXJNZ6** [comment]
rm -rf tmp/go-build
rm -rf dl/go-mod-cache
rm -rf ./tmp(怕只删除go-build不保险)
然后不下载dl包了直接make -j1编译过了

**Comment by 1715173329** [comment]
关掉 GOPROXY。

**Comment by MXJNZ6** [comment]
> 关掉 GOPROXY，如果是 lean 稳定版或者 openwrt 19.07 及以下可能需要考虑升级 golang 版本。

关了，谢谢大佬
