### ISSUE TITLE
无法使用奈飞

### ISSUE THREAD

**Issue by TorBoxCode** [fw876/helloworld#827]
目前最新版本无法使用奈飞
1、服务器为自己搭建的trojan服务器，服务器确认可以使用奈飞，通过以前版本ssrp、电脑客户端使用可以正常访问。
2、ssrp使用trojan，在coolsnowwolf/lede最新源码的5.4、5.10、5.15内核都不可以。
3、目前版本在正常模式和启用 Netflix 分流模式下都不可以使用奈飞，4种GFWList；奈飞域名加入强制走代理的域名中都不可以。
4、订阅模式下目前没有资源暂时没有测试。
请问下大家只是我遇到这种问题还是

**Comment by deplives** [comment]
没问题
