### ISSUE TITLE
更新后新编译，打开服务器节点设置页面 系统日志中就出现报错

### ISSUE THREAD

**Issue by Suwipe** [fw876/helloworld#828]
Sat Mar 19 20:13:09 2022 daemon.err uhttpd[2432]: sh: curl: not found
Sat Mar 19 20:13:09 2022 daemon.err uhttpd[2432]: /usr/lib/lua/luci/dispatcher.lua:474: Failed to execute call dispatcher target for entry '/admin/services/shadowsocksr/ping'.
Sat Mar 19 20:13:09 2022 daemon.err uhttpd[2432]: The called action terminated with an exception:
Sat Mar 19 20:13:09 2022 daemon.err uhttpd[2432]: /usr/lib/lua/luci/controller/shadowsocksr.lua:59: attempt to perform arithmetic on a nil value
Sat Mar 19 20:13:09 2022 daemon.err uhttpd[2432]: stack traceback:
Sat Mar 19 20:13:09 2022 daemon.err uhttpd[2432]: 	[C]: in function 'assert'
Sat Mar 19 20:13:09 2022 daemon.err uhttpd[2432]: 	/usr/lib/lua/luci/dispatcher.lua:474: in function 'dispatch'
Sat Mar 19 20:13:09 2022 daemon.err uhttpd[2432]: 	/usr/lib/lua/luci/dispatcher.lua:126: in function </usr/lib/lua/luci/dispatcher.lua:125>
杠编译出的新版本，打开服务器节点设置页面 系统日志中就出现报错这是什么原因

**Comment by 1715173329** [comment]
命令行执行 tcping 看下是否正常运作。
