### ISSUE TITLE
最新版X86-64固件   运行后重启路由器无法访问Google   

### ISSUE THREAD

**Issue by leishao1993** [fw876/helloworld#83]
#73跟这个兄弟一样的问题 179.1版本  重启路由器之后无法连通Google  必须手动点击保存应用才可以    他的方法无效，因为根本没设置过服务端，刷回178.5的版本就没这个问题，原因未知
以下是日志：
Wed Jun 17 23:07:21 2020 user.notice dnsmasq: DNS rebinding protection is active, will discard upstream RFC1918 responses!
Wed Jun 17 23:07:21 2020 user.notice dnsmasq: Allowing 127.0.0.0/8 responses
Wed Jun 17 23:07:22 2020 kern.info /usr/bin/ssr-redir[5591]: initializing ciphers... chacha20
Wed Jun 17 23:07:22 2020 kern.info /usr/bin/ssr-redir[5591]: tcp port reuse enabled
Wed Jun 17 23:07:22 2020 kern.info /usr/bin/ssr-redir[5591]: listening at 0.0.0.0:4321
Wed Jun 17 23:07:22 2020 kern.info /usr/bin/ssr-redir[5591]: running from root user
Wed Jun 17 23:07:22 2020 kern.info /usr/bin/ssr-local[5593]: initializing ciphers... chacha20
Wed Jun 17 23:07:22 2020 kern.info /usr/bin/ssr-local[5593]: tcp port reuse enabled
Wed Jun 17 23:07:22 2020 kern.info /usr/bin/ssr-local[5593]: listening at 0.0.0.0:1088
Wed Jun 17 23:07:22 2020 kern.info /usr/bin/ssr-local[5593]: running from root user
Wed Jun 17 23:07:22 2020 user.notice dnsmasq: DNS rebinding protection is active, will discard upstream RFC1918 responses!
Wed Jun 17 23:07:22 2020 user.notice dnsmasq: Allowing 127.0.0.0/8 responses
Wed Jun 17 23:07:22 2020 user.notice dnsmasq: DNS rebinding protection is active, will discard upstream RFC1918 responses!
Wed Jun 17 23:07:22 2020 user.notice dnsmasq: Allowing 127.0.0.0/8 responses
Wed Jun 17 23:07:24 2020 cron.info crond[6132]: crond (busybox 1.30.0) started, log level 8
Wed Jun 17 23:07:24 2020 cron.info crond[6250]: crond (busybox 1.30.0) started, log level 8
Wed Jun 17 23:07:25 2020 kern.info /usr/bin/ssr-server[6567]: UDP relay enabled
Wed Jun 17 23:07:25 2020 kern.info /usr/bin/ssr-server[6567]: initializing ciphers... rc4-md5
Wed Jun 17 23:07:25 2020 kern.info /usr/bin/ssr-server[6567]: tcp port reuse enabled
Wed Jun 17 23:07:25 2020 kern.info /usr/bin/ssr-server[6567]: udp port reuse enabled
Wed Jun 17 23:07:25 2020 kern.info /usr/bin/ssr-server[6567]: listening at 0.0.0.0:8388
Wed Jun 17 23:07:25 2020 kern.info /usr/bin/ssr-server[6567]: running from root user
Wed Jun 17 23:07:25 2020 daemon.err miniupnpd[6628]: could not open lease file: /var/upnp.leases
Wed Jun 17 23:07:25 2020 daemon.notice miniupnpd[6628]: HTTP listening on port 5000
Wed Jun 17 23:07:25 2020 daemon.notice miniupnpd[6628]: Listening for NAT-PMP/PCP traffic on port 5351
Wed Jun 17 23:07:30 2020 daemon.notice procd: /etc/rc.d/S99openclash: OpenClash Already Stop
Wed Jun 17 23:07:30 2020 cron.info crond[6744]: crond (busybox 1.30.0) started, log level 8
Wed Jun 17 23:07:35 2020 daemon.notice procd: /etc/rc.d/S99serverchan: serverchan is starting now ...
Wed Jun 17 23:07:35 2020 user.notice transmission: Starting with 1978470000 virt mem
Wed Jun 17 23:07:36 2020 user.notice TTYD: Starting ttyd service
Wed Jun 17 23:07:36 2020 user.info wsdd2[7985]: starting.
Wed Jun 17 23:07:36 2020 daemon.notice procd: /etc/rc.d/S99zerotier: disabled in config
Wed Jun 17 23:07:36 2020 daemon.info procd: - init complete -
Wed Jun 17 23:07:42 2020 daemon.err uhttpd[2894]: cat: write error: Broken pipe
Wed Jun 17 23:07:45 2020 user.notice firewall: Reloading firewall due to ifup of wan (pppoe-wan)
Wed Jun 17 23:07:46 2020 cron.info crond[9083]: crond (busybox 1.30.0) started, log level 8
Wed Jun 17 23:07:47 2020 daemon.info procd: Instance nginx::instance1 s in a crash loop 6 crashes, 2 seconds since last crash
Wed Jun 17 23:07:47 2020 user.notice ddns-scripts[9161]: Oray: PID '9161' started at 2020-06-17 23:07
Wed Jun 17 23:07:47 2020 user.notice ddns-scripts[9163]: 3322: PID '9163' started at 2020-06-17 23:07
Wed Jun 17 23:07:48 2020 user.notice ddns-scripts[9162]: Aliddns: PID '9162' started at 2020-06-17 23:07
Wed Jun 17 23:07:49 2020 user.notice dnsmasq: DNS rebinding protection is active, will discard upstream RFC1918 responses!
Wed Jun 17 23:07:49 2020 user.notice dnsmasq: Allowing 127.0.0.0/8 responses
Wed Jun 17 23:07:52 2020 cron.info crond[17480]: crond (busybox 1.30.0) started, log level 8
Wed Jun 17 23:07:52 2020 cron.info crond[17598]: crond (busybox 1.30.0) started, log level 8
Wed Jun 17 23:07:53 2020 user.notice ddns-scripts[17794]: Oray: PID '17794' started at 2020-06-17 23:07
Wed Jun 17 23:07:53 2020 user.notice ddns-scripts[17796]: 3322: PID '17796' started at 2020-06-17 23:07
Wed Jun 17 23:07:53 2020 user.notice ddns-scripts[17795]: Aliddns: PID '17795' started at 2020-06-17 23:07
Wed Jun 17 23:07:54 2020 user.notice ddns-scripts[9163]: 3322: PID '9163' terminated by 'SIGTERM' at 2020-06-17 23:07
Wed Jun 17 23:07:54 2020 user.notice ddns-scripts[9161]: Oray: PID '9161' terminated by 'SIGTERM' at 2020-06-17 23:07
Wed Jun 17 23:07:55 2020 user.notice ddns-scripts[9162]: Aliddns: PID '9162' terminated by 'SIGTERM' at 2020-06-17 23:07

**Comment by leishao1993** [comment]
[https://i.loli.net/2020/06/17/6FihoC57Mc1tqmW.jpg](url)

**Comment by hplee0120** [comment]
保留配置升级系统之后这问题必现。。必须手动保存并应用一下才正常

**Comment by aloph** [comment]
可以尝试关闭dhcpv6

**Comment by WXfeng-boy** [comment]
> 保留配置升级系统之后这问题必现。。必须手动保存并应用一下才正常

我重新配置的，这个问题也存在

**Comment by sk007** [comment]
> > 保留配置升级系统之后这问题必现。。必须手动保存并应用一下才正常
> 
> 我重新配置的，这个问题也存在

多次测试 原因是 开启Netflix 分流服务器 导致

**Comment by hplee0120** [comment]
> > > 保留配置升级系统之后这问题必现。。必须手动保存并应用一下才正常
> > 
> > 
> > 我重新配置的，这个问题也存在
> 
> 多次测试 原因是 开启Netflix 分流服务器 导致
> 关闭Netflix 分流服务器 后重启正常

尝试了一下，的确关闭分流服务器后重启正常运行
