### ISSUE TITLE
能否开放IP名单到/etc/ssrplus目录下

### ISSUE THREAD

**Issue by naoki66** [fw876/helloworld#832]
默认域名的黑白名单都在/etc/ssrplus下，编译的时候就很方便加载自定义黑白名单，
但是黑白IP却在其他地方，实在不方便设置。

**Comment by 1715173329** [comment]
这个是保存在 ssrplus 配置里面的，编译的时候你可以直接把 /etc/config/shadowsocksr 塞进去。

**Comment by naoki66** [comment]
> 这个是保存在 ssrplus 配置里面的，编译的时候你可以直接把 /etc/config/shadowsocksr 塞进去。

我知道，但是这个目录包含太多配置了。config servers信息等等，并不是我们需要的。
