### ISSUE TITLE
今天编译5.10.108 内核的lede， v2ray-plugin报错了

### ISSUE THREAD

**Issue by kissyouhunter** [fw876/helloworld#836]
make[3]: Entering directory '/workdir/openwrt/feeds/helloworld/v2ray-plugin'
mkdir -p /workdir/openwrt/dl
SHELL= flock /workdir/openwrt/tmp/.v2ray-plugin-4.44.0.tar.gz.flock -c '  	/workdir/openwrt/scripts/download.pl "/workdir/openwrt/dl" "v2ray-plugin-4.44.0.tar.gz" "f94e8efe879a5300871dd01faec7d6635baaef4dbd39d83f4362802f716d386e" "" "https://codeload.github.com/teddysun/v2ray-plugin/tar.gz/v4.44.0?"    '
rm -f /workdir/openwrt/build_dir/target-x86_64_musl/v2ray-plugin-4.44.0/.built
touch /workdir/openwrt/build_dir/target-x86_64_musl/v2ray-plugin-4.44.0/.built_check
CONFIG_GOLANG_MOD_CACHE_WORLD_READABLE="" GO_BUILD_CACHE_DIR="/workdir/openwrt/tmp/go-build" GO_MOD_CACHE_DIR="/workdir/openwrt/dl/go-mod-cache" GO_MOD_ARGS="-modcacherw" GO_PKG="github.com/shadowsocks/v2ray-plugin" GO_INSTALL_EXTRA="" GO_INSTALL_ALL="" GO_SOURCE_ONLY="" GO_BUILD_PKG="github.com/shadowsocks/v2ray-plugin/..." GO_EXCLUDES="" GO_GO_GENERATE="" GO_INSTALL_BIN_PATH="/usr/bin" BUILD_DIR="/workdir/openwrt/build_dir/target-x86_64_musl/v2ray-plugin-4.44.0" GO_BUILD_DIR="/workdir/openwrt/build_dir/target-x86_64_musl/v2ray-plugin-4.44.0/.go_work/build" GO_BUILD_BIN_DIR="/workdir/openwrt/build_dir/target-x86_64_musl/v2ray-plugin-4.44.0/.go_work/build/bin" GO_BUILD_DEPENDS_PATH="/usr/share/gocode" GO_BUILD_DEPENDS_SRC="/workdir/openwrt/staging_dir/target-x86_64_musl/usr/share/gocode/src" GOOS="linux" GOARCH="amd64" GO386="" GOAMD64="v1" GOARM="" GOMIPS="" GOMIPS64="" GOPPC64="" CGO_ENABLED=1 CC="x86_64-openwrt-linux-musl-gcc" CXX="x86_64-openwrt-linux-musl-g++" CGO_CFLAGS="-Os -pipe -fno-caller-saves -fno-plt -fhonour-copts -Wno-error=unused-but-set-variable -Wno-error=unused-result -fmacro-prefix-map=/workdir/openwrt/build_dir/target-x86_64_musl/v2ray-plugin-4.44.0=v2ray-plugin-4.44.0 -Wformat -Werror=format-security -fstack-protector -D_FORTIFY_SOURCE=1 -Wl,-z,now -Wl,-z,relro" CGO_CPPFLAGS="-I/workdir/openwrt/staging_dir/toolchain-x86_64_gcc-8.4.0_musl/usr/include -I/workdir/openwrt/staging_dir/toolchain-x86_64_gcc-8.4.0_musl/include/fortify -I/workdir/openwrt/staging_dir/toolchain-x86_64_gcc-8.4.0_musl/include" CGO_CXXFLAGS="-Os -pipe -fno-caller-saves -fno-plt -fhonour-copts -Wno-error=unused-but-set-variable -Wno-error=unused-result -fmacro-prefix-map=/workdir/openwrt/build_dir/target-x86_64_musl/v2ray-plugin-4.44.0=v2ray-plugin-4.44.0 -Wformat -Werror=format-security -fstack-protector -D_FORTIFY_SOURCE=1 -Wl,-z,now -Wl,-z,relro" CGO_LDFLAGS="-L/workdir/openwrt/staging_dir/toolchain-x86_64_gcc-8.4.0_musl/usr/lib -L/workdir/openwrt/staging_dir/toolchain-x86_64_gcc-8.4.0_musl/lib -znow -zrelro" GOPATH="/workdir/openwrt/build_dir/target-x86_64_musl/v2ray-plugin-4.44.0/.go_work/build" GOCACHE="/workdir/openwrt/tmp/go-build" GOMODCACHE="/workdir/openwrt/dl/go-mod-cache" GOENV=off /usr/bin/env bash /workdir/openwrt/feeds/packages/lang/golang//golang-build.sh build -v -trimpath -ldflags "all=-buildid '1648642689' -linkmode external -extldflags '-L/workdir/openwrt/staging_dir/toolchain-x86_64_gcc-8.4.0_musl/usr/lib -L/workdir/openwrt/staging_dir/toolchain-x86_64_gcc-8.4.0_musl/lib -Wl,-z,now -Wl,-z,relro'"        -ldflags "-s -w -X main.VERSION=v4.44.0 -buildid '1648642689' -linkmode external -extldflags '-L/workdir/openwrt/staging_dir/toolchain-x86_64_gcc-8.4.0_musl/usr/lib -L/workdir/openwrt/staging_dir/toolchain-x86_64_gcc-8.4.0_musl/lib -Wl,-z,now -Wl,-z,relro'"  
Finding targets

Building targets
github.com/lucas-clemente/quic-go/internal/qtls
# github.com/lucas-clemente/quic-go/internal/qtls
../../../../../dl/go-mod-cache/github.com/lucas-clemente/quic-go@v0.23.0/internal/qtls/go118.go:5:13: cannot use "quic-go doesn't build on Go 1.18 yet." (untyped string constant) as int value in variable declaration

make[3]: *** [Makefile:71: /workdir/openwrt/build_dir/target-x86_64_musl/v2ray-plugin-4.44.0/.built] Error 2
make[3]: Leaving directory '/workdir/openwrt/feeds/helloworld/v2ray-plugin'
time: package/feeds/helloworld/v2ray-plugin/compile#0.98#0.44#0.96
    ERROR: package/feeds/helloworld/v2ray-plugin failed to build.
make[2]: *** [package/Makefile:116: package/feeds/helloworld/v2ray-plugin/compile] Error 1
make[2]: Leaving directory '/workdir/openwrt'
make[1]: *** [package/Makefile:110: /workdir/openwrt/staging_dir/target-x86_64_musl/stamp/.package_compile] Error 2
make[1]: Leaving directory '/workdir/openwrt'
make: *** [/workdir/openwrt/include/toplevel.mk:230: world] Error 2

**Comment by Beginner-Go** [comment]
别急 由于 `v2ray-plugin` 还未适配go1.18 已向上游反馈，等一个patch就好了

**Comment by kissyouhunter** [comment]
> 别急 由于 `v2ray-plugin` 还未适配go1.18 已向上游反馈，等一个patch就好了

了解

**Comment by BenjaminX** [comment]
如果不使用 V2Ray 和 Trojan 可以关掉

CONFIG_PACKAGE_luci-app-ssr-plus_INCLUDE_Trojan=n
CONFIG_PACKAGE_luci-app-ssr-plus_INCLUDE_V2ray_Plugin=n

**Comment by Beginner-Go** [comment]
已回退go1.17.8

**Comment by RuyeNet** [comment]
我在官方源码编译的时候也遇到这个问题了

**Comment by RuyeNet** [comment]
既然这个1.18不适配，那能不能给他换个版本来解决

**Comment by neabei** [comment]
这问题解决了吗？昨天编译还是这样。
