### ISSUE TITLE
近期版本存在重启路由器后 不能使用 原因是开启Netflix 分流服务器导致 

### ISSUE THREAD

**Issue by sk007** [fw876/helloworld#84]
经多次测试 
已经确定找出是
开启Netflix 分流服务器导致 
关闭后
重启路由器一切正常
希望有空 修复下！

**Comment by fw876** [comment]
不能重现

**Comment by sk007** [comment]
> 不能重现

ssr plus 配置好了Netflix 分流服务器 成功后
可以正常使用
然后重启路由器后
ssr plus 显示运行中
但是 不能正常访问 国外网站
需要保存配置一下才可以
解决方法
关闭 Netflix分流服务器 重启路由器 是可以正常使用的

**Comment by sk007** [comment]
> 不能重现

已经多次测试 
开关 Neflix 分流服务器
均可重现

**Comment by hplee0120** [comment]
试过好几遍，如果是保留配置升级的固件，这个问题基本可以说必现。如果是全新安装固件就没有问题。

**Comment by sk007** [comment]
> 不能重现

新版本还是存在 这个问题

都是 V2ray WS TLS 
只要开启Neflix 分流服务器 重启后就不能使用

必须启动项添加
sleep 20 && /etc/init.d/shadowsocksr restart
或者重启后手动保存应用一下 ssr plus 页面

**Comment by sk007** [comment]
已经重新刷机 配置
