### ISSUE TITLE
shadowsock-rust 已经添加aead 2022的初步支持，请问是否会跟进？

### ISSUE THREAD

**Issue by Gzxhwq** [fw876/helloworld#848]
https://github.com/shadowsocks/shadowsocks-rust/pull/811

**Comment by EnnawYang** [comment]
初步？那现在去跟进干嘛？

**Comment by YIDAWN** [comment]
这个也是我关心的问题。 强制失效AEAD认证导致连不上还没弃用该机制的机场服务器，怎么解决

**Comment by xiechangan123** [comment]
rust那一群人不用理会，ss理念就是简单快速不保证安全（天生缺陷），天天在那各种加解密隐私安全折腾来折腾去，违背初心。。。小鸡从始至终没部署过rust，要安全为啥不用v2ray或者xray呢，是吧

**Comment by Gzxhwq** [comment]
AEAD-2022就是由提升性能而后引出的新协议，顺道解决了SS一直以来的重放问题
https://github.com/shadowsocks/shadowsocks-org/issues/194
