### ISSUE TITLE
无法订阅Vless Xray节点

### ISSUE THREAD

**Issue by fourcanacsa** [fw876/helloworld#849]
设备为 R4S 4G版，固件为 骷髅头2022年4月4日正式版
内核为 5.4.187
Hello World插件版本为
luci-app-vssr | 1.23-20220108

无法订阅vless节点，使用URL导入节点可以应用，可以Ping，但是应用后无法科学上网。

![QQ截图20220411203509](https://user-images.githubusercontent.com/103617376/164300924-4ca08574-c95c-43cd-a43f-1cd4ffe28d53.jpg)

**Comment by 1715173329** [comment]
Should be fixed in eed48511cbc19a13cadcfb5dfeeb2783871e1447.
