### ISSUE TITLE
Openwrt  22.03.x

### ISSUE THREAD

**Issue by predators46** [fw876/helloworld#861]
@1715173329 

`root@OpenWrt:~# service shadowsocksr restart
/usr/bin/ssr-rules: line 60: iptables-save: not found
/usr/bin/ssr-rules: line 60: iptables-save: not found
/etc/rc.common: line 863: iptables: not found
/usr/bin/ssr-rules: line 60: iptables-save: not found
/usr/bin/ssr-rules: line 60: iptables-save: not found
/usr/bin/ssr-rules: line 154: iptables: not found
/usr/bin/ssr-rules: line 155: iptables: not found
/usr/bin/ssr-rules: line 156: iptables: not found
/usr/bin/ssr-rules: line 157: iptables: not found
/usr/bin/ssr-rules: line 158: iptables: not found
/usr/bin/ssr-rules: line 159: iptables: not found
/usr/bin/ssr-rules: line 160: iptables: not found
/usr/bin/ssr-rules: line 161: iptables: not found
/usr/bin/ssr-rules: line 162: iptables: not found
ssr-rules[5206]: Can't redirect, please check the iptables.
root@OpenWrt:~#`

**Comment by 1715173329** [comment]
install iptables-nft

**Comment by predators46** [comment]
> install iptables-nft

Thanks fix
