### ISSUE TITLE
解析不到tls host参数

### ISSUE THREAD

**Issue by binge8** [fw876/helloworld#869]
v2ray机场，之前他们没有tls host参数，一直正常使用，前两天机场加了tls host参数，之后更新订阅就获取不到这个tls host参数了，导致fq失败，望修复

**Comment by 1715173329** [comment]
你发机场还带 aff 是吧

**Comment by binge8** [comment]
> 你发机场还带 aff 是吧

小意思，删了

**Comment by binge8** [comment]
老板们，能帮忙给解决下吗？如果需要联系机场要什么参数，随时留言配合
