### ISSUE TITLE
奇怪的问题，同一个网络下，电脑能访问某些网站，但手机和安卓电视不行

### ISSUE THREAD

**Issue by hisune** [fw876/helloworld#871]
一个很奇怪的问题

例如：v2ex.com，电脑可以访问，但手机访问浏览器提示：`net::ERR_CONNECTION_RESET`

另外安卓APP：SmartTube Next打开也无法加载内容

但用passwall2可以，使用安卓手机v2rayNG客户端也能正常访问。

只有openwrt下的ssr在手机和其他安卓机器下不行

![image](https://user-images.githubusercontent.com/7941669/168627831-68ae1a1d-34d5-46e1-846a-d8f905767fab.png)

xray客户端服务端版本都是：Xray 1.5.5 

openwrt固件为lean最新版本固件：OpenWrt R22.5.5

**Comment by foxhoundhcm** [comment]
你应该是没有禁用IPv6 DNS解析，手机优先走了IPv6，所以不通。可在dnsmasq.conf加上address=/v2ex.com/::

**Comment by hisune** [comment]
> 你应该是没有禁用IPv6 DNS解析，手机优先走了IPv6，所以不通。可在dnsmasq.conf加上address=/v2ex.com/::

感谢，关闭ipv6解析后貌似真的正常了

**Comment by RItziiiiii** [comment]
十分感谢，我也有由此疑惑，不过都那种网站你懂得，也没好意思到处问，这两天各种换着问谷歌，总算找到你的这份帖子了，试了一下，v2rayNG客户端，而不是使用clash，就能进行正常访问了。
哈哈哈哈哈我明天尝试一下关闭手机的ipv6？

**Comment by bulidoge** [comment]
看这个.....我解决了 如果是华为的话很可能是这样 被后台自动清理了https://blog.csdn.net/sxf1061700625/article/details/127476100

**Comment by RItziiiiii** [comment]
你好，非常感谢你的回复，我现在才看到。
事情的最后，就是我换了一个梯子就解决了，那个网站因为是H网站，我也没太深究。
后面换了手机以后发现梯子也不用换了，原来的clash就能用。原来是小米11pro手机，系统是miui。

bulidoge ***@***.***> 于 2024年7月13日周六 01:32写道：
