### ISSUE TITLE
GFW模式下，如何精细控制二、三级域名的分流？

### ISSUE THREAD

**Issue by terrellgf** [fw876/helloworld#878]
(1) 具体问题
A：比如我想让https://test.com/ 走代理，https://tracker.test.com/ 不走，在GFW列表模式下应该怎么配置？
如果强制走代理的域名中，直接配置test.com，则实际测试test.com和tracker.test.com都走代理。
如果强制走代理的域名中，配置test.com。然后不走代理的域名中，配置tracker.test.com。则这两个实际测试都不会走代理。
尝试用正则解决，比如在强制走代理的域名中，配置 ^test.com, 但貌似也不起作用。

IP模式确实可以通过把强制tracker.test.com不走代理来实现分流，奈何我有PT任务（P2P）要跑，IP模式使得我很多没必要出海的流量走了我的桥头堡，导致我桥头堡流量巨大（基本都是PT的P2P上传流量），都是按照流量收费，成本上受不了，这部分流量也没必要出海，但对方IP是不是海外IP我也没办法控制。所以基于这种环境，我没办法使用IP模式。
(2) 路由器型号和固件版本
A：软路由; OpenWrt R20.2.15 / LuCI Master (git-20.047.54228-e6b2608); luci-app-ssr-plus 3-142;

**Comment by terrellgf** [comment]
> (1) 具体问题 A：比如我想让https://test.com/ 走代理，https://abc.test.com/ 不走，在GFW列表模式下应该怎么配置？ 如果强制走代理的域名中，直接配置test.com，则实际测试test.com和abc.test.com都走代理。 如果强制走代理的域名中，配置test.com。然后不走代理的域名中，配置abc.test.com。则这两个实际测试都不会走代理。 尝试用正则解决，比如在强制走代理的域名中，配置 ^test.com, 但貌似也不起作用。
> 
> IP模式确实可以通过把强制abc.test.com不走代理来实现分流，奈何我有PT的P2P任务要跑，IP模式使得我很多没必要出海的流量走了我的桥头堡，导致我桥头堡流量巨大（基本都是PT的P2P上传流量），都是按照流量收费，成本上受不了。所以基于这种环境，我没办法使用IP模式。 (2) 路由器型号和固件版本 A：软路由; OpenWrt R20.2.15 / LuCI Master (git-20.047.54228-e6b2608); luci-app-ssr-plus 3-142;

**Comment by 1715173329** [comment]
建议使用 v2rayA.org
