### ISSUE TITLE
SSR-Plus如何更新v2ray到最新版本

### ISSUE THREAD

**Issue by smallprogram** [fw876/helloworld#88]
需要更新v2ray版本到4.25.0。

**Comment by Nicepaul** [comment]
需要更新v2ray版本到4.25.0。

**Comment by Mattraks** [comment]
这里跟v2ray版本没关系你发错地方了，关闭吧

**Comment by smallprogram** [comment]
> 这里跟v2ray版本没关系你发错地方了，关闭吧

嗯，其实我的意思是SSR-Plus如何更新v2ray到最新版本。

**Comment by WXfeng-boy** [comment]
> > 这里跟v2ray版本没关系你发错地方了，关闭吧
> 
> 嗯，其实我的意思是SSR-Plus如何更新v2ray到最新版

> > 这里跟v2ray版本没关系你发错地方了，关闭吧
> 
> 嗯，其实我的意思是SSR-Plus如何更新v2ray到最新版本。

如果固件里有passwall了，直接在那里更新就行

**Comment by smallprogram** [comment]
> 如果固件里有passwall了，直接在那里更新就行

固件中没有包含passwall。

**Comment by leishao1993** [comment]
那你就单独更新v2ray或者直接更新固件

**Comment by smallprogram** [comment]
其实如果ssr plus能投提供更新V2Ray功能就太好了

**Comment by smallprogram** [comment]
coolsnowwolf/lede/pulls#4844

**Comment by Rangtian** [comment]
难受，刷的Flippy版Openwrt，目前也在愁ssr-plus的v2ray的更新问题。4.25.1已经发布，总不能每次有更新都手动编译。

**Comment by smallprogram** [comment]
> 难受，刷的Flippy版Openwrt，目前也在愁ssr-plus的v2ray的更新问题。4.25.1已经发布，总不能每次有更新都手动编译。

要不就直接ssh进路由。手工替换新版v2ray程序。

**Comment by Rangtian** [comment]
@smallprogram 你好，我有几个小白问题想请教

1. 这编译出来的 v2ray 是与 ssr plus+ 插件耦合了么？与 VPN 里的 v2ray 无关吧？
2. 有没有办法能让 ssr plus+ 像 passwall 那样跟 v2ray 解耦，直接点“升级”按钮来更新 v2ray？

谢谢你！！！
