### ISSUE TITLE
luci-app-ssr-plus/Makefile新增加的依赖luci-lib-ipkg导致编译出错了

### ISSUE THREAD

**Issue by Michaol** [fw876/helloworld#891]
Collected errors:
 * pkg_hash_check_unresolved: cannot find dependency luci-lib-ipkg for luci-app-ssr-plus
 * pkg_hash_fetch_best_installation_candidate: Packages for luci-app-ssr-plus found, but incompatible with the architectures configured
 * opkg_install_cmd: Cannot install package luci-app-ssr-plus.
 * satisfy_dependencies_for: Cannot satisfy the following dependencies for luci-i18n-ssr-plus-zh-cn:
 * 	luci-lib-ipkg
 * opkg_install_cmd: Cannot install package luci-i18n-ssr-plus-zh-cn.
 * check_conflicts_for: The following packages conflict with sagernet-core:
 * check_conflicts_for: 	xray-core * 
 * opkg_install_cmd: Cannot install package sagernet-core.
make[2]: *** [package/Makefile:70: package/install] Error 255
make[2]: Leaving directory '/home/michaol/lede'
make[1]: *** [package/Makefile:111: /home/michaol/lede/staging_dir/target-x86_64_musl/stamp/.package_install] Error 2
make[1]: Leaving directory '/home/michaol/lede'
make: *** [/home/michaol/lede/include/toplevel.mk:230: world] Error 2
michaol@e38585308b46:~/lede$ make menuconfig
WARNING: Makefile 'package/feeds/helloworld/luci-app-ssr-plus/Makefile' has a dependency on 'luci-lib-ipkg', which does not exist

看了一下历史，昨天还没有加入时一切正常，老大凌晨修改后，今天编译就出错了。

**Comment by Michaol** [comment]
云编译同样错误
 * pkg_hash_check_unresolved: cannot find dependency luci-lib-ipkg for luci-app-ssr-plus
 * pkg_hash_fetch_best_installation_candidate: Packages for luci-app-ssr-plus found, but incompatible with the architectures configured
 * opkg_install_cmd: Cannot install package luci-app-ssr-plus.
 * satisfy_dependencies_for: Cannot satisfy the following dependencies for luci-i18n-ssr-plus-zh-cn:
 * 	luci-lib-ipkg
 * opkg_install_cmd: Cannot install package luci-i18n-ssr-plus-zh-cn.
 * check_conflicts_for: The following packages conflict with sagernet-core:
 * check_conflicts_for: 	xray-core * 
 * opkg_install_cmd: Cannot install package sagernet-core.
make[2]: *** [package/Makefile:70: package/install] Error 255

**Comment by hcym** [comment]
这是前面，把依赖去掉就是了，后面和xray也有冲突，最后我是把那个新的什么sage core去掉才行，用倒是能用。昨天的完美，尤其是dns2什么的非常灵光

**Comment by Michaol** [comment]
> 这是前面，把依赖去掉就是了，后面和xray也有冲突，最后我是把那个新的什么sage core去掉才行，用倒是能用。昨天的完美，尤其是dns2什么的非常灵光

管是去掉依赖不行，要直接回退到加入sagernet-core之前，否则还是出错。

**Comment by lovehackintosh** [comment]
> > 这是前面，把依赖去掉就是了，后面和xray也有冲突，最后我是把那个新的什么sage core去掉才行，用倒是能用。昨天的完美，尤其是dns2什么的非常灵光
> 
> 管是去掉依赖不行，要直接回退到加入sagernet-core之前，否则还是出错。

请问该怎么做

**Comment by Michaol** [comment]
呃，看了一下L大维护的LUCI，其实原因是L大把LUCI里面的luci-lib-ipkg去掉了。

**Comment by ayancn** [comment]
同样问题怎么解决

**Comment by Jejz168** [comment]
不要这插件就好了

**Comment by WYC-2020** [comment]
> 呃，看了一下L大维护的LUCI，其实原因是L大把LUCI里面的luci-lib-ipkg去掉了。

这不是去掉，而是l大从来就没分离过，这个模块是别人从luci-base 分离出来的，你们直接删除依赖或者改成luci-base就行了

**Comment by Jejz168** [comment]
> > 呃，看了一下L大维护的LUCI，其实原因是L大把LUCI里面的luci-lib-ipkg去掉了。
> 
> 这不是去掉，而是l大从来就没分离过，这个模块是别人从luci-base 分离出来的，你们直接删除依赖或者改成luci-base就行了

sed -i 's/luci-lib-ipkg/luci-base/g'  麻烦

**Comment by Michaol** [comment]
> > 呃，看了一下L大维护的LUCI，其实原因是L大把LUCI里面的luci-lib-ipkg去掉了。
> 
> 这不是去掉，而是l大从来就没分离过，这个模块是别人从luci-base 分离出来的，你们直接删除依赖或者改成luci-base就行了

删除依赖和改luci-base我都试过，依然出错。SSRP我只加了xray-core一个，没加其他。莫非v2ray-core可以，xray-core不行？

**Comment by 1715173329** [comment]
1. `luci-lib-ipkg` 在新的 js luci 中已经不再默认包含，故必须写入依赖。
2. 新引入的 sagernet-core 与 v2ray xray core 都冲突。如果之前勾选过 *ray，请先反选。
3. sagernet-core 必须使用 Go 1.18+ 进行编译。

**Comment by Jan20th9e** [comment]
> * `luci-lib-ipkg` 在新的 js luci 中已经不再默认包含，故必须写入依赖。我稍后会做一个 workaround。
> * 新引入的 sagernet-core 与 v2ray xray core 都冲突。如果之前勾选过 *ray，请先反选。
> * sagernet-core 必须使用 Go 1.18+ 进行编译。

新版已经默认采用dns2tcp进行解析，在不勾选PDNSD的时候插件里还保留有那个清空PDNSD缓存，是忘了删吗

**Comment by WYC-2020** [comment]
> > > * `luci-lib-ipkg` 在新的 js luci 中已经不再默认包含，故必须写入依赖。我稍后会做一个 workaround。
> > > * 新引入的 sagernet-core 与 v2ray xray core 都冲突。如果之前勾选过 *ray，请先反选。
> > > * sagernet-core 必须使用 Go 1.18+ 进行编译。
> > 
> > 
> > 新版已经默认采用dns2tcp进行解析，在不勾选PDNSD的时候插件里还保留有那个清空PDNSD缓存，是忘了删吗
> 
> 选PDNSD反而没有清空缓存这个按钮,选DNS2TCP反而有这个选项

![image](https://user-images.githubusercontent.com/34025388/172354149-9988fe0f-1867-4fe2-9e90-69a6be09b953.png)
其实不用完全移除pdnsd，完全可以备用，状态不对改这里，passwall也是一刀切除了pdnsd，也是可以兼容保留的
