### ISSUE TITLE
加强版内核版本编译通不过

### ISSUE THREAD

**Issue by gswangmd-gssi** [fw876/helloworld#898]
Configuring xray-core.
Collected errors:
 * check_conflicts_for: The following packages conflict with sagernet-core:
 * check_conflicts_for: 	v2ray-core * check_conflicts_for: 	xray-core * 
 * opkg_install_cmd: Cannot install package luci-app-ssr-plus.
 * check_conflicts_for: The following packages conflict with sagernet-core:
 * check_conflicts_for: 	v2ray-core * check_conflicts_for: 	xray-core * 
 * opkg_install_cmd: Cannot install package sagernet-core.
make[2]: *** [package/Makefile:70: package/install] Error 255
make[2]: Leaving directory '/home/gswangmd/lede'
make[1]: *** [package/Makefile:111: /home/gswangmd/lede/staging_dir/target-aarch64_generic_musl/stamp/.package_install] Error 2
make[1]: Leaving directory '/home/gswangmd/lede'
make: *** [/home/gswangmd/lede/include/toplevel.mk:230: world] Error 2
gswangmd@WMD-HOME:~/lede$

**Comment by hcym** [comment]
除了sage，其它的v，x的都要取消，我用官方master也编译过了，就是wireguard不能用，其他正常，也没感觉什么加强，🤣

**Comment by 1715173329** [comment]
取消勾选 xray-core。
