### ISSUE TITLE
新添加的Hysteria协议无法启动

### ISSUE THREAD

**Issue by xcf13363175** [fw876/helloworld#899]
新添加的Hysteria协议无法启动，协议wechat，端口123XX，passwall和v2rayN可以连接。
2022-06-08 17:22:51: -----------end------------
2022-06-08 17:22:50: Main node:hysteria 1.0.4 Started!
2022-06-08 17:22:50: ----------start------------

日志显示启动，但是实际未运行，无法连接节点。ps. 甚至在服务器节点中都ping不同服务器。

**Comment by hcym** [comment]
我的能用，就是不能用ipv6，pass那边就能用ipv6

**Comment by 1715173329** [comment]
用户配置问题，开启允许不安全连接后解决。

**Comment by xcf13363175** [comment]
谢谢天灵巨佬

**Comment by hunter8605** [comment]
> 用户配置问题，开启允许不安全连接后解决。

我遇到同样的问题了，开启这个允许不安全连接还是不行
