### ISSUE TITLE
[help]开启去广告怎么查看日志

### ISSUE THREAD

**Issue by cecial** [fw876/helloworld#9]
你好，在ssrp里面开启了去广告，用的是anti-AD, 发现电视盒子里面的腾讯视频TV版看不了视频，关闭就可以了。想问一下怎么查看哪个域名被阻挡了？

**Comment by norikohxb** [comment]
装一个adguardhome，然后把电视盒子的dns设置为adguardhome的设备，那么就忠实纪录所有域名纪录了

**Comment by norikohxb** [comment]
在lean-lede的dhcp/dns的设置里面其实也有一个 纪录查询日志，但是不知道为何打钩了以后还是没用，查询日志没有纪录。

**Comment by cecial** [comment]
> 在lean-lede的dhcp/dns的设置里面其实也有一个 纪录查询日志，但是不知道为何打钩了以后还是没用，查询日志没有纪录。

这个不清楚，我安装adg看看吧
