### ISSUE TITLE
 sagernet-core 无法与xray-core 共存？

### ISSUE THREAD

**Issue by xiangfeidexiaohuo** [fw876/helloworld#902]
* check_conflicts_for: The following packages conflict with sagernet-core:
 * check_conflicts_for: 	xray-core * 
 * opkg_install_cmd: Cannot install package luci-app-ssr-plus.
 * check_conflicts_for: The following packages conflict with sagernet-core:
 * check_conflicts_for: 	xray-core * 
 * opkg_install_cmd: Cannot install package sagernet-core.

也就是说，固件内置ssrp编译进去，如果还要内置其他带xray的插件，就无法共存？

**Comment by wekingchen** [comment]
我也遇到同样的问题，ssrp本身没有带xray-core了，但其他插件有用到，就编译不过

**Comment by ShoukakuChuuCC** [comment]
是的，暂时不能和xray-core共存

**Comment by 1715173329** [comment]
不能。

**Comment by gswangmd-gssi** [comment]
不能共存，只好放弃SSR了。
