### ISSUE TITLE
6月9日的更新后 UDP无法正常代理

### ISSUE THREAD

**Issue by ShoukakuChuuCC** [fw876/helloworld#904]
节点类型shadowsocks，加密协议ss2022 edition
6月8日最后一个commit则正常

**Comment by ShoukakuChuuCC** [comment]
![image](https://user-images.githubusercontent.com/38343280/172961041-88a19970-5068-417d-98fb-92b0858f03db.png)
![image](https://user-images.githubusercontent.com/38343280/172961058-9d343a1b-24e2-419c-aea5-eb91387e1672.png)

**Comment by ShoukakuChuuCC** [comment]
服务端Xray v1.5.7
SSRP-高级设置-数据包编码-xudp

**Comment by 1715173329** [comment]
https://github.com/SagerNet/v2ray-core/suites/6860170564/artifacts/265087919
试试此版本的 v2ray 核心。

**Comment by ShoukakuChuuCC** [comment]
是把服务端核心换成SagerNet？SSRP的数据包编码需不需要也改成v2ray的

**Comment by ShoukakuChuuCC** [comment]
服务端核心换成SagerNet的v2ray-core v5.0.14后，直接连不上代理了，v2ray日志提示cipher: message authentication failed，双端密码都是正确对应的，服务端换成xray后就正常了，v2ray和xray用的config都是一样的配置

**Comment by 1715173329** [comment]
> 是把服务端核心换成SagerNet？SSRP的数据包编码需不需要也改成v2ray的

是需要更新一下客户端，ss 不使用此数据包编码。
SagerNet 的 v2ray-core 请直接下载 Actions 编译文件，不要用 Release 版本，通常不是最新。

**Comment by kennyleo** [comment]
同样的问题，SagerNet后udp就不通

**Comment by 1715173329** [comment]
udp 问题正在与上游作者沟通，如有 udp 需求可以先取消 ssrp 的 sn 依赖并手动选择 xray。

**Comment by tmptr** [comment]
> udp 问题正在与上游作者沟通，如有 udp 需求可以先取消 ssrp 的 sn 依赖并手动选择 xray。

Also could you please chat with upstreamer about the full-cone nat issue that connect to xray server? Thank you.

**Comment by foxjie** [comment]
是的，我这里也发现用SagerNet核心以后，xray节点无法full-cone了，请问现在应该怎样获取到full-core？使用非vless节点么？

**Comment by minlang112** [comment]
嗯，换SagerNet之后系统日志就会大量报这种东西↓

Wed Jun 22 00:24:48 2022 kern.notice kernel: [215484.767642]  IN= OUT= SRC=100.90.33.139 DST=119.xxx.xxx.xxx LEN=132 TOS=0x00 PREC=0x20 TTL=63 ID=13082 PROTO=UDP SPT=32729 DPT=161 LEN=112
Wed Jun 22 00:25:19 2022 kern.notice kernel: [215515.419797] nf_ct_snmp: dropping packet: parser failed
Wed Jun 22 00:25:19 2022 kern.notice kernel: [215515.419797]  IN= OUT= SRC=100.90.33.139 DST=119.xxx.xxx.xxx LEN=48 TOS=0x00 PREC=0x20 TTL=63 ID=16514 PROTO=UDP SPT=32729 DPT=161 LEN=28
Wed Jun 22 00:31:59 2022 kern.notice kernel: [215916.066174] nf_ct_snmp: dropping packet: parser failed
Wed Jun 22 00:31:59 2022 kern.notice kernel: [215916.066174]  IN= OUT= SRC=100.90.33.139 DST=119.xxx.xxx.xxx LEN=132 TOS=0x00 PREC=0x20 TTL=63 ID=1560 PROTO=UDP SPT=32729 DPT=161 LEN=112
Wed Jun 22 00:38:40 2022 kern.notice kernel: [216317.101160] nf_ct_snmp: dropping packet: parser failed
Wed Jun 22 00:38:40 2022 kern.notice kernel: [216317.101160]  IN= OUT= SRC=100.90.33.139 DST=119.xxx.xxx.xxx LEN=132 TOS=0x00 PREC=0x20 TTL=63 ID=53979 PROTO=UDP SPT=32729 DPT=161 LEN=112
Wed Jun 22 00:38:58 2022 kern.notice kernel: [216334.516450] nf_ct_snmp: dropping packet: parser failed
Wed Jun 22 00:38:58 2022 kern.notice kernel: [216334.516450]  IN= OUT= SRC=100.90.33.139 DST=119.xxx.xxx.xxx LEN=132 TOS=0x00 PREC=0x20 TTL=63 ID=56404 PROTO=UDP SPT=32729 DPT=161 LEN=112

**Comment by predators46** [comment]
you are using shadowsocks looks like shadowsocks doesn't support udp this is a problem in shadowsocks

**Comment by dongfangy2011** [comment]
我个人试验很多次DNS解析方式
只能选“使用dns2scoks“方可使用，如选择“dns2tcp”时日志显示如下：
022-07-07 15:39:04: 找不到 dns2tcp，无法启动...
2022-07-07 15:37:10: Main node:Welcome to trojan 1.16.0 , 4 Threads Started!
2022-07-07 15:37:10: Global_Socks5:Welcome to trojan 1.16.0 Started!
2022-07-07 15:37:10: UDP TPROXY Relay:Welcome to trojan 1.16.0 Started!
2022-07-07 15:37:10: ----------start------------
2022-07-07 15:37:06: -----------end------------
