### ISSUE TITLE
必须解决和其它代理的冲突问题！

### ISSUE THREAD

**Issue by gswangmd-gssi** [fw876/helloworld#906]

**Comment by Michaol** [comment]
你这口气真让人看的不舒服！什么叫必须？凭什么用这种命令式语气？你可以建议，可以提出需求，但是没有什么必须不必须！

**Comment by EnnawYang** [comment]
多开几个代理叠buff？

**Comment by minlang112** [comment]
我站在风中，不知道你是牛是马

**Comment by Aes64X** [comment]
> _No description provided._

建议联系商务，您先报个价，交钱您是大爷，没有？那您是屁。

**Comment by Aes64X** [comment]
> _No description provided._

什么？连商务都没有联系吗？。。。。。不好意思，那您连屁都不是。

**Comment by jh0072110** [comment]
没想到在gayhub上也是什么人都能见到啊啧啧啧

**Comment by kisaragychihaya** [comment]
您就是这个项目的产品经理吗

**Comment by oluceps** [comment]
呃呃

**Comment by MikuMaxZ** [comment]
又不是你做的这口气
