### ISSUE TITLE
编译一直出错，都是sagecore报错

### ISSUE THREAD

**Issue by longercui** [fw876/helloworld#907]
Building targets
../../../../../dl/go-mod-cache/github.com/sagernet/sing@v0.0.0-20220606113732-5efacc1c7db5/common/metadata/addr.go:5:2: package net/netip is not in GOROOT (/home/eloncui/openwrt/staging_dir/hostpkg/lib/go-cross/src/net/netip)

make[3]: *** [Makefile:88: /home/eloncui/openwrt/build_dir/target-mipsel_24kc_musl/sagernet-core-5.0.14-2022-06-07-5590c5fe/.built] Error 1
make[3]: Leaving directory '/home/eloncui/openwrt/package/helloworld/sagernet-core'
time: package/helloworld/sagernet-core/compile#14.05#2.19#17.41
    ERROR: package/helloworld/sagernet-core failed to build.
make[2]: *** [package/Makefile:116: package/helloworld/sagernet-core/compile] Error 1
make[2]: Leaving directory '/home/eloncui/openwrt'
make[1]: *** [package/Makefile:110: /home/eloncui/openwrt/staging_dir/target-mipsel_24kc_musl/stamp/.package_compile] Error 2
make[1]: Leaving directory '/home/eloncui/openwrt'
make: *** [/home/eloncui/openwrt/include/toplevel.mk:230: world] Error 2

**Comment by 1715173329** [comment]
需要 golang 1.18 及以上版本。
