### ISSUE TITLE
6月11日，编译红米rm2100 固件的menuconfig中，在ssrp中没有v2ray/xray的选项，编译后的固件在s

### ISSUE THREAD

**Issue by sdc9088** [fw876/helloworld#909]
6月11日，编译红米rm2100 固件的menuconfig中，在ssrp中没有v2ray/xray的选项，编译后的固件在ssrp中添加节点也没有v2ray/xray的服务器节点类型的选择。请帮忙查一下。谢谢

**Comment by EnnawYang** [comment]
https://github.com/fw876/helloworld/commit/d7c88a9a34080baef6711a7c94d081caf51846e7
