### ISSUE TITLE
怎么跟进v2ray的版本？？

### ISSUE THREAD

**Issue by maryjeck** [fw876/helloworld#91]
如题，v2ray最近更新比较勤，这个有点慢哦

自己怎么跟进，学习一下

**Comment by smallprogram** [comment]
> 如题，v2ray最近更新比较勤，这个有点慢哦
> 
> 自己怎么跟进，学习一下

昨晚已经更新到4.25.0了。去编译把骚年

**Comment by qqsir-dev** [comment]
编译完了V2Ray好像用不了了，SSR没问题

**Comment by hcym** [comment]
哪有什么乱七八糟的事，不论list模式还是路由模式，v2ray和trojan一直正常，就是用haproxy均衡的话只能用list列表，不能用路由表，但是官方的可以。还是单口路由器

**Comment by smallprogram** [comment]
> 编译完了V2Ray好像用不了了，SSR没问题

删掉源码，重新clone源码重新单核编译

**Comment by smallprogram** [comment]
源码已更新到4.25.1 ，git pull 重新编译把

**Comment by hcym** [comment]
好像是arm稳定性有改进，涮了n1没什么感觉，x86编译过了就放着吧
