### ISSUE TITLE
6月11日编译SSRP的问题

### ISSUE THREAD

**Issue by sdc9088** [fw876/helloworld#910]
我在6月11日编译红米rm2100是在ssrp的选项里面没有V2ray/Xray的选项，编译出来的固件在添加服务器类型时也没有V2ray/XRay的选择，请帮忙指导一下！

**Comment by Bruce-prs** [comment]
https://github.com/fw876/helloworld/commit/d7c88a9a34080baef6711a7c94d081caf51846e7
