### ISSUE TITLE
请问新的v2ray核心运行不了vmess节点了吗？

### ISSUE THREAD

**Issue by Benjamin23333** [fw876/helloworld#911]
我的设备是r2s，12号之前一直用的https://github.com/haiibo/OpenWrt 这里的6月6号编译的固件，可以正常用vmess节点。之后到13号这个项目里的固件一直是编译失败的。
今天（13号）刷了当天编译成功的固件，发现里面的ssrp用不了vmess节点，Trojan节点可以用。
我发现6月6号的固件运行vmess节点，使用的xray的1.5.7的核心，今天的是用的V2Ray 5.0.15（sagernet-core），运行Trojan都是使用的Trojan-go，是新的v2ray核心的问题吗？

**Comment by Benjamin23333** [comment]
我试了一些方法，把sagernet-core的action里面最新的核心解压拖到/usr/bin/里面覆盖，赋予权限，不行
把v2ray原作者的核心拖进去，赋予权限，可以日志显示运行了原版v2ray
或者把xray重命名v2ay放进去也可以，日志显示运行了xray

**Comment by 1715173329** [comment]
请联系固件作者。

**Comment by Benjamin23333** [comment]
> 请联系固件作者。

我用404大佬固件的https://github.com/QiuSimons/YAOF 也会遇到一样的问题，应该不是[haiibo](https://github.com/haiibo/OpenWrt)这个的个例，是我用的机场节点的问题吗？
![image](https://user-images.githubusercontent.com/54323063/173334937-1d596aea-7a43-4b11-9d7f-2648a8aa49d9.png)
