### ISSUE TITLE
编新新版的SSR出现问题

### ISSUE THREAD

**Issue by dengchan0416** [fw876/helloworld#912]
![1](https://user-images.githubusercontent.com/41529838/173321702-85ab0ccd-d27e-497f-8c37-33216ba60684.png)

![2](https://user-images.githubusercontent.com/41529838/173322096-28c2156c-2900-48de-a59c-4566d9bd0ed7.png)

编译错误，请问怎样解决

**Comment by 1715173329** [comment]
取消勾选 xray-core
