### ISSUE TITLE
编译出错

### ISSUE THREAD

**Issue by longercui** [fw876/helloworld#915]
Building targets
../../../../../dl/go-mod-cache/github.com/sagernet/sing@v0.0.0-20220610074707-a30d5506be41/common/metadata/addr.go:5:2: package net/netip is not in GOROOT (/home/eloncui/openwrt/staging_dir/hostpkg/lib/go-cross/src/net/netip)

golang is already the newest version (2:1.18~0ubuntu2).

go env -w GO111MODULE=off

请问大佬们怎么解决，谢谢！

**Comment by MichaelWang666** [comment]
same issue by remove  the sagernet package

**Comment by 1715173329** [comment]
更新 openwrt golang toolchain
https://github.com/openwrt/packages/tree/master/lang/golang
