### ISSUE TITLE
sagernet-core，shadowsocks无法运行

### ISSUE THREAD

**Issue by Hallsong** [fw876/helloworld#919]
6月15日最新commit，重刷固件选择不保留配置升级，使用SS协议。
ssrp主界面显示ShadowsocksR Plus+ 未运行，换用其他协议能正常运行。

**Comment by hcym** [comment]
x内核也是如此，估计是配置写错了，只能用ss原版凑活，pass不受影响

**Comment by Hallsong** [comment]
https://github.com/fw876/helloworld/issues/918

这里是天大提供的方案，但是我看不懂。

**Comment by hcym** [comment]
不急，等他们修吧，我原来是指望wireguard的，现在鸡飞狗跳的也没人管了，大雕这个放一放。用pass，其实最好用的还是一年前的，哈哈😄

**Comment by 1715173329** [comment]
配置呢，就一句话无法启动，建议在隔壁请算命大师。
