### ISSUE TITLE
ssrp+选择的xray-core或者v2ray-core发现问题如下

### ISSUE THREAD

**Issue by ohbaby30** [fw876/helloworld#920]
1.uuid V5问题

2.xray-vless v2ray-vmass能运行但是无法上外网，如图
<img width="901" alt="image" src="https://user-images.githubusercontent.com/62003514/173998010-dcbcb32e-a1fd-41a9-9f9f-1403e479f56a.png">
<img width="1524" alt="image" src="https://user-images.githubusercontent.com/62003514/173998037-ab64544a-44a7-4d17-92e2-d27278fb3fb8.png">
<img width="953" alt="image" src="https://user-images.githubusercontent.com/62003514/173998059-b3d4187f-88c6-481b-a0ac-ffec4c3b73ca.png">
<img width="811" alt="image" src="https://user-images.githubusercontent.com/62003514/173998080-2324833d-aead-4318-893f-47c05041df0e.png">
<img width="905" alt="image" src="https://user-images.githubusercontent.com/62003514/173998092-75b83a2b-2aaf-4734-9aa9-e04be87a1e86.png">

其他协议正常（trojan-plus，hy，ss-rust）

更新一下，系统日志里大量的Thu Jun 16 14:58:06 2022 daemon.err uhttpd[2060]: Failed to send request: Operation not permitted
Thu Jun 16 14:58:06 2022 daemon.err uhttpd[2060]: Failed to send request: Operation not permitted
Thu Jun 16 14:58:19 2022 daemon.err uhttpd[2060]: Failed to send request: Operation not permitted
Thu Jun 16 14:58:20 2022 daemon.err uhttpd[2060]: Failed to send request: Operation not permitted
Thu Jun 16 14:59:11 2022 daemon.err uhttpd[2060]: Failed to send request: Operation not permitted
Thu Jun 16 14:59:11 2022 daemon.err uhttpd[2060]: Failed to send request: Operation not permitted

并无单独编译uhttpd啊，默认编译外加一个ssrplus

谢谢~

**Comment by saoba1982** [comment]
和楼主 一样的问题，有解决办法么？
