### ISSUE TITLE
无法更新订阅服务器节点（已尝试找到临时解决办法，求解惑）

### ISSUE THREAD

**Issue by minlang112** [fw876/helloworld#921]
## 1.关于你要提交的问题

Q：是否搜索了issue (使用 "x" 选择)
* [ x] 没有类似的issue

## 2. 详细叙述
近日更新后，无法正常更新所有订阅服务器节点
### (1) 具体问题

本人使用的是某商业机场，更新订阅地址的URL是一个HTTPS地址。近日更新后，无法正常更新所有订阅服务器节点。但是使用这个URL在浏览器内可以正常获取到订阅结果，BASE64解码后可以获得正确的VMESS链接。
根据代码，该功能是由此函数实现的
 local stdout = luci.sys.exec('uclient-fetch -q --user-agent="Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/44.0.2403.157 Safari/537.36" --no-check-certificate -O- "' .. url .. '"')
uclient-fetch约等于wget，于是做了以下测试：
①在ttyd里使用uclient-fetch -q --user-agent="Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/44.0.2403.157 Safari/537.36" --no-check-certificate -O- "'https://马赛克/osubscribe.php?sid=xxxxx&token=xxxxxx '"
返回结果是Failed to allocate uclient context
感觉好像是https的问题
②在ttyd里使用wget-ssl -q --user-agent="Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/44.0.2403.157 Safari/537.36" --no-check-certificate -O- "'https://马赛克/osubscribe.php?sid=xxxxx&token=xxxxxx '"
则不会返回任何报错

于是直接修改subscribe.lua，把uclient-fetch改成wget-ssl，在尝试更新订阅节点，发现可以更新了

### (2) 路由器型号和固件版本

A：X86-64，OpenWrt R22.6.16 / LuCI branch (git-22.155.59899-bc97b88)，lean的库
B：SSRP插件为6月17日编译版本

### (3) 详细日志

2022-06-18 01:01:40 更新失败，没有可用的节点信息
2022-06-18 01:01:40 https://马赛克/osubscribe.php?sid=xxxxx&token=xxxxxx: 获取内容为空
2022-06-18 00:39:34 更新失败，没有可用的节点信息
2022-06-18 00:39:34 https://马赛克/osubscribe.php?sid=xxxxx&token=xxxxxxx: 获取内容为空

**Comment by minlang112** [comment]
uclient-fetch的https是否必须依赖于libustream-wolfssl？

**Comment by 1715173329** [comment]
> uclient-fetch的https是否必须依赖于libustream-wolfssl？

需要任意一个 libustream 库。
