### ISSUE TITLE
【使用疑问】如何批量导入黑白名单ip

### ISSUE THREAD

**Issue by MasterOfStar** [fw876/helloworld#925]
黑白名单域名可以通过访问控制的子菜单批量导入，IP却只能一个个的填，有没有能批量导入黑白名单IP的方法？
另：像*.cm.steampowered.com这类有通配符的域名，加入白名单似乎不生效，是白名单不认通配符吗？

**Comment by 1715173329** [comment]
可以自己修改 /etc/config/shadowsocksr 批量增加 ip
默认通配所有子域名
