### ISSUE TITLE
WARNING: No feed for package 'redsocks2' found

### ISSUE THREAD

**Issue by lsq726** [fw876/helloworld#928]
WARNING: Makefile 'package/feeds/helloworld/luci-app-ssr-plus/Makefile' has a dependency on 'redsocks2', which does not exist

**Comment by lsq726git** [comment]
ipt2socks
microsocks
dns2socks
又多了3个同样的错

**Comment by lsq726git** [comment]
原来下面有提示，，英文的

**Comment by 1715173329** [comment]
RTFM.
