### ISSUE TITLE
每次点保存的时候是否可以不用执行那么多操作

### ISSUE THREAD

**Issue by fengqi** [fw876/helloworld#930]
出发点是这个问题：https://github.com/fw876/helloworld/issues/917，自己尝试看代码，步骤挺多的，所以一下子看不出个所以然来，但是能发现，每次点保存，哪怕只是修改下结点名称，添加个域名，就把所有的配置全部刷一遍，是否逻辑太重了。

如果不是修改运行模式，可能很多配置都不用动，哪怕是访问控制调整了，其实可能就个别地方需要调整下。

所以是否考虑把各个地方的操作分开来，比如修改结点的，可能只需要动ss配置和小部分重启，比如只是打开或关闭自动切换，可能只是修改下定时相关的就够了。

**Comment by 1715173329** [comment]
因为 openwrt 的触发器，我们只知道配置文件被改动了，却并不知道具体是哪一条哪一项。

**Comment by 1715173329** [comment]
那程序凭借你的意念自己就可以跑了吗？
