### ISSUE TITLE
请问最新的luci-app-ssr-plus，不能正常订阅，一订阅很多正常的节点说是无效的节点，然后丢弃了

### ISSUE THREAD

**Issue by netlovehf** [fw876/helloworld#933]
请问最新的luci-app-ssr-plus，不能正常订阅，一订阅很多正常的节点说是无效的节点，然后丢弃了，以前的luci-app-ssr-plus正常的

**Comment by netlovehf** [comment]
![2424](https://user-images.githubusercontent.com/48405188/178093028-c6a77948-28d6-437b-8866-e91a99112413.jpg)

**Comment by minlang112** [comment]
问问题之前尝试自己搜索issues
https://github.com/fw876/helloworld/issues/758

**Comment by netlovehf** [comment]
> 问问题之前尝试自己搜索issues #758

关键是在ssrp+没有出现V2ray-core Selection (Include Xray-core)  --->这个LuCI 配置选项前编译的固件，同样的订阅是正常的，有了V2ray-core Selection (Include Xray-core)  --->这个LuCI 配置选项编译的固件，就出现不能订阅的情况了

**Comment by minlang112** [comment]
> > 问问题之前尝试自己搜索issues #758
> 
> 关键是在ssrp+没有出现V2ray-core Selection (Include Xray-core) --->这个LuCI 配置选项前编译的固件，同样的订阅是正常的，有了V2ray-core Selection (Include Xray-core) --->这个LuCI 配置选项编译的固件，就出现不能订阅的情况了

ssrplus 现已移除 alterId 配置项并强制启用 Vmess AEAD 认证
未启用Vmess AEAD 认证的服务器在订阅的时候会被抛弃，请联系机场客服并要求启用该认证（alterId = 0）
