### ISSUE TITLE
最新编译的 ssrp-186-5 的 GFW list 和国内IP数据库更新失败

### ISSUE THREAD

**Issue by Zeezorn** [fw876/helloworld#939]
最新编译的 ssrp-186-5 的 GFW list 和国内IP数据库更新失败
![微信截图_20220719222800](https://user-images.githubusercontent.com/31385055/179775909-d5d895d3-d413-4480-88f4-7eec8d9164d4.png)

**Comment by Zeezorn** [comment]
附件：
luci-app-ssr-plus_186-5_all.ipk
luci-i18n-ssr-plus-zh-cn_186-5_all.ipk

[luci-ssr-plus-186-5_all-20220719-v2ray-core.zip](https://github.com/fw876/helloworld/files/9142047/luci-ssr-plus-186-5_all-20220719-v2ray-core.zip)

**Comment by baodp** [comment]
我这边 正常哦

**Comment by Zeezorn** [comment]
又检查了一遍，[dns2socks] [microsocks] [ipt2socks] [redsocks2] 均已安装，数据库更新依然失败，请大佬指点，谢谢

**Comment by Zeezorn** [comment]
问题已找到，是此前 wget 替换了 uclient-fetch 造成数据库更新失败，测试了3台软路由，发现 uclient-fetch 兼容性更好一些，wget 在其中2台软路由中更新数据库失败（1台lean源码失败，1台openwrt官方源码失败，1台lean源码正常），uclient-fetch 测试3台软路由都没有数据库更新失败的情况。

**Comment by Zeezorn** [comment]
已提交请求
#940 
#941 
#942

**Comment by minlang112** [comment]
用wget替换uclient-fetch是我上次提的issues相关的，因为发现近期版本用uclient-fetch拉取https的订阅url会报错。目前我这里更新订阅url、【GFW列表】数据库、【国内IP段】数据库是正常的……我也不知道具体是什么原因囧
@@[1715173329](https://github.com/fw876/helloworld/commits?author=1715173329)

**Comment by 1715173329** [comment]
默认 uclient-fetch 会提供一个 wget 的软链接，如果你没有装 gnu-wget 的话就会自动 fallback。
建议检查下自己是不是装了一个烂的 wget-ssl 或者装了 wget-nossl。

**Comment by Zeezorn** [comment]
> 默认 uclient-fetch 会提供一个 wget 的软链接，如果你没有装 gnu-wget 的话就会自动 fallback。 建议检查下自己是不是装了一个烂的 wget-ssl 或者装了 wget-nossl。

经测试，删除 wget-nossl 包之后故障排除。
感谢天灵兄~

不过有个疑惑，为什么 wget-nossl 会干扰下载呢。。。

**Comment by 1715173329** [comment]
> 不过有个疑惑，为什么 wget-nossl 会干扰下载呢。。。

因为现在 wget 优先，wget-nossl 即代表无 ssl 支持，自然订阅失败。
