### ISSUE TITLE
更新后R2S最新版SSRPlus无法正常使用

### ISSUE THREAD

**Issue by iavgo** [fw876/helloworld#943]
如题，更新后R2S最新版SSRPlus无法正常使用，配置为 vless+ws+tls 以及 vless+tcp+xtls 都试过。在旧版本是一切都OK的，可以正常使用的。

但是新版的ssrplus无法正常使用，具体表现为，服务能显示正常启动，谷歌连通性检查OK，但是手机跟电脑均无法访问谷歌。不管是选择绕过中国大陆还是其他模式（选择MosDNS模式的话直接连通性都显示不通，其他模式虽然无法使用，但至少连通性是显示OK的）

**Comment by 1715173329** [comment]
MosDNS模式？谁改的问谁。
