### ISSUE TITLE
请教一个问题，为什么有些机场能成功订阅，connection也正常，但是就是连不到外网？

### ISSUE THREAD

**Issue by lesliedh** [fw876/helloworld#953]
小白跪求答案

**Comment by chika0801** [comment]
建议从此学自建（内容有买域名，买VPS，学LINUX操作

靠自己掌握核心技术

**Comment by frankang** [comment]
可能需要手动直接改节点信息（比如允许”不安全证书“）或者在获取订阅脚本里改一些默认的设置，订阅直接解析到的信息不一定是完整的。
