### ISSUE TITLE
openwrt 5.19内核 sagernet-core 编译不成功

### ISSUE THREAD

**Issue by xiexiaosheng** [fw876/helloworld#955]
Configuring xray-core.
Collected errors:
 * check_conflicts_for: The following packages conflict with sagernet-core:
 * check_conflicts_for:         v2ray-core * check_conflicts_for:       xray-core *
 * opkg_install_cmd: Cannot install package luci-app-ssr-plus.
 * check_conflicts_for: The following packages conflict with sagernet-core:
 * check_conflicts_for:         v2ray-core * check_conflicts_for:       xray-core *
 * opkg_install_cmd: Cannot install package sagernet-core.
make[2]: *** [package/Makefile:70: package/install] Error 255
make[2]: Leaving directory '/home/xiexiaosheng/openwrt'
make[1]: *** [package/Makefile:111: /home/xiexiaosheng/openwrt/staging_dir/target-x86_64_musl/stamp/.package_install] Error 2
make[1]: Leaving directory '/home/xiexiaosheng/openwrt'
make: *** [/home/xiexiaosheng/openwrt/include/toplevel.mk:230: world] Error 2

**Comment by hcym** [comment]
成功刷了n6005，但是没有感觉😂

**Comment by zheshifandian** [comment]
sagernet-core=v2ray+xray

**Comment by 1715173329** [comment]
核心三选一。
