### ISSUE TITLE
请求使用xray原生route路由功能，使用geosite：和geoip来进行分流

### ISSUE THREAD

**Issue by Kaze1027** [fw876/helloworld#959]
之所以提这样一个需求是因为目前的xxrp的绕开大陆ip模式有很多问题，不知道是什么原因，有一些大陆站点也会莫名其妙走代理，例如罗技中国官网：logitech.com.cn以及导购软件慢慢买APP站点：manmanbuy.com。
如果能够支持使用xray原生route功能，那么只要引用一个更新快准确率高的geosite库，就可以避免这个问题，例如`https://github.com/Loyalsoldier/v2ray-rules-dat#geositedat-1`

**Comment by 1715173329** [comment]
try passwall2

**Comment by Kaze1027** [comment]
好的，谢谢天灵大佬。
