### ISSUE TITLE
由于shadowsocks-rust不支持xchacha20-ietf-poly1305导致ssrplus redir tcp error.restart的问题

### ISSUE THREAD

**Issue by leochien0102** [fw876/helloworld#964]
机场使用了xchacha20-ietf-poly1305加密的ss服务端，当选装了shadowsocks-rust（或同时选装shadowsocks-libev）时，由于shadowsocks-rust不支持xchacha20-ietf-poly1305加密方式，
```unsupported method, `xchacha20-ietf-poly1305` is not a supported method```

而代码优先使用了shadowsocks-rust的sslocal作为主程序，
[helloworld/luci-app-ssr-plus/root/etc/init.d/shadowsocksr/#L535](https://github.com/fw876/helloworld/blob/d458c2cd49753d7f7ba9b0acdc6b1142bfb436ba/luci-app-ssr-plus/root/etc/init.d/shadowsocksr#L535)

最终导致页面显示`ShadowsocksR Plus+ 未运行`，日志提示`ssrplus redir tcp error.restart`

去掉shadowsocks-rust选装后一切正常。

目前ssrplus将shadowsocks-rust和shadowsocks-libev统一归为"Shadowsocks New Version"，但实际两者还是有些许差别，如果可以区别处理的话，可能更好一些。

**Comment by 1715173329** [comment]
xchacha20 is not standard, you should avoid using it.
It's even not supported by the official windows client.

**Comment by ylmf56** [comment]
> 机场使用了xchacha20-ietf-poly1305加密的ss服务端，当选装了shadowsocks-rust（或同时选装shadowsocks-libev）时，由于shadowsocks-rust不支持xchacha20-ietf-poly1305加密方式， `` unsupported method, `xchacha20-ietf-poly1305` is not a supported method ``
> 
> 而代码优先使用了shadowsocks-rust的sslocal作为主程序， [helloworld/luci-app-ssr-plus/root/etc/init.d/shadowsocksr/#L535](https://github.com/fw876/helloworld/blob/d458c2cd49753d7f7ba9b0acdc6b1142bfb436ba/luci-app-ssr-plus/root/etc/init.d/shadowsocksr#L535)
> 
> 最终导致页面显示`ShadowsocksR Plus+ 未运行`，日志提示`ssrplus redir tcp error.restart`
> 
> 去掉shadowsocks-rust选装后一切正常。
> 
> 目前ssrplus将shadowsocks-rust和shadowsocks-libev统一归为"Shadowsocks New Version"，但实际两者还是有些许差别，如果可以区别处理的话，可能更好一些。

确实是这样，使用XRay就能正常运行。
