### ISSUE TITLE
[Discuss] Use coredns instead dns2tcp

### ISSUE THREAD

**Issue by XiaoliChan** [fw876/helloworld#979]
As you can see, coredns has better performance and more functions than dns2tcp, also lightweight than unbound  (unbound is very hard to understand each parameter).

But the main reason why I recommend this is because it can drop IPv6 response without complex configuration.

Here is my configuration file:
```
.:5335 {
	forward . 8.8.4.4:53 8.8.8.8:53 {
		policy sequential
		force_tcp
	}
	cache 60
	template ANY AAAA {
		rcode NXDOMAIN
	}
}
```

**Comment by 1715173329** [comment]
dns2tcp only takes 13 KB on jffs2, while coredns is 13 MB.
Caching and filtering AAAA are pointless here, as dnsmasq already provides these functions.
