### ISSUE TITLE
ws tls suport

### ISSUE THREAD

**Issue by predators46** [fw876/helloworld#980]
@1715173329

can this be added by default? if I select tls websocket host does not exist, if I do not select tls websocket host exists. i see the passwall by default enable this

https://github.com/fw876/helloworld/blob/4b43ba4af7e03f75635994591191e8c81fbd8831/luci-app-ssr-plus/luasrc/model/cbi/shadowsocksr/client-config.lua#L424

**Comment by 1715173329** [comment]
idk why it is unavailable when TLS is enabled
& Idk why you set different values for tls_host and ws_host

**Comment by predators46** [comment]
i need websocket_host and tls_host. I want to use the configuration as below

```{
		"inbounds": [],
		"outbounds": [
				{
						"mux": {
								"enabled": false
						},
						"protocol": "vless",
						"settings": {
								"vnext": [
										{
												"address": "domain.com",
												"port": 443,
												"users": [
														{
																"encryption": "none",
																"flow": "",
																"id": "81f1f510-3ca7-4734-8956-0f4fce675688",
																"level": 8
														}
												]
										}
								]
						},
						"streamSettings": {
								"network": "ws",
								"security": "tls",
								"tlsSettings": {
										"allowInsecure": true,
										"serverName": "domain.com"
								},
								"wsSettings": {
										"headers": {
												"Host": "domain_server"
										},
										"path": "wss://domain.com/fastssh/zuzuio/"
								}
						},
						"tag": "VLESS"
				}
		],
		"policy": {
				"levels": {
						"8": {
								"connIdle": 300,
								"downlinkOnly": 1,
								"handshake": 4,
								"uplinkOnly": 1
						}
				}
		}
}```

**Comment by predators46** [comment]
I've tried changing as below

```o:depends({transport = "ws", tls = false})```

To

```o:depends("transport", "ws")```

Internet connection is not stable. but if i use this passwall it is very stable

**Comment by predators46** [comment]
I will close this. let me know if it's been added
