### ISSUE TITLE
Access control

### ISSUE THREAD

**Issue by predators46** [fw876/helloworld#987]
@1715173329 

access control and no interference. this problem is in openwrt 21 and 22. for the openwrt 19 version there is no problem. is there a way to fix this

![Screenshot_2022-09-20_062923](https://user-images.githubusercontent.com/31931530/191131239-1c63d2ce-7976-4f79-b3f9-348f022e14b9.jpg)

**Comment by 1715173329** [comment]
This is caused by DSA. Ask upstream openwrt for fix.
