### ISSUE TITLE
求大佬们帮解决下，感谢！xtls问题

### ISSUE THREAD

**Issue by qz87** [fw876/helloworld#990]
求大佬们帮解决下，感谢！官方openwrt21.02编译ssrp，xtls模式无法出墙，tls模式可以正常出墙，服务端也检查了，pass可以用xtls出墙，就ssrp不行，这是咋回事呢？

**Comment by chika0801** [comment]
不行就不行吧。就用TLS得了，何必浪费时间研究这个小地方了。

**Comment by 1715173329** [comment]
服务端必须支持 TLS v1.3。
