### ISSUE TITLE
请问如何才能让helloworld使用naiveproxy呀？

### ISSUE THREAD

**Issue by jmantnt** [fw876/helloworld#993]
我看helloworld选项里面没有naiveproxy，因为感觉helloworld的分流好用想使用，请问大佬谁知道怎么设置

**Comment by pangfeng161** [comment]
编译进去或者找个有naiveproxy固件

**Comment by alida008** [comment]
如何编译进去，同求

**Comment by 1715173329** [comment]
CONFIG_PACKAGE_luci-app-ssr-plus_INCLUDE_NaiveProxy=y
