### ISSUE TITLE
广告过滤功能可以过滤youtube广告么？

### ISSUE THREAD

**Issue by Arrowunner** [fw876/helloworld#997]
SSR+广告过滤功能可以过滤youtube广告么？试了内置的广告过滤列表（已更新），都不能过滤Youtube广告。或者大神们有没有SSR+兼容的广告列表链接，谢谢！！

**Comment by 1715173329** [comment]
ublock origin - adguard app - youtube premium
任何一个都比 DNS 去广告好使
